### ISSUE TITLE
Manifest canvases fail to delete due to missing method

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10029]
The manifest manager view used to have a method, `check_canvas_in_use` but it was removed. That method is still called within `delete_canvases` resulting in an error if a user tries to delete a canvas.

Here is the former method: https://github.com/archesproject/arches/commit/b3ac5284569db52596af3966b04841a2441dc678

It was removed here:
https://github.com/archesproject/arches/commit/456ab3e9b44625385778f76979f4b7cafa05260a

**Comment by jacobtylerwalls** [comment]
Fixed in #10054
