### ISSUE TITLE
Vertical Menu: Arches Designer pop out should allow scroll and navigation to branches/resource models page

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1005]
### Bug Report

see: http://recordit.co/Vszizr24fC   for visual description of bug

Desired behavior:
1. panel should avoid overwriting branch/resource model entries by supporting scroll
2. User should be able to navigate to the branches page when clicking on "Branches"
3. User should also be able to navigate to the resource models page when clicking "Resource Models"

**Comment by dwuthrich** [comment]
As an alternative to Desired behaviour #1, we can forgo listing the resource models and branches by name and just let the user jump to the branch page and resource page

**Comment by robgaston** [comment]
@dwuthrich I wired up the links as you've described, but I'm unable to reproduce the visual bug on my end; the panel resizes and scrolls nicely for me when I add many branches/resource models and/or resize the window.  Perhaps some more information is needed?

**Comment by dwuthrich** [comment]
perhaps we just remove the listing of resource models and branches in the menu.  Use case is to allow users to quickly jump to either resource models or branches from another screen

**Comment by dwuthrich** [comment]
meets requirements
