### ISSUE TITLE
Need user group permissioning for access to workflows (dev/1.0.x)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#10064]
To access the workflows, it seems like one needs to be a superuser AND member of all (or some?) of the Arches predefined groups. We should probably create a "Workflow Group" to grant access to certain users to access the workflows. 

(cc @annabelleee who may have more ideas)

**Comment by jacobtylerwalls** [comment]
Resolved at the project level in archesproject/arches-for-science#1366, other projects can consider similar solutions.
