### ISSUE TITLE
Widget: Create multi-select dropdown widget from user supplied list or function results

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1006]
The list could generated be a simple comma separated string, or from the results of a function.  
The function should be client side.  
In either case a function will be used, either by wrapping the comma separated string in a function and returning the parsed results, or by the user supplying the function itself.

**Comment by dwuthrich** [comment]
Widget does not work in graph manager UI

**Comment by dwuthrich** [comment]
meets requirements
