### ISSUE TITLE
Marking image or resource instance list nodes as required does not work

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10077]
Resource instance list and file list nodes escape validation for missing values because an empty list is not None:

https://github.com/archesproject/arches/blob/6346ab34e10e5cf2331108947e097d8285c183cc/arches/app/models/tile.py#L298

Version: 7.4
Found while testing: #10075

**Comment by chiatt** [comment]
We should make sure this problem isn't in 6.2

**Comment by jacobtylerwalls** [comment]
Affects 6.2
