### ISSUE TITLE
Resource editor raises KeyError when switching languages

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10079]
1. Enable ~the language switcher~ an additional language
2. Save a new resource ~model~ instance
3. Change to that language

```py
Internal Server Error: /resource/44490b12-feb3-4b09-977c-8b15588baea4
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/web_root/arches/arches/app/utils/decorators.py", line 82, in wrapper
    return function(request, *args, **kwargs)
  File "/web_root/arches/arches/app/views/resource.py", line 277, in get
    serialized_graph = published_graph.serialized_graph
AttributeError: 'NoneType' object has no attribute 'serialized_graph'
```

Tested with afs
Version 7.5 dev

**Comment by jacobtylerwalls** [comment]
Can still reproduce

**Comment by chrabyrd** [comment]
Can you add the steps to reproduce?

**Comment by jacobtylerwalls** [comment]
Looks like the OP was missing a step. (sorry!)

1. Publish a graph
2. Add a new language to settings.py that wasn't there before
3. Rebuild webpack and refresh
4. Create an instance of that graph
5. Switch to the language you added in step 2


Now it strikes me that the problem goes away if I run `manage.py graph publish --update` after adding the new language. If this is a requirement, we should document it, I figure?

I'll also update the traceback, which is a little different now.

**Comment by jacobtylerwalls** [comment]
Looks like I was a little confused about whether the error emanated from the graph designer or the resource instance editor. Looks like it's only emanating from the latter now. I'll retitle.

**Comment by chrabyrd** [comment]
> Looks like the OP was missing a step. (sorry!)
> 
> 1. Publish a graph
> 2. Add a new language to settings.py that wasn't there before
> 3. Rebuild webpack and refresh
> 4. Create an instance of that graph
> 5. Switch to the language you added in step 2
> 
> Now it strikes me that the problem goes away if I run `manage.py graph publish --update` after adding the new language. If this is a requirement, we should document it, I figure?
> 
> I'll also update the traceback, which is a little different now.

No worries!

The `Graph.publish` command iterates `settings.LANGUAGES` and not the languages table so there's not really anything to hang a trigger onto. Also automatically triggering a serialized save could result in unpredictable behavior. So yeah this looks to be a documentation issue. Alternatively I'm going to put a small timebox on this and investigate how easy it would be to gracefully fall back to the un-serialized graph.

**Comment by jacobtylerwalls** [comment]
Nice. In terms of documentation, I bet you could throw a system check from the `PublishedGraph` class that tells you to run the update command if you're missing publications for some language. There's a little example [here](https://docs.djangoproject.com/en/4.2/topics/checks/#field-model-manager-and-database-checks). Then you wouldn't even be able to runserver if you end up in this situation.

**Comment by chrabyrd** [comment]
@jacobtylerwalls  I've assigned a PR to you here https://github.com/archesproject/arches/pull/10652 that should address the issue. 

Unfortunately I couldn't override the `check` attr on models without making it a class method, and as a class method we can't check any specifics about the actual graph. This worked locally for me and hopefully it should work on yours as well but let me know. I also removed the `raise_if_missing` arg since with this change there isn't a conceivable way to accidentally have an unpublished graph ( as far as I know ). However if it needs to be re-added please let me know.
