### ISSUE TITLE
Widget: Create single-select dropdown widget from user supplied list or function results

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1007]
see #1006 for details

**Comment by dwuthrich** [comment]
Widget does not function in the graph manager UI.

**Comment by robgaston** [comment]
@dwuthrich can you please add more detail?

**Comment by dwuthrich** [comment]
Adding values in for the widget in the graph UI does not persist to the widget in the card manager

**Comment by robgaston** [comment]
@dwuthrich I think it is possible that what you are seeing is a result of this bug (I'm working on this now): https://github.com/archesproject/arches/issues/1011

let's take a look again after that's resolved.

**Comment by robgaston** [comment]
@dwuthrich okay, I think this is resolved now (also #1006) based on my work on #1011

**Comment by dwuthrich** [comment]
meets requirements
