### ISSUE TITLE
Search term-filter should include exact matches for resource displaynames

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#10090]
This could be classified as either a bug or a feature enhancement.

Use Case:
A user is typing a search term in Search and receives a list of dropdown terms from which to select. Should a user select a term displaying a node value alongside the name of the node/nodegroup, this term-filter is applied. However, when the term-filter is applied, it still gets treated more or less as a search term. 
![Screen Shot 2023-09-28 at 5 23 15 PM](https://github.com/archesproject/arches/assets/8366985/c8c4c4c9-630d-480c-aa48-ae666daff702)

The expected behavior is that a resourceinstance-specific value is presented in the dropdown and thus only that resource instance should show up in the search query results.
![Screen Shot 2023-09-28 at 5 04 02 PM](https://github.com/archesproject/arches/assets/8366985/91d7bb03-3cdf-43ca-b605-9563b0739f20)

The search-term objects that get sent to the frontend via the search method ``search_terms`` should be able to get the ``resourceinstanceid`` associated with the node value since it is present in the ``terms`` index.

**Comment by apeters** [comment]
To clarify, the underlying issue that @whatisgalen is trying to fix is that users might expect to get an exact match to a single resource instance when selecting an item from the "Term Search" dropdown.  Right now those terms in the dropdown are really only used as suggestions.

<img width="388" alt="Screenshot 2023-09-29 at 1 07 51 PM" src="https://github.com/archesproject/arches/assets/823773/4329a1fe-5de5-4d37-aced-31713d835632">


After a conversation with both @whatisgalen and @chiatt about this ticket and [associated PR](https://github.com/archesproject/arches/pull/10094) 
what might be nice to have would several things:
1. A separate tab (bucket) in the term search dropdown that explicitly highlights "exact resource instance" matches
2. Renaming "Term Matches" to "Suggested Searches"
3. Removing the context section (text in parenthesis) of the term suggestions 
4. Only showing the "Concepts" tab to logged in, and presumably more advanced, users

**Comment by whatisgalen** [comment]
Following conversation about the intial PR's associated with this issue, it was agreed that something ideal would be a new category of search term dropdown, i.e. "Exact Matches". 

(Incidentally, it was also mentioned that the label "Term Matches" should be something like "Term Suggestions" so as not to mislead the user in thinking that some logic specific to that node or its value would be applied.)

Therefore I have removed the "bug" label and will rename the issue to fit the description of a more ideal solution in PR #10102

**Comment by whatisgalen** [comment]
From @apeters on PR #10102:

> 
> 1. Terms that show up in the dropdown have a contextual bit in parenthesis that can add more confusion then help about what is actually being searched, or even what might be returned from a search.  ie, since the model name is shown one might assume that only instances of that type will be returned, which is not the case
> 2. Maybe more importantly, search results aren't scored, and therefore ordered, in way that that the most relevant results are at the top.  For example if the name of a resource happens to match a simple string in another resource, then those two resources will get the same score.  One would (correctly) assume that the resource that matched on the display name would receive a higher score and therefore show up nearer (or at) the top of the search results.
> 


It seems like issue 2 might have already been addressed, given that testing with this:
```
boolquery.must(Match(field="displayname.value", query=searchString.lower(), fuzziness=2, boost=2))
```
...in `search_terms` doesn't yield a noticeable difference in search order. I could be wrong, based on my dataset.

However issue 1 is still at large: when a suggested term indicates a match on display name, the search still includes any match in the entire document body, display name or not. To me this still feels counterintuitive given the context label's suggestion, i.e. "Did you want *this* resource?"

I still think there's a strong case to be made for facilitating some kind of an exact match on either displayname or a particular node value matching the string entered.

For example when a context label says "Resource Type - District", including any result that mentions the word "District" is excessively noisy when the user expects that the result set will contain documents whose *Resource Type equals 'District'*. Philosophically, we shouldn't ask users to learn a counterintuitive UX. We should make the UX conform to what already feels intuitive if we can, and in this case it could be accomplished thus:

An idea would be to update both the frontend and backend like so:
- Indicate at the very top of the term dropdown "*Contains term:* [raw term value]" (because that's literally what it would do)
- In the context label, indicate "Filter where [NodeName or DisplayName]  = '[term match value]'
- On the backend, *only do term matching if the user selected the "contains word" term*, otherwise if they selected a "term" with a context label, make the search either graph-node-specific or nodename-datatype-specific (assuming multiple graphs share common node names for common purpose, e.g. "Name Type")

### What would this Accomplish?
The aforementioned UX would make the Term Filter as useful as the Advanced Filter but without the learning curve. It would also feel intuitive: Either search for docments "containing word", or else search for documents "matching value". These are the two existing use cases for both "Terms" and "Concepts", except with the UX presented herein, we could elimate the "Concepts" tab altogether, reducing clutter and one more element of Arches UX to learn.
