### ISSUE TITLE
Running command `python manage.py packages` defaults to resetting database

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#10103]
**Arches Version/Branch:** All versions.

**Describe the bug:**
When running the command `python manage.py packages` (with nothing after and no `-o` flag) the default action is to run the setup_db function.
Potentially caused by this line: https://github.com/archesproject/arches/blob/6346ab34e10e5cf2331108947e097d8285c183cc/arches/management/commands/packages.py#L82C1-L82C29 as changing it to a different function runs the changed one.

The intended outcome should be to show the same help message as when running `python manage.py packages -o`.

**Example**
```
(env) samuel@DESKTOP:~/testing/v7test/v7test$ python manage.py packages
operation: setup
Drop and recreate the database...

SELECT pg_terminate_backend(pid) FROM pg_stat_activity
    WHERE datname IN ('v7test', 'template_postgis');

DROP DATABASE IF EXISTS v7test;

CREATE DATABASE v7test
    WITH OWNER = postgres
        ENCODING = 'UTF8'
        CONNECTION LIMIT=-1
        TEMPLATE = template_postgis;

deleting index : v7test_terms
... 
```

**Comment by jacobtylerwalls** [comment]
Fixed in #10577
