### ISSUE TITLE
Replace arches-django-revproxy with django-revproxy

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10117]
We were using a fork of django-revproxy because v0.11 of django-revproxy was not published on pypi. Now v0.11 is available, we can switch back to the official django-revproxy release.

https://github.com/jazzband/django-revproxy/issues/144
https://pypi.org/project/django-revproxy/0.11.0/

**Comment by jacobtylerwalls** [comment]
Fixed in #10327
