### ISSUE TITLE
Graph Manager: `cards_x_nodes_x_widgets` records not copied when a graph is copied (including append branch)

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1011]
`cards_x_nodes_x_widgets` records are not copied into resource models from a source branch on append.

Append operations (and moreover, all graph clones) should include `cards_x_nodes_x_widgets` records in addition to the `cards` records already being included.

**Comment by dwuthrich** [comment]
Adding a card to a resource does not respect the cardinality of the card.  For example, add a card container with a card that has cardinality of n to a resource.  Notice that when managing the card from the resource model that the card no longer has cardinality of n.

**Comment by robgaston** [comment]
@dwuthrich #1095 should fix the issue that you've mentioned here.

**Comment by robgaston** [comment]
(also, the above mentioned issue has it's own ticket: #862)
