### ISSUE TITLE
Polish i18n logic

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#10121]
Currently there are a few areas that deal with i18n and could use a little polish:

- When a project is created it creates several `Language` database objects. Instead it should either create no objects or just the `en` language object.
- There appears to be an `en-US` language object as well as an `en-us` language object.
- `translation.get_language()` returns a lowercase language code. We should check all call sites to ensure this logic is handled for
- Currently `PublishedGraph` objects have a foreign key to the `Language` table. It may be preferable to instead turn this into a text field so a user could select languages they'd want to update the UI with but not necessarily collect data with.

There may be other items to add to this list. If you have any questions please reach out to me or @apeters

**Comment by jacobtylerwalls** [comment]
After we deduplicate en-US from en-us, we'll still have that one, plus "en". We should distinguish their labels in the "name" column so they don't look like duplicates in the UI.

**Comment by chiatt** [comment]
I think we should just get rid of 'en-us'  and 'en-US' altogether and just use 'en'.

**Comment by chrabyrd** [comment]
> I think we should just get rid of 'en-us' and 'en-US' altogether and just use 'en'.

@chiatt are you saying we should drop support for regionalization?

**Comment by chiatt** [comment]
If admins want to use 'en-us' they can always add it themselves, or en-gb or en-ca.

**Comment by chrabyrd** [comment]
oh cool, that works. My misunderstanding

**Comment by jacobtylerwalls** [comment]
Will open a new issue for the 3rd and 4th bullet points

**Comment by jacobtylerwalls** [comment]
Items 1 and 2 fixed in #10777. Items 3 and 4 broken out into #10892.
