### ISSUE TITLE
Resource results show as provisional when resource does not exist

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10130]
If a resource is indexed, but there is no resource in the database, the search result will appear in search as provisional. Ideally there wouldn't be any indexed instances without a corresponding instance in postgres, but when it happens we can hopefully indicate that in the search results rather than leaving users confused about the presence of provisional instances.
![image](https://github.com/archesproject/arches/assets/1877663/318f3ce4-e1c3-4676-bc7d-4235d50c0daa)

**Comment by chiatt** [comment]
@chrabyrd Looked into this issue and found that this state doesn't occur if a resource is manually deleted. It only seems to occur as a side effect of the failure of an afs workflow. It's not clear which one or what kind of failure is needed to reproduce.

**Comment by chiatt** [comment]
This issue is caused by changing an empty tile from {} to a tile with all nodeids as keys with a value of 'None' [done here](https://github.com/archesproject/arches/pull/9704). This changed how we assign the provisional property to a resource instance document.

**Comment by jacobtylerwalls** [comment]
Fixed in #10179
