### ISSUE TITLE
Enable customisation (branding) of emails

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#10139]
As part of the Keystone project (based on Arches 6.1.x) we were required to find a method through which emails could be branded.

This not only required custom templates to be produced but also some alterations made to the core code to enable the production of these custom emails.  See the following pull requests to the Historic England forks to see what was changed:

Arches: https://github.com/HistoricEngland/arches/pull/252/files
Arches-her: https://github.com/HistoricEngland/arches-her/pull/288/files

We'd like to feed this ability to customisation back to the core Arches and Arches-her repos for version 7.5.x.  

Would our current methodology be acceptable or are there some changes that need to be made before this can happen?

**Comment by chiatt** [comment]
@csmith-he I think this looks like a good approach. @robgaston, @apeters What do you think? If you are both ok with the general approach, I'd say @csmith-he should submit a PR against core and then we can make any necessary refinements from there.
