### ISSUE TITLE
Error in RI widget if graphid not in graph lookup

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10151]
If a resource instance node is configured without any graphs (allowing a relationship with an instance of any resource type) the widget can fail when looking up the iconclass of the target graph. This is a symptom of a larger issue, however, in the meantime if the graph is undefined, we should not try to get its iconclass.

![image](https://github.com/archesproject/arches/assets/1877663/1db3cde8-42e9-41b5-a046-0618fb81d38d)

**Comment by jacobtylerwalls** [comment]
Fixed in #10152 in 6.2
and e5eed8054c9b6b0d3edcdb574a3edd7710106d03 in 7.4
