### ISSUE TITLE
"arches-project create" command throws an error if a project of the same name already exists

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#10166]
The error thrown is this
```
AttributeError: 'ArchesCommand' object has no attribute 'a_or_an'
```

It should instead show a message explaining the issue.

**Comment by jacobtylerwalls** [comment]
Hey @apeters I think this is #10018

**Comment by jacobtylerwalls** [comment]
Or at least somewhat similar :-)

**Comment by apeters** [comment]
@jacobtylerwalls It's definitely similar, but different.  #10018 deals with invalid names, this ticket deals with duplicate names and throws a slightly different error and will require a different fix.

**Comment by jacobtylerwalls** [comment]
Duplicate of #10759

**Comment by apeters** [comment]
> Duplicate of #10759

I swear I searched for "a_or_an" and found nothing before I wrote #10759 🙏
