### ISSUE TITLE
Race condition in concept-select.js

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#10162]
There's a bug in project statements.  It appears to be related to concepts.  

1.) Create a new project with the new project workflow.  Add a statement in step 2.
2) View this project resource in the UI.  Click on "Statement About Project". You'll see 
```
Cannot read properties of null (reading 'find')
TypeError: Cannot read properties of null (reading 'find')
```

**Comment by chrabyrd** [comment]
resolved in #10163
