### ISSUE TITLE
Workflow completed status remains false after save

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10182]
If a user completes a workflow and clicks 'save and complete workflow', the workflow's 'complete' value remains 'false' in the database.

**Comment by jacobtylerwalls** [comment]
@chrabyrd Hey, just looked at this with Cyrus and he couldn't reproduce after hard refreshing. I think this was just #10157

**Comment by chrabyrd** [comment]
oh nice

**Comment by chiatt** [comment]
Sorry for the false alarm @chrabyrd
