### ISSUE TITLE
Adv. search labels are not read out for selectwoo dropdowns

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#10190]
The initial dropdown for each facet in advanced search just reads out the text "Search Criteria" rather than the card label associated with the search facet.

<img width="334" alt="Screenshot 2023-10-24 at 2 07 08 PM" src="https://github.com/archesproject/arches/assets/823773/a4b0a885-df0a-41e6-9d91-6b8abd22d50e">

**Comment by johnatawnclementawn** [comment]
Resolved in #10192
