### ISSUE TITLE
Webpack resolve issue if ROOT_DIR is a sub-path of a symlink

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#10234]
If the `ROOT_DIR` is within a path that contains a symlink directory, resource resolve fails as the absolute (real) path is different than the symlink path.

For example, in our system, the venv directory is `/fs/u02/apps_ux/apps_dlvr/venv`. However there is an `/apps_ux/` -> `/fs/u02/apps_ux/` symlink in the root that causes line 366 in `webpack/webpack.common.js` to not match:
`  templatePath = resourcePath.split(APP_ROOT)[1];`

An example of this mismatch in our case is as follows:

```
ROOT_DIR: /apps_ux/apps_dlvr/bcrhp_dlvr_venv/lib64/python3.9/site-packages/arches
Resource:  /fs/u02/apps_ux/apps_dlvr/bcrhp_dlvr_venv/lib/python3.9/site-packages/arches/app/templates/views/components/cards/related-resources-map.htm
```

Resolving all paths to the real (full path) should fix this issue (eg `os.path.realpath(ROOT_DIR)`).

**Comment by jacobtylerwalls** [comment]
Fixed in #10236
