### ISSUE TITLE
Time Filter, Saved Searches, Export Saved Searches - 1.1.1 Non-Text Content - Time Filter, Saved Searches and Export Search Results graphics do not have labels which appear on hover

### ISSUE THREAD

**Issue by imogenroberts** [archesproject/arches#10251]
As a user who struggles to put graphical representations into context, I expect all non-text content (i.e. graphical buttons) to have a textual alternative, and for the manner in which this is done to match that given for other graphical buttons in the page.

**Linked work item:**
#9500 

**Expected Result:**
The graphic buttons above, (Login, Notifications and Help) all have labels which appear when the user hovers over them to give the user a textual description of the button. The graphical buttons for the Time Filter, Saved Searches and Export Saved Searches panels should also exhibit this behaviour on hover.

**Actual Result:**
The Time Filter, Saved Searches or Export Search Results do not have textual alternatives provided on mouse hover/keyboard focus and therefore give the user no context on the button's purpose before the panel is opened.

**Evidence:**

https://github.com/archesproject/arches/assets/77161085/9523c5aa-4ce4-428e-86c6-380a0fe5709c

**Comment by johnatawnclementawn** [comment]
@imogenroberts, please pull latest and RETEST - resolved in #10255

**Comment by imogenroberts** [comment]
RETEST: The Time Filter, Saved Searches and Export Saved Searches buttons now all have labels which appear on hover, and which match the behaviour of the graphical buttons above (login, notifications, etc.)

**Evidence:**


![Image](https://github.com/archesproject/arches/assets/77161085/d1fa11c3-b264-4705-8ee3-361b341e8f40)
