### ISSUE TITLE
User Friendly "Request Failed" Message on an EDTF Search Field

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10250]
Whenever a number or date is used as a search value on an EDTF field, an error shows up:
![image](https://github.com/archesproject/arches/assets/150346658/12f565b9-fb2a-47e8-ab18-d54bbe3b98d7)

however, the message doesn't contain anything for the user to know what the issue is or what has went wrong.

Could this be populated  please so that users are aware of the error?

**Comment by chiatt** [comment]
@JPdelaRosa83 What version of Arches are you using?

**Comment by JPdelaRosa83** [comment]
hi @chiatt our version is on 7.4.2

**Comment by johnatawnclementawn** [comment]
Resolved in #10309
