### ISSUE TITLE
`FUNCTION_LOCATIONS`, `ETL_MODULE_LOCATIONS`, etc don't account for arches applications

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10288]
dev/7.5.x

1. Create an arches application with a function at pkg/extensions/functions/foo.py
2. Create an app that installs app 1 as an arches application
3. Plugin will be registered to app2's db, but will never be found at runtime without manipulating app2's FUNCTION_LOCATIONS to include `app1.pkg.extensions.functions`.

Suggesting an enhancement where whatever reads from `FUNCTION_LOCATIONS` is smart enough to get the function from the installed arches applications (probably discovering in whatever order the apps are defined in `ARCHES_APPLICATIONS`) instead of requiring additional configuration in app2.

Probably affects these also, but haven't checked:
- DATATYPE_LOCATIONS
- ETL_MODULE_LOCATIONS
- SEARCH_COMPONENT_LOCATIONS

**Comment by chiatt** [comment]
This change would probably need to be made to `arches/app/utils/module_importer.py`

**Comment by jacobtylerwalls** [comment]
@robgaston FYI this came up last week with @johnatawnclementawn and just now with @aarongundel.

**Comment by jacobtylerwalls** [comment]
Fixed in #10613
