### ISSUE TITLE
Adding Geometry Data to Resource won't update in Search Map

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10287]
On Arches v 7.4.2
We are using the Spatial View function of Arches to send data to our GeoMaps system and found that when we create a new resource that has a geospatial coordinate that this resource/record doesn’t show up in the Spatial View that we created. We have also discovered that it is not showing in the Search Map
Found that this resources with geospatial coordinate don't get created with a record in the geojson_geometry which previous version did.

as an example, this new resource has a polygon as a coordinate
![image](https://github.com/archesproject/arches/assets/150346658/cd34aa35-3849-4b07-bf5b-6634731df52b)
none created in postgres table geojson_geometry
![image](https://github.com/archesproject/arches/assets/150346658/d2a0c79e-7828-4be4-8baa-191cb30c66d3)

was able to force the geojson_geometries table to refresh using SELECT * FROM refresh_geojson_geometries(); and once it appears in the table, refresh the spatial views using SELECT __arches_refresh_spatial_views();

**Comment by chiatt** [comment]
I have to test 7.4, but this doesn't appear to be a bug in 7.5. Are you creating new geometries using the resource editor?

**Comment by JPdelaRosa83** [comment]
hi, yes, that is correct - creating new geometries using the resource editor:
![image](https://github.com/archesproject/arches/assets/150346658/62022b08-4477-422a-b186-0e7c3a995fe6)
