### ISSUE TITLE
Time Wheel Function - Zoom In/Out Capability

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10293]
Hi Team,

I am reporting a potential bug for the Time Wheel functionality in 7.4.2 (I also tested this function in 7.4.0) as it is not doing as per the instructions on the label which is when double-click it should zoom in or out

This is our Test environment for Arches in version 7.4.2 - which shows the bug as when I click the Time Wheel, it just filters it but not zooming in/out
[screen-capture.webm](https://github.com/archesproject/arches/assets/150346658/5db30272-328f-427c-9baa-6be4694e30fe)

This second video is from Arches demo page which shows how the Time Wheel function should work
[screen-capture (1).webm](https://github.com/archesproject/arches/assets/150346658/b01f01e8-a579-4ea9-9ad2-dd4750f02946)

**Comment by chiatt** [comment]
This error occurs when double clicking:
![image](https://github.com/archesproject/arches/assets/1877663/5a0631da-8d62-4556-8512-fbdaf88f8651)

**Comment by johnatawnclementawn** [comment]
Resolved in #10324
