### ISSUE TITLE
Time Wheel - Date Picker

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10294]
Hi Team,

Reporting another bug for the Time Wheel function on 7.4.2 version of Arches. The date picker, when changing to the Yearly scroll, the months somehow disappear
 
![image](https://github.com/archesproject/arches/assets/150346658/c43f2590-f7b7-48fb-975e-affd4c8aedd1)

So users cannot choose a specific date when using the Date picker

**Comment by chiatt** [comment]
Duplicate of #9060
