### ISSUE TITLE
Bulk Data Manager: Import Single CSV - Nested Nodegroups excluded

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#10369]
A Resource Model was imported without any errors. When attempting to use the Bulk Data Manager "Import Single CSV" module, not all nodes were available in the dropdown list. It's unclear why this would be the case so it's most likely a bug. See images below:

Known Node "Spatial Coordinates Geometry"
![Screen Shot 2023-12-07 at 1 15 22 PM](https://github.com/archesproject/arches/assets/8366985/2fa69fc6-9d8d-4739-b34a-6a87f01e6bb8)

Unable to find Node (by node_alias or any other name)
![Screen Shot 2023-12-07 at 1 14 49 PM](https://github.com/archesproject/arches/assets/8366985/3a6c125c-37b0-4f03-82b6-503408866efe)

I haven't seen this before until I *imported* a Resource Model. The node aliases all seem intact but perhaps there's a flaw in the import process?

**Comment by whatisgalen** [comment]
Just confirmed that deleting the example node and recreating it as the child of "Place" makes the node alias show up in the dropdown list of the CSV import module. This suggests that there is some issue specific to importing resource models vs creating them.

**Comment by chiatt** [comment]
Probably not a bug, but a documentation issue. It looks like the node you want to import is nested. Only top nodes can be imported using Single CSV. If you have more complex data to import, you have to use branch or tile excel.

**Comment by whatisgalen** [comment]
@chiatt thanks yea I just saw the logic regarding filtering nodes. I see that if a Node is part of a top nodegroup, it's included. When I recreated my node in my test, I didn't make it its own nodegroup this time which is why it is showing up now.  Just curious what the motivation was to exclude nested nodegroups?
