### ISSUE TITLE
[VGM] Search shows the same concepts in a list multiple times, why?

### ISSUE THREAD

**Issue by MarcusDPRoling** [archesproject/arches#10387]
In our test instance of AfS we have recorded paintings as physical things with a "Type of Object" with "Type= paintings (visual works)". When searching for "painting" in the search box, we see in the "Concepts" tab a list of "Top Concepts" with some entries in multiple rows (see image attched). Why is that? I expect only the concepts that actually have an entry, and only one line per concept in this list.

In this example the following is shown:
a. painting (image-making) (Top Concept), shown 4 times
b. painting techniques (Top Concept), shown 2 times
c. paintings (visual works) (Top Concept), shown once
d. acrylic painting (technique) (Top Concept) (WHY IS THIS SHOWN, no data has been entered for it?)
e. oil painting (technique) (Top Concept) (idem)
f. watercolor painting (technique) (Top Concept) (idem)
![Issue_SearchPainting_ConceptList_20231206](https://github.com/archesproject/arches-for-science/assets/134408250/69d2d6c5-da54-4347-845d-30644a8a5785)

**Comment by jacobtylerwalls** [comment]
Fixed in https://github.com/archesproject/arches-for-science/pull/1514
