### ISSUE TITLE
EXPORT_DATA_FIELDS_IN_CARD_ORDER = True doesn't work for data model with records large than 2000 records 

### ISSUE THREAD

**Issue by storynana** [archesproject/arches#10392]
HI, there;
     We are on Version 7.4.3. What we found is that we can export data records <=2000 with EXPORT_DATA_FIELDS_IN_CARD_ORDER turned on, columns are ordered by the card order properly. 
    But if we export data records >2000, the columns are NOT ordered by the card order any more.
  
Cheers,
Qiuwei

**Comment by johnatawnclementawn** [comment]
This was a project specific bug
