### ISSUE TITLE
Broken link in contributing guidelines

### ISSUE THREAD

**Issue by ErnstBas** [archesproject/arches#10393]
There is a broken link in the *contributing guidelines*  when clicking on the link for setting up a development environment.   `404 not found` is returned for this link: https://arches.readthedocs.io/en/latest/creating-a-development-environment/

In the documentation, I found this other link for the stable version: https://arches.readthedocs.io/en/stable/developing/getting-started/creating-a-development-environment/

If this link is correct, I can submit a PR with an updated file CONTRIBUTING.md

Cheers.

**Comment by jacobtylerwalls** [comment]
Thanks, PR would be welcome!
