### ISSUE TITLE
Empty string node not handled in Map Header Template

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10429]
Currently on Arches 7.4.3 and found that whenever we are updating an existing Geospatial Coordinates on the resource, it just goes to a white screen of death.
![image](https://github.com/archesproject/arches/assets/150346658/5a412db2-83a0-4685-aa3a-3f98be036a1f)

I have also did an inspect on the web browser and this is what the errors are
![image](https://github.com/archesproject/arches/assets/150346658/b0551e2f-3436-4594-952c-7b7e5d6fe484)

To Reproduce:
1. Create a model with a node group with geojson node and string children nodes, this model should use the **map header report template**. 
2. Create a new resource for that model and create a geometry, but leave the string node blank
3. Leave the editor, then return to the edit this resource.
4. Make a change to the geometry, but maintain the string node as blank
5. ** If data entered into string node, UI is not blocked **

**Comment by jacobtylerwalls** [comment]
Fixed in #10473
