### ISSUE TITLE
z-index issue: When Adding Geometry, The Edit toolbar is still visible when opening the Help Option

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10432]
Hi Team,
Currently running 7.4.3 version but have noticed this on previous version too:

The EDIT toolbar seems to be visible when the HELP option has been toggled On.
![image](https://github.com/archesproject/arches/assets/150346658/7dd55ae3-12f2-4213-bf77-5c1b6519cdf2)

**Comment by jacobtylerwalls** [comment]
For implementers: check very similar issue #10404

**Comment by johnatawnclementawn** [comment]
Resolved in #10475
