### ISSUE TITLE
Description on Rich-Text format is having issues when other Language is selected

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10468]
Hi Team,

We have been testing the changing of language function in Arches on 7.5 (installed on my local dev machine) and 7.4.3 on our Test servers and found that when a Description field is set to Rich-Text format and selecting a new language besides English (en), when typing, the text seems to be disappearing or deleting itself.

Been difficult to replicate but found that when there is already a Description saved on English (en) format then add a new description and select a new language, that is when the problem shows up.
Here's a video showing the steps:
[screen-capture.webm](https://github.com/archesproject/arches/assets/150346658/5a760200-5da8-491e-a0b9-7377236c16dd)

**Comment by chiatt** [comment]
This only seems to occur when `ACCESSIBILITY_MODE = True`

**Comment by jacobtylerwalls** [comment]
I was having trouble getting the rich-text widget selected at all due to #10471, but I can reproduce now (and without ACCESSIBILITY_MODE on, either).
