### ISSUE TITLE
Workflow steps aren't locked when reopening workflow

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#10505]
When reopening a workflow with locked steps that has been closed, those steps do not continue to be locked.  The "lock" command is issued in individual steps, so if the workflow opens on the first step (instead of a step with the lock command in it) - lockable steps are unlocked.  

To replicate:  
1) Start XY upload workflow in AfS
2) Fill workflow through Data Files and Location step
3) Go back to "Project Info" - note that it is locked.
4) close the workflow
5) go back to init workflow and select the workflow you just closed
6) Go to "Project Info" - it is unlocked.

**Comment by jacobtylerwalls** [comment]
> workflows need to save the lock status to the database

This is already supported FYI, but there surely is a bug at one layer or the other!

**Comment by aarongundel** [comment]
That is good to know @jacobtylerwalls - I will pick this up and see if I can track down where it's failing.
