### ISSUE TITLE
Arches Designer: Order Branches and Resource Models

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1052]
### User Story

As a graph designer, it would be nice if the resource models and branches were ordered in a specific logical order so that each respective resource model or branch is easier find in cases where there are many of them on the page.  The easiest/most obvious thing would be to just auto-order alphabetically by name.  It might be a nicety to have ability for user to sort on name and date/time of creation or editing.

**Comment by apeters** [comment]
Graphs are now sorted alphabetically as of this fix #1119.  Can I close this?

**Comment by apeters** [comment]
I'm going to close this for now.  We can reopen if ordering by name isn't sufficient.
