### ISSUE TITLE
Abnormal behavior with language switcher

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#10542]
This ticket is to address the following forum post, the contents of which I have copied below: https://community.archesproject.org/t/language-selection-when-adding-resource/2204

Currently running 7.5.0 on my local development machine and on 7.4.3 on our Test environments.

So whenever we are adding other language besides english (en to be specific) in Edit Mode, the text only shows up when that Language is selected and when saving it, it doesn’t show up in the list as per screen shot:

![](https://global.discourse-cdn.com/standard17/uploads/archesproject/original/2X/b/bac87559dc345e16036700e61e04c2a2b3d6cd66.png)

And when we try to update it, it reverts back to English (en)

![](https://global.discourse-cdn.com/standard17/uploads/archesproject/original/2X/d/d345e1efeb7e53b8cc083877e22472ecd53a21be.png)

Also another unusual behavior that we noticed is that when we select a language other than ‘English (en)’, when adding a new name to an existing resource instance, we cannot type anything into the field as [object Object] shows up

![](https://global.discourse-cdn.com/standard17/uploads/archesproject/original/2X/f/fe996e565dc96ae22bbf89bc4e19082b9e863842.png)

**Comment by jacobtylerwalls** [comment]
@ryan86 is the situation improved as of #10483?
