### ISSUE TITLE
Python modules inside of Arches Applications are not imported

### ISSUE THREAD

**Issue by johnatawnclementawn** [archesproject/arches#10565]
Python modules inside of Arches Applications should be added to the path so they can be used.

I'm building an [ETL module for the Arches RDM application](https://github.com/archesproject/arches-rdm/issues/2), and was experiencing an issue in which the ETL module that I wrote, which lived in the application directory rather than the core directory, was not being imported. The issue presented itself [here](https://github.com/archesproject/arches/blob/a1c2b429f5aaa54af95a4111862eb87d56709107/arches/app/views/etl_manager.py#L179).

**Comment by jacobtylerwalls** [comment]
Bothered Johnathan about this briefly. We had trouble reproducing the issue so long as we had `arches_rdm.etl_modules` included in `settings.ETL_MODULE_LOCATIONS`.

The proposal that you shouldn't _have_ to do that is captured in #10288.

**Comment by johnatawnclementawn** [comment]
Can be fixed by ensuring `arches_rdm.etl_modules` is appended to `ETL_MODULE_LOCATIONS` in `settings.py`
