### ISSUE TITLE
Map widget tyling bug in Report config

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#10579]
See video below:

https://github.com/archesproject/arches/assets/8366985/47a3533c-c756-4b07-8b91-20cbf2e5a7ff

**Comment by jacobtylerwalls** [comment]
Hey @whatisgalen this is supposedly fixed in #10475 -- can you let us know on which commit hash you reproduced this? And is it only in reports?

**Comment by whatisgalen** [comment]
> Hey @whatisgalen this is supposedly fixed in #10475 -- can you let us know on which commit hash you reproduced this? And is it only in reports?

Ok that's good to know. `stable/7.5.0` predates that commit you referenced; it should probably be added to `7.5.x` etc. if it hasn't already
