### ISSUE TITLE
Plugins can't be edited in the Django admin

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10597]
After `Plugin.name` was localized in #10517, you can no longer use the Django admin to edit a plugin. The non-localized name will load in the form, and then saving the form throws "Enter a valid JSON" when saving the field.

Workaround is to hand-edit the name to look like localized JSON again.

Could block people from using the Django admin to set `{"show": True}` in the config field.

Version: 7.6 dev

**Comment by johnatawnclementawn** [comment]
+1

**Comment by johnatawnclementawn** [comment]
This appears to be related to #9794 - Somewhere in the line of converting back and forth between json and strings, the double quotes around the value are dropped when being supplied to the django admin. It could be related to how we're overriding `_parse` on both I18n_JSONFields & I18n_TextFields, made worse by upgrade to Django 4.2
