### ISSUE TITLE
Import: how to handle graphs w/o card data

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1060]
A graph that does not have card data associated with it does bad things to the application.

The application prevents a user from creating such a graph, but what about import...

if a user imports a branch/resource model w/o associated card data, how should the system handle this?

I see two obvious paths:
1. Throw an exception and prevent the import of the graph
2. Create default card records for each node group

**Comment by robgaston** [comment]
Personally, I am leaning towards 2.  I think that it would be easy to do and would make import more useful if a user wanted to venture to create a graph JSON using some other client.

**Comment by ryan86** [comment]
I'm leaning towards 1. I think because this is never an expected condition in the data if it's exported from arches it should be a validation. I also think we should minimize the amount of data we create for a user on import.

**Comment by apeters** [comment]
I can't even create a graph w/o card data in it.  @robgaston were you editing the json after export?  
What I did to test this was to create a branch and append the node/node_type branch to it.  I then exported the branch and re-imported it.  Everything seemed to work as expected.

**Comment by robgaston** [comment]
@apeters that's right, the system (as mentioned in the original description) doesn't allow you to export graphs w/o card data any longer, but, previously, we didn't export card information w/ our graph data.  Therefore, people had .json files that they had exported with that older version of the code that didn't include card information.  

The question, in my mind, remains: how should import handle .json files (like this example) that are problematic for the system at large (regardless of the origin of that .json file)?

I would argue that if importing the .json file causes the application to break (as this example does), we should either: 

1. prevent a user from importing that file [throw an exception] or...

1. ensure that the data being imported won't break the system [in this example, create default card records for each node group]

**Comment by apeters** [comment]
I agree that we need to handle for this.  In this case simply throwing a meaningful and detailed error seems sufficient.  Arches.json is really meant to be an internal transfer format and it would be very difficult to "fix" any errors effectively and safely during import.

**Comment by ryan86** [comment]
May not be available to test on the dev site because of travis issues.

**Comment by apeters** [comment]
I tested this by removing the the items in the "Cards" list and then re-importing the .json file.  I got an error, but it was just a generic error about contacting your administrator.  I thought that this was changed to be something more specific?

**Comment by ryan86** [comment]
You should no longer get the 'contact your administrator' generic javascript popup on the dev site. I recreated the steps you outlined above and got a more specific error.


<img width="1440" alt="screen shot 2016-11-10 at 11 35 17 am" src="https://cloud.githubusercontent.com/assets/3038476/20191321/cd52c984-a739-11e6-8ce3-c045ee429b42.png">
