### ISSUE TITLE
Some values from provisional edits  are initially missing when reviewing

### ISSUE THREAD

**Issue by pdpotter** [archesproject/arches#10612]
Values selected using the `concept-select-widget` and `concept-multiselect-widget` by a user from `resource editor` group (not in the `resource reviewer` group) are initially missing when reviewing the edits. After clicking another card and then clicking back on the card with the `concept-select-widget` or `concept-multiselect-widget`, the value(s) are loaded.

**Comment by chiatt** [comment]
Closing as a duplicate of #10633
