### ISSUE TITLE
Graph Manager: Deleting node in graph editor causes spinner to appear until page reload

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1062]
### Bug Report

When building a resource model or branch in the graph editor when a node is deleted from the resource model or branch the loading 'spinner' appears and does not go away until the page is reloaded.
#### Expected Behavior

Should be able to delete a node without requiring a page reload.
#### Current Behavior

Spinner appears after deleting a node in a resource model or branch until you reload the page.
#### Steps to Reproduce (for bugs)
1. Create simple resource model/branch with an ontology
2. Add a node or branch to that graph.
3. Delete a node/branch from resource model/branch

http://recordit.co/3pm2EkomKn

**Comment by apeters** [comment]
@ryan86: I can't reproduce this error in the latest, can you confirm?

**Comment by ryan86** [comment]
I still see it on the dev machine.

**Comment by apeters** [comment]
I checked on dev and I still can't reproduce this.  If you can't either you can close this ticket.

**Comment by ryan86** [comment]
This may only happen when there is a concept node in the branch.

**Comment by apeters** [comment]
fixed in the latest
