### ISSUE TITLE
Card tree view in card manager

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1065]
the new permissions manager UI (link to follow) has a tree of cards & nodes similar to the card manager but with a slightly different style.  We should unify these by moving the card manager tree view over to this new style.

**Comment by apeters** [comment]
@dwuthrich I think we're going to need a mockup to be able to proceed with this ticket.  I think the "new permissions manager UI" referenced above is now the old permissions manager.  For now i'm going to move this back into the Icebox

**Comment by apeters** [comment]
@dwuthrich is there a mockup for this, or should we just close this ticket?

**Comment by apeters** [comment]
obsolete because of new UI
