### ISSUE TITLE
Upload Photographs - max-photo-size-warning - filesize hardcoded and displays incorrect value.

### ISSUE THREAD

**Issue by khodgkinson-he** [archesproject/arches#10653]
**Arches Version/Branch:** dev/7.5.x (and likely previous).

**Bug description:** - Upload Photographs widget displays **max-photo-size-warning** containing hardcoded "maximum size of any single file", which neither responds, nor corresponds to the Max File Size as set on the widget manager.

![image](https://github.com/archesproject/arches/assets/53860784/dc024f0f-e74a-41d6-b5f1-5af2d516f5b8)

**Steps to reproduce:** Navigate to photo-gallery-card.

**Comment by jacobtylerwalls** [comment]
Fixed in #10660
