### ISSUE TITLE
Improve UX to configure resource-instance dt nodes

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#10666]
Currently the UI for a node of datatype resource-instance looks like this:

![Screenshot 2024-03-07 at 2 25 27 PM](https://github.com/archesproject/arches/assets/8366985/9dac1ff8-f07a-4e43-9cbc-675a53b1a3d4)

Given that there's no visual cue to click on it in order to do something, I would assume many users (like myself) are unaware there's a relationship configuration UI hidden behind it. An improvement in UX might look like adding a button or icon in order to visually prompt the user to configure this node.

**Comment by jacobtylerwalls** [comment]
Fixed in #10667
