### ISSUE TITLE
Date Widget: Saved dates do not appear in the widget

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1067]
### Bug Report

When editing a date widget, user can select a date and save the card.  However, when returning to the card (on refresh or on editing an existing resource) the date widget does not display the saved date value

**Comment by robgaston** [comment]
@dwuthrich the card manager doesn't save widget values - these are only saved in `tiles` when creating a resource (instance).

What is the use case for saving this value?  Is it meant to be used as the default value?  We could manage that as a configuration, but business data values entered into widgets on the card manager aren't saved in general (only card/widget configurations).

**Comment by dwuthrich** [comment]
A data editor should see previously a previously selected date in the date widget, just as other widgets show saved values (e.g.: strings, concepts, etc.)

**Comment by dwuthrich** [comment]
To be clear, this is related to a resource instance data editing session, NOT the card manager

**Comment by robgaston** [comment]
I see - I thought you were referring to the widget in the card manager preview (my bad).

**Comment by dwuthrich** [comment]
meets requirements
