### ISSUE TITLE
500 error in profile view if there is a Group with no members

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#10702]
Just found this logical bug. Took a little while to track down, but ultimately I got `ERROR local variable 'groupUsers' referenced before assignment` when trying to access a user's profile page. Led me to this line: https://github.com/archesproject/arches/blob/d048c402746183c28a8b78fea16fde04c711d338/arches/app/views/user.py#L63 (linking to latest master commit as of writing). As you can see, an if condition creates the `groupUsers` variable only if a group has more than 0 users. But a subsequent line depends on the variable whether there are >0 users or not.

Ultimately, the `if` line should just be removed, it's unnecessary.

**Comment by jacobtylerwalls** [comment]
Fixed in #10708
