### ISSUE TITLE
Cancel edits feature not working as intended for unsaved url datatype tile

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#10732]
Found in all versions of Arches (to my knowledge).

When entering new data into a url datatype tile and clicking "Cancel edits", the entered data is not removed like it should be and is for other datatypes.
The issue is only for unsaved tiles, as cancelling the edits for saved URL data reverts back to the saved.

https://github.com/archesproject/arches/assets/119508494/732edd2d-1394-47c2-a45d-4b12887a9939

**Comment by chiatt** [comment]
Resolved in https://github.com/archesproject/arches/pull/11138
