### ISSUE TITLE
webpack doesn't build if project name contains the string "js"

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10791]
In setting up a new project to test #10642 this morning I was having trouble setting up a new project.

Traced it to my project name "prjsevenfive" containing the substring "js", which violates an assumption here:

https://github.com/archesproject/arches/blob/0c89e7d117f4c639f1ce706f3dfaa82462fb1ca4/arches/webpack/webpack-utils/build-javascript-filepath-lookup.js#L20

Sneaky one! 😉

**Comment by bferguso** [comment]
Ouch! This sort of webpack logic has also bitten me in my dev environment when pulling in common artifacts by way of symlink.

**Comment by jacobtylerwalls** [comment]
@bferguso I'd be grateful for a review if you'd like to take a look. I haven't tested with symlinks :pray:

**Comment by chrabyrd** [comment]
resolved in #11014
