### ISSUE TITLE
Upgrade to PrimeVue 4 and use new theming API

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10838]
Upgrade to PrimeVue 4 to take advantage of the more modern styling API. See [comment](https://github.com/archesproject/arches/pull/10569#discussion_r1509525876).

From [v4 styled mode docs](https://v4.primevue.org/theming/styled):

> Best Practices
Use primitive tokens when defining the core color palette and semantic tokens to specify the common design elements such as focus ring, primary colors and surfaces. Components tokens should only be used when customizing a specific component. By defining your own design tokens as a custom preset, you'll be able to define your own style without touching CSS. Overriding the PrimeVue components using style classes is not a best practice and should be the last resort, design tokens are the suggested approach.

**Comment by chrabyrd** [comment]
resolved in #10990
