### ISSUE TITLE
include database link between geoms in geojson_geometries and individual features in a tile.data feature collection

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#10831]
This issue is essentially about the fact that each geospatial feature exists independent of the tile and resource it's associated with because there can be N features per tile. Basically if you're looking for a particular geom via its `featureid`, you can't find it via the database, only ES. If a given tile has N geoms, the db doesn't know one from the other except via that integer primary key. I would characterize a solution to this as "Nice to Have" as opposed to "necessary" because the `"id"` property on the feature is part of the ES `terms` index, so each individual feature is searchable if you know that id. [This change](https://github.com/archesproject/arches/pull/10827/commits/40959570cb3f87a330ecc461405809f64ab1b3b2) 
 included in PR #10827 also ensures that when we create new tiles with known feature ids they don't get overwritten.

**Comment by chiatt** [comment]
Hey @whatisgalen, could you provide a little more detail on what needs to be done for this ticket?

**Comment by whatisgalen** [comment]
@chiatt sorry for the delay on this. It's surfaced as a blocker to #10704 

When an MVT request gets sent, the features in the response are defined thus out of the `geojson_geometries` table:

```
"""SELECT ST_AsMVT(tile, %s, 4096, 'geom', 'id') FROM (SELECT tileid,
                            id,
                            resourceinstanceid,
                            nodeid,
                            ST_AsMVTGeom(
                                geom,
                                TileBBox(%s, %s, %s, 3857)
                            ) AS geom,
                            1 AS total
                        FROM geojson_geometries
                        WHERE nodeid = %s and resourceinstanceid not in %s) AS tile;""",
                        [nodeid, zoom, x, y, nodeid, resource_ids],
```

The issue is that when you click on a popup [here](https://github.com/archesproject/arches/blob/dev/7.6.x/arches/app/media/js/viewmodels/map.js#L342-L374), the `feature.id` property is a uuid that looks nothing like the `id` property coming from `geojson_geometries`. So in #10827 if I try to compare a clicked feature against the feature properties available via `resource_descriptors`, I'll never have a match on `feature.id` despite comparing features with identical geometries.

Essentially we're maintaining two parallel ids for the same feature: an int feature id in `geojson_geometries` and a uuid feature id in `tile.data...geometries...{feature}`. I think we should either conform them to a single shared featureid, or else maintain a link in `geojson_geometries` to the featureid used when saving geojson tile data [here](https://github.com/archesproject/arches/blob/dev/7.6.x/arches/app/datatypes/datatypes.py#L1276-L1284).

**Comment by whatisgalen** [comment]
done in #11056
