### ISSUE TITLE
Evaluate adding a global client to issue requests (e.g. `axios`)

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10880]
Libraries like [axios](https://axios-http.com/docs/req_config) allow you to declare a central configuration for communicating with your API for things like:
- root url
- headers
- timeouts
- cancellation
- intercepting promise rejections to parse/localize errors

Having to do this with each request individually is cumbersome and increases the surface area for mistakes or inconsistencies.

@teenorth and I made a small start toward this at the developer sprints, opening a ticket to suggest keeping up the momentum.

With luck, it will make extracting microfrontend-level API interactions (e.g. plugins/controlled_list_manager/api.ts or cards/widgets/whatever/api.ts) out of Vue files into pure typescript files less cumbersome (ideally without the need to pass toast/gettext callbacks around).

**Comment by chrabyrd** [comment]
Just to weigh in:

I'm reticent to add any dependencies where the functionality exists with native tools, without a very strong reason to.  It adds to the bundle size, though admittedly not much in this case. Using fetch keeps things simpler and more direct, it's web-standard ( with all the implications for long-term maintenance support ),  and using `axios` abstracts away / renames ( eg body vs data ) basic development patterns. If we use axios it'd likely need to be 100% adopted across the codebase to keep the frontend orderly and essentially locks us out of using native tooling.

**Comment by jacobtylerwalls** [comment]
With fresh eyes had another look in the controlled list manager context and don't see a pressing need for this. I'm not certain that this would make localizing error messages any easier, which was my main hope.

We can reevaluate/reopen if someone has a strong use case for an interceptor.
