### ISSUE TITLE
Templates Manager: Provide a UI to allow admins to configure search, map pop-up, related resources pop-up content

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1089]
### User Story

Arches admins will need to define the nodes that will populate content for the templates that define search results, map pop-up, and related resources pop ups.

**Comment by apeters** [comment]
isn't this the same as #847 ?

**Comment by robgaston** [comment]
@apeters I believe you are correct

**Comment by apeters** [comment]
closing as duplicate of #847
