### ISSUE TITLE
Cannot change widget template (changes don't persist)

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#10899]
Tested in stable/7.5.2 and dev/7.5.x

Changing the template of a card does not seem to work after saving and refreshing the graph.

Tested here with the rich text template:

https://github.com/archesproject/arches/assets/119508494/0b34d877-b21e-450c-a5cd-75eb371c3496

Steps to reproduce:
1. Create a node of either string or concept datatype (easiest to test)
2. On the card, change the template to either rich-text or radio buttons
3. Save the card edits
4. Refresh the graph page
5. Navigate back to the card and see the template hasn't changed (i.e it will still display the text template not rich-text)

Then trying to change it to rich-text again produces an integrity error like the following:
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "cards_x_nodes_x_widgets_nodeid_cardid_widgetid_976dc542_uniq"
DETAIL:  Key (nodeid, cardid, widgetid)=(eaf17eaa-0d56-11ef-b8bc-00155d34a3f9, 3880e6b4-1b5a-450e-97e6-1c0eea178210, 10000000-0000-0000-0000-000000000005) already exists.
```

**Comment by bferguso** [comment]
I've noticed this as well. It appears that in certain circumstances the widget configuration is duplicated when the widget type is changed for a node.
