### ISSUE TITLE
Geometry Widget: symbology of polygon geometry does not change after leaving edit mode

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1090]
### Bug Report

After finishing an edit of a polygon the geometry symbology should change to the default resource model symbology to indicate to the user that the edit is complete.

Even after pressing the save button, the geometry does not change symbology, making it unclear to the user that their edits have been saved

**Comment by chiatt** [comment]
The selection of a geometry should now clear when a user presses the save button.

**Comment by dwuthrich** [comment]
The "edit" and "static" symbology now appears to be the same.  Desired functionality: one symbology for edit mode, and second (user defined) symbology for static mode.

**Comment by dwuthrich** [comment]
meets requirements
