### ISSUE TITLE
Geometry Widget: no way to delete a vertex

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1093]
### Bug Report

There doesn't seem to be a way to delete a vertex in a line or polygon geometry

**Comment by chiatt** [comment]
It's actually possible to delete a vertex - it's just not very clear how it's done.  You have to select a feature to get it into edit mode and then select it again to get it into edit vertex mode. Then select a  vertex and click the Delete button in the drawing tools.  

I will add some instructions in the edit status notifications. 

I could also change the text for the Delete button to be 'Delete Feature' or 'Delete Vertex' depending on editing state.

**Comment by robgaston** [comment]
@chiatt I'm reassigning this to @dwuthrich to verify that this solution is okay.  In general, I would recommend assigning UI related tickets to him to QA as he has the big picture there and the most experience QA'ing the front end.

**Comment by dwuthrich** [comment]
meets requirements
