### ISSUE TITLE
Boolean datatype validation broken

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#10934]
implementation of `str_to_bool` in `BooleanDatatype.validate` fails on case difference for values like `"True"` vs `"true"`.
We should either call `.lower()` on the string passed to `str_to_bool` or bypass it altogether if we already know `isinstance(value, bool)` is `True`.

replicable in `dev/7.6.x`

**Comment by jacobtylerwalls** [comment]
Hey @whatisgalen 👋 .

I remember spotting that when refactoring it in 7.6, and I added a test to be sure, notice "True" is a rejected value:

https://github.com/archesproject/arches/blob/e4145e4cd546210c1bde18a04634fb36ec8d548b/tests/utils/datatype_tests.py#L38

I think it makes sense to change it, but are there any backwards compatibility implications?

**Comment by jacobtylerwalls** [comment]
Just so you think I'm not crazy, this is what we were using before. Agree that it's probably too strict if you can assure me there aren't bc implications :-)
https://docs.python.org/3.11/distutils/apiref.html#distutils.util.strtobool

**Comment by whatisgalen** [comment]
@jacobtylerwalls Yea I'm seeing those tests fail right now. I'm looking at the 3 instances where `str_to_bool` gets used and I can't see any harm in including `'False'` and `'True'` as acceptable values, or lowercasing incoming values.

**Comment by whatisgalen** [comment]
Also the fact that this bug got through means that we should most likely test the datatypes the same way they get called/used by an actual client when saving tiles. So maybe a "tile_post_datatypes_test" or something (with a better name).

**Comment by whatisgalen** [comment]
A little more background:

As of 7.6, when the nodevalue of a boolean node gets validated in `Tile.validate()`, it's validated as a python bool `True` or `False`. Calling `str(True)` becomes `"True"` which due to the upper case T fails the `str_to_bool` logic. My guess is that either [this older way](https://github.com/archesproject/arches/blob/dev/6.2.x/arches/app/datatypes/datatypes.py#L256-L257) somehow handled that without issue or something about how the frontend tile request payload gets loaded into the python tile view may have changed.
