### ISSUE TITLE
Import Top Concepts from SPARQL does not work

### ISSUE THREAD

**Issue by ViktorGetty** [archesproject/arches#10941]
Arches 7.5.1, 7.5.2. 

When trying to Import Top Concept from SPARQL in RDM nothing happens. 

For comparison, in v. 7.3 when start typing in the search text box, the AJAX calls initiated and text box is populated with the results.

**Comment by jacobtylerwalls** [comment]
Thanks for the report. This is fixed and scheduled for a 7.5.3 release in #10856.
