### ISSUE TITLE
Include Metadata in Export of data or branches

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#1096]
Within an export of an arches.json file, metadata about the Arches instance should be included for use with debugging issues.

As we move forward and have more people importing/exporting data, there may be issues importing an arches.json file from different versions of Arches. Rather than giving the arches.json file a versioning system, we should consider including other information to help debug issues.

This metadata would be discarded and not be imported with the rest of the file during an import into Arches.

Proposed metadata to be included in an export:
* Version of Arches (Git commit hash)
* Version and Type of Operating System 
* Version of Postgres

Information that should be included would be related to how the data is stored/generated. Data that would not be included:
* Version of Elastic Search
* Version of Browser used to access the website
* Version of GEOs
* Version of Python/Django.

**Comment by apeters** [comment]
I agree that this information could be very helpful in debugging any issues.

**Comment by jmunowitch** [comment]
Looks good to me:
```
"metadata":{  
   "git hash":"2ffe197 2016-11-04 14:34:26 -0700",
   "db":"PostgreSQL 9.5.2 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit",
   "os version":"3.13.0-74-generic",
   "os":"Linux"
}
```
Nice work.
