### ISSUE TITLE
Running `python manage.py i18n makemessages` in a project creates .po files in Arches core

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#10960]
to reproduce:

1. create a project
2. enable multiple languages in settings.py
3. run `python manage.py i18n makemessages` in the terminal at the project level
4. notice that no .po files are created, instead they are created in Arches-core

The expected behavior is that these files will be created at the project level

**Comment by chiatt** [comment]
Have you seen this @apeters?

**Comment by apeters** [comment]
@chiatt well, @chrabyrd demoed the issue to me, but I haven't tested locally myself

**Comment by chrabyrd** [comment]
resolved in #10993
