### ISSUE TITLE
hard-coded fetch url in create-vue-application breaks projects with FORCE_SCRIPT_NAME

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#10974]
the file `create-vue-application.js` calls this url with fetch:
`return fetch('/api/get_frontend_i18n_data').then(resp => {`

However if a project has set a string value in their `settings.py` file for `FORCE_SCRIPT_NAME` such as `FORCE_SCRIPT_NAME = "/my-web-app"` then this specific fetch request breaks as it does not prepend this to the url supplied, resulting in a 404 and all vue applications in an Arches project to break

**Comment by chrabyrd** [comment]
resolved in #10976
