### ISSUE TITLE
Transform multi-part geoms to single-part feature collections when saving tile data

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10972]
The convert_multipart_to_singlepart should work for this. It can be called in transform_value_for_tile. It probably needs to also be in pre_tile_save. There's some overlap in the roles of these functions that might need review.

**Comment by bferguso** [comment]
@chiatt  - Does this mean that only one geometry can be stored in a GeoJSON node?

**Comment by aarongundel** [comment]
@bferguso no, but it does mean that MultiPolygons, MultiLineStrings, etc will be converted to single features (many polygons) within a feature collection within geojson.

**Comment by bferguso** [comment]
> @bferguso no, but it does mean that MultiPolygons, MultiLineStrings, etc will be converted to single features (many polygons) within the geojson feature collection.

Awesome - thanks @aarongundel!
