### ISSUE TITLE
The project level test fails due to the directory name difference

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#10982]
The project level test fails when the upper and lower directory names of the project are different.
For example, arches-her/arches_her

The test seems to assume that they are the same...
https://github.com/archesproject/arches/blob/dev/7.6.x/arches/install/arches-templates/.github/workflows/main.yml#L46-L47

There are other places there may be other related issues, too.
eg. https://github.com/archesproject/arches/blob/dev/7.6.x/arches/install/arches-templates/.github/workflows/main.yml#L17

**Comment by chrabyrd** [comment]
resolved in #11004
