### ISSUE TITLE
Resource Manger: Appending branch does not preserve display order of nodes in a card

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1098]
### Bug Report

Dragging a card onto a resource does not preserve the ordering of the nodes in a card.  

For example, a branch creator may set the order of address, address type in a card such that the address widget should be placed above the address type widget.  This order is not preserved when appending the card onto a resource model

**Comment by apeters** [comment]
I have confirmed this bug.

Steps to reproduce:
1. Create a new branch 
2. Append the node/nodetype branch to it and rename Node --> Address, Node Type --> Address Type
3. Save the branch
4. Go to the Card Manager and confirm that the Address widget appears above the Address Type widget, reorder if necessary.
5. Save all edits
6. Create a new Resource Model
7. Go to the Card Manager and add the newly created card from Step 4 above
8. Click on the newly added Card and observe that the Address Type widget appears above the Address widget

**Comment by dwuthrich** [comment]
meets requirements
