### ISSUE TITLE
On the search screen there are no page numbers to navigate to next set of results.

### ISSUE THREAD

**Issue by gouthamrandhi** [archesproject/arches#10994]
**Steps to reproduce:**

- Navigate to AHER search screen.
- On this screen the search results should display page numbers to navigate to next set of results.

**Expected:** Page numbers should display so that user can navigate to next set of search results.
**Actual:** When the screen is at 100% zoom the page numbers do not display whereas when zoomed out to 90% they appear.

**Note:** When Window height is smaller the issue arises.

![image](https://github.com/archesproject/arches/assets/131354127/14316d96-a7f9-4b21-a982-d3dbf5942a1b)
![image](https://github.com/archesproject/arches/assets/131354127/7c1119ac-aaeb-4948-9a5b-c55404a805e0)

**Comment by phudson-he** [comment]
Closing as fixed in https://github.com/archesproject/arches/pull/11191
