### ISSUE TITLE
Resource Manager: Widgets not updating as expected when card has a cardinality of n

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1100]
### Bug Report

For cards with cardinality of n, widgets do not update properly after first user interaction.

see:  http://recordit.co/O2obeMUyiX

Note that the user provided string remains after pressing "save" for the first data entry event.  Subsequent data entry functions as expected (widget clears user input and is ready for next data entry event).

**Comment by apeters** [comment]
I have verified this bug as well.

**Comment by dwuthrich** [comment]
meets requirements
