### ISSUE TITLE
Integrate `black` into github actions

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#11028]
It seems [pretty straightforward](https://black.readthedocs.io/en/stable/integrations/github_actions.html) to integrate `black` into GH actions. Since we're already integrating a `prettier`, `eslint`, and `typescript` check, we should add that as well.

**Comment by jacobtylerwalls** [comment]
We did that in #10737, see output:
> All done! ✨ 🍰 ✨
933 files would be left unchanged.

**Comment by chrabyrd** [comment]
++ yep just missed that line I guess 🤦
