### ISSUE TITLE
Deprecate `arches-project` management command in v8

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#11038]
This functionality has been superseded by `arches-admin` , this more closely mimics the [Django syntax](https://docs.djangoproject.com/en/5.0/ref/django-admin/#startproject)

**Comment by jacobtylerwalls** [comment]
Let's issue the deprecation warning in 7.6 and then remove it in 8 or 8+, that way the warning appears in an LTS.

**Comment by jacobtylerwalls** [comment]
Deprecation message was added, so we can remove in a future version (no rush)
