### ISSUE TITLE
Create triggering mechanism for functions

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1103]
Devise and implement a scheme where by a user can specify when during a CRUD operation a function should be triggered to run.

The user needs to be able to specify at least 2 things: 
 - The nodegroup involved in the CRUD operation
 - The operation being performed (Create, Read, Update, Delete)

**Comment by dwuthrich** [comment]
Not clear how the user specified the operation being performed (Create, Read, Update, Delete)

**Comment by apeters** [comment]
That's actually built into the function itself.  The function developer makes the decision as to when best to trigger the function.

**Comment by dwuthrich** [comment]
meets requirements
