### ISSUE TITLE
Upgrade `PrimeVue` to 4.0.0-rc.2

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#11041]
New release just dropped ( https://www.npmjs.com/package/primevue/v/4.0.0-beta.5 ), and [the issue I raised has been addressed.](https://github.com/primefaces/primevue/issues/5811)

Hopefully we can get this working now 👍

**Comment by chrabyrd** [comment]
It looks like they've moved [themes to it's own package](https://github.com/primefaces/primevue/blob/4.0.0-beta.5/README.md)

but nothing has been updated yet, and even though the [packaged exists on npm](https://www.npmjs.com/package/@primevue/themes) , it appears to not be able to be found when adding it to Arches. Rolling off for now and waiting for a documentation update from the team.

**Comment by jacobtylerwalls** [comment]
Fiexed in #11093
