### ISSUE TITLE
Replace setup.py with pyproject.toml 

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#11057]
The python ecosystem seems to be heading toward replacing setup.py with pyproject.toml - this ticket is about replacing the arches setup.py (s) and their associated files (requirements.txt, etc) with a pyproject.toml file.

**Comment by chiatt** [comment]
As part of replacing `arches/setup.py`, it would be great if we could also get rid of `arches/arches/setup.py`.

**Comment by jacobtylerwalls** [comment]
Fixed in #11113
