### ISSUE TITLE
Search results alignment issue on iOS and Android.

### ISSUE THREAD

**Issue by gouthamrandhi** [archesproject/arches#11078]
On the search screen, the results displayed are not aligned. This is observed in both iOS and Android.

![image](https://github.com/archesproject/arches/assets/131354127/2f705f30-456a-4de3-9b2e-0a5ad3879654)

**Comment by aj-he** [comment]
@gouthamrandhi - please confirm that #11145 fixed this issue

**Comment by gouthamrandhi** [comment]
@aj-he This is issue is now fixed. I have tested this issue against DevOps bug ticket (https://hedev.visualstudio.com/Inventory/_workitems/edit/70006).

**Comment by phudson-he** [comment]
Fixed in #11145
