### ISSUE TITLE
GeoJSON export error when export contains a GeometryCollection

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#11084]
The following error has been noted when exporting geometries in a GeoJSON export when some of those geometries are a GeometryCollection

![image](https://github.com/archesproject/arches/assets/38533555/7a698a2b-8767-4f81-bc4e-d981188ee54d)

It appears get_feature_collections is not handling the GeometryCollection when applying set-precision

**Comment by chiatt** [comment]
Did a geometry collection get saved to the tile value? Maybe on import? We actually plan to work on ensuring multipart polygons don't get saved to the tile. https://github.com/archesproject/arches/issues/10972. The map editor doesn't support editing multi-part geometries (although they should display fine). I suspect the same would be true of geometry collections as well.

**Comment by csmith-he** [comment]
@chiatt Having had a closer look at this, I think the issue is with imported Geometry.  It hasn't come through the map but is part of the JSON import file.

I think perhaps this isn't an immediate issue but might be a case of tightening up validation of geometry when being imported via a JSON file?

**Comment by chiatt** [comment]
Thanks @csmith-he we actually recently added geometry validation in 7.6: https://github.com/archesproject/arches/commit/8d0ec6ba70dc959e259a6ff8ae7ef604132f584d

**Comment by csmith-he** [comment]
@chiatt We've confirmed the issue is with the data format we've imported as part of the bulk load process.

I'll close this issue now as validation is now in 7.6
