### ISSUE TITLE
Wide catch in `SystemSettings.__getattr__` might cause unexpected database fetch

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#11118]
While developing #11016, I discovered an edge case where SystemSettings, which is supposed to read from settings.py first if can, falls back unexpectedly to database settings.

The scenario is:
- during the Django startup phase (which #11016 manually invokes when transmitting django settings to nodejs/webpack)
- the arches models are imported
- one of those modules has a module-level constant that calls ThumbnailFactory.create()
- that calls settings.THUMBNAIL_GENERATOR
- but settings aren't ready yet, because we're in the middle of the Django startup phase, so Django throws ImproperlyConfigured
- that's caught by the wide catch, and we go to the database unexpectedly
- then, that happened to throw a circular import error, which is the only reason @chrabyrd and I noticed it

Suggest to catch and reraise ImproperlyConfigured instead of proceeding onward. Will demonstrate in a PR.

**Comment by johnatawnclementawn** [comment]
Resolved in #11119
