### ISSUE TITLE
In card widget within workflow, widgets object passed in is empty

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#11111]
When the card-widget front end model file loads in a workflow, the widgets object being passed in is always empty.

Raised by @aj-he as part of the upgrade of Arches HER to dev/7.5.x.

**Comment by chiatt** [comment]
Unfortunately the fix in #11112 isn't working for me because widgets is an empty object:
<img width="2284" alt="image" src="https://github.com/archesproject/arches/assets/1877663/5a8628de-e037-41e6-b9f9-a66489c637a8"> 

Submitted another PR to fix: #11133

**Comment by aj-he** [comment]
fixed in #11133
