### ISSUE TITLE
Stub out Permissions Manager Page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1112]
Please refer to the mockup located here: http://archesproject.github.io/mockups/arches_permissions_manager.html

This ticket is for the page/endpoint/view only.  
Please refer to these ticket for the specific components in the page: #1113, #1114, #1115
![screen shot 2016-11-01 at 9 47 22 am](https://cloud.githubusercontent.com/assets/823773/19898308/c49ff2f8-a018-11e6-9cc4-405825e44cc4.png)

**Comment by chiatt** [comment]
Looks good!
