### ISSUE TITLE
Import concept from SPARQL not working

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#11130]
As reported here, import from SPARQL in the RDM is not working.
https://community.archesproject.org/t/search-function-in-the-import-concept-modal-does-not-seem-to-work/2451?u=cyrus

@annabelleee Has confirmed  that it is not working on dev/7.6.x

**Comment by chiatt** [comment]
Fixed here https://github.com/archesproject/arches/pull/10857

**Comment by johnatawnclementawn** [comment]
FWIW, could I not repro in dev/7.6.x

**Comment by chiatt** [comment]
Thanks @johnatawnclementawn - That makes sense. We recently merged 7.5.x into 7.6.x
