### ISSUE TITLE
Create page to manage the permissions a user or group has for a given set of nodes

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1115]
re #1112 
Note that the mockup below shows multiple groups/users able to be selected but in reality only one user or group can be selected at a time.  The ui should be updated to reflect this.

Permissions available should be 
 - Create
 - Read
 - Edit
 - Delete

![screen shot 2016-11-01 at 9 52 31 am](https://cloud.githubusercontent.com/assets/823773/19903169/dd89c26e-a02a-11e6-8869-5a4767f282ac.png)

**Comment by dwuthrich** [comment]
meets requirements
