### ISSUE TITLE
Card Manager: Suppress changing of node names in the first Panel (node listing widget)

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1116]
### Bug Report

In the card manager, when a user modifies a card container, card, or node label in the middle panel, the node listing widget is updated with the user's edits.  

This makes it very difficult to know which node in a branch has been edited because the node name (as it appears in the graph) is no longer displayed anywhere in the card manager UI.

Arches should allow users to configure the name of the card container, card, and node for display on a data entry form (so that data editors are presented with meaningful terminology) and show the result on the card preview (e.g.: third panel in the card manager).  But the Card Manager UI shouldn't change the name of the node in the node listing widget (e.g.: first panel in the card manager).

**Comment by robgaston** [comment]
@dwuthrich it appears that this bug is a duplicate of issue #1054.

**Comment by dwuthrich** [comment]
@robgaston That's right.  I'll close this ticket in favor of #1054
