### ISSUE TITLE
Change "Form Settings" to "Settings" AND/OR remove "Form" from "Form Name", "Form Subtitle", and "Form Icon"

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1121]
related to #935 first mentioned by @mradamcox 

Change "Form Settings" to "Settings" AND/OR remove "Form" from "Form Name", "Form Subtitle", and "Form Icon" in the form manager page.

**Comment by apeters** [comment]
I agree with this recommendation.  @dwuthrich what do you think?

**Comment by dwuthrich** [comment]
@apeters I agree that we can drop"Form" from the labels
