### ISSUE TITLE
Project typescript linter doesn't find types exported from core arches

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#11234]
#11210 added the following type to core arches, as a baby step to prove out shipping types that projects/arches applications such as the controlled list manager will find useful:

https://github.com/archesproject/arches/blob/2dc5abe88102c3bf80342e4a83a039cdc0810a3c/arches/app/src/arches/types.ts#L1-L8

However, this import, which worked in #10569 when part of arches core:

```ts
import type { Language } from "@/arches/types";
```

Fails (at the ts linter only, not the bundle) in an arches application (archesproject/arches-references@9fa562a) with:

```ts
arches_references/src/arches-references/utils.ts:4:31 - error TS2307: Cannot find module '@/arches/types' or its corresponding type declarations.

4 import type { Language } from "@/arches/types";
                                ~~~~~~~~~~~~~~~~

[6:02:58 PM] Found 12 errors. Watching for file changes.
```

**Comment by chrabyrd** [comment]
ah, but aren't there different errors when appending `.ts` to `types`?

**Comment by jacobtylerwalls** [comment]
For sure. I wrote up my findings in the PR, let me know what you think!
