### ISSUE TITLE
Pre-commit out of the box ts linting does not seem to check files

### ISSUE THREAD

**Issue by johnatawnclementawn** [archesproject/arches#11249]
1. Initialize new project
2. Place some example ts files in `project_name/src/project-name/` can take from [arches-references](https://github.com/archesproject/arches-references/tree/main/arches_references/src/arches-references)
3. Init project as github repo & install pre-commit (`pre-commit install`) & `npm i` at top level of project
4. Run `pre-commit run --all-files`
5. Despite existence of ts files in src dir, observe `typescript...........................................(no files to check)Skipped`

**Comment by jacobtylerwalls** [comment]
I'm finding better success with:

```diff
diff --git a/arches/install/arches-templates/.pre-commit-config.yaml b/arches/install/arches-templates/.pre-commit-config.yaml
index e74a5a43ed..389decefa7 100644
--- a/arches/install/arches-templates/.pre-commit-config.yaml
+++ b/arches/install/arches-templates/.pre-commit-config.yaml
@@ -24,7 +24,7 @@ repos:
         name: typescript
         entry: npm run ts:check
         language: system
-        types: [
+        types_or: [
           "ts",
           "vue",
         ]
```

However, we should wait to test until the dust settles from #11234, b/c there seems to be false positives having to do with aliasing.
