### ISSUE TITLE
JSONSerializer.handle_model() doesn't serialize if editable=False

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#11272]
Use a Django field with editable=False.
Call handle_model().
Result: doesn't serialize.
Expected: serialized.

Use a Django field with serialize=False.
Call handle_model().
Result: serialized.
Expected: doesn't serialize.

https://github.com/archesproject/arches/blob/c6b043ae0357892f25f1c143daadde1162ff4e19/arches/app/utils/betterJSONSerializer.py#L231-L232

***
_Originally posted by @jacobtylerwalls in https://github.com/archesproject/arches/pull/11096#discussion_r1693524955_

**Comment by jacobtylerwalls** [comment]
> Use a Django field with serialize=False.
Call handle_model().
Result: serialized.
Expected: doesn't serialize.

Actually, we can't find where `serialize` is doc'd as a django field option, so ignore this part.

**Comment by apeters** [comment]
I think we should just remove those 2 lines from `betterJSONSerializer` and call it a day.  I can imagine many scenarios where we'd want to see the values of "non-editable" fields.  It's really up to the implementor of that data consumer to make sure those fields don't get edited.
