### ISSUE TITLE
updateproject doesn't create typescript declarations file in /src/project_name

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#11285]
- Create a new 7.6 project
- manage.py updateproject

Expected:
no new files

Actual:
- messages.pot (#10917)
- /src/declarations/d.ts

We need to determine whether this file should exist, and if so, then it should get created in createproject.

**Comment by apeters** [comment]
added to this is that in the latest install of arches when you create a project 2 declarations files are created at 
```
src/{{project name}}/declarations.d.ts
src/{{project name}}/declarations.test.ts
```

neither of those files get created when you run the `updateproject` command

**Comment by jacobtylerwalls** [comment]
create project is fine but needs an update for @apeters observation above about updateproject.
