### ISSUE TITLE
Arches Resource Model Workflow: Preserve page reference when changing resource models

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1129]
### Bug Report

When switching between resources Arches always refreshes to the settings page.  Instead, Arches should refresh with the new resource in displaying in the requested page.

For example, select a resource and navigate to cards/widgets page.  Then go to manage and select a new resource.  Arches will revert to the settings page for the new resource, not the cards/widgets page

**Comment by dwuthrich** [comment]
This same issue is true when toggling between branches.  Example: select a branch and navigate to semantics (graph manager) page.  Go to manage and select a new card and observe that Arches takes you to the settings page for the new card, not the graph manager page

**Comment by chiatt** [comment]
@dwuthrich In writing up a description of my changes, I created list of changes to QA in my pull request:
https://github.com/archesproject/arches/pull/2494

**Comment by chiatt** [comment]
@dwuthrich In case you didn't see my comments in the pull request, I've updated card navigation with your and @apeters changes. I updated the QA checklist for cards here: https://github.com/archesproject/arches/pull/2494

**Comment by apeters** [comment]
meets requirements
