### ISSUE TITLE
Django default_storage breaks on non-ascii characters in files

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#11337]
When importing a csv, often Django's `default_storage` module is used to handle the file, like so:
```.py
with default_storage.open(csv_file_path, mode="r") as csvfile:
            reader = csv.reader(csvfile)
            data = {"csv": [line for line in reader], "csv_file": csv_file_name}
```
However the default encoding used is ascii, creating an error for non-ascii characters. Django's `default_stoarge.open` method does not take an `encoding=` kwarg like the python `open` method does, so there is no good way to force utf-8 encoding when opening files this way.

**Comment by jacobtylerwalls** [comment]
@whatisgalen you might consider posting on the django forum to gauge appetite for doing the same thing for the storage interface that was done for the [file interface in 5.0](https://docs.djangoproject.com/en/5.0/releases/5.0/#file-storage) to allow all kwargs through to `open()` (assuming still a problem in 5.1)

**Comment by whatisgalen** [comment]
> @whatisgalen you might consider posting on the django forum to gauge appetite for doing the same thing for the storage interface that was done for the [file interface in 5.0](https://docs.djangoproject.com/en/5.0/releases/5.0/#file-storage) to allow all kwargs through to `open()` (assuming still a problem in 5.1)

Just [posted](https://forum.djangoproject.com/t/enable-default-storage-to-pass-kwargs-to-python-open/34045)!

**Comment by jacobtylerwalls** [comment]
> However the default encoding used is ascii

Just noting that this platform dependent. Were you testing with Windows?

**Comment by whatisgalen** [comment]
> 
> Just noting that this platform dependent. Were you testing with Windows?

Ubuntu 20 actually
