### ISSUE TITLE
Create card: Appellation

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1134]
#### Acceptance Criteria
- [ ]
- [ ]
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by annabelleee** [comment]
Edited card and checked against associated resource models.
