### ISSUE TITLE
Create card: Component

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1136]

**Comment by annabelleee** [comment]
Edited card and checked against associated resource models.

**Comment by adamlodge** [comment]
I wonder if there would ever be a need to - within a single component - group a material and technique.  Currently the branch wouldnt support that... should it?

**Comment by adamlodge** [comment]
From slack:
annabelleee [12:11 PM]  
@adamlodge Regarding your question about component, could you elaborate?  the technique and material generally refer to the component as a whole, but if you're wondering if a technique might refer to a particular material in the door, I'm not sure if there's a need to be that specific. I guess a use case would be if say a door has both metal and wood and a particular technique refers only to the part that is metal.

adamlodge [12:12 PM]  
you re-explained it perfectly.  Supporting that level of detail would mean modifying the graph and a more onerous data entry workflow.  Is it worth it?... may not.

new messages
annabelleee [12:47 PM]  
I don't think it's worth it at this point. The data sets I've been working with don't require that.
