### ISSUE TITLE
Add workaround for failing frontend tests

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#11373]
Frontend tests fail if referring to `arches`, usually when trying to access `arches.urls.` This is because we're referring to `arches` as a node_module, but while the project _does_ exist in node_modules, the `arches` moniker only works because of some webpack fanciness.

The proper solution to this is to stop using the `arches` object, and instead move urls and a subset of settings to the frontend via other means. A stopgap solution is to update vitest configuration to appropriately mock the dependency.

**Comment by jacobtylerwalls** [comment]
Fixed in #11374
