### ISSUE TITLE
Unable to change widget type in graph designer

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#11495]
To reproduce:

1. Create a new resource model
2. Add a string node
3. Select the card tab and change the widget type to rich text
4. Notice in the resource editor that the widget is still a standard text widget
5. Go back to the graph designer and change it again to a rich text widget and you should get a 500 error similar to:

```
IntegrityError at /en/card/[some uuid]
duplicate key value violates unique constraint "cards_x_nodes_x_widgets_nodeid_cardid_widgetid_976dc542_uniq"
```

**Comment by jacobtylerwalls** [comment]
I think this is #10899, should we comment there with the more distilled steps?

**Comment by chiatt** [comment]
> I think this is #10899, should we comment there with the more distilled steps?

Thanks @jacobtylerwalls  - I saw that ticket mentioned cards rather than widgets, but looking at it again I see that it is the same. I'll add my notes to that ticket.

**Comment by chiatt** [comment]
Duplicate of #10899
