### ISSUE TITLE
Map Layer Manager can crash when using default permissions

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#11522]
When checking permissions while loading the map layer manager, the graphid of an object is checked against the graphs in the DEFAULT_PERMISSIONS setting. If a Nodegroup is passed in, an error can occur because nodegroups do not have a graph_id attribute.

**Comment by jacobtylerwalls** [comment]
Sounds like a nice use case for #11396 :-)

**Comment by chiatt** [comment]
> Sounds like a nice use case for #11396 :-)

Nice connection - but in this case we don't actually need the graphid because default permissions don't apply to nodegroups. It might be nice to extend default permissions to nodegroups, though, in which case #11396 would be very helpful, but that would that would probably be a much bigger change.
