### ISSUE TITLE
Create card: Place

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1152]

**Comment by annabelleee** [comment]
Edited card and checked against associated resource models. For some resource models, certain nodes can be deleted  as appropriate.

**Comment by adamlodge** [comment]
Cyrus brought up that allowing n cardinality on the spatial_coorindates node results in multiple maps when you have multiple tiles containing geometries in a single resource instance.  

He also noted that this is doubly confusing when the place node is also set to n cardinality because then you have multiple maps inside of multiple tile containers.

I think that users will generally not care whether geometry being captured is stored in a single feature collection (in one tile) or across multiple tiles.  Given that we support feature collections within a single tile, I would suggest that we set both Place and spatial_coordinates_geometry to cardinality of 1 in the HIP graphs. If someone cares for them to be splayed across multiple tiles for some reason, they change the setting.

Thoughts?

**Comment by annabelleee** [comment]
Split this branch into Place-HeritageResource_HeritageResourceGroup, Place-HistoricEvent_Activity, Place-InformationResource. Also changed toggled off "Allow Multiple Values" on the overall place card and the spatial coordinates subcard.
