### ISSUE TITLE
In 7.6.1, when a saved search has no description, the search page then fails to load.

### ISSUE THREAD

**Issue by CWDamm-Kint** [archesproject/arches#11551]
In 7.6.1, when a saved search has no description, the search page then fails to load. 

This is because the search description is null, but the JavaScript file is looking for an active language, which doesn't exist, hence the error:

```
TypeError: Cannot read properties of null (reading 'en')
```

![image](https://github.com/user-attachments/assets/68cbc2a9-b161-425f-adfc-cf0697f6be9a)

**Comment by samuelscandrett** [comment]
Note, this also seems to happen in 7.5.  While the error doesn't produce the "undefined of undefined" search result, it does prevent the saved search from actually displaying.  The saved search will only display if a description is provided.
