### ISSUE TITLE
Create card: Right Description

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1157]

**Comment by annabelleee** [comment]
Edited card and checked against associated resource models.

**Comment by adamlodge** [comment]
@annabelleee   noticed the focus here is on "copyright".  Should we name the branch something like "Information Resource Copyright" rather than Right Description?

**Comment by annabelleee** [comment]
@adamlodge Yes, I think that is much clearer.

**Comment by adamlodge** [comment]
reviewed
