### ISSUE TITLE
Create card: Right

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1158]

**Comment by annabelleee** [comment]
Edited card and checked against associated resource models.

**Comment by adamlodge** [comment]
@annabelleee What do you think about adding a description node to this graph so that user has an opportunity to write up something like an abstract explaining more detail about the protection than the protection type alone can provide.

**Comment by annabelleee** [comment]
@adamlodge It's not necessary, but certainly wouldn't hurt.

**Comment by adamlodge** [comment]
ok.  i guess better to underengineer than over-engineer.
