### ISSUE TITLE
In-app Help and tips, esp. in Arches Designer pages

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1177]
### Background
As part of our desire to have multiple levels of documentation (for developers, for users, etc.) I think we should consider the addition of a lot of hover-text/in-app help toggles. This would allow the inclusion of quick reference info that would help users considerable, I believe.

#### Current Behavior and Proposal
Currently, on all (I think) of the Arches Designer menus, this ![image](https://cloud.githubusercontent.com/assets/10427268/20146147/600210fa-a668-11e6-83a1-87f92eac55db.png) exists, though only as a placeholder. Are there specific plans to implement this "help" concept? I'm thinking of a few ways it could be used:
1. click on Help, the mouse turns into a little info icon, and the next click with give you information about any portion of the page.
2. click on Help and a modal will open with a description of whatever screen is currently being viewed.
3. click on Help to toggle inline explanatory text (e.g. underneath each field). This would be problematic/not work at all within the Graph Designer, however.
4. remove Help and add a lot more hover tool tips for all components
5. combination of 3 and 4: click on Help (rename to "enable tool tips" or something) to toggle 4. In other words, the user would click "enable tool tips" and then get verbose explanations of each component when they hover over it. They would then "disable tool tips" and all of this hover text would be replaced with a concise, two or three word help (similar to what exists now).

I'm liking number 5, but I don't know how complicated or messy it would be to implement. It would be really nice to be able to keep all of these tool tips separate from the html itself (mostly for aesthetics and ease of editing). For example, pass a dictionary to the view that would be something like {component:tip} key/value pairs, which would be conditionally used as tooltips based on the toggle.

Anyway, just spit-balling, but the larger question here is, how can we include user-level documentation directly within the app interface?

**Comment by dwuthrich** [comment]
We implement suggestion #2.  As part of card configuration you can add help text that is displayed in a panel when the user clicks the help link.

**Comment by mradamcox** [comment]
Ok, that addresses the specific card configuration help, but sounds targeted at the "Data Entry User", not the "Resource Designer User", which is who I was thinking about. I realize that the Help button I was looking at isn't what I thought it was. I'm going to create a new issue that more clearly addresses what I was trying to get at.

**Comment by dwuthrich** [comment]
I see.  Notice the help button in the upper right corner of the UI.  Although not functional yet, pressing this button will show a help panel with hyperlinks to Resource Designer specific help.  A key idea is that the help panel will expose hyperlinks to various resource designer workflows (these might be text or video help) hosted either on the Archesproject.org website, Github, or other appropriate platform (e.g.: YouTube for videos).

**Comment by mradamcox** [comment]
Ok, yeah, I was just creating a new issue about implementing that button. Are you thinking there would be a different panel based on which Designer page (whether the graph designer, the report designer, etc.) is in use, or a one-size-fits-all panel that would contain info for all the pages at once?

**Comment by dwuthrich** [comment]
I'm imagining a single panel that groups help links by category (e.g.: Settings, Card Manager, Forms, Reports, Functions, Graphs).  This seems like the most straightforward implementation...

**Comment by mradamcox** [comment]
Ok, got it. However, that header is also visible while a user is adding a resource and entering data through the forms (just noticed). I'd imagine that a different panel should at least be used there, because a "Data Entry User" will not need to see any of the information about how to use the graph manager, for example. Similarly, a "Resource Designer User" won't need help with how to fill out the forms.

**Comment by dwuthrich** [comment]
Exactly right.  We'll want "context sensitive" help (e.g.: a set of help links based on the tool a user is engaged with).  That means a help panel for Resource Design, another for Resource Editing, and perhaps a general help page for users who can only access search.

**Comment by mradamcox** [comment]
Ok, I'll see what I can do about creating some tickets to address these needs. Thanks for all the input.

**Comment by mradamcox** [comment]
ok, #1180, #1181, #1182. These only address Arches Designer and Resource Editor panels, not the possible one that will be used for people with only search privileges. When the Search page and other configuration pages are finished, we should revisit this issue.
