### ISSUE TITLE
Update Terminology on Delete Resource/Branch Warning box

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1190]
#### Current Behavior
Deleting a Resource Model or Branch from the Arches Designer home page yields the following behavior.
![image](https://cloud.githubusercontent.com/assets/10427268/20191948/62b000d8-a74d-11e6-88c1-8b4b68f40742.png)

"Graph/Resource" should be updated to "Resource Model/Branch".

**Comment by adamlodge** [comment]
By definition, a “branch” cannot have resources (instances of resources) associated with it - only Resource Models can.  I wonder if we can avoid this message altogether for branches.

**Comment by mradamcox** [comment]
Well, I think it's still good to have some sort of warning when you try to delete a Branch from the Arches Designer...
