### ISSUE TITLE
Arches Designer: Hide "Appearance" Tab for Branches?

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1194]
#### Current Behavior
Currently, the Settings menu for both Resource Models and Branches includes a tab called "Appearance", where you can "Define this resource's default color when displayed on a map".

#### Expected Behavior
I'm thinking that this tab should be hidden for Branches, as they never appear on a map. Or, there may be a use I'm unaware of (the branch doesn't use this color in the graph manager though).

**Comment by chiatt** [comment]
The appearance tab is no longer available in the branch settings.
