### ISSUE TITLE
Forms Manager: Active/Inactive switch does work

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1195]
### Bug Report

Switching a form's status from "Active" to "Inactive" does not affect the Resource Editor.  The Resource Editor lists the form and allows a user to edit its node group(s) either way.

#### Expected Behavior

Setting a form's status to "Inactive" should prevent the Resource Editor from listing the form or showing its associated card(s), even if its status is updated to "visible" from "hidden".

The purpose of the Active/Inactive switch is to allow a system admin to define a form and its associated cards before allowing CRUD operations to proceed.

**Comment by robgaston** [comment]
@dwuthrich as of #1217 forms will now only show up now if they are flagged as both 'active' and 'visible'.

There isn't really any difference in terms of how the application handles these two values, but they both must be true in order for the form to show up.  This makes me question the need for both values.

If there is really a need for both values, I suspect that there is additional application logic that will need to be added that will consider these values, but it is not clear to me what that would be.

**Comment by robgaston** [comment]
as per slack convo, will remove the form's active switch

**Comment by dwuthrich** [comment]
meets requirements
