### ISSUE TITLE
Resource Model and Branch Settings: In Icon tab, change "Form Icon"

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1197]
#### Current Behavior
"Form Icon" is used in the Icon tab for both Resource Models and Branches.
 
![image](https://cloud.githubusercontent.com/assets/10427268/20198053/2c10be26-a768-11e6-9502-841d3c2513cb.png)

#### Definition of Done
Suggest changing to simply "Icon". Would consider making the same change even in the Form Designer, but not for this ticket.

**Comment by apeters** [comment]
fixed by #2676
