### ISSUE TITLE
Resource Manager/Report: Editing an existing tile appears to create a new tile

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1205]
#### Expected Behavior

Editing an existing card appears to create a new tile.  

see: http://recordit.co/KaVC92ZERa

Not clear if this is a save flaw or reporting logic flaw

**Comment by apeters** [comment]
I added a Node/Node Type card to a resource and then repeatedly edited the values, but I wasn't able to reproduce the error you're seeing.

Looking closely at the video, it looks like this might be related to #1203

**Comment by dwuthrich** [comment]
Try adding/editing a node group in a card in a container with multiple cards.  I suspect the problem appears when the card container has more than one card

**Comment by dwuthrich** [comment]
meets requirements
