### ISSUE TITLE
Integrate a mapserver service into Arches

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1210]
Using the work we did in our 2 day offsite,  integrate a mapserver service into Arches such that on start up, the service is running and available.

**Comment by robgaston** [comment]
should include some way (possibly using settings...) to define layers by providing a name for the layer and a path to a mapnik xml file

**Comment by robgaston** [comment]
will probably also need to generate db records for mapboxgl layers and sources

**Comment by dwuthrich** [comment]
meets requirements
