### ISSUE TITLE
Map report template doesn't zoom to features in the resource

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1215]
I've added a couple feature to my instance and the map in the report doesn't seem to zoom to them.

See: http://recordit.co/bGhgDEpg9D

**Comment by chiatt** [comment]
@apeters I'm not able to reproduce this on my end.  Did you notice any error messages when the report opened?

**Comment by chiatt** [comment]
@apeters Hey Alexei - I can't reproduce this error. Maybe it was resolved by changes I'd already made on my branch (which now should be in master).  Are features still not zooming correctly?

**Comment by apeters** [comment]
Yeah, this appears to be fixed in the latest.
