### ISSUE TITLE
Develop format for arches.json to arches.json mapping file

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1226]
This file will be used in the business data migration/import process to map resource model nodes from a source arches.json file to resource model nodes in a target arches.json file. This file is intended to be used in two ways:

1.) Within open refine to map from node name to UUID using reconciliation services.
2.) With import/translation script to create a target arches.json file based on the completed mappings.

It is envisioned that this will be a csv file but does not have to be. If a csv could include the following columns:

Source Resource Model Name
Source Resource Node ID
Source Node Name
Source Node ID
Target Resource Model Name
Target Resource Node ID
Target Node Name
Target Node ID

No matter what the format nodes should be grouped by resource model. Need some way to know what resource model a node belongs to.

#### Definition of Done
This ticket will be ongoing throughout the business data import/export process as the configuration file may need to modified as the workflow is developed.

**Comment by ryan86** [comment]
This format was changed to json that can support both import and export mapping. The json file structure can be viewed by downloading a mapping file from the graph manager.

**Comment by ryan86** [comment]
You can create a mapping file using the graph manager and choosing 'Create Mapping File' from the 'Manage' menu of a resource model. Or using the cli 'create_mapping_file -d 'path_to_destination' -g 'resource_model_uuid'.

The mapping file is currently exported in the following format (see notes below for details):
{
    "resource_model_id": "99417385-b8fa-11e6-84a5-026d961c88e6",
    "resource_model_name": "Heritage Resource Model",
    "nodes": [
        {
            "arches_nodeid": "82f2dd57-e747-11e6-84a6-026d961c88e6",
            "arches_node_name": "Address Type",
            "file_field_name": "Address Type",
            "concept_export_value": "label",
            "value_type": "",
            "data_length": "",
            "data_type": "",
            "export": false
        }, ...
   ]
}

resource_model_id, resource_model_name, and all arches_node_names and arches_nodeids are populated by the exporter. These attributes indicate the resource model and nodes to which or from which you will be importing/export.

file_field_name - always refers to the field name in a file external to arches. On import this is the column from a csv whose data will populate this node. On export this will be the column in the csv that will be populated with data from this node.

value_type, data_length, data_type - ignore these attributes for now.

export - this parameter indicates whether you would like to export this particular node or not. There may be some nodes in the graph that you don't want users to export by default. Use this parameter to control nodes users are allowed to export.

concept_export_value - 'label', 'id', 'both' - when exporting concepts a user may wish to export the label of the concept the id of the concept label or both. Use this attribute to select, for each concept node, which value you would like exported. Valid values for this attribute are 'label', 'id' or 'both'


If you would like to map multiple file_fields to the same node, simply copy and paste the node object in the mapping file and populate one instance with one column and another instance with another column.

**Comment by apeters** [comment]
fixed in the latest
