### ISSUE TITLE
Create a node name reconciliation service for OpenRefine

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1227]
Create an openrefine reconciliation service to assist in mapping from a source node to a target node in the arches.json mapping/configuration file.

This service will be running on the target arches instance and should take in a source node name string and return a 'fuzzy string' matched target node name and target node id from an existing arches instance. 

source node name --> target node name and target node id 

More information on reconciliation services here:
https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API

Example of Reconciliation Service in Arches here:
https://github.com/archesproject/arches/tree/reconciliation_test

Arches Reconciliation Service Base on this example:
https://github.com/mblwhoi/reconciliation_service_skeleton

**Comment by jmunowitch** [comment]
Implementing OpenRefine workflows has been removed from the Roadmap.
