### ISSUE TITLE
Create openrefine workflow for translating arches.json businessdata

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1228]
Create an openrefine workflow that can be used to incorporate the arches reconciliation services and reconcile your source resource model nodes to your target resource model nodes.

This can be a mixture of script and documented workflow explaining how to import a reconciliation service from arches and use it to reconcile your arches.json mapping/configuration file.

After completing this ticket a user should be able to do the following:
1.) Be able to connect to reconciliation service (developed in #1227) in OpenRefine (https://www.youtube.com/watch?v=Y5-OXywJZoY)
2.) Reconcile source node names with target node names (where target node names are from the arches instance hosting the reconciliation service) using a documented workflow.
3.) Return a completed mapping configuration file.

**Comment by jmunowitch** [comment]
Implementing OpenRefine workflows has been removed from the Roadmap.
