### ISSUE TITLE
Create UI tests to test the 6 different permutations of cardinality

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1240]
The 6 different possibilities are: 
 - 1- (no card container, cardinality = 1)
 - n- (no card container, cardinality = n)
 - 1-1 (card container with cardinaltiy = 1, child card with cardinality = 1)
 - 1-n (card container with cardinaltiy = 1, child card with cardinality = n)
 - n-1 (card container with cardinaltiy = n, child card with cardinality = 1)
 - n-n (card container with cardinaltiy = n, child card with cardinality = n)

**Comment by chiatt** [comment]
Completed in #1240
