### ISSUE TITLE
Copy a potion of a resource model as a branch

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1248]
It would be desirable to be able to identify some non-top node in a resource model and copy it and all of its downstream nodes and edges as a branch.  That would make it possible to preserve and re-use edits made to graphs within resource models as branches that can be applied to other resource models.

**Comment by adamlodge** [comment]
@apeters - could you give me some thoughts on how much effort this would take to implement?  This capability sure would be handy as we evolve the HIP graphs.

**Comment by dwuthrich** [comment]
We should probably put this off until after we finish the current sprint and next sprint.  I think its a lower priority than search and import/export.

**Comment by jmunowitch** [comment]
Duplicate of #3398
