### ISSUE TITLE
Make sure editing info panel does not appear unless a user is in edit/draw mode

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1252]
The editing state panel occasionally appears in cases when the user is not editing.

**Comment by chiatt** [comment]
@dwuthrich  I am sure that I'd seen the editing state panel appear at seemingly random times, but I'm no longer able to reproduce the issue. Perhaps this was resolved with the addition of the draw tools in the panel.

**Comment by dwuthrich** [comment]
@chiatt OK, lets close this ticket.
