### ISSUE TITLE
Increase width and z-index of edit info panel

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1253]
The edit info panel is sometimes hidden behind the geocoder widget. Instead, it should show above any other map elements. It should also extend all the way to the map controls panel.

**Comment by dwuthrich** [comment]
width of info panel should increase to within 10px of the main map tools button if the user dismisses the main map tools panel.

**Comment by chiatt** [comment]
Panel should now resize to 10px left of the map tools button when user dismisses main map tools panel.

**Comment by dwuthrich** [comment]
meets requirements
