### ISSUE TITLE
Remove unneeded files from the system

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1259]
The code base contains a lot of old and obsolete files.  These should be removed before release of the code.

Those files are:
- [x] management/commands/package_utils/resource_graphs.py
- [x] arches/app/media/js/map/*
- [x] arches/app/templates/resource-manager.htm
- [x] arches/app/templates/views/form.htm
- [x] arches/app/templates/views/form-wizard.htm
- [x] arches/app/utils/data_management/concepts/importer.py
- [x] arches/app/media/js/views/forms/base.js:
- [x] arches/app/media/js/views/forms/wizard-base.js:
- [x] arches/app/utils/data_management/resources/formats/shpfile.py
- [x] arches/management/patches/*
- [x] arches/app/templates/views/reports/title.htm
- [x] tests/fixtures/authority_files/*
- [x] arches/app/utils/geos_to_pyshp.py
- [x] arches/app/templates/config-manager.htm
- [x] arches/app/templates/resource-manager.htm
- [x] arches/app/views/entity.py
- [x] arches/app/views/config.py

Additional
- [x] arches/app/models/edit_history
- [x] arches/app/models/entitity
- [x] arches/app/templates/views/saved-searches.htm
- [x] arches/app/templates/views/simple-search.htm
- [x] arches/app/utils/imageutils.py **<-- not sure if I can delete**
- [x] arches/app/utils/data_management/arches_file.py
- [x] arches/app/utils/data_management/concepts/formats/*
- [x] arches/app/utils/data_management/db/backends/*
- [x] arches/app/db/install/dependencies/* **<-- not sure if I can delete**
- [x] arches/app/management/resource_graphs/*
- [x] arches/arches/app/media/js/views/forms/*

**Comment by mradamcox** [comment]
Should this effort also include an examination of the various packages.py options? Some of those methods are similarly out of date at this point.

**Comment by apeters** [comment]
Yes it should @mradamcox

**Comment by apeters** [comment]
should someone be reviewing this @ryan86 ?

**Comment by ryan86** [comment]
Yes. Just assigned you.

**Comment by apeters** [comment]
@ryan, I'm sorry I wasn't more specific, but the list of files above wasn't complete, it was just a list I kept building as I went through the code.  For example the "entity.py" model needs to be removed.

What someone really needs to do is go though the files one-by-one and remove ones that aren't used any more.  I'll send this back to you, if that's ok.

**Comment by chiatt** [comment]
@ryan86 Just added geos_to_pyshp.py to the file list.  I think it was only used in formats/shpfile.py which has been removed.

**Comment by chiatt** [comment]
@apeters I see that only base.js and wizard-base.js are listed above from the files in `arches/arches/app/media/js/views/forms`
Should we add the other files in that directory to the list above as well (entity.js, entity-list.js, edit-history.js, delete-resource.js)?

**Comment by apeters** [comment]
A few more files I think we can delete: 
- [ ] arches/app/utils/imageutils.py
- [ ] arches/app/db/install/dependencies/*
- [ ] arches/app/db/install/postdeployment/*
- [ ] arches/app/db/install/install_db.sql
- [ ] arches/app/db/ddl/*
- [ ] arches/install/django_overrides/*  (make sure to remove the references to those files in arches/setup.py, lines 30 and 31)
- [ ] arches/fabfile.py <-- we should ask if anyone is still using fab
- [ ] arches/app/views/resources.py
- [ ] arches/app/models/validations.py

**Comment by apeters** [comment]
meets requirements
