### ISSUE TITLE
Replace archesv4_resource.json for testing

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1260]
The archesv4_resource.json was created before we had a good idea of what an Arches 4 resource might actually look like. It has been updated as we've gone along but it might be time to revisit this and replace it with a more modern arches json file that's more representative of what resources will look like in Arches 4.

At time of writing more representative branches and resource models can be found in db/graphs. For resource models in particular the Actor Resource Model json. It may still be desirable to use a "snapshot" of graphs for testing instead of testing against the graphs while they are in development to avoid testing against a moving target.

**Comment by dwuthrich** [comment]
meets requirements
