### ISSUE TITLE
Update Travis build infrastructure to Trusty

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#1271]
Travis CI has finally made Postgres 9.5 and 9.6 available to us: https://github.com/travis-ci/travis-ci/issues/4264#issuecomment-263550556

- [x] The .travis.yml needs to be updated to use this.
- [x] Disallowed packages in the new Trusty environment need to be removed or a [PR/issue needs to be submitted to Travis CI](https://github.com/travis-ci/apt-package-whitelist/issues) to allow the package

**Comment by jmunowitch** [comment]
.travis.yml file updated for Trusty setup: 
https://github.com/archesproject/arches/blob/travis-trusty-update/.travis.yml#L1

.travis.yml file updated for Postgres 9.6:
https://github.com/archesproject/arches/blob/travis-trusty-update/.travis.yml#L15

**Comment by apeters** [comment]
is this finished?

**Comment by jmunowitch** [comment]
This should be marked as finished. Everybody's build is currently on the Travis CI Trusty Environment.
