### ISSUE TITLE
Revise dirty state management to simplify crud operations

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1280]
Several tickets related to the resource manager may be resolved by changing the way tile dirty state is managed in form.js.  One approach might be to use the ko reactor library:

re: #1100, #1277, #1282, #1283 
maybe re #1205 #1203

https://github.com/ZiadJ/knockoutjs-reactor

**Comment by apeters** [comment]
all the tickets referenced above have been closed.  I think we can close this as well.
