### ISSUE TITLE
Error when adding first n value in 1-n form cardinality

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1283]
In the case of an inner card that allows for multiple node values, there is an error thrown when the first value is saved (due to the ko.calculated not having a write method).  Subsequent values do not have this issue. 

Error message: knockout.js:47 Uncaught Error: Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.

**Comment by apeters** [comment]
fixed in the latest
