### ISSUE TITLE
Overlay Manager: "Unselecting" does not disable the overlay service request

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1305]
### Bug Report

A user can "unselect" an overlay in the overlay panel.  This removes the overlay from the map view.  However, Arches just updates the overlay's opacity so that it is fully transparent.  This means that when a user pans/zooms the map, the client still request tiles even though they won't be visible.

Expected Behavior:
User clicks on the overlay name in the panel to toggle whether Arches requests tiles.  The user's opacity setting is preserved (currently this is not the case).

**Comment by chiatt** [comment]
@robgaston perhaps a filter (https://www.mapbox.com/mapbox-gl-js/api/#Map#setFilter) could be used to preserve layer order? I'm not sure how filters would work on a raster overlay though.

**Comment by dwuthrich** [comment]
Closing this issue because the current state might actually be desirable.
