### ISSUE TITLE
Inactive resources models or resource models with no form are enabled in nav bar 'Add New Resource' list 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1311]
Inactive resources or resources with no active forms should be disabled in 'Add New Resource' menu in the nav bar.

**Comment by robgaston** [comment]
@ryan86 This sounds related to a ticket that you were working on re: displaying messages and disabling adding resources from the resource manager page, but I can't find the ticket for that issue.  Perhaps this is something that you could easily knock out.

**Comment by ryan86** [comment]
related to #948

**Comment by dwuthrich** [comment]
meets requirements
