### ISSUE TITLE
Resource Manager: Concept checkbox widget doesn't trigger outer card dirty state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1312]
### Bug Report

After saving a card container with cardinality of n, forms for a new card container are generated as expected.  However, when a user edits a card in the card container, no save/discard button is available.

see: http://recordit.co/pZo9zksFgf

**Comment by apeters** [comment]
I tested by changing the widget to the concept multi-select dropdown and it worked as expected.

**Comment by adamlodge** [comment]
Tested with both multi-seect dropdown and with checkbox widget.  Meets requirement.
