### ISSUE TITLE
Nav bar menus obscured by Resource Designer's 'Find' input

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1313]
On the Resource Designer page when a user selects 'Find' and then hovers over the nav bar, the `Find a Resource Model/Branch` input field obscures the `Add New Resource` menu.

**Comment by dwuthrich** [comment]
@chiatt Perhaps assign this to @mradamcox?  I've never had this issue

**Comment by mradamcox** [comment]
Here's an image for reference. The Add New Resource menu is behind the Find dropdown.
![image](https://cloud.githubusercontent.com/assets/10427268/25243415/9a436de8-25c2-11e7-8bb8-60279e99c072.png)
This doesn't have anything to do with the navbar work that I did in the past (that was on the top nav bar).

**Comment by chiatt** [comment]
@mradamcox This should be fixed now. Could you confirm when you get a chance, Adam?

**Comment by mradamcox** [comment]
yes, all good.
