### ISSUE TITLE
Overlay Panel: On save of map, refresh resource layer overlay

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1315]
### Bug Report

Issue:

1. Create new resource instance with a geometry
2. Include the resource model (or all resources) overlay in the map widget
3. Edit the current geometry (either move, edit, or delete)
4. Save the edit
5. Observe that the overlay of the resource instance and the geometry of the resource instance are no longer in synch

Expected behavior:  Arches automatically refreshes the overlay for the current resource model and the "all resources" overlay if the user has added them to the overlay panel of map widget

**Comment by robgaston** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/2633

**Comment by robgaston** [comment]
Currently, refreshing the resources layer causes the map to flicker, but this should be resolved in the next version of mapbox-gl-js:
mapbox/mapbox-gl-js#3621

**Comment by dwuthrich** [comment]
meets requirements
