### ISSUE TITLE
register start_livereload as a valid argument for manage.py packages

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1321]
### User Story
Running `python manage.py packages -o start_livereload` should run [this method](https://github.com/archesproject/arches/blob/master/arches/management/commands/packages.py#L389). Currently, it is not accepted as a valid argument.  Also important because the Procfile that honcho uses includes this command.

#### Acceptance Criteria
Option should be registered in packages.py and reference the existing start_livereload() method.

**Comment by apeters** [comment]
I think the start_livereload command is initiated like this:

**Comment by mradamcox** [comment]
You're completely right, I was stuck on using "start_livereload" because that's the name of the method that is run... wasn't being thorough enough. Thanks for catching it. I will downgrade this issue to a "trivial enhancement" and only suggest that where the other packages.py operation commands use the exact same name as their method, it would be nice to do the same with this one for the sake of consistency.

**Comment by apeters** [comment]
I'm closing that as fairly arbitrary (the naming of the commands and the method name should have to be in sync)
