### ISSUE TITLE
Create landing page for search at localhost:8000/search

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1324]
see http://archesproject.github.io/mockups/arches_resource_editor_v3.html for the mockup

See other tickets for details on the search results (#1235) panel and search filters (term (#1331), temporal (#1326, #1327), spatial(#1330), advanced (#1328))

![screen shot 2016-12-06 at 11 38 19 am](https://cloud.githubusercontent.com/assets/823773/20940998/8af2f576-bba9-11e6-9dd3-3ffe6384a170.png)

**Comment by apeters** [comment]
@robgaston Can you wire this up to the search icon found in the header of the admin pages?  Thanks!

![screen shot 2016-12-12 at 10 54 08 am](https://cloud.githubusercontent.com/assets/823773/21112120/5c981936-c059-11e6-9e02-09733f973699.png)

**Comment by robgaston** [comment]
@apeters I had thought I'd wired it up for all pages, but I didn't notice that the resource manager overrides the header (perhaps overly aggressively), so it was not set up on just those pages.  I've fixed this in the latest.
