### ISSUE TITLE
Create a panel to display a list of search results.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1325]
see http://archesproject.github.io/mockups/arches_resource_editor_v3.html for the mockup

Panel should be able to page results.  Results should be optionally be further filtered by type.

![screen shot 2016-12-06 at 11 38 41 am](https://cloud.githubusercontent.com/assets/823773/20941187/2c49f83e-bbaa-11e6-8ad1-0e5a80ee577b.png)

**Comment by dwuthrich** [comment]
meets requirements
