### ISSUE TITLE
Create panel to manage related resources

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1329]
see http://archesproject.github.io/mockups/arches_resource_editor_v3.html for the mockup

Panel will allow for search results to be dropped into the relationship manager area.
Related resources can be visualized either via a simple grid layout or via a D3 graph (see related-resources-graph.js in Arches v3 for details).

![screen shot 2016-12-06 at 11 40 52 am](https://cloud.githubusercontent.com/assets/823773/20945163/0426939c-bbbb-11e6-8773-b91244cf13d6.png)

**Panel to manage relationship details**

![screen shot 2016-12-06 at 11 40 40 am](https://cloud.githubusercontent.com/assets/823773/20945161/04247ada-bbbb-11e6-907d-2d7bcea0ab81.png)

**Comment by chiatt** [comment]
I thought this should be moved to QA so remaining issues with related resources could be tracked with more targeted tickets.

**Comment by dwuthrich** [comment]
agree
