### ISSUE TITLE
Create widget to generate a spatial filter for search using a map interface

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1330]
see http://archesproject.github.io/mockups/arches_resource_editor_v3.html for the mockup

see [js/views/search/map-filter.js](https://github.com/archesproject/arches/blob/master/arches/app/media/js/views/search/map-filter.js) for an example of what was done in Arches v3

![screen shot 2016-12-06 at 11 38 19 am](https://cloud.githubusercontent.com/assets/823773/20945416/0db31524-bbbc-11e6-8a95-5d3140d1138f.png)

Map widget should be just like the widget we currently use, except that instead of **Map Tools** we have **Query Tools** that allow a user to draw like you can now, plus add a buffer like you can in v3.

![screen shot 2016-12-06 at 3 28 41 pm](https://cloud.githubusercontent.com/assets/823773/20948415/ead15978-bbc8-11e6-9f17-7779aedcd519.png)

**Comment by dwuthrich** [comment]
meets requirements
