### ISSUE TITLE
Create widget to generate a term based filter for search

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1331]
see http://archesproject.github.io/mockups/arches_resource_editor_v3.html for the mockup

see [js/views/search/term-filter.js](https://github.com/archesproject/arches/blob/master/arches/app/media/js/views/search/term-filter.js) for an example of what was done in Arches v3

![screen shot 2016-12-06 at 2 05 39 pm](https://cloud.githubusercontent.com/assets/823773/20945715/3238cd0c-bbbd-11e6-8657-a602e8d23a40.png)

**Comment by dwuthrich** [comment]
meets requirements
