### ISSUE TITLE
Create view to manage saved search filters

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1335]
This new filter would show up here...

![screen shot 2016-12-06 at 3 42 09 pm](https://cloud.githubusercontent.com/assets/823773/20948775/a7e5cd68-bbca-11e6-9607-2fad5ccb91fe.png)

Link to mockup:
http://archesproject.github.io/mockups/arches_resource_editor_v3.html
Load the page, press the related resources button, then the saved search or advanced search button.

dependent on #1631

**Comment by apeters** [comment]
@dwuthrich any movement on a mockup for saved searches?  The guidance I've given the team to date is that I could imagine it's something like our card management view where we display a bunch of "tiles" that in this case represent saved searches, kind of like we do in v3.

**Comment by dwuthrich** [comment]
ANP:

this page now shows saved search, and advanced search:

http://archesproject.github.io/mockups/arches_resource_editor_v3.html <http://archesproject.github.io/mockups/arches_resource_editor_v3.html>

Load the page, press the related resources button, then the saved search or advanced search button.

-drw

Dennis Wuthrich
CEO Farallon Geographics  |  www.fargeo.com <http://www.fargeo.com/>
601 Montgomery St, Suite 1095 | San Francisco, CA  94111
T 415 227 1140  |  Cell 415 317 2771

**Comment by apeters** [comment]
Perfect!


Director of Web Development - Farallon Geographics, Inc. - 971.227.3173

**Comment by dwuthrich** [comment]
meets requirements
