### ISSUE TITLE
Create a simple client side job viewer for long running import tasks.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1340]
For now we'll try to use something simple to avoid having to use [django-channels](https://channels.readthedocs.io/en/stable/) and websockets, or [celery](http://www.celeryproject.org/).

Here's an approach we could use that would be simple without any additional external dependencies:
 - On upload of a file for import send back a job id and associate that job with the user who uploaded the file.
 - Once job id is on the client, the user can start the load of data using a job endpoint (you created a job endpoint right?) (this is initiated with the import button, and is an async request)
 - The start job request (from above) sets up a recursive async poll to the server to allow the ui to update on a regular basis (it would be nice if this interface could have methods that mirror websocket events, ie. open, close, message, error)

**A running Job rendered in the UI**
![screen shot 2016-12-06 at 10 32 53 pm](https://cloud.githubusercontent.com/assets/823773/20957325/ff620fd2-bc03-11e6-9670-c3df1dabfe5b.png)

**Comment by chiatt** [comment]
Bulk Data Manager now addresses this issue
