### ISSUE TITLE
Document default Arches-HIP resource models and branches.

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1342]
### User Story
As a user I will be provided with all of the new versions of the Arches HIP resource models and the branches that composed them. I should be able to to look to the user documentation for a list of all resource models and branches, and maybe a one-sentence summary of what purpose each graph serves.

It's true that a user will be able to see all of these in the actual interface, and that in-app documentation in the Abstract field will answer these questions, but having documentation outside of the installation will be necessary as well.

#### Acceptance Criteria
Create content for a new appendix or reference section that will give a summary of all the default graphs that arches will ship with.

**Comment by adamlodge** [comment]
@mradamcox I would suggest holding off on this until the abstracts graphs are a bit more mature and the abstracts are all written.  And then this content can be queried directly from the database as a starting point.  I want to minimize the chance that the external documentation will get out of synch with the in-system metadata.

**Comment by mradamcox** [comment]
Yeah, sounds good, that's what Annabel and I were thinking too.
