### ISSUE TITLE
Propose changing name of Resource Manager in the tools menu

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1343]
### Proposal
As the Arches Designer is labeled "Arches Designer" in the tools menu, I propose changing "Add New Resource" to Resource Manager, for consistency. This also makes sense because you are able to do more than just add a new resource when you go to the resource manager.

![designer-vs-manager](https://cloud.githubusercontent.com/assets/10427268/20980941/3d243e34-bc78-11e6-98a8-dbcdf46dd1e2.gif)

**Comment by apeters** [comment]
I think to be completely clear, we'd also need to prepend every Resource Model name with "Add New" and drop "Model", as in: 
Activity Resource Model --> **Add New Activity Resource**

**Comment by mradamcox** [comment]
Yes, I like that a lot. Possibly a shortcut to the "Recently Added" at the bottom of the dropdown list as well.

**Comment by mradamcox** [comment]
Closing, this has been taken care of.
