### ISSUE TITLE
Map Widget: scroll bar persists after overlay menu is removed.

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1346]
Found this while using the widget in the Data Widgets and Cards context, but also happens in the Resource Editor.

![map widget scroll bar](https://cloud.githubusercontent.com/assets/10427268/20983309/93f29c7a-bc81-11e6-86bc-149a4b39a852.gif)

Windows 10 / Chrome

**Comment by robgaston** [comment]
@mradamcox looks like a platform specific thing; can you post details on OS & browser, please?

**Comment by mradamcox** [comment]
Sure, I'm just using Chrome on the dev.archesproject machine.

**Comment by robgaston** [comment]
@mradamcox sorry, I meant your local OS, looks like Windows, but not sure which version...

**Comment by mradamcox** [comment]
on windows 10.

**Comment by mradamcox** [comment]
Perhaps related: just opened the dev site on firefox for the first time, and found more scroll bar issues. For example:

![image](https://cloud.githubusercontent.com/assets/10427268/20983606/bc0a87e4-bc82-11e6-82a0-98c769625fc2.png)

A) scroll bar along tools menu
B) this one shows up for me in Chrome also but really isn't an issue overall.
C) main scroll bar for form is not functional at all.

I'm going to turn this into a separate issue actually...

**Comment by mradamcox** [comment]
Please see related issue #1348 .

**Comment by chiatt** [comment]
@mradamcox This should be cleared up now. Let me know if you see any unwanted scroll bars on the map or elsewhere.

**Comment by mradamcox** [comment]
all good!
