### ISSUE TITLE
Unify beg/end of existence branches

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1355]
adamlodge [3:45 PM]  
was thinking about begin of existence and end of existence... i wonder if we can unify those under a single branch.  that way they can be two separate cards under one card container to make a better workflow.

annabelleee [3:48 PM]  
Have you thought about how to do this using the CRM yet?

**Comment by dwuthrich** [comment]
@adamlodge I've done this on my local Arches instance.  Agree that it would be a nice way to group beginning and end of existence nodes.  FYI, both fit under an E5_Event node

**Comment by annabelleee** [comment]
Thanks, Dennis. I agree about the E5... can you export and send me that branch?

**Comment by adamlodge** [comment]
[Creation-Destruction Events.json.txt](https://github.com/archesproject/arches/files/640904/Creation-Destruction.Events.json.txt)

**Comment by annabelleee** [comment]
Existence branch currently on branch machine and ready for review. Attached it to Activity and Historical Event resource models using P114, Actor using p11i, and Heritage Resource and Heritage Resource Group using P12i. Removed old Beginning of Existence and End of Existence branches from those resource models.

**Comment by adamlodge** [comment]
reviewed
