### ISSUE TITLE
Bug: Concept widgets dont respect collector concepts

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1359]
Some concepts are not intended to be used as selectable values in pick lists associated to E55 nodes.  We have called them "collector" concepts and identified as such in the data.  They generally only exist to add organization to concept hierarchies.  For example:

Colors of Churches (collector)
   green (index)
   blue  (index)
   yellow (index)

Currently, if a node is set with a concept or concept-list data type, you can select collector concepts within the list.

**Comment by robgaston** [comment]
see here:
http://dev.archesproject.org/card/e817b2a9-956d-11e6-b664-024f9e178154

**Comment by robgaston** [comment]
Looks like this is actually working already, but the concepts referenced above are not configured to be collectors.

**Comment by robgaston** [comment]
I modified the "meteorological" concept to be a collector in this example:
http://dev.archesproject.org/card/e817b2a9-956d-11e6-b664-024f9e178154

You should note that it is no longer selectable.

**Comment by adamlodge** [comment]
meets requirement.

**Comment by adamlodge** [comment]
@ryan86 can you confirm that the collector switch for concepts is being loaded to the DB correctly?

**Comment by ryan86** [comment]
I think this is working correctly. There are no collector concepts in the test authority documents.

**Comment by ryan86** [comment]
@adamlodge Meteorological concept in the Threat Type Collection is now a collector concept on the dev machine.

**Comment by adamlodge** [comment]
Meets requirement. It would be nice if the auto-loaded RDM content included some concepts that are collectors.  I had to change one to a collector in the RDM to test.
