### ISSUE TITLE
Suggest remove the word "Help" from custom card help.

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1365]
### User Story
As a user, when I create custom help contents for a card, it looks like this in the card designer:

![image](https://cloud.githubusercontent.com/assets/10427268/21120080/35d885c4-c08b-11e6-86bd-0599cf2cd15e.png)

and this in the form itself:
![image](https://cloud.githubusercontent.com/assets/10427268/21119975/a10554cc-c08a-11e6-8d0b-044fef4d76ca.png)

proposing the removal of the word "help" (circled in red in the first image), at least if a custom title has been added.

**Comment by mradamcox** [comment]
I would just like to add that if anyone takes this issue, a more thorough testing of the card-level help system would be great... sometimes I have had trouble typing help contents in, or strange persistence of content from one card to the next...

**Comment by chiatt** [comment]
I don't believe this UI still exists in the latest designer
