### ISSUE TITLE
Proposal: Move report Active/Inactive switch from the Header to the Report Reports front page.

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1368]
#### Current Behavior
Currently the "Active" switch for a resource report exists here, inside the report manager for a single report.
![image](https://cloud.githubusercontent.com/assets/10427268/21122293/dbeb9680-c096-11e6-9278-a14b3c81fc86.png)

Propose rewiring this switch to be exposed on the main Resource Reports page where it is referenced like this:
![image](https://cloud.githubusercontent.com/assets/10427268/21122331/15668320-c097-11e6-9f23-674f9ee30298.png)

Reasoning:
1) Technically this is a report setting, not a part of its content. So putting it within the Header section places it hierarchically similar to the "publish this section" switches, which may be misleading.
2) The tiles in the resource reports landing page have an active delete button, so it would be intuitive to have the active status function as button also.
3) The radio nature of this switch would be visually obvious if selecting "active" on one report automatically made all the others "inactive"

This may be more work than its worth.

**Comment by chiatt** [comment]
Closing because issue addresses deprecated graph manager.
