### ISSUE TITLE
Link to graph from card and vica-versa

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1376]
I am finding that as I refine cards for branches I am constantly going between the card manager view of the branch and graph manager view to tune "list"-style data types (defined in the graph manager) vs the "Allow multiple values" option defined in the card manager.  

For now, I am manually copying the url of the view I am looking at and then swopping the word "graph" or "card" to access the alternate view.  It would save me (and future graph/card designers) many button clicks if there was a one-click way to open the alternate view in another browser window.

**Comment by robgaston** [comment]
@adamlodge #1379 should allow you to right click on any of these navigation links and open them in a new tab.

I think this will satisfy the requirement that you described - you can now open the manage menu on the left and right click on any item in the menu and select "Open in a new tab" to open that page in a new tab.

**Comment by adamlodge** [comment]
meets requirements.  Thanks Rob!
