### ISSUE TITLE
Graph Manager: "Editable"/"Non-editable" labels are problematic

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1378]
#1266 changed labels on graph list and graph settings page from "Active" and "Inactive" to "Editable" and "Non-editable"

this is problematic for a few reasons:

- It’s unclear if “Editable” means the *resource model* itself can be edited, or that a user may add *resource instances* using this *resource model* (turns out, it’s the latter).

- this flag means different things for *resource models* vs. *branches*: for a *resource model* it means that a user can create *resource instances* using this *resource model*, whereas for *branches* it means that a user may add this *branch* to other *branches* or *resource models*.

We’ll need to come up w/ the right labels here, because I think what we’ve got now is insufficient.

**Comment by mradamcox** [comment]
Personally, I liked Active/Inactive, as these are general enough terms to mean both "use this model to create a new resource" and "make this branch available to be added to a resource model". And intuitively the setting makes sense in both contexts.
