### ISSUE TITLE
Graph Manager: switching between certain data types causes issues

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1403]
#### Current Behavior
Multiple issues here, figuring that they are all connected and a single effort should solve them all.
1.) While editing a Branch in the Graph Manager, I make a new node and set its data type to domain-value. I enter "yes" and "no" as values and save. Head to the Card Manager, and everything looks good, yes and no show up. However, go back to graph manager, and change data type to "domain-value-list" and save. The "yes" and "no" values are still listed. However, head to the Card Manager and they do not show up, and return to the Graph Manager and they are gone.
2) I'm pretty sure that the exact same thing happens when dealing with concept vs. concept-list.
3) Probably connected to this issue is that the Save button does not show up reliably during these processes. For example, select 'concept', choose a concept collection and click save. Now change to  'concept-list' and click save. Now, choosing a new concept collection does not make the save button show up.

#### Expected Behavior
1) When switching from the domain-value to domain-value-list, the previously entered values should be erased in the interface, because they seem to be erased from the node.
2) Same for concept to concept-list.
3) The save button should show up whenever a change is made to the concept collection.

**Comment by chiatt** [comment]
@mradamcox Hey Adam - I'm not able to reproduce this issue for domain or concept types. A lot of work has been done recently on datatypes, so perhaps it got resolved in the process.

**Comment by mradamcox** [comment]
Yeah, everything seems to work fine now.
