### ISSUE TITLE
Upgrade to mapbox-gl-js 0.29.0

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1419]
https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.29.0

This release gives us smooth map style updates, which should improve the map display when refreshing resource vector tile layers after edit (#1315)

**Comment by jmunowitch** [comment]
mapbox-gl-js-bower has been updated with v0.29.0:
https://github.com/archesproject/mapbox-gl-js-bower/tree/v0.29.0

Testing will be required to confirm this doesn't break existing functionality

**Comment by jmunowitch** [comment]
FYI: The Changelog claims there is no breaking changes.

**Comment by robgaston** [comment]
@chiatt the latest in `master` is using 0.29.0 - the feature that I wanted is working well (had to rework the resource vector tile source refresh logic a bit there, but that was sort of a hack anyhow, so no big surprise there).  Everything else seems to be working well from my experience, but I wanted to get a double-check from you.  Please QA this with an eye for any regression in the map component that might have been caused by this upgrade.  Thanks!

**Comment by jmunowitch** [comment]
See #1445. v0.30.0 is now out

**Comment by chiatt** [comment]
works as expected
