### ISSUE TITLE
integrate time wheel w/ time filter controls

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1429]
depends on #1326 & #1327 

Once we have the time filter controls and time wheel binding working, we need to integrate the two.  This will involve setting the time filter controls' date range based on the selection of a range in the time wheel.

**Comment by dwuthrich** [comment]
A reminder: the time wheel will support temporal representations that are not JS date (or database date) types.  Example: a valid time wheel bin is -1,000,000 to -135,000 (e.g.: a representation of years before present)

**Comment by apeters** [comment]
fixed in the latest

**Comment by apeters** [comment]
when selecting a value from the time wheel, the time filter inputs get populated with **date and time** information.  We should probably remove the **time** portion of date.

**Comment by dwuthrich** [comment]
meets requirements
