### ISSUE TITLE
Rework Settings in Card Container, Card, and Widget Managers

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1437]
This icon is used for "settings" in the Graph Designer
![image](https://cloud.githubusercontent.com/assets/10427268/21658993/5d744a4a-d28e-11e6-86ad-8fae6202b3be.png)
but this one is used in all of the Card-related manager panels
![image](https://cloud.githubusercontent.com/assets/10427268/21661131/36036694-d298-11e6-969d-dec14086d7bf.png)
recommending that that latter (tools icon) be changed to the former (gear icon).
Additionally, propose moving the "Settings" header (circled) to the top of the menu, so it more closely mirrors the Permissions menu.

**Comment by dwuthrich** [comment]
closing ticket as no longer relevant to current v4 UI
