### ISSUE TITLE
Mapbox:  Need to add support for additional Mapbox style objects 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1442]
Mapbox allows users to download [styles](https://www.mapbox.com/mapbox-gl-style-spec/) that can be used to define how geospatial data are rendered in a browser.  Arches currently supports the [`sources`](https://www.mapbox.com/mapbox-gl-style-spec/#root-sources) and [`layers`](https://www.mapbox.com/mapbox-gl-style-spec/#root-sources) objects in a Mapbox style .json file.

Arches should also support the [`metadata`](https://www.mapbox.com/mapbox-gl-style-spec/#root-metadata), [`sprite`](https://www.mapbox.com/mapbox-gl-style-spec/#root-sprite), and [`glyphs`](https://www.mapbox.com/mapbox-gl-style-spec/#root-glyphs) objects that are also delivered in a Mapbox style .json file, as these objects are used to style geospatial data.

**Comment by robgaston** [comment]
@dwuthrich Our component constructs a style object from some tables and the widget configurations.  We can easily just add these properties to the map component.

The general question is: to what extent should these parameters be configurable?

The answer depends (I think) on each parameter.  However, all of these parameters are on the root of the style object.  This means that they are always applied to an entire style/map instance, which implies to me that each could be managed in one of three ways:

1. hard-coded in our JS (if the value should always be used w/ any arches application),
1. configured at the application level (if the value should be configurable for arches applications, but used application wide), or 
1. configured at the widget level (if the value should be configurable on a per widget basis).

Some specific thoughts & questions I have are:
- `metadata` is an object that contains some arbitrary properties.  These properties in no way impact rendering ([as per the docs](https://www.mapbox.com/mapbox-gl-style-spec/#root-metadata)).  I think we can probably just hard code this in our JS unless there is something I'm missing here.  What did you envision storing in the `metadata`?
- `sprite` and `glyphs` specify string urls for resolving images and glyph sets.  In my opinion, we might make these configurable at the application level, or we might hardcode these values to a set of resources supplied by arches (which would require that we create and supply those resources somehow). Not sure yet what's best.  Did you have some specific thoughts on these two parameters?

**Comment by dwuthrich** [comment]
It appears that metadata does in fact define sources for rendering, so this would be something that we should support.  I suggest that this will vary between sources/styles, so should probably be configurable by the user in some way.

As for sprite/glyph, this does seem like something that could be dealt with at the application level (possibly as a setting)

**Comment by dwuthrich** [comment]
Here's a snippet from a Mapbox style sheet that seems to show metadata being used to define sources for rendering:

"name": "Light",
    "metadata": {
        "mapbox:autocomposite": true,
        "mapbox:type": "default",
        "mapbox:groups": {
            "1444934828655.3389": {
                "name": "Aeroways",
                "collapsed": true
            },
            "1444933322393.2852": {
                "name": "POI labels  (scalerank 1)",
                "collapsed": true
            },
            "1444862578782.6787": {
                "name": "Road labels",
                "collapsed": true
            },
            "1444855786460.0557": {
                "name": "Roads",
                "collapsed": true
            },
            "1444934295202.7542": {
                "name": "Admin boundaries",
                "collapsed": true
            },
            "1444856151690.9143": {
                "name": "State labels",
                "collapsed": true
            },
            "1444933721429.3076": {
                "name": "Road labels",
                "collapsed": true
            },
            "1444933358918.2366": {
                "name": "POI labels (scalerank 2)",
                "collapsed": true
            },....

and in the layers object:

"layers": [
        {
            "id": "background",
            "type": "background",
            "layout": {},
            "paint": {
                "background-color": "hsl(55, 11%, 96%)"
            },
            "interactive": true
        },
        {
            "id": "landcover_wood",
            "type": "fill",
            "metadata": {
                "mapbox:group": "1456970288113.8113"
            },
            "source": "composite",
            "source-layer": "landcover",
            "maxzoom": 14,
            "filter": [
                "==",
                "class",
                "wood"
            ],
            "layout": {},
            "paint": {
                "fill-color": "hsl(0, 0%, 89%)",
                "fill-opacity": 0.1,
                "fill-antialias": false
            },
            "interactive": true
        },
        {
            "id": "landcover_scrub",
            "type": "fill",
            "metadata": {
                "mapbox:group": "1456970288113.8113"
            },
            "source": "composite",
            "source-layer": "landcover",
            "maxzoom": 14,
            "filter": [
                "==",
                "class",
                "scrub"
            ],
            "layout": {},
            "paint": {
                "fill-color": "hsl(0, 0%, 89%)",
                "fill-opacity": 0.1,
                "fill-antialias": false
            },
            "interactive": true
        },....

Based on my testing it looks like mapbox gl fails on rendering layers that reference a mapbox group defined in the metadata object.

**Comment by robgaston** [comment]
@dwuthrich I'll need to know exactly what you're doing to understand what is going on, but I'm guessing there is an issue with the layers you are defining.

If you are using layers from the above example, they won't work in Arches unless you are also defining a source called 'composite' (there isn't such a source that ships w/ Arches).

**Comment by dwuthrich** [comment]
I have added 'composite' as a map source.  Arches renders layers without metadata references, but does not seem to render those layers that do.

**Comment by dwuthrich** [comment]
fixed in #1443
