### ISSUE TITLE
Document arches csv formatting requirements

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1460]
A csv to be imported into arches will have to follow certain formatting requirements (eg how should groups be displayed in your csv, do all attributes of a resource have to be on the same line, etc). This ticket is for the documentation of those requirements.

**Comment by ryan86** [comment]
To run csv import make sure you have a populated mapping file in the same directory as your csv file and use the following command:

`python manage.py packages -o import_csv -s 'path_to_csv_file_including_file_name'`

**Comment by ryan86** [comment]
CSV File Format Requirements

1.) A row may contain the attribute values of one and only one resource instance. However, one resource may be comprised of multiple rows (see #3 below)

2.) Each row must include a column called ResourceID **(name subject to change)**. ResourceID is a user-generated unique ID for each individual resource. Arches will create a separate unique ID for any resource that is loaded. Since any given resource may have many groups of attributes, a given RESOURCEID value may repeat on many lines (see #3 below).

`ResourceID,attribute 1,attribute 2,attribute 3
1,resource 1 value 1, resource 1 value 2, resource 1 value 3
1,resource 1 value 4, 
2,resource 2 value 1, resource 2 value 2, resource 2 value 3
2,resource 2 value 4, 
3,resource 3 value 1, resource 3 value 2, resource 3 value 3
4,resource 4 value 1, resource 4 value 2, resource 4 value 3`


3.) Grouped attributes must be in the same row and in order to preserve grouping, each group of the same attribute types should be in separate rows. For instance, a resource may have two names with corresponding name type values: <1> Name 1, Primary <2> Name 2, Alternate. Name 1 and Primary should be in one row, and Name 2 and Alternate should be in another.

`ResourceID, name, name type
1,name 1, primary        <---Name Group 1
1,name 2, alternate     <---Name Group 2`

4.) One row may contain many attributes in groups of different types. In the above example, the Name 2 name group may be in a row with a group of place attributes

`ResourceID, name, name type, address, geometry, place description
1,name 1, primary,some address 1, some geometry 1, some description 1
1,name 2, alternate, some address 2, some geometry 2, some description 2`

5.) If a resource comprises multiple rows, those rows must be contiguous. In other words, rows must be sorted by ResourceID.

6.) Geometry: Any value that is to be loaded as a geometry must be formatted using Well Known Text (or “WKT” for short) with coordinates set to ESPG 4326 or latitude/longitude WGS84 (http://spatialreference.org/ref/epsg/4326/). WKT is a standard format for storing vector geometry as human-readable text. Details of the standard can be found here: https://portal.opengeospatial.org/files/?artifact_id=54797, and Wikipedia has a much more readable aggregation of the relevant information here: http://en.wikipedia.org/wiki/Well-known_text.

7.) Domains: Another special case here is values associated to ATTRIBUTENAME``(s) that link to the ``domains businesstable. In those cases, the value stored in ATTRIBUTEVALUE must be the conceptid fed in from CSV-formatted “authority files.” **(More on domain lists coming soon!)**

**Comment by apeters** [comment]
meets requirements

**Comment by apeters** [comment]
didn't mean to close this

**Comment by mradamcox** [comment]
Sorry i've been so slow on getting this done, it's on the shortlist. Thanks @ryan86 for all the material here.

**Comment by mradamcox** [comment]
https://arches4.readthedocs.io/en/latest/import-export/

**Comment by apeters** [comment]
@mradamcox what's the status of this?

**Comment by mradamcox** [comment]
I assigned it to @ryan86 so he could look over the content, because it's all based on his comments here. I thought that was the way we were asking for review, per se, as opposed to setting "reviewers". Anyway, after he's ok with it he can close it, or let me know what is wrong or needs to be changed. You can view the content in the link above.
