### ISSUE TITLE
Resource Model Settings: Improve display of relatable resources list

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1462]
### User Story
Currently, the list of resources that may be related to a Resource Model that shows up in the Settings is a little uneven:
![image](https://cloud.githubusercontent.com/assets/10427268/21786873/d3dd1346-d68b-11e6-9e64-8b58b01e1335.png)
A little bit of styling would be good to improve the alignment and spacing of items in this list.

**Comment by dwuthrich** [comment]
meets requirements
