### ISSUE TITLE
Create large test dataset to test search and import/export

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1490]
Create a test dataset large enough to stress test the import/export routines and the can be used to test search as well.

The test dataset should have all manner of datatypes within it, including temporal and spatial information.

Here's a link to a test data generator that I used to make an initial pass at generating a schema.

https://www.mockaroo.com/cd716390

make sure to use "problematic data for some data"

**Comment by dwuthrich** [comment]
meets requirement
