### ISSUE TITLE
Shapefile Export

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1498]
**JUST NEED TO DOCUMENT WORKFLOW AS MENTIONED IN @apeters COMMENT BELOW**

Create command to export business data from elastic search to shapefile.

Should utilize mapping file that is can be created for each resource model, using the 'create mapping file' button in the graph manager UI.

**Comment by apeters** [comment]
Note that an acceptable workflow would be to convert CSV to shapefile (using QGIS, specifying the geometry encoding as WKT). This would then mean that to export to shapefile, one first needs to export data from Arches as CSV and then use QGIS to convert to shapefile

**Comment by chiatt** [comment]
@apeters 
To QA this ticket you will need to load the her-data and then add the following view to your database:
[monuments.sql](https://github.com/archesproject/test-package-load/blob/master/business_data/resource_views/monuments.sql)

Then run the following:
```python manage.py export shp --table vw_monuments --dest monuments```

**Comment by apeters** [comment]
@chiatt, Functionally this meets requirements, but we still need some documentation.

**Comment by apeters** [comment]
meets requirements
