### ISSUE TITLE
Search time wheel zoom feature

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1506]
Currently there is a bug w/ the search time wheel zoom feature as implemented.  You can double click to zoom in/out, but you are unable to ever zoom all the way back out.

Some background: I found [this example](http://tiven.wang/apps/d3/zoom-sequence-sunburst.html) which conflates the ["sequences sunburst"](https://bl.ocks.org/kerryrodden/7090426) and ["zoomable sunburst"](http://bl.ocks.org/mbostock/4348373) examples to achieve what (I think) we want, but it is unfortunately written against an old version of the API and I've not yet had success integrating this code and updating for the version of D3 that we're using.

**Comment by apeters** [comment]
fixed by #1602
