### ISSUE TITLE
Implement related resource model constraints in Resource Model settings

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1512]
In the resource model settings, a user should be able to check which other resource models are eligible for a relationship. The UI is currently stubbed out, but a user can't yet save their selection. 

<img width="942" alt="screen shot 2017-01-25 at 2 48 29 pm" src="https://cloud.githubusercontent.com/assets/1877663/22312614/73387ea2-e30d-11e6-9212-6df96728d088.png">

**Comment by robgaston** [comment]
@adamlodge assigning this to you for QA as you mentioned it in the standup this morning - thanks

**Comment by adamlodge** [comment]
Works as expected when assigning settings to resource models - per the scope of this ticket.  Still in flight as part of a seperate issue is actually using this capability in the context of associating one resource instance to another.
