### ISSUE TITLE
Upgrade to mapbox-gl-js 0.32.1

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#1515]
mapbox-gl-js-bower has been updated with v0.32.1:
https://github.com/archesproject/mapbox-gl-js-bower/tree/v0.32.1

Testing will be required to confirm this doesn't break existing functionality

The Changelog claims there is no breaking changes from the version currently pinned (0.30.0). 
here are the changes:

#### Bug Fixes

 - Fix bug causing [`mapbox-gl-rtl-text` plugin](https://github.com/mapbox/mapbox-gl-rtl-text) to not work #4055

#### Deprecation Notices

- [Style classes](https://www.mapbox.com/mapbox-gl-style-spec/#layer-paint.*) are deprecated and will be removed in an upcoming release of Mapbox GL JS.

#### New Features

 - Add `Map#isSourceLoaded` method #4033
 - Automatically reload tiles based on their `Expires` and `Cache-Control` HTTP headers #3944
 - Add `around=center` option to `scrollZoom` and `touchZoomRotate` interaction handlers #3876
 - Add support for [`mapbox-gl-rtl-text` plugin](https://github.com/mapbox/mapbox-gl-rtl-text) to support right-to-left scripts #3758
 - Add `canvas` source type #3765
 - Add `Map#isMoving` method #2792

#### Bug Fixes

 - Fix bug causing garbled text on zoom #3962
 - Fix bug causing crash in Firefox and Mobile Safari when rendering a large map #4037
 - Fix bug causing raster tiles to flicker during zoom #2467
 - Fix bug causing exception when unsetting and resetting fill-outline-color #3657
 - Fix memory leak when removing raster sources #3951
 - Fix bug causing exception when when zooming in / out on empty GeoJSON tile #3985
 - Fix line join artifacts at very sharp angles #4008

#### New Features

- Add `renderWorldCopies` option to the `Map` constructor to give users control over whether multiple worlds are rendered in a map #3885

#### Bug Fixes

- Fix performance regression triggered when `Map` pitch or bearing is changed #3938
- Fix null pointer exception caused by trying to clear an `undefined` source #3903

#### Miscellaneous

- Incorporate integration tests formerly at [`mapbox-gl-test-suite`](https://github.com/mapbox/mapbox-gl-test-suite) into this repository #3834

**Comment by jmunowitch** [comment]
Existing UI tests that were just fixed (https://github.com/archesproject/arches/issues/1505) should give some level of confidence this won't break everything.

**Comment by jmunowitch** [comment]
This has been upgraded in the master branch, but this issue is still open.  I think @dwuthrich mentioned he noticed a bug with the stamen basemap after one of these mapbox-gl-js upgrades.

**Comment by chiatt** [comment]
@jmunowitch @dwuthrich Rob and I looked into the stamen basemap issue and it appears mapbox has recently pushed a fix for this. https://github.com/mapbox/mapbox-gl-js/pull/3944.  We will have to evaluate the next release (which should be out soon).
