### ISSUE TITLE
Move initial ontologies to config?

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#1519]
In trying to manage the set of terms available within the system, I replaced the CIDOC ontology with a new version that includes the 6.2.2 Monetary_Amount and related terms and removed the unused CRM extensions.  Assuming that we can't dynamically reload ontologies (?) I recreated the installation from scratch.  During packages setup, the initial migration errors as it cannot find the extensions here:

https://github.com/archesproject/arches/blob/master/arches/app/models/migrations/0001_initial.py#L25

Could these file paths be exported to settings.py, overridable in settings_local.py?
Or if there's required to be a master ontology with extensions, pick the master and then assume all other .xml files in the directory are extensions?

If there's a better way to manage this, please let me know :)

**Comment by azaroth42** [comment]
Closed by #1519, #1538?

**Comment by apeters** [comment]
fixed by #1538
