### ISSUE TITLE
Reclassify Elasticsearch as a dependency, not as part of the arches installation process

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1532]
### User Story
Users should have the option to install elasticsearch inside the app (as was common in v3), but this should not be documented as a requirement of the arches system architecture.

#### Acceptance Criteria
- [x] Update documentation to list ES as a dependency
- [x] Remove (or clearly characterize as optional) the ES install commands
- [x] Remove most elasticsearch commands from the packages.py operations (leave the ability to set it up, but make this separate from all other operations)
- [ ] Update graphic shown [here](https://github.com/archesproject/arches/wiki/Dev-Installation#system-architecture) to reflect these changes. EDIT: thinking of removing this section for now, as it does not take into account the app packaging that has been implemented.

**Comment by azaroth42** [comment]
As part of the documentation, explaining how to refer to an external Elastic Cloud instance would be greatly appreciated for institutions with centralized ES service provision.

**Comment by mradamcox** [comment]
@azaroth42 please let me know if you think more should be added here https://github.com/archesproject/arches/wiki/Installing-Elasticsearch

**Comment by apeters** [comment]
fixed in the latest
