### ISSUE TITLE
Shapefile Import

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1543]
Create command to import business data from a shapefile.

Should utilize mapping file that is can be created for each resource model, using the 'create mapping file' button in the graph manager UI.

**Comment by dwuthrich** [comment]
Note that an acceptable workflow would be to convert shapefile to CSV (using QGIS, specifying the geometry encoding as WKT).  This would then mean shapefile load is a CSV import with the required first step of using QGIS to convert to CSV

**Comment by apeters** [comment]
So, @dwuthrich is the task here to document the workflow above, or to actually allow for shapefile import?

**Comment by dwuthrich** [comment]
allow for import.  We can discuss the details

**Comment by mradamcox** [comment]
Would you guys mind discussing here? I am working on converting shapefiles right now, and would be interested to hear the development of this ticket.

**Comment by ryan86** [comment]
http://arches4.readthedocs.io/en/latest/import-export/#uploading-a-shapefile-to-arches

**Comment by dwuthrich** [comment]
meets requirements
