### ISSUE TITLE
Create a map layer style manager page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1550]
This is just a starting point.  Please talk to Dennis before starting work on this.  
mockup here: http://archesproject.github.io/mockups/arches_map_server_manager.html

**Comment by mradamcox** [comment]
Just a note that based on the mockup, a user will have comprehensive control over the style of features for each Resource Model. This is somewhat a duplication of the Appearance settings that a user can determine for a Resource Model in the Arches Designer.

![image](https://cloud.githubusercontent.com/assets/10427268/22528333/74e4face-e898-11e6-9491-4a82d8eb46ae.png)

It may make sense, depending on how this mockup is implemented, to remove the appearance tab in the Resource Model settings altogether, and direct the user to do all of the map styling here.

**Comment by mradamcox** [comment]
Just found that my comment above is covered in this issue #1264

**Comment by dwuthrich** [comment]
meets requirements
