### ISSUE TITLE
Report Printing CSS

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1551]
CSS is messed for printing (map rendering...).  Talk to Dennis

**Comment by robgaston** [comment]
@dwuthrich can you please add some details to this ticket?

**Comment by dwuthrich** [comment]
Print CSS should:

1. Remove Chrome from printed page (eg: Resource Model Identifier and recently added resource button shown at top of printed page)
2. Add Resource Name (as defined by Designation function) after Report Title
3. Remove geocode search bar and map tools icon from map
4. Ensure resource instance is centered in map window
5. Include border immediately above information groups (e.g.: Card Container Titles)
6. Printed report appears to include a second blank page.  Remove this.
7. Layout of data should mimic web page (e.g.: 2 column, not label above value as print css currently displays data).

**Comment by apeters** [comment]
the resource get's centered in the map when first opening the report, but users can then reposition the map as needed, this seems like the best of both worlds.
