### ISSUE TITLE
Card manager panel doesn't allow users to specify Relation to Resource like in the Card Container Manger

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1559]
![screen shot 2017-02-02 at 11 41 19 am](https://cloud.githubusercontent.com/assets/823773/22565346/9feb5b56-e93c-11e6-96a4-7c338ca46661.png)

The Card Manager is missing the above, which appears in the Card Container Manager.

**Comment by dwuthrich** [comment]
meets requirements
