### ISSUE TITLE
Default resource relationship type not automatically loading in relationship properties form

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1562]
The default relationship type must load in the relationship properties form when the resource editor page loads.

**Comment by chiatt** [comment]
@dwuthrich When the related resources page loads in the resource editor, `is related to` should automatically load in the relationship properties form as the default relationship type.  It wasn't doing that when I imported the skos concepts.  It should be working now, though.

**Comment by dwuthrich** [comment]
meets requirements
