### ISSUE TITLE
Link to edit a resource in the recently added table is not working for instances created in the UI after resources are imported

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1568]
To reproduce:

1. Create a new resource instance using the UI.
2. Check that the link is working properly by going to the Resource Manager page, selecting "Recently Added" and clicking the link to navigate to the resource editor. The link should bring you to the editor page for the selected resource.

3. Import resources using the command line: 
> - Import the Arches concept schema found at `db/schemas/arches_concept_scheme.rdf` using the UI
> - import the dropdowns schema found at `db/schemas/dropdowns.rdf`
> - load the resource models by running the command `manage.py packages -o import_json`
> - Add a primary name function to the Heritage Resource Model and select the `Name` nodegroup and create a template with just `<Name>` (you can exclude the Name Type node)
> - from the command line run `manage.py packages -o import_business_data -s tests/fixtures/data/csv/heritage_resource_model.csv` (it takes a few minutes)

4. Return to the resource manager, and test the link to the resource editor for the resource created in step one.

The link works for the imported resources, but not the resource created in the UI.

**Comment by robgaston** [comment]
@chiatt this appears to be fixed in the latest - please confirm

**Comment by chiatt** [comment]
@robgaston Yep - seems to be working fine now.
