### ISSUE TITLE
Navbar:  Add "recent edits" button as a default

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1573]
### Bug Report

The "recent edits" button should appear by default in the navbar for users with edit privileges

**Comment by mradamcox** [comment]
Do we currently have a way that user groups, especially membership to the edit group, is exposed directly to the templates?

**Comment by dwuthrich** [comment]
I believe that @apeters has a pattern in place for this

**Comment by mradamcox** [comment]
If so, no problem, if not, I'd just as soon wait until permissions are fully implemented throughout the app.

**Comment by apeters** [comment]
@mradamcox you should be able to use this:
{% if 'edit' in user.user_groups %}

**Comment by mradamcox** [comment]
Ok, great, thanks.
