### ISSUE TITLE
Missing requirement: SPARQLWrapper

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#1581]
The installation process does not fetch and install the rdflib SPARQLWrapper module, resulting in errors trying to use the Reference Data Manager

```
  File "/Users/rsanderson/Development/getty/arches/ENV/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/rsanderson/Development/getty/arches/arches_master/arches/app/utils/data_management/sparql_providers/aat_provider.py", line 23, in <module>
    from SPARQLWrapper import SPARQLWrapper, JSON
ImportError: No module named SPARQLWrapper
```

**Comment by apeters** [comment]
SPARQLWrapper should be included as part of the rdflib (https://github.com/RDFLib/rdflib/blob/master/requirements.txt) module (which is required by Arches, see https://github.com/archesproject/arches/blob/master/arches/install/requirements.txt).  

Maybe there was an issue with your install?

**Comment by azaroth42** [comment]
It installed okay other than that following the instructions in the wiki, and worked as expected after manually doing pip install SPARQLWrapper. Could be because I have rdflib installed in my site libs, but and hence it just used it, skipping over its requirements, but I don't have SPARQLWrapper installed at the site level?

**Comment by chiatt** [comment]
Added SPARQLWrapper to requirements.txt.

**Comment by veuncent** [comment]
I am still getting this error after a fresh pull when I load the RDM page.
The package does get installed:

``` 
Successfully installed Django-1.9.2 [snip] SPARQLWrapper-1.8.0 [snip]
```

Installation command:
```
. ${WEB_ROOT}/ENV/bin/activate &&\
	bower --allow-root install &&\
	python setup.py install
```

Error stack:
```
Internal Server Error: /concepts/857efa19-88e8-4744-9624-7746fb2cc6ff
arches           | Traceback (most recent call last):
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
arches           |     response = self.process_exception_by_middleware(e, request)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
arches           |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
arches           |     return view_func(request, *args, **kwargs)
arches           |   File "/web_root/arches/arches/app/views/concept.py", line 138, in concept
arches           |     'sparql_providers': get_sparql_providers(),
arches           |   File "/web_root/arches/arches/app/views/concept.py", line 71, in get_sparql_providers
arches           |     Provider = import_string(provider)()
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
arches           |     module = import_module(module_path)
arches           |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
arches           |     __import__(name)
arches           |   File "/web_root/arches/arches/app/utils/data_management/sparql_providers/aat_provider.py", line 23, in <module>
arches           |     from SPARQLWrapper import SPARQLWrapper, JSON
arches           | ImportError: No module named SPARQLWrapper
arches           | [20/Mar/2017 13:05:54] "GET /concepts/857efa19-88e8-4744-9624-7746fb2cc6ff?f=html HTTP/1.1" 500 16283
arches           | [20/Mar/2017 13:05:54] "GET /concepts/tree/semantic?_=1490033153584 HTTP/1.1" 200 12211
```

**Comment by chiatt** [comment]
Thanks @veuncent I'll look into it.

**Comment by chiatt** [comment]
@veuncent I'm not getting the import error when I do a normal installation and open the RDM. I'm not very familiar with Docker, but could the issue be specific to the Docker install?

**Comment by veuncent** [comment]
I'm still getting the error, can't seem to find any differences between my (Docker) install and the Arches requirements.

Could you please have a look at my Dockerfile (install script) to see if there is something missing? 
I think even without any Docker knowledge these scripts are easy to read, as it's basically a shell script.
https://github.com/cvast/arches/blob/1650_docker_support/Dockerfile 

Thanks, I appreciate it!
Vincent

**Comment by veuncent** [comment]
I found the culprit: I had a Docker volume laid over the ENV directory, which is where the python packages get installed (site-packages dir). Basically the packages I installed through `python setup.py install` were hidden by that overlaid volume. 

Errors are gone after removing this volume.

Sorry for the trouble,
Vincent
