### ISSUE TITLE
Authentication: Change landing page after user logs in

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1610]
### User Story

After user supplies login credentials, Arches should:

> return user to home page, update the navbar with links to pages that match their permissions.  For example, admins would see links to "Manage Data", "Arches Designer", "RDM"

> User then selects page to navigate to

**Comment by mradamcox** [comment]
@dwuthrich is this still an issue?

**Comment by dwuthrich** [comment]
@mradamcox thanks for the prompt.  meets requirements
