### ISSUE TITLE
UI Terminology: Change "Data Entry Forms" to "Menus"

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1613]
### User Story

The term "Forms" is a bit confusing, and could be taken to mean data entry forms.  To minimize confusion, we should use the more accurate term "Menu" to indicate that the user is managing collections of Cards as a menu entry in the Resource Editor

**Comment by mradamcox** [comment]
@dwuthrich Are you thinking that the term "form" should be removed from the app entirely?

**Comment by dwuthrich** [comment]
I propose that we use the term "menu" instead of our current use of "form".  I think menu is the more appropriate and descriptive term.  Making this change would allow us to use the word "form" in other ways (perhaps to indicate the data entry portion of a card) if we wish

**Comment by mradamcox** [comment]
Ok, as in "configure the menu for this resource model" instead of "create a series of data entry forms for this resource model". That makes sense to me. Would it be ok to refer to it elsewhere as the "data entry menu for this Resource Model"?

**Comment by dwuthrich** [comment]
Yes, your examples are spot on.

**Comment by adamlodge** [comment]
I realize that we are just talking about labels in the UI to make things clearer for end-users, and to that end I agree that this may improve things.  However, we should also weigh the fact that there is a "forms" table in the database that is consistent with what we currently mean by forms in the ui.  There is also probably quite a bit of code uses the term "forms" based on thinking to date.  Ideally, if we make this UI change, we would also modify all the backend stuff to be consistent.  Just wanna make sure we make the decision with eyes open.

**Comment by mradamcox** [comment]
That's a good point, because in the back end, forms would still exist as subset components of the "menu".

**Comment by dwuthrich** [comment]
I agree that we use the "forms" in a particular way in the backend.  Not sure that way we use terms in the code has to conform to the UI.

**Comment by dwuthrich** [comment]
For example, we use the word "tile" in a couple of ways: tileserver = geospatial data.  But tile also means an instance of a node group.  I think that both are ok, even though they refer to slightly different things

**Comment by mradamcox** [comment]
@dwuthrich I'm inclined to only make this change in the Manage... dropdown menu and the header of the current form manager, and leave "Forms" elsewhere in the UI. As in, "Add Form" to this resource model's menu. Partly for @adamlodge 's point about back to front consistency, and partly for expediency. If you want to go further, we could call "forms" "sections", as in "add section to menu" and "add cards to a section". This would require markup changes in quite a few places.

**Comment by dwuthrich** [comment]
@mradamcox At a minimum we should change the label in the UI under the "Manage..." menu and dropdown button, as well as in the header for the form manager.  FYI, I think usability and clarity of terminology in the UI outweighs the back to front consistency in this specific case.
