### ISSUE TITLE
Remove or Implement Tile Name in Card Configuration

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1617]
### User Story
Currently a user is able to enter a "Tile Name" in a Card's settings, when multiple values are enabled for that card.
![image](https://cloud.githubusercontent.com/assets/10427268/22891749/ef0599f8-f1d5-11e6-826d-817e577e0dcd.png)
This feature is not actually implemented in the rest of the app.

### Definition of Done
Before full documentation of the Card Designer can be finished, the Tile Name entry should either be removed (from the screenshot above as well as the card preview), or it should be fully implemented.

**Comment by dwuthrich** [comment]
meets requirments
