### ISSUE TITLE
Only Card Containers have the Make Visible and Make Active settings (top-level Cards don't)

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1618]
### User Story
Go to a Branch that uses a Card Container (like Place 2) and notice that when the Card Container is selected in the contents panel, both switches are shown
![pasted image at 2017_02_09 12_21 pm](https://cloud.githubusercontent.com/assets/10427268/22895688/0b675a20-f1e3-11e6-8c34-8ba8f5d53d7c.png)
Select a card inside this container, and no switches are shown
![image](https://cloud.githubusercontent.com/assets/10427268/22895937/df7ad8f0-f1e3-11e6-89c0-477037b4a4e6.png)
Finally, navigate to a simple Card (no Card Container) and you'll see that neither switch is shown.
![pasted image at 2017_02_09 12_21 pm 1](https://cloud.githubusercontent.com/assets/10427268/22895949/e7479fb4-f1e3-11e6-944a-6a43013345d6.png)

#### Expected Behavior
Card Containers: Both switches should be available to the Card Container, and "Make Card Visible" should be an option on each card within the card container (as per slack comment from @dwuthrich ).

Top-level Cards (simple branches as shown above): Both switches should be available to the Card.

#### Related Issues
It would make sense to address #1437 and #1617 at the same time as this issue.

**Comment by dwuthrich** [comment]
meets requirements
