### ISSUE TITLE
Rework Report Designer to allow only one report per resource model

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1622]
### User Story
Synopsis of an ongoing discussion: 

As a data manager, there is relatively little use for the ability to create multiple reports for a single resource model. The reason for this is that at any given time, only one report can be active, so switching between reports is a manual process, and not something data managers should be expected to do regularly. Multiple reports would be more useful if users with different permission levels were shown different reports based on their permission level, but this is not currently implemented.

One advantage to having multiple reports, though, is that a draft report could be disabled during development or testing. As a counterpoint to this, I'd personally point out that creating and modifying a report is a very simple and quick process (as far as I can tell) so it doesn't strike me as something that would need to be worked on over many sessions.

Anyway, there is currently no impedance to the use of the Report Designer in its current state, so this should probably be considered a proposed change, not one that is necessary to implement at this time.

**Comment by mradamcox** [comment]
I'd add that the back end provision for multiple reports attached to a resource is great, and should stick around, in order to allow the potential for implementing the above-mentioned permissions filtering.

**Comment by chiatt** [comment]
In the new Graph Designer, a resource model now has only one report.

**Comment by mradamcox** [comment]
Good point @chiatt, closing this ticket now.
