### ISSUE TITLE
Include date based concepts attached resources when doing date based searches

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1629]
For example: Cultural Periods specify a `to` and `from` date.
Resources that reference those cultural periods should be included in date based search results.

**Comment by dwuthrich** [comment]
This does not work as intended.  Adding an instance with a concept that has min_ and max_ years defined is not indexed into the time wheel, nor is the instance returned when filtering with traditional calendar from/to filter

**Comment by dwuthrich** [comment]
Note, traditional calendar to/from search does work.  Time wheel is not updated when user adds an instance referencing a concept that has min_ and max_years defined

**Comment by dwuthrich** [comment]
@apeters Getting the time wheel to work with concepts with min/max dates is highly desirable for the beta.  Just want to make sure this is prioritized for you

**Comment by dwuthrich** [comment]
works with time filter, not time wheel
