### ISSUE TITLE
Lay the ground work for a simple API and document it

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1638]
To support a simple API, the system at the very least needs to allow users to:
- Authenticate themselves in a secure manner 
- Perform basic CRUD operations against resources and tiles

**Comment by mradamcox** [comment]
Please put documentation in this new wiki page https://github.com/archesproject/arches/wiki/Using-the-Arches-API (for now at least).

**Comment by apeters** [comment]
duplicate of #2783
