### ISSUE TITLE
As a developer and end-user I want to be able to run Arches inside a Docker container so that the application's installation is simplified, it can run on any server and it is better protected through the isolation from its host

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#1650]
### User Story

Docker is the world’s leading software containerization platform: https://www.docker.com/ 

Being able to run Arches inside a Docker container:
 - Eliminates the installation process from the end-user side: one can simply download the Arches Docker image from hub.docker.com and run the container.
- Keeps your system clean and provides a stable environment that is the same wherever you run it.
- Enhances security: the container Arches is running in is isolated from the host machine. 

Docker images are usually published to Docker Hub. From here, any user can download our Docker images. The Arches Project should have an official account here. Additionally, an automated build should be set up on Docker Hub that is triggered by check-ins on GitHub.   

#### Acceptance Criteria
- [ ] Must have a Dockerfile, which builds the container without errors. The resulting Docker image runs Arches without errors.
- [ ] Must have a docker-compose.yml file. This helps you set up a complete environment, running Arches, Postgres, Elasticsearch and Nginx containers.
- [ ] The Arches Project has an official account on Docker Hub.
- [ ] The Docker Hub account is set to automatically build Docker images and create Docker image tags when code is checked in to GitHub.  This build should be triggered by check-ins on the master branch, as well as by the creation of new tags.  
    - Builds from the master branch will have the Docker image version 'master' (e.g. 'arches:master').
    - Builds from tags will have this tag name as Docker image version (e.g. 'arches:4.0').
    - Additionally, the latest GitHub tag will have the Docker image version 'latest' (e.g. 'arches:latest')
- [ ] The image should kick off unit tests when running in DEV mode (set through and environment variable).
- [ ] The documentation shall instruct users how to build and run the image.

#### Definition of Done
Arches can run without errors in a Docker container. Users can download this image from Docker Hub.

**Comment by veuncent** [comment]
P.s. I am working on this :) More soon.

**Comment by dwuthrich** [comment]
@veuncent Thanks for adding such a nice, concise ticket.  Very much looking forward to seeing this implemented!

**Comment by jmunowitch** [comment]
I consider this ticket complete
