### ISSUE TITLE
Importer: Importer fails without log

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1653]
### User Story

When attempting to import a csv file into Arches, if there's a problem Arches fails with:

(ENV)DRW-MacBook-Pro:arches4 dwuthrich$ python manage.py packages -o import_business_data -s GLHER_Activities.csv -c GLHER_Activities.mapping
operation: import_business_data
package: arches
'ResourceID'
Import Errors Found
Time to import_business_data = 0:00:00.014979

User is not alerted in any way to what the import errors are, and therefore can't fix the problem

Arches should write the errors to a log and alert user to location of error.log

**Comment by chiatt** [comment]
@dwuthrich Errors are now recorded to a log file in arches/logs.  I also added a print statement that writes out the stack trace.

**Comment by dwuthrich** [comment]
running "python manage.py packages -o import_business_data -s GLHER_Activities.csv -c GLHER_Activities.mapping" does not fail when the referenced .csv or .mapping files do not exist in the folder

**Comment by dwuthrich** [comment]
Running import_business_data with following command

(ENV)DRW-MacBook-Pro:arches4 dwuthrich$ python manage.py packages -o import_business_data -s GLHER_Activities.csv -c GLHER_Activities.mapping
operation: import_business_data


Results in:
package: arches
Traceback (most recent call last):

  File "/Users/dwuthrich/arches/arches4/arches/app/utils/data_management/resources/formats/csvfile.py", line 219, in import_business_data
    self.save_resource(populated_tiles, resourceinstanceid, resources, target_resource_model, bulk)

  File "/Users/dwuthrich/arches/arches4/arches/app/utils/data_management/resources/formats/csvfile.py", line 136, in save_resource
    newresourceinstance.save()

  File "/Users/dwuthrich/arches/arches4/arches/app/models/resource.py", line 76, in save
    self.index()

  File "/Users/dwuthrich/arches/arches4/arches/app/models/resource.py", line 130, in index
    se.index_data('resource', self.graph_id, JSONSerializer().serializeToPython(document), id=self.pk)

  File "/Users/dwuthrich/arches/arches4/arches/app/search/search.py", line 166, in index_data
    raise detail

RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [geometries.features.geometry]')

No import errors
Time to import_business_data = 0:01:04.028366

Note that importer reports on parsing error, but also says no import errors encountered.  Executing this command did not generate a log file

**Comment by dwuthrich** [comment]
meets requirements

**Comment by dwuthrich** [comment]
meets requirements
