### ISSUE TITLE
Time Filter fails when trying to relate resources in Resource Editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1656]
### Bug Report

Recreate issue:
1. Create (or open) a resource instance in the Resource Editor.  
2. Press green "Related Resouces" button in the upper right
3. Press the time filter button
4. Note that neither the time wheel nor the "Type" dropdown in the time filter work properly

This issue does not appear in the Search page.  Both time wheel and time filter operate as expected from the Search page

**Comment by robgaston** [comment]
I cannot reproduce this - I think it is fixed in the latest.

**Comment by dwuthrich** [comment]
meets requirements
