### ISSUE TITLE
Add Related Resources to Report Templates

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1657]
### User Story
Currently, report templates don't include a section that summarizes related resources. As a user, I would consider this a **critical** issue, because v3 did have that section.

A good **enhancement** would be to include the related resource graph at the bottom of report templates, instead of the list the v3 included by default. Perhaps this would be easier than making a new block of markup, I'm not sure.

#### Acceptance Criteria
- [ ] Reports templates (I'd say all three of the current templates) have a related resources section at the bottom that 
- [ ] Unit Tests passed
- [ ] Documentation

**Comment by dwuthrich** [comment]
At a minimum, the related resources section of the report should list related resources in a way similar to the v3 report.  Agree that an enhancement would be to include the related resource force-directed graph

**Comment by chiatt** [comment]
I've created a ticket regarding the suggestion of adding the force directed graph #2184
@dwuthrich Should a user have the option to publish the related resources section using the Report Manager? Currently it will show up in every report.

**Comment by dwuthrich** [comment]
meets requirement
