### ISSUE TITLE
Develop recommendations for how Arches will be run in a Production environment.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1662]
Assuming that all dependencies have been loaded (postgres, elasticsearch, etc...), how will people run Arches in Production? What's next after users have pip installed Arches? 

Will users have to then create a wrapper Django app and set that as one of the "Installed Applications" in settings.py?
Will users have to run an **Install Arches** command similar to what was provided in v3?

What ever is decided, it needs to be **documented and tested** and needs to support the following.
- [x] Users need to be able to install and run their own datatypes
- [x] Users need to be able to install and run their own functions 
- [x] Users need to be able to run the app from a root url (eg, http://localhost/, http://www.hpla.org/)
- [x] All command-line commands (business data load, graph load, etc..) need to be supported

**Comment by mradamcox** [comment]
I would add the need for some basic template customization, background images, head title, favicon, etc.

**Comment by apeters** [comment]
recently added resources doesn't seem to be returning any results

**Comment by mradamcox** [comment]
Here's some documentation I've developed along these lines. https://github.com/archesproject/arches/wiki/Creating-an-Arches-Project
Any feedback welcome. This content can make its way to readthedocs eventually.

**Comment by apeters** [comment]
@chiatt was this fixed?

> recently added resources doesn't seem to be returning any results

**Comment by chiatt** [comment]
@apeters Yeah - the project templates just needed updating. The script that moves files from arches app to the project template directory helped resolve it.

**Comment by apeters** [comment]
meets requirements
