### ISSUE TITLE
Confirm (and script) installation of dependencies on Windows

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1664]
Just like we have scripts to install dependencies on Linux, we should develop a script to install dependencies on Windows.

This assumes that for now, our recommendation for Windows users is a completely native solution (as opposed to using **Bash on Windows** or **Docker**, etc...)

**Comment by mradamcox** [comment]
FYI, as far as I can tell, postgres and postgis are best installed with the EnterprisDB GUI installers found here: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads#windows, i.e. no great way to do it with a script unless you build from source.

**Comment by jmunowitch** [comment]
I know @mradamcox has been working on something like this...

**Comment by apeters** [comment]
@mradamcox is there any update on this?

**Comment by mradamcox** [comment]
I haven't pursued this further, based on what I mentioned in my comment above. I have scripted certain aspects of the Python side of things, here for example: https://gist.github.com/mradamcox/e66f5008a72c1896003ecc785cb643fe, but that is no longer up-to-date... It was made before the project/package architecture, still uses bower, etc.

**Comment by mradamcox** [comment]
Docker has been talked about a lot as a recommendation for native installs on Windows, and @veuncent would be the best one to talk about that, as I have not pursued docker locally.

**Comment by mradamcox** [comment]
This is a promising step toward a headless installation of postgres on windows: https://www.openscg.com/bigsql/package-manager.jsp/

**Comment by chiatt** [comment]
As @mradamcox suggested above, Docker can be used to install dependencies on windows. Containers for those dependencies can be found here: https://github.com/archesproject/arches-dependency-containers
