### ISSUE TITLE
Map Digitizing Tools: Add "geojson" type

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1665]
### User Story

Arches provides digitizing tools as part of the map widget.  These include digitizing point, line, and polygon geometries.

We should add an additional entry for the digitizing tools that would allow a user to cut and paste geojson into a text box to define a geometry.  

Implementation would be to add a "Geojson" entry under the Polygon entry in the Map Tools tab in the map widget.  Clicking on the GeoJSON entry would reveal a text area that would accept geojson that a user can paste into the text area.

**Comment by chiatt** [comment]
@dwuthrich Clearing the geojson textarea is a bit tricky and still needs to be done. I've created a separate ticket for it.  #1861

**Comment by dwuthrich** [comment]
meets requirements
