### ISSUE TITLE
Map Widget: Wire up new/edit/delete buttons in map widget alert panel

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1667]
### User Story

Arches does a poor job of allowing users to toggle between creating new geometries and editing existing geometries (e.g.: move, edit).  

The alert box (visible when user is managing geometries) now contains buttons that will communicate the digitizing state more clearly to the user.  By default, the "new" button is enabled, allowing users to continue to create new geometries

Clicking the "edit" button should update Arches into the "edit geometry mode", which allows users to move/edit geometries.  After clicking the "edit" button, the next geometry will be toggled into edit mode and the edit button state is updated.

Clicking the "delete" button should update Arches into the "delete geometry" mode.  After pressing "delete", the next geometry the user clicks on will be deleted.

**Comment by dwuthrich** [comment]
@chiatt Delete no longer works.  I can't delete any geometries

**Comment by chiatt** [comment]
@dwuthrich Thanks - looking into it right now.

**Comment by dwuthrich** [comment]
meets requirements
