### ISSUE TITLE
Clicking on a node in a graph in some instances causes the node to think it's been edited.  Discarding the edit is problematic

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1684]
http://recordit.co/ZRwYAKascs

**Comment by robgaston** [comment]
Keep in mind - this may not be a bug in the code, but rather in the resource model json files.
That is - the code may have changed in terms of the schema it is expecting and the json files may not have kept in sync.

This is particularly insidious when it comes to changes to expect json field schemas as the database does not enforce schema on these fields in any way (for example: `nodes.config`, `cards_x_nodes_x_widgets.config`, `functions_x_graphs.config`, etc.).

In general, developers have tried to keep these json files in sync, but when things are moving fast it's easy for things to fall through the cracks (or regression to occur in the json files themselves).  I've seen it before, so it wouldn't surprise me if that was the case here. 

In many cases, these `config` columns have a corresponding `default_config` column in a related table that could potentially be used to check the schema of these objects on import from a json file.

**Comment by mradamcox** [comment]
I did a little testing (because I remember coming across this a while ago and thought I'd made a ticket but can't find it) and I think @robgaston is right. When using the default branches and models, I get this behavior, but I created a new branch and added it to a new resource model I didn't. Maybe a little inside editing of the HIP models and branches json would be the way to solve this.

**Comment by robgaston** [comment]
There was actually a small issue w/ node config management that caused some issues, but there is also an issue w/ existing configurations  as loaded.  Currently, the import allows you to import concept ids in the node configurations that don't exist in the db.  When this happens, the user will need to save a new concept id in the UI to prevent the node form from seeing data as being out os sync (dirty).

**Comment by apeters** [comment]
fixed
