### ISSUE TITLE
Arches Import: Support Multipolygons

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1694]
### Bug Report

Testing import with multipolygons as WKT appears to break importer

**Comment by dwuthrich** [comment]
Note that we should probably support MultiLineString and MultiPoint geometries as well

**Comment by ryan86** [comment]
I've tested this with the following three geometries. They all imported successfully, although they have to be quoted in the csv file(as does any value that contains commas). I will make sure this is in the import documentation.

MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)),((20 35, 10 30, 10 10, 30 5, 45 20, 20 35),(30 20, 20 15, 20 25, 30 20)))

MULTILINESTRING ((10 10, 20 20, 10 40),(40 40, 30 30, 40 20, 30 10))

MULTIPOINT (10 40, 40 30, 20 20, 30 10)

**Comment by apeters** [comment]
meets requirements
