### ISSUE TITLE
Update Install Documentation for Arches

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#1696]
As we are going through the install process for the Liverpool workshop on Windows 10 machines, we are running into a few hiccups that should be documented:

- [x] Considering upgrading the virtualenv version used to 15.*
- [x] Pip upgrade needs to happen within the virtual environment: `install --upgrade pip` (Dependant on virtualenv update)
- [x] Setuptools upgrade needs to happen, also within the virtual environment: `install --upgrade setuptools` (Dependant on virtualenv update)
- [x] On Windows, Shapely does not install through`python setup.py install`.  It needs to be installed via the Wheel that is on this site: http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
- [x] Update Prereq for JDK.  With Windows, the JAVA_HOME needs to be added to PATH
- [x] Update documentation on the new version of ElasticSearch (See link [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/windows.html))
- [x] Consider linking to the MacOS install gist I created [here](https://gist.github.com/jmunowitch/35eb1d20a0b9cbf86f4b0eb4b167d43a)

**Comment by jmunowitch** [comment]
In our V[3 documentation](http://arches3.readthedocs.io/en/latest/getting-started/#installing-arches) and [V4 documentation](https://github.com/archesproject/arches/wiki/Dev-Installation), it instructs the user to pip install virtualenv. In the V4 documentation, the version of `virtualenv` is pinned to 13.1.2 which includes the following python libraries by default:
```
Package    Version
---------- -------
pip        7.1.2
setuptools 18.2
```

With `virtualenv`version 15.1.0, the following python libraries are included:
```
Package    Version
---------- -------
pip        9.0.1  
setuptools 34.3.0 
```

Since we seem to have to update pip and setuptools in the Windows install by hand, would it be worth using `virtualenv` version 15.1.0?

Also of note, there is a separate process that could install virtualenv alltogether in the [setup.py](https://github.com/archesproject/arches/blob/master/arches/setup.py#L82) that calls the [virtualenv.py](https://github.com/archesproject/arches/blob/master/virtualenv/virtualenv.py) file to install a virtual environment. this method is is currently pinned to version 1.11.2, but the method here is not really documented anywhere.

What should the suggested install for `virtualenv` be?

**Comment by jmunowitch** [comment]
Also of note, I have tested out version 15.1.0 on my Mac environment, and everything seems to be working for me at first glance, and all my tests are passing as well

**Comment by mradamcox** [comment]
I think it would be prudent to use this command to upgrade pip
`python -m pip install --upgrade pip`
instead of the normal one you have listed above. You may have been able to run `pip install --upgrade pip` without any trouble, but I came across this issue awhile ago https://github.com/pypa/pip/issues/3804 (while installing arches in the past) and so I think it would be better to recommend the workaround right off the bat.

**Comment by jmunowitch** [comment]
If an up to date VirtualEnv is installed, does pip need to be upgraded?

**Comment by jmunowitch** [comment]
Also, FYI: I added a new item in the main ticket: Considering adding a link to the gist I created for a MacOS install (on a completely new system).

**Comment by mradamcox** [comment]
@jmunowitch As far as I can tell, upgrading to virtualenv 15 solves all of the pip upgrade issues, which is great, so I'll update relevant documentation along those lines.

**Comment by jmunowitch** [comment]
@mradamcox: That is great.

Should we also update the documentation to say that Python 2.7.13 is suggested?

**Comment by mradamcox** [comment]
@jmunowitch could you check this page out now and let me know what you think? https://github.com/archesproject/arches/wiki/Dev-Installation
I put in placeholders to link to the dependencies installations on different systems, but don't think that needs to be filled out to close this ticket.

I added a section called Getting Started that has a list of commands to install the test data that comes with Arches.

I'm also going to close this issue now https://github.com/archesproject/arches/issues/1290.

**Comment by jmunowitch** [comment]
This looks pretty good. 

For MacOS under Elasticsearch: if we are pushing them to use the gist script to install, the script takes care of running Elasticsearch through brew services.

Under the Windows section for Elasticsearch: The link to the CLI is not working.

Under System Architecture: the arches-in-production link is broken as well.

**Comment by mradamcox** [comment]
Thanks, I will check these issues out when I get a chance.

**Comment by jmunowitch** [comment]
@mradamcox: Checking in. Should this be closed now?

**Comment by mradamcox** [comment]
Yeah. I just fixed those links (thanks for catching that).

For the macOS stuff, I'll let you add the notes to that, describing how the ES install is handled.
