### ISSUE TITLE
Display of search results on map

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1697]
We need a way to display search results on the map.

First, the results in the list should get points (markers) on the map, assuming that the end user has read privileges to these nodes.  Mouseover of markers or list items should highlight the corresponding other.  Also, the "map" link in the search results list should only show for items w/ a marker and clicking on it should zoom to the marker.

Additionally, we should try to provide some summary of the entire results set.  Some ideas:
- hex binned results, extruded by count
- display the top _n_ results on the map when the first page is loaded
- display an extent polygon showing the approximate extent of the result set

**Comment by robgaston** [comment]
@dwuthrich has indicated that hex binning is the strategy that we should aim for when it comes to displaying the entire result set.  Towards that end, I've come up with a proposed solution for displaying search results using hexagonal binning:
- add a `geo-point` centroid to resource index (or possibly create a new index?) — this is because the Geohash grid aggregation only works w/ points
- on initial load of search results (as we did previously w/ ids) aggregate  results using Geohash grid aggregation (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html), and return the aggregation results to the client.
- on the client, parse points from each GeoHash cell (https://github.com/chrisveness/latlon-geohash) and create GeoJSON features with document count as a property
- using turf, convert grid of points into a hex grid (http://thinkingspatial.com/mapbox-gl-hex-bins-example/)
- add to layer in mapbox gl js and style w/ extrusion on count (and also color ramp) (https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-fill-extrusion)

**Comment by dwuthrich** [comment]
Latest commit appears to have broken map display due to problem with finding styles.

See:  http://recordit.co/TfDQwBCK8o

**Comment by dwuthrich** [comment]
meets requirements
