### ISSUE TITLE
Related Resources Force Directed Graph: Update information panel

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1713]
### User Story

An information panel appears when a user's cursor hovers over a node in the related resource forced directed graph.  

Instead, the force directed graph panel should implement a list of all the nodes in the graph using a widget like the map listing widget in the Map Layer Manager.

In the force directed graph panel, the node listing widget will appear on the right side of the panel (similar to the map tools widget when it has been expanded).

When the cursor hovers over a node, the appropriate entry in the node listing widget highlights (and vice versa).  Clicking on a node adds new related nodes to the graph, and should load new nodes into the listing widget

**Comment by dwuthrich** [comment]
I have added appropriate UI to support listing resource nodes in the side panel.  This can now be wired up to support the functionality described above

**Comment by apeters** [comment]
@dwuthrich can you provide a link to the Mockup you're referring to in the above comment.

**Comment by dwuthrich** [comment]
@apeters just click on the force directed graph link in the related resources panel and you will see it

**Comment by dwuthrich** [comment]
meets requirements
