### ISSUE TITLE
Search: Search by map extent breaks when toggling to full screen mode

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1717]
### Bug Report

Steps to reproduce:

1. Open search page, navigate to map query tools, select "search map extent"

2. Click the button near the top of the search results panel that toggles the map into full-width mode

3. Observe that Arches crashes

**Comment by apeters** [comment]
Arches actually doesn't crash (or at least it didn't for me, but rather re-runs the query for every change in the size of the map as the panel slides open/closed)  You'll notice that 100's of calls get triggered.  

What we should do is suspend the triggering of the query on window resize until after the resize is complete

**Comment by dwuthrich** [comment]
meets requirements
