### ISSUE TITLE
Arches Designer data entry vs "Normal" Resource Data Entry

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1718]
There should be a more obvious pathway from the landing page to the resource data entry screens.

As a user whose job might be to simply enter/edit resource data within resource models that have already been designed, it would be nice to NOT have to first go through the Arches Designer to access the button that allows me to enter resource data.  

At risk of being prescriptive, it seems we might remove the "manage data" link from the splash page in favor of (at least) two links: 
1. Arches Designer
2. Enter Resource Data  

Access to these links can then be controlled by roles that the user is associated to.

**Comment by dwuthrich** [comment]
Closing this ticket as it appears to be satisfied in latest UI
