### ISSUE TITLE
Resource Editor: Add Resource Display Name to Title Bar

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1721]
### User Story

As a resource instance editor I would like to see the instance display name (as defined in the "Define Resource Descriptors" Function) displayed next to the Resource Editor label in the Resource Editor page.

For instances that haven't been named yet, use "Unnamed Resource" as the default string

**Comment by robgaston** [comment]
@mradamcox are you working on this? Let me know - if you aren't, I was thinking I'd knock this out this morning. Thanks

**Comment by mradamcox** [comment]
@robgaston just saw this, doing it now... thanks for checking in.

**Comment by mradamcox** [comment]
Initial work on this is in the 1721_display_name branch. However, an potentially unfavorable result is demonstrated in the screenshot below. 
![image](https://cloud.githubusercontent.com/assets/10427268/24063453/ad5bf314-0b2d-11e7-85ef-03273f55a077.png)
Which brings up the fact that there are 3 contexts for a resource when it comes to a display name:
1. no function has been defined ("undefined" is currently returned)
2. a function has been defined, but no name or not all of the nodes in the nodegroup have been entered. The result is the function is run returning the template, as pictured above.
3. a function has been defined and name saved, giving the desired results.

Context 2 should probably be fixed before fully completing this ticket.

Unassigning myself as I need to focus on other Arches-related things...

**Comment by dwuthrich** [comment]
@mradamcox This is not an undesirable outcome.  In fact, it is exactly the outcome that we want as it makes clear to the data entry person that expected data hasn't been entered yet.

**Comment by mradamcox** [comment]
@dwuthrich OK, in that case I'll put in a pull request soon and you can check it out. The ticket says that resources that don't have a name should return "Unnamed Resource", which will not entirely be accomplished by the pull request. "Unnamed Resource" will only be returned if the resource model doesn't have a descriptor function applied to it (context 1 as described above).

**Comment by dwuthrich** [comment]
meets requirements
