### ISSUE TITLE
TIme Wheel: bins should be ordered by time

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1733]
### Bug Report

Time bins are ordered randomly within a parent bin.  Instead, bins should be ordered by time clockwise, with earliest time bin first as follows:

Parent bin: 1900 - 2000
Children bins: 1900-1909, 1910-1919, 1920-1929, etc.

**Comment by dwuthrich** [comment]
Earliest time should start at the "12 o'clock" position, with newer time intervals appearing clockwise.  Current version of the time wheel shows City of Lincoln dates with the earliest interval starting at about 2 o'clock

**Comment by apeters** [comment]
Made a ticket(#2704) out of the above comment.

**Comment by chiatt** [comment]
Loaded the HER data and the order and direction (increasing clockwise) are correct.
