### ISSUE TITLE
Create widget to upload and render contents of data files on x-y graph

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1738]
http://archesproject.github.io/mockups/d_sample_project_datasets.html
Use Case:
1. A user uploads a zip file of data files (@dwuthrich said he might be able to provide or get some example files).  
2. The system unzips the files and presents them to the user in a table like format.  
3. A user then clicks a file in the table and a graph of the data is presented to the user.
4. The data is assumed to be x-y formatted data.
5. A user can hover over the graph and a cursor showing the data values follows the users mouse.
6. It should be possible to zoom the extents of the graph to see more or less detail.

![screen shot 2017-03-01 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/823773/23481134/33c065cc-fe7f-11e6-947d-6cbddcd6fa3e.png)

**Comment by dwuthrich** [comment]
meets requirements
