### ISSUE TITLE
Create IIIF viewer and annotation widget

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1740]
Use Case:
1. A user is provided a list of available IIIF(http://iiif.io/) services to select from.
2. A user selects a an IIIF service and then the widget shows the image in the IIIF viewer widget.
3. A user can then add annotations.  A single annotation can consist of many different things but most likely would include a spatial object that references the image selected in step 2, as well as any number of additional metadata (text, rich-text, dates, etc...)

Mockup and more details to follow.

**Comment by robgaston** [comment]
This will require implementing a custom data type as well, most likely.

**Comment by dwuthrich** [comment]
meets requirements
