### ISSUE TITLE
Summernote Editor: Cut and paste text results in HTML, breaks save

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1752]
### Bug Report

Pasted text into the summernote rich text widget retains HTML tags, breaks save.

Probable fix: http://stackoverflow.com/questions/30993836/paste-content-as-plain-text-in-summernote-editor

**Comment by apeters** [comment]
I just tested this out and I couldn't reproduce the error.

**Comment by dwuthrich** [comment]
Try cutting and pasting a paragraph from Word.  Text appears, but save fails

**Comment by apeters** [comment]
I don't have Word, so I can't really reproduce this.  I'll see is someone else can.

**Comment by robgaston** [comment]
this may help: https://github.com/StudioJunkyard/summernote-cleaner

**Comment by dwuthrich** [comment]
meets requirements
