### ISSUE TITLE
Graph Designer: Function Manager not consistently showing filter bar

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#1760]
On a number of resources, the 'Define Resource Description' function has no filter bar in the 'Card Name' dropdown on all three tabs:

![actor resource model - functions](https://cloud.githubusercontent.com/assets/7893339/23373649/ed5efdaa-fcee-11e6-98a5-59666b7620a2.png)

Resource Models where filter bar is missing:
- Activity
- Actor
- (Arches Config)
- Historical Event
- Information Resource

#### Expected Behavior

In Heritage Resource Model, this filter bar is present:
![heritage resource model - functions](https://cloud.githubusercontent.com/assets/7893339/23373698/242f6090-fcef-11e6-9509-5a593345c2fb.png)

The filter bar is present in these Resource Models on all tabs:
- Heritage Resource Group
- Heritage Resource

I expected the same for the other Resource Models.

#### Steps to Reproduce (for bugs)

1. Navigate to /graph/
2. Click 'Manage' of e.g. Actor Resource Model --> click 'Manage Functions'
3. Select 'Define Resource Descriptors'
4. Click the 'Card Name' dropdown 

#### Your Arches Information

* Version used: master branch. Last commit: ae145f349c4519a7a24b3a6d64a5d86af9c6ba47
* Browser Name and version: Google Chrome Version 56.0.2924.87
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by apeters** [comment]
This is by design.  If the list is short enough (I think 10 items or less in this case) then the search/filter is not employed.
