### ISSUE TITLE
NoReverseMatch Exception on 'Add New Resource'

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#1763]
### Bug Report
I'm getting an exception when I try to create a new resource.

#### Expected Behavior
I expect to be led to the Resource Model's edit form when I click 'Add New Resource'.

#### Current Behavior
This exception happens:

 `NoReverseMatch at /graph/fad0563b-b8f8-11e6-84a5-026d961c88e6/add_resource
Reverse for 'Resource Editor' with arguments '()' and keyword arguments '{'resourceid': UUID('9d300572-027f-11e7-aa3e-0242ac110003')}' not found. 0 pattern(s) tried: []` 

The (empty) resource does get created, because when I go back they show up in the search results.
I am then able to click on the resource and get into edit mode and work as usual.

#### Steps to Reproduce (for bugs)

1. Click 'Add New Resource'
2. Click 'Activity Resource Model' (or any other resource)

#### Your Arches Information

* Version used: master branch, SHA 2124f444a7dd0e18737be6caa179950c3abfa288
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by apeters** [comment]
I can't reproduce this bug.  Can you reverify @veuncent ?

**Comment by veuncent** [comment]
Fixed after a fresh pull, thanks!
