### ISSUE TITLE
Search: Map link on a search result item only centers map

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1775]
### Bug Report

When pressing the map link in a search result item, the map centers on the selected resource instance at the current zoom scale

#### Expected Behavior

When selecting the map link, the map should both center on the instance and zoom to the instance

**Comment by robgaston** [comment]
@dwuthrich what should the map do for resources w/ a single point geometry? possibilities:
- zoom to a defined zoom level
- do what it does currently
- something else?

the Liverpool data will be helpful here for us in testing this as all the geometries in our current test data set are points

**Comment by dwuthrich** [comment]
@robgaston This appears to be functional for editing geoms, as well as for showing geom in reports. If we need to, we should define a zoom level (perhaps this is a global setting or set for a resource in the map manager) for points.  For lines/polygons we can zoom to the MBR and then back out a bit.

**Comment by dwuthrich** [comment]
meets requirements
