### ISSUE TITLE
Map Search: Spatial Search (buffer) using line crashes Arches

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1777]
### Bug Report

Trying to define a spatial search by digitizing a line crashes Arches

**Comment by apeters** [comment]
I can't reproduce this error. Can you reverify?

**Comment by dwuthrich** [comment]
Yes, repeat digitizing line and buffering at small distances (1000 ft).  Then buffer with large distance (10,000 ft) and I can crash Arches server.

Using large buffer distances seems ok with points/polygons

**Comment by apeters** [comment]
When you say crash do you mean that a 500 error is thrown?

**Comment by apeters** [comment]
Maybe we should limit the size of the buffer, because at some point I get errors with the buffer polygon having self intersecting geometry and core C api errors.  

I was thinking of trying to clip the buffer to the world extents, but that's also proving problematic.

**Comment by dwuthrich** [comment]
We should definitely limit the size of the buffer.  An arbitrary number is fine.  10km?  100km?  Something reasonable and also very unlikely to cause a crash.

**Comment by apeters** [comment]
I currently have the buffer limit set to 100,000 ft ~= 30km.

**Comment by dwuthrich** [comment]
That seems quite reasonable as a default

**Comment by dwuthrich** [comment]
This appears to be machine-dependent and possibly related to a local version of a C++ file
