### ISSUE TITLE
Map: Hide popups when layer is hidden

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1779]
### Bug Report

The search results layer appears by default, even when no query has been submitted.  Search results overlay should only appear after user defines a filter.

**Comment by robgaston** [comment]
@dwuthrich the search page always shows a result set, so even before the user has entered query parameters there are results to show on the map.  I think that because of this, it's nice to see the layer.  

For example, you can see markers on the map as you page through results, even if that result set is the entire database.

**Comment by dwuthrich** [comment]
pop up for resource instances should always appear when user's cursor hovers over the geometry on the map, even if the resource instance isn't currently paged

**Comment by dwuthrich** [comment]
@robgaston To be clear, if the resource layer is displayed on the map, then a pop up should appear when the user's cursor hovers over the geometry.  Only hide the popup for a resource layer when the layer overlay has been removed or is no longer displayed

**Comment by robgaston** [comment]
@dwuthrich The behavior that you described is what I had implemented.  I just tested this locally on my machine and on http://dev.archesproject.org/search and it seems to be working as you described.  Perhaps you need to rebuild your database locally.

**Comment by dwuthrich** [comment]
@robgaston You did indeed implement it correctly.  Problem was I needed to clear the map cache for the resource I am testing on for the desired functionality to take effect

**Comment by robgaston** [comment]
I did catch a problem here, actually - mouse interaction with features on the map can be obscured by transparent features that overlap them! (for example map, points below search markers)

I'll find a work around there.

**Comment by robgaston** [comment]
the above mentioned issue is fixed by #1831
