### ISSUE TITLE
Search Map:  Display of same resource model geometry changes with zoom level

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1782]
### Bug Report

For a resource model, display of the same geometry changes with zoom level.  See: http://recordit.co/dKYf385Rl5

Note that there are 3 resource instances, each with a single polygon geometry.  Visibility of a geometry is somehow affected by zoom scale.

**Comment by robgaston** [comment]
@dwuthrich is it possible that you have cached tiles on your system?

**Comment by dwuthrich** [comment]
@robgaston Yes, this occurs with caching turned on for the resource model

**Comment by robgaston** [comment]
it may be that you have tiles that are cached that did not get cleaned properly in the process of changing settings, etc.  For example, if you had automatic cache clearing off while editing some data, then turned it on later.

in cases like this, the cache can fall out of sync with the data, and an admin (ie, you) would have to clean the cache themselves.  This can easily be done by deleting the layer's cache folder in `arches/app/tileserver/cache/{node id}`.

If automatic cache clearing is not on and caching is enabled, then the cache will be falling out of sync with the latest data.  Tiles are generated as requested, so unless you seed the cache zoom levels may cache slightly different data if users are adding data between clearing the cache.

In a production environment, I imagine an administrator (perhaps through a bit of trial and error) will find good compromises on these settings for their implementations, which would likely include routine cache clearing as part of a cron job/scheduled task.  With time, I hope we (and the wider community) can provide good guidance here.

Note: all of this only applies to the resource model tileserver layers (not to search results shown in the results layer)

**Comment by dwuthrich** [comment]
That's really good information, and should probably be rolled into our documentation (or a knowledge base).  Seems like we're getting close to considering a more formal knowledge base system.
