### ISSUE TITLE
Tile Cache config is throwing error [Windows]

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#1817]
### Bug Report
When attempting to use the tileserver cache, an error is thrown.

#### Expected Behavior
This should work on Windows as well as it does on a Mac/Linux machine.

#### Current Behavior
I believe the The bug is based upon the path creation 
 this error is received:
```
KnownUnknown: Disk cache path path must be a local file path, absolute or "file://", not "C:\arches\arches\tileserver\cache".
```
![Tileserver Cache Error](https://cloud.githubusercontent.com/assets/1542229/23962192/87cc3eac-096a-11e7-9b74-03b3557b2843.png)

#### Steps to Reproduce (for bugs)
1. Install on windows
2. import a layer into tileserver such as `python manage.py packages -o add_tileserver_layer -m arches/tileserver/hillshade.xml -n hillshade`
3. attempted to access the layer, such as `curl -I localhost:8000/tileserver/hillshade/11/324/790.png`

#### Your Arches Information

* Version used: Latest Master
* Browser Name and version: Not Applicable
* Operating System and version (desktop or mobile): Windows 10 64 bit

**Comment by jmunowitch** [comment]
If you hard code the URI, you can get past this error.
![Hard Coded Config](https://cloud.githubusercontent.com/assets/1542229/23962657/0b9cd8f8-096c-11e7-9dda-ac69456c7e5e.png)

**Comment by robgaston** [comment]
@jmunowitch since you've got this running on Windows, can you please try to re-craft the code in `settings.py` to generate a path that will work across platforms? 

some things to try:
- try wrapping the path generation code in a call to [`path.abspath`](https://docs.python.org/2/library/os.path.html#os.path.abspath), something like this: `"path": os.path.abspath(os.path.join(ROOT_DIR, 'tileserver', 'cache'))`
- try something like [this](http://stackoverflow.com/questions/11687478/convert-a-filename-to-a-file-url) to generate a file url

Thanks!

**Comment by jmunowitch** [comment]
@robgaston: I ran into this error while debugging for a future workshop. Unfortunately I do not have easy access to a Windows install that is running into this bug.

@mradamcox should have a Windows setup that is running into this bug. Can you see if you can reproduce this bug and assign it to yourself?

**Comment by mradamcox** [comment]
As @jmunowitch mentioned above, hard-coding with the `file:///` url scheme seems to get past this error. I would just recommend that a line like that be added to `settings_local.py` for Windows. I've added it to [the settings_local.py gist](https://gist.github.com/mradamcox/13eb4f5b4455e59340c8cefe48625505) that I currently have linked in the dev documentation. I'm going to consider that good enough for this issue to be closed, but we still have not been able to install mapnik on Windows (separate issue).
