### ISSUE TITLE
Error when deleting tile data

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1818]
The following error occurs when a user attempts to delete a tile: 

`Traceback (most recent call last):
  ...
  File "/Users/cyrus/Documents/projects/GCI/arches_v4/arches/arches/app/views/tile.py", line 83, in delete
    nodegroup = models.NodeGroup.objects.get(pk=tile.nodegroup_id)
UnboundLocalError: local variable 'tile' referenced before assignment`

**Comment by apeters** [comment]
fixed
