### ISSUE TITLE
Rich Text widget (Summernote) allows users to save and execute <script> tags in code view

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1837]
In codeview you can add a script tag and the script will execute.  This is a big no-no.

One potential fix is to not allow users into code view (we did this in v3, although recently @1000camels was having an issue because of this - he wanted to have code view enabled).

Another maybe more difficult option is to scrub the incoming data of script tags.  Maybe this could be done in the widget code?

**Comment by chiatt** [comment]
@apeters I added some listeners in the summernote binding handler that will clean up any script tags after you 1. Type the opening and closing tag and then press any key afterward or 2. Type/paste in opening and closing script tags and press the code button in the editor. I am not proud of the direct JQuery calls, but I'm not sure of a better way to do it within the binding.

**Comment by apeters** [comment]
@chiatt , I'm seeing this issue:
http://recordit.co/xMPSB5e2pw
using the element reference might fix this.  
In any case it does seem like you now can't save a script tag.

**Comment by chiatt** [comment]
@apeters Ok - now you an still run scripts from the browser if you enter a script in the code editor and press the summernote code button. However, the tags will get stripped from the widget's value, so that scripts aren't saved in the tile.

**Comment by apeters** [comment]
that fixed it
