### ISSUE TITLE
Clear geojson input when a user saves a card with a map widget

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1861]
When a user enters GeoJSON in the map widget, the text persists after a user saves the tile.  The GeoJSON input should clear after a user presses the save button

**Comment by chiatt** [comment]
re #1665

**Comment by dwuthrich** [comment]
@chiatt Widget does clear when entering valid geojson.  However, it does not clear when json is invalid, and the widget does not allow you to "scroll up" and view the invalid geojson.  We should allow a user to scroll and view invalid json and to clear an invalid file

**Comment by chiatt** [comment]
@dwuthrich I just merged in a couple of commits. Scrolling is now enabled in the textarea and there is a button in the upper right of the input that will clear the input if it's invalid.

**Comment by dwuthrich** [comment]
meets requirements
