### ISSUE TITLE
Problem installing Mapnik python bindings on Windows

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1865]
We have been working with mapnik 3.0.x. We have found that installing mapnik through node works on windows 10, as well as using one of the binaries that Jeff found. However, no success installing python bindings.

pip install mapnik seems to work, but import mapnik results in this
![Error importing Mapnik](https://cloud.githubusercontent.com/assets/1542229/23965416/21a563a0-0975-11e7-9fb8-c5b5310ba7cd.png)

Mapnik documentation tends to state that 32-bit Python is needed anyway (though I didn't have luck with that either) [here](https://github.com/mapnik/mapnik/issues/3127) and [here](https://gis.stackexchange.com/questions/212151/mapnik-on-64-bit-windows) for example. We know that on 64-bit Windows, 64-bit python must be used in order to make the app run.

#### Acceptance Criteria
- [ ] Serving a raster should work
- [ ] Unit Tests passed
- [ ] Documentation of Installation Steps

#### Definition of Done
import a layer into tileserver

`python manage.py packages -o add_tileserver_layer -m arches/tileserver/hillshade.xml -n hillshade`

and then

`curl -I localhost:8000/tileserver/hillshade/11/324/790.png`

should produce a 200 response.

#### Your Arches Information
* Version used: v4 beta
* Operating System and version (desktop or mobile): Windows 10, 64-bit
* Python 2.7.13 64-bit

#### further
more discussion of this issue can be found here https://github.com/archesproject/arches/issues/1819

**Comment by apeters** [comment]
Haven't we determined that mapnik can't be installed because Arches requires a 64 bit OS (btw, what component in Arches requires this?)

**Comment by mradamcox** [comment]
Not exactly. If Windows 64-bit is used, then 64-bit GDAL is required, and also 64-bit python to work with GDAL. It's a requirement avalanche. In way, this is a non-issue (because I don't see a way past it right now), but I made the ticket as a good-faith effort to retain and summarize #1819.

**Comment by mradamcox** [comment]
In theory (though I haven't tried this) everything could work on a 32-bit installation of Windows.

**Comment by apeters** [comment]
I'm going to close this, because I'm not sure what we can do to fix this.
