### ISSUE TITLE
Readme.md needs to be updated

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1873]
The readme file is out of date and needs to be updated for v4.

**Comment by mradamcox** [comment]
Ok I merged a readme update to master, so check it out. Like I said, all of what is on there is now in the wiki, but I put some "quick install" steps, and then links to all of the relevant project sites.

**Comment by jmunowitch** [comment]
I tested out the instructions.

Changing the directory to myproject is missing. beyond that, everything seems to work pretty well.

**Comment by mradamcox** [comment]
I'd say yes.

**Comment by apeters** [comment]
fixed
