### ISSUE TITLE
Time Filter: "To" Field in the time search does not let you pick a date before "today"

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1878]
### Bug Report

"From" search field in time filter allows user to select a date.  However the "To" field restricts input to future dates, even if the "From" field is several decades in the past.

**Comment by dwuthrich** [comment]
@robgaston Now "To" field allows user to select a time that precedes the user's entry in the "From" field, resulting in an ugly error message.

**Comment by robgaston** [comment]
this is related to #1791 - should now be fixed in the latest in `master`

**Comment by dwuthrich** [comment]
meets requirements
