### ISSUE TITLE
Add default geocoder and basemap for search map

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#1896]
Add variables in settings.py allowing a user to set the default map and geocoder for the search map.

**Comment by chiatt** [comment]
@dwuthrich I've added the following to settings.py:
```
DEFAULT_SEARCH_BASEMAP_NAME = "streets" 
DEFAULT_SEARCH_GEOCODER = "MapzenGeocoder"
```

**Comment by dwuthrich** [comment]
meets requirements
