### ISSUE TITLE
Can't edit a previously saved text in the rich-text editor (summernote)

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1898]
#### Steps to Reproduce (for bugs)

1. Add text to a rich-text input (summernote), pick a card that allows you to save multiple instances (I'm using the HER Monument description field)
2. Save the text
3. Refresh the page and go back to the form
4. Open the previously saved card and try to edit the text
5. Notice how you can't easily edit the text

http://recordit.co/TKolf3RNlh

**Comment by chiatt** [comment]
@apeters  Works as expected. Glad there was an alternative to summernote.
