### ISSUE TITLE
Support for SI units in search buffer

### ISSUE THREAD

**Issue by saberraz** [archesproject/arches#1913]
Currently measurements (e.g. search buffer) are in imperial.

**Comment by apeters** [comment]
this should probably be managed by the Configuration Manager

**Comment by azerbini** [comment]
How about using units by including the Math.js library? I have solved this problem that way on my v.4 (the buffer now supports any given linear unit) and will be putting through a pull request shortly.

**Comment by apeters** [comment]
meets requirements
