### ISSUE TITLE
ubuntu xenial dependencies install script doesn't install java

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1918]
Running the xenial dependencies script works without error. However, after using it, trying to run elasticsearch fails because java isn't installed. I fixed this by running [this line](https://github.com/archesproject/arches/blob/master/arches/install/ubuntu_xenial_setup.sh#L46) manually without the elasticsearch argument at the end (technically I ran `sudo apt-get install openjdk-8-jre-headless` and then entered `y` when prompted).

This fixed the problem. Not sure what `elasticsearch=5.2.1` does at the end of that line, but it seems to break the command. For this ticket, that argument should be removed or modified and tested to make sure java is successfully installed.

**Comment by chiatt** [comment]
@mradamcox I added the java installation back in and removed the command to install elasticsearch using apt-get. The `python manage.py es install` command is now the preferred way to install ES because it also updates the config file for you.

**Comment by mradamcox** [comment]
finally was able to test and all good.
