### ISSUE TITLE
Consider using Appveyor for Windows Build Tests

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#1925]
We are currently using [Travis CI](https://travis-ci.org) to test our builds on Linux.  Travis CI can also used to test Mac Builds. 

We currently are not doing automated Windows unit tests of our commits. [Appveyor](https://www.appveyor.com/) claims to be the Travis CI of Windows.  

Is this something we want to consider implementing to get automated Windows units testing?

**Comment by apeters** [comment]
This could be interesting.

**Comment by jmunowitch** [comment]
Closing this, as it has not been discussed since.

Also, Travis CI now offers Window Builds: https://blog.travis-ci.com/2018-10-11-windows-early-release
