### ISSUE TITLE
Modify v3 SKOS exporter

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#1942]
Modify/create new skos exporter in arches v3 that exports skos that preserves valueids and conceptids from v3 and can be imported by v4.

**Comment by apeters** [comment]
A few things to note here when exporting skos from Arches v3 using the v4 exporter:

 - When importing a v3 skos file to a clean v4 instance the `is related to` relationship type concept is duplicated (the `00000000-0000-0000-0000-000000000007` `is related to` concept comes by default with v4).  

 - The v3 value types `minimum date` and `maximum date` have been transformed to `min_year` and `max_year` respectively.
