### ISSUE TITLE
Save of domain-value and domain-value-list datatypes fail

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1943]
It appears that this is because they are pointing to the Concept datatype python classes, so save fails when trying to index these values as if they were concepts.

We need to add new datatype class(es) for these 2 datatypes and set them up to properly index values (as strings, rather than concept ids).

**Comment by dwuthrich** [comment]
@chiatt Appears that domain, domain lists can now be saved.  However, values don't seem to be indexed, meaning that they don't participate in search

**Comment by chiatt** [comment]
@dwuthrich It seems I was indexing the domain's id rather than its text value.  You should now be able to search against domain values and domain value lists.

**Comment by dwuthrich** [comment]
meets requirements
