### ISSUE TITLE
Document how to support using maps w/o an internet connection

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1957]
Currently, you can use arches w/o an internet connection, but getting your maps to be functional requires some setup.  An admin needs to do the following:
1) remove mapbox sources and layers
2) add your own basemaps (either as tileserver layers in Arches, or otherwise, eg: openmaptiles.org)
3) build (using [Maki](https://github.com/mapbox/maki)) or download sprites (from mapbox, for example), and adjust local django settings (`MAPBOX_SPRITES`) to point to them locally  (local media dir, or other hosted location)
4) build fonts (using [fontnik](https://github.com/mapbox/node-fontnik)) and adjust local django settings (`MAPBOX_GLYPHS`) to point to them locally (local media dir, or other hosted location)

It would be nice if we provided at least better documentation on these issues.  It would also be nice to possibly provide some better tooling/support/UI for these things; some ideas:
- included scripts to build local sprites and fonts
- prebuilt sprites and fonts included w/ the system (would probably need to zip/unzip prebuilt fonts as they are hundreds of files a piece)
- some UI for managing these things?

**Comment by mradamcox** [comment]
This issue was moved to archesproject/arches-docs#12
