### ISSUE TITLE
Map Widget Minor Enhancements

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#1958]
- do not show hover popup when a click feature is selected
- add 'hover' and 'clicked' properties to resource features

**Comment by dwuthrich** [comment]
Also add hover property to search results layer (e.g.: hexes)

**Comment by dwuthrich** [comment]
meets requirements

**Comment by dwuthrich** [comment]
@robgaston I'm closing this issue; will resolve specific styling issues in future tickets
