### ISSUE TITLE
Time wheel counts not in sync with search result counts

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1987]
Notice in the image below, that the time wheel reports **42** hits for the period 0040-0050, but the search results return **247** resources.  

![screen shot 2017-04-19 at 10 29 18 am](https://cloud.githubusercontent.com/assets/823773/25193215/2b1c4386-24eb-11e7-9601-e25b4b13e1f1.png)

**Comment by dwuthrich** [comment]
Still seeing very different counts in the time wheel versus returned records

**Comment by chiatt** [comment]
@dwuthrich The counts should match up now, but you'll need to rebuild in order to see the change.

**Comment by dwuthrich** [comment]
meets requirements
