### ISSUE TITLE
Scrollbars not working with Firefox 52 (Yosemite 10.10.5 and Windows 8.1) RE: #1348

### ISSUE THREAD

**Issue by azerbini** [archesproject/arches#1989]
### Bug Report

Scrollbars on all panes are not working when using Firefox v.52 on Mac Yosemite (10.10.5) and Windows 8.1. See #1348

**Comment by veuncent** [comment]
Same here on Windows 10 desktop

**Comment by jmunowitch** [comment]
This looks solved. There is still some funkiness with some css, but it is not specific to Firefox.

@azerbini @veuncent: If you see any continued Firefox funkiness, please reopen or link to this ticket with a new one.
