### ISSUE TITLE
Propose moving "recent edits" link that sits in the top nav bar over to it’s own dedicated page accessed by the “dashboard” link on the left nav bar. 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1990]
As currently implemented, the recent edits are part of the one of the base templates and because of this all the pages which inherit the base (which is basically all of them, including the RDM) incur the overhead of rendering the template and getting the data to populate the edits table. By moving it to it’s own page we remove all this unnecessary (most of the time) data gathering and rendering, plus we put the “dashboard” link to good use.

**Comment by apeters** [comment]
@dwuthrich what do you think of this?

**Comment by dwuthrich** [comment]
The basic idea is good.  We should reserve "dashboard" for now, and introduce a new link called "recent edits" using the same icon as the current link

**Comment by chiatt** [comment]
Meets requirements
