### ISSUE TITLE
Map Popup: Revert selected instance geometry to unselect when popup is dismissed

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1992]
### Bug Report

A user may click on an instance geometry, thereby setting the map popup to display information about the selected geometry.  This also causes Arches to style the selected geometry based on the styling rules for a "click".

When user dismisses the popup entirely (by clicking the "x" in the upper right corner) the user selected instance geom still maintains its "click" style.  Instead, geometry style should revert to non-click rules.

**Comment by robgaston** [comment]
@dwuthrich I just tested this locally and on http://dev.archesproject.com and it seems to be working fine.  Is it possible that you've modified your styles locally, or there is more to the repro steps here?

**Comment by dwuthrich** [comment]
@robgaston I'm seeing several styling issues when testing with City of Lincoln data.  Are you testing with Lincoln's heritage resource and activities models/data?

**Comment by robgaston** [comment]
@dwuthrich I'm using the default data stored in the arches repo.  Can you please be specific about the issues you are seeing?  Examples are always helpful

**Comment by dwuthrich** [comment]
@robgaston The issues I'm seeing are too intricate to try and describe in a ticket (they occur conditionally depending on styling settings in the Map Manager and may be present when multiple datasets are loaded).  It would probably be easiest to show you via shared screens

**Comment by dwuthrich** [comment]
@robgaston Just tested on dev.archesproject.org and am seeing the problem as described above: after clicking on a geometry in the map (search page) the Map popup appears as expected.  Dismissing the popup does not clear the "clicked" style of the geometry.

**Comment by robgaston** [comment]
@dwuthrich saw what you were talking about here; I just merged a fix into `master` for this

**Comment by dwuthrich** [comment]
meets requirements
