### ISSUE TITLE
Map widget: Raster layers flicker on mouseover & layer opacity change

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1995]
### Bug Report

Moving the cursor with a tileserver overlay causes the overlay to disappear on cursor move:  http://recordit.co/0q0zJeTfwu

**Comment by robgaston** [comment]
I did a little research here - looks like any time we call `map.setStyle` it causes any raster layers to flicker.  We should consider moving away from using `map.setStyle` and instead move back to using API methods to manage layers individually on the map (eg `setFilter`, `setPaintProperty`, `addLayer`, `removeLayer`, etc).  We should be mindful of the performance impact here - in some cases it may be worth enduring the flicker (for instance on adding and removing of layers) if the performance impact of managing layers individually is significant.

**Comment by dwuthrich** [comment]
meets requirements
