### ISSUE TITLE
Information Carrier Upload menu: Save/Cancel buttons do not disappear

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2007]
#### Expected Behavior
After adding a file and type and clicking 'Save', I expected the Cancel/Save buttons to disappear.

#### Current Behavior
The Cancel/Save buttons remain on the page. Clicking it will add an additional row with an empty Type and the same file as the first row.

State after clicking 'Save' the first time:
![upload_1](https://cloud.githubusercontent.com/assets/7893339/25355549/08fd20d6-2905-11e7-9caf-cec87586a318.PNG)

After clicking 'Save the second time:
![upload_2](https://cloud.githubusercontent.com/assets/7893339/25355551/0b478a02-2905-11e7-89cd-2635075399ca.PNG)

After clicking 'Save the fifth time :) :
![upload_3](https://cloud.githubusercontent.com/assets/7893339/25355554/0cd09d3c-2905-11e7-8d66-4a6676e583fe.PNG)

Content of the first and second rows:
![upload_4](https://cloud.githubusercontent.com/assets/7893339/25355556/0e43ca90-2905-11e7-994e-01cae5cd377b.PNG)

#### Steps to Reproduce (for bugs)
1. Go to the Information Carrier Upload menu
2. Select an Information Carrier Format Type
3. Select a file using the  'Add File' button
4. Click 'Save'
5. Now the buttons are still there and clicking 'Save' will create an additional row

#### Your Arches Information

* Version used: master branch, SHA 11d5a4435564c2185f49b6235e8ba9cf302a5fc8 
* Browser Name and version: Chrome Version 57.0.2987.133
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by adamlodge** [comment]
Meet requirement
