### ISSUE TITLE
RDM concepts not sorted correctly

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2018]
### Bug Report
Concepts are sorted incorrectly, both in the RDM and in actual dropdowns. 
Sort order is:  
1
10
11
12
2
3
4

#### Expected Behavior
I expected concepts/dropdowns to be sorted:
1
2
3
4
..
9
10
11
12

#### Your Arches Information

* Version used: master branch, SHA b804b8654d83f177b6a0d51f0eef128aed4da2da 
* Browser Name and version: Chrome Version 58.0.3029.81
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by apeters** [comment]
the temporary workaround for this is to understand that this is an alphanumeric sort:
this would probably work:
01
02
03
04
....

**Comment by jmunowitch** [comment]
**The RDM does not sort the concepts by sort order as described above.**
The actual drop downs DO sort the concepts by sort order as described avove.

**Comment by jmunowitch** [comment]
The RDM sorts the concepts by sort order as described above (In tree mode and concept report).
The actual drop downs DO sort the concepts by sort order as described above.
