### ISSUE TITLE
Select widget does not allow deselect

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2020]
### Bug Report
Select widget does not allow deselect, i.e. remove the selected value and save the field as empty

#### Expected Behavior
I would expect every dropdown menu to have an empty item that the user can select in order to clear the value of that field. 

#### Your Arches Information

* Version used: master branch, SHA c43934f65bd527c0005cd067c44324d5bff28b93 
* Browser Name and version: Chrome Version 58.0.3029.81
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by robgaston** [comment]
@ryan86 the select widget seems to suffer from a similar problem as we'd seen previously w/ the date widget in #1866 

that is, when you clear the widget, the save & cancel buttons persist

can you please take a look at this?
