### ISSUE TITLE
As an RDM user and graph designer I would like to have exported concept schemes, collections, graphs and branches sorted in a reproducible way, in order to make GIT understand what has changed since the last version and thus to organize the development process

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2022]
### User Story
Currently exported json and rdf files (e.g. concept schemes, collections, graphs and branches) are not sorted in a standard way. This leads to GIT picking up changes that are really just nodes that moved to another location in the document.

This requested change can make the development process less cumbersome and error-prone. 

#### Acceptance Criteria
- [ ] json files are exported using a standard sort method
- [ ] rdf files are exported using a standard sort method
- [ ] Unit Tests passed

#### Definition of Done
This can be considered complete when GIT only picks up changes that the user actually made and not the changes caused by a different sorting.

**Comment by mradamcox** [comment]
@veuncent I have been working with reference data import/export a lot in the last couple days, and I would suggest looking at integrating a different output format [here](https://github.com/archesproject/arches/blob/master/arches/app/utils/skos.py#L332) into your workflow. As you can see, it's `pretty-xml` by default, and that format doesn't seem to be sortable at all. If you used `turtle`, I think it would get to closer to what you are looking for (though I don't know if that would parse correctly on upload).

**Comment by apeters** [comment]
this seems pretty low priority, I'm going to close for now
