### ISSUE TITLE
Adv. Search: add the ability to make specific nodes in a graph not searchable (they're searchable by default)

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2026]
Right now the ability to limit searchability is enforced at the **datatype** level.  We'd like to extend this to the node level.

This setting would be managed either in the graph manager, or the card manager (I think the card manager is preferable)

This should be easy to incorporate into Adv. search. but less clear is how (or even if) it could be incorporated into the other built-in search view (temporal, spatial, term, etc..)

**Comment by dwuthrich** [comment]
I don't see anywhere in the UI to access the searchable flag for a node

**Comment by robgaston** [comment]
it's in the graph manager - node form.

the node's datatype must be searchable for the flag to show up.

<img width="1920" alt="screen shot 2017-06-06 at 8 19 54 am" src="https://user-images.githubusercontent.com/1187406/26836987-240ab44e-4a91-11e7-9e32-914aedd767f8.png">

**Comment by dwuthrich** [comment]
meets requirements
