### ISSUE TITLE
Adv. Search: Implement for the "boolean" datatype

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2028]
- Add Elasticsearch DSL generator to datatypes.py (or derivatives)
- Add datatype template (.htm file) for adv. search filter
- Add datatype component (.js file) for adv. search filter
- Update the migrations file to update the record in the `d_data_types` table to set `issearchable` to true

**Comment by adamlodge** [comment]
I set up a test resource model with a simple branch/card that had a checkbox for selecting yes or no as values in the card for the boolean node.  When searching on the node, my only only option seemed to be a dropdown pick list containing true/false as options.  Would be nice to coordinate the data entry card, search widget, and report display to avoid confusion.

**Comment by apeters** [comment]
You should open a different ticket for this 

> Would be nice to coordinate the data entry card, search widget, and report display to avoid confusion.

It sounds like you can search for boolean values, if so I would say that you can close this ticket.

**Comment by adamlodge** [comment]
meets requirement
