### ISSUE TITLE
URLs are not always created the proper Django way (using tags)

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2034]
### Bug Report
Some URLs in Arches templates are not created the proper Django way, that is: using tags `{% url 'url_name' %}`. 

#### Expected Behavior

In order to allow proper routing, e.g. in situations where Arches lives under a subfolder of a webserver, URLs should be generated dynamically by Django.
 
#### Current Behavior
Some URLs are hard-coded, e.g. in templates as `href="/resource"`.

Besides .htm templates, .js files also need to be checked for this. 
URLs in javascript should come from `arches.urls`, which is defined in `javascript.htm`
E.g. `url: "/"` --> `url: arches.urls.root`

#### Your Arches Information

* Version used: master branch, SHA a24c50c590bbcf00ccf357b96d626523de61fc1b

**Comment by apeters** [comment]
fixed
