### ISSUE TITLE
Some .htm templates call http links

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2037]
### Bug Report
On some pages css and/or js files are loaded using http URLs, e.g.: 
`<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/select2/3.5.0/select2-bootstrap.min.css" type="text/css">`
(in arches/app/templates/rmd.htm)

This causes trouble when running Arches under a strict https protocol. Most modern browsers refuse to load any http content when the main site is running under https.

#### Expected Behavior
I would expect front end media to be loaded using `//` instead of `http://` to avoid the described problem. 

#### Current Behavior
Affected files:
`arches/app/templates/rmd.htm`
`tests/fixtures/viewer.html` (less problematic)

#### Your Arches Information

* Version used: master branch, SHA d99722e3b917f3fbbfdcd03d64201d9be97c4a7c 
* Browser Name and version: Chrome Version 58.0.3029.96 (64-bit)

#### Context
I would like to run Arches under strict https in production.

**Comment by veuncent** [comment]
P.s. I will create a pull request for this.

**Comment by chiatt** [comment]
@veuncent I searched for other files that were also using http. I think they are all covered, but let me know if you see any others.
