### ISSUE TITLE
Buffer is not getting recreated when a user reloads a saved search

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2057]
When a user creates a spatial query with a buffer and then reloads the page, the spatial query returns the proper results and the query geometry is rendered in the map, but the buffer geometry is not drawn as well.  

When reloading a search query, the buffer should be added to the map along with the buffered feature.

**Comment by apeters** [comment]
@chiatt what's the status of this?

**Comment by chiatt** [comment]
@apeters I fixed this issue under a different ticket and forgot to move it to QA.  Could you QA it when you get a chance?

**Comment by apeters** [comment]
meets requirements
