### ISSUE TITLE
Geocoding Service: Geocoder no longer provides a candidate list based on user input

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2069]
### Bug Report

Entering a string into the geocoder widget no longer results in a candidate list, even if a real city is entered (e.g.: London).  Candidate list just flickers on for an instant

Suspect that this is caused by new settings graph not passing a valid key to the geocoder.

**Comment by chiatt** [comment]
re #346

**Comment by dwuthrich** [comment]
meets requirements
