### ISSUE TITLE
Move geocoder requests from geocoder.py to geocoder components on the client

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2071]
Currently geocoder requests are proxied through the Geocoder class in utils/geocoders.py.  Managing geocoder requests using knockout components would make writing custom geocoders easier and would resolve SSL issues when making server-side requests. re #2069

**Comment by chiatt** [comment]
@robgaston There are quite a few changes in this pull request: https://github.com/archesproject/arches/commit/da7c5e7ae553af7b1adf85a18daa770dc61336f7
Maybe when you get a chance we can do a short code review and discuss what I did.

**Comment by robgaston** [comment]
@chiatt this mostly looks good - please take a look at the comments that I added to #2195
