### ISSUE TITLE
Earliest time in the time wheel should start at the "12 o'clock" position

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2074]
Earliest time should start at the "12 o'clock" position, with newer time intervals appearing clockwise. Current version of the time wheel shows City of Lincoln dates with the earliest interval starting at about 2 o'clock

see this: http://stackoverflow.com/questions/30627459/how-to-make-d3-sunburst-starting-at-3-oclock

**Comment by chiatt** [comment]
@dwuthrich I saw this problem a couple of weeks ago, but noticed recently that it seems to be positioned properly.

**Comment by dwuthrich** [comment]
meets requirements
