### ISSUE TITLE
Advanced Search does not list all nodes in a model

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2082]
### Bug Report

Using the Disco_data test dataset, Arches advanced search UI fails to list all nodes in a resource model.  For example, the Assets model includes a node (concept data type) that is not present in the list of nodes.

For example search for "Keyword" and notice that nothing is available in the Adv. search window, bu the monuments model has a card named "Keyword"

**Comment by robgaston** [comment]
@dwuthrich the list of "Search Facets" on the right is not a list of nodes, but rather cards in a given Resource Model.  Not sure if that is what you are referring to here.

**Comment by dwuthrich** [comment]
@robgaston Yes, that's what I'm referring to.  Some cards are not being shown

**Comment by dwuthrich** [comment]
@ryan86 concept list data types are not searchable, and therefore do not show up in the advanced search list

**Comment by dwuthrich** [comment]
@ryan86 Pulling and rebuilding seems to have fixed this on my machine.  I'm going to close ticket because it looks like its fixed
