### ISSUE TITLE
Domain data type does not index values into ES

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2083]
### Bug Report

Users can define a list of options used to populate the dropdown widget for the domain data type.  The string values entered by a user are not indexed into Elasticsearch, so that when a user attempts to search on a domain value ES does not return the string as a match in the Search UI's attribute filter.

**Comment by chiatt** [comment]
@dwuthrich I created a resource with domain-value and domain-value-list nodes. Both are indexing for me, and I'm able to get search results using the value strings. Hopefully this bug has already been resolved, but if not, is there an example in the Lincoln data where you see values aren't getting indexed?

**Comment by dwuthrich** [comment]
@chiatt Yes, spatial accuracy (metadata node group) in the DISCO project model.  I'm not getting search to return results that it should

**Comment by chiatt** [comment]
@dwuthrich  I just pushed a fix for this issue. You should now see domain labels in the search terms for those domain values that have been saved to a tile.

**Comment by dwuthrich** [comment]
meets requirements
