### ISSUE TITLE
Search UI: Need an export button

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2085]
### User Story

Arches should allow users to export search results from the Search page.

Export should include 2 formats:

1. csv.  This format will include the nodes defined by the system admin for export

2. Lincoln -- PDF.  This format will include a map (if the search results include geospatial data) and a list of the instances that match the search criteria (e.g.: basically a list of all the search results)

**Comment by azaroth42** [comment]
Much support for this issue in slack on 2019-02-01

**Comment by azaroth42** [comment]
I'd like to add JSON-LD as a supported format - e.g. export the LOD representation of each instance in the result set.

**Comment by dwuthrich** [comment]
There are some things to consider when discussing an export button from the search page:

1. Search can include instances of many models.  And because models generally have quite different "attributes" (e.g.: node groups), it would require some thought for how to export all the search results into a single file, particularly if you want to support .csv

2. Models can be deeply nested, with branches that support higher cardinality.  This means that export results might not be easily represented as flat files (e.g.: .csv).  What is the best way to export sophisticated parent-child relationships in data?

3. Large search result sets will likely require some kind of asynchronous download to support large datasets.

4. Search results can include instances with multiple files (e.g.: images, documents, pdf, etc).  How should an export function treat this?

5. Search results need to respect user permissions, which are defined on a per model basis.  This will have some performance implications.

These are just some of the technical questions that I can think of when we consider allowing an export button on search results.  Some real-world use cases for export would be really helpful!

**Comment by dwuthrich** [comment]
closing, as search export now supported in master and will be released in v5
