### ISSUE TITLE
CLI command setup_db does not (re)index Elasticsearch

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2097]
#### Expected Behavior
I expected the `setup_db` cli command to (re)index Elasticsearch, because otherwise after the database is wiped clean, (non-existing) resources will still show up in Arches search results. 

These are the commands that would make sense to run after/at the end of `setup_db`:
```
python manage.py es delete_indexes
python manage.py es setup_indexes
python manage.py es index_database
```

#### Current Behavior
`setup_db` only drops and recreates the database, but does not touch ES indexes. 

#### Your Arches Information

* Version used: master branch, SHA 80f459c7e2f59b2f25a9461f9c3c6f7723d15425 
* Operating System and version (desktop or mobile): Ubuntu 16.04

#### Context
This is especially important in cases where database installation is automated, such as in Docker containers.

**Comment by apeters** [comment]
fixed in the latest.  indexes are now deleted and recreated.
