### ISSUE TITLE
Documentation: Managing Geospatial Services

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2104]
### User Story

We should have documentation that summarizes the following activities:
1. Basic settings for Arches resources
2. Basic and advanced styling for resources
3. Loading basemaps
4. Loading overlays (note that Arches supports several overlay types.  Maybe this just references the Tilestache website)
5. Summary of how to support "selectable" geometries in overlays
6. Summary of Caching vectors
7. Summary of Clustering vectors

Additional helpful information (perhaps links to relevant articles) might include Mapnik, Tilestache, and general discussions on managing geospatial clustering.

**Comment by mradamcox** [comment]
please see http://arches4.readthedocs.io/en/latest/managing-map-layers/

The content is not all in the order described above (as some of it is more directly tied to the format of the Map Layer Manager interface) but the contents covers all of the items listed in this ticket.

**Comment by dwuthrich** [comment]
@mradamcox meets requirements.  It would be helpful to include a summary of how to include an esri service as a basemap/overlay.  I expect that many users would appreciate an example.

**Comment by mradamcox** [comment]
Yeah, I tried for a while to get a NOAA one working but was unable to do so. I think it was a parameters/projection issue. It would be great to add that to the example repo as well. I was hoping that if anyone at all was able to make an example it would be that much easier to add to example repo.

**Comment by dwuthrich** [comment]
@robgaston  has confirmed that esri tiled services work.  I think he has an example of the proper config file
