### ISSUE TITLE
Allow settings to be defined on a per-project (not per installation) basis

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2106]
### User Story
Currently, the default business data file that holds settings is stored within the virtual environment. This means that if two projects were created from the same arches installation, running setup_db on each one would use the same default settings file. There is no mechanism for creating different files for each project.

#### Suggested Solution
My initial thoughts based on Slack conversation...
1) make a new variable in settings.py something like DEFAULT_JSON_SETTINGS which stores a path
2) make sure this variable exists in the settings.py file in a new project
3) modify setup_db (and any related commands) to find that variable and load business data from the json file it points to.
4) the value for this variable stored in the virtual environment arches settings.py file should point to a default settings .json file (stored in the same place that it currently is stored) in case the project's settings.py variable is commented out.

For discussion: A clone of the default settings .json file could be included in each new project with the DEFAULT_JSON_SETTINGS uncommented and pointing to it. This would immediately override (render useless) the settings .json file that is in the virtual env. Or the DEFAULT_JSON_SETTINGS could be commented out, and the export command
`python manage.py packages -o export_business_data -d ~/Documents/projects/GCI/arches_v4/arches -f json -g ff623370-fa12-11e6-b98b-6c4008b05c4c`
could be added to the settings.py, with instructions for users on how to export their current settings and make them default. Personally I like the latter. Other thoughts welcome...

**Comment by apeters** [comment]
i'm not sure I understand the use case

**Comment by mradamcox** [comment]
Use Case: two Arches projects are created on a server and they use the same pip installed virtual environment. They have different map settings, which get defined through the UI. Then, setup_db is run on one of them, for any number of reasons. There is currently no way to store those default map settings distinctly from the other project.

**Comment by mradamcox** [comment]
This issue is almost taken care of, but the variable that points to the path for the `Arches_System_Settings_Local.json` file is not included in a project's `settings.py` file by default, so a user would have to copy that variable from the `settings.py` file within the virtual environment, and then run `python manage.py packages -o save_system_settings` to create the file. Only after that would settings be fully independent of the virtual environment, which is what is necessary to have different settings on a per project basis.

**Comment by chiatt** [comment]
@mradamcox Your description of the steps needed to persist the system settings for a project is correct. I didn't include the `SYSTEM_SETTINGS_LOCAL_PATH` setting in the project settings.py because it seemed like something that would only be needed in a development environment where rebuilding the database would happen repeatedly. Within a project I imagined that an admin would just configure their system settings once and be done with it. However, I can see that there might be other use cases.

For now I can add the `SYSTEM_SETTINGS_LOCAL_PATH` to the script that generates a project's settings_local.py file. It will be commented out, but uncommenting it there would be much easier than digging into the virtual environment to find the setting.

**Comment by mradamcox** [comment]
That seems reasonable to me. Truth is, for anyone to get to a production environment, it seems that there is a lot of development-type work that has to happen anyway.

**Comment by chiatt** [comment]
The SYSTEM_SETTINGS_LOCAL_PATH setting is now added to a project's settings - uncommented.

**Comment by mradamcox** [comment]
I will close this ticket now, because it is now possible to save system settings on a per project basis, and the path variable mentioned initially (now called SYSTEM_SETTINGS_LOCAL_PATH) is included in project settings.py and uncommented for ease of use. Running ` ... save_system_settings` works as expected. I noticed however that this line https://github.com/archesproject/arches/blob/master/arches/management/commands/packages.py#L611 doesn't reference that new settings location, which means that setup_db will not automatically use the new project settings. A user must further use `python manage.py packages -o import_business_data -s "path/to/project/project/system_settings/System_Settings.json" -ow overwrite`, unless I am missing something.

**Comment by mradamcox** [comment]
Ah, looks like I was missing something: https://github.com/archesproject/arches/blob/master/arches/management/commands/packages.py#L252 In the load_package command this local settings file IS referenced. Sorry for the confusion.
