### ISSUE TITLE
Resource to Resource Relationships: Default behavior of relationship editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2108]
### Bug Report

Issue: Arches defines relationships between resource instances in an unexpected manner.  Follow these steps to re-create the issue:

1. open a resource instance in the resource editor.
2. create a relationship with another resource instance
3. select another resource instance and observe that Arches has already applied the previous relationship values to the instance.

Expected behavior: Users must fill out the resource to resource relationship form.

**Comment by mradamcox** [comment]
I'm trying to make gifs of editing relationship properties, and finding significant issues. First, I can't save the properties (no button appears) but if I delete the relation and then re-add it, all of the previously saved properties are now present. Trying to go in and delete them doesn't entirely work, the dates still remain in the grid layout.

**Comment by dwuthrich** [comment]
meets requirements
