### ISSUE TITLE
Documentation: Setting up Arches for production deployment

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2109]
### User Story

We should identify the key steps in getting Arches ready for production use.  These steps include:

1. Deciding on overall installation approach.  Potential items to address may include:
Unix/Windows OS issues, Application tiers (database/application/ES tiers).  This might just require stating that Arches can be deployed in scalable/fault tolerant ways
2. Setting up a production web server with Arches
3. How to update default landing page images/text
4. User/group management tips (perhaps just a link to Django documentation)
5. Suggested backup strategy (e.g.: database, models/business data, concepts/collections, uploaded files)

For each item, directing users to on-line references for more information would be fine.

**Comment by mradamcox** [comment]
This issue was moved to archesproject/arches-docs#11
