### ISSUE TITLE
Resource-to-Resource Force-Directed Graph: Improve display of nodes/property

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2110]
### Bug Report

When looking at the resource-to-resource instance force directed graph, Arches displays information on nodes and the property joining them when a cursor hovers over a node or edge.  Currently, this information becomes difficult to read when the graph contains many nodes

#### Proposes Behavior
Instead of showing panels that hover near the nodes and edge, we could consider showing the relationship in a dedicated panel (much like the panel used in the map widget).  

When a user hovers over a node, the panel would show a node with a label automatically updated with the node data the user is hovering over.

When a user hovers over an edge, the panel would show two nodes connected by an edge.  Arches would automatically update the labels of each node and the edge based on the edge the user is hovering over

**Comment by apeters** [comment]
related to #1264

**Comment by dwuthrich** [comment]
meets requirements
