### ISSUE TITLE
Permissions Manager: Semantic nodes listed under cards

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2126]
### Bug Report

The permissions manager allows users to view the node group within a card.  This listing includes semantic nodes as well as data type nodes.

The semantic nodes should not be listed (they do not manage business data) and just add a bit of unnecessary confusion to the editor.

**Comment by ryan86** [comment]
Additions to this ticket based on convo with Dennis:
- persist permissions (read,edit,delete) icons to subcards and nodes
- make sure 'clear' button actually clears all selected subcards and nodes

**Comment by apeters** [comment]
'clear' button doesn't appear to clear the nodes entries

**Comment by apeters** [comment]
meets requirements
