### ISSUE TITLE
Document System Settings

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2152]
Need to create basic documentation for all of the system settings that are available through the UI. These should be simple, brief explanations.

**Comment by mradamcox** [comment]
@apeters there are two holes in this documentation that I would like your input on

1.  **Default Data Import/Export User** where in the app is this setting used?
2.  **Time Wheel Config** where can I get an example of this? Would it be feasible to make arches come with a default config?

**Comment by apeters** [comment]
@mradamcox Here's what they are (although I don't believe either is implemented)

1.  **Default Data Import/Export User** : this is essentially the user name to associate with data that is imported into the system
2.  **Time Wheel Config** : this is the bucketing scheme used to render the time wheel.  arches does come with a built-in default config (it's just not visible to the end user). The data is bucketed by Millennium/Century/Decade

**Comment by apeters** [comment]
Need documentation for:
- Default Data Import/Export User
- Properties for Map Zoom
- Search Results Grid
- Number of search hints per dropdown

Remove 
- Time wheel configuration entry

**Comment by apeters** [comment]
meets requirements
