### ISSUE TITLE
Allow export_business_data to omit the default .relations file

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2165]
### User Story
In certain cases, it may be desirable to export business data without the .relations file that usually comes along. This would be most useful when exporting the System Settings business data, but would be helpful on single-resource exports of any kind.

#### Definition of Done
Suggest adding a `-nr/--no-relations` flag (which would be a boolean and require no further argument) to the `export_business_data` command. If the argument is true, the creation of a .relations file would be suppressed.

**Comment by mradamcox** [comment]
As the main rationale mentioned, exporting system settings, has been handled in a case-specific manner, adding the `minor` tag to this. Low priority in my opinion now.

**Comment by apeters** [comment]
I'm going to close this as it does seem very low priority
