### ISSUE TITLE
System Settings Resource Model Card Help titles have full help contents in them

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2167]
Edits need to be made to all of the Cards in the System Settings Resource Model. Card help titles currently look like this:

![image](https://user-images.githubusercontent.com/10427268/27309050-7e1108ae-5517-11e7-914f-7f4860b23f28.png)

**Comment by dwuthrich** [comment]
Steps to reproduce problem:

1. Create Help text for a card in a resource model. Enter the help panel title and help content
2. Save the card edits
3. Export the model
4. Delete the model, then import using the json saved in step 3
5. Create an instance of the model, navigate to the card with your help text, click the help link on the card and note that the help card title is replaced with html derived from the help content

**Comment by mradamcox** [comment]
all good.
