### ISSUE TITLE
Map Manager: Overlays and basemaps no longer display in Manager

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2177]
### Bug Report

Map Manager no longer shows a listing of overlays or basemaps.  This means an admin can no longer administer these objects

**Comment by robgaston** [comment]
@chiiatt looks like the list of map layers was removed from the base view, correct?  Please ensure that all other pages that use the map widget (Card Manager, Report Manager, Resource Editor, Resource Report, Search, others?) don't suffer from the same issue as we saw here.

**Comment by chiatt** [comment]
@robgaston You're right - I think somebody thought is was cruft and removed it from several views. I found the same issue in reports/report manager yesterday. I've been working with search and forms already today and haven't noticed any issue, so I think everything should be covered.

**Comment by robgaston** [comment]
It looks like this is the commit in question: https://github.com/archesproject/arches/commit/4d207bbe01ffcb3f447f48681529f1fd08a2ba9b

Looks like **all** references to map layers were removed - so far as I can tell, there is no good reason for these changes.  I suspect (based on the changes in that commit) that these were removed (incorrectly) in a global find a replace related to removing an unrelated url that happened to also be named `map_layers`.  Will you please review the commit above and make sure that the references to the `map_layers` object on the view contexts are restored? Thanks!

**Comment by chiatt** [comment]
@robgaston Cool - I'll go through it right now. Thanks.

**Comment by chiatt** [comment]
Just combed over the references to `map_layers` in the view contexts and it looks like everything is back in place.

**Comment by dwuthrich** [comment]
meets requirement
