### ISSUE TITLE
Concept Widget: Improve responsiveness of widgets that reference very large collections

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2193]
### Bug Report

Concept widget such as "monument type" (see the "Asset Phases" menu in the Asset resource model in the disco-data test dataset) do not appear to respond to a user because of the latency in getting the collections to display in the dropdown.

One solution might be to implement an AJAX style request so the the widget only requests the first 20 or so members of the collection for display.  Scrolling or typing in the dropdown would then trigger an AJAX request to update the list of collection items shown in the dropdown

**Comment by dwuthrich** [comment]
Arches appears to return both duplicate and other labels in the dropdown.  To re-create: navigate to Assets>Asset Phases and type Beer Garden into the Monument Type widget.  Note 3 returns of Beer Garden under  "Licensed Premises".  However, the RDM only lists a single "Beer House" NOT "Beer Garden" under Lincoln Monument Type > Commercial > Eating and Drinking Establishment > Licensed Premises in the collection associated with this node.

**Comment by robgaston** [comment]
@dwuthrich I've modified the code to only show `prefLabel` values.  This should remove the duplicates, however you will still see some values appear multiple times in the dropdown where they have multiple paths in the hierarchy.

**Comment by dwuthrich** [comment]
meets requirements
