### ISSUE TITLE
Remove any non-functional buttons or UI elements

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2196]
There are various UI elements in the application that are non-functional.

We should remove or hide these elements.

**Comment by dwuthrich** [comment]
@robgaston please review

**Comment by mradamcox** [comment]
https://github.com/archesproject/arches/issues/1264 is relevant to the completion of this ticket.

**Comment by mradamcox** [comment]
also, consider @apeters comment https://github.com/archesproject/arches/issues/2152#issuecomment-313488187 should those non-functional elements be covered in this ticket as well?
