### ISSUE TITLE
RDM: Naming of collections and thesauri

### ISSUE THREAD

**Issue by Philbox** [archesproject/arches#2198]
### Bug Report
Adding thesauri and collections to support resource models

#### Expected Behavior
When adding a collection the name should be the same as the thesaurus which includes the concepts

#### Current Behavior
When adding a collection the name cannot be the same as the thesaurus when first created

#### Steps to Reproduce (for bugs)
1. Create a thesaurus - Thesaurus is created and appears in the menu
2. Add a concept - The concept appears as a child
3. Create a collection with the same name - The collection doesn't appear in the list
4. Create a collection with a modified version of the name - The collection appears in the list
5. Open the collection and change the label to match the thesaurus - The collection and the thesaurus have the same name

#### Your Arches Information
* Version used: 4.0b3
* Browser Name and version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 7 Version 6.1 Desktop
* Link to your Arches Install (optional): http://54.67.27.171/graph/

#### Context
Adds an extra step (ie the renaming of the collection - or thesaurus as the reverse is true)

**Comment by apeters** [comment]
Confirmed this error. Created concept scheme called `ANP Test` and added a child concept.
Tried to create a Collection of the same name (`ANP Test`).  Witnessed the following error.
Error details:
```
IntegrityError at /concepts/
duplicate key value violates unique constraint "concepts_legacyoid_key"
DETAIL:  Key (legacyoid)=(ANP Test) already exists.
```
