### ISSUE TITLE
RDM: Creating a collection from a thesaurus

### ISSUE THREAD

**Issue by Philbox** [archesproject/arches#2200]
It would be useful if once you had created a thesaurus you could copy it wholesale and create it as a collection

#### Current Behavior
At the moment you have to create the thesaurus and then individually add concepts to the dropdown.

The ability to add an entire thesaurus would negate the need to go through multiple steps, repeating work that's already been done.

#### Context
Having to duplicate work is time-consuming. Not all use cases will require this, especially with large scale vocabularies but for small dropdowns it will save a shedload of time.

**Comment by jmunowitch** [comment]
Tested. Works well.
