### ISSUE TITLE
Remove "sub-card" terminology from app

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2225]
This is an unresolved issue stemming from the use of Card Containers and Cards terminology, as opposed to Cards and Sub-Cards.

In the Graph Designer, there is still a switch for turning a card into a sub-card. This would have to be changed to something like "Make parent into Card Container".

I haven't done a thorough search for every occurrence of "sub-card" terminology, but this ticket is to remove it from wherever it can be found.

**Comment by ryan86** [comment]
@dwuthrich Can you offer guidance on what would be the correct terminology here? 

"Place card in card container"?
"Make parent into card container"?
. . .

**Comment by dwuthrich** [comment]
Maybe something like "Place nodes in a separate card"

**Comment by apeters** [comment]
@ryan86 , the images and animated gifs in the graph manager help still reference the old "sub card" terminology
![screen shot 2018-01-03 at 9 40 58 pm](https://user-images.githubusercontent.com/823773/34551455-d0d5bde8-f0ce-11e7-81d6-a1c5901c7a36.png)

**Comment by mradamcox** [comment]
Huh, I was waiting to see this PR get used for this issue https://github.com/archesproject/arches/pull/2674 but looks like the work is done. I'll get on the gif updates ASAP.

**Comment by mradamcox** [comment]
These images/gifs are currently fixed in master, but did not make it into master before it was pushed to pypi (the commits were all in the `docs_in_progress_rtd_build` branch which was not merged until just after the pypi push).

**Comment by apeters** [comment]
@mradamcox can you put this in the QA pipeline and assign it to someone?  Thanks!

**Comment by ryan86** [comment]
meets requirements
