### ISSUE TITLE
Ensure the search buffer in the UI matches the buffer used for the spatial query

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2237]
In some cases search results can fall outside of the search buffer. Both the buffer on the server and the buffer in the UI should be identical so that there is no discrepancy between the search results and the buffer boundary.

**Comment by mradamcox** [comment]
was this not just caused by different coordinate reference systems being used in the client and on the server?

**Comment by chiatt** [comment]
Unfortunately the issue was not the projection but rather that Geos and turf.js use different algorithms.  As @robgaston  mentioned, even if we got them to match it is probably better to return the buffer geometry from the server to avoid disagreement between libraries in future versions.

**Comment by mradamcox** [comment]
Interesting. Yeah, I definitely agree with rob's approach.

**Comment by apeters** [comment]
meets requirements
