### ISSUE TITLE
Synchronize Expression of Boolean Values in card, search, and report

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2246]
Related to: https://github.com/archesproject/arches/issues/2028#issuecomment-315855906

I set up a test resource model with a simple branch/card that had a checkbox for selecting "yes/no" as values in the card for the boolean node. When using search against the node, my only option seemed to be a dropdown pick list containing "true/false" as options. Would be good for the data entry card, search widget, and report display to use what the boolean values as defined in the card for consistency.

**Comment by chiatt** [comment]
Fixed in 6.0
