### ISSUE TITLE
Add note to display name function help about public access to name

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2268]
### User Story
The display name function documentation (in-app and elsewhere) should have a note mentioning that the display name or description will be shown to ALL users, regardless of permissions, unless they don't have permission to see the resource instance at all, of course. Thus, if the display name is made from a sensitive node, it will be publishing sensitive information to people that perhaps shouldn't be allowed to see it.

#### Acceptance Criteria
- [x] add note to docs

**Comment by ryan86** [comment]
meets requirements

see other ticket for migrating documentation over to readthedocs
