### ISSUE TITLE
User with Edit privileges to a resource can't access data entry forms

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2286]
### Bug Report

Steps to reproduce:

1. Add a user account, make the account a member of the crowdsource editor group
2. Select a resource model (such as Assets in the disco_data test dataset) and give the account delete, read, create/update privileges on a card (e.g.; HER Asset Summary)
3. Log out of arches, login in with user account just created
4. Select "Manage Data" from the Arches home page
5. Observe that the user is redirected to the login page

**Comment by apeters** [comment]
related to #1636

**Comment by chiatt** [comment]
meets requirements
