### ISSUE TITLE
Advanced Search: clearing a valid search term raises an error 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2288]
### Bug Report

In the Advanced Search, searching on a concept node type works as expected.  However, clearing a value from the concept widget raises an error.  Steps to reproduce

1. Navigate to search page, press "advanced" tool
2. Select "tags" from the DISCO Project model
3. select the "Byzantine" concept, note that Arches returns 2 results
4. click the "x" icon in the select2  widget to clear the Byzantine concept
5. Note that Arches raises and error and does not clear the search results

**Comment by chiatt** [comment]
Working as expected as of version 6.2.x
