### ISSUE TITLE
Recent Edits table does not update when a resource instance is edited

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2293]
### Bug Report

Recent Edits table lists the 100 most recent imported resource instances.  But it does not update to show edits to a resource instance that has been edited after import

**Comment by apeters** [comment]
@dwuthrich This is probably my mistake.  I took the original page which was called "Recently Added" and just renamed this "Recent Edits" but didn't change the backend code to reflect the name change.

What should it be?  "Recently Added" (a simple name change), or "Recently Edited" (an update to logic and code)

**Comment by dwuthrich** [comment]
@apeters It should be recently edited (e.g.; a way of quickly reviewing and accessing the most recently edited instances, which will require updates to logic)

**Comment by dwuthrich** [comment]
meets requirements
