### ISSUE TITLE
Extend Arches to Support Additional Ontologies

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2306]
The Arches platform provides visual database design tools, allowing users to define the
content and structure of their Arches implementation using graph models. To enhance the
usefulness and interoperability of data managed by the platform, Arches implements the
CIDOC-CRM ontology. This means that database designers can use apply CRM classes to
nodes in their graphs, and describe the relationship between nodes using CRM properties.
Although the CRM is an ISO standard, it does not claim to describe the full suite of
concepts that may be necessary to describe the cultural heritage domain. As part of this
task, Farallon will extend Arches to support non-CRM ontologies.
Deliverables:
- Implement a namespace manager in the Arches Designer
- Support the import non-CRM of ontologies into Arches
- Allow use of rdf:value, rdf:label, dc:description, xsd:integer, xsd:string

Assumptions:
- GRI will provide the information needed to define inheritance rules within non-CRM
ontologies so that Arches can enforce semantic rules in the Resource Designer
during graph design
- GRI will provide the information needed to define inheritance rules to support
multi-ontology models so that Arches can enforce semantic rules in the Resource
Designer during graph design

**Comment by azaroth42** [comment]
Running from master branch, as of 08/10/17 ...

Functionality expected:
 - [X] Use different ontologies for creating classes and properties (e.g. rdf, rdfs)
 - [X] Assign rdfs:Literal as range of property  (e.g. for rdfs:label)
 - [X] Assign properties to classes directly (e.g. E1 as domain)
 - [ ] Assign properties to rdfs:Resource to be used on any class (see 1 below)
 - [X] Assign specific datatypes as range (e.g. xsd:string for rdfs:label)
 - [X] ... without explicitly redefining xsd datatypes, or core rdf/rdfs classes
 - [X] Do something sensible with class labels in the UI (e.g. not show entire URI) 
 - [ ] Do something sensible with relationship labels in the UI (see 2 below)
 - [ ] Works without the full set of CRM ontologies (see 3 below)

Remaining issues:
  1.  Assigning (e.g.) dc:description to rdfs:Resource in the ontology does not result in it being valid for all classes.  Priority: Medium (workaround:  just assign to E1)
  2.  taking the slug after the last `/` in the URI works okay for `rdf-schema#label`, and is a bit of an eyesore for `22-rdf-syntax-ns#value`. It would be nicer if it would use the XMLNS prefix instead (e.g `rdfs:value`).  Where it becomes a bigger problem is for ontologies where the final character of the namespace is a `/`, such as Dublin Core.  Then there's only `description` not `dc:description`... which could become ambiguous.  Priority: Low
  3.  Removing the CRM extensions other than the new `arches_crm_enhancements.xml` results in the graph builder always presenting the red "We're Sorry" box. Adding them back makes it work again. Some assumption being made somewhere? Priority: Medium-High (workaround: ignore all the unused classes, but slows down graph construction)

Validation methodology per item above:
  * Delete /data and restart elasticsearch
  * Edit crm_arches_enhancements.xml
  * packages setup_db && runserver
  * login as admin
  * Create new branch with CRM ontology
  * Set node to E54_Dimension
  * Add a node
  * Unset the property (re #2347)
  * Try to set the class, and then the property

(last couple of tests was by using the ontology reload command, thanks @apeters!)

/cc @workergnome @joshuago78

**Comment by apeters** [comment]
Issue resolution:
1.  Issue 1 can be achieved with the following definitions:
 ```<!-- Allow dc:description on anything, from any ontology -->
<rdf:Property rdf:about="http://purl.org/dc/elements/1.1/description">
	<rdfs:label xml:lang="en">Description</rdfs:label>
	<rdfs:comment xml:lang="en">An account of the resource.</rdfs:comment>
	<rdfs:isDefinedBy rdf:resource="http://purl.org/dc/elements/1.1/"/>
	<rdfs:domain rdf:resource="http://www.w3.org/2000/01/rdf-schema#Resource"/>
	<rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
</rdf:Property>

<rdfs:Class rdf:about="E1_CRM_Entity">
	<rdfs:label xml:lang="en">CRM Entity</rdfs:label>
	<rdfs:label xml:lang="de">CRM Entit&#228;t</rdfs:label>
	<rdfs:label xml:lang="fr">Entit&#233; CRM</rdfs:label>
	<rdfs:comment>This class comprises all things in the universe of discourse of the CIDOC Conceptual Reference Model.</rdfs:comment>
	<!-- this is implicit in RDF, but let's make it explicit -->
	<rdfs:subClassOf rdf:resource="http://www.w3.org/2000/01/rdf-schema#Resource"/>
</rdfs:Class>
```
Keep in mind that Arches requires you to be explicit in your ontology definitions.  Arches has to be told that a E1_Entity is a subclass of Resource.  That knowledge is not built in to Arches.

**Comment by azaroth42** [comment]
Ahh, okay that works :) Issue 3 is the big one ... have you been able to reproduce?

**Comment by apeters** [comment]
@azaroth42 if you feel that the requirements for this ticket have been resolved, then could you please close this ticket?  Thanks!

**Comment by azaroth42** [comment]
Yup, it all looks good! Thanks @apeters!
