### ISSUE TITLE
Migrate vector tile simplification setting to layer settings

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2309]
Should be managed as part of the node configuration via the map layer manager.

**Comment by dwuthrich** [comment]
@robgaston Can't confirm that changing the simplification value in the map manager for a resource model actually changes the way vectors are represented when viewing an overlay.  To recreate: create a complex polygon with many vertices.  Change the vector simplification value in the map manager for the resource model (I used values such as .1 and 150 in my testing), observe that the vector appears to be equally complex regardless of simplification value selected

**Comment by robgaston** [comment]
@dwuthrich you have to save your changes to the map layer for the updated simplification settings to be reflected on the map.  This is because the setting is applied on the server.

**Comment by dwuthrich** [comment]
@robgaston My test workflow: go to the map manager, select model, click "clustering" tab, update vector simplification value, save changes, navigate to search page, refresh, add model overlay, zoom to sample instance with complex geometry, observe that overlay vector does not appear to change based on zoom.

**Comment by robgaston** [comment]
Here's my local demo:
http://recordit.co/LuTQNWBvrE

**Comment by robgaston** [comment]
@dwuthrich here is a demo I ran locally:
http://recordit.co/LuTQNWBvrE

**Comment by dwuthrich** [comment]
meets requirements (after re-booting my machine!)
