### ISSUE TITLE
Develop multiple resource instance widget/datatype

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2314]
create a widget/datatype to represent multiple resource instances
re: #2305 

includes:
- [ ] adding datatype
- [ ] adding widget
- [ ] datatype config form
- [ ] widget config form
- [ ] datatype display value
- [ ] report template

(Search functionality in another ticket: #2315)

**Comment by dwuthrich** [comment]
@robgaston When populating a node-to-resource list widget and saving, everything works as expected.  When then searching on one of the resources defined in the widget, the instance with the node-to-resource list widget is also returned, as expected.  However, searching on the instance itself does not also return the resources defined in the node-to-resource widget. This seems un-expected.

**Comment by robgaston** [comment]
@dwuthrich when you search for resource instances, you are searching for the document associated with a given resource instance.

Arches currently only indexes values to a resource instance document that are a part of that instance.

This is why you can search for an instance on other instances that have been associated to it via the data type, but you cannot resolve to the associated instances when searching for it.

To make search work in this way, we would need to enhance our indexing logic to support this case.  If we want to do this, I think we should open a new ticket for this enhancement.

**Comment by dwuthrich** [comment]
meets requirements
