### ISSUE TITLE
Develop search functionality for single & multiple resource instance datatypes

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2315]
(#2313 & #2314)

this includes (for both datatypes):
- advanced search component
- advanced search backend
- value indexing?
- term indexing?
- other search related functionality?

**Comment by dwuthrich** [comment]
@robgaston search functionality for the widget does not appear to resolve concept labels.  To reproduce: type "extended inhumation" in widget that references disco_data Assets and note that no instances are found despite a resource with id=791be32a-3d6c-45f6-b4ed-e8b5e48a1b38 (Roman burial (BGC) Newport) having a resource type of extended inhumation

**Comment by robgaston** [comment]
@dwuthrich I think your comment should have actually been on #2313 o #2314 - this ticket (#2315) is specifically about integrating these data types into search (specifically, advanced search, i.e. the ability to do an advanced search for resource instances that include/exclude references to another specific resource instance), not the "search functionality of the widget" (i.e. the widget's ability to search for a resource instance to add a reference to).

On the topic that you bring up, though, right now, the widget just does a single term search on the value entered using our default search services.

From the search page, I should be able in the search to type in the string "extended inhumation" and get hits back on that string itself, but right now, I can only get hits using the concept value selected from the term drop down. See here:

![joymhwqjay](https://user-images.githubusercontent.com/1187406/28979629-63b4e910-78ff-11e7-853c-c278a5b69405.gif)

As such, I think that what needs to be addressed here is not to do w/ the Resource Instance datatypes or widgets, but rather with the way we index concept values, specifically, the way that we populate the term index.

@apeters - would you agree w/ this assessment?

**Comment by dwuthrich** [comment]
meets requirements
