### ISSUE TITLE
Documentation: Add dcomentation/examples for loading basemaps/overlays to Arches

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2319]
### User Story

As an Arches admin, I need a reference that summarizes how to load basemaps and overlays.  Examples that demonstrate adding vector, raster, and mapbox services would helpfult

#### Acceptance Criteria
- [ ]
- [ ]
- [ ] Unit Tests passed
- [ ] Documentation

**Comment by mradamcox** [comment]
please see http://arches4.readthedocs.io/en/latest/managing-map-layers/, especially this new section: http://arches4.readthedocs.io/en/latest/managing-map-layers/#adding-new-map-layers and the new repo that is linked therein.

**Comment by dwuthrich** [comment]
meets requirements

**Comment by mradamcox** [comment]
I just got a good example of adding WMS layers working also, so I'll put docs on that up soon too.
