### ISSUE TITLE
Create an Arches Function that can populate a node value based on a user defined setting(s)

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2322]
I can imagine that a user might want to define an string template that this function could use to generate a string and then populate a node with the generated value.

eg: <nodeid of a name node>-HER-<nodeid of a number node> => the_resource_name-HER-3928

There's obviously a lot we COULD do, so we should first start simply.

> Task 3.4: Automated Resource Naming
> Local authorities such as Lincoln and the Greater London HER (GL-HER) have
> implemented naming conventions for their HER records. These conventions typically
> define a unique identifier for a resource record, and are often used as a short-hand
> way of identifying resource types.
> We anticipate that local authorities will wish to implement their naming conventions in
> Arches. This task will implement a custom function that will allow a system
> administrator to define the naming convention for a resource model.

**Comment by chiatt** [comment]
No longer required
