### ISSUE TITLE
Support for Easting/Northing Point Geometry Creation

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2323]
> Task 3.1: Support for Easting/Northing Point Geometry Creation
> Heritage inventory data editors are accustomed to creating a GIS representation of a
> resource by entering an “Easting/Northing” coordinate pair using a specific geospatial
> coordinate system.
> Task 3.1 will enhance Arches’ current geospatial data creation and search tools to
> support this requirement.

**Comment by chiatt** [comment]
The PREFERRED_COORDINATE_SYSTEMS setting in settings.py can be modified to edit the list of projections available the xy input dropdown.

PREFERRED_COORDINATE_SYSTEMS = {
    "4326": {"name": "Geographic", "proj4": "+proj=longlat +datum=WGS84 +no_defs", "default": False},
    "32630": {"name": "UTM 30N", "proj4": "+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs", "default": True},
}

The key for each coordinate system is it's SRID and each coordinate system must have the following properties:

name: The name of the reference system as it will appear in the dropdown.
proj4: The proj4 definition string
default: Indicates which projection will be available by default

**Comment by dwuthrich** [comment]
meets requirements
