### ISSUE TITLE
Create Custom Report Templates for HER Models

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2332]
> Task 3.2: Custom Report Templates for HER Models
> Arches HER will implement approximately 8 resource models, each designed to
> manage a specific portion of the MIDAS Heritage Data Standard. We expect that
> Lincoln and HE will wish to define the report template responsible for defining the
> layout and printing characteristics of each model.

We'll need to get mockups of each of the report templates from @dwuthrich ?

**Comment by robgaston** [comment]
We will need more detail on the following to complete this ticket:
1. the target resource models that we will be building custom reports for
2. the nature of the desired customizations to the report templates

**Comment by apeters** [comment]
We currently have a repo for HER data (https://github.com/archesproject/her-data) and we also have a Lincoln data repo (https://github.com/archesproject/Lincoln_data) which is empty.  

The HER data repo has a total of 9 graphs (4 marked as incomplete).  I'm not sure if those are the graphs that will need custom reports or not.  Only 8 models are mentioned in the ticket.  I'm assuming @dwuthrich knows.

**Comment by dwuthrich** [comment]
@rushfan and we are working on finalizing a branch library that represents the content in MIDAS (Historic England's brilliant document on data themes for representing cultural heritage).  The branches (and the final "Arches HER" models built with them) will allow HERs to deploy Arches and load a default set of models.  

It may be that Lincoln will want to customize our default report templates and present the content on these yet-to-be finalized resource models in a specific format.  Or they may be ok with our default templates.  We'll need to finalize the models and get feedback on the reports from Lincoln before we begin this task

**Comment by dwuthrich** [comment]
Closing issue until we get specific requirements
