### ISSUE TITLE
Linking Arches Resources to External Systems

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2333]
Task 3.3: Linking Arches Resources to External Systems
Historic England maintains a database of the cultural heritage objects in the country
that have formal protection or other “designation” status. Arches HER will need to link
to this database to ensure that the local authority is aware of the designation status of
the object.
This will require that data editors can quickly link their Arches HER data record to the
national designation database. We anticipate that this will require the creation of an
additional data type (like Arches existing geocoding widget) that will allow editors to
query the national designation database and link their local data with the national
record

**Comment by robgaston** [comment]
We will need access to the external system (in this case, "the national designation database") to develop the datatype & widget that will allow for this integration.

**Comment by apeters** [comment]
Actually it's still unclear to me if this needs to be specific to the City of Lincoln's use case or if it can be more generic
> We anticipate that this will require the creation of an
additional data type (like Arches existing geocoding widget) that will allow editors to
query the national designation database and link their local data with the national
record

When it says _allow editors to query the national designation database_ does that mean through Arches, or simply query via another system and copy and past the URL/database link/??? into a potentially new Arches datatype.  More guidance is needed from @dwuthrich and Lincoln

**Comment by dwuthrich** [comment]
This task anticipates the need to enter data from a specific external system.  Our current "external reference" branch may be sufficient to meet City of Lincoln's needs.  Or it may be that a more generic data type is required to properly support this task.  We'll need to hear from Lincoln.

**Comment by dwuthrich** [comment]
Closing; assuming that the External system reference node is sufficient
