### ISSUE TITLE
Load everything to support data collection in Arches from a Git repo/zip file

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2335]
> Task 4: Load an Arches Application
> Our work with Lincoln, HE, and GL-HER will result in an internally consistent and preconfigured
> suite of resource models, data entry cards, report templates, data processing
> functions, Reference data (e.g.: thesauri and collections), and geospatial data presentation
> tools.
> These components will be managed in a Git repository, and define the basis for an “Arches
> HER” application. As part of Task 4, we will develop the necessary code to allow a new
> Arches instance to be configured as the Arches HER application.
> Assumptions:

> - The application load script will check to determine whether the Arches installation
already contains the same resource models (this can happen if a user has
manually imported a version of a model contained in the Arches HER application).
If so, the script will gracefully exit without altering the system to ensure that the
system administrator does not inadvertently overwrite existing models

**Comment by dwuthrich** [comment]
meets requirements
