### ISSUE TITLE
Add the ability to style subsets of map data

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2336]
> Task 2.2: Enhanced Map Representation of Resources
> Arches provides tools for defining how to display resource information on maps. The
> Map Manager tool allows administrators to define the styling, clustering, and caching
> of resources, thereby supporting the efficient display of resources as mapping layers.
> Lincoln and other Arches HER user will wish to extend these capabilities to allow an
> administrator to display subsets of a single resource model. For example: thematically
> display only “archaeological resource areas” from the “Areas” resource model as a
> single overlay; thematically display “conservation areas” from the Areas resource
> model as another overlay.
> This task will implement a robust and flexible methodology to support the ability to
> extract subsets of a resource model and display them as individual overlays that may
> be styled independently and whose geometries may be used as input for other Arches
> resource models.

**Comment by robgaston** [comment]
I'm pretty sure that Arches includes all of the functionality mentioned in this ticket.

I assume then that this ticket is either means to:
1.  document how one can configure a layer such as described, and/or
2. implement some specific set of layers for use in a specific Arches instance.

I think in either event, it would be helpful to have the target graphs for this exercise settled so that we have a concrete example of resource models to build these layers against, and also very specific examples of what layers we are to create.

**Comment by dwuthrich** [comment]
We discussed documenting a standard (and generic) way of supporting this requirement.  Our initial discussions explored the idea of implementing a view of the resource model in PostGIS that would allow both Tileserver and QGIS to access and render subsets of a resource instances as map layers

**Comment by robgaston** [comment]
@dwuthrich That makes sense - the approach you described is what I meant by "Arches includes all of the functionality mentioned in this ticket", so it makes sense that this ticket would really be about documenting that approach using specific examples for Lincoln.

Is there a target resource model we should be using for this ticket?

**Comment by robgaston** [comment]
Here is an example of SQL that (using her-data) filters for just Monument resources of type "Structure" and includes the primary name:
```sql
select row_number() OVER () as gid,
	mv.*,
	nt.tiledata ->> '677f303d-09cc-11e7-9aa6-6c4008b05c4c' as name
	from mv_geojson_geoms mv
	left join tiles t on mv.resourceinstanceid = t.resourceinstanceid
	left join tiles nt on mv.resourceinstanceid = nt.resourceinstanceid
	where (t.tiledata::json ->> '677f2c0f-09cc-11e7-b412-6c4008b05c4c') = '3cf28c22-7271-4bd8-a7da-6e6c45ca4c13'
		and (nt.tiledata::json ->> '677f39a8-09cc-11e7-834a-6c4008b05c4c') = '81dd62d2-6701-4195-b74b-8057456bba4b';
```

This will be useful in creating views that can be queried using QGIS or TileStache

**Comment by dwuthrich** [comment]
meets requirements
