### ISSUE TITLE
Dismiss "Manage..." menu in the Resource Editor after user makes a selection

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2345]
### User Story

As a resource editor, I can press the "Manage..." button to display a menu of options, such as "Copy Resource", "Delete Resource", "Review Edit History", etc.

After making my selection, the menu is not dismissed, requiring me to click again to dismiss the screen.  Instead, the menu should disappear after I make my selection

**Comment by adamlodge** [comment]
meets requirement
