### ISSUE TITLE
Default relationship unintuitively limits class filtering in graph manager

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#2347]
### User Story
As an arches administrator, when I am setting up a branch, it is unintuitive that the default selection of the relationship (L54 in a vanilla installation) limits the selection of the class in the dropdown above it.  When working down the page, I have not yet set the relationship, and would prefer that it does not limit the selection of the class.

#### Acceptance Criteria
- [ ] Unit Tests passed

#### Definition of Done

Two possible solutions have been proposed:

1.  The preferred (by me) solution is to not filter on the default relationship.  This might mean having the default relationship either empty (and thus require it to be set before saving, lest the database get into an invalid state) or some meaningless relationship that can connect any two classes.
2.  Simply flip the order of the relationship and the class selection in the UI, so that the relationship is configured before the class when progressing down the page. 

#### Expected Behavior

Default selections for validity should not limit user selections.

#### Steps to Reproduce (for bugs)
1. Create a new branch
2. Set the top node to be of type E54 Dimension
3. Create a child node, intended to be E60 Number (the value of the dimension)
4. Try to set the class to E60, before changing the relationship away from L54

#### Your Arches Information

* Version used:  4.0.0 (from pypi)
* Browser Name and version:  Chrome
* Operating System and version (desktop or mobile): MacosX

**Comment by azaroth42** [comment]
Triage: This is still valid. Still prefer no default to a limiting default, or at least a more intelligently selected default

**Comment by dwuthrich** [comment]
@apeters This looks good to me.  If @azaroth42 approves we can go ahead and merge into master

**Comment by azaroth42** [comment]
will try and look later today,  otherwise feel free to merge if I dont get to it by CoBSent from my T-Mobile 4G LTE Device
-------- Original message --------From: dwuthrich <notifications@github.com> Date: 4/23/20  09:58  (GMT-08:00) To: archesproject/arches <arches@noreply.github.com> Cc: Rob Sanderson <rsanderson@getty.edu>, Mention <mention@noreply.github.com> Subject: Re: [archesproject/arches] Default relationship unintuitively limits class filtering in graph manager (#2347) 
@apeters This looks good to me.  If @azaroth42 approves we can go ahead and merge into master

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/archesproject/arches/issues/2347#issuecomment-618516811",
"url": "https://github.com/archesproject/arches/issues/2347#issuecomment-618516811",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by azaroth42** [comment]
Agree that this issue is resolved, but ...

... there's still a default class set, which then limits the relationship ... which is, I guess, the inverse problem of this issue.  

![Screen Shot 2020-04-23 at 11 29 47 AM](https://user-images.githubusercontent.com/871868/80135882-c1e5d200-8555-11ea-811d-17aab1cd0347.png)

So I'm okay to close this one but should the class also not be set to a default as well as the relationship?

**Comment by azaroth42** [comment]
Ahh, PICNIC. Well, Problem in browser cache not being up to date. 

:+1: to fixed.
