### ISSUE TITLE
Add --force flag to load_ontology command

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#2351]
### User Story
As an administrator and ontology manager, I want to have a way to not require user keyboard input when reloading ontologies, so that I can script it more easily without expect.

#### Acceptance Criteria
- [ ] Unit Tests passed
- [ ] Documentation

#### Definition of Done
Ontologies can be reloaded without user input.

#### Proposal
Add a `--force` command line argument that, if present and there is only one base ontology, will reload it without further input from the user.  Discussion with @apeters came to this to ensure that the user does really want to do the reload, as it's a destructive operation.

**Comment by mradamcox** [comment]
@azaroth42 Just seeing this now, but I think this syntax should be the same as whatever ends up being implemented for the `delete_resources` command interaction. Right now I have -y/--yes in a PR, but that could be changed as well.

**Comment by azaroth42** [comment]
I'm fine with -y/--yes.  The color of the bikeshed is much less important than the functionality :)

**Comment by azaroth42** [comment]
Was this ever merged?

**Comment by azaroth42** [comment]
Ontology mgmt changed so much this is no longer relevant.
