### ISSUE TITLE
Arches does not properly the help text ("Help Title") associated with a card 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2356]
### Bug Report

Steps to reproduce problem:

1. Create Help text for a card in a resource model.  Enter the help panel title and help content
2. Save the card edits
3. Export the model
4. Delete the model, then import using the json saved in step 3
5. Create an instance of the model, navigate to the card with your help text, click the help link on the card and note that the help card title is replaced with html derived from the help content

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by mradamcox** [comment]
see also #2167

**Comment by dwuthrich** [comment]
closing in favor of #2167
