### ISSUE TITLE
Business Data Groups not exporting to CSV correctly

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#2361]
### Bug Report
When exporting business data with more than two of the same group (three names/name types) to csv the third group of business data was overwriting the second group, the fourth overwriting the third and so on resulting in only two groups of business data being exported to csv (the primary group and the last group that was iterated over).

#### Expected Behavior
All business data groups should be exported to csv

#### Steps to Reproduce (for bugs)
1. Create a resource with more than two groups of the same type (three names/name types)
2. Export that resource to csv
3. Observe only two groups appearing in csv or csv_groups file (depending on if you chose single_file export or not)

**Comment by apeters** [comment]
fixed in the latest
