### ISSUE TITLE
Business Data Export: CSV export incorrectly combining multiple groups of business data

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#2367]
### Bug Report
In certain circumstances csv business data export will combine two business data groups of the same type. 

#### Expected Behavior
Business data export should preserve each group on export.

#### Steps to Reproduce (for bugs)
1. Create a resource with a name and no name type.
2. Add new name group and add only a name type to the new group.
3. Export this data to csv and observe the name and name type from separate groups have been combined into one group.

**Comment by apeters** [comment]
fixed in the latest
