### ISSUE TITLE
Default Resource Count in Time Wheel is Incorrect, propose removing this text

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2372]
When you open the Time Wheel without any search criteria, an incorrect number is shown for the total resources. I'm pretty sure this is just the total number of _dates_ in the database, not individual resources.
![image](https://user-images.githubusercontent.com/10427268/29676354-d8e11e04-88c5-11e7-8200-c0d5a4eacaf4.png)
However, after a segment of the time wheel is chosen, the correct filter is applied and the resource counts are just fine.

Proposing the removal of the this inital Resource count, as it's redundant (the full search results on the left pane already show a full resource count) and at present it's incorrect.

**Comment by mradamcox** [comment]
On further inspection, I figured out this is not simply caused by multiple dates in the same resource. It seems that it was an issue that showed up while using the Lincoln data, but when I made a small test case the count was correct. However, it would be best for the time wheel to function properly regardless of the integrity of the data.

**Comment by dwuthrich** [comment]
Relabel the initial record count with "date values" instead of resources

**Comment by mradamcox** [comment]
assigning to @dwuthrich as he had the final say in deciding how this would be addressed https://github.com/archesproject/arches/issues/2372#issuecomment-352934431

**Comment by dwuthrich** [comment]
meets requirements
