### ISSUE TITLE
Arches 4.0 Apache cannot import settings 

### ISSUE THREAD

**Issue by vpirinski** [archesproject/arches#2375]
On a clean installation of Arches 4.0 and Apache on ubuntu 16.04, apache gives error:

`ImportError: No module named my_project.settings`

The problem is solved by removing "my_project" from the wsgi.py file in app directory.

In other words this line:

`os.environ['DJANGO_SETTINGS_MODULE'] = "my_project.settings"`

Should become:

`os.environ['DJANGO_SETTINGS_MODULE'] = "settings"`

After this everything is working fine.

Best regards,
Venci Pirinski

**Comment by mradamcox** [comment]
Hi Vencislav, for a little more context, could you also post the relevant portion of your apache configuration file?

**Comment by vpirinski** [comment]
This is the file /etc/apache2/sites-enabled/000-default.conf :

```
WSGIDaemonProcess arches python-path=/home/flame/Projects/mc4ch/mc4ch:/home/flame/Projects/ENV/lib/python2.7/site-packages
WSGIScriptAlias / /home/flame/Projects/mc4ch/mc4ch/wsgi.py process-group=arches

<Directory /home/flame/Projects/mc4ch>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

```

Best regards

**Comment by mradamcox** [comment]
I recently encountered this on a different Django project, and came across this answer: https://stackoverflow.com/a/17796481/3873885

Apparently the way to fix it is to append a few paths to sys.path. This worked in my case. If you get a chance, could you try it out? I do not know what is actually wrong with removing `my_project` from the settings reference though...

**Comment by vpirinski** [comment]
With the new version of Arches, there is no problem.

Best regards
