### ISSUE TITLE
Allow additional UI styling of nodes in Graph Manager

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#2379]
### User Story
As an administrator / data modeler, I want to have a way to assign colors to the nodes in the graph manager, in order to have an easy way to see the overall structure of the graph at a glance. The selected node could have a special color, or the line of the circle have an increased width.

#### Definition of Done

If accepted, the administrator could either associate a color with CRM classes and it would apply to all subClasses (until another color was assigned), or as a minimum, assign it in the graph manager interface per node per branch/model from a pick list of colors.  

### Horrible Mockup

![screen shot 2017-08-25 at 5 16 15 pm](https://user-images.githubusercontent.com/871868/29736749-20d95598-89b9-11e7-857e-e131fefa5815.png)

By manually messing around with the DOM, I changed the styles of the SVG circles.

**Comment by adamlodge** [comment]
As a logical extension it would be nice to configure styling of edges based on properies, and/or to config styling of nodes on data type.

**Comment by chiatt** [comment]
re #1264 - @dwuthrich Mentioned that we should use the Appearance tab to define node color

**Comment by azaroth42** [comment]
Triage:  Still valid.
