### ISSUE TITLE
Allow multi-select for resource-instance models

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#2385]
### User Story

As a data model manager, I want to allow my editors to add a resource-instance from a set of models, rather than a single model without finding the right card per model.  For example, a Painting can depict a Person, or a Place or another Object.

Current workaround is to have one branch per model with the same relationship for each (e.g. `depicts` in the above use case) however this means the user has to find the right card -- you can't add a depiction of a Person in the depicts-object card.

**Comment by azaroth42** [comment]
A better example:  An Acquisition can transfer the title of an Object, from either a Person or an Organization, to either a Person or an Organization.

**Comment by dwuthrich** [comment]
meets requirements
