### ISSUE TITLE
Set up External Links for in-Arches documentation to open in new window

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#2388]
### Bug Report

Clicking on the links within the Help for Defining Resource Model settings ([settings-help.html](https://github.com/archesproject/arches/blob/master/arches/app/templates/help/settings-help.htm)) opens in the same browser tab.

#### Expected Behavior

Similar to the link for visiting Arches4.readthedocs.io link, should following this link open its own tab/window?

#### Current Behavior

Currently, following these links overwrites the existing tab.

**Comment by jmunowitch** [comment]
Checked Resource Model Settings help.

All links now open in a new tab

**Comment by jmunowitch** [comment]
Went through the rest of in-app documentation and updated a few more links:
eaeaea95babc5c87fec827c0fb9e6f6bc19e8d13
794da42444e533347d55e537dd64b11cd3904123
83d12962cd41cff69846a6290f3a017781af36da

**Comment by mradamcox** [comment]
Thanks @jmunowitch, much appreciated.
