### ISSUE TITLE
Workflow Documentation: Branch Versioning

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#2409]
If a user would like to create multiple versions of a branch each version must have its own branch ID. If a user creates a branch then exports it as 'verison 1' modifies the branch and exports the second version as 'version 2', on import the second branch imported will overwrite the first because both of those branches will have the same graphid.

To resolve this it should be documented that if a user would like to create multiple versions of a branch, each version should have its own graphid. To accomplish this a user should use the 'Clone' command in the UI before creating 'Version 2' of their branch.

**Comment by mradamcox** [comment]
Just found this ticket and it should be transferred to the arches-docs repo.

**Comment by chiatt** [comment]
Transferred to the arches-docs repo: https://github.com/archesproject/arches-docs/issues/117
