### ISSUE TITLE
Unable to fully utilize CRM Inf Classes

### ISSUE THREAD

**Issue by Philbox** [archesproject/arches#2414]
I've been able to create a branch based on I2 Belief  -J4 that - I4 Proposition Set.

However for the I2 - J5 - I6 branch "Belief holds to be Belief Value" I've had to use E59 Primitive Value instead of I6 as the Graph manager won't allow me to choose I6 Belief Value. (I6 seems to be missing)

Once the Belief branch has been created I have begun to build a branch beginning with an I2 Argumentation.

In this branch it will allow me to select the Belief branch but when I try to add a new child node (in this instance I'd like to add an E39 Actor to carry out the argumentation) it won't let me.

I think the answer lies in the inheritance of properties and classes.

Can we revisit the Inf extension, and the others included, and make sure that all the superclasses/subclasses and superproperties/subproperties applicable across the extension and CRM Core are all in place?

Argumentation is a subclass of E13 Attribute Assignment and as such should inherit all of the properties and subproperties. At the moment it only seems to have the property which is explicitly declared in CRM Inf.
As you can see from the scope note "Only one instance of E39 Actor may carry out an instance of I1 Argumentation, though the E39 Actor may, of course, be an instance of E74 Group." This implies that Argumentation inherits the property P14 as a result of being a grandchild (as it were) of E7 Activity (through its parent E13 Attribute Assignment).

The CRMInf extension will be needed for modelling evidence in the UK HER implementations

**Comment by Philbox** [comment]
Thanks Alexei, I think that would be very helpful. It makes it easier for bears of very little brain, like myself, to get their heads around things. Can we also solve the issue of property inheritance for the other Inf classes?

**Comment by apeters** [comment]
Can you explain what you mean by: 
 
"**Can we also solve the issue of property inheritance for the other Inf classes?**"

**Comment by chiatt** [comment]
Because the CRM is no longer in core arches, I'm going to move this ticket to the CRM repo: https://github.com/archesproject/cidoc-crm-ontology.

**Comment by chiatt** [comment]
Issue moved to [archesproject/cidoc-crm-ontology #2](https://github.com/archesproject/cidoc-crm-ontology/issues/2) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chiatt** [comment]
Issue moved to [archesproject/cidoc-crm-ontology #3](https://github.com/archesproject/cidoc-crm-ontology/issues/3) via [**ZenHub**](https://www.zenhub.com/)
