### ISSUE TITLE
Move commands unrelated to package management out of packages.py

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2428]
packages.py contains operations not relevant to package management.  These commands should be moved into their own respective files to improve organization of management commands.

Be aware that many operations in packages.py share methods, so moving code out of package.py should be done carefully.

Changes should also be documented here:  https://github.com/archesproject/arches/wiki/Command-Line-Reference

**Comment by jmunowitch** [comment]
Related to #3603
