### ISSUE TITLE
Map Widget: show geometry(s) of an instance when user clicks on search marker

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2439]
### User Story

As a user exploring search results, I would like to see the actual geometry of a model instance when I click on the search marker that represents the location of its centroid.  This is an enhancement of Arches current ability to show and persist an information panel with instance-level data when I click on a search marker

#### Acceptance Criteria
- [ ]
- [ ]
- [ ] Unit Tests passed
- [ ] Documentation

**Comment by chiatt** [comment]
Duplicate of #3239. Deleting the earlier ticket because the later ticket has more detail.
