### ISSUE TITLE
Report Manager: Map widget shows "Edit Mode" alert even though map is not editable

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2440]
### Bug Report

The Map template in the Report Manager inappropriately shows an alert box with an "Edit Mode" notification, despite the fact that map widget does not allow users to edit data in the report.

**Comment by jmunowitch** [comment]
Related to: https://github.com/archesproject/arches/issues/2540

**Comment by dwuthrich** [comment]
meets requirements
