### ISSUE TITLE
allow admin to specify password requirements

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2454]
the admin should be able to specify the requirements for password complexity:

- password min and max length
- if numbers are required 
- if caps are required
- if symbols are allowed/required?

we should strive to emulate what is common practice

http://archesproject.github.io/mockups/arches_profile_manager

**Comment by chiatt** [comment]
@jmunowitch I fixed the django link in the password validation docs, so this ticket is ready for you to QA.
