### ISSUE TITLE
Add db schema to support mobile project management

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2457]
We need to be able to store all the metadata that defines a mobile project:
- Project name
- status (active/inactive)
- Spatial extent
- Begin and end dates (when to allow data to be collected, when to allow users to upload data)
- Models involved
- Specific cards in each model
- Users
- Resources to include (saved search?)

there are more things I'm sure

**Comment by robgaston** [comment]
broken out into smaller tickets

**Comment by apeters** [comment]
meets requrements
