### ISSUE TITLE
Create project summary section in the profile manager page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2458]
The project summary section would be used in the profile management page.
It simply lists the projects the user is associated with and the details of the project itself.

![screen shot 2017-09-27 at 12 56 47 pm](https://user-images.githubusercontent.com/823773/30934783-7b35805a-a383-11e7-9ca2-40a00c6d0adc.png)

**Comment by apeters** [comment]
@chiatt, I think this ticket has been superseded by #2582

**Comment by dwuthrich** [comment]
meets requirements
