### ISSUE TITLE
No Access Permissions do not Properly Hide Resources from Search

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2465]
### User Story
Basic example. I'm using specific terms, but the generic nature of the issue should be clear.

As a user/database designer I need to be able to hide a certain resource model from anonymous users. In this case, it's Archaeological Sites. The sites should not show up in the map, in the search suggestion dropdown, nor in search results. In other words, Archaeological Sites should not be visible in any way to non-authenticated users.

#### Current Behavior
To handle this, I go to the Archaeological Site resource model, and edit its permissions. I select the Guest group, and I select all nodes in the Resource Model, set the desired change to No Access, and apply the permissions. Result shown below.

![image](https://user-images.githubusercontent.com/10427268/30979219-a6cf4c36-a442-11e7-829e-436b0c82b0d2.png)

Now I make a new resource called "test archaeological site", log out, and navigate to the map view as a non-authenticated user.

Existing Desirable Behavior:

- [x] When trying to add a resource overlay, the Archaeological Site geospatial location node layer is not available.
- [x] If I search for the name of the site and select it from the search suggestion dropdown (see below), no results are returned.

Existing Undesirable Behavior:

- [ ] Upon loading the search page the number of results includes the Archaeological Site resource(s)
- [ ] Similarly, upon loading the page the "Search Results" overlay (the hex bins) includes the location of Archaeological Sites
- [ ] When I begin to type the name "test archaeological site" into the search bar, I am prompted with that string as a search option (selecting this term yields no results which is good). This name should not be visible to a non-authenticated user.
- [ ] Archaeological Site is visible to me in the "Select" dropdown as shown below
![image](https://user-images.githubusercontent.com/10427268/30979936-d9235630-a444-11e7-9a6c-320b8b78a983.png)
- [ ] If I click on Archaeological Site in that dropdown, I am given a list of all Archaeological Sites like this, and the map zooms to the location of these results (though the geospatial locations are not shown). 
![image](https://user-images.githubusercontent.com/10427268/30980004-1cd03e0c-a445-11e7-99a0-8daf3cfe7a64.png)

#### Thoughts
None of the description above indicates that node-level permissions are not working correctly. However, there is no flag to make an entire resource model off-limits to a user, and this inadvertently allows the user to learn way too much about the protected resource (name, location, number of resources). In lieu of a "protected" flag on a per-resource model basis, it could reasonably be expected that giving a user No Access to all of the resource's nodes would accomplish the same thing, but this is not the case.

#### Version Info
Arches 4.0.0

**Comment by apeters** [comment]
I think we'll have to have @dwuthrich weigh in on this, but to respond to a few points, but I think we determined that we were ok with:

1. Showing the count of results that included resources that were "hidden"
2. Showing the hex bins of search results as that obfuscates location 
3. Showing the name of restricted resources in the dropdown as that doesn't reveal anything about the resource itself.  Also notice that if a user were to select that item, it would not return any results.

I think what this does point out is that when a user lands on the search page the page presents everything in the system.  It's not really a search in that sense, but I agree with your last 2 points.  I would think that we should fix that.

**Comment by dwuthrich** [comment]
@mradamcox @apeters Adam's point about the model not appearing as a selection in the dropdown (as shown in the second image) seems reasonable.  I also agree that "no access" on the nodes used to define the content of the search results template should preclude showing instance names and listing them in the search results panel (as shown in the last image).

**Comment by mradamcox** [comment]
Regarding the items that @alexei enumerated, I personally am not satisfied with that behavior so I can put that into a separate ticket if @dwuthrich agrees that that behavior is acceptable. My reasoning is simply that if I want to hide a category of resources from a certain type of user then I expect that no trace of those resources will be discoverable by that user.

Of course, I have my own current example, but if you think of broader applications, it seems like the ability to completely hide a category of resources from an anonymous user would be a given.

Sounds good on the last two points. It's really more than just removing the item from the dropdown list, that url must be protected too of course.

I made a single ticket because I assumed all of these issues would be fixed in a single effort. If that is not the case because there isn't consensus on what is acceptable, I can rework this ticket and make others if necessary.

**Comment by dwuthrich** [comment]
@mradamcox I know its a pain, but having individual tickets would probably speed up the resolution of these issues.  For example, we seem to have agreement on some issues (e.g.: listing instances in the search results panel should be possible), whereas other issues (e.g.: count of resources) are less clear and will probably generate some discussion.

**Comment by mradamcox** [comment]
Could you clarify what you mean by "listing instances in the search results panel should be possible"?

**Comment by dwuthrich** [comment]
@mradamcox Sorry, the "should" was a typo.  What I mean is that Arches should not list instances in the search results panel if the nodes used to populate the content of search result template are set to "no access" for the user.

**Comment by mradamcox** [comment]
@dwuthrich aren't the search result templates populated by whatever is defined in the resource descriptors function?

**Comment by dwuthrich** [comment]
@mradamcox Yes.  And if the user's permissions for nodes defined in the resource descriptor's function is "no access" then Arches should not display the search result

**Comment by mradamcox** [comment]
Ok, then we also don't agree on that, and that is not the result I was getting at. Currently, as we have noted in the documentation, the display name and display description are calculated from nodes regardless of what permissions have been set on those nodes. Thus, as we warn people, don't create a display name or description from a node that you are hoping to restrict from somebody.

I think that it's fine to list results if a user doesn't have access to one or more of the nodes, even if those restricted nodes are being used in the resource descriptors. Because I feel 1) it's fair to have that limitation on what people will use for resource descriptors and 2) the method you have described creates a way to _inadvertently_ modify permissions: changing the resource descriptor function could alter someone's ability to view a resource, even if the actual permissions haven't been changed.

The other point I was trying to make is that the very act of displaying those results automatically zooms the map to the location of those results, regardless of whether the user has access to the spatial location of those resources or not. This should not happen (though I do understand that it would be a complicated thing to change).

**Comment by dwuthrich** [comment]
@mradamcox My point is that setting permissions on a node should be respected across the app, even in functions/templates.  FYI, this approach would NOT inadvertently modify permissions (that has to be done in the permissions manager), but it definitely could change who could view data used in a function like the one used for display search results.  Overall, if you're ok with listing instance results even if a user doesn't have permission to read the values of nodes, then that's less restrictive than my view.

**Comment by mradamcox** [comment]
@dwuthrich, this discussion is getting a little muddy, so I will just be clear about what I'm trying to say with this ticket. This is informed by whatever number of clients I have spoken with who ask nervously about archaeological data, as well as my own ideas of what would make a streamlined and intuitive workflow.

-- Resource Models can be completely hidden from a certain user group. 

This is why I started this ticket: I thought I would be able to achieve this by restricting access to all of the nodes within a Resource Model, but it turns out that does not do the trick. I listed above all of the characteristics of what such an enforcement would look like in my opinion. (I did not look at the time wheel, but I do know that the Advanced Search tool worked as desired.)

-- Portions (nodes) of Resource Models can be hidden from certain user groups.

This is supported, as I pointed out above, but for a few details mostly having to do with geospatial coordinates. I think that if a user is restricted from seeing a geospatial coordinate node it should not be represented in the hex bins, and it should not be considered by the "zoom to" function that happens automatically when new search results are produced. (I think these two things would have the same fix.)

To be clear: I am not at all concerned with what nodes are used in the resource descriptors function. I think that that function should not have anything to do with restricting access to resources, in this case determining what shows up in the search results, because I find that to be unintuitive. Technically it may be less restrictive, but to me that doesn't matter if the other bases are actually covered.

**Comment by mradamcox** [comment]
@dwuthrich, based on this discussion, could you please let me know which of the "undesirable behaviors" I have listed above that you agree should be fixed? I'd like to reconfigure this ticket and be a little more specific.

**Comment by dwuthrich** [comment]
@mradamcox To be clear, you're welcome to add tickets for each of the undesirable behaviors that you've noted.  For me, the second and the last two issues seem the most pressing to resolve.

**Comment by mradamcox** [comment]
Ok. It just became clear through this discussion that your interpretation of the last item was not what I intended. I will open more specific tickets to cover what I consider to be appropriate behavior for restricted resources. If you want to open one to address your interpretation of the last issue (which was that if restricted nodes are used in resource descriptors those resources should not show up in search results) you'll have to do it separately.

**Comment by mradamcox** [comment]
Closing in favor of #2491 and #2492
