### ISSUE TITLE
Set up automated tests in Docker Cloud

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2489]
Once PR #1650 is pulled, we can set up automated tests in Docker Cloud.

Currently there is already an automated build set up that is triggered by pushes to the Arches GIT repo. 
This can be leveraged to easily set up automated tests for each of those pushes. 

This can be done by adding a `docker-compose-test.yml` file to the root of the repository. 
This file needs to have a service called `sut` which will be the Arches service that runs the tests.
Additionally, it requires a Postgres and Elasticsearch service for the tests to run. 

#### Acceptance Criteria
- [x] A `docker-compose-test.yml` file is created under root with the above services specified
- [x] Unit tests are run automatically when automated builds are done
- [x] Unit Tests passed in Docker Cloud

**Comment by jmunowitch** [comment]
This looks complete to me, and has been happening for a while.
