### ISSUE TITLE
Restricting All Nodes On A Resource Model Does Not Fully Restrict Access To It

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2491]
### User Story
Currently Arches provides the ability to implement permissions on a node-by-node basis, but there is no ability to fully restrict a given resource model. This should happen if No Access has been defined on every node in the Resource Model, triggering a "completely restricted" state.

#### Expected Behavior
If a resource model is fully restricted from a user/user group, said user/user group should see no trace of any resources  
1. that resource model would not show up in the filter dropdown in the Search Page (Archaeological Site, in the example below).
![image](https://user-images.githubusercontent.com/10427268/30979936-d9235630-a444-11e7-9a6c-320b8b78a983.png)
2. the url that would result from clicking Archaeological Site in the dropdown shown above must be protected, or return no results (right now it does in fact return all archaeological sites, though as the nodes themselves are restricted, no information shows up in the resource report besides the display name)
3. typing the name of a fully restricted resource into the search bar should not generate suggestions that include that name
4. the initial number of search results should not include these restricted resources. Admittedly, no really sensitive information would be revealed, but I can't actually see any good, universal, argument for why the search results should include a count of restricted resources.

#### Steps to Reproduce (for bugs)
Create a new resource model, with at least one or two nodes, set permissions to No Access for the Guest user group, create one resource with this resource model, log out, go to search, note all the behaviors described above.

#### Your Arches Information
* Version used: 4.0.0

#### Context
This level of restriction is necessary for many organizations whose database will include sensitive records, such as archaeological data.

**Comment by mradamcox** [comment]
I have accomplished some of these tasks for my current project with this commit: https://github.com/legiongis/arches/commit/df0d7723cdc21c928b6ad3d3e79cf92f1b9ac9cb. The `get_doc_type` function is altered to check the user's group assignments against a new setting in settings.py. This is not a 100% comprehensive fix for all the issues above, as described below:

1. (not solved) the resource type still shows up in the dropdown (though that should be real easy to fix with this new settings variable).
2. (solved) though not exactly as described: the url is still available to the user, but 0 results will be returned if they are trying to get a resource type to which they don't have access.
3. (not solved) no effort is made to cull dropdown suggestions
4. (solved) the search results number correctly reflects the accessible resources

see also #2492

**Comment by bferguso** [comment]
We have a similar requirement for our business area as we would like to use the system for both sensitive archeological information as well as public heritage data.

**Comment by chiatt** [comment]
Hey @njkim - I think this is resolved in the latest. Can you check when you have a chance?

**Comment by chiatt** [comment]
The only outstanding issue now is #3 which is now covered by #7316.
