### ISSUE TITLE
Restricting Access To A Geospatial Node Still Allows General Access To Coordinates

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2492]
### Bug Report - from @mradamcox 
Currently, a user/user group can be restricted from seeing a Geospatial node, just as any other node may be restricted. Doing so successfully hides that node's geospatial overlay layer in the search view from the user.

However, these nodes are still used in the creation of the "search results overlay" hex bins. This means that in some situations archaeological site locations could be very much exposed (e.g. a small project area with small hex bins).

Further, if these Archaeological Sites show up in search results, which is a legitimate possibility if guests are allowed Read access to non-spatial attributes, the map will still automatically zoom to the coordinates. In a database with only a few archaeological sites, or a number of sites that are in a very tight cluster, the location of these sites would be pretty clearly revealed.

#### Definition of Done
If a geospatial coordinate node is restricted for a user/user group, that node should actually be hidden from that user/user group. This must include (though may not be limited to)

- [ ] the creation of the search results overlay
- [ ] the automatic search results zoom function

#### system info
Arches 4.0.0

#### Expected Behavior
When a user or group is put on no access to a Resource Model's location card, using that model's search filter should not cause the data to affect the map or its orientation.

#### Current Behavior
When a user or group is denied access to a Resource Model's location card, the map still reacts to a user search like they have access to the data. The only difference is that the location information does not show up on the map. 

For example, if the administrator was to put the location card of HER Find Models on 'No Access' for a specific user or group, the group would not be able to view the data points on the Map Search. However, if the filter is activated, the map search still zooms in automatically to show the user where the Find Model locations are.

#### Steps to Reproduce (for bugs)
1. Open Arches 4.1.1 in browser
2. Disable 'read' permissions on a Resource Model's location card
3. Navigate to Map search and apply that model's search filter
4. Observe error listed above

http://recordit.co/8PL9Ig1aRd
http://recordit.co/inQWMRyBdv

#### Your Arches Information
* Version used: 4.1.1
* Browser Name and version: Chrome, Safari, Firefox, IE11
* Operating System and version (desktop or mobile): Mac OS, Windows 10

**Comment by adamlodge** [comment]
Works in 4.1.1. Reassigning to Cyrus so he can migrate to master.

**Comment by adamlodge** [comment]
@chiatt Works properly in simple cases where, for example, I disable access to the card container node that includes the geometry and all of geometry's siblings, but if I disable geometry (and not it's siblings) the privilege seems to still be applied at the container level and siblings that I want to expose are not exposed. Probably worth a chat.

Example of issue permissions config below:

![Screen Shot 2018-05-23 at 7.35.37 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/1552dfeb-443c-4791-9210-5d7fd40484a3)

**Comment by adamlodge** [comment]
The behavior I saw in the comment above was a result of the HER Place node being set to "no access".  That (lack of) privilege flows downstream to the child nodes within the card container regardless of what privs are assigned to the child nodes.

Meets requirements as it relates to original intent of the ticket regarding access to spatial information.  Closing ticket.
