### ISSUE TITLE
Changing datatype in node form does not trigger dirty state

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2525]
Once a graph is saved in the designer, if a user then tries to switch the datatype of a node in the node form, the dirty state of the form is not triggered. This makes it impossible to change the datatype of a node regardless of whether the resource model has instances saved or not.

Users should be able to change the node datatype if there are no instances saved against the node's resource model.

**Comment by ryan86** [comment]
This bug was noticed when changing the datatype from concept to boolean datatype.

**Comment by apeters** [comment]
I just noticed this bug too and at first it seemed only to happen when changing from a concept node, but now I've noticed it when changing from geojson, and domains and others.  There is just a big lack of proper triggering of the dirty state.  It looks like something to do with code that @robgaston wrote (changeset 7641e0e - handling for legacy nodes re: #2309)

**Comment by chiatt** [comment]
Works as expected
