### ISSUE TITLE
Boolean datatype displays "true" or "false" instead of label values in reports

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2532]
**In the form it displays like this:** 
<img width="308" alt="screen shot 2017-10-10 at 11 24 25 am" src="https://user-images.githubusercontent.com/823773/31403333-ac4b5316-adad-11e7-96c0-640788467c0b.png">

**But in the report it displays like this:**
<img width="398" alt="screen shot 2017-10-10 at 11 24 45 am" src="https://user-images.githubusercontent.com/823773/31403334-ac6971d4-adad-11e7-8ab4-04058d31232a.png">

**Comment by ryan86** [comment]
@apeters do we also want to use the true and false labels in advanced search or should those stay values stay 'True' and 'False'?

**Comment by apeters** [comment]
@ryan86 I think we should use the labels, 
as a user I could set up the labels to be "Black/White", or "Strong/Weak", so I would expect those to show up in adv. search.
