### ISSUE TITLE
Related Concepts get duplicated during import of skos file

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2533]
Link to file that demonstrates this problem: [seneschal_eh_tbm_20130717.txt](https://github.com/archesproject/arches/files/1373198/seneschal_eh_tbm_20130717.txt)

Screenshot:
<img width="393" alt="screen shot 2017-10-10 at 12 28 39 pm" src="https://user-images.githubusercontent.com/823773/31406538-9ab29250-adb6-11e7-837d-b76382c616ca.png">

**Comment by adamlodge** [comment]
@ryan86 db code to do the psuedo-unique validation on relations is attached. Happy to walk you through it at your convenience.
[Check_Relations.sql.zip](https://github.com/archesproject/arches/files/1617330/Check_Relations.sql.zip)

**Comment by apeters** [comment]
@ryan86 were you able to notice/test any difference in loading time based on the update?

**Comment by apeters** [comment]
meets requirements

**Comment by Philbox** [comment]
@apeters I've just imported a SKOS file and this is still happening. Has it been rectified in only certain versions? I was using Lincoln's instance which is 4.0.2b0
