### ISSUE TITLE
Docker: run arbitrary cli commands within an activated virtual env

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2546]
### Bug Report
Currently any arbitrary cli command (i.e. anything outside the commands set in `entrypoint.sh`) is run in a new process using the `exec` command.

This means the virtual environment is no longer active and needs to be explicitly set in the arbitrary command, e.g.
`docker run arches source ../ENV/bin/activate && python manage.py makemigrations`

By removing the `exec` part of `exec "$@"`, the command is run in the parent process instead, meaning the virtual env is already active. Thus the user can run the command like this:
`docker run arches python manage.py makemigrations`

In addition, any environment variables set in `docker-compose.yml` or in a `docker run` command are also available in the active shell. 

#### Context

`exec` starts a new process, which is isolated from its parent process.

**Comment by jmunowitch** [comment]
I am unable to reproduce this with the tip of master (https://github.com/archesproject/arches/commit/182c485fe1548feccf8dfcb740026cb197cc964c). Perhaps this was fixed and never closed. 

If you are still having this issue, reopen this ticket and we can re-evaluate.
