### ISSUE TITLE
Enable hover popup for any features on map

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2549]
Should be driven by a property attached to vector features that could contain the popup content used to render it on the client.  We should show the content in the same popup we are currently using on the map.

**Comment by chiatt** [comment]
To QA this ticket you can load the example package which includes a postgis vector layer called `example_layer`.

```python manage.py packages -o load_package -s https://github.com/archesproject/arches4-example-pkg/archive/master.zip -db true -y```

2. Navigate to search and add the `example_layer` overlay. Once added, you should see see some features located near South Carlton northeast of Lincoln.  All of them have html in their `arches_description` property, and this should appear in the markup. 

3. Add this to your project's settings: `ALLOWED_POPUP_HOSTS = ['localhost']`

4. Add a `snippet.htm` file to a local directory and add some html that you would like to see in a popup. Then cd to that directory and serve up the contents like so:
python -m SimpleHTTPServer 8081

You should now see in site three's pop-up the contents of your .htm file. Sites 1,2 and 4 should still show text.

**Comment by chiatt** [comment]
@robgaston I was hoping you could review the technical implementation before having Dennis QA the UI.

**Comment by chiatt** [comment]
@robgaston I went ahead and changed the variable name from `arches_description` to `feature_info_content`

I realized after our discussion that I actually had designed the feature_info_content property to be either an html string or a url; it just wasn't very clear in the code. The `feature_info_content` defaults to an html string, but if it passes the url regex, a request is made for the markup. There's a layer in the example package that demonstrates both:

https://github.com/archesproject/arches4-example-pkg/blob/master/preliminary_sql/tileserver_example.sql

https://github.com/archesproject/arches4-example-pkg/blob/master/map_layers/tile_server/overlays/vector_example/vector_example.json

Also, I added some docs here: 
http://arches4.readthedocs.io/en/latest/creating-new-map-layers/#customizing-map-popup-content
