### ISSUE TITLE
RDM: Collections do not export with sort order

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#2554]
Unable to export collection using the 'Export all collections' command if the collections contain sort order. See uploaded screen shot.

![screen shot 2017-10-11 at 7 17 23 pm](https://user-images.githubusercontent.com/3038476/31513018-c397e526-af41-11e7-899d-e64dbb9f51b6.png)

**Comment by jmunowitch** [comment]
@ryan86 claims this fixed the issue.
