### ISSUE TITLE
Add a "file" data type

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2563]
Currently Arches has a file-list data type, but no datatype that restricts to just one file.  This is important for cases like images where a single-card branch is created that associates (what should be) one image with one caption and one copyright.  As it currently stands a user might add multiple images through the file-list data type and then it becomes unclear which file the caption and right relates to.

**Comment by chiatt** [comment]
This might also be solved with a different widget that allows for only one file. It might be possible just to modify the existing widget to limit the number of files. In either case the file-list datatype would still work.

**Comment by chiatt** [comment]
The filelist datatype can currently be configured to limit upload to one file and the file viewer restricts a tile to one file in the UI.
