### ISSUE TITLE
Docker: Minor bugfixes and Readme updates

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2565]
#### Minor bugfixes
- [ ] On container startup using `docker-compose.yml`, the `collectstatic` command outputs errors because of duplicate static files 
- [ ] Wrong project path in entrypoint echo
- [ ] Wrong project path in Readme
- [ ] Readme instructs user to copy root folder to Docker image, should be only project folder

**Comment by jmunowitch** [comment]
@veuncent: is this complete?

**Comment by veuncent** [comment]
@jmunowitch Yes, I'm closing this
