### ISSUE TITLE
Docker: Add Gunicorn for production-ready containers

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2569]
### User Story
In order to run Django applications securely in production, we need Gunicorn as a 'middle-app' between Nginx/Apache and Django.

This can be added to the current image, rather than creating a new image that a user would run as a container alongside the Arches container. 

Adapt `Dockerfile` and `entrypoint.sh`  to run gunicorn instead of django dev server when `MODE=PROD`

**Comment by jmunowitch** [comment]
It looks like the gunicorn server is not using the project folder to launch from, but the Django Dev server is. As such, no project template modifications are working in Production.
