### ISSUE TITLE
Bug: Data Type disabled when adding node in branch

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2585]
### Bug Report
When generating the second tab within a branch graph, the first node create disallows setting data type to anything but semantic.  The current workaround for the bug is to click on another node and then come back to the offending node, but this can take a long time to figure out for an inexperienced user.

http://recordit.co/Kvx1QyvrfU

#### Expected Behavior
The node should allow you to set data type consistent with business rules.

**Comment by ryan86** [comment]
@adamlodge I was unable to reproduce this bug. Can you please check if it's still an issue on the latest? If so, please add more detail about how the issue can be recreated.

**Comment by adamlodge** [comment]
meets requirement
