### ISSUE TITLE
Change Manage Data Link on splashpage

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2590]
### Proposal
A user I am working with finds the option for "Manage Data" on the front splash misleading.  9 times out of 10, when he wants to manage data, he is adding additional attributes to an existing resource, not creating a new resource where one did not exist before.  When following the Manage Data link, the user is tunneled into creating a new resource, and this is not desirable.

Proposal is to do one of the following:
1.  remove the "manage data" link altogether - and thereby force a pathway through search to find the resource he wants to edit, or
2. Change the wording on the link to say "Add Resource"

**Comment by chiatt** [comment]
I am going to close this ticket because in most cases implementors override the index page anyway, and this is a very easy thing to customize.
