### ISSUE TITLE
format numbers as currency

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2591]
### User Story
As a card manager, I want to set up a widget that formats numbers as currency so that I can enter information that is intended to represent currency amounts.  It would be ideal if the symbology could be customized based on the relevant currency type for a given region (ie dollar, euro, peso)

**Comment by chiatt** [comment]
@adamlodge If you want to format a number as currency, you can modify the configs for the widget like so:
Prefix: $
Decimal Places: 2
Increment: .01

**Comment by adamlodge** [comment]
Configs work well in cards, however, the symbology seems not to be reflected in reports or in map bubble.  Requirement not fully met.

**Comment by chiatt** [comment]
@adamlodge The prefix and suffix values now appear in the report.  For the map - you have to configure that in the map popup tab of the resource descriptors function. Something like: 
`Some expense: $<A Currency Node>`

**Comment by adamlodge** [comment]
meets requirement
