### ISSUE TITLE
Ability to Configure Name in search result to access forms rather than reports

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2596]
### User Story
As a user who is primarily concerned with data entry and data editing, my expectation is that the primary link in the search results will take me to data editing forms rather than the resource's report page.  Could we add a configuration option (I would suspect in Basic Search Settings) that allows an implementor to configure the name to direct me to editing forms rather than resource report?

More background:
This is inspired by an instance of arches in which 90% of users are concerned with data editing rather than reporting.  Only a very small subset of users (executives) will look at reports, and likely the reports will be printed by more adept users for their review.

I would suspect that reports would remain the default configuration.

**Comment by mradamcox** [comment]
Another idea that may be easier/faster to implement would be to add an edit button to the result listing for resources that the user has permission to edit. This is how it was handled in v3.

**Comment by jmunowitch** [comment]
@mradamcox. Like this?
![screen shot 2017-10-23 at 14 15 49](https://user-images.githubusercontent.com/1542229/31913682-c727b13a-b7fc-11e7-8835-85f05019af2a.png)

**Comment by mradamcox** [comment]
Ah, yes exactly, I rescind my comment! I'm assuming @adamlodge wants more than that link button.

**Comment by adamlodge** [comment]
@mradamcox indeed.  I'm just seeing that users are consistently invoking the report from the search results when they intend to invoke an edit session. (despite the fact there is an "edit" button readily available)

**Comment by dwuthrich** [comment]
Closing this ticket.  The current UI makes it clear which instances a user may edit and those that are not editable via the "edit" link.  Proposed enhancement obfuscates this ability
