### ISSUE TITLE
Prefix all ElasticSearch indices with a common string on a per project/installation basis

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2612]
The idea here is to allow multiple arches projects/installations to use the same ElasticSearch cluster, just as it's possible to have multiple projects/installations use the same Postgres/PostGIS instance. Currently this is not possible because the names of indices, like `strings`, are hard-coded and used throughout the code-base, so if two independent arches projects are pointed to the same ES instance, they will share all of the same data.

If there a better, cleaner way to accomplish this goal, then please comment below... prefixing the index names was the first thing that we at Legion came up with that seemed both functional and reasonable.

#### Acceptance Criteria
This is more or less up for discussion, but to me the ideal outcome would be a setting, like `ELASTICSEARCH_PREFIX` that could be either set to equal

- the app name (`settings.APP_NAME`)
- blank `''`
- or any other custom string (in case you do want multiple apps to use the same indices).

This string would then be added to the front (probably joined with `"-"`) to every index that is used in the app. This would yield indices named `app-strings`, `app-related_resources`, etc. Naturally, every reference to and elasticsearch index by name in the code base would need to use this prefixed name.

#### Definition of Done
A brand new project can be created, all manner of ES intensive actions done should be performed, and all ES indices should have a user defined prefix. It's necessary to test many different actions, because some indices are not created until they are needed, and they are not always referenced in the same way.

**Comment by apeters** [comment]
see https://github.com/archesproject/arches/tree/2612_elasticsearch_prefixing
for a branch with some existing work toward this end

**Comment by mradamcox** [comment]
Strategy 1: I first tried modifying the SearchEngine class itself, so that a new method would add the prefix to any index name that is passed to any of the search engine methods. I have pushed all of this work to a [new branch](https://github.com/archesproject/arches/tree/2612_elasticsearch_prefixing). You'll see a new file `app.search.search_prefix.py` to which the changes have been made. In settings.py the search backend is pointed toward to this file currently.

Advantages: The main advantage I saw to this strategy was a relatively small amount of work, a very controlled set of changes (only modifying one file, changing a setting, adding a setting), and no changes necessary in terms of how references are made to indices in the future (`se.create(index="strings")` would remain unchanged, e.g.)

Disadvantages: The SearchEngine object is not actually the only object that needs to reference indices by name, see [https://github.com/archesproject/arches/blob/master/arches/app/utils/index_database.py#L204] for an example of a different method being used to which an index name is passed, `se.es.count(index="strings")`. i.e. the changes to SearchEngine are irrelevant, and the actual prefixed index name would need to be passed to that function, which would been pulling the prefix string into that `utils.py` file and manually adding it. This means that developers would need to manually add the prefix to any index name references that _do not_ end up in `se` methods.

**Comment by mradamcox** [comment]
Strategy 2: Create a dictionary of elastic search index names references that could be pulled from anywhere in the app and used whenever an index name is needed. For example, in settings.py you could have `ES={'strings':APP_NAME+"-strings"}` (or load it from elsewhere), then in any other file, `se.create(index=settings.ES['strings'])`.

Advantages: Having a single place that lists all of elasticsearch indices, and can be used to reference a dynamically set (different for each project) would be ideal. Right now, I don't know of anywhere that listed all the names of indices that arches uses. This dictionary could be used (down the road) to drive functions like `es setup_indexes`, or `delete_indexes`. Also, where strategy 1 more or less hides the prefix process from developers, there is no mystery about referencing a dictionary, and I think anyone digging through the code would figure out right away why it exists.

Disadvantages: Lots of up front work to add change everything like `delete_index(index='resource')` to `delete_index(index=ES['resource'])`. A quick search for `(index="` (which is only a good place to start) finds 182 matches across 46 files.

**Comment by mradamcox** [comment]
Personally, I think 2 is the more robust method, though I know @apeters has accomplished this index prefixing for testing, so hopefully he can weigh in with a third option as well.

**Comment by apeters** [comment]
I think the 3rd option is to do the 1st option and to just fix the issues where we call methods on the underlying `es` module directly 
so this:
```se.es.count(index="strings")```
might become this
```se.count(index="strings")```

**Comment by mradamcox** [comment]
Ah, is it the case that anything `se.es` would be doing could be done by `se`?

**Comment by jmunowitch** [comment]
Tested this in Docker: https://github.com/archesproject/arches/issues/2655

Success!
