### ISSUE TITLE
Need mockup for additional "Seed Data" tab in Mobile Project Management

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2621]
A mockup is required for an additional tab in the Mobile Project Management form, that defines the resource instances that mobile apps will be seeded with.

**Comment by dwuthrich** [comment]
See http://archesproject.github.io/mockups/arches_mobile_project_manager.html for mockup of data download tab

**Comment by apeters** [comment]
Should the `custom download` also be limited to 1000 results?

**Comment by dwuthrich** [comment]
It seems like we should allow the admin to limit number of downloadable instances (either by project or as a global setting for all projects).  Downloading 1000 instances seems like a reasonable default.

**Comment by apeters** [comment]
meets requirements
