### ISSUE TITLE
Proposal: Use Menu as a means to group nodegroups for applying permissions

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2622]
### User Story
In the course of implementing user permissions, it would be nice if I could use menu as an idiom for applying or revoking permissions.  For example, I have a data entry menu dedicated to Engineering, and I only want users associated with the "Engineering Editor" User Group to edit data within the Engineering Menu.  The same might hold for other menus associated with other business units in an organization that interact with the application.

BTW - I realize that there may be complications given that one card can be associated with many menus and therefore a naive implementation of this could cause conflicting permissions to be set up.  Would require some thinking through to prevent that.

**Comment by dwuthrich** [comment]
closing as no longer relevant (Arches v4.3 no longer uses menus).
