### ISSUE TITLE
Update browser tab heading based on what aspect of an arches app you are designing

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2623]
### User Story
When doing resource model design workflows, I often have multiple data windows open showing the resource model graph, the cards, and reports, etc.. so I can quickly see how a modification in one (usually the graph) effects the others.  It would make me more efficient if it was easily to tell which browser tab was the graph vs the card vs the report by looking at the heading displayed in the tab.  Currently, when in design mode, it always says "Graph Manager" for these things.

http://recordit.co/vB5EYkWJsB

**Comment by chiatt** [comment]
This ticket is no longer applies based on changes to the graph designer.
