### ISSUE TITLE
Add "Seed Data" tab to Mobile Project Manager tab

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2626]
dependent on mockup (#2621)

**Comment by dwuthrich** [comment]
Does not meet requirement.  Clicking the toggle in the data tab should display a panel (as shown in the mockup http://archesproject.github.io/mockups/arches_mobile_project_manager.html) that allows the user to select which model (or query URL) from which to synch data

**Comment by chiatt** [comment]
Oops - I see. I didn't click on the toggle in the mockup.

**Comment by chiatt** [comment]
@dwuthrich I've added the download panels to the data tab

**Comment by dwuthrich** [comment]
meets requirements
