### ISSUE TITLE
Proposal: Save branch/card from resource model as an actual branch

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2642]
### User Story
As a graph designer, I generally start by making branches, push the cards associated with those branches as far as I can, and then build resources models from the branches.  It is always the case, however, that I want to make adjustments to my branches as I iteratively gain better understanding of what my resource graph, cards, menus, and reports should look like to support end-user needs.  

Current best practice is the following:
1. Make graph and card updates to branches (outside of the resource model)
2. Drop the portion of the resource model's graph represents the old state of the branch
3. Copy the updated branch into the resource model

The reason this is best practice is because it ensures that the original branch reflects the most up-to-date thinking and can be reused later.

In practice, however, I often find myself making modifications to "branches" directly on the resource model rather than in the original branch.  This is because in step 2 (above) I lose the details of my menus, reports, and functions - all of which have to be rebuilt.  Therefore, if the change is minor, I tend to avoid all of that extra work by just making the change on the model.

I would be able to maintain best practice if I had the ability to copy a Card/branch that exists within a resource model and save it as an actual branch.  That would allow me to efficiently dial in the details of my resource model without worrying about keeping branches up to date, and then save the final branches when the resource model is stabilized.

**Comment by apeters** [comment]
this functionality is included with the updated graph manager
