### ISSUE TITLE
Remove resources command deletes system settings instance

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2656]
Currently if an admin runs the `remove_resources` it deletes the system settings instance. By default it should not.

**Comment by mradamcox** [comment]
I'm not sure that this is happening for me... I just deleted all of my resources, but in system settings everything is retained properly. I'm using a project made from the stable/4.0.x branch.

**Comment by chiatt** [comment]
@mradamcox Thanks Adam - Very good to know. I saw it get deleted on an earlier version of Arches, but it likely has been resolved since then.

**Comment by apeters** [comment]
If that's the case, we should close this ticket


Director of Web Development - Farallon Geographics, Inc. - 971.227.3173

**Comment by mradamcox** [comment]
I have been continually loading and removing resources using the stable/4.0.x branch, and system settings are not removed, so I am closing this now. Also, the number of resource removed matched the number of resources I import.
