### ISSUE TITLE
PrefLabel import does not handle commas

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2665]
### User Story
Currently, if data in a CSV is mapped to a concept-list, the importer automatically tries to parse it into a comma-separated list, even if it is escaped. This will result in an error message like this:

    Mon Nov 06 11:08:41 2017 ERROR: datatype: ConceptListDataType value: [u'"School', u'University', u'College"'] on line 2 - badly formed hexadecimal UUID string

where the intention is to import the valid prefLabel `School, University, College` which itself contains commas. Note that in the example, the value is double-quoted properly.

Therefore it is impossible to import preflabels with commas into a concept-list node at this time.

#### Acceptance Criteria
- Importing preflabels that have a comma in them into a concept-list should be possible.

#### suggestion
I would also suggest that change the expected delimiter to a semi-colon would be useful. 1) this is already inside of a comma separated file, so any concept-list itself must already be double-quoted and this would not be necessary with a semi-colon 2) even if things worked correctly, having a preflabel with a comma in it would require double-quoting within double-quoting, which is an intense precedent to set...

**Comment by mradamcox** [comment]
@ryan86 I'm finally able to test this out. Could you please outline what the changes mean in terms of accepted input values so that I can test them appropriately?

**Comment by ryan86** [comment]
@mradamcox this follows the csv convention for including commas in values and excepting quotes from values. So the value you'd like to import with commas needs to be quoted and those quotes need to be excepted if they are not part of the value.

Ex.
"this,""that, other"", another"

The entire comma separated string is quoted then the comma separated substring is quoted ("that, other") and the quotes around the substring are excepted (""that, other"")

Also referenced here: https://github.com/archesproject/arches/pull/2683

**Comment by mradamcox** [comment]
Ok, the following examples load without error, assuming these are all valid preflabels.

##### single concepts, can load into a `concept` node or `concept-list` node
single concept, no comma (as before)
    `Slate`
single concept with a comma in it:
    `"""Shingles, original"""`
##### multiple concepts, can only load into a `concept-list` node
multiple concepts, no commas in any of them:
    `"Slate,Thatch"`
multiple concepts, comma in one of them:
    `"Slate,""Shingles, original"""`
    or
    `"Slate,""Shingles, original"",Thatch"`

Certainly, I think now even more than before that using semi-colons as a delimiter for multiple values in the same column (or allowing a custom delimiter) instead of commas would be best. I see many more potential data migration complications when trying to script the addition of multiple `"` characters than just using, for example, `';'.join(list())` However, closing ticket as the original issue is solved.
