### ISSUE TITLE
Investigate if pyshp is needed

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#2689]
@mradamcox suggested that pyshp functionality could be replaced with the builtin GeoDjango functionality.  In an effort to reduce dependancies, we should look into it.

**Comment by mradamcox** [comment]
I don't know what it is used for, but perhaps if geodjango can replace pyshp, it could also replace shapely.

**Comment by mradamcox** [comment]
Here's how easy it is to use geodjango utils. This code is probably 95% of what is needed to eliminate `pyshp` and `Shapely` from the Arches codebase.

```
from django.contrib.gis.gdal import DataSource
shp = r"C:\arches\AllPublicLandsFL.shp"
ds = DataSource(shp)
layer = ds[0]
crs = layer.srs
for feat in layer:
    name = feat.get("NAME")
    geom = feat.geom.wkt
```

https://docs.djangoproject.com/en/1.11/ref/contrib/gis/layermapping/, http://www.paolocorti.net/2009/04/01/a-day-with-geodjango/, etc.
