### ISSUE TITLE
Upgrade to PostgreSQL 10.*

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2690]
PostgreSQL 10 has been released.

We should verify the viability of this release for Arches, consider and, if decided, upgrade Arches to use PostgreSQL 10.

**Comment by jmunowitch** [comment]
https://wiki.postgresql.org/wiki/New_in_postgres_10#Backwards-Incompatible_Changes

**Comment by jmunowitch** [comment]
AWS RDS now supports ST_AsMVT with their Postgres 10.5 implementation:
https://forums.aws.amazon.com/message.jspa?messageID=838144#871121

**Comment by jmunowitch** [comment]
For the Month of October, I have been using 10.5 locally. 
It seems like this ticket could be closed due to this PR: https://github.com/archesproject/arches/pull/3828

**Comment by chiatt** [comment]
Closing because I'm using 11.1 without any issues.
