### ISSUE TITLE
Upgrade to Elasticsearch 6.4

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2691]
We should evaluate Elasticsearch 6.1 and, if desirable, upgrade Arches to use the latest

**Comment by jmunowitch** [comment]
https://spatiallyadjusted.com/2018/02/07/elastic_620_wkt/
https://www.elastic.co/blog/elasticsearch-6-2-0-released

> Several geospatial systems use [Well Known Text (WKT)](https://en.wikipedia.org/wiki/Well-known_text) as their preferred/only format for geospatial objects.  What if you wanted to use Elasticsearch for your geospatial data though?  Until 6.2, Elasticsearch has only provided the option of providing shapes in [GeoJSON](http://geojson.org/) format.   To get your WKT data into Elasticsearch, you may have to go through a complicated export + conversion process. [No longer!](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/geo-shape.html#input-structure)  You can now index a shape in a WKT string directly to Elasticsearch.

**Comment by jmunowitch** [comment]
Elasticsearch 6.4 is the latest version now: https://www.elastic.co/blog/elasticsearch-6-4-0-released

**Comment by ryan86** [comment]
meets requirements.
