### ISSUE TITLE
Upgrade to next release of Mapbox GL JS

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2692]
Mapbox GL JS 0.41.0 has some very desirable features, but we should wait for the next release before upgrading, as there is this relevant bug that will be resolved in the next release: https://github.com/mapbox/mapbox-gl-js/issues/5473

**Comment by jmunowitch** [comment]
https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.42.0

**Comment by jmunowitch** [comment]
See: https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.42.2

Before upgrading/testing, the bower project will need to be updated

**Comment by jmunowitch** [comment]
New Update:
https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.43.0

**Comment by jmunowitch** [comment]
Latest Update is available on https://github.com/archesproject/mapbox-gl-js-bower/issues/24.

**Comment by jmunowitch** [comment]
Latest update is available on https://github.com/archesproject/mapbox-gl-js-bower/issues/25

**Comment by jmunowitch** [comment]
With https://github.com/archesproject/arches/issues/2916 being pulled into Master, @robgaston updated to the latest version of mapbox-gl-js that is on npm.

The https://github.com/archesproject/mapbox-gl-js-bower repo is now going to be deprecated and is read-only.
