### ISSUE TITLE
String Widgets: Add support for disabled state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2693]
### User Story

Widgets supporting the string data type should support a disabled state.  This should allow the UI to present the widget to a user in a way that makes it clear the value can't be edited or altered.

#### Acceptance Criteria
- [ ] Card designer UI allows user to define a default value that is displayed in any widget that supports the string data type.
- [ ] UI does not display the widget when a user without read privileges requests either a card or report template referencing the widget
- [ ] UI displays the widget in the disabled state when a user without create or delete privileges requests a card referencing the widget.
- [ ] Unit Tests passed
- [ ] Documentation

**Comment by apeters** [comment]
meets requirements
