### ISSUE TITLE
Domain, Domain List Widgets: Add support for disabled state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2694]
Widgets supporting the domain and domain list data type should support a disabled state.  This should allow the UI to present the widget to a user in a way that makes it clear the value it holds can't be edited or altered.

#### Acceptance Criteria
- [x] UI does not display the widget when a user without read privileges requests either a card or report template referencing the widget
- [x] UI displays the widget in the disabled state when a user without create or delete privileges requests a card referencing the widget.
- [x] Unit Tests passed
- [x] Documentation

**Comment by ryan86** [comment]
meets requirements
