### ISSUE TITLE
Number Widgets: Add support for disabled state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2697]
### User Story

Widgets supporting the Number data type should support a disabled state.  This should allow the UI to present the widget to a user in a way that makes it clear the value it holds can't be edited or altered.

#### Acceptance Criteria
- [ ] Card designer UI allows user to define a default value that is displayed in any widget that supports the data type.
- [ ] UI does not display the widget when a user without read privileges requests either a card or report template referencing the widget
- [ ] UI displays the widget in the disabled state when a user without create or delete privileges requests a card referencing the widget.
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by dwuthrich** [comment]
a "disabled" number widget still allows users with read only permissions to edit a number value when the widget appears in a card with cardinality = n.  Widgets in tiles that have been previously saved (and appear when a user opens a previously saved tile) are editable.

**Comment by chiatt** [comment]
@dwuthrich Just pushed a fix for your last comment.  Number widgets that belong to cards with a cardinality of `n` should now be disabled - even in cases when data has already been saved to its tile.

**Comment by dwuthrich** [comment]
Number widget is rendered as disabled in the Card Manager (e.g.: at design time), even though the Graph Editor group has full access privileges to the node.

**Comment by chiatt** [comment]
@dwuthrich Ok - this should be working properly now.

**Comment by dwuthrich** [comment]
meets requirements
