### ISSUE TITLE
GeoJSON Feature Collection Widgets: Add support for disabled state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2698]
### User Story

Widgets supporting the GeoJSON Feature Collection data type should support a disabled state.  This should allow the UI to present the widget to a user in a way that makes it clear the value it holds can't be edited or altered.  For this date type, the data editing tools displayed by default should either be disabled or not rendered 

#### Acceptance Criteria
- [x] Card designer UI allows user to define a default value that is displayed in any widget that supports the data type.
- [x] UI does not display the widget when a user without read privileges requests either a card or report template referencing the widget
- [x] UI displays the widget in the disabled state when a user without create or delete privileges requests a card referencing the widget.
- [x] Unit Tests passed
- [x] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by ryan86** [comment]
meets requirements
