### ISSUE TITLE
Resource Instance Widgets: Add support for disabled state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2699]
### User Story

Widgets supporting the Resource Instance data type should support a disabled state.  This should allow the UI to present the widget to a user in a way that makes it clear the value it holds can't be edited or altered.  

Because this data type references a Resource Instance (and therefore requires business data to have been imported into Arches) I don't think there's a meaningful use case for defining a default value for this widget.

**Comment by apeters** [comment]
meets requirements
