### ISSUE TITLE
File List Widgets: Add support for disabled state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2700]
### User Story

Widgets supporting the File List data type should support a disabled state.  This should allow the UI to present the widget to a user in a way that makes it clear the value it holds can't be edited or altered.  

Because this data type references an external file (and therefore requires user input to import into Arches) I don't think there's a meaningful use case for defining a default value for this widget.

#### Acceptance Criteria
- [ ] UI does not display the widget when a user without read privileges requests either a card or report template referencing the widget
- [ ] UI displays the widget in the disabled state when a user without create or delete privileges requests a card referencing the widget.
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by chiatt** [comment]
meets requirements
