### ISSUE TITLE
GeoJSON Feature Collection Widgets: Add support for default value

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2709]
Widgets also need to allow a designer to select a default value(s) (e.g.: a default GeoJSON value) for the node to streamline data creation.  This default value may take the form of a function (e.g.: current location from a GPS, gracefully failing if no GPS data point is available) to automatically determine the appropriate default value.

**Comment by apeters** [comment]
meets requirements

**Comment by apeters** [comment]
meets requirements
