### ISSUE TITLE
File List Widget: Support preview of image files

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2717]
### User Story

As a data editor, I often wish to review previously uploaded image files when editing a resource instance.  At present, there is no way to view the full image from the Resource Editor; I am forced to request a report of the instance then click on the thumbnail of the image, which then opens a new window.

Desired functionality: implement an "image lightbox" (see http://bashooka.com/coding/10-best-javascript-lightbox-plugins-2017/ for possible libraries) that will support viewing of images within the Resource Editor.

#### Acceptance Criteria
- [ ]
- [ ]
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by chiatt** [comment]
The new photo widget will support this functionality. https://github.com/archesproject/arches/issues/4751
