### ISSUE TITLE
Support resource-instance level permissions

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2725]
As an Arches admin, I need to manage permissions to Arches model instances.  At present, Arches allows me to define node-level permissions.  But there is no way to access to a complete model instance by account or group.

Desired Behavior:
Allow a user to define access privileges to an instance.  Options are:
1.  restrict access to account that created the instance
2. restrict access to members of a group (e.g.: read-only, read/write/delete)
3. allow access to instance by all groups (e.g.: no instance-level restriction).

For options 2 and 3, search would only return a reference to the instance if the user inherits read permissions

**Comment by mradamcox** [comment]
I have needed a similar feature in two previous deployments of Arches.

Most recently in v4, I accomplished it by 
1. creating a widget that allows me to choose an account name as a node in a graph (so a username is stored as an attribute of the resource)
2. creating a new method on Resource() which will return a given node's value by name (pr here https://github.com/archesproject/arches/pull/2845) (so the username from 1 can be tested for)
3. creating a new setting which can designate, on a per-resource model basis, which node to look in and what term to look for (or just `no-access`) https://github.com/legiongis/arches/blob/fpan_master/arches/settings.py#L63
4. some logic in search.py (here, more or less, https://github.com/legiongis/arches/blob/fpan_master/arches/app/views/search.py#L216) which filters per resource model based on the node name and permission criterion.

In my case, I added extra logic to return the current user's name and filter based on that. However, I constructed the code to work in a must more generic way.

This was a pretty in-depth customization, but may be useful for future efforts in this direction.

**Comment by dwuthrich** [comment]
@mradamcox We should consider review and possibly adding your code to core Arches

**Comment by mradamcox** [comment]
@dwuthrich in fact I've just heard that there will be funding for me to revisit the project I did this for, so it's likely we'll be able to put time into pushing something into core Arches. It wouldn't be until spring at the earliest though.

**Comment by chiatt** [comment]
re #5997

**Comment by dwuthrich** [comment]
meets requirements
