### ISSUE TITLE
Map Widget: Remove overlay without having to open overlay manager

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2735]
### User Story

As an Arches user I need to manage the overlays that I want to include on my map using the Overlay Library (accessed by clicking on the "Add Overlay" button in the map).  Often I want to completely remove an overlay from my map, and Arches requires that I return to the Overlay Library to de-select the overlay.

Desired functionality: add a button or icon in the overlay entry (perhaps as part of the overlay opacity tool) that will let me remove the overlay

#### Acceptance Criteria
- [ ]
- [ ]
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by apeters** [comment]
meets requirements
