### ISSUE TITLE
ubuntu xenial not properly prepared for elasticsearch with install script

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2746]
### User Story
currently, neither https://github.com/archesproject/arches/blob/master/arches/install/ubuntu_xenial_setup.sh nor the `python manage.py packages -o es install` modify the `vm.max_map_count` setting. This used to happen when the installation included the rpm and debian packages (up to this commit https://github.com/archesproject/arches/commit/14c9233b35d50bb140a551c41b48fb791bd00112#diff-585893c6dce669430322947316a9f89bL43).

Because this setting modification is OS-specific, it should be taken care of in the ubuntu install script, no in the manage.py command.

I think, though don't have the time to try right now, simply adding this would do it, but I don't know if it's the best approach:

`sudo echo vm.max_map_count=262144 > /etc/sysctl.d/99-elasticsearch.conf`

**Comment by chiatt** [comment]
It might be good to take care of this issue when we update the install script with the latest version of ES. re #2691

**Comment by mradamcox** [comment]
This seems to be taken care of now with ES7 on master branch. Closing.
