### ISSUE TITLE
Change 'mobile project' to 'mobile survey'.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2760]
The term 'mobile survey' was chosen to replace 'mobile project'. References to 'mobile project' (or 'project' when referring to a 'mobile project') should be replaced by 'mobile survey' throughout the arches in UI, code, and database.

**Comment by jmunowitch** [comment]
Is this now considered resolved?

**Comment by chiatt** [comment]
There are still variables in both python and javascript that reference 'projects'.

**Comment by apeters** [comment]
I found one instance of the word "Project"
![screen shot 2018-01-03 at 9 46 00 pm](https://user-images.githubusercontent.com/823773/34552153-b22a847c-f0d4-11e7-8ec2-3b97eb077eb7.png)

**Comment by chiatt** [comment]
@apeters Ok - I think I got the last of the project references now.

**Comment by apeters** [comment]
meets requirements
