### ISSUE TITLE
Identify endpoints for and API that need to be provided to support the Mobile Data Collection App

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2783]
Before we can create an API we need to identify and document the endpoints needed to support the MDCA. 

Some to consider:
1. {host}/GetToken (POST) (already partially implemented, but not documented)
2. {host}/Projects (GET) - Gets a list of projects the user can participate in
3. {host}/Projects/{id} (POST) - For updating project business data
4. {host}/Projects/{id} (GET) - For getting project data (business and tiles)
5. {host}/

**Comment by apeters** [comment]
@dwuthrich it would be nice to hear from you as to what use cases we'd like to support with our API.

**Comment by apeters** [comment]
Use Case:
Manage Business Data (Tile, Resource Instances?)
Read Domain/Concept Data (for business data support)
Tile Cardinality

**Comment by apeters** [comment]
GET: http://localhost/graph/{graph id}
# retrieve node settings and config (eg: domain values, collection id)
GET: http://localhost/graph/{graph id}/node/{node id}
GET: http://localhost/graph/{graph id}/node/{node name}

# manage an entire resource instance including tile data, allow for multiple format output (json, json-ld, etc..)
GET/PUT/DELETE: http://localhost/resource/{resource instance id}
POST: http://localhost/resource/

# access node values directly
GET: http://localhost/resource/{resource instance id}/node/{node id}
GET: http://localhost/resource/{resource instance id}/node/{node name}
PUT: http://localhost/node/{resource instance id}/node/{node id}
PUT: http://localhost/node/{resource instance id}/node/{node name}

# manage a single tile instance
GET/PUT/DELETE: http://localhost/tile/{tile id}
POST: http://localhost/tile/
GET: http://localhost/tile/{tile id}/cardinality

# manage a single concept instance
GET/PUT/DELETE: http://localhost/concepts/{concept id}
POST: http://localhost/concepts/

# manage a single concept collection instance
GET/PUT/DELETE: http://localhost/collection/{collection id}
POST: http://localhost/collection/

**Comment by apeters** [comment]
For requests that return multiple results, a consistent JSON structure should be returned:
```
{
    "count": 1023,
    "next": "https://api.example.org/accounts/?page=5&size=10",
    "previous": "https://api.example.org/accounts/?page=3&size=10",
    "results": [
       …
    ]
}
```

**Comment by dwuthrich** [comment]
meets requirements
