### ISSUE TITLE
List of git branches or tickets or changesets that we would like to have in a new release

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2796]
Ultimately we need to define a list of changesets that can be `cherry picked` from master for use in a 4.0.2 release of Arches.

**Comment by mradamcox** [comment]
Here are my initial suggestions for what should be in the 4.0.2 release.

#### open issues
(Some of these issues are ones I put in the 4.0.1 milestone right after 4.0 was released)
+ clearing a valid search term raises an error #2288
+ incorrect initial resource count in time wheel #2372
+ scroll bars in RDM https://github.com/archesproject/arches/issues/1218
+ import required node validation fail https://github.com/archesproject/arches/issues/2732 (I need to QA this)
+ predefined function/widget ids https://github.com/archesproject/arches/issues/2637 (I need to QA this)
+ handle missing settings https://github.com/archesproject/arches/issues/2602 (I need to QA this)
+ remove `Shapely` and `pyshp` from code-base in favor of geodjango utils
    + please see the comments I have put in the following Issues and PRs. I think this would be well worth the effort, because Shapely has been a problematic library to install on Windows, and ultimately I think these libraries are both unnecessary. It will require a bit of investigation to be sure though.
        + https://github.com/archesproject/arches/issues/2689
        + https://github.com/archesproject/arches/pull/2684
        + https://github.com/archesproject/arches/pull/2688

#### open pull requests
+ firefox scrollbar improvement https://github.com/archesproject/arches/pull/2762
+ done button to branch menu https://github.com/archesproject/arches/pull/2677
+ clean up "form icon" text https://github.com/archesproject/arches/pull/2676
+ removing sub-card terminology https://github.com/archesproject/arches/pull/2674
+ alt text change https://github.com/archesproject/arches/pull/2675

#### changesets/closed pull requests
Some at the bottom of this list may already in stable/4.0.x.
+ change "searchable" text https://github.com/archesproject/arches/pull/2711
+ elasticsearch prefixing
    + https://github.com/archesproject/arches/pull/2638
    + https://github.com/archesproject/arches/pull/2795
+ upgrading django https://github.com/archesproject/arches/pull/2583
+ fix card html in card help title https://github.com/archesproject/arches/commit/a96d777532c0be0cd2de44657f4945851a288113
+ fix floating asterisks https://github.com/archesproject/arches/pull/2587
+ improved error messages for bad concepts on import https://github.com/archesproject/arches/pull/2731
+ remove xlrd requirement https://github.com/archesproject/arches/pull/2687/commits/2dcb5e529a42324625c46de074a09b7411f4e43f
+ fix raw unicode string in ontology https://github.com/archesproject/arches/pull/2745/commits
+ improve button display https://github.com/archesproject/arches/pull/2640/commits
+ unescaped strings https://github.com/archesproject/arches/commit/09dbb5346338023291c1b38e833fbde855ffff88
+ search map height https://github.com/archesproject/arches/pull/2529
+ speed up paged dropdown https://github.com/archesproject/arches/pull/2505

**Comment by chiatt** [comment]
I think we should also include: 

Ensures graph manage menu is visible: https://github.com/archesproject/arches/pull/2680/commits/311eb6b42845f1df1c9614b11f83e19fef8b3fe3

**Comment by ryan86** [comment]
This commit fixes an issue with domain value label import: `2a0a4a58319fbdc627de67e0946d6c7f4df084b4`

**Comment by mradamcox** [comment]
Closing this as the list of changesets and tickets is now irrelevant to the next scheduled release, which will be 4.1, not 4.0.2.
