### ISSUE TITLE
Allow domain values to be suplied in bulk to the domain widget

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2805]
The Card Manager should allow a designer to upload the domain values from a csv file (file needs to include a single column of labels) or some other mechanism. 

- [ ] Card designer UI allows designer to populate the domain list from a simple csv file.

**Comment by ryan86** [comment]
@dwuthrich Domain values can be saved and exported with resource models/branches meaning a user should only have to do manually entry of domain values once and they should be preserved with the model/branch on export/re-import. If a user is entering/managing a large amount of domain values should they use a collection instead?

**Comment by dwuthrich** [comment]
This ticket is primarily for convenience.  Agree that in general we expect domains to be short lists, so your point about this being a one-time effort seems reasonable.  I don't have any issue putting this ticket in the Icebox for now

**Comment by chiatt** [comment]
Duplicate of #2447
