### ISSUE TITLE
Card Manager should allow the designer to re-order the list of values in the domain list.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2806]
Card Manager should allow the designer to re-order the list of values in the domain list.

- [ ] Card designer UI allows designer to re-order the domain list by dragging-and-dropping the list of values

**Comment by adamlodge** [comment]
Meets requirement.

**Comment by adamlodge** [comment]
Noticed that css seems a little squirrley on the entered domain values.  See screenshot.  Can you pretty that up?
<img width="462" alt="screen shot 2017-12-19 at 1 33 26 pm" src="https://user-images.githubusercontent.com/9683819/34179870-6f071cd8-e4c1-11e7-804f-75956d213dbc.png">

**Comment by ryan86** [comment]
@adamlodge neither Cyrus, Alexei or I were able to recreate this css weirdness.

**Comment by adamlodge** [comment]
Meets requirement
