### ISSUE TITLE
Idioms to expand packages to handle

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2822]
This is a listing of additional implementation-specific idioms that may make sense to handle as part of packages:

- Privileges (including users and user groups)
- Ontologies
- Mobile Survey Definitions
- Structure for documentation of the package itself

**Comment by adamlodge** [comment]
soliciting more ideas!

**Comment by chiatt** [comment]
Privileges (including users and user groups) to be addressed by #2815
Ontologies: Resolved in #3693 
Mobile Survey Definitions: to be addressed by #6010 
Documentation: to be addressed by #6011

**Comment by chiatt** [comment]
This ticket is now addressed by individual tickets.
