### ISSUE TITLE
Add Method to Resource Class that will return a node's value

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2828]
This will be extremely useful in many cases, for example it would allow the return of a 403 status for a Resource view request if the resource contains a value that indicates the logged in user is not allowed to see it.

#### Definition of Done
A method called `get_node_value` should be added to arches.app.models.resource.Resource() that will take a node name (string) as an argument. A number of objects will have to be instantiated to make this happen.

##### pseudo code
```
def get_node_value(node_name):
    nodes = Node.objects.filter(name=node_name,resourcemodel_id=self.id)
```
- get all nodegroup ids from these nodes (though, there should only be one unique nodegroup id I think)
- if there are more than one nodegroup_id returned, then this will not work, and the function should return empty and maybe print a message or something. This would happen if there are two different nodes in the graph with the same name, which is possible.
- get all tiles that match that nodegroup id
`tiles = Tile.objects.filter(nodegroup_id=nodegroup_id)`
- iterate tiles and get their values
   - **for this ticket, only string, domain, domain-list, concept, and concept-list datatypes should be handled.** others should return empty or with a message....
   - if a tile's datatype is a concept or concept-list, then the values will be uuids that will need to be transformed to strings. this would probably look like `Value.objects.get(id=uuidfromtiledata).value`
- note that there may be multiple tiles, and each tile (if it contains a domain-list or concept-list) may have multiple values. so iterations are necessary, and every returned value should be a list (even if it only has one item or is empty).

#### Expected Behavior

Something like

```
res = Resource.objects.get(pk="<uuid>")
site_type = res.get_node_value("Site Type")
print site_type
>>> ['House']
other = res.get_node_value("Wrong Node Name")
print other
>>> []
```

**Comment by chiatt** [comment]
Hey @mradamcox, I think this was resolved by @veuncent.  Can you QA?

**Comment by mradamcox** [comment]
@chiatt will get to this soon as I'm now getting back to the original project I needed it for.

**Comment by apeters** [comment]
works as expected
