### ISSUE TITLE
file upload unstable

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2839]
### Bug Report
After uploading a file to a resource, two issues:
1> the thumbnail (for image files) is unavailable to the browser
2> I cant download the uploaded file(s) from the resource's report page

#### Steps to Reproduce (for bugs)

1.Create a resource model with a node of file-list data type
2. Upload a file to that resource
3. refresh the resource's edit page to see the thumbnail disappear
4. Go to resource's report page to see that you cannot download the files

#### Your Arches Information

* Version used:
* Chrome
* Mac

**Comment by mradamcox** [comment]
This could have more to do with the media settings, whether Apache is in use, etc., than with actual Arches code. Could you give some details about the environment?

**Comment by mradamcox** [comment]
Or, this could have to do with #2861

**Comment by adamlodge** [comment]
seems to be resolved
