### ISSUE TITLE
Document release schedule and general expectations concerning our release strategy

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2846]
Release Schedule:
4.1 - User account creation, user profile management, 
4.2 - QA workflow
4.3 - Mobile application

**Comment by apeters** [comment]
the proposed schedule looks reasonable to me

**Comment by dwuthrich** [comment]
Which release will the new graph/card/resource editor work go under?

**Comment by apeters** [comment]
that would be 4.3 - "Relaxed graph constraint"

**Comment by dwuthrich** [comment]
Where is the release schedule published?

**Comment by chiatt** [comment]
Right now it's just in the latest: http://arches.readthedocs.io/en/latest/release-process/

**Comment by dwuthrich** [comment]
We should call release 4.3:

4.3 - Update to Graph Manager, Card Manager and Resource Editor UI to support more sophisticated graphs (anticipated June 2018)

**Comment by dwuthrich** [comment]
meets requirements
