### ISSUE TITLE
Advanced Search: can no longer clear values in a concept widget (or any widget that uses a dropdown, eg: domain, bool, etc)

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2848]
### User Story

Arches no longer allows users to clear a selection from a concept widget (and perhaps also from a domain widget) when using the Advanced Search.  This means that a user can no longer remove a filter from a concept widget without removing and re-adding the filter widget

**Comment by dwuthrich** [comment]
This is still an issue that should be addressed

**Comment by apeters** [comment]
this is still an issue and if the field has default values, then the user is forced to make a selection
![Screen Shot 2020-01-08 at 3 40 18 PM](https://user-images.githubusercontent.com/823773/72025686-c4821d00-322d-11ea-80c4-adc77952dea9.png)

**Comment by dwuthrich** [comment]
meets requirements
