### ISSUE TITLE
Resource edit history page: move date label so that it appears below resource identifier

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2850]
### User Story

Currently Arches displays the description of a resource instance (if configured using the proper function) below the Resource Instance Identifier in the page header.

Remove the description and re-position the date under the resource instance identifier

**Comment by chiatt** [comment]
@dwuthrich It looks like this ticket has already been resolved.

**Comment by dwuthrich** [comment]
@chiatt yes, I resolved the ticket recently and forgot to attach the ticket to the PR.

**Comment by chiatt** [comment]
@dwuthrich Great  - thanks.
