### ISSUE TITLE
Scrollbars in permissions for users/groups and nodes are underneath header

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2853]
### User Story
If I am an admin working with permissions, the scrollbars for the groups/users list and the node list do not work as expected.

![image](https://user-images.githubusercontent.com/10427268/34220205-68f213e4-e579-11e7-9c46-f670ba56a4ff.png)

Apparently the top of the scroll bar in both of these panes is underneath the header, which is a fixed element. I assume there is a spacer at the top of the list that ensures all entries are shown, but the actual top of the scroll bar is obscured. Further, on the left-hand side of the example above, there seems to be no scroll bar, but this is just because the list is very long (many many users) so the bar itself is very small, and it is hidden under the top element.

#### Definition of Done
Fix these scroll bars so they are fully visible.

**There are probably other places in the app that need the same fix to be applied, but I am not sure where they all are.**

#### Your Arches Information
* Version used: 4.0.1
* Browser Name and version: Chrome

**Comment by adamlodge** [comment]
scrollbars still a little wonky.  Reviewed with @chiatt .

**Comment by chiatt** [comment]
@adamlodge Should be good now.

**Comment by adamlodge** [comment]
meets requirement
