### ISSUE TITLE
Fully qualified CRM class and property names are displayed when adding a new card or branch

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2856]
Any newly added cards or branches display a fully qualified CRM class or property name instead of the abbreviated version.

<img width="547" alt="screen shot 2017-12-20 at 1 02 26 pm" src="https://user-images.githubusercontent.com/823773/34228722-825d5f84-e586-11e7-9acb-2d3a367cc985.png">

**Comment by adamlodge** [comment]
Meets requirement
