### ISSUE TITLE
Evolve "Recent Edits" UI

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2869]
### User Story
The edit_log table within the DB contains rich information about every conceivable edit in the Arches system, but the "Recent Edits" UI seems to only expose a small fraction of what is stored in edit_log.  As an arches system admin, I may want the ability to see which user initiated which edits and even be able to see the old and new values so I can identify and resolve issues related to data editing workflows.

Attached screenshots illustrate discrepancy between what is saved in edit_log and available in the recent edits UI.

In addition to what is already there, I would like to see records for:
- Resource delete
- tile create, delete, and update operations
- which user committed the action

I imagine that will involve changing the UI to:
- remove the Created column in favor of something generic like "edit type"
- adding user name column

![screen shot 2018-01-02 at 9 20 08 am](https://user-images.githubusercontent.com/9683819/34492873-4760e370-ef9e-11e7-9aa6-d028358671d3.png)
![screen shot 2018-01-02 at 9 20 33 am](https://user-images.githubusercontent.com/9683819/34492875-4777296e-ef9e-11e7-8fed-dbd79a1c0338.png)

**Comment by dwuthrich** [comment]
@adamlodge The information you have requested in this ticket is already available to a user with edit privileges via the "review edit history" command (accessible from the "Manage..." panel in the Resource Editor).  

FYI, the recent edits page is meant to allow editors to quickly identify resource instances that may be partially completed, or are "in progress".

Given that your user story is already supported using the edit history for a specific instance, I propose closing this ticket

**Comment by adamlodge** [comment]
@dwuthrich Thanks for pointing me to the "review edit history" option.  With that context I still have some comments, but they are more focused, and I will address them in other tickets.
