### ISSUE TITLE
Time value discrepancy in "review edits" and "edit history" pages

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2871]
### Bug Report
Noticing that the time value displayed in both the "review edits" page and the "manage --> edit history page" is three hours off of the correct time of the actual edit.  Also noticed that the value as stored in the edit_log table seems to be accurate.

**Comment by chiatt** [comment]
@adamlodge  I think this issue is related to your `TIME_ZONE` setting in settings.py.  Try changing this to `America/Los_Angeles` or `US/Pacific`

**Comment by adamlodge** [comment]
meets requirement
