### ISSUE TITLE
Recent Edits Page: Add user

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2872]
### User Story

As an Arches administrator, I would like to see which Arches user it was that committed the action being recorded in the recent edits log.  

I can see that the edit_log table has a column for capturing this information, but (in my system) the values are all null - not being captured.

**Comment by chiatt** [comment]
@adamlodge This should now display the user's username - or full name if it's been added to the user's profile.

**Comment by adamlodge** [comment]
meets requirement
