### ISSUE TITLE
Recent Edits page: resource instance deletes

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2873]
### User Story
As an Arches administrator, it would be nice to have a way to see that a given resource instance once existed but has now been deleted.  This will allow me to track if data is incorrectly or inadvertently deleted and will give me a trail with which to recover lost data from the backend edit_log.

As it currently stands, the only way to see deleted tile values is to use the "manage --> review edit history", but if the resource instance is deleted, then there is no way to access this page for the given instance.

**Comment by chiatt** [comment]
@adamlodge I think I've resolved this.

**Comment by adamlodge** [comment]
meets requirement
