### ISSUE TITLE
Rebuild settings graph sans ontology

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2874]
I dont believe there is any value in the Arches settings graph being constructed with CRM (or any other ontology) inbuilt into the graph given that it does not store business data.  (Please chime in if I am wrong in that assertion).  

Given that, there would be some advantages to rebuilding the settings graph as a non-ontology graph.  They include:

- It would be possible (should an implementor choose) to deploy an Arches instance without loading an ontology at all

- It would be easier for Arches developers to modify and extend the settings graph as needs evolve because the graph design would not need to be constrained by the idiosyncrasies of CRM.

**Comment by apeters** [comment]
I agree with you Adam.  This would be a nice change

**Comment by adamlodge** [comment]
@apeters ... Would it be useful for me to rebuild the graph and cards and pin the exported json to this ticket for later deployment?

**Comment by apeters** [comment]
sure, that would be helpful

**Comment by chiatt** [comment]
Meets requirements
