### ISSUE TITLE
Geojson widget lacks dropdown indicator for properties

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2883]
I feel like there should be a dropdown caret for each of those properties.  
Initially it's unclear that those can be expanded.
![screen shot 2018-01-03 at 10 34 48 pm](https://user-images.githubusercontent.com/823773/34552515-c3b1cd02-f0d6-11e7-8f7b-8a6dd5431464.png)

**Comment by apeters** [comment]
If you click on the indicator itself, then the indicator changes but the panel doesn't expand and then can get out of sync.
http://recordit.co/M4MKcEit8O

**Comment by chiatt** [comment]
@apeters Ah - good catch.

**Comment by chiatt** [comment]
@apeters Should be working properly now for clicks to the indicator and its parent panel.

**Comment by jmunowitch** [comment]
Behaves as Expected. 
![geojson widget drop down](https://user-images.githubusercontent.com/1542229/36000398-a85177d4-0cd7-11e8-8c2e-0ae026232526.gif)
