### ISSUE TITLE
v3 can't handle gif image upload

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2898]
### User Story
Uploading a gif file results in a `wrong number of lut entries` error during thumbnail creation.

#### Definition of Done
At the very least, the thumbnail creation could just be skipped for gifs. Better, [generate_thumbnail()](https://github.com/archesproject/arches/blob/stable/3.x/arches/app/utils/imageutils.py#L6) could be enhanced to handle gifs.

**Comment by chiatt** [comment]
Closing because there is no active development on v3
