### ISSUE TITLE
arches_hip.get_version() returns arches version?

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#290]
It's a detail, but strangely when I'm in a python environment and try to print arches_hip.get_version(), it always returns '3.1.2'.  VERSION, as shown from help(arches_hip) should be '1.0.4'.

**Comment by robgaston** [comment]
currently get_version is returning the arches version - the package itself should know and return it's version number and arches.get_version should return the arches version number

**Comment by mradamcox** [comment]
This ticket should be moved to the https://github.com/archesproject/hip repo.

**Comment by mradamcox** [comment]
Closing.
