### ISSUE TITLE
Remove default inclusion of Mapzen map in Arches

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2901]
### User Story

Arches includes a reference to a Mapzen map by default.  Now that Mapzen is closing and their map service hosting will cease, we should remove this layer reference.

**Comment by mradamcox** [comment]
There could be some references to mapzen in settings.py or the template settings_local.py as well, or geocoder references, which will need to be removed too.

**Comment by dwuthrich** [comment]
meets requirements
