### ISSUE TITLE
Remove inactive option for Branches

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2903]
On more than one occasion, I have spun my wheels trying to figure out why a given branch/card is unavailable to be added to a resource model that I am constructing only to find that I failed to set it to "Active".  (An inactive branch is unavailable for being added to a resource model.)  

As I see it, there is no functional advantage to distinguishing between active and inactive branches given that:
1>  (unlike resource models) branch graphs never actually serve as a vessel to collect business data, and
2> Branches are generally evolve iteratively even well after they are added to a resource model

I would propose that all branches are just active. 

If anyone sees this as problematic for some workflow, then I could settle for branches being "active" by default rather than inactive by default as is currently the case.

**Comment by dwuthrich** [comment]
@adamlodge agree on the problem.  We should make branches active by default, but allow a branch designer to make a branch inactive if they desire.  

The card and graph manager should show all branches (active and inactive), but only allow users to select active branches

**Comment by dwuthrich** [comment]
meets requirements
