### ISSUE TITLE
RDM:Cannot delete a concept when no longer being used by a resource

### ISSUE THREAD

**Issue by lucyfj** [archesproject/arches#291]
I entered some heritage resources using the Resource data manager. These resources used concepts in the RDM. I then deleted these heritage resources and tried to delete the concept that I had used, but the RDM would not let me, stating that 'the concept is being used by one or more heritage resources'.  Search shows these resources are definitely deleted from the database. 
Likewise, I had created some 'types' for the External cross Reference and would now like to delete these and enter them to a more appropriate part of the database. But, despite removing the references from all the heritage resources using these types, I cannot delete the concept.

**Comment by dwuthrich** [comment]
@apeters RDM does not appear to remove the concept from left panel in the Collections tab until page is refreshed

**Comment by apeters** [comment]
@dwuthrich, this seems to be fixed in the latest.  Can you confirm?

**Comment by dwuthrich** [comment]
meets requirements
