### ISSUE TITLE
Rework search layers

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2911]
As part of our upgrade to the latest version of mapbox-gl-js, we should rework search layers in a few ways:
- search layers should no longer be delivered as a part of core arches - instead their creation should be delegated to a package
- arches should provide for aggregating search data into a package defined geojson source w/ an assumed name (for layers like our current hex bins)
- arches should also create a raw source of ES aggregated data (as points) for use in other layers, such as a heat map
- arches may need a way to distinguish overlays that are for use in search only
- search layers should probably be collapsed into a single overlay?... this will be determined per package

**Comment by dwuthrich** [comment]
meets requirements
