### ISSUE TITLE
Bump sphinx from 1.3.1 to 1.6.6

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#2914]
RE: https://github.com/archesproject/arches/pull/2868

**Comment by jmunowitch** [comment]
It looks like there could be some incompatible changes between these versions:
http://www.sphinx-doc.org/en/stable/changes.html#release-1-3-2-released-nov-29-2015

This should be tested.

**Comment by mradamcox** [comment]
building the docs locally works fine.

**Comment by jmunowitch** [comment]
https://github.com/archesproject/arches/pull/2932

**Comment by mradamcox** [comment]
tested with 1.6.6 and docs build locally correctly
