### ISSUE TITLE
Migrate from bower to npm/yarn?

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#2916]
We should probably migrate away from bower as:
- [bower encourages migration](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)
- dependabot works w/ npm/yarn
- it may allow us to better package/minify scripts

**Comment by robgaston** [comment]
migrating from bower to yarn compels a migration from requirejs to webpack, which in turn compels a migration from amd to commonjs

reading:
https://bower.io/blog/2017/how-to-migrate-away-from-bower/
https://github.com/sheerun/bower-away
https://gist.github.com/xjamundx/b1c800e9282e16a6a18e
https://github.com/ezhome/django-webpack-loader
https://www.npmjs.com/package/babel-plugin-transform-amd-to-commonjs

**Comment by jmunowitch** [comment]
Our migration from Bower to NPM/Yarn seems pretty finished. We have a few bugs related to upgrading some libraries to a version that is on npm, but that issue has a separate ticket. (https://github.com/archesproject/arches/issues/2917)
