### ISSUE TITLE
Using Arches to build a gazetteer of works by late 19th / early 20th century architect

### ISSUE THREAD

**Issue by richardwilding** [archesproject/arches#293]
Dear All,

I am project manager for a new 'gazetteer' which will catalogue the works by a leading late 19th / early 20th century architect. This will consist of a back-end database allowing our editors to enter a range of metadata (location, date, client, building type, image etc.) for each work, and also a front-end website which will allow the public to browse and search through these same works.

If I wish to appoint a developer who already has experience of building database projects to catalogue cultural heritage, and I want to recommend Arches as a suitable platform, how likely is it that they will be able to get up-to-speed quickly with Arches to create a back-end and front-end website?

Alternatively, how can I go about finding a specialist Arches developer?

Thanks and best wishes,
Richard Wilding

**Comment by robgaston** [comment]
Hi Richard,

Sorry for the late reply (catching up on backlog of issues now!)

A developer with the following skills could hit the ground running w/ arches (for the most part) after reading the documentation:

- Javascript (especially knockoutjs, openlayers and backbone)

- Python (especially django)

- HTML5/CSS3

- SQL


There is a list of service providers on the Arches project website: http://archesproject.org/service-providers/

You can also find others working with Arches on the forum: https://groups.google.com/forum/#!forum/archesproject
