### ISSUE TITLE
Visualize node-value datatype relationship on graph UI

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2930]
As a an Arches data modeler, it would be nice (and consistent) if relationships between nodes defined within the node-value datatype were visualized on the graph UI.

For example, in the attached screenshot, there should be a line between "Value Reference Node" and "Value Node".![Screen Shot 2018-01-12 at 12.09.32 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/a82daa7b-8ee7-4cd7-9b6a-9adde9656883)

**Comment by chiatt** [comment]
This visualization is getting removed
