### ISSUE TITLE
Considerations for node-value datatype

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2931]
This ticket should likely be broken into smaller ones when/if these issues are going to be addressed in code, but I wanted to capture some thoughts after testing and accepting the initial release of the node-value datatype.

- Would be ideal to hide or grey out “Relationship to Node/Select a property” option when the graph is non-ontology because Property is not applicable in the absence of ontology.

- I understand that the relationship between the node-value node and the target node is captured in the configuration of the node-value node, and is not captured in the edges table where all (or at least most) relationships between nodes are captured.  We should consider whether the edges table can/should be retired in favor of node configs, or whether we should double down on edges and try to do a better job of capturing all relationships between nodes there.

- When importing a branch to a resource model that contains node-value node, the target node with the value gets lost. (This is due to new NodeID's being generated as the branch is being copied from branch to resource model.) If we are going to allow users to set a target node within a branch, the I think we should put the effort to preserve that setting after the branch is imported to resource model.

- I noticed some flakiness in the settings panel after branch with datatype is imported to resource model.  Problem is resolved by clicking off the node and back on it, but not good ux.  Again, I am quite certain that this is a result of new nodes with new UUID's being generated, but the configs not keeping up.

- Import/export of node-value nodes is unaddressed at this point.  

- No documentation currently exists

**Comment by apeters** [comment]
Adam, in response to this question

> I understand that the relationship between the node-value node and the target node is captured in the configuration of the node-value node, and is not captured in the edges table where all (or at least most) relationships between nodes are captured. We should consider whether the edges table can/should be retired in favor of node configs, or whether we should double down on edges and try to do a better job of capturing all relationships between nodes there.

I don't we want to get rid of the `edges` table as that stores graph shape.  The node-value datatype stores a reference to an `instance` of a node which is different

**Comment by adamlodge** [comment]
@apeters Sorry the this year-long delayed response... 
I think in the case of json-ld or RDF export of data, this is a meaningless difference.  My only point is that it would be preferable to only have to look in one place for relationships between nodes rather than many places. My personal instinct on implementation approach is to find a way to capture these relationships as edges like all (or at least most) other relationships.

**Comment by adamlodge** [comment]
not longer relevant
