### ISSUE TITLE
User Accounts: Automatically associate a user account to a default group

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2936]
### User Story

Arches allows users to create an account by submitting a user name, email address, and password.  However, these accounts are not associated with any Arches groups, making it hard to manage these kinds of accounts.

Arches should include a "automated account" group and automatically add each web-based new user account to this group.  This would allow Arches model designers to define privileges for members of the group in the same way that they manage permissions for other groups/users

**Comment by apeters** [comment]
@dwuthrich What about adding a setting that allows an admin to define the group (via the name perhaps) that the new user will be added to?

**Comment by dwuthrich** [comment]
@apeters Yes, that would be a totally acceptable solution, so long as we provide a reasonable default.

**Comment by apeters** [comment]
@dwuthrich What would be a reasonable default?  The `Crowdsource Editor`?

**Comment by dwuthrich** [comment]
Yes, that would be fine.

**Comment by dwuthrich** [comment]
meets requirements
