### ISSUE TITLE
Remove in code requirement to use virtualenv and virtualenv directory

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#2939]
Currently, Arches performs a check to see that it is running within a virtualenv. While it should still be highly recommended that Arches be run in a virtualenv we should probably drop the check in code that requires a virtualenv.

This would be helpful for containerization where the container is basically your virtual environment and the actual virtualenv software does not run as well.

#### Acceptance Criteria
- [ ] Ability to install Arches on system python
- [ ] Unit Tests passed
- [ ] Documentation

**Comment by jmunowitch** [comment]
Part of this comes from the question of if a Virtualenv is needed inside a container.

I would defer to @apeters.

**Comment by apeters** [comment]
I agree that we should remove the requirement for a Virtualenv.  Previously, because we actually modified django files, it was a requirement.  We now don't do that and hence the requirement is not strictly necessary.

**Comment by mradamcox** [comment]
Where is this code?

**Comment by jmunowitch** [comment]
> Where is this code?

Here is the main code that I remember from this ticket:
https://github.com/archesproject/arches/blob/master/arches/setup.py#L84

**Comment by chiatt** [comment]
Additionally - the virtualenv directory should be removed from the repo as part of this ticket.

https://github.com/archesproject/arches/tree/master/virtualenv

**Comment by chiatt** [comment]
Works as expected
