### ISSUE TITLE
CRUD: ALL Information Resource forms crash if you save a creation or publication date

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#294]
I've traced this issue back to resource.py.  It's because only in the Information Resource are actual date nodes indexed in prepare_documents_for_map_index().  The get_entity_data function breaks when a datetime object is sent to it.

**Comment by mradamcox** [comment]
To solve, node.value in [this line](https://github.com/archesproject/hip/blob/master/arches_hip/models/resource.py#L191) should be cast to a string.

**Comment by chiatt** [comment]
Closing because there is no active development on v3
