### ISSUE TITLE
GOOGLE_ANALYTICS_TRACKING_ID not set correctly from settings graph

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2942]
### User Story
I have a tracking id set in the UI version of the system settings, but when I reference that value in the templates, it is none. I have printed out all of the settings to the console and confirmed that using both `from arches.app.models.system_settings import settings` and `from django.conf import settings` results in `GOOGLE_ANALYTICS_TRACKING_ID = None`.

To reproduce, make sure you have added a value for the web analytics id in the settings UI, and then add
```
from arches.app.models.system_settings import settings
print settings
```
and/or
```
from django.conf import settings as django_settings
for s in dir(django_settings):
    print s, ':', getattr(django_settings, s)
```
to any view and look to the console for output.
Also, place `google id = "{{GOOGLE_ANALYTICS_TRACKING_ID}}"` in any template and check the output (this is where the value is actually needed anyway).

#### Your Arches Information

* Version used: 4.0.1

#### Context
The workaround is easy, just set `GOOGLE_ANALYTICS_TRACKING_ID` in settings.py, but the fact that this isn't working (at least for me) is puzzling.

**Comment by mradamcox** [comment]
I've been trying to document the settings inheritance pattern, and learned more about this. Turns out the tracking ID, as with a couple other settings, are defined in a context processor, and then passed into the view explicitly within the view itself.

The other thing I've found is that if I open the django shell `python manage.py shell` and run `from arches.app.models.system_settings import settings`, `print settings.APP_NAME` gives me a value that I have set in `settings_local.py`, even if I have a different `APP_NAME` defined through the system settings graph.

**Comment by chiatt** [comment]
I wonder if the unexpected behavior has something to do with the `update_system_settings_cache` method on the tile model. This comparison in that method: `if tile.resourceinstance_id == settings.RESOURCE_INSTANCE_ID` should always evaluate false because a string is getting compared to a UUID. I fixed it at one point because it was preventing saved searches in the system settings from getting updated.  However, I removed my fix however because it seemed to cause other bugs.

**Comment by apeters** [comment]
this should be fixed by #f216f7b

**Comment by chiatt** [comment]
@mradamcox I'm now able to see the tracking ID I set in my system settings form.  Is this working for you as well?

**Comment by beatboxchad** [comment]
It works over here. I modified the index.htm file in my 4.1.1 project and when I refer to it as `app_settings.GOOGLE_ANALYTICS_TRACKING_ID` as seen in the base.htm template in Arches, it shows up. It also appears in the system settings area.

**Comment by mradamcox** [comment]
All good.
