### ISSUE TITLE
Expose graph/branch id in UI

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#2944]
### User Story

As an Arches administrator, I would like to know the internal IDs assigned to models and branches without having to export them and read through the resulting JSON, in order to use these identifiers in external code that manages data for import.  In the future, these URIs might be used to identify the model in an API call to determine which model is used for newly imported records.

An un-editable field at the bottom of the Settings tab of the Model/Branch designer would be great, if possible

**Comment by nlomeli** [comment]
UI access to nodegroup IDs and node IDs would also be helpful for data import.

**Comment by azaroth42** [comment]
Can we add this one to `Roadmap: Graph Designer Update: Task 2` ?

**Comment by azaroth42** [comment]
Agreed, but also the ids for all of the nodes below the model would be necessary too.
Especially if the `@archesNodeId` reference is part of the solution for #3485.

**Comment by adamlodge** [comment]
Gotcha.  I didnt look closely enough at the enhancement to the original user story made by @nlomeli

**Comment by azaroth42** [comment]
This is done in master.
