### ISSUE TITLE
The import business data command should allow for a relative path to the file being loaded

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2947]

**Comment by chiatt** [comment]
@apeters Hey Alexei - did you mean to leave this assigned to you?

**Comment by apeters** [comment]
@chiatt not really, you can grab this if you want

**Comment by adamlodge** [comment]
This doesnt seem to be working, but I'll check again after #3512 is resolved.

**Comment by adamlodge** [comment]
meets requirement
