### ISSUE TITLE
Change password button hidden on smaller screens

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#2949]
When trying to change your password in arches using a small (laptop) screen the 'change password' button can't be seen because it appears outside the browser window. See image below:

![Screen Shot 2018-01-18 at 1.27.36 PM.png](https://images.zenhubusercontent.com/56f0760d6caf56c9d38e0f81/d3229fa0-61a2-455f-944f-a2a2c1c6eda8)

**Comment by apeters** [comment]
what screen resolution was this using?

**Comment by ryan86** [comment]
1680 x 1050

**Comment by ryan86** [comment]
meets requirements
