### ISSUE TITLE
Create configuration manager page chrome

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#297]
Create a skeleton page with header, sidebar, collapsing internal sidebar, and blank container for forms.

See http://archesproject.github.io/mockups/config_manager.html for example

**Comment by mradamcox** [comment]
Not sure where to find the example that is mentioned...

**Comment by robgaston** [comment]
I turned the mockup path above into a live link - thanks for pointing that out, @mradamcox !

**Comment by jmunowitch** [comment]
Initial Config Manager work complete: 03b75e17c363cd4d218b89e08b5f317f9602bae0
