### ISSUE TITLE
Scroll in search page not working in FireFox /IE

### ISSUE THREAD

**Issue by afeliu** [archesproject/arches#2970]
Scroll in search page is not working gor firefox or IE

### Bug Report
I have installed arches v4 and I can see that the scroll on results in the search page is not working so pagination is not avalaible for FireFox or Interntet Explorer

#### Your Arches Information

* Version used: v4
* Browser Name and version: FireFox 57
* Operating System and version (desktop or mobile):  Desktop

![captura](https://user-images.githubusercontent.com/35261672/35290276-05d0cc18-006a-11e8-8595-bfa27976b075.PNG)

**Comment by chiatt** [comment]
@afeliu Thanks for adding this ticket. Someone has already identified this issue and there's a ticket for it in our backlog.  I'm therefore going to close this one as a duplicate.
