### ISSUE TITLE
Allow QA editors to search for provisional tiles 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2975]
### User Story
QA editors will need to search for provisional tiles they would like to review. The search mappings will need to be modified to allow filtering on provisional status (and possibly associated edit log information).  Additionally, search will have restrict the ability to search for provisional tiles to users belonging to the QAEditor group. By default, provisional tiles should not be available in search results.

**Comment by chiatt** [comment]
To QA - 

The general rules by which provisional search works are this: 

Users that belong to the `Resource Reviewer` group (e.g. Admin) save authoritative data while users that do not belong to that group save only provisional data.

`Reviewers` by default should see all provisional and authoritative data in search, but can choose to see exclusively authoritative or provisional data by using the QA filter.

`Provisional` users cannot see any provisional data. If a resource is entirely provisional it should not appear in their search results at all.  If a resource is partially provisional (has both authoritative and provisional data) it will appear in their search results, and they can search on it's authoritative data. However, they will not be able to search on any of it's provisional tiles.

Here are some steps to help you QA this:

1. Create a new user and add them to the `Graph Editor` group. This will be your provisional editor.
2. Log in as the new user and create a new Actor resource instance. Make sure the resource has name, concept, date, and geometry tile values on which to search. 
3. Open the search page. Because all of the data in your resource is provisional, your entire resource is indexed as provisional and should not show up in search results.
4. Try to search for your tile using the term, date or geometry search. You should not be able to see your resource listed in the results, nor should the map zoom to your resource's location.
5. Now open another browser and log in as admin.  You should be able to search for your resource as you would any other. However, change value of the QA dropdown, located under the term search input, to 'Provisional' and you should see only your provisional resource listed in the search results. Change the QA type to Authoritative and your provisional resource should disappear. Also be sure to test inverting your search by clicking on the `Authoritative` or `Provisional` tags in the term search input.
6. Now open your provisional resource for editing as an admin and add another name tile. This will make your resource `Partially provisional`. Confirm that it behaves the same way in search as it did before.
7. Now log in as the graph editor user you created in step one. It should load in your search results because it has some authoritative data. Search for your resource using the provisional name (the one created as a Graph Editor); it should not show up in results.  Now search for it using the authoritative name; you should see it in your results.

**Comment by adamlodge** [comment]
Meets requirement from a search perspective.  I think there are issues around making sure that the right user can edit the right tile at the right time.  Cyrus is focusing on that in https://github.com/archesproject/arches/issues/2974
