### ISSUE TITLE
Unsupported graph shape for csv import

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2976]
I have a branch that is designed to support a one to many relationship between contracts and change orders.  Thereby, one contract can have many change orders, but any one change order can only apply to just one contract.

To do that, the "contracting" branch illustrated in the attached screenshot.  To restrain data entry and build appropriate relationships, I set the following cardinality:

Contracting (card container) - multiples allowed
Contract (card/tab) - only one allowed
Change Order  (card/tab)- multiples allowed

This forces an instance where 1 "contracting" creates each individual contract, and all change orders related to that contract.  If multiple contracts are required, then you add multiple "contracting"s.  

Export for this works great in json format, but csv's exported from data captured in this manner cannot be imported back into the system with their relational integrity intact.  A csv export with a few sample records is attached to illustrate output.
[Port_Projects_2018-01-22_17-03-37_processed.csv.txt](https://github.com/archesproject/arches/files/1658101/Port_Projects_2018-01-22_17-03-37_processed.csv.txt)

Consider the solution for this problem in the context of node-to-node data type support.  Perhaps one solution resolve both.

![screen shot 2018-01-23 at 4 31 16 pm](https://user-images.githubusercontent.com/9683819/35308341-1c4af95e-005c-11e8-8352-8b1e92655a20.png)
![screen shot 2018-01-23 at 4 40 39 pm](https://user-images.githubusercontent.com/9683819/35308359-2f559680-005c-11e8-9c39-98185ba649aa.png)

**Comment by apeters** [comment]
I don't think that the csv output was ever meant to support complex structures like this.  I'm sure @ryan86 would have something to say about this

**Comment by adamlodge** [comment]
I think that is a valid point @apeters.  And I can add credence to it by pointing out that the client for whom I created this data structure has no need to import legacy data (csv or otherwise) into it.  However, Dennis, Ryan, and I discussed this use case together on Monday, and @dwuthrich made a point to ask that I document this as an issue.

**Comment by adamlodge** [comment]
Closing for now
