### ISSUE TITLE
Document the API

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2978]
Part of this work is to identify the form the documentation will take (research how other API's are documented).
Examples should be part of this as well.

**Comment by apeters** [comment]
The api is documented here:
http://arches4.readthedocs.io/en/latest/api/

**Comment by jmunowitch** [comment]
While this is a still work in progress, as development on the API continues, the overall format is set and pretty straightforward.

It may be beneficial to specify what level of authentication is required to hit each endpoint. For Example, the Concept endpoint requires that `a user is a part of the RDM Administrator group.`

**Comment by chiatt** [comment]
Meets requirements
