### ISSUE TITLE
Allow users to force default responses when running the load_package command

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2988]
When loading a package users are prompted to confirm whether they want to overwrite existing graphs in their system with graphs from the package.  This can be a problem if a user wants to automate package loading.

Users should be able to pass an optional argument, `-y` or `--force` to default to `Y` allowing the load to proceed without interruption.

**Comment by mradamcox** [comment]
yes, generally this would be a good rule for all cli commands that have a prompt of any kind.

**Comment by jmunowitch** [comment]
What release is this ticket aimed for? Can we tag it?

**Comment by ryan86** [comment]
meets requirements
