### ISSUE TITLE
IE search page widgets won't close

### ISSUE THREAD

**Issue by mike-campbell-k-int** [archesproject/arches#2993]
### User Story
Trying to use the map on the search page on internet explorer has the map blocked by widgets which are open by default, and they do not close when their respective close buttons are pressed.

#### Definition of Done
Map can be accessed on the search page in IE.

### Bug Report
The search page on internet explorer (tested on versions 10 & 11) has the widgets permanently open 
and they do not close. This blocks users from viewing the map.

#### Expected Behavior
The widgets shouldn't open automatically, and should be able to close.

#### Current Behavior
Map widgets are blocking the map from being viewed and used.

**Comment by jmunowitch** [comment]
This is what the bug looks like:
![image](https://user-images.githubusercontent.com/1542229/36502527-1ace387a-16ff-11e8-8365-d10d2763945b.png)

**Comment by jmunowitch** [comment]
This looks fixed for me in IE11
![ieshim](https://user-images.githubusercontent.com/1542229/36502800-e36a97ce-16ff-11e8-9d67-94ba23a76d82.png)

Zoomed in:
![ieshim2](https://user-images.githubusercontent.com/1542229/36502939-4f6f2282-1700-11e8-9dd5-995c01196a80.png)
