### ISSUE TITLE
Allow branches in graph designer to be collapsed

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3013]
### User Story

As a data modeler, I want to be able to easily see different parts of the model I'm working on, in order to make sure it matches what is required.

### Issue:

Some branches can be extensive, and make it difficult to see the other features of the model.

### Proposal:

Allow a node and all downstream nodes to be collapsed and expanded in the graph view.  When collapsed, only the node remains in view, with an ellipsis or other handle to denote that there are more nodes below it.

### Severity:

Nice to have

**Comment by azaroth42** [comment]
Triage: still valid. Note that "graph view" in issue means the preview mode of designer.

**Comment by chiatt** [comment]
Closing because the d3 graph preview is no longer available in designer.
