### ISSUE TITLE
ProgrammingError: relation "strings" does not exist

### ISSUE THREAD

**Issue by 1000camels** [archesproject/arches#302]
I'm getting a ProgrammingError:
The Exception Value:
  relation "strings" does not exist
  LINE 1: SELECT "strings"."entityid", "strings"."val" FROM "strings" ...

Perhaps there is an issue with my entire system. I am somewhat new to Arches, so I am uncertain whether it is safe to reinstall in order to work from a clean state.

The full debug output is here: http://dpaste.com/2Z00F5T

**Comment by robgaston** [comment]
It appears that your database may not have been deployed properly.

if things are deployed properly you should be able to run the following command:
```sh
psql -d arches_heritagehku -c "SELECT table_name FROM information_schema.tables WHERE table_schema = 'data';"
```

And get something like this for the output:
```
     table_name      
---------------------
 files
 geometries
 numbers
 relations
 strings
 entities
 edit_log
 resource_x_resource
 vw_nodes
 vw_edges
 vw_resources
 vw_resources_line
 vw_resources_point
 vw_resources_poly
 entity_types
 dates
 domains
(17 rows)

```

I see that you are using arches-hip; did you run step 2 ('Create your database') under [Running Arches-HIP](https://github.com/archesproject/hip#running-arches-hip)?

It would be helpful to have some additional information: How did you get to this error?  What OS are you running on? (Some tips for providing good issue reports can be found [here](http://polite.technology/reportabug.html)

**Comment by 1000camels** [comment]
Hi Rob, I appreciate you helping me. Sorry about not providing more information. I thought maybe the debug output was good enough.

I am running on Centos 6.7. I have setup and run this for a while, although not in production. I am still getting familiar with the environment. Some of my issues are related to be unfamiliarity with python, django etc, but I have managed to set up gunicorn, supervisor, nginx.

I have reinstalled several times. I am not certain what I did. Things were working well when I ran into an issue with upload images. I reported it on the Google Group. Then attempted to work on upgrading the Pillow library. Also realised I hadn't created the uploadedfiles directory, which was probably the problem. Then I hit further issues related to the strings table. Finally I am hit the error above. And now, without doing anything else, I am seeing another error; KeyError, Exception Value:	'found' (http://dpaste.com/30PT0HM).

This suggests to me some environment issue, although I am not certain how to debug it.

**Comment by 1000camels** [comment]
I have a feeling my environment is somehow messed up, because I am getting a similar error on another hip project which I had never even touched

My pip modules are:

arches (3.1.2)
arches-hip (1.0.4)
Django (1.6.2)
elasticsearch (1.9.0)
gunicorn (19.4.5)
html5lib (0.9999999)
isodate (0.5.4)
keepalive (0.5)
meld3 (1.0.2)
Pillow (2.4.0)
pip (1.5.4)
psycopg2 (2.6.1)
pyparsing (2.0.7)
pyshp (1.2.3)
PyYAML (3.11)
rdflib (4.2.1)
setproctitle (1.1.9)
setuptools (19.6.2)
six (1.10.0)
SPARQLWrapper (1.7.6)
supervisor (3.2.0)
unicodecsv (0.14.1)
urllib3 (1.14)
wsgiref (0.1.2)
xlrd (0.9.0)

Does that look correct?

**Comment by apeters** [comment]
Hi Darcy,
This issue:

> KeyError, Exception Value: 'found' 

is from elasticsearch.  Do you have the elasticsearch service running?  If so, have you installed any authority documents?  I'm assuming that you haven't installed a newer version of elasticsearch, which could end up throwing that error.

The only time I see this error:

> relation "strings" does not exist

is when the strings table isn't in the database.  Obviously something didn't install correctly.  If you don't mind losing the data in your database, you could always reinstall the arches module in your virtualenv.

You can do this by running the following commands in your activated environment.

```
pip uninstall arches
pip install arches
```

Hopefully that helps.
Cheers,
Alexei

**Comment by 1000camels** [comment]
Ok, I've uninstalled arches_hip and reinstalled it. I created a new arches_app, walking through the steps again. I even reinstalled elastic search independently as well.

The errors keep shifting. Now I am seeing:

relation "dates" does not exist
LINE 1: ...AS "val__max", MIN("dates"."val") AS "val__min" FROM "dates"

What could possibly cause so many issues with the database, when I am doing a normal install (python manage.py packages -o install)?

My Postgresql is version 9.5. Is that a problem?

I also will I understood better the various commands available under manage.py. Perhaps one of those could help.

Ultimately, I need to set up two apps. I have them installed under the same root, where the bin, lib and run directories are. As I understand it, this should be a problem for django apps.

I appreciate any guidance you can provide. I am also going through the Google Group to find issues that are similar to mine.

**Comment by mradamcox** [comment]
Hi Darcy, I've spent many hours working on a Centos 6.5 (strangely there
are no 6.7 AMIs on AWS) test installation today, and it's crazy.  I do
think your problem is with your Postgres installation.  I'd definitely
recommend you go to 9.3 (that's what's in the documentation at least) just
to reduce the potential for errors (I can confirm that PostGIS 2.2 does
work however, at least on windows that is).  However, I'm still having
trouble getting my postgres installation to work on this installation, so
I'll have to get back to you with more info as soon as I can.

Adam

**Comment by apeters** [comment]
FYI, under arches/install we have a centos_core_setup.sh script that may
ease the installation of the dependencies under centos.
-Alexei


Director of Web Development - Farallon Geographics, Inc. - 971.227.3173

**Comment by mradamcox** [comment]
Hi Alexei, thanks, the setup script helped with a few steps but was missing
some things so I've push a new one
<https://github.com/archesproject/arches/blob/master/arches/install/centos6_setup.sh>
to the arches repo.  I had a bunch of those steps from when I worked on it
a while ago, pulling from a few different tutorials (here
<https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-a-centos-vps>
 here
<http://www.postgresonline.com/journal/archives/329-An-almost-idiots-guide-to-install-PostgreSQL-9.3,-PostGIS-2.1-and-pgRouting-with-Yum.html>
here <http://www.liquidweb.com/kb/how-to-install-pip-on-centos-7/> here
<https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4>).
Centos 6 seems to need a lot more babying than Ubuntu, so there are a
number of necessary extra packages.  I'm sure that I have some redundancies
in that script though. It worked on a centos 6.5 instance when run as the
root user.  I put sudo all over it so it should work for a user with sudo
privileges, I just haven't tested that out yet.

Darcy, I'm confident the issue you had was from a bad/partial postgres
installation, possibly just because of the version you were using.  One
thing I found is that the absence of this package
yum install -y postgresql-contrib
will cause certain parts of the arches package install to be left out
(because uuid-ossp is missing), resulting in a partial database similar to
what you were finding, but you can still run the dev server and view the
website.  So you may want to just give that a shot and then reinstall
arches and reinstall the package.

At any rate, I'm not sure how well these commands will work on a machine
with some dependencies in it already, I only tested on blank images.

Adam

**Comment by 1000camels** [comment]
Thank you for that information. I've gone over that script. I've run it. I've also checked over the new script that Adam submitted and I am working with the correct environment. I even dropped my databases and started again.

I've checked my versions. Specifically bringing Postgresql back to 9.3 from 9.5. I think the above error ultimately starts with a failed installation. It seems to happen when I run: python manage.py packages -o install


I get an issue with Indexing:

INDEXING ENTITY NODES
---------------------
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hkarches/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/hkarches/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hkarches/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/hkarches/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/hkarches/lib/python2.7/site-packages/arches/management/commands/packages.py", line 73, in handle
    self.install(package_name)
  File "/home/hkarches/lib/python2.7/site-packages/arches/management/commands/packages.py", line 126, in install
    install() 
  File "/home/hkarches/hongkong/hongkong/setup.py", line 6, in install
    setup.install()
  File "/home/hkarches/lib/python2.7/site-packages/arches_hip/setup.py", line 24, in install
    load_resource_graphs()
  File "/home/hkarches/lib/python2.7/site-packages/arches_hip/setup.py", line 47, in load_resource_graphs
    resource_graphs.load_graphs(break_on_error=True)
  File "/home/hkarches/lib/python2.7/site-packages/arches/management/commands/package_utils/resource_graphs.py", line 69, in load_graphs
    concepts.index_entity_concept_lables()
  File "/home/hkarches/lib/python2.7/site-packages/arches/management/commands/package_utils/concepts.py", line 17, in index_entity_concept_lables
    domains_concept = Concept('00000000-0000-0000-0000-000000000003')
  File "/home/hkarches/lib/python2.7/site-packages/arches/app/models/concept.py", line 60, in __init__
    self.get(args[0])
  File "/home/hkarches/lib/python2.7/site-packages/arches/app/models/concept.py", line 97, in get
    self.load(models.Concepts.objects.get(pk=id))
  File "/home/hkarches/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/hkarches/lib/python2.7/site-packages/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/home/hkarches/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/home/hkarches/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/hkarches/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/home/hkarches/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/hkarches/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 782, in execute_sql
    cursor.execute(sql, params)
  File "/home/hkarches/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/hkarches/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/hkarches/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/hkarches/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "concepts" does not exist
LINE 1: ...concepts"."nodetype", "concepts"."legacyoid" FROM "concepts"...

**Comment by mradamcox** [comment]
Darcy, I'm pretty sure that there have been errors prior to this in your
installation process.  Sometimes the output print messages are too numerous
for you to scroll up far enough to check on the earliest (i.e. most
important) ones.  I'd recommend that you redo your install commands and
write the output messages and errors to a file.  So

pip install arches_hip > archesinstall_log.txt 2>&1

and then, after you make the package and setup elasticsearch:

python manage.py packages -o install > packageinstall_log.txt 2>&1

We should be able to get more information out of those logs.

Just fyi, the arches install command may produce an error during the "wheel
building" process, but that should not affect the actual installation.  (I
think the wheel thing is an alternate installation method, and if it fails,
the normal setup.py installation process is used instead.)

Adam

**Comment by 1000camels** [comment]
Ok, that helped considerably.

My error turned out to be:

/home/hkarches/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/hkarches/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

After doing 'pip install certify’ all was good.

Thanks, Adam!



Darcy W. Christ
Digital Generalist
@1000camels

To send me a secure message: http://bit.ly/SecureMsg
