### ISSUE TITLE
Client side error occurs when new cards are added to the card manager

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3027]
### Bug Report
When trying to add a card in the card manager to a resource model, an error is thrown on the client in models/graph.js because the `nodes` attribute is missing from the client's graph model.

```
graph.js:437 Uncaught TypeError: self.get(...) is not a function
    at graph.js:437
```
The error prevents the page from loading, so users are ultimately unable to save cards to resource models. This occurs in both the master and 4.1.x branches.

**Comment by mradamcox** [comment]
works like a charm now.
