### ISSUE TITLE
Internal graph to RDF mapping fails for literals

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3033]
### Bug Report

While exploring how complicated an import / export API would be to do poorly (but would let some work move forwards until a better solution is in place), I worked with the implementation in .../formats/rdffile.py

It makes an assumption that any node is a Resource, not a Literal value like a string.  Our extension uses rdfs:label (which has xsd:string as its range, which is a literal data type) but the Writer gives:

```
{
  "@id": "http://localhost/resource/a57edf24-222e-48cf-9c85-78652751ff14",
  "@type": ["http://www.cidoc-crm.org/cidoc-crm/E30_Right"],
  "http://www.w3.org/2000/01/rdf-schema#label": [
    {"@id": "http://localhost/tile/617eab82-687b-4968-b1bd-9c6ca0db6f5c/node/17980085-0aad-11e8-b0b6-a4d18cec433a"}
  ]
}
```

Rather than reporting the string value associated with the node, which is "Test Right"

![screen shot 2018-02-08 at 8 59 44 pm](https://user-images.githubusercontent.com/871868/36012454-0de5ff62-0d13-11e8-9137-99e2c6405a53.png)

I would expect:

```
"rdfs:label" : "Test Right"
```

The fix looks like it should be to improve this block:  https://github.com/archesproject/arches/blob/master/arches/app/utils/data_management/resources/formats/rdffile.py#L95

**Comment by azaroth42** [comment]
This worked for me, but is probably terrible...

```python
                if graph_info['subgraphs'][tile.nodegroup]['parentnode_nodegroup'] == None:
                    edge = graph_info['subgraphs'][tile.nodegroup]['inedge']
                    if edge.domainnode.istopnode:
                        domainnode = archesproject['resource/%s' % resourceinstanceid]
                    else:
                        domainnode = archesproject[str(edge.domainnode.pk)]
                    rangepk = str(edge.rangenode.pk)
                    rangenode = archesproject["tile/%s/node/%s" % (str(tile.pk), rangepk)]
                    if rangepk in tile.data:
                        rangenode = Literal(tile.data[rangepk])
                    add_edge_to_graph(g, domainnode, rangenode, edge)
```

**Comment by apeters** [comment]
Can you share the graph that you used to test this?  I'd like to validate what I understand to be the problem.  Seems like a use case I didn't consider.

**Comment by azaroth42** [comment]
Attached, along with the extension ontology doc.

[right_model.zip](https://github.com/archesproject/arches/files/1711743/right_model.zip)

**Comment by apeters** [comment]
Thanks Rob, just as I thought.  This is a use case I hadn't considered.  Single-node nodegroups attached to a resource graph or single-node nodegroups within a nodegroup.
```
              Resource Graph Root (semantic)
                 /                       \
Node (group) 1 (non-semantic)        Node (group) 2 (non-semantic)


Resource Graph Root (semantic)
             |              
     Node (group) 1 (semantic)        
             |
Node (group) 2 (non-semantic)
```

**Comment by azaroth42** [comment]
Do you have a test fixture with all (?!) of the possible graph shapes that could be used to validate the export?

**Comment by apeters** [comment]
It looks like we don't have any test coverage for export (import, yes).

**Comment by azaroth42** [comment]
Test Cases -- model + instance data:
[test_cases.zip](https://github.com/archesproject/arches/files/1732359/test_cases.zip)

**Comment by azaroth42** [comment]
The instance data shape that I'm struggling with:
```
         root (semantic)
                |
         node (semantic)
             /     \
value (string)     node (semantic)
                     \
                      value (string) <-- not present in instance
```

As the second node down is included, due to the presence of the value node, even though it has no data of its own.

**Comment by apeters** [comment]
I'm not sure I fully understand without better labeling, 
can you explain the issue referencing this graph shape:

         root (semantic)
                |
         node 1 (semantic)
             /     \
node 2 (string)     node 3 (semantic)
                     \
                      node 4 (string) <-- not present in instance

**Comment by azaroth42** [comment]
In serializing an instance with this form, nodes 1-3 are included in the representation.  That doesn't make sense, as node 3 is only semantic and has no purpose without node 4.  It gets added because node 2 is there, with a value and hence node 1 has tile data. The algorithm (both original and mine) walk through the edges when there are tiles... and there are tiles due to node 2.  So node 3 and its type are added, but have no tiles of their own.

**Comment by apeters** [comment]
I see the issue.  We need to be able to "peak" down the node chain to see if nodes (or their children) actually have data associated with them.  If they do, then we should serialize those nodes, otherwise we shouldn't.

**Comment by azaroth42** [comment]
I think this issue can be closed as being superseded by newer ones?
