### ISSUE TITLE
Import graph/branch

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#304]
import a resource graph and/or branch from an arches.json file

acceptance criteria:
- [x] import json file and see graph in UI: {URL HERE}
- [x] import should create nodes, edges, nodegroups
- [x] ensure default root node in a resource is not a collector
- [x] ensure default root node in a resource has datatype 'semantic'
- [x] document it

**Comment by jmunowitch** [comment]
Document this to wrap this ticket up

**Comment by apeters** [comment]
Please document!

**Comment by ryan86** [comment]
http://archesproject.github.io/docs/#graphs

**Comment by apeters** [comment]
I would update the doc to show the actual command the user has to enter
eg:
python manage.py packages -o import_json -s data_source

**Comment by dwuthrich** [comment]
meets requirements
