### ISSUE TITLE
Search: Suggested search terms in search dropdown do not have parenthetical context unless they are RDM concepts

### ISSUE THREAD

**Issue by annabelleee** [archesproject/arches#3062]
### Issue
When typing in a search, only RDM concepts have parenthetical context as suggested search terms. This makes it difficult to determine what exactly is being searched on. For example, if "Frank Lloyd Wright" is typed in the search box, "Frank Lloyd Wright" is suggested, but it is unclear whether this is a random string, a string associated with a particular node, or a reference to the "Frank Lloyd Wright" actor resource. Here's an example of the types of suggestions returned when typing in "Frank Lloyd Wright":
"Frank Lloyd Wright"
"Frank Lloyd Wright"
"Lloyd Wright"
"Frank Lloyd Wright Jr."
"Frank Lloyd Wright designed this building in 1923."

#### Ideal Behavior
When typing in the search box, all suggested search terms, except strings unassociated with nodes, should have parenthetical context. For the example above, "Frank Lloyd Wright" should have suggestions such as: 
"Frank Lloyd Wright"
"Frank Lloyd Wright (Actor)" 
"Lloyd Wright (Actor)"
"Frank Lloyd Wright Jr. (Actor)"
"Frank Lloyd Wright designed this building in 1923. (Description)"

In the above example, "(Actor)" is referring to the resource model name and "(Description)" is referring to a string node label. "Frank Lloyd Wright" without a parenthetical is just a string and the assumption is that will search all string nodes.

**Comment by dwuthrich** [comment]
meets requirements
