### ISSUE TITLE
Index nodegroup permissions in ES to improve application performance

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3071]
Currently permissions are read from Postgres via the ORM resulting in a high number of database queries. Indexing permissions in Elasticsearch would reduce the burden on the database and improve application performance.

**Comment by chiatt** [comment]
I discovered that I could use and id rather than an object when getting permissions and eliminate a db query. For example I switched `user.has_perm('read_nodegroup', card.nodegroup)` to `user.has_perm('read_nodegroup', card.nodegroup_id)`. This really reduces the need to index permissions.

**Comment by apeters** [comment]
meets requirements
