### ISSUE TITLE
Investigate/implement site performance improvements using django caching

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3105]
django provides a way to selectively cache parts of the site

**Comment by chiatt** [comment]
@apeters This can probably be QA'd alongside #3071 because the strategy to improve performance (focusing on minimizing db queries rather than caching) was similar.

**Comment by apeters** [comment]
is there anything to QA here?

**Comment by chiatt** [comment]
@apeters I think the work done under #3071 covers this ticket as well.
