### ISSUE TITLE
"Resource models that may be related" styling issue

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3108]
On the status tab of of Settings for resource models, the various resource model names display strangely.  See attached screenshot.![Screen Shot 2018-03-07 at 4.44.46 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/c8619fcc-c0df-4272-a439-e1396f023b02)

**Comment by chiatt** [comment]
Closing because this is related to the old graph manager UI
