### ISSUE TITLE
Graceful error out if no report defined

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3118]
As a user just exploring resources in the system, if I call up a report from search results on a resource model for which there is no report defined, then I get this rather jarring screen in return.  It would be nice if it either jumped to a page that says there is no report defined for this resource model, or if the link to jump to a report from search was disabled.

![Screen Shot 2018-03-12 at 4.44.26 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/f817a39f-1155-4960-971f-e1b5357a837a)

**Comment by chiatt** [comment]
@adamlodge 
Hey Adam - a couple of things you might want to look at when you QA:
- you get an alert if you try to navigate to a report from search
- the jump to report link is disabled in the resource editor 
- if you try to go to the url directly (http://localhost:8000/report/[a resource id]), you get a 404 page letting you know that there is no report available.

**Comment by adamlodge** [comment]
looks good
