### ISSUE TITLE
Passwords: No path to reset password if forgotten

### ISSUE THREAD

**Issue by annabelleee** [archesproject/arches#3119]
### Issue

If login credentials are forgotten, at the moment, there is no way to create a new one. If a person tries to create a new account, the system will recognize that the same email has been used and direct them to the login page to create a new password:
![image](https://user-images.githubusercontent.com/16655095/37364098-c61fe25c-26b6-11e8-9883-44074d7bf615.png)
But upon clicking "Exit" as directed, there is no path to resetting the password. 

#### Expected Behavior

Ideally, some sort of "Forgot password?" link with a way to reset a password should be present in the login screen.

**Comment by apeters** [comment]
meets requirements
