### ISSUE TITLE
Now that we have resource-instance data type, is old fashioned resource-to-resource relationship still relevant?

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3121]
I am unclear whether there are use cases where the old fashioned style approach will be preferable from a data modeling perspective.  I know that there are capabilities (ie force-directed relationships graph) that are exclusive to resource-to-resource, but it seems like that capability could (and maybe should) be ported to resource-instance.

**Comment by mradamcox** [comment]
Very interesting question, and behind it is the tension that has always existed between the filter/search capabilities that come along with having a relationship to a resource (minimal, but with the graph) vs. attributes (all search capabilities)

Ultimately, the graph visualization that resource-to-resource relationships provide is very important, so I think that would need to be brought to the resource-instance before it could actually replace relationships as they exist today.

In terms of modeling, I think the choice between resource-instance nodes and resource-to-resource relationships really comes down to how prescriptive you want to be about the relationships between resources in your database. If you know ahead of time that the only relationships that will exist are between actors and graves, for example (as in "person interred in this grave") then resource-instance nodes in the grave resource model would be the way to go. However, if you want a more open-ended structure that would allow very general, _non-qualified_ relationships to be made between resources, then you may not want to muddy a resource model up with vague nodes.

Maybe all graphs could have, by default, a semi-hidden or immutable resource-instance node for each of the other resource models in the db, which could be utilized for general relationships between resources.

**Comment by apeters** [comment]
RESOLUTION:
It looks like for 4.x we will retain the current method of implementing related resources on the server.  
For 5.x implementation via the resource-instance datatype may be in order.
