### ISSUE TITLE
IE System Settings page won't load

### ISSUE THREAD

**Issue by mike-campbell-k-int** [archesproject/arches#3123]
### User Story
Visiting the System Settings page in Internet Explorer doesn't progress past the loading animation.

#### Definition of Done
System Settings page can be displayed in Internet Explorer.

### Bug Report
The settings page on internet explorer (tested on versions 10 & 11) has the loading animation permanently displayed. This blocks users from viewing or amending the settings.

#### Expected Behavior
Settings page can be accessed using Internet Explorer.

**Comment by chiatt** [comment]
Works as expected
