### ISSUE TITLE
Notify when CouchDB connection fails in the Survey Manager

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3131]
### User Story
Currently when a user creates a new survey, a corresponding database is created in CouchDB. However, if the connection to CouchDB fails, the problem is not clear to the user.  

An alert should be posted notifying the user that the connection has failed and that they need to confirm that the expected service (defined in settings.COUCHDB_URL) is running.

**Comment by chiatt** [comment]
@apeters I tinkered with the error handling after I closed that ticket. Should be working again now.

**Comment by apeters** [comment]
An error message is now displayed, but no message only [object Object]
![screen shot 2018-06-22 at 12 20 20 pm](https://user-images.githubusercontent.com/823773/41795182-b881aae0-7616-11e8-8ab8-642fdbab5324.png)

**Comment by jmunowitch** [comment]
Attempt to create/save survey:
![image](https://user-images.githubusercontent.com/1542229/41882326-373028c0-789d-11e8-8f22-a11771ef37d2.png)
Attempted Delete:
![image](https://user-images.githubusercontent.com/1542229/41882317-257c785e-789d-11e8-808a-96868d92a5be.png)

**Comment by apeters** [comment]
when delete fails, the content in the main panel still disappears.

removing this line should fix that:
https://github.com/archesproject/arches/blob/master/arches/app/media/js/views/mobile-survey-manager.js#L89

**Comment by apeters** [comment]
meets requirements
