### ISSUE TITLE
Remove old documentation files from main arches repo

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#3148]
Now that documentation has all be consolidated into the arches-docs repo, as per #3104, we can remove the /docs/ directory.

However, note that the /docs/releases contents were not built in RTD, thus have not been transferred to the new repo. Those files must be dealt with appropriately and not lost.

It may be worthwhile to double-check for links on the forum and edit/update any past forum posts that reference those release notes.

**Comment by chiatt** [comment]
@mradamcox Following a short discussion with @apeters, I moved the releases into a `releases` directory in root and deleted the `docs` directory.  I took a quick look on the forum and didn't see any broken links to those files.

**Comment by mradamcox** [comment]
@chiatt sounds good to me 👍 There are quite a few forum posts that do reference that url https://groups.google.com/forum/#!searchin/archesproject/releases%7Csort:date, so it would be good to edit them eventually.

Also, is this PR https://github.com/archesproject/arches/pull/3391 that I put up now obsolete because of the recent work you've done? If so could you please close it? And it sounds like you have already discussed this ticket internally https://github.com/archesproject/arches/issues/3389 and resolved it? If so, could you please close it?
