### ISSUE TITLE
Add two-way reference ability for `resource-instance` nodes

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#3154]
This is a proposal for enhancing the way resource-instance datatypes nodes are handled. It is related to #3121.

#### background
Consider two resource models: Condition Assessment and Structure. The graph for the Condition Assessment has a node called "Assessed Structure", which is a resource-instance node pointing to the Structure resource model. (This is a specific example which could be modeled differently, but extrapolate this into any number of examples which this proposal would benefit.)

Currently, if you view a Condition Assessment resource report, it will show a link to the structure, because the Structure link is stored in a tile in the Condition Assessment. However, there is no trace of the Condition Assessment in the Structure.

#### proposal
This proposal is to make a _two-way_ connection the default behavior for resource-instance datatypes. It may be far too involved and introduce too many complications, but one idea would be to add a matching node to the target resource (Structure) behind the scenes whenever a resource-instance node is added to the source resource (Condition Assessment).

Before the node addition

    condition assessment                                              structure
        /                   
     date

after the node addition

    condition assessment                                              structure
        /          \                                                    |
     date      structure (manually added)               condition assessment (automatically added)

Naturally, the if a structure is entered for the Condition Assessment's node, then the corresponding Structure's node automatically be populated.

The main reason for this would be to greatly expand the ways in which these connections can be used.

A few examples: It would make showing the Condition Assessments in the Structure report very easy/already handled. It would make it much easier to replace the related resource graph with a graph generated by these types of embedded node resources. It would allow for more simple methods like the proposed [resource.get_node_values()](https://github.com/archesproject/arches/pull/2845) to be used instead of get_related_resources(), which would also provide a more centralized location for permissions to be handled.

**Comment by apeters** [comment]
closing this ticket in favor of #5290
