### ISSUE TITLE
Update Arches to use Python 3

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3165]
### User Story

Many of Arches' dependancies are now compatible with Python 3, and some having less support for Python 2. We should evaluate the effort needed to update Arches to run on Python 3 and if it is possible to be compatible with both Python 2 and 3. 

#### Acceptance Criteria
-   [ ] All Arches Code compatible with Python 3.*
-   [ ] All Dependancies compatible with Python 3.*
-   [ ] Unit Tests updated and passed
-   [ ] Test pipeline (Travis) updated to test both Python2/3.
-   [ ] Docker Container updated
-   [ ] Installation Documentation updated

#### Definition of Done 
Arches should be able to be run with Python 3.*.

**Comment by mradamcox** [comment]
I would suggest that research begin on the dependencies, before looking at Arches code. Arches has lot of dependencies, so it's quite possible that some of them do not have python 3 bindings yet, and that would probably be the easiest thing to check for first.

**Comment by jmunowitch** [comment]
@mradamcox: @chiatt did a dependency scan recently for Python 3 compatibility, but I am unsure where the results are. Perhaps he can provide them?

**Comment by benosteen** [comment]
Python 2.7 will not be maintained past the beginning of 2020, so there is a definite deadline to consider. https://pythonclock.org/

**Comment by jvasile** [comment]
@jmunowitch, I don't know where @chiatt's dependency scan lives, but it's not terribly hard to do a new (albeit naive) scan:

This evening, I did:

    virtualenv -p python2.7 --prompt "[arches] " venv
    source venv/bin/activate
    pip install arches
    pip freeze > requirements.txt
    deactivate
    virtualenv -p python3 --prompt "[arches-py3] " venv3
    source venv3/bin/activate


Then I did `pip install -r requirements.txt` and every time it failed, I commented out the package that caused failure and reran it.

Pip was able to find and install every package listed in requirements.txt *except* for arches==4.3.3 and mapnik==0.1.  I did not attempt to diagnose the problem with mapnik, though I see Debian offers a python3-mapnik package, so I assume this is a hurdle we could clear.

I have not attempted to run 2to3 on the arches codebase yet, but that would seem to be a logical place to explore next.

**Comment by chiatt** [comment]
I used `caniusedpython3` to check dependencies. I just re-ran it against requirements.txt in master and my results were similar to @jvasile's:

```
caniusepython3 -r requirements.txt 
Finding and checking dependencies ...
[WARNING] mapnik not found

You need 4 projects to transition to Python 3.
Of those 4 projects, 3 have no direct dependencies blocking their transition:

  mapbox-vector-tile
  pyld
  modestmaps (which is blocking tilestache)
```

I think these results are not completely accurate though:
It looks like pyld, mapbox-vector-tile actually support Python 3:
https://github.com/tilezen/mapbox-vector-tile
https://github.com/digitalbazaar/pyld

Based on the Debian build that @jvasile found and tickets in the python-mapnik repo, it appears it's supported as well. https://github.com/mapnik/python-mapnik/issues/36#workspaces/python-mapnik-5be04a234b5806bc2bf13bf2/boards?repos=34407915&search=python3

That leaves just modestmaps: https://github.com/stamen/modestmaps-py

**Comment by mradamcox** [comment]
As this become a more important task, I'd like to float the idea of completing it for the Arches 4.5 release, which should take place sometime this year. That release will also include the upgrade to ES 6 (maybe 7??).

I also think we should make a plan for when Arches stops supporting python 2; i.e. which will be the first release that uses non-backward compatible code like `f""` strings.

**Comment by chiatt** [comment]
Meets requirements
