### ISSUE TITLE
Stub out page for revised graph designer

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3198]
This new page with merge the current Graph Manager and Card Manager into one cohesive page.
The left panel is resizable.  The left side bar is expandable.  The color of the left side bar is unchanged. 
There is a centralized Save/Cancel button that is context sensitive.

![New Graph Designer.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/74dbc865-674d-4b4e-8169-20a615c4d160)

**Comment by apeters** [comment]
@chiatt can you QA this?
the endpoint is available at
http://localhost:8000/graph_designer/{graph_id}

**Comment by chiatt** [comment]
Looks great
