### ISSUE TITLE
Create new graph settings page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3199]
Clicking on the root node of a graph brings up the settings page.  The graph name in the left panel is bound to the name field in the settings page.  

![Screen Shot 2018-04-03 at 3.18.45 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/d965d8db-ddb4-4b12-a94d-bce1d29c4d26)

**Comment by apeters** [comment]
Hitting `Discard Edits` seems to work for every item on the settings page except for:
- The root ontology class
- The color picker 

http://recordit.co/SNtLeKwCdq

**Comment by chiatt** [comment]
@apeters Discard edits should be resetting those properties properly now.

**Comment by apeters** [comment]
@chiatt everything seems to work as expected except the color picker.
Also, when you scroll the color picker stays in the same place.

http://recordit.co/VE94plsSWq

**Comment by chiatt** [comment]
@apeters Nice catch. I didn't notice this last time because I was just looking at the color swatch which was updating properly. Now both the input and color swatch should update properly on reset.

**Comment by apeters** [comment]
errors when saving the settings page don't notify the user with our `AlertViewModel` in designer

**Comment by chiatt** [comment]
@apeters I've added the alert

**Comment by apeters** [comment]
@chiatt a few things:

- let's move the color picker above the icon picker
- remove the left padding from the icon picker (it looks to be about 10px)
- the color picker pop up still stays fixed when scrolling the page

There is a weird save anomaly:
Here's the steps to reproduce:

1. Load the graph settings page
2. Edit the name of the graph to `TESTING`
3. Save the graph
4. Edit the name of the graph to `TESTING 123`
5. Discard your edit
6. The graph name should revert to `TESTING`, but note that it reverts to the name that the page initially loaded with, it looks like this applies to all the fields not just the name field.

**Comment by chiatt** [comment]
@apeters I fixed those style issues and resolved that anomaly with the graph name (as well as a similar issue with the relatable resources checkboxes).

**Comment by apeters** [comment]
meets requirements
