### ISSUE TITLE
Create Card KO Component

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3206]
Create a Knockout component that represents a card object.
Keep in mind that a card can contain other cards or nodegroups.
Only top level nodegroups or nodegroups that can rise in the hierarchy should be presented.

![screen shot 2018-04-04 at 12 27 00 pm](https://user-images.githubusercontent.com/823773/38329737-8b831232-3803-11e8-9e8a-7c45c33463d7.png)
![screen shot 2018-04-04 at 12 27 08 pm](https://user-images.githubusercontent.com/823773/38329747-8f3c66d0-3803-11e8-94ad-a7ecd33af466.png)

**Comment by robgaston** [comment]
@apeters I think this ticket may have been addressed in the work I did on #3210

**Comment by apeters** [comment]
meets requirements
