### ISSUE TITLE
Create a Tree view of cards and instances for the new Resource Editor

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3209]
A "plus" button should appear next to cards with "n" cardinality
For cards with cardinality "1" (not shown in mockup) a summary of the nodes should appear (first node in the group, or something similar)

![Screen Shot 2018-04-04 at 3.09.33 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/fab0a91d-a296-41f5-8105-fa5646c7e129)

**Comment by apeters** [comment]
Rob, the UI for the tree seems to have many issues (see below).
Also, if I try to filter the tree with the word `another` the node in the screenshot below (Another Node...) doesn't highlight.  

![screen shot 2018-05-18 at 2 26 44 pm](https://user-images.githubusercontent.com/823773/40258787-a350a034-5aa7-11e8-9226-97786340ed44.png)

**Comment by robgaston** [comment]
@apeters I've not seen that issue - perhaps you are not 100% on the latest? @adamlodge has been QAing this part of the app and I've not heard anything about these issues from him either.

Can you specify which resource model you are testing w/?  I've been testing w/ Lincoln w/o issue.

**Comment by robgaston** [comment]
@apeters something to keep in mind is that nodes in the tree are a rendering of widgets, so it may be that the issue you are seeing is actually an issue w/ a specific widget (hard to say from here as I don't know what resource model & widgets you are using here).

**Comment by robgaston** [comment]
@apeters here's a screen capture from my local env:
<img width="285" alt="screen shot 2018-05-18 at 2 45 53 pm" src="https://user-images.githubusercontent.com/1187406/40259266-4977fd52-5aaa-11e8-960b-acf1a9c60bba.png">

**Comment by apeters** [comment]
@robgaston It's the node-value datatype that's causing this issue.

**Comment by robgaston** [comment]
node value widget fixed in #3431

**Comment by apeters** [comment]
meets requirements
