### ISSUE TITLE
Resource Editor: Node value datatype dropdown is not populated immediately

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#3219]
When attempting to create a new node-value datatype the node-value dropdown is not populated immediately in the menu. See attached gif.

A workaround involves the user creating the data that will be referenced in the dropdown, going to the search page, finding their new resource, clicking edit to get back to the resource editor where the node-value drop down menu is now populated.

http://recordit.co/Bb3cHmJApz

**Comment by ryan86** [comment]
This works when creating a new resource with the node-value card, but the card configuration form is not working correctly. See attached photo for more information.

![screen shot 2018-05-29 at 10 58 40 am](https://user-images.githubusercontent.com/3038476/40676379-6cd2bbec-632f-11e8-872c-d30ba327d3b7.png)

**Comment by chiatt** [comment]
Good catch @ryan86. Should be working in the resource editor and card manager now.

**Comment by ryan86** [comment]
meets requirements
