### ISSUE TITLE
Add re-index command for CouchDB

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3238]
### User Story

Currently, there is no way to re-create the CouchDB from an existing PostgreSQL database. If a server crash happens, this is needed to get an instance of Arches up and running again.

#### Acceptance Criteria
-   [ ] Management command that can re-build CouchDB from valid Arches DB in PostgreSQL
-   [ ] Unit Tests passed
-   [ ] Documentation

#### Definition of Done
Once a CLI command can be run to re-create the CouchDB from an Arches DB

**Comment by jmunowitch** [comment]
https://github.com/archesproject/arches/pull/3483

**Comment by chiatt** [comment]
Meets requirements
