### ISSUE TITLE
Add the ability to use the remove_resources command on one resource model

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3257]
Currently the remove_resources command line tool only has the ability to remove all resources in the system - regardless of resource model, or any other criteria.  It would be nice to be able to specify the resource model whose resources you wish to delete.  As an arches implementor, this would help with resource model development.

If there are other criteria that might prove useful for defining which resources should be deleted by this command, then I encourage others to comment with ideas.

**Comment by mradamcox** [comment]
This issue is also discussed on the forum here: https://groups.google.com/forum/#!topic/archesproject/afluEq2g9vY

**Comment by jmunowitch** [comment]
Solved by: https://github.com/archesproject/arches/pull/3617
