### ISSUE TITLE
Manage TileServer Cache Commands

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3266]
### User Story

Managing TileServer Cache via command line (Seeding and clearing) should be available. 

When first utilizing the Tile Server, loading overlays on the map take significant time to render. An option to pre-seed the cache should be created.

#### Acceptance Criteria
-   [ ] CLI option to pre-seed the tile server cache.
-   [ ] Unit Tests passed
-   [ ] Documentation

#### Outside Resources
https://github.com/TileStache/TileStache/blob/master/scripts/tilestache-seed.py
https://github.com/TileStache/TileStache/blob/master/scripts/tilestache-clean.py

**Comment by chiatt** [comment]
This ticket is no longer relevant due to the removal of the tileserver.
