### ISSUE TITLE
Deleting a graph with resource instances associated with it doesn't throw an error, but should

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3282]
![screen shot 2018-04-30 at 6 19 08 pm](https://user-images.githubusercontent.com/823773/39457485-19320fa8-4ca3-11e8-884b-35be3e240a17.png)
#### Expected Behavior
The UI should throw an error message like it does when trying to delete a node from a graph that has resource instances associated with it.

#### Current Behavior
The ui doesn't throw an error and it appears that the graph was successfully deleted, but on refresh of the page the graph still there (as it should be).

**Comment by chiatt** [comment]
@apeters Maybe we should just disable that button?

**Comment by apeters** [comment]
@chiatt the problem with just removing that button, is that it then becomes unclear why the delete button is missing.  We already throw an error when deleting a node that explains why you can't delete a node from a graph that has resource instances associated with it.  I think we should just do that.

**Comment by chiatt** [comment]
@apeters Yeah - that makes sense.

**Comment by adamlodge** [comment]
The software works now as expected, but I think the warning messages could be improved a bit.  Every model, regardless of whether instances exist results in the following warning:
![Screen Shot 2018-05-16 at 3.29.25 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/89036356-b295-4f18-b0e0-38d9c139f09c)

If you say OK to that, and there are no instances, then the model/branch just deletes.  If you say OK to that and there are instances, then you are shown the following message:
![Screen Shot 2018-05-16 at 3.30.11 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/1011a3a9-80d9-40b6-a4a4-f97821996e13)

I suggest the following: 

If there are instances in the model, then just show the second of those two warnings and end the process.

Else, just show the first of those two messages and allow the user to proceed.

**Comment by chiatt** [comment]
@adamlodge I think your suggestion is a good one. However, when you press okay in the first message, a trip is made to the sever try to delete the graph. If instances exist, an error is returned in the response which fires the second message.  This means that to skip the first message means an additional service and nested ajax requests in the client.  In other words, making this change is more work than it would seem.

**Comment by adamlodge** [comment]
Ok. Given the sw works as is, I'll close this and open a new one with my suggestion.
