### ISSUE TITLE
Search Map: Clusters are cutoff at edge of map when search page loads

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#3300]
By default when loading the search page resource clusters are cut in half. See image below.

#### Expected Behavior
By default when loading search map, all resource clusters should fully display on map.

![Screen Shot 2018-05-01 at 12.10.47 PM.png](https://images.zenhubusercontent.com/56f0760d6caf56c9d38e0f81/dcda50b4-63c3-47ac-9e59-ad674c5425de)

**Comment by apeters** [comment]
they're no longer getting cut off
