### ISSUE TITLE
Improve timewheel performance

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3306]
There are 2 things that can improve the performance of the timewheel.
1. limit the number of buckets generated 
2. cache the resultant output of the aggregation query (handled in #3343)

Some strategies to consider for 1
- bucket BCE dates at a lower resolution (every 100 years for example)
- allow a user to define bucket resolutions
- allow a user to define min/max date range of the timewheel

**Comment by chiatt** [comment]
Broke caching into a separate ticket: #3343

**Comment by dwuthrich** [comment]
meets requirements
