### ISSUE TITLE
Import: Null Concept Values fail to validate on json Import

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3308]
#### Expected Behavior
Json with null concept values should import without error

#### Current Behavior
Failed to validate tile:f622fac7-593c-4fa6-a54f-ff8da8b26376 at node:84e64f02-1a43-11e7-bdce-6c4008b05c4c with datatype: <arches.app.datatypes.concept_types.ConceptDataType object at 0x11a790d90> and value: None

#### Steps to Reproduce (for bugs)
1. Install Arches 4.1.x
2. Run load_package command with disco-data-pkg
3. Observe error listed above

#### Your Arches Information
* Version used: 4.1.x
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): desktop, macOS
* Link to your Arches Install (optional):

**Comment by jmunowitch** [comment]
Reviewed and looks good.

I did not encounter any errors loading the DISCO Dataset
