### ISSUE TITLE
Create method to centralize the normalizing of request Header parameters and querystring parameters 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3309]
It would be nice to have a method/(base view) that can normalize the parameters passed in via request headers as well as a query strings.  this method/view could then be used in requests to the API to allow users some flexibility in how to pass parameters.

Request header parameters should be prefixed with some easily distinguishable string (eg: "X-", or "Arches-", etc...)

Some headers/parameters we should consider:
- api version
- output format
- token
- profile (flavor) ?? I can't remember what this meant
- metadata (admin)

**Comment by apeters** [comment]
Here's a curl request to use for testing:
curl --header "X-ARCHES-TEST: 123" http://localhost:8000/surveys?test=taco

**Comment by chiatt** [comment]
Works as expected
