### ISSUE TITLE
Clean Up Models.py (and models/migrations/0001_initial.py)

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#331]
Models like:
Nodegroup should become NodeGroup

**Comment by jmunowitch** [comment]
### Camel case model instance names:
Nodegroup -> NodeGroups
### Singularize model names:
Nodes -> Node
### Update table names to snake case
tileinstance --> tile_instance

**Comment by jmunowitch** [comment]
Camel Case Model Instance Names should be taken care of in 742e7fe2ab63614f11fb3899998eda7b086b94c3
Singularize Model Names should be taken care of in: 742e7fe2ab63614f11fb3899998eda7b086b94c3

**Comment by jmunowitch** [comment]
@robgaston: at this point, conceptid in the Value model needs to be renamed to concept:
https://github.com/archesproject/arches/blob/models_upgrade/arches/app/models/models.py#L310
