### ISSUE TITLE
Investigate and Implement OAuth backend to support API calls 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3311]
There is: https://github.com/evonove/django-oauth-toolkit that may be helpful here, but there may be others.
- https://django-oauth-toolkit.readthedocs.io/en/latest/

**Comment by apeters** [comment]
**To test, follow this script:**
https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_01.html#create-an-oauth2-client-application

Once you have a valid token, use that token in a Bearer header to access a restricted resource.  See image below (using Postman)
![screen shot 2018-05-21 at 12 32 39 pm](https://user-images.githubusercontent.com/823773/40326516-5be482d4-5cf4-11e8-9c0f-04a650029082.png)

**Comment by chiatt** [comment]
Works as expected
