### ISSUE TITLE
Allow users to define an JSON-LD context on a per-graph basis

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3314]
A context takes the form of a JSON object as in the example below:

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "https://linked.art/example/object/28", 
  "type": "ManMadeObject", 
  "label": "Example Painting", 
  "classified_as": ["aat:300033618","aat:300133025"], 
  "made_of": [
    {"id": "aat:300015045","type": "Material","label": "watercolor"}
  ], 
  "part": [
    {
      "id": "https://linked.art/example/object/28/part/1", 
      "type": "ManMadeObject", 
      "label": "Canvas Support", 
      "classified_as": ["aat:300014844"], 
      "made_of": [{"id": "aat:300014078","type": "Material","label": "canvas"}]
    }
  ]
}
```

**Comment by ryan86** [comment]
@azaroth42 we were planning to implement this like any other resource model setting. That is, it would appear in the resource model settings UI, probably as another tab with a widget allowing a user to copy/paste/edit the json-ld context. Please let me know if this would not satisfy use case outlined in this ticket.

**Comment by azaroth42** [comment]
That's fine, UI wise :)

Also, the context should be able to be by reference rather than by value ... e.g. a URI to a context, rather than the JSON of the context.  The JSON in the ticket is instance data, not a context definition.

Context JSON looks like: https://www.w3.org/TR/json-ld/#the-context

**Comment by chiatt** [comment]
meets requirements
