### ISSUE TITLE
Add system setting for url slug

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3315]
- need to support multiple prefixes, so setting should probably be a tuple <- we should ask @azaroth42  about this (I'm not sure what the use case is)

an example url: - GET `/{slug}/{graph_alias}/{resource_instance_id}`

**Comment by azaroth42** [comment]
For example, if we have two Arches instances deployed that manage URIs that start with `https://data.getty.edu/` then we need to be able to route requests to the correct instance.  We might then have `https://data.getty.edu/disco/` and `https://data.getty.edu/provenance/`.

**Comment by apeters** [comment]
@azaroth42 I think the question is about **_multiple prefixes_** on a **_single_** instance.  
It was @robgaston's opinion that a tuple of **_multiple prefixes_** simply meant additional "slash" divided parts of the URL path.

EG:
setting tuple = ('disco',) --> `https://data.getty.edu/disco`
setting tuple = ('disco','api',) --> `https://data.getty.edu/disco/api`

is that what was meant?

**Comment by apeters** [comment]
@azaroth42 yes, perfectly!

**Comment by apeters** [comment]
meets requirements

**Comment by apeters** [comment]
@azaroth42 after actually implementing this functionality, @robgaston and I feel that allowing users to essentially add a viarable endpoint isn't the correct solution to the issue of routing/namespacing requests.

I think there are 2 issues
- With a variable endpoint, client apps will first need to know that the endpoint is variable (documentation), and then would have to hit a dedicated (and fixed) endpoint to get the slug variable and then use that with the known part of the final endpoint.  
Eg: a user wants to get a resource instance record
a user can't just hit {host}/reources/{resourceid}
the user first has to hit {host}/get_slug to retrieve the slug value
then the user can use {host}/slug/reources/{resourceid} to get the resource

This is a non-standard way to structure an API
As a user of an API I expect all my endpoints to be the same relative to the host of the instance
If those endpoints can very then I don't have that certainty anymore

- Secondly, if I need to have multiple instances of Arches running at a common host then some system outside of Arches needs to be able to differentiate incomming requests and route them appropriatly.  This is not something that Arches does.  At a very technical level, some system will have to route a request to an endpoint based on some rule which itself will need to point to a wsgi.py file in the Arches instance itself.

Thoughts?

**Comment by azaroth42** [comment]
The URI in the content must be the same as the URI that the content is
retrieved from.

So unless there's a way to configure the URI to some degree, you can't
colocate multiple instances under the same hostname. E.g. data.getty.edu
could only have one arches installation, and our intent is to separate
identity from hosting platform.

**Comment by mradamcox** [comment]
@azaroth42 The configuration you describe is best handled at the webserver level. I have often placed multiple instances on the same server and the same hostname, it is just a matter of getting apache (or whatever your webserver is) to serve your django app from `/disco` instead of from `/`.

There are some forum posts about this because others have wanted the same thing, but this discussion is a good reminder that a little addendum to our existing Apache documentation would be super useful.

**Comment by apeters** [comment]
@azaroth42 I think I finally see what you're getting at.  If I understand correctly, you're concerned about URI's that show up in, for example, json-ld output.
I presume what you'd like to see is this:
```
[
  {
    "@id": "https://data.getty.edu/disco/tile/2765c7ab-0f07-4a37-ba7c-f94e6c89f609/node/6a880278-3474-11e8-b9a9-dca90488358a",
    "@type": [
      "http://www.cidoc-crm.org/cidoc-crm/E55_Type"
    ],
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#value": [
      {
        "@value": "Lincoln Heritage Database"
      }
    ]
  }
]
```
notice `"@id": "https://data.getty.edu/disco/tile/2765c7.....`

If that's the case, then there is already a setting to handle that in settings.py
```
# This is the namespace to use for export of data (for RDF/XML for example)
# Ideally this should point to the url where you host your site
ARCHES_NAMESPACE_FOR_DATA_EXPORT = 'https://data.getty.edu/disco/'
```

Am I on the right track here?

**Comment by azaroth42** [comment]
Yes :) That's fine then! So long as the URIs can be managed effectively in both single instance and reverse-proxied scenarios, count me happy.
(Apologies for the slow response, my laptop died a horrible death while I was at a conference last week)
