### ISSUE TITLE
Implement external slack archive

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3325]
Related to #3324, slack's archiving is extremely limited and unreliable.
If slack is to be used transparently for decision making, as it currently is, then these discussions should be made more persistent.  The integration mentioned in #3324 could then be more valuable if they reference the external archive rather than the ephemeral messages.

slackarchive.io very recently threw all of their code over the wall (and at the same time EoLed their service): https://github.com/dutchcoders/slackarchive. Adopting that code might be a relatively low investment solution.

**Comment by mradamcox** [comment]
This ticket and #3324 point to a more official adoption of Slack for discussion and decision-making concerning this repo. I'm wondering: what is the need and justification for moving these kinds of discussions out of the standard conversation format that github already provides for?

**Comment by azaroth42** [comment]
Conversations already happen in slack about issues in GH, but invisibly to people who are not on slack at that point or perhaps at all. This gives a way to catch up with that discussion and be notified about that discussion, potentially in a timely enough fashion to connect to slack and participate.
