### ISSUE TITLE
Warning thrown on running of requirements.txt

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3327]
Arches throws the following warning during the installation step that runs requirements.txt

`django-revproxy 0.9.14 has requirement urllib3<1.17,>=1.12, but you'll have urllib3 1.22 which is incompatible.`

It seems that whatever is being warned about has no ill effect on the Arches installation.

**Comment by chiatt** [comment]
@ajwuthrich Did you see this error when you ran `pip install -r requirements.txt`?

**Comment by ajwuthrich** [comment]
@chiatt No, the error I got was 

```Usage:   
  
pip <command> [options]

no such option: -r```

**Comment by jmunowitch** [comment]
This should be solved by: 73fa09da05f3753d73a3e9ca10969dae6ef84eb5

**Comment by chiatt** [comment]
Error no longer occurs.
