### ISSUE TITLE
Concepts must remain intact when a collection is deleted

### ISSUE THREAD

**Issue by ViktorGetty** [archesproject/arches#3330]
#### Expected Behavior
When deleting a collection, all concepts that are used in the collection should remain in the DB.

#### Current Behavior
When deleting a collection in RDM, all concepts used in the collection are also deleted. 

#### Steps to Reproduce 
-	Create a new Scheme with the name ‘Test Scheme’
-	Create  a Top Concept for this scheme with the name ‘Top Concept’
-	Add a child concept to this top concept with the name ‘Child Concept’ (so now you have ‘Test Scheme -> Top Concept -> Child Concept’)
-	Create a new collection with the name ‘Test Collection’
-	Add a drop down entry (by searching for ‘Child Concept’) to this new collection (‘Test Collection -> Child Concept’)
-	Press the refresh button of the browser to see the newly created collection.
-	Delete ‘Test Collection’ 
-	The ‘Child Concept’ is gone from ‘Test Scheme -> Top Concept -> …

**Comment by azaroth42** [comment]
I've verified this issue in a separate instance.

**Comment by rvdb** [comment]
This issue seems still around. I don't have a solution, but found a workaround:

1. delete all terms from collection
2. delete collection

This preserves the thesaurus terms.
