### ISSUE TITLE
Search: Search Map Extent: Disabling the Map Filter in the search bar fails to turn off the filter

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3332]
#### Expected Behavior
Using the Search Map Extent function in the main search map adds a Map Filter to the search bar. Clicking the "close" button on the filter should disable the function from filtering search results while continuing to use the search map.

#### Current Behavior
When the close button is clicked on the filter all the search results come back and it appears that the function is turned off. However, the toolbar on the map shows that the function is still on and once the map is moved in any way (zoomed in/out, dragged, etc),  the map filter is turned on again and filters search results. The only way to turn it off is to do so on the map toolbar itself.

This occurs on both Chrome and Safari using the 4.1x branch of the disco-data-pkg.

#### Steps to Reproduce (for bugs)
1. Navigate to the Arches Search engine
2. Activate the "Search Map Extent" function
3. Observe error listed above

http://recordit.co/bUTGB1bJ7N

**Comment by chiatt** [comment]
Now works as expected in the latest
