### ISSUE TITLE
Search: Saved Searches: Add text to the Saved Search webpage

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3333]
When no Saved Searches have been created by the user, the Saved Search tab of the search page is a solid grey page. This could confuse a user into thinking that there are saved searches, but for some reason they are unable to load. Instead, add text to the Saved Search page informing the user that no Saved Searches have been loaded because none exist.

**Comment by chiatt** [comment]
Resolved since saved searches became a search component.
