### ISSUE TITLE
System Settings: Project Name: Renaming the application does not affect the Index page

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3339]
#### Expected Behavior
Changing the Project name should change what title is presented on the browser tab and the Index page that the user first sees when they open Arches. 

#### Current Behavior
When the Project name is changed from the placeholder of Arches, the tab title will change to reflect the name change. However, the Index page does not change to conform to the new title. Furthermore, on the index page, the tab title reverts back to Arches.

#### Steps to Reproduce (for bugs)
1. Change the Project name in the System Settings
2. Reload the page
3. Observe title change on settings page
4. Navigate to the Index page and observe error listed above
http://g.recordit.co/6htao6DXrH.gif

* Version used: 4.1.1
* Browser Name and version: Chrome, Safari
* Operating System and version (desktop or mobile): Mac OS

**Comment by chiatt** [comment]
This would be fixed with #6531
