### ISSUE TITLE
Map: Map fails to render correctly in Internet Explorer

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3349]
#### Expected Behavior
When a Map API Key is entered, the rendering of the map should fill the allotted space on the webpage, in both the search map and the map widget.

#### Current Behavior
When the Map API Key is entered, the entire map only renders in the top left of the map box. This happens in both the Map Search and the map widget. Without the Map API Key, the map box fails to load like normal. The same Map API Key was used on Chrome, Firefox, and Safari and rendered correctly each time.

![screenshot 1](https://user-images.githubusercontent.com/38868744/39785431-040042e2-52d1-11e8-8475-bdf061ccd689.png)

#### Steps to Reproduce (for bugs)
1. Load Arches 4.1.1 in Internet Explorer
2. Enter a Map API Key in the System Settings
3. Navigate to the Map Search page or to the Map widget
4. Observe Error listed above

#### Your Arches Information
* Version used: 4.1.1
* Browser Name and version: Internet Explorer 11
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by chiatt** [comment]
Arches does not support IE
