### ISSUE TITLE
Related Resources: The Related Resources graph does not load

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3352]
#### Expected Behavior
When looking at a Resource Instance's related resources, the Related Resources table and the Graph should show which Resources are related to one another.

#### Current Behavior
When looking at a Resource Instance's related resources graph, the graph fails to load at all, leaving a blank grey screen in the webpage.

![Screenshot (3).png](https://images.zenhubusercontent.com/5ae784c04b5806bc2bd13b56/4ca9301c-d406-4d97-8570-b43d8c171760)

#### Steps to Reproduce (for bugs)
1. Load Arches 4.1.1 in Internet Explorer
2. Load the Related Resources of a Resource instance
3. Navigate to the D3 graph
4. Observe the error listed above

#### Your Arches Information
* Version used: 4.1.1
* Browser Name and version: Internet Explorer 11
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by chiatt** [comment]
This is also an issue in v4.2 and most likely master.  It occurs in Edge as well as IE 11.  In both browsers if the user scrolls down the force directed graph and list of related resources becomes visible (http://recordit.co/kBTa4MrmnD).

**Comment by ajwuthrich** [comment]
Works as intended
