### ISSUE TITLE
Search result count for the anonymous user is lower than expected

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3353]
### User Story
The search result count for the anonymous user, despite having read access to every node group, is lower than it is for the admin user.  If the anonymous user has read permissions on every nodegroup, the search result count should be the same as it is for the admin user.

**Comment by chiatt** [comment]
To QA:

Verify that the 'anonymous' user sees fewer search results than 'admin'. With the lincoln data loaded and logged in as 'admin', the following search should return about 29 resource instances. Logged in as 'anonymous', it should return 0.

Search for Lincoln Heritage Asset - Artefacts in 1801

Using Lincoln Heritage Asset - Artefact descriptors function, reindex the instances.

Re-load the above search for the 'anonymous' user. The count should be the same as it is for the 'admin' user

**Comment by dwuthrich** [comment]
meets requirements
