### ISSUE TITLE
Resource Model Manager: Manage Menus: Card sidebar is cut off

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3360]
#### Expected Behavior
In IE11, when looking at the Menu Manager of a Resource Model, the card sidebar should present the cards in a way that allows the user to see the cards within the Resource Model and allow the user to add them to the menu.

#### Current Behavior
When looking at a Resource Model's menus, the Data Card Library is cut off by the cards that are being edited in the menus. However, the user can still add cards to the menus.

![Screenshot (5).png](https://images.zenhubusercontent.com/5ae784c04b5806bc2bd13b56/f4b6c647-7383-4139-b7f5-c1881c46a544)

#### Steps to Reproduce (for bugs)
1. Load Arches 4.1.1 in Internet Explorer
2. Navigate to the Resource Model Manager
3. Manage a Resource Model's Menus
4. Observe Error listed above

Your Arches Information
Version used: 4.1.1
Browser Name and version: Internet Explorer 11
Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ajwuthrich** [comment]
Sidebars are also cut off when adding cards in the Card Configuration Manager and the Resource Reports mananger, although to a much lesser degree.

**Comment by chiatt** [comment]
No longer relevant since UI was moved to the graph designer.
