### ISSUE TITLE
Permissions Manager: Search Map: Map will zoom on data points that the user does not have access to

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3365]
#### Expected Behavior
When a user or group is put on no access to a Resource Model's location card, using that model's search filter should not cause the data to affect the map or its orientation.

#### Current Behavior
When a user or group is denied access to a Resource Model's location card, the map still reacts to a user search like they have access to the data. The only difference is that the location information does not show up on the map. 

For example, if the administrator was to put the location card of HER Find Models on 'No Access' for a specific user or group, the group would not be able to view the data points on the Map Search. However, if the filter is activated, the map search still zooms in automatically to show the user where the Find Model locations are.

#### Steps to Reproduce (for bugs)
1. Open Arches 4.1.1 in browser
2. Disable 'read' permissions on a Resource Model's location card
3. Navigate to Map search and apply that model's search filter
4. Observe error listed above

http://recordit.co/8PL9Ig1aRd
http://recordit.co/inQWMRyBdv

#### Your Arches Information
* Version used: 4.1.1
* Browser Name and version: Chrome, Safari, Firefox, IE11
* Operating System and version (desktop or mobile): Mac OS, Windows 10

**Comment by chiatt** [comment]
Duplicate of #2492
