### ISSUE TITLE
Map Search: Map zooms in too far on Resource Instances by default

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3366]
#### Current Behavior

When looking at a specific resource instance on the map in the Map Search, by default the map zooms in to it's extent on that specific instance. In a group of resource instances, the map cuts off the outliers as it is trying to zoom in as far as possible on the group while still including all of the instances (see Examples below).

<img width="1440" alt="screen shot 2018-05-10 at 12 11 32 pm" src="https://user-images.githubusercontent.com/38868744/39888966-5b4bea58-544b-11e8-9356-be866d2ac891.png">

http://recordit.co/aLuO6FQCrO

#### Expected Behavior

When using the Map Search, clicking on a Resource Instance's map button takes you to it's location on the map. The map, instead of zooming in to the max level on the instance or group, should zoom in to a level that allows the user to understand the context of the instance's location.

**Comment by adamlodge** [comment]
meets requirement
