### ISSUE TITLE
Map Widget: Valid Geojson input entered and features added, but not panned to

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3368]
#### Expected Behavior
Entering a valid geojson in to the geojson input should create the features described in the code and pan the map over to the new created features.

#### Current Behavior
In IE11, when a valid geojson is added to the input window, the code disappears and nothing appears to happen, as the map does not move. However, when the user zooms out, the features have been added to the map.

#### Steps to Reproduce (for bugs)
1. Open Arches 4.1.1 in IE11
2. Navigate to the map widget through the Card Configuration Manager or on a new Resource Instance
3. Enter valid geojson into the geojson input window
4. Observe errors listed above

#### Your Arches Information
* Version used: 4.1.1
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Windows 10

**Comment by chiatt** [comment]
Arches does not support IE
