### ISSUE TITLE
Map Widget: Valid Geojson input entered, but features are not added

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3369]
#### Expected Behavior
Entering a valid geojson in to the geojson input should create the features described in the code and pan the map over to the new created features.

#### Current Behavior
On Firefox and Chrome, the geojson input works as intended.

However, on Safari the geojson does not work as intended. The valid geojson code can be added to the input, but the code does not disappear from the input window and the map does not create the features nor does it pan to them.

#### Steps to Reproduce (for bugs)
1. Open Arches 4.1.1 in Safari
2. Navigate to the map widget through the Card Configuration Manager or on a new Resource Instance
3. Enter valid geojson into the geojson input window
4. Observe errors listed above

http://recordit.co/3XkfQeVOdJ

#### Your Arches Information
* Version used: 4.1.1
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): Mac OS

**Comment by chiatt** [comment]
This works ok now in v6 with Safari 15
