### ISSUE TITLE
Arches should support hover and click styles for overlays

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3375]
### User Story

Arches should support the same styling of vector tile overlays as it does for resource instances on the search map.  Map styling for resource instances with geometries can be configured for basic display, as well as for alternate symbology when a user hovers or clicks on the resource instance geometry.

Arches should support the same ability to style overlay geometries when a user hovers or clicks on a vector tile geometry in an overlay

**Comment by chiatt** [comment]
If QA'ing with the `lincoln` package you may notice issues with the display of the `raz_high_midieval`, `monument_listed_buildings` and `raz_roman_military layers`.  You will need to delete and reload those layers with the latest versions of those layers in the lincoln_release repo, or reload the lincoln package.

**Comment by dwuthrich** [comment]
meets requirements
