### ISSUE TITLE
Respect sortorder of cards, tiles, and widgets in new resource editor

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#3387]
we need to ensure that cards, tiles and widgets in the new resource editor are sorted properly based on sort order values.

Tiles themselves should be sortable within their cards in the new resource editor tree.

**Comment by adamlodge** [comment]
I can confirm:
- sorting tiles in resource editor works
- changing sortorder values in db (cards_x_nodes_x_widgets table) effects the ordering of widgets in the new resource editor
- changing sortorder in db (cards table) modifies order of cards in the new resource editor.  
- changing sortorder on cards table DOES NOT change ordering of 1:1 cards within the graph designer. Should it? (I am guessing that this will be handled in the new card manager.)

I am guessing this is ready to close, but I wanna talk this through with @robgaston one more time before closing the ticket.

**Comment by adamlodge** [comment]
meets requirement
