### ISSUE TITLE
Add manage menu to new resource editor

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#3388]
the top left "manage" menu in the new resource editor should include the following:
- copy
- delete
- edit history
- report

(see the existing resource editor)

**Comment by adamlodge** [comment]
@robgaston  The Manage option is there and all buttons work except Review Edit History.  Given that the option works when using the old resource editor, I imagine the fix is pretty simple.

**Comment by robgaston** [comment]
@adamlodge good catch, I just merged a fix in for this (#3405)

**Comment by adamlodge** [comment]
meets requirement
