### ISSUE TITLE
Discussion: Best place to store release notes?

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#3389]
Currently, we have release notes stored in /docs/releases as individual markdown files. This made sense previously when all of the documentation was published in readthedocs from the /docs directory. However, now that we've moved the documentation to a new repo, it would be cleaner to get rid of the /docs directory altogether, because the only thing left in it is this releases directory.

Some options:

+ migrate all past releases contents into the github release notes that accompany the actual releases https://github.com/archesproject/arches/releases
    + looking around, it's easy to find projects that follow this pattern, https://github.com/vuejs/vue/releases, https://github.com/Leaflet/Leaflet/releases
+ make a new section in the read the docs documentation for this content
    + this is essentially what django does https://docs.djangoproject.com/en/2.0/releases/
+ make no change and leave this content where it is.

Also take into consideration that Arches' release notes tend to include instructions for upgrading, as here: https://github.com/archesproject/arches/blob/master/docs/releases/4.1.0.md. This content may be more appropriate in the official documentation than in the gihub release notes.

Open to other suggestions and thoughts.

**Comment by chiatt** [comment]
@mradamcox @apeters For the last couple of releases I put the release notes in `arches/releases`.

**Comment by mradamcox** [comment]
@chiatt ok, it's good to have them there for now. overall I don't see this is a pressing issue, but it would be nice to consider placing the notes into the actual release tags as well.

**Comment by chiatt** [comment]
I'm going to close this for now as I think we have a good pattern of placing them in the release directory. However, per the suggestion made by @mradamcox I'll try to add them to the release tag too.
