### ISSUE TITLE
Add the ability to add a branch at any level of the graph (not just the root)

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3397]
Currently the button to bring up the branch list only appears on the root node.  We'll have to change that so that a user can bring up the list from any node and can append a branch at that node. 

Make sure the list is properly filtered based on the selected node

**Comment by ryan86** [comment]
@apeters I've added this functionality in the branch referenced above, but I had to comment out the 'semantic parent node-group' graph validation in the graph model in order to make it work. When you return I would like to discuss whether this validation is still necessary.

**Comment by apeters** [comment]
@ryan86 I don't think that we need that validation anymore

**Comment by apeters** [comment]
@ryan86 can you remove all the code you commented instead of leaving it in the files
- arches/app/media/js/models/graph.js
- arches/app/models/graph.py
- tests/models/graph_tests.py

**Comment by apeters** [comment]
It looks like the logic for determining if a branch can be appended to a graph is now too restrictive.
My test was pretty simple.
- Take an existing graph `Condition Assessment - HER` and export the branch directly beneath the root (Condition State  E3).
- Try too append the branch you just exported to the root of the graph you just exported from.
- At a minimum, that branch should show up in the list of branches that could be appended.

I think we can remove these constraints from the code:
- https://github.com/archesproject/arches/blob/master/arches/app/media/js/models/graph.js#L421-L455
- https://github.com/archesproject/arches/blob/master/arches/app/media/js/models/graph.js#L375-L397
- https://github.com/archesproject/arches/blob/master/arches/app/models/graph.py#L897-L912
- https://github.com/archesproject/arches/blob/master/arches/app/models/graph.py#L855
- https://github.com/archesproject/arches/blob/master/arches/app/models/graph.py#L873-L894

**Comment by ryan86** [comment]
@apeters this appears to work for me . . .

http://recordit.co/DMUUwqXkOt

**Comment by apeters** [comment]
meets requirements
