### ISSUE TITLE
Add the ability to create a branch from a node selected in a graph

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3398]
Users should be able to create a branch by selecting a node in a graph.
The selected node and all its children would form the new branch.

The new name of the branch should take on the name of the new root node.
Ontologies should remain in place.

**Comment by robgaston** [comment]
@apeters as I recall, the root node of a branch is required to always be the start of a node group/card.  Is this still the case w/ the new graph designer?

I'm wondering if we should:
1) only allow for the export of branches from nodes that represent the start of a node group, or, perhaps...
2) enforce grouping at the root node of the branch on export

what do you think?

**Comment by apeters** [comment]
Well, I think it would be pretty easy in the UI to only show an export button at the root node of a nodegroup (where nodeid and nodegroupid are equal) if that's something we want to enforce.

That being said, I'm unsure there's any real good reason to do that.  Why not let a user export from whatever node they want.  No matter what node you pick, you'll either end up with a nodegroup of 1 (the root) or of many.  We have to recreate all the nodegroups anyway.

**Comment by dwuthrich** [comment]
@apeters I agree that it would be nice to let a user pick whatever node they like to define the root node of a new branch.

**Comment by apeters** [comment]
Looks good!  One thing though, maybe we should clear the settings fields for `Subtitle` and `Abstract`, and maybe even `Author` before you save the export, as those don't seem to make as much sense once exported from the graph.

As a test I exported a node from the `Place-HER3` graph an observed the items mentioned above in the exported graph.

**Comment by apeters** [comment]
meets requirements

**Comment by robgaston** [comment]
re: #3205
