### ISSUE TITLE
Deactivating Resource Layer in Map Layer Manager causes errors in rendering the page

### ISSUE THREAD

**Issue by mike-campbell-k-int** [archesproject/arches#3423]
### Bug Report
When a map layer is deactivated in the Resource Layer tab of Map Layer Manager and then the page is refreshed, the layer is no longer able to be selected or edited, and any layers that should appear after it are not shown in the page.

#### Expected Behavior
The map layer should be able to be selected and edited whilst it is deactivated.

#### Current Behavior
As it appears in page:
![image](https://user-images.githubusercontent.com/15122428/40311355-661d69b0-5d07-11e8-97c1-1e240212fb1f.png)

Error message in Chrome:
Uncaught TypeError: Unable to process binding "if: function(){return item.nodeid }"
Message: Unable to process binding "css: function(){return item.config.layerIcon() || item.layer.icon }"
Message: Cannot read property 'icon' of undefined

The deactivated layer does not show in the page, and causes any other layers beneath it to not appear either

#### Steps to Reproduce (for bugs)
1. Go to /map_layer_manager page
2. Toggle a resource layer Activated: toggle to off
3. Refresh or navigate away and return to the page

#### Your Arches Information
* Version used: 4.1 (archesproject:latest)
* Browser Name and version: Chrome and Firefox
* Operating System and version (desktop or mobile): Windows 10
* Link to your Arches Install (optional): https://arcade.lincoln.gov.uk

**Comment by mike-campbell-k-int** [comment]
From what I can tell, it seems that item.layer is undefined in map-layer-manager.htm for a deactivated resource layer, which causes issues on line 52 for item.layer and line 95 for selection().layer when doing a css data-bind.

**Comment by chiatt** [comment]
Works as expected in 4.2 and master
