### ISSUE TITLE
Improve warning/error messaging on resource model delete

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3425]
On delete of resource model, I think the warning messages could be improved a bit. Every model, regardless of whether instances exist results in the following warning:

![image.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/a671d000-7ec6-472d-a9cb-25974a00eb8e)

If you say OK to that, and there are no instances, then the model/branch just deletes. If you say OK to that and there are instances, then you are shown the following message:

![image.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/53cac70b-c592-4118-8f73-b66243da6766)

I suggest the following:

If there are instances in the model, then just show the second of those two warnings and end the process.

Else, just show the first of those two messages and allow the user to proceed.

**Comment by jmunowitch** [comment]
With https://github.com/archesproject/arches/issues/3574, the deletion of a Resource Model completes, and actually deletes the instances associated with it (if there are any).

I will close this for now. If you have an idea of how to improve this process, you can re-open it or file a new ticket.
