### ISSUE TITLE
Graph Manager: The "Graph" and "Card" tabs should remain visible when a user scrolls down the tree

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3436]
The panel tabs should stay in place even after a user scrolls down the tree so that they can quickly toggle between the graph and card views.

**Comment by dwuthrich** [comment]
@ryan86 The expand/collapse and tree search widget should also remain visible when a user scrolls the tree

**Comment by jmunowitch** [comment]
Reviewed and looks good to me. @dwuthrich: Does this match what you had in mind?



![3436treescroll](https://user-images.githubusercontent.com/1542229/42116615-e722e68e-7bac-11e8-8260-5297b0f23205.gif)
