### ISSUE TITLE
Navigating to final page in unfiltered search causes error

### ISSUE THREAD

**Issue by mike-campbell-k-int** [archesproject/arches#3440]
### Bug Report
When clicking to navigate to the last results on the search, this results in an error being displayed: "There was an error retrieving the search results"

#### Expected Behavior
It should show the last results on an unfiltered search.

#### Current Behavior
The search results do not change and an error message displays.

#### Steps to Reproduce (for bugs)
1. Go to the map search page
2. Scroll to the bottom of the search results without inputting anything into the search box
3. Click the last pagination button to go the last search results page

#### Your Arches Information
* Version used: 4.1
* Browser Name and version: Firefox & Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your Arches Install (optional): https://arcade.lincoln.gov.uk/

**Comment by chiatt** [comment]
re #4318

**Comment by apeters** [comment]
fixed in the latest
