### ISSUE TITLE
Breadcrumbs should allow users to navigate the tree as well as add new tiles

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3456]
Clicking on any breadcrumb in the trail will navigate the tree and card to that position.

Additionally, the breadcrumb trail would allow users to add a new child tile via a dropdown (because there could be multiple types of child cards).  This functionality still needs to be reviewed and probably warrants a further discussion with @dwuthrich.                       

![Screen Shot 2018-05-30 at 12.33.09 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/b9df9850-4975-4c8f-9810-aa4ddef85a6f)

![Screen Shot 2018-05-30 at 12.39.38 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/e9b0a28e-961a-483e-8643-422eaf02471a)

![Screen Shot 2018-05-30 at 12.39.38 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/4ee621ff-e422-4ccf-a531-81d1b6887464)

**Comment by dwuthrich** [comment]
meets requirements
