### ISSUE TITLE
Add "Map Settings" form to config manager

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#346]
The form should manage things like (see settings.py for details):
- [x] Default map center and zoom
- [ ] Available basemaps //These can be set in the layer manager
- [x] CACHE_SEED_BOUNDS = (-89.99, 179.99, 89.99, -179.99)
- [x] CACHE_SEED_MAX_ZOOM = 5
- [x] TILE_CACHE_CONFIG = {
    "name": "Disk",
    "path": os.path.join(ROOT_DIR, 'tileserver', 'cache')
}
- [x] MAPBOX_API_KEY = '' # Put your Mapbox key here!
- [x] MAPBOX_SPRITES = "mapbox://sprites/mapbox/basic-v9"
- [x] MAPBOX_GLYPHS = "mapbox://fonts/mapbox/{fontstack}/{range}.pbf"
- [x] DEFAULT_MAP_Y = 0
- [x] DEFAULT_MAP_X = 0
- [x] DEFAULT_MAP_ZOOM = 0
- [x] MAP_MIN_ZOOM = 0
- [x] MAP_MAX_ZOOM = 20
- [x] HEX_BIN_BOUNDS = (-122, -52, 128, 69)
- [x] HEX_BIN_SIZE = 100
- [x] HEX_BIN_PRECISION = 4

**Comment by mradamcox** [comment]
- if basemaps will be defined here, then default basemap should be set here too.
- min and max zoom levels might be nice
- as we've talked about [on the forum](https://groups.google.com/forum/#!searchin/archesproject/extent/archesproject/wQe6uHk9VUA/ZVuNN88oAwAJ), ol3's use of a max extent bounding box is a little non-intuitive, but it may still be nice to support that?

**Comment by dwuthrich** [comment]
@apeters Pushed a new model (Arches System Settings) and a series of branches (Settings*) that define system and search configuration settings.

**Comment by dwuthrich** [comment]
meets requirements
