### ISSUE TITLE
Project Extent: Changes to the Project Extent are not reflected

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3466]
#### Expected Behavior
In the Card Configuration Manager or when editing a spatial location card, the location map should be zoomed in on the project extent by default. Changes to the project extent should be reflected in the card and the card configuration manager.

#### Current Behavior
Currently, the project extent does not affect how the spatial location card or the card configuration manager map act. They show the default worldview no matter what the project extent is.

#### Steps to Reproduce (for bugs)
1. Open system setting to the Project Extent tab. Change it or leave it, just use as a reference.
2. Navigate to the Card Configuration Manager and navigate to the spatial location card.
3. Observe Error listed above

http://recordit.co/cjf6WnYvqk 

#### Your Arches Information

* Version used: 4.2.0
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): Mac
* Link to your Arches Install (optional):

**Comment by chiatt** [comment]
I see this behavior in Chrome as well

**Comment by chiatt** [comment]
This has been resolved in more recent versions of arches.
