### ISSUE TITLE
Search: Clicking on the the title of a search result does not trigger the report

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3467]
#### Expected Behavior
When the user wants to view a resource instance on the search page, they should be able to click on the title link and the report should pop up in a separate tab.

#### Current Behavior
When clicking on the title link, the report does not pop up. 

#### Steps to Reproduce (for bugs)
1. On Safari, navigate to the search page.
2. Click on a search link
3. Observe the error listed above

#### Your Arches Information
* Version used: 4.2.0
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): Mac
* Link to your Arches Install (optional):

**Comment by chiatt** [comment]
This is now working for me in Safari Version 11.1
