### ISSUE TITLE
Cannot assign a resource type to the resource-instance/resource-instance-list datatype configs

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3476]
### User Story
When configuring a resource-instance or resource-instance-list datatype node, the dropdown listing available resource types is not populated. This is the case in both the card manager and the graph manager node form.  

The both datatypes still function properly in the resource editor. However, the list of relatable resources is not constrained to any resource instance type.

**Comment by jmunowitch** [comment]
Reviewed and looks good for 4.2.0.

It looks as though there are some CSS issues though:



![image](https://user-images.githubusercontent.com/1542229/41323590-34eacb94-6e64-11e8-9f13-08bbfde03305.png)

@chiatt thinks the CSS issue should be a different ticket.

**Comment by jmunowitch** [comment]
Reviewed and looks good for master for the Node config (as of 6/22/2018). The Card Config is not yet complete in the new Graph Designer.
