### ISSUE TITLE
XY widget does not work in IE 11 due to camera.js error

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3480]
### User Story
An error occurs in camera.js (which seems to be a mapbox-gl dependency) when using the map widget xy tool.  ![Screen Shot 2018-06-03 at 11.57.26 AM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/c58abf33-db63-4607-ae6f-c0e4c038eb40)

**Comment by jmunowitch** [comment]
Reviewed and looks good for 4.2.0.
![image](https://user-images.githubusercontent.com/1542229/41322463-ec000080-6e5d-11e8-849a-9d6cf37f7025.png)
