### ISSUE TITLE
Dirty state persists when a user saves a provisional edit to a card within a card container.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3481]
### User Story
When a provisional user saves a card within a card container, the provisional data is properly saved, but the save/cancel buttons reappear afterward. If the user presses save again, the save/cancel buttons disappear. This is most likely due to the the parent tile starting with a value of None (tile.data === None). Once the provisional edit is saved its assigned an empty object (tile.data === {}).

http://recordit.co/R9hYAImDVR

The dirty state needs to be cleared after a user saves a provisional edit.

**Comment by jmunowitch** [comment]
Reviewed and looks good for Saving edits in the map.

Does not meet requirements for removing geometry from the map
![dirty state on map](https://user-images.githubusercontent.com/1542229/41321533-3af14c8a-6e59-11e8-8563-3dcf46377929.gif)

**Comment by chiatt** [comment]
The issue with removing a geometry is addressed by #3508.  Because saving works properly per the comment by @jmunowitch above, I'm closing this ticket.
