### ISSUE TITLE
`Create Resource` links are broken on Resource Manager page

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3518]
The Create Resource links at the Resource Manager page (`/resource`) should navigate a user to the new resource editor.

**Comment by ryan86** [comment]
I get the following error when trying to create resources from the /resource page.


![screen shot 2018-06-14 at 1 43 14 pm](https://user-images.githubusercontent.com/3038476/41437371-153f30ca-6fd9-11e8-8cf0-59b666cfe341.png)

**Comment by ryan86** [comment]
Nm, this could have been due to migration/indexing issues. Reloading a package and trying this again works. I will close for now.
