### ISSUE TITLE
Graph Manager: d3 representation

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#352]
d3 Graph and set node as selectable in global view model

acceptance criteria:
- [x] goto graph manager page for test graph, see d3 rendering
- [x] ability to select nodes via click
- [x] styled nodes based on select state and currently selected group, currently filtered set from node list
- [ ] document it

**Comment by apeters** [comment]
Meets functional requirements

**Comment by jmunowitch** [comment]
I am noticing that the Document This check box is still unchecked. Is documentation still needed?

**Comment by robgaston** [comment]
I believe that this was just in reference to documenting the code itself, which is actually completed - thus I'm checking that off now.  Thanks for the reminder!
