### ISSUE TITLE
Graph Manager: Node Management Form

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#353]
- [x] Take globally selected node and provides a form for managing it
- [x] Form should validate CRM Ontology (Validate and Warn, not enforce)
- [x] Form should only display valid ontologies
- [x] Saving data back to Database

**Comment by apeters** [comment]
Repeatable flag is now migrated to the Card Manager (need to remove from this form)

**Comment by robgaston** [comment]
fixed with https://github.com/archesproject/arches/pull/467

**Comment by dwuthrich** [comment]
Node Manager has the following issues:

1. Does not validate CRM properly.  Example: CRM allows two E53 nodes to be be related via P87.  However, the node manager does not allow user to select the P87 property to relate 2 E53 nodes .

2. Adding a node/node-type graph does not allow user to define the node-type as an E32 CRM class

3. Form allows user to define data type for E55 nodes as any primitive.  An E55 is by definition (I think) a domain type.

4. Node Manager allows user to select any node type for an E32 (auth doc) type.  Is this correct?

5. Graph list (shown when adding a child node) allows user to select the current graph being edited.  I think this is a problem.

**Comment by apeters** [comment]
Re items above:

1. The CRM allows you to related two E53 nodes via P89 not via P87.  Using a P87 you can relate an E53 to a E44.
1. If you don't change the property from P2_has_type then you can't change the node-type node to an E32 class
1. I personally don't think that we should enforce any datatype to class relationship.  Our system of managing ontologies is quite simple now and doesn't really have any intelligence built into it.  We really just saving a string which we would probably have to promote to something like a key in a related table.
1. see above
1. Hmm, I'm eating my own tail am I?  Probably should fix that!

**Comment by dwuthrich** [comment]
Re:

1. Yup.  User error (and old eyes) made "89" look like "87".  FYI, our HIP graphs are wrong (they show p87 properties connecting two E53 nodes)
2. Then the p71i class should be available
3. OK.
4. OK.
5. Looks like it's already been fixed!

**Comment by apeters** [comment]
Re 
2. as far as I can tell P71i_is_listed_in is available once you select E32_Authority_Document

**Comment by dwuthrich** [comment]
Re: point #2:

Neither my local instance nor dev.archesproject.org allows selection of P71i.

FYI, our current HIP graphs show the E55/E32 property to be -p71, so I assume that its a valid property.  However, the current HIP graphs are wrong (see the p87 issue noted above).  

After speaking with Adam, we probably want to ignore the E55/E32 relationship anyway (because it represents another level of nesting that doesn't really buy us anything...).

So, if it turns out that p71i is not a valid property for connecting an E55 and E32 node, then we can close this ticket

**Comment by apeters** [comment]
P71i is a valid property to connect E55 and E32 nodes.
I was able to save a graph with that combination.

**Comment by dwuthrich** [comment]
Try using the node/node-type graph to create an E55/p7i/E32 branch  (I can add separate nodes as E55 and E32 and then connect them via the p71i property too).

**Comment by robgaston** [comment]
is this (broadly) resolved? 

if so, we should close out this rather broadly defined ticket and open additional, more specific tickets for the problems mentioned in this thread for better tracking.

**Comment by dwuthrich** [comment]
meets requirements
