### ISSUE TITLE
Graph Manager: Control Panel/Branch Library

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#354]
- [x] Take Branch Library Data from PostgreSQL to Client
- [x] Displaying the data of the branches
- [x] Drag and drop interaction to move nodes and their children in a given graph

**Comment by apeters** [comment]
- Remove 'connects to' section.
- Fix top node value

**Comment by dwuthrich** [comment]
UI allows user to drag branch and "drop" it onto nothing (e.g.: completely disconnected from graph).

**Comment by robgaston** [comment]
@dwuthrich I think the issue you've mentioned is being tracked in the current sprint backlog as #481 

What do you think? Can we move this issue into 'Closed' and track this bug in the other one?

**Comment by dwuthrich** [comment]
@robgaston Yes, we can close this issue and track the drag/drop bug in #481
