### ISSUE TITLE
Move the delete node icon to the far right on the graph manager node

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3545]
![Screen Shot 2018-06-19 at 1.19.52 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/521cf802-864a-4e6f-84de-7a8e3b7a2205)

**Comment by jmunowitch** [comment]
With https://github.com/archesproject/arches/pull/3566:
![image](https://user-images.githubusercontent.com/1542229/41688030-36740052-749f-11e8-9c47-6b70f37c6353.png)

**Comment by apeters** [comment]
meets requirements
