### ISSUE TITLE
Add d3 preview to graph manager

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3546]
When a user hit's the `Preview` button, we should show the d3 circular dendrogram graph.
- Clicking on nodes in the hierarchical graph on the left should focus the d3 graph like it does in the old graph manager. 
- Select state of the nodes should be synced like it currently is in the old graph manager

**Comment by jmunowitch** [comment]
Reviewed and meets requirements as listed. See Below Gif.

Upon testing, I would expect the following: 
- [ ] Selecting a node in the D3 graph that is hidden in the hierarchical graph on the left should expand the Hierarchical Graph to display the once hidden/collapsed node.
- [ ] Selecting a child node further in the graph does not highlight a 1st level child node. For example, see the node titled `Right` in this image:
![image](https://user-images.githubusercontent.com/1542229/42180616-bcb465c0-7dec-11e8-94eb-06720ac4b0db.png)



![d3 preview](https://user-images.githubusercontent.com/1542229/42180426-175d2b7a-7dec-11e8-8f3d-57c9fb613eac.gif)

**Comment by jmunowitch** [comment]
Reviewed and looks good.



![expand hierarchical graph on node selection](https://user-images.githubusercontent.com/1542229/42234473-862e8e82-7ea9-11e8-9907-cb36b8374dd4.gif)
