### ISSUE TITLE
Move the search/filter tree box to above the expand all / collapse all links

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3552]
![Screen Shot 2018-06-19 at 3.30.24 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/ea41ab69-64a6-4cbc-952b-4a375b44b8a9)

**Comment by jmunowitch** [comment]
Graph Designer: 
![image](https://user-images.githubusercontent.com/1542229/41738829-032885f2-7548-11e8-9f9c-d76bd02d42b6.png)
Resource Editor:
![image](https://user-images.githubusercontent.com/1542229/41738858-173215fe-7548-11e8-95d3-706527421111.png)

**Comment by apeters** [comment]
meets requirements
