### ISSUE TITLE
Add the ability to quickly jump to a different graph 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3553]
**This dropdown of graphs in the current version of Arches:**
 ![Screen Shot 2018-06-19 at 3.35.27 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/c58bf464-bbae-4f6f-ab77-11508136bf9f)

**Should go where the search/filter box currently resides in the new graph designer:**
![Screen Shot 2018-06-19 at 3.30.24 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/171b3b30-4d45-4dcb-a0f9-57eebe353e3e)

The filter is going to be moved by this ticket #3552

**Comment by jmunowitch** [comment]
@dwuthrich provided some more guidance here. This is the drop down option we want:
![drop down want](https://user-images.githubusercontent.com/1542229/41749252-3d13bd14-756a-11e8-9d4e-dbbdaa52d01e.gif)

**Comment by jmunowitch** [comment]
Drop down updated:
![drop down](https://user-images.githubusercontent.com/1542229/41751263-439c3084-7575-11e8-8c59-78dc3aaa9182.gif)

**Comment by apeters** [comment]
meets requirements
