### ISSUE TITLE
Remove empty html area in the resource editor  

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3555]
Once the search/filter box ("Find a card") is moved (see #3552) we can remove the blank area below the top bar and above the tree and content areas.

![Screen Shot 2018-06-20 at 9.59.19 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/69090a7d-49ac-42c8-9604-16ba5a254ec3)

**Comment by jmunowitch** [comment]
Blank space removed:
![image](https://user-images.githubusercontent.com/1542229/41748836-61179818-7568-11e8-9678-bfee3a4dd8c1.png)

**Comment by apeters** [comment]
meets requirements
