### ISSUE TITLE
Allow changing of module/function that powers map pop up and results list

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#3556]
While attempting to modify the Primary Descriptors Function to work in a specific way with resource node values, we found that the function and module called by the get_descriptor function in resource.py was hardcoded into core arches.  This means that we could not reference our own, altered version of the module in our project.

![image](https://user-images.githubusercontent.com/38533555/41673084-a2d6d4c2-74b3-11e8-87a2-d2336b8ffa43.png)

Please can this be changed so we can, in effect, overwrite the out-of-the-box core function in favour of a custom function that we can alter without changing the core arches installation?

**Comment by chiatt** [comment]
Resolved in #8256
