### ISSUE TITLE
Extend API endpoint to GET a single concept as json-ld

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3562]
Extends #3399 to work with json-ld.  Testing should be similar, utilizing `?f=json-ld` instead of `?f=json`

**Comment by apeters** [comment]
I think we should be able to use our SKOSWriter to generate rdf-nt and then convert to json-ld (similar to what we did with the JsonLdWriter for resources)

**Comment by jmunowitch** [comment]
Reviewed and looks good.
