### ISSUE TITLE
When creating a new resource, the "add-resource/{graph id}" portion of the url remains even after a save operation

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3569]
This should revert to the url
"resource/{resourceID}"

This becomes a problem, because if someone tries to refresh that url, then the page reloads and it appears that you've lost all your data.

**Comment by jmunowitch** [comment]
Is the expected behavior that the tile data is saved, and the resource editor page is loaded with the UUID?

**Comment by apeters** [comment]
I'd prefer an immediate redirect.

**Comment by apeters** [comment]
meets requirements
