### ISSUE TITLE
Fix Fast Graph Switcher in the Graph Manager

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3572]
**Describe the bug**

The Graph Switcher in the Graph Manager is broken in 4.2.0
**Screenshots**
![graph switcher not working](https://user-images.githubusercontent.com/1542229/41734851-0af01634-753d-11e8-8c77-855a3659bd31.gif)

**Expected behavior**
This drop down should list all the graphs: 
![graph switcher working](https://user-images.githubusercontent.com/1542229/41734975-5a680e7e-753d-11e8-86ff-5f66b2e4d248.gif)

**Your Arches Information**

*   Version used: 4.2.0

**Ticket Background**
*   Found by: @dwuthrich

**Comment by jmunowitch** [comment]
Graph Switcher is now Functional ![graph switcher working](https://user-images.githubusercontent.com/1542229/41734975-5a680e7e-753d-11e8-86ff-5f66b2e4d248.gif)

**Comment by ajwuthrich** [comment]
Works as intended
