### ISSUE TITLE
Direct the resource editor to the current instance after a tile is saved

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3581]
Currently URL of the resource editor remains pointed to `add-resource/[graphid]` after a tile is saved. If a user refreshes the page, they will no longer be looking at the resource instance they were previously editing, but rather a completely new resource.  

Once an initial tile is saved in the resource editor, the URL in the browser should point to the newly created resource instance.

**Comment by apeters** [comment]
duplicate of #3569
