### ISSUE TITLE
Be able to extend Primary Descriptor function from project

### ISSUE THREAD

**Issue by AJ-HistoricEngland** [archesproject/arches#3588]
The Primary Descriptor function is hard coded within the resources.py, which means that it can not be replaced with a different function or extended from within a project.

```
def get_descriptor(self, descriptor):
        module = importlib.import_module('**arches.app.functions.primary_descriptors**')
        PrimaryDescriptorsFunction = getattr(module, 'PrimaryDescriptorsFunction')()
        functionConfig = models.FunctionXGraph.objects.filter(graph_id=self.graph_id, function__functiontype='primarydescriptors')
        if len(functionConfig) == 1:
            return PrimaryDescriptorsFunction.get_primary_descriptor_from_nodes(self, functionConfig[0].config[descriptor])
        else:
            return 'undefined'
```

**Comment by apeters** [comment]
@ryan86 what's the deal with this ticket?

**Comment by AJ-HistoricEngland** [comment]
Sorry for the ticket being poorly described!  This was early in our Arches days and I definitely didn't describe this well!!

We wanted to be able to create our own function to generate the primary descriptor values.

Ideally we could create a function and set it to be the primary descriptor function for the graph.

**Comment by apeters** [comment]
I understand now, no worries!

**Comment by chiatt** [comment]
Closing because this functionality is covered by #3556
