### ISSUE TITLE
Clean up dropdown for managing navigation of graph management commands

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3600]
![Screen Shot 2018-06-27 at 11.29.30 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/ba5b4cc5-aa23-4e46-acbe-5d1db74584b5)

**Comment by chiatt** [comment]
@apeters @robgaston What about the Function and Report managers? Will those pages remain in 4.3?

**Comment by robgaston** [comment]
@chiatt my understanding is that we are going to retain those two UIs (Function Manager & Report Manager) for the 4.3 release; they will be migrated into the new Graph Designer interface in the following release

**Comment by chiatt** [comment]
@robgaston Great - thanks Rob

**Comment by dwuthrich** [comment]
meets requirements
