### ISSUE TITLE
Remove all code that is now deprecated based on the new UI

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3601]
Remove all code related to old UI constructs:
- [x] Menus/forms - this will require a migration, also .json files contain references to forms (should those references be removed as well??)
- [ ] Permissions manger
- [ ] Graph manager
- [ ] Card manager
- [ ] Resource editor
- [ ] Report Manager
- [ ] all in-app help templates that are no longer used anywhere

**Comment by mradamcox** [comment]
Work on this should also take into account urls.py.
