### ISSUE TITLE
Rethink the Arches CLI

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3603]
While the majority of the Arches application has been revamped with a wholistic thought process, I believe the CLI has been left behind.

A wholistic view about how to manage an Arches deployment via the CLI could be helpful in making management easier.

Here are a few areas that the CLI could be improved:

### Implement a more user friendly experience with a unified style:
For example: 
- Asking questions could utilize a more well known CLI pattern: https://github.com/ActiveState/code/blob/master/recipes/Python/577058_query_yesno/recipe-577058.py
 - Tasks that take a while could have a progress bar, so the user would know how far they are in the process (import/export): https://github.com/rasbt/pyprind, or https://tqdm.github.io

### Rethink the organize the commands.
This could be rethinking the grouping of commands by function, and moving more things out of packages.

**Comment by jmunowitch** [comment]
A brief thought on how some existing commands could be re-grouped:

#### install
*   'setup'
*   'install'
*   'setup_db'
*   'setup_indexes'
*   'start_elasticsearch'
*   'setup_elasticsearch'
*   'update_project_templates'
*   'build_permissions'

#### import
*   'load_concept_scheme'
*   'import_reference_data'
*   'import_graphs'
*   'import_business_data'
*   'import_business_data_relations'
*   'import_mapping_file'
*   'import_node_value_data'

#### export
*   'export_business_data'
*   'export_graphs'
*   'create_mapping_file'

#### packages (new file)
*   'load_package'
*   'create_package'
*   'update_package'
*   'export_package_configs'

#### maps
*   'add_tileserver_layer'
*   'delete_tileserver_layer'
*   'add_mapbox_layer'
*   'seed_resource_tile_cache'

#### settings
*   'save_system_settings'

Removing duplicative or unused commands could also make the CLI a bit easier to understand and use.

**Comment by mradamcox** [comment]
First, I think there are a couple general tenets to keep in mind when constructing commands:

1. as few characters as possible
    e.g. instead of `-db true` just `-db` because there is no other value option for `-db`. In fact, single hyphens should be single letters arguments, as well, which will be much easier when the commands are split between more files.
2. as much granularity as possible
    e.g. allow loading of individual package components; allow re-indexing specific ES indices, etc.
3. more explanatory failure/successes
    there are a number of commands that fail or succeed without much of an explanation why, and sometimes it's only possible to judge the results by resorting to the UI.
4. asking for confirmation is good sometimes, but all commands should support a "no input" mode.

---

As for the actual structure of the commands, I'm inclined (though not tied to) a slightly more "component-driven" paradigm than what @jmunowitch proposes, which is a little more process driven. For example I think all elasticsearch commands should remaind in the `es` command that @apeters has already moved us toward.

Along those lines (and this is not exhaustive, I'm sure there are existing commands I'm overlooking) I would propose something like this:

**es**
+ I haven't looked at this command recently, but overall I really like the way it's been reworked in v4.

**map**
+ basically as described above, and I currently have a PR out to add `delete_mapbox_layer`
+ I think these commands could be simplified as well, but perhaps that's for a different ticket

**package**
+ `manage.py package load -s <path to package> [other configs as necessary]`
+ `manage.py package create -d <path to package> [other configs as necessary]`
+ `manage.py package update [other configs as necessary]`
+ `manage.py package export_configs -d <path to export dest> [other configs as necessary]`
+ I think it would be wise to leave `packages.py` as it is and where appropriate rewrite those commands to route to all of these new locations.

As for some of the commands listed in the **install** section of the above comment, 'setup', 'install', 'setup_db', I'm not sure what the nuances are of each one, but perhaps they could be split into a separate set of commands. As far as I can tell, all we need is one `setup_db`-type command (which could install the db, call the es indexing functions, fail right off the bat if ES is not running, etc...).

---

When it comes down to resource and schema management, I see two ways to go. Either

**Idea 1**

`python manage.py import resources [config options]`
`python manage.py import concepts [config options]`
`python manage.py import graphs [config options]`

...and substitute `export` for the corresponding actions

**or Idea 2** 

+ `python manage.py resource import -s <path to file> [other configs as necessary]`
+ `python manage.py resource export -d <path to outfile> [other configs as necessary]`
+ `python manage.py resource delete [other configs as necessary]`
+ perhaps it would be feasible to have the es index function here as well, like `python manage.py resources index`, and perhaps that command itself could just call something like `python manage.py es index_database --resources`

and

+ `manage.py concepts import -s <path to file> [other configs as necessary]`
+ `manage.py concepts export -d <path to outfile> [other configs as necessary]`
+ indexing, as mentioned above

etc. I haven't weighed enough pros and cons to have a real solid opinion about this, as the actual file/method structure could dictate which option makes the most sense. My gut leans toward Idea 2...

**Comment by mradamcox** [comment]
I'll point out that one of the really good things about having so much in packages.py, is that we can slowly migrate those functions out into new files, and at the same time reference them in packages.py so we won't break backward cli compatibility.
