### ISSUE TITLE
Add splash page for related resources to display when no related resources have been added

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3605]
![Screen Shot 2018-06-27 at 3.48.44 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/509ec260-f308-4383-99a9-4e90f877b010)

**Comment by jmunowitch** [comment]
Current Status:
![image](https://user-images.githubusercontent.com/1542229/42399709-bfc1679c-8123-11e8-82a4-7aac828178c2.png)

**Comment by jmunowitch** [comment]
@apeters What is expected of the Show Me How link at the bottom of the splash? Is it a link to http://arches.readthedocs.io/en/stable/ or is it a link to the in app help?

**Comment by jmunowitch** [comment]
@dwuthrich What is expected of the Show Me How link at the bottom of the splash? Is it a link to http://arches.readthedocs.io/en/stable/ or is it a link to the in app help?

**Comment by chiatt** [comment]
Possibly related to updating the in app help in the new designer #3712

**Comment by jmunowitch** [comment]
@chiatt : I think that is right. The `Show Me How` Link should pull up the in app help which will have a gif demonstrating the basic workflow.

**Comment by chiatt** [comment]
@jmunowitch In that case it's really blocked by #3712.

**Comment by chiatt** [comment]
@jmunowitch This is now unblocked. If you click on the link it will open the help panel. The content however needs to be changed.

**Comment by apeters** [comment]
meets requirements
