### ISSUE TITLE
Implement a search for related resources

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3607]
The desired search functionality for related resources is somewhat different from our current search.
The dropdown shows resource instance results as if it were from a term search aggregated with concepts from a term search.  If the user selects a concept then show the results filtering by that concept.

As the user types, display concepts that match, as well as resource instances, as if the user had done a term search for **publi** in this example:
![Screen Shot 2018-06-27 at 4.10.09 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/7b71c44f-28bc-43e1-953e-39801a4ae58d)

If a user selects a concept then show a list of resource that contain that concept.
![Screen Shot 2018-06-27 at 4.10.20 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/a7a486cf-4369-419b-9bbc-cbd95c8d336f)

**Comment by robgaston** [comment]
An important thing to note here: the functionality is very similar to our existing widget for the resource instance data type.
We should reuse that widget here and enhance is according to the mock-up so that the enhancements are available everywhere we use that widget.
