### ISSUE TITLE
Possiible Duplicate Key on Form Entry

### ISSUE THREAD

**Issue by BAPAlveyCHIC** [archesproject/arches#361]
Two users entered an actor record at the same time: when we searched for the record of one user, the other user's record appeared in the search list; when we deleted one record, both records were deleted.

This happened only once.

The associated image may or m
![archesbugforbryan](https://cloud.githubusercontent.com/assets/16782478/13983024/14467b80-f0e5-11e5-99f9-19155186bc42.jpg)
ay not help.

**Comment by chiatt** [comment]
Closing because there is no active development on v3
