### ISSUE TITLE
Graph Designer: Resizable Side Panel does not resize in Firefox

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3620]
**Describe the bug**

Resizable Side Panel does not resize in Firefox

**Screenshots**

![newticketfirefox](https://user-images.githubusercontent.com/1542229/42117141-de066cda-7baf-11e8-9540-7922d2576622.gif)

**Your Arches Information**

*   Browser Name and version: Firefox 61

**Ticket Background**
*   Found by: @ryan86

**Comment by chiatt** [comment]
Works great. Thanks @veuncent!
