### ISSUE TITLE
Provisional Edits: Improve UI

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3629]
Some items to address in the provisional UI:

re-style warnings, move provisional panel to right side of card, simplify display of provisional editor

**Comment by mradamcox** [comment]
One thing I noticed also: when you are a reviewer and you open the panel to review an edit, I couldn't figure out how to close the panel without making an Accept/Decline decision. Just an `x` in the corner would be good to allow a reviewer to close the panel without making a decision.

**Comment by chiatt** [comment]
@dwuthrich This looks great. @mradamcox I'm going to make a dedicated ticket for your suggestion.
