### ISSUE TITLE
Enhancement request: ability to show compulsory fields v optional fields

### ISSUE THREAD

**Issue by BAPAlveyCHIC** [archesproject/arches#363]
Again, users have found it annoying to save a record only to be told that a field needs to be filled in. 

In other applications, compulsory fields can be recognised by a red asterisk; would this be possible in a later version?

**Comment by apeters** [comment]
@dwuthrich, Is this something we should have represented in our mockups for v4?

**Comment by dwuthrich** [comment]
meets requirements
