### ISSUE TITLE
CACHE_SEED_BOUNDS Settings format should allow for geojson or a tuple

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3631]
Currently the CACHE_SEED_BOUNDS setting is a tuple by default, but geojson is required in order run the seed_resource_cache command.  We should modify the command to allow for either geojson or a tuple.

**Comment by mradamcox** [comment]
It may be nice to make sure that the format is such that would allow this setting to inherit from the project bounding box setting, if desired (though I'm not sure how the inheritance chain would work). In other words, it would be nice if bounding box-esque settings like this one all used the same format...

**Comment by chiatt** [comment]
CACHE_SEED_BOUNDS setting no longer in Arches
