### ISSUE TITLE
Enhancement request: ability to enter coords directly into the application

### ISSUE THREAD

**Issue by BAPAlveyCHIC** [archesproject/arches#364]
Bhutan uses Druk Refs: in order to get a grid reference into the system, the user must first transform the coordinates before adding to to KML or similar before dragging and dropping.  

It would be great if the user could enter these directly into fields on the form.

**Comment by apeters** [comment]
I think we're planning on allowing this in v4.  Can you confirm this @dwuthrich?

**Comment by mradamcox** [comment]
For the Egyptian Archeaological Database, we have implemented this in the app, here's the commit https://github.com/legiongis/ead/commit/a86540958075ec82812714484e58bd0e9c9ba3de

**Comment by chiatt** [comment]
Closing because there is no active development on v3
