### ISSUE TITLE
Configurable default json-ld context

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3645]
**Is your feature request related to a problem? Please describe.**

As a data modeler / api designer, I want to use a single json-ld context for all of my branches and models. 

**Describe the solution you'd like**

In order to save typing, being able to configure a default context (in settings_local.py?) would be a great time saver and ensure consistency / prevent typos.

**Describe alternatives you've considered**

A drop-down list of pre-configured contexts might also work, but would prevent pasting in arbitrary JSON.  The arbitrary definition is potentially useful, especially for testing.

**Comment by apeters** [comment]
A graph can now have a json-ld context associated with it
