### ISSUE TITLE
Document yarn install

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3646]
**Is your feature request related to a problem? Please describe.**

After pulling the latest master from github, a yarn dependency had changed resulting in some media assets not being available. 

**Describe the solution you'd like**

Document that `migrate` and `yarn install` are likely needed after pulling the latest code base from GH, if you're not setting up a new project. This should probably be in https://arches.readthedocs.io/en/latest/creating-a-development-environment/ 

**Describe alternatives you've considered**

These could be automagically run, but it would still need documentation and slow down development when it wasn't needed.

**Additional context**

Discussed on slack in #development, 2018-07-05T10:00:00. with @chiatt and @mradamcox

**Comment by mradamcox** [comment]
@azaroth42 I've made a PR for this ticket (you can see the link in this thread). Could you check it out and let me know if it looks good to you?

**Comment by azaroth42** [comment]
LGTM! :)
