### ISSUE TITLE
Populate middle "Functions" panel with resource level functions

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3651]
The drop-down should contain a list of only unapplied functions.
Below the dropdown show a tiles of applied functions.

![Screen Shot 2018-07-05 at 11.03.37 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/507c63fd-0be8-4713-8f6b-d591aff9dcca)

**Comment by chiatt** [comment]
This UI is deprecated following the implementation of the graph designer
