### ISSUE TITLE
Graph save button location?

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3655]
**Is your feature request related to a problem? Please describe.**

After filling out a graph form, it's extra effort scroll back to the top of the page to click on Save Edits in the top right hand corner.

**Describe the solution you'd like**

Move or duplicate the save/discard buttons to the top left, as 99% of the time you'll be either adding a new node in the tree, or going back to the designer, both of which are top left.

**Describe alternatives you've considered**

Could be at the bottom of the form, but for long forms that might mean scrolling down. Consistency in location is probably better.

**Comment by chiatt** [comment]
The save button is now always visible in the upper right.
