### ISSUE TITLE
Graph Designer: Add Done Button to return to Default Graph Designer page.

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3663]
Add Done Button in the new Graph Designer to match the Existing Graph Manager:

Previous Graph Manager:
![image](https://user-images.githubusercontent.com/1542229/42343865-4e76c228-804f-11e8-8e89-b24fb66f183f.png)

Current Graph Designer:
![image](https://user-images.githubusercontent.com/1542229/42343884-5dcab43c-804f-11e8-8a1c-1c3803df77cd.png)

**Ticket Background**
*   Sponsored by: Getty Conservation Institute 

See: https://github.com/archesproject/arches/pull/2677#issuecomment-402941021

**Comment by apeters** [comment]
meets requirements

**Comment by apeters** [comment]
meets requirements
