### ISSUE TITLE
Adding ' into a map layer name creates an error

### ISSUE THREAD

**Issue by mike-campbell-k-int** [archesproject/arches#3687]
**Describe the bug**
When editing an overlay on the map layer manager, including a ' character in the overlay name causes the page to recognize the symbol as the end of the name, which then causes an error by having the rest of the ' symbols to be out of sync and puts the close brace of the map layer inside a string.

**To Reproduce**
1. Go to 'Map Layer Manager' screen
2. Click on 'Overlays'
3. Edit an overlay name to contain the ' symbol
4. The page will then fail to load when refreshed

**Expected behavior**
The ' character should either be handled as a special character or disallowed when trying to edit the name of a map layer.

**Your Arches Information**
*   Version used: 7.1
*   Operating System and version (desktop or mobile): Windows 10
*   Browser Name and version: Firefox, IE

**Additional Context**
This can also cause the issue to occur on the search page when the overlay containing ' is included there.

**Ticket Background**
*   Found by: @mike-campbell-k-int

**Comment by chiatt** [comment]
Arches no longer supports IE
