### ISSUE TITLE
Add Ontology to Packages

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3693]
As a package creator and maintainer, I may need to use a custom ontology file (this is the case for the package that will hold ARM branches) to support the graphs I am managing in my package.  It would be nice to be able to save the custom ontology right alongside my graphs in the package.

**Comment by adamlodge** [comment]
This ticket is related to #3703.  I think the two should be solved simultaneously.

**Comment by chiatt** [comment]
This implementation has now been in use for 8 months and appears to be working reliably.
