### ISSUE TITLE
Remove default loading of ontology when creating a project

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3703]
As an Arches implementor, it makes more sense to load ontology as part of loading a package rather than loading CRM by default on creating a project.   This is because graphs within a project may or may not relate to CRM as defined in the default project loading script.  It would be more ideal to load ontology as part and parcel of loading graphs that use the ontology.

**Comment by azaroth42** [comment]
I agree with the concept, but in practice there needs to be a lot more work around ontology management first.  Not every instance will come from a package, and not having an ontology with the current ontology management CLI-only pattern would likely just mean people built models without one.

**Comment by adamlodge** [comment]
closing in favor of #3713
