### ISSUE TITLE
Remove PyCrypto

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3704]
Since GitHub is now checking our requirements.txt for vulnerabilities, it found that `pycrypto` has a Known Security Vulnerability. `Pycrypto` hasn't been updated in almost 5 years, and it is not showing up as a dependency in any other one of our pip packages. `pycryptodome` serves as a drop in replacement for most projects, and it looks like it could for Arches as well. We have it installed as a dependency already.

I tested this by `pip uninstall pycrypto` and received an error: `ImportError: No module named Crypto.Cipher`. 

I ran `pip install pycryptodome --force-reinstall` and the error is gone. We may be able to remove `pycrypto` as a dependency.

**Comment by jmunowitch** [comment]
This looks to be used here: https://github.com/archesproject/arches/blob/master/arches/app/utils/arches_crypto.py
Which is used here: https://github.com/archesproject/arches/blob/master/arches/app/views/auth.py#L155

I have removed `pycrypto` with the instructions above, and tested this process by creating a new User through the UI. I encountered no errors.

**Comment by jmunowitch** [comment]
It looks like some older versions of pip do not have the `--force-reinstall` command. If that is the case, try:
`pip uninstall pycryptodome`
`pip install pycryptodome`

**Comment by apeters** [comment]
I think you need to add pycryptodome into requirements.txt

**Comment by jmunowitch** [comment]
This should be installed by default thanks to it being a requirement of `python-jose`. Since we require it in our own code, I added it to requirements.txt:
https://github.com/archesproject/arches/commit/5203620163ce4a5e178fefd99e5a2160ec1c3ba1

**Comment by apeters** [comment]
@jmunowitch 
see here: https://github.com/mpdavis/python-jose#custom-backends
pycryptodome doesn't come by default

we can add this to requirements.txt instead
python-jose[pycryptodome]>=3.0.0,<4.0.0

**Comment by jmunowitch** [comment]
@apeters: I agree that since we are specifically calling pycryptodome from our own code, we should include it in our requirements.txt file. Before today, it looks like Travis-CI installed pycryptodome as a requirement from python-jose: 
https://travis-ci.org/archesproject/arches/builds/418825806#L3368

Also a note that the custom backend section you are referring to applies to >3.0.0, but we are pinned to python-jose 2.0.2: https://github.com/archesproject/arches/blob/master/arches/install/requirements.txt#L14

We have PR from @dependabot-bot to upgrade python-jose:
https://github.com/archesproject/arches/pull/3462.
The main gist of the release notes relates to the crypto package:
> As of 3.0.0, python-jose uses the pure python rsa package for signing and verifying RSA signatures by default.
> 
> Other backends can be used by installing python-jose with extras. Options include pycrypto, pycryptodome and cryptography. It is recommended that one of these options is used in production, as they will be much faster than the pure python rsa module.
> 
> The cryptography option is a good default.
While we should look at upgrading python-jose, I don't think this is going to make it into the 4.3 release.

**Comment by apeters** [comment]
meets requirements
