### ISSUE TITLE
Import graph throws an error

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3710]
To test this I created a simple resource graph with 3 nodes, saved the graph, exported the graph, the tried to re-import it.  The file I used is below.

https://github.com/archesproject/arches/blob/stable/4.3.x/releases/pre-4.3.0.md#graphresource-designer

[https://app.zenhub.com/files/49451058/f3f79609-ea49-41a6-bce1-6155c049cb08/download](https://app.zenhub.com/files/49451058/f3f79609-ea49-41a6-bce1-6155c049cb08/download)

**Comment by ryan86** [comment]
@apeters this is happening because the resource graph importer assumes that all imported graphs have cards. Is this still a valid assumption given that you can create a graph without cards?

**Comment by apeters** [comment]
I suppose that this isn't always the case

**Comment by apeters** [comment]
meets requirements
