### ISSUE TITLE
Tags show up in rich text widget

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3711]
https://github.com/archesproject/arches/blob/stable/4.3.x/releases/pre-4.3.0.md#data-types

**Comment by chiatt** [comment]
@apeters I'm not seeing this issue in master. Could there be a special character or something else data related causing the editor to parse it incorrectly?

**Comment by apeters** [comment]
@chiatt I think i might have fixed this as part of the work I did on reports.  I'll close for now
