### ISSUE TITLE
Don't load an ontology by default when creating a project in Arches

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3713]

**Comment by azaroth42** [comment]
Duplicate of #3703?

**Comment by chiatt** [comment]
This could also be a flag to not load ontologies

**Comment by chiatt** [comment]
The default ontology is loaded in the first migration: https://github.com/archesproject/arches/blob/d3bee6050e74f4616317a95dfb9009cef2587d95/arches/app/models/migrations/0001_initial.py#L25
It looks like the task would be to remove it rather than prevent it from being loaded.

**Comment by chiatt** [comment]
Meets requirements
