### ISSUE TITLE
Index descriptors based on provisional edit values if no authoritative tile for the descriptor exists

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3714]
Currently if a provisional user creates a tile used to define a descriptor, the descriptor will not be indexed until a reviewer approves the edit. This means that in the edit log, there is no name saved with resource instances that do not have authoritative descriptor cards. The drawback is that in the provisional edit history, users will have difficulty understanding their edits because some edits have no resource name associated with them.

**Comment by apeters** [comment]
This works:
I create a provisional edit and I can see my edit in the 'edit history' left nav and in "My Edit History", but not in search (as expected).

What doesn't work:
I can't see the edit in the 'Review Edit History' menu item.

**Comment by chiatt** [comment]
Created new ticket, #5900, to address @apeters Oct 23, 2019 comment.
