### ISSUE TITLE
Populate middle "Reports" tab panel with report configuration form

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3724]
Create a form to manage the selection of report template, report configuration, and section settings.

![Screen Shot 2018-07-20 at 10.48.52 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/abf3a9d9-2a67-4de4-848b-c373ab7c9024)

**Comment by robgaston** [comment]
@apeters I've not seen the error that you mentioned, not can I recreate it currently.

**Comment by robgaston** [comment]
@apeters @dwuthrich looks like this issue was caused by #3952 

I've got a fix I'll push now

**Comment by apeters** [comment]
meets requirements
