### ISSUE TITLE
Update UI of provisional UI panel

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3729]
Reposition UI elements (change order of provisional edit metadata), and small style updates

**Comment by mradamcox** [comment]
duplicate of https://github.com/archesproject/arches/issues/3629?

**Comment by dwuthrich** [comment]
@mradamcox Yes, this could be seen as a duplicate of 3629.  In fact, the ticket was meant to further update some of the chances implemented in 3629

**Comment by dwuthrich** [comment]
meets requirements
