### ISSUE TITLE
Deploy QA Machine

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#373]
We want to have a QA and Production machine up and running on AWS. 

To do this, we need the appspec.yml file created:
http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html

**Comment by ryan86** [comment]
The dev machine will be cloning the stable/4.x branch of the repo. This branch does not exist yet.

**Comment by apeters** [comment]
@ryan86 what's the status of this?

**Comment by ryan86** [comment]
http://qa.archesproject.org

For now I'm managing it manually. An open question would be how we want to manage it in the future.

**Comment by apeters** [comment]
I think for now, manually managing it is fine.
