### ISSUE TITLE
Match the Style of the Card Component Configuration and Widget Manager

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3736]
Currently, the middle panels implemented by #3570 and #3559 are not consistent in their styles:

Card Configuration | Widget Manager
------------ | -------------
![image](https://user-images.githubusercontent.com/1542229/43104058-f0c9a21e-8e84-11e8-812a-687cc60be989.png) | ![image](https://user-images.githubusercontent.com/1542229/43104064-f59c33ec-8e84-11e8-889d-31443a6306dc.png)

**Definition of Done**
Consistent Style between the Card Configuration and Widget Configuration Middle Panels.

**Comment by jmunowitch** [comment]
Reviewed and looks good.

Card Configuration | Widget Manager
------------ | -------------
<img width="301" alt="image" src="https://user-images.githubusercontent.com/1542229/43290832-35f5ed8c-90e4-11e8-9d7c-44ee55fe1e2a.png"> | <img width="301" alt="image" src="https://user-images.githubusercontent.com/1542229/43290862-4cd5750e-90e4-11e8-8404-9edc47332793.png">

@dwuthrich Out of scope of this ticket, but should the `Default Value` field match the rest of the drop downs in the Middle Panel?

**Comment by dwuthrich** [comment]
@jmunowitch Yes, it should be.  I'll add a fix for it

**Comment by dwuthrich** [comment]
meets requirements
