### ISSUE TITLE
Ontologies: Ontology extensions appear to load correctly when it should give an error

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3745]
#### Current Behavior
When loading additional ontologies into a personal version of arches from the command line, if the pathway is incorrect the command lines shows the ontology loading anyway, without letting the user know at any point that it has failed. 

![Screen Shot 2018-07-24 at 11.31.08 AM.png](https://images.zenhubusercontent.com/5ae784c04b5806bc2bd13b56/b7d6da09-62f1-47fe-97cd-76010b3c2bf5)

When the user checks the graph manager for the additional ontology classes and relationships, neither are present within the app. 

#### Expected Behavior
When loading additional ontologies into arches from the command line, the extension will load in from a correct pathway to a valid .xml file. If the pathway is incorrect, then the command line will let the user know that not only the ontology extension has failed to load, but the reason why it did so.

**Comment by jmunowitch** [comment]
Currently, a way to confirm it actually loaded would be to run a `python manage.py load_ontology -r` and see if the file is in the list of extensions loaded a second time

**Comment by chiatt** [comment]
Works as expected
