### ISSUE TITLE
Arches v4 marker click on map doesn't work on phones

### ISSUE THREAD

**Issue by afeliuNexus-zz** [archesproject/arches#3760]
On Map search the click on feature of resource layer doesn't work nor show any pop up with the information of the feature

https://user-images.githubusercontent.com/35261672/43307295-176581e4-917e-11e8-9602-21f2ac9866be.PNG

1. Go to Search
2. Open the map view
3. Click on any feature
4. The pop up doesn't apppear nor do anything

We expect to see the pop up after clicking on a feature from resource layer

**Your Arches Information**
This happens on arches demo v4.1 with google chrome and mozilla firefox.

**Comment by chiatt** [comment]
Hi @afeliu can you confirm that you are still seeing this issue?
