### ISSUE TITLE
Cannot edit data in a tile that has been added to a card without data.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3763]
In the resource editor if a user selects a card, enters data in the card's tile and clicks add, the tile can later be edited. However, if a user selects a card, adds the tile, and then tries to edit the tile, the dirty state will not be activated preventing the user from saving any edits.

**Comment by adamlodge** [comment]
Meets requirement and closing.

There is still some weird UX around when the page goes to dirty state.  Wasnt able to produce consistent results but sometimes it went immediately to dirty state after a (successful) save.
