### ISSUE TITLE
Error prevents resource editor from loading if user has no write permissions to any card in model

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3769]
In the resource editor, if a user does not have permissions to write to any card in a resource model, a browser error, "Top Card is undefined", prevents the page from loading.

**Comment by adamlodge** [comment]
@chiatt 
I am unclear how to test this properly.  It seems to me that if a user no write privileges on a given resource model, then the opportunity to access the resource editor for that model should never present itself.  This is the behavior I am seeing when I tried to test.

**Comment by jmunowitch** [comment]
This issue is no longer valid due to the user not being able to load the page if they do not have permissions to edit any data.
