### ISSUE TITLE
Graph Manager - Need to be able to add a node or branch to a model that has instances associated with it

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3777]
This is currently possible in 4.2 and should be possible in the latest.

**Comment by dwuthrich** [comment]
This issue persists.  See attached screen capture: http://recordit.co/w3i02khAlS

Note that the error message when attempting to add a node to a branch with existing instances (e.g.: attempting to add child node to name) is wrong.  It should be possible to add a node to a graph with instances.  

Note sure what the second error message is trying to say when adding a child to the root node (this should definitely be possibe)

**Comment by jmunowitch** [comment]
I am having trouble reproducing this. 

I was able to add nodes onto a model I built that has instances, as well as a model from the DISCO package.

Is the model you are using from the [Lincoln Release](https://github.com/archesproject/lincoln_release) or [Lincoln data](https://github.com/archesproject/Lincoln_data) package?

**Comment by dwuthrich** [comment]
@jmunowitch Using the Lincoln Release package, I get the following error when trying to add a branch to the root node of the monuments modeul:

<img width="1676" alt="add branch error" src="https://user-images.githubusercontent.com/815185/44612485-bd37ac00-a7bd-11e8-8f4c-5412d477e9e0.png">

**Comment by jmunowitch** [comment]
Reviewed and looks good.
