### ISSUE TITLE
Graph Manager - Show class and datatype info in the content header

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3778]
In the grey content header where is says "Identifiers", it should say "Identifiers (E15_Identifier_Assignment - semantic)"

![Screen Shot 2018-07-31 at 11.20.02 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/e0e770f4-c6fa-472b-94f6-8f63591a0b65)

**Comment by apeters** [comment]
Remove static content for the root node

**Comment by jmunowitch** [comment]
![3778](https://user-images.githubusercontent.com/1542229/43666638-8463d0b0-9729-11e8-8917-2ada8dadc84f.gif)

**Comment by apeters** [comment]
meets requirements
