### ISSUE TITLE
Graph Manager - Add “Cardinality” switch for nodes

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3780]
Add “Cardinality” switch in the node form, this should only be available on the node that defines the nodegroup (card).

**Comment by azaroth42** [comment]
Is this issue that we can't set "Allow multiple values" on leaf nodes within branches in the card view of the graph manager?

(If not, I will create a new issue for that!)

**Comment by jmunowitch** [comment]
This ticket spawned a few questions on what we would want to implement: 
Cardinality is not defined on the js node model. Do we want to add it to the js node model, and adjust the backend to handle this new data on the model?
Instead, do we want to create a js nodegroup model to handle this type of info?

**Comment by apeters** [comment]
I think we decided that we're not going to do this for now

**Comment by mradamcox** [comment]
out of curiosity how is this different from setting the card to allow multiple values? As I was working through the documentation, it made sense that node-level cardinality was based on the datatype (concept vs. concept-list) and card-level (which is essentially nodegroup-level, correct?) cardinality is defined in the Cards tab.

**Comment by adamlodge** [comment]
It's the same "allow multiple values". Only difference was that you'd be able to it in the graph designer.

**Comment by mradamcox** [comment]
Oh, I see. The removal of that redundancy was something I personally felt was an improvement.
