### ISSUE TITLE
Graph Manger - Add parenthetical to the graph name in header to show whether we’re working on a “branch” or “model”

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3784]
![Screen Shot 2018-07-31 at 11.50.17 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/50f3b559-f466-411f-81b8-317a61664129)

**Comment by jmunowitch** [comment]
Implemented with #3804.

**Comment by jmunowitch** [comment]
<img width="422" alt="screen shot 2018-08-10 at 12 19 08" src="https://user-images.githubusercontent.com/1542229/43977016-9bfcc5ec-9c97-11e8-9280-687fe33059a3.png">
<img width="269" alt="screen shot 2018-08-10 at 12 18 55" src="https://user-images.githubusercontent.com/1542229/43977017-9c13cd0a-9c97-11e8-8d49-d16d5e9f5581.png">

**Comment by apeters** [comment]
meets requirements
