### ISSUE TITLE
Card Manager - show “hover” and “select” state of widgets in the form (currently we only do this in the tree)

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3785]
When you hover and select a widget in the card tree the node in the tree reflects this action and it should also be reflected in the preview form (like it currently is in 4.2)

**Comment by chiatt** [comment]
@jmunowitch I think the select state breaks the tools panel in the map widget (at this commit `ef37ca7`)

**Comment by chiatt** [comment]
@jmunowitch @apeters I'm going to pick up this ticket and take a look at the map widget css issue.

**Comment by apeters** [comment]
meets requirements
