### ISSUE TITLE
Card Manager - Dirty state is triggered when no edits have occurred

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3787]
This is partially due to concept widget getting data dynamically.  Ask Alexei, as he did some work on this and might be able to shed some light on it.

**Comment by azaroth42** [comment]
I encounter this very frequently.

**Comment by adamlodge** [comment]
Meets reqt

**Comment by chiatt** [comment]
This issue seems to have recurred in the latest. Reopening.

**Comment by chiatt** [comment]
@adamlodge Hey Adam, there was a regression that I had to fix for this bug. Could you QA this again?

**Comment by jmunowitch** [comment]
Reviewed and looks good.
