### ISSUE TITLE
Card Manager - "CSS Classes" setting should be implemented in the card configuration form

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3788]
![Screen Shot 2018-07-31 at 12.20.34 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/0d80f583-853f-43ff-9355-22aa802cc7e5)

**Comment by apeters** [comment]
ask @robgaston about how to achieve this

**Comment by jmunowitch** [comment]
The idea behind this ticket is the ability to add a CSS class to the Card Element in the DOM. A separate .css file would be used to apply styles to based upon these added CSS classes.

**Comment by jmunowitch** [comment]
![card css class add](https://user-images.githubusercontent.com/1542229/44234175-d061d080-a15a-11e8-8bf7-53f371791f8e.gif)

**Comment by apeters** [comment]
meets requirements
