### ISSUE TITLE
Changes in the map system settings are not reflected in the card manager

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3796]
If a user changes the min or max zoom in the system settings, those changes should be the default values for the map in the card configuration manager.  Currently, changes to map properties in the system settings is not reflected in the card manager.

**Comment by chiatt** [comment]
Looks like this was fixed in PR #3849

**Comment by chiatt** [comment]
@adamlodge I just checked and it still seems to be working okay. Be sure that you are working with a card that has never had it's settings saved. The system settings are only used as defaults for new map widgets and shouldn't override any settings that have already be saved to the widget.

**Comment by jmunowitch** [comment]
Reviewed and looks good.
