### ISSUE TITLE
Map card properties do not immediately update when a user modifies the map

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3797]
In old card manager if a user panned, zoomed, rotated or tilted the map, the map widget properties would automatically update in sync with the map. Likewise if they changed the numeric property values the map would respond. In the new designer the properties only update when a user has the card selected in the card tree.  When the card is selected rather than the tile, users cannot see the widget properties change when the modify the map.

http://recordit.co/atKCZfne3O

Simultaneous changes in the map state and widget properties should be visible to the user when they have the map widget selected.

**Comment by chiatt** [comment]
Possibly related to #3781

**Comment by adamlodge** [comment]
meets reqt
