### ISSUE TITLE
Resource Editor - Dropdown in resource editor bread crumb is empty

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3800]
To recreate load import the graph below.  Select the card as in the image below and see that the breadcrumb dropdown is empty.

[https://app.zenhub.com/files/49451058/8dff635f-a6a9-4fb2-b4e5-abfa2576c713/download](https://app.zenhub.com/files/49451058/8dff635f-a6a9-4fb2-b4e5-abfa2576c713/download)

![Screen Shot 2018-07-31 at 4.58.16 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/37ac2f4d-13f1-41d2-924d-955dcff6fbe2)

**Comment by ryan86** [comment]
@apeters this appears to work if you click one card down in the tree, so instead of selecting 'Address' (as in the picture above) you select 'Place-HER3'. Do we want the breadcrumbs to display when a user clicks on the 'Address' card?

**Comment by apeters** [comment]
@ryan86 I understand, but I'm pretty sure that showing a blank dropdown is not what we want.  If the dropdown is going to be blank, then maybe we shouldn't show it at all.
