### ISSUE TITLE
Resource Descriptor not functioning properly

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3801]
To recreate load import the graph below.  Notice how the resource descriptor function for the display name for the resource is not rendering the Place Address and Address Type properly in the header.

[https://app.zenhub.com/files/49451058/8dff635f-a6a9-4fb2-b4e5-abfa2576c713/download](https://app.zenhub.com/files/49451058/8dff635f-a6a9-4fb2-b4e5-abfa2576c713/download)

![Screen Shot 2018-07-31 at 4.58.16 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/37ac2f4d-13f1-41d2-924d-955dcff6fbe2)

**Comment by ryan86** [comment]
![screen shot 2018-08-09 at 2 30 37 pm](https://user-images.githubusercontent.com/3038476/43927116-4671aef0-9be1-11e8-9ffe-34b0cdf48fb1.png)

Closing for now because I cannot recreate on the latest.
