### ISSUE TITLE
Create command to load custom cards

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3808]
In order for developers to load their own custom cards or include them in a package, a management command (e.g. datatype.py, fn.py, and reports.py)  to load, drop, and update card components should be added to Arches.

**Comment by chiatt** [comment]
@apeters Maybe this should go in the current sprint? It wouldn't take long, and would be necessary for developers to take full advantage of the benefits of card components.

**Comment by ryan86** [comment]
To QA:

python manage.py card_component register --source `path_to_card_component_config_json`

python manage.py card_component unregister -n `name_of_card_component`

python manage.py card_component list


Example card_component config json:

{
    "componentid": "g05e4d3a-53c1-11e8-b0ea-784f435179ea",
    "name": "This new card",
    "description": "New test card component",
    "component": "views/components/cards/this-new-card",
    "componentname": "this-new-card",
    "defaultconfig": {}
}

**Should not be able to unregister the default card component.
