### ISSUE TITLE
disallowed from adding a node to ontology-enabled graph

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3811]
**Describe the bug**
When adding a node to an ontology-enabled graph, I get an error telling me that I need to define the ontology property of the new node even when the "relationship to parent" is already defined.  I see two problems here:

1. I can make the node I need
2. There is a disconnect between the language in the error message and the language in the UI.  UI only speaks of relationship to parent, where error message speaks of ontology property.  Both are accurate and valid, but a more naive user might not know that they are one and the same.

**To Reproduce**
Build the graph as described in the screenshot below

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used: 4.3 stable testing
*   Operating System and version (desktop or mobile): osx
*   Browser Name and version: chrome
<img width="1452" alt="screen shot 2018-08-01 at 12 00 27 pm" src="https://user-images.githubusercontent.com/9683819/43543836-0d49d258-9586-11e8-9523-35c2936a8ab2.png">

*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by azaroth42** [comment]
+1 to this issue.  

I updated to master as of 2018-08-01 and after making changes to the configuration of the graph nodes and cards, no new nodes or deleted nodes, the relationship between the root and several nodes had been reset to None.  This means no further changes can be made (e.g. to fix the missing relationship) as the consistency of the graph is broken in two places and the graph must be saved before switching from the first to the second (and now third and fourth!)

This blocks me from testing the API work, as I can't make the cards to enter data to then test the retrieval.

**Comment by chiatt** [comment]
@adamlodge Can you try to rebuild the graph presented in the ticket? I'm able to create it without any errors. If you still see errors let me know. Perhaps I'm doing something differently in building the graph than you are.

**Comment by azaroth42** [comment]
I can only reproduce the error by editing data in the cards and then coming back to the graph view.

I also can't do it in a clean install of master at the moment, as another bug means we can't make new models!

**Comment by azaroth42** [comment]
Steps from clean install of current master:

* Create new model
* Set Ontology to CIDOC CRM
* Save edits
* Add child node
* Add child node
* set node 1's relationship to something (e.g. falls within)
* set make card to true
* save edits
* set node 2's relationship to something (e.g. contains)
* set make card to true
* save edits
* reload to avoid the cards not updating
* Go to cards and drag the lower card above the first card (eg new node_1 to above new node)
* save edits
* reload

Now New Node's relationship will be gone.

**Comment by chiatt** [comment]
@adamlodge and @azaroth42 I've merged a fix for this into master. Let me know if you see this issue occur again.

**Comment by adamlodge** [comment]
Looks good to me.  Leaving open to give @azaroth42 a chance to test.

**Comment by azaroth42** [comment]
:+1: that the case above is fixed. LGTM to close, and will open a new issue if there's another problem with similar symptoms that aren't addressed by this fix.
