### ISSUE TITLE
Add 'Remove Instances' to the dropdown for managing navigation of graph management commands

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3815]
**User Story**

Related to #3600: 
With the work done in #3574 and #3617, a user should be able to remove all the associated resource instances associated with a graph in the UI:
![image](https://user-images.githubusercontent.com/1542229/43552810-eca2f6e0-95a0-11e8-8050-a1624d0ac959.png)

`Remove Resources` or something similar, grouped with the Export, Clone and Delete section of this dropdown.

**Comment by apeters** [comment]
meets requirements
