### ISSUE TITLE
Permission icons are not visible in firefox

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3823]
The permission icons displayed next to the card name in the permissions card tree are not visible in firefox.

![Screen Shot 2018-08-03 at 12.55.37 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/51295764-8923-4f20-bd4d-e6a52415a32f)

**Comment by jmunowitch** [comment]
Duplicate of #4020
