### ISSUE TITLE
Cannot create models with ontology

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3825]
When selecting to use CIDOC-CRM as the ontology, no dropdown box appears to select the class from within the ontology. The model will still save, resulting in a broken internal state.

Steps to reproduce:

* Update to current master
* run migrations and yarn install
* setup_db to clean state
* Go to graph designer and select to create a new resource model
* Select CIDOC-CRM as the ontology in the dropdown
* Save the model (if you want)

Screenshot:
![screen shot 2018-08-03 at 3 16 24 pm](https://user-images.githubusercontent.com/871868/43668144-4861e7d0-9730-11e8-95fc-84b0c5b85b64.png)

**Comment by jmunowitch** [comment]
Solved with ba6037c39e0081e7a3002223fe01716d10d6a7bc.
