### ISSUE TITLE
JSON-LD: RDM concepts should be resolvable entities

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3855]
Using the concept data type results in a tile URI being generated, with a value of a UUID.  The tile URI results in a 404 when being requested, but is wrong anyway.

Instead, the concept managed by the RDM should have its own consistent URI, rather than having a URI that is unique to the model that it is part of.

For example, currently a concept reference generates:

```
"classified_as": [
  {
    "id": "http://localhost:8000/tile/ba189705-9e88-4270-af62-fb0949142e11/node/62beec23-9b3e-11e8-962e-a4d18cec433a", 
    "type": "Type", 
    "value": "84ff88e5-4879-467d-82a8-a42095913c59"
  }
]
```

I don't know where the UUID in value comes from. I have only three concepts in the RDM, none of which have this UUID as their Arches ID. It is also not the UUID of the Thesaurus, nor the Collection.

The preferred result would be, assuming it references a resource with an ID of `...c64a` with a label of `concept 1`:

```
{
  "id": "http://(host)/(slug-for-rdm)/...c64a",
  "type": "Type",
  "label": "concept 1"
}
```

And if the term is imported from an external thesaurus, such as AAT, then the `id` should be the external URI not an internal one. The RDM could be treated separately with its own context for the SKOS definitions, but the above should still be available as a link across to it from the CIDOC-CRM layer of instance data.

**Comment by apeters** [comment]
The "value" in the above example is actually the UUID of the chosen "Value" (from the values table) of the concept.  
A concept may have pref and alt labels, and in different languages, and when a user selects one of those it is that UUID that is persisted (not the more general concept UUID).  Because of this we can display to the user the concept in the EXACT form they initially selected.

We need to have the @id in the form it is currently because without it a user would never be able to PUT tile/node data.  This @id doesn't represent the id of the value, it represents the id of tile/node instance.  

To capture what you want, I would suggest something like this:
```
{
  "id": "http://localhost:8000/tile/ba189705-9e88-4270-af62-fb0949142e11/node/62beec23-9b3e-11e8-962e-a4d18cec433a", 
  "type": "Type",
  "label": "concept 1"
  "value": "http://(host)/(slug-for-rdm)/...c64a"
}
```

**Comment by azaroth42** [comment]
As a design consideration, which we've talked through a little in slack previously, I feel that this makes the RDM unusable. The point of the p2_has_type relationship is to point to a consistent resource -- the one that is now just a string in "value", rather than the identity of the node.

It would be more accurate to create models for the Types, and refer to them with `resource-instance` or `resource-instance-list`. The above is an unnecessary (and indeed from my viewpoint harmful) layer of indirection.

**Comment by apeters** [comment]
I believe that this should be handled by the to_rdf/from_rdf methods in the datatype class that @benosteen developed

**Comment by azaroth42** [comment]
@apeters It needs at least API level integration such that there's a URL that you can go to that delivers the concept description. I believe that the RDM is not a native datatype system, and hence Ben's code won't help here? 

Or ... what is the URL that will deliver back all of the information about a particular concept as managed in the RDM?

**Comment by apeters** [comment]
There used to be a way to get back a concept as JSON, but that seems to have be refactored out of the code.  It would be a relatively simple matter to bring it back

**Comment by azaroth42** [comment]
Let's set this as a lower priority compared to other issues in this particular roadmap track. If this doesn't happen in the next 3 months, we're not currently going to be significantly affected, as 99% of the time, the concepts are only externally defined ones in AAT.

**Comment by azaroth42** [comment]
Closing -- RDM-future will just have this natively from having its own models etc.
