### ISSUE TITLE
docker/entrypoint.sh - assumes project is already created if target dir has any files in, including '.files'

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#3857]
Line 191 in entrypoint.sh runs a test to see if the target directory for a custom Arches site exists or does not have any files inside. Any file, including 'hidden' files, can cause this to be False and the code assumes that "Custom Arches project '${ARCHES_PROJECT}' already exists."

**To Reproduce**
1. Create docker-compose-local.yml to create a custom Arches site (as detailed https://github.com/archesproject/arches/blob/master/docker/Readme.md#arches-core-development)
  -- key point: assume the custom site will be installed into '/dev' and that this volume will be accessible from the host filesystem
2. docker-compose -f docker-compose-local.yml build --no-cache arches
3. docker-compose -f docker-compose-local.yml up -d

If a hidden file (eg .DS_Store) is added inside "/dev" between spinning up the arches stack and the test within the entrypoint.sh to see if the custom project already exists, it will skip the install and fail later repeatedly (without terminating the script) at points where it cannot find 'manage.py' within the custom site.

**Expected behavior**

  - Custom Arches installation will happen if the target directory does not exist, or exists but is empty of any non-hidden files.

**Your Arches Information**
*   Version used: 4.3
*   Operating System and version: Built with latest docker-compose profile.

**Ticket Background**
*   Found by: @benosteen

**Comment by jmunowitch** [comment]
Reviewed and looks good.
