### ISSUE TITLE
Resource Editor: default node should be the root node when opening the resource editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3863]
When opening the resource editor, Arches should default to the root node, which would show the report for the resource instance being edited.

For new instances, the report should show a message alerting the user that this is a new instance with no saved data.  Use attached image as a guide for displaying the message![editor message.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/5156438e-365a-4efe-ae42-940d244d045c)

**Comment by apeters** [comment]
meets requirements
