### ISSUE TITLE
Graph Designer: Dirty state is triggered when no edits have occurred

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3875]
**Describe the bug**

Browsing both the Graph tree and the Card Tree triggers the dirty state.

**Screenshots**
Card Designer:
![cardmanagerdirtystate](https://user-images.githubusercontent.com/1542229/43977503-3d741294-9c99-11e8-86cf-fc536d7045de.gif)
Graph Designer:
![graphdesignerdirtystate](https://user-images.githubusercontent.com/1542229/43977513-48fa67ee-9c99-11e8-976d-ff3ae94d8961.gif)

**Comment by jmunowitch** [comment]
I am unsure if this is related to @chiatt's work on #3787.

**Comment by chiatt** [comment]
@jmunowitch Yeah - that's the same issue. I'm going to close this one as a duplicate.
