### ISSUE TITLE
Error when loading search page as a guest

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3877]
When running arches as a guest, an ajax request causes a redirect to the auth page causing an error. 

![Screen Shot 2018-08-10 at 2.10.00 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/65f34897-4065-4a70-a358-c28238b04ced)

**Comment by jmunowitch** [comment]
Reviewed and looks good.
