### ISSUE TITLE
Required node error displays "node name" rather than a widget label

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3885]
If you don't supply a required value for a node, the error message displays the node name which is not represented in the UI, rather then the widget label, which would be more appropriate.

![Screen Shot 2018-08-13 at 1.55.59 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/2e26d8a4-7561-48be-a9b0-1d06306e5260)

**Comment by ryan86** [comment]
<img width="700" alt="screen shot 2018-08-24 at 10 00 01 am" src="https://user-images.githubusercontent.com/3038476/44597471-9446f500-a784-11e8-8a41-b67762ebd7db.png">

meets requirements.
