### ISSUE TITLE
Importing a graph can sometimes silently fail

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3886]
I tried importing a graph into the test package that was originally designed from the Disco package and the import failed without any error.  Because of this I'm not sure why exactly it failed, missing ontologies most likely, but maybe something else too.

**Comment by ryan86** [comment]
@apeters I am unable to recreate this. To try to reproduce it I loaded the arches test package directly from github with -db set to True. Then I imported all the DISCO resource models without issue.

**Comment by apeters** [comment]
@ryan86 I can't reproduce this now either, closing for now
