### ISSUE TITLE
Export/Import of resource model loses cardinality configs

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3895]
When I export a resource model as json, and then import that file to same instance of Arches (after deleting the original) the cards revert their "All Multiple Values" (cardinality) setting to "no".  I tested and observed this behavior both when importing via package load and via import graph on UI.

Makes me worry that other configs are getting lost when graphs are exchanged.

**Comment by jmunowitch** [comment]
Reviewed and looks good.
