### ISSUE TITLE
Confirm that in-app help works as expected

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3902]
Context appropriate in-app help should display correctly when a users clicks on the help link in the page.

This is separate from card-level help.

**Comment by apeters** [comment]
In `Node Level Settings` section, `Expose to Advanced Search` content is in italics (should it be?)
The `Resource Editor` help still has the old gifs.

**Comment by mradamcox** [comment]
Nope, shouldn't be italicized, good catch. I'll add a commit to fix that, and will add the notes about JSON context, Resource Model color, and report templates in Branches.

**Comment by apeters** [comment]
meets requirements
