### ISSUE TITLE
"For more information" links to 'arches4.readthedocs.io', not to 'arches.readthedocs.io'

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#3904]
**Describe the bug**
The "help content loaded from contextually referenced template" has a footer that links to the 'arches4.readthedocs.io' site. This greets users with a deprecation notice that the documentation has moved to 'arches.readthedocs.io'. I assume that this is the intended target these days.

**To Reproduce**
Load anything that displays this template. For example, clicking on the top-right '?' button that is displayed in most pages.

**Your Arches Information**

*   Version used: 4.1.0-1604-g3d3762386 (from git describe --tags)

**Comment by mradamcox** [comment]
completed, thanks ben!
