### ISSUE TITLE
Design Question: Should boolean switch widget have 2 or 3 states when node is required?

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#3915]
Currently the switch widget has three states
1. True
2. False
3. Null

Currently the default value is null and if node is required, and card is saved with null as the state, then an error message is thrown.

This might be an acceptable UX, but I thought this may warrant a discussion.  Screenshot attached to make visualizing the issue easier.

![Screen Shot 2018-08-16 at 10.54.36 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/e496c6d4-497b-4e55-bc1f-f17dab05874d)

**Comment by chiatt** [comment]
@adamlodge Can you confirm that you're still getting this error?

**Comment by adamlodge** [comment]
Confirmed. This is still an issue.

**Comment by chiatt** [comment]
Maybe we should have a config in the widget to allow or not allow null values.

**Comment by chiatt** [comment]
I think this is a good question, but given that there hasn't been much discussion here, and there haven't been any other concerns from the community, I'm going to close this for now.
