### ISSUE TITLE
Deleting files in UI does not remove the files from the server

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3934]
It appears that Arches does not delete files from the file system when a user deletes the file from the UI.

To recreate:
1. Upload a file using the file list widget
2. Save and observe that the file now appears in the "uploadedfiles" folder in the Arches package root (this it the default location for storing files).
3. Delete the tile with the file that you just saved
4. Note that the file still resides in the uploadedfiles folder.

**Comment by veuncent** [comment]
Does this issue still exist for you? I am having the same problem, although I use Azure Blob Storage as a storage backend, which may be the cause in my case.

**Comment by chiatt** [comment]
Hey @dwuthrich This issue should now be resolved. Can you confirm?
