### ISSUE TITLE
Docker Readme should explain DEV vs PROD mode

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#3941]
The Docker Readme should explain the difference between running in `DJANGO_MODE=DEV` versus `PROD`, especially with regard to static files and Nginx.

**User Story**

When a new developer starts setting up Arches with Docker, they should know that `collect_static` is not run when running in `DJANGO_MODE=DEV`. In that case, they should not use the Nginx container (which is preferred for developing anyway)

**Acceptance Criteria**
-   [x] Documentation

**Definition of Done**
docker/Readme.md explains not to use Nginx when using `DJANGO_MODE=DEV`

**Comment by mradamcox** [comment]
@veuncent Just a thought, but would it make sense to put the docker docs into the docs repo? Maybe a section under the Developing With Arches header? If it makes more sense to have it along with the code that's fine too.

**Comment by veuncent** [comment]
Good point, though I think that's up to you guys :)
Personally I would put it under `Installation and Configuration`, because it is not just for developing, but definitely also to just get Arches running quickly. You would want to present that option to your users as early as possible.

**Comment by mradamcox** [comment]
@jmunowitch do you have any thoughts on this? Would it be possible to completely remove the docker readme from arches and put its contents in RTD, or do you think it should remain with the code base?

**Comment by veuncent** [comment]
@mradamcox I just came across this open issue. The PR for it has already been merged. Should we close this?

The discussion about whether to move the Docker readme to RTD is another issue :)

**Comment by mradamcox** [comment]
Yup, I'll close it now. Thanks!
