### ISSUE TITLE
Move card level help from from its own panel to middle panel

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3946]
When trying to define card level help, Arches shows the card level help form in a panel that obscures the data entry form.  We should move the form into the existing card management panel, directly underneath the toggle for card-level help

**Comment by dwuthrich** [comment]
End result should look as follows: 

(accomplished by modifying the following CSS classes as follows):
.tertiary-panel {
    position: relative;
    top: 0px;
    left: -15px;
    bottom: 0;
    z-index: 50;
    border-width: 0px;

Increasing width of .middle-column-container to 450px when "Enable card level help" is toggeled

<img width="1668" alt="card level help" src="https://user-images.githubusercontent.com/815185/44357848-08715800-a468-11e8-89d1-a28a85213983.png">

**Comment by apeters** [comment]
@jmunowitch 
This works, but there are a few things that might improve this a little:
- remove the opacity property from the `card-help-panel` class
- set the background color of the `card-help-panel` to  #e7e7e7
- set the color of the `help-close` class to #868686
- set the data-bind property for both the `help panel title` to `textInput` rather then `value` 
- remove the word `Help` from the help content title as it becomes distracting

**Comment by jmunowitch** [comment]
All the above items have been implemented.

**Comment by apeters** [comment]
meets requirements
