### ISSUE TITLE
Search RDM using UUID

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#395]
It would be very useful, especially from a developer's point of view, to be able to search the RDM for a concept by using that concept's UUID.  Similarly, it would be nice for users to be able to enter UUIDs in the search bar.

**Comment by apeters** [comment]
I completely agree.


Director of Web Development - Farallon Geographics, Inc. - 971.227.3173

**Comment by mradamcox** [comment]
I just realized that you can enter www.blah.com/rdm/eb4220c2-5e6c-4e2b-8179-31bb0f743382 in order to view a concept directly.  More or less makes this a non-issue.

**Comment by apeters** [comment]
closing because of @mradamcox's comment above.
