### ISSUE TITLE
Related Resources not showing up in report in Resource Editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3956]
When editing a resource Arches now defaults to the root node and a resource report.  This report does not include related resources.  However, when accessing the report via manage > Jump to Report the related resources are listed as part of the resource report.

Arches should list related resources in both reports

**Comment by robgaston** [comment]
@dwuthrich I left the related resources off of the resource editor report intentionally.  This is for the same reasons as we did not include all of the related resources in the tree.  Some resources may have thousands of relations, so loading and showing all of those in the resource editor would significantly impact performance when loading the resource editor and showing those dynamically in the editor page would require retaining all of those records in memory and updating them accordingly.

For these reasons, I think that we should consider instead just adding a link at the bottom of the report in the resource editor that would jump you to the "Related Resources" item in the tree (which has our paged list of related resources.

Thoughts?

**Comment by dwuthrich** [comment]
@robgaston That makes sense.  Let's just leave the report as is.  Users can just click on the related resources branch in the tree if they want.
Closing ticket.
