### ISSUE TITLE
Close icon on multiselect chosen element appears incorrectly

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3961]
![Screen Shot 2018-08-21 at 10.20.58 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/a0d2cc2d-c975-450a-b10d-b1fb5be2afc3)

**Comment by jmunowitch** [comment]
Looks like the css class is currently set to `search-choice-close` instead of `select2-search-choice-close`

**Comment by jmunowitch** [comment]
Looks like this could be fixed by setting the css class to `select2-search-choice-close` instead of `search-choice-close`

**Comment by ryan86** [comment]
![screen shot 2018-08-23 at 4 47 42 pm](https://user-images.githubusercontent.com/3038476/44557640-471b4280-a6f4-11e8-9db1-897137a4dcd9.png)

meets requirements.
