### ISSUE TITLE
JSON-LD: Representation of file-list data type

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3971]
The representation of the file-list data type embeds a lot of custom JSON information into the `value` property of the resource as a string. It would be good to explode these out into CRM data, rather than an encoded string with custom properties.

```
{
 "type": "Person",
 "representation":  [
    {"id": "http://localhost:8000/tile/62a64365-4291-4478-8d13-07d1f8df907f/node/cd35b335-a592-11e8-b365-a4d18cec433a", 
    "type": "VisualItem", 
    "value": "[{\"accepted\": true, \"content\": \"blob:http://localhost:8000/f95cf90c-f2a4-4c28-af6b-2864c3c9687f\", \"file_id\": \"701ea4fd-a593-11e8-9763-a4d18cec433a\", \"height\": 3226, \"index\": 0, \"lastModified\": 1502583959000, \"name\": \"passport_rob2.jpg\", \"size\": 1351672, \"status\": \"uploaded\", \"type\": \"image/jpeg\", \"url\": \"/files/uploadedfiles/passport_rob2.jpg\", \"width\": 2420}]"}
 ]
}
``` 

It would be good to represent this with Dimensions for the size, height and width, `dc:format` for the media type, and the URI of the node would be the URL of the image itself, as available from the Arches instance.

TBD what the exact representation would be, and whether there should be a separate Image data type.

**Comment by azaroth42** [comment]
The discussion was that each "magic" data type should be a shortcut form of a larger structure, where the information in that structure can be managed by the system rather than needing an editor to hand-craft it.

File-List is a good example, as you put in a file, and get back a lot of information... currently encoded as a JSON inside a string, and not conforming to any model. If the particular structure is not the desired representation, then developers could duplicate the data type and change the model.
An alternative would be to have a templating system where the model structure could be designed in the regular graph manager, but with placeholder values for the information that is gathered, in this case, from the file. This seems like a good phase 2, and a static mapping per data-type as the initial target.

**Comment by apeters** [comment]
Sounds good, I was expecting that this mapping would be built in to the datatypes.  
We have a `transform_export_values` method that we might be able to tap into for that.
