### ISSUE TITLE
DB implementation to support node group level permissions

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#398]
- [ ] Utilize the existing Auth module to support node group level permissions
- [ ] Add/remove node group level permissions on node group create/delete
- [ ] Allow multiple users/groups to be associated with node group level permissions in a single call
- [ ] Add unit tests

acceptance criteria:
- [ ] permissions successfully persisted to the database
- [ ] a documented model for storing & retrieving user and role based permissions for a given node group

**Comment by apeters** [comment]
duplicate of #624
