### ISSUE TITLE
graph manager landing page/view

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#399]
landing view for graph page with a listing of existing graphs and tools to create new ones from a template

mockup from @dwuthrich pending.  

acceptance criteria:
- [x] a user should be able to visit /graph/ and find a page with a listing of existing graphs and a way to create new graphs using existing ones as a template.

**Comment by dwuthrich** [comment]
See mockup at: http://archesproject.github.io/mockups/resources.html

Note: I didn't have time to clean up most of the style="..." rendering with CSS classes... sorry.  Let me know if you'd like me to provide classes once you've seen the mockup.

**Comment by apeters** [comment]
meets requirements
