### ISSUE TITLE
knockout-mapping produces a large number of strings in memory

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3993]
Knockout mapping seems to be producing a large number of strings in memory. Presumably this is because its computeds are not getting disposed even though the models using them no longer exist. Over time this can adversely impact arches performance. 

This SO question may provide some insights, but the proposed solution will unlikely work for every place we are using knockout mapping: https://stackoverflow.com/questions/27490439/strange-memory-leak-in-knockout-mapping-plugin#27492430

**Comment by mradamcox** [comment]
https://github.com/archesproject/arches/issues/4033 is probably related to this

**Comment by chiatt** [comment]
During 4.3 testing I noticed memory issues in the graph designer, and the number of knockout-mapping strings was fairly low. There may be some other objects that are not getting properly disposed.

**Comment by chiatt** [comment]
Likely the cause of  #4149 as well
