### ISSUE TITLE
Permissions: Arches does not show users with read permissions cards

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3998]
Setting cards with read only permissions results in Arches not showing cards to users

See: http://recordit.co/f30rrn4qau

**Comment by apeters** [comment]
@dwuthrich to explain what you're seeing, in the editor, you need write permission to edit a card.
In the permissions manager, you've only given write permission to the "Lincoln Activity Name" card.  I'm assuming that if you went to the report, you'd see all the cards that have "read" permissions.

**Comment by dwuthrich** [comment]
@apeters The issue is that the resource editor report does not show the user data that they have permissions for.  This ticket documents the fact that a user with read permissions can not read data when in the resource editor report.

**Comment by dwuthrich** [comment]
meets requirements
