### ISSUE TITLE
Design of the CardTree is inconsistent

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#4005]
The main thing here is the `New Node_1` card's tree connection to either the card or widget above it is unconnected. 
 **Screenshots**

Existing | Expected
------------ | -------------
![screen shot 2018-08-24 at 11 52 38](https://user-images.githubusercontent.com/1542229/44602395-5d78db00-a794-11e8-971e-55ddf5f067b1.png) | ![screen shot 2018-08-24 at 11 52 38 copy](https://user-images.githubusercontent.com/1542229/44607353-0a5b5400-a7a5-11e8-8f25-c620c6e69f70.png)

**Comment by apeters** [comment]
@jmunowitch  can you add a little more explanation?

**Comment by jmunowitch** [comment]
@apeters: I updated the main comment.

**Comment by mradamcox** [comment]
I'm not seeing this on Chrome nor Firefox.

**Comment by mradamcox** [comment]
Realized I was looking at the graph tree, not cardtree.

**Comment by jmunowitch** [comment]
Reviewed and looks good.



Screenshot from Master |
------------ | 
![screen shot 2018-10-09 at 11 05 26](https://user-images.githubusercontent.com/1542229/46688871-4e6ab280-cbb3-11e8-994a-1cb1b7fa4060.png) |

**Comment by jmunowitch** [comment]
Lets confirm that this makes its way into `stable/4.3.x`
