### ISSUE TITLE
Related Resources splash page broken when a user is not a Graph Editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4010]
Clicking on the related resources node in the resource editor tree functions as expected in Chrome, but shows a broken data entry form in FF and Safari: http://recordit.co/ci8CtPAO5v

**Comment by jmunowitch** [comment]
I am not able to reproduce this on stable/4.3.x

**Comment by jmunowitch** [comment]
With @chiatt's suggestion, I was able to reproduce this with a provisional edit: 
![screen shot 2018-08-30 at 13 55 22](https://user-images.githubusercontent.com/1542229/44878703-69fda780-ac5c-11e8-9f40-258b75dfa181.png)

Here is the console error:
```
TypeError: this.graph.domain_connections.forEach is not a function[Learn More] related-resources-manager.js:279:17
	initialize http://localhost:8000/media/js/views/resource/related-resources-manager.js:279:17
	e.View backbone.js:1224:4
	n backbone.js:1884:33
	vm.showRelatedResourcesManager/</< http://localhost:8000/media/js/views/resource/new-editor.js:259:50
	u http://localhost:8000/media/packages/jquery/dist/jquery.min.js:2:27452
	fireWith http://localhost:8000/media/packages/jquery/dist/jquery.min.js:2:28202
	k http://localhost:8000/media/packages/jquery/dist/jquery.min.js:2:77649
	n/< http://localhost:8000/media/packages/jquery/dist/jquery.min.js:2:79907
```

**Comment by chiatt** [comment]
@jmunowitch Hi Jeff - Could you QA this in 4.3.x and master?
