### ISSUE TITLE
Rendering issue of the permissions Manager in Chrome on Windows and Firefox

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#4020]
**Describe the bug**

The Permission Icons in the Permissions Manager have rendering issues in Chrome on Windows and Firefox. In Chrome on Windows, a scroll bar appears on each card, and on Firefox, the permissions icons themselves to do not display.

**Screenshots**
Chrome on Windows:
![image](https://user-images.githubusercontent.com/1542229/44681019-2f91d180-a9f4-11e8-860b-b649cd446447.png)

**Ticket Background**
*   Found by: @mradamcox

**Comment by mradamcox** [comment]
looks good now. thanks @jmunowitch
