### ISSUE TITLE
Chrome Dev tools work extremely slowly in the Graph Designer

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#4033]
**Describe the bug**
This isn't a bug per se, but I wanted to record the fact that using dev tools has been extremely slow for me on the graph designer page, to the point of often crashing chrome. If others have this experience maybe we can pursue a way to address it. I'll note that FireFox dev tools does seem to work fine on these pages.

**To Reproduce**
1. Go to /graph, and enter the graph designer for a Resource Model or Branch. I was mostly using moderately large resource models, e.g. Heritage Resource from the Lincoln sample dataset.
2. Open Chrome Dev tools
3. Try to use the element selector as you normally would to inspect css.
4. For me, the tools loaded very slowly, ~10 seconds, and were high unresponsive and the page was frozen periodically.

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used: 4.3 pre-release
*   Operating System and version (desktop or mobile): Windows 10
*   Browser Name and version: Chrome
*   Link to your Arches Install (optional):

**Ticket Background**
*   Found by: @mradamcox

**Comment by mradamcox** [comment]
@chiatt hopefully I can check it out tomorrow.

**Comment by chiatt** [comment]
Hey @mradamcox, can you check and make sure this is working better for you in 4.3.x?

**Comment by chiatt** [comment]
@mradamcox It seems ok to me. I haven't noticed any issues. Perhaps is OS specific? Are you on Windows?

**Comment by apeters** [comment]
I haven't noticed any systemic issue here

**Comment by mradamcox** [comment]
thanks for checking, things have probably been smoothed over since I first encountered this.
