### ISSUE TITLE
Card name not inherited from node name

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4034]
When I create a new node that is consistent being a card, the card label does not inherit from the node name.

**Comment by apeters** [comment]
To me it looks like the card takes on the name of the node at the time the card is created.  Subsequent edits to the node name don't change the card label.  This is by design.
Was that what you were seeing @adamlodge ?

**Comment by adamlodge** [comment]
I cant be certain about the sequence of events when I made the ticket yesterday, but I think your instinct is right. Testing today bears out that this is functioning as designed.
