### ISSUE TITLE
When using the geocoder to find a point on the map it appears to place that point on the map, but saving the map doesn't actually save the dropped point.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#4049]
This is because the dropped point is also rendered as a red point on the map which is the same way a point placed directly on the map is rendered.  Maybe something like cross hairs would be better.  Or maybe it should just be like a point added manually.

**Comment by adamlodge** [comment]
My experience is this: I use the geocoder in the data editing card simply to zoom in to my area of interest where I will manually capture the geometry I am actually interested in.  I have never once wanted to actually use the resulting point from my geocode as part of the geometry I want to save.

**Comment by dwuthrich** [comment]
@apeters @adamlodge I think Alexei's suggesting of styling the geocoded point as a cross-hair or other icon would be a better experience because users would no confuse the geocode as an instance

**Comment by chiatt** [comment]
The new geocoder marker is now very distinct from a drawn point.
