### ISSUE TITLE
Parents of selected nodes not highlighted in Card & Permissions trees

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4066]
Parents of the selected nodes are properly highlighted in the Graph and Resource Editor trees.

This used to work in the Card and Permissions trees as well, but it seems to have regressed.

Graph tree (working):

<img width="302" alt="screen shot 2018-08-29 at 8 55 35 am" src="https://user-images.githubusercontent.com/1187406/44799840-c633cf00-ab69-11e8-8998-2a1673d0a575.png">

Card and Permissions trees (not working):

<img width="308" alt="screen shot 2018-08-29 at 8 55 43 am" src="https://user-images.githubusercontent.com/1187406/44799876-dd72bc80-ab69-11e8-887b-61a0e04a66be.png">

<img width="303" alt="screen shot 2018-08-29 at 8 55 55 am" src="https://user-images.githubusercontent.com/1187406/44799889-e4013400-ab69-11e8-9064-2c60c351281d.png">

**Comment by adamlodge** [comment]
meets reqt
