### ISSUE TITLE
Resource Editor: Overlay button on Map Widget Flashes on load

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#4080]
**Describe the bug**

Overlay button on Map Widget Flashes on load.

**Screenshots**
![overlay button flashing on resource editor](https://user-images.githubusercontent.com/1542229/44875384-e12e3e00-ac52-11e8-96d2-855df4556dea.gif)

**Ticket Background**
*   Found by: @jmunowitch

**Comment by jmunowitch** [comment]
This happens in the Report as well:
![overlay button flashing on resource report](https://user-images.githubusercontent.com/1542229/44876504-24d67700-ac56-11e8-9bca-2b075762cd79.gif)

**Comment by dwuthrich** [comment]
closing, as this widget is now replaced with the next generation map widget
