### ISSUE TITLE
Card Component - default UI is used in new card components unless overridden.

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#4092]
**Is your feature request related to a problem? Please describe.**
I anticipate that the main area of outside development will be around data entry and the 'form' and 'report' user interfaces. This is presented by the "Card Component". If a developer wished to create their own card component, currently they would have to replicate the functionality for the editor/design/permissions tree (jqtree)

**Describe the solution you'd like**
- Developer wishes to create a new 'form' for entry that re-arranges the widgets associated with the card, or perhaps even creates their own form entry from scratch.
- They create 'myformmodule.htm' which extends the base card component, and places the custom UI in the appropriate template block (eg {% block form %} ... {% endblock %})
- The default javascript is used, unless overridden.
- They register the new card component through the CLI or UI.
- The UI falls back to default presentation and behaviour when not overridden by the new component for the cards that are associated with this new card component.

**Additional context**
How to handle overriding the default.js behaviour requires some thought, but for most of the use cases I have seen so far, the ability to include extra js alongside the default might be useful but not required.

The templating system should provide a good pattern for handling the separation of concerns as outlined above.

**Comment by azaroth42** [comment]
Agreed that this would be a good enhancement to the code for developers

**Comment by chiatt** [comment]
These changes are now implemented in the default card component.
