### ISSUE TITLE
Graph Designer UI bug when adding a branch

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4095]
**Note: this only happens in Chrome. In Firefox everything looks fine**

**Describe the bug**
When adding a branch to a resource model node, I received the following result:
![image](https://user-images.githubusercontent.com/7893339/45106866-1c8ba980-b138-11e8-8fac-1ad3892ed08a.png)

**To Reproduce**
1. Open a model in the Resource Editor
2. Click on 'Add Branch' (on any node)

**Your Arches Information**

*   Version used: 4.3.1
*   Operating System and version (desktop or mobile): Docker on Windows
*   Browser Name and version: Chrome 68.0.3440.106

**Comment by chiatt** [comment]
@apeters I saw @veuncent submit this ticket this morning and elevated it to the sprint backlog.

**Comment by chiatt** [comment]
@veuncent Do you see any errors in the Chrome dev tools console?

**Comment by veuncent** [comment]
No errors, no nothing. Also all requests in the network tab return 200.

Also can't scroll down in Chrome.

By the way, Firefox also has its share of bugs: there I can't drag the
separator bar between the list of nodes in the left and the settings/graph
preview in the right.

**Comment by chiatt** [comment]
@veuncent Thanks - there's a ticket for the separator bar in Firefox (#3620).  I checked Chrome on Windows and wasn't able to reproduce this issue you're seeing. However, I haven't yet checked using Docker because it seemed unlikely that Docker was the source of the problem, but perhaps it is.

**Comment by apeters** [comment]
this looks like a knockout issue

**Comment by veuncent** [comment]
Woke up this morning and everything worked as it should...

[image: image.png]

**Comment by veuncent** [comment]
Woke up this morning and everything worked as it should...

![image](https://user-images.githubusercontent.com/7893339/45150086-58238380-b1cb-11e8-9a3a-c606bc111bb9.png)
