### ISSUE TITLE
Arches does not support Postgresql username with special characters

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4099]
**Describe the bug**
Postgres usernames with special characters are not supported at the moment.
The format of usernames in the Azure Postgresql service is `username@hostname`. This database service is therefore not usable with Arches.

**Your Arches Information**

*   Version used: 4.3.1
*   Operating System and version (desktop or mobile): Docker for Windows 10

**Comment by jmunowitch** [comment]
Solved with https://github.com/archesproject/arches/pull/4100
