### ISSUE TITLE
RDM Related Concepts: wrong GUID recorded in Target Concept

### ISSUE THREAD

**Issue by ViktorGetty** [archesproject/arches#4125]
**Describe the bug**
When linking a related concept through the UI, the wrong GUID is recorded into the target concept. Instead of of the source's GUID, the target's own GUID is recorded. This leads to target being linked to itself.

Example of the target XML after export:

 ****_<skos::Concept rdf:about="http://www.archesproject.org/6b68705a-73a3-46f4-9185-520d89582b28">
    <skos::prefLabel xml:lang="el">{"id": "464601bc-5cf8-4185-b827-c5ca507ca0fc", "value": "Viktor Test Concept People"}</skos:prefLabel>
    <skos::inScheme rdf:resource="http://www.archesproject.org/932a19f5-dcbb-497e-8f58-7f44976d894c"/>
    <skos::related rdf:resource="http://www.archesproject.org/6b68705a-73a3-46f4-9185-520d89582b28"/>
  </skos:Concept>_****

**To Reproduce**
1. Create a concept with the name "Source Concept"
2. Create a concept with the name "Target Concept"
3. Open "Source Concept" and press "Add related concept". Search for "Target Concept" and add it as a related concept with any type of relations
4. Export schemes with both: source and target concept
5. In the source concept the correct GUID of the target is recorded. In the target concept its own GUID (instead of the source's) is recorded

**Expected behavior**
Source and target concepts should contain each other's GUIDs

**Your Arches Information**
Arches 4.1 on Ubuntu. Chrome.

**Comment by azaroth42** [comment]
Validated the issue. No known workaround.
