### ISSUE TITLE
RDM Related Concept: Concept linked with relation type 'related' appears in RDM UI as a child of the Source Concept

### ISSUE THREAD

**Issue by ViktorGetty** [archesproject/arches#4126]
**Describe the bug**
If a target concept is added to a source concept as a related concept with the type 'related', it appears in the RDM as a child concept of the source concept. It does not happen with any other related type (relatedMatch, exactMatch, etc...)

**To Reproduce**
1. Create a concept with the name "Source Concept"
2. Create a concept with the name "Target Concept"
3. Open Source Concept and add Target Concept as a related concept with relation type "related"
4. In RDM open the scheme with Source Concept on the left and find Source Concept: Target Concept is now appears as a child of the Source concept

**Your Arches Information**
Arches 4.1 on Ubuntu. Chrome

**Comment by azaroth42** [comment]
@ViktorGetty We cannot reproduce the issue. Following the instructions does not result in the target concept being a child of the source concept.  Can you check to see if the issue still exists in master?  Thanks!

**Comment by azaroth42** [comment]
Ha, no, reproduced it! Validated the bug.

**Comment by azaroth42** [comment]
Tagging as low priority as the severity of the bug is also low - the way to avoid the problem is simply not to use the `related` relationship in the RDM
