### ISSUE TITLE
RDM Related Concepts: impossible to edit Related Concept

### ISSUE THREAD

**Issue by ViktorGetty** [archesproject/arches#4127]
**Describe the bug**
There is no way to edit / modify / remove 'Related Concepts' (even see the relation type) through the UI.  

**To Reproduce**
1. Relate any two concepts
2. Click on 'Related Concept' - no editing capabilities

**Your Arches Information**
Arches 4.1 on Ubuntu. Chrome

**Comment by azaroth42** [comment]
Seems to be fixed in master. The red x appears that allows the relationship to be deleted.

![screen shot 2019-01-18 at 2 31 19 pm](https://user-images.githubusercontent.com/871868/51416338-e4589680-1b2d-11e9-92c7-fcad6db061ce.png)

**Comment by ViktorGetty** [comment]
Bug was found in Arches 4.1. Does not appear in 4.3. Closing.
