### ISSUE TITLE
Collectors in collections are clickable 

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4134]
**Describe the bug**
Collectors in concepts/collections are clickable, while they shouldn't be.

**To Reproduce**
1. In RDM -> concepts, select a concept with children
2. click `Add Value` -> enter name of the concept in the text field --> select 'Collector' from the Type dropdown
3. Go to Collections, add a collection and add the concept from step 1/2
4. Add the collection to a concept node in a resource model
5. Add a new resource from that resource model
6. Notice that it is possible to select the parent concept in the dropdown list of the edited node.

**Screenshots**
`Length` is defined as a parent concept with the `Collector` value attached:
![collection](https://user-images.githubusercontent.com/7893339/45961577-214cca80-c01f-11e8-86a3-c021e0bcc9ec.png)

The `Length` concept is clickable in the dropdown:
![dropdown](https://user-images.githubusercontent.com/7893339/45961579-23168e00-c01f-11e8-9177-628b8c47e5b7.png)

**Expected behavior**
Collectors shouldn't be clickable.

**Your Arches Information**

*   Version used: 4.3.1
*   Operating System and version (desktop or mobile): Ubuntu 16.04 (Docker on Windows)
*   Browser Name and version: Chrome

**Comment by adamlodge** [comment]
meets reqt

**Comment by veuncent** [comment]
What's the verdict on this one, @adamlodge ? Is it working as designed?

**Comment by adamlodge** [comment]
@veuncent it is working as designed, but this functionality has reverted at least twice in various releases so I'll be vigilant about testing.

**Comment by veuncent** [comment]
Having thought about this a bit more, I do think it would be quite valuable to have subdivisions in dropdowns of which the parent is not clickable. 

Would you reconsider @adamlodge ?

**Comment by adamlodge** [comment]
@veuncent I agree.  When I said it's working as designed and closed the ticket, what I meant is that you can now configure specific nodes to be unclickable per the request in the ticket.  The issue is fixed in master.

**Comment by veuncent** [comment]
That's great to hear. I looked for the corresponding issue for this so I
can cherry pick the commits, but couldn't find anything that matches your
description.
Do you happen to know the story/issue this was solved in?

**Comment by robgaston** [comment]
@veuncent here's the PR with those edits to `master`: #4199 
and here's the PR to `stable/4.3.x`: #4200

**Comment by veuncent** [comment]
Nice, thanks
