### ISSUE TITLE
Resource Model import error: 'list' object has no attribute 'itervalues'

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4172]
**Describe the bug**
Importing certain resource models results in the following error:
`'list' object has no attribute 'itervalues'`

**To Reproduce**
1. Import this Resource Model: https://github.com/globaldigitalheritage/arches-3d/blob/9b7fb6c690045eaaa9e42ffa47985c5e82d16f98/arches_3d/arches_3d/db/graphs/resource_models/Potree%20Model.json
2. Notice that the import succeeds and the Potree Model is listed on the Resource Model page 
3. Delete the Resource Model
4. Import this Resource Model: https://github.com/globaldigitalheritage/arches-3d/blob/5065dd7f1f5e51ea5b7c5d784cf424c5d2d14eb6/arches_3d/arches_3d/db/graphs/resource_models/Potree%20Model.json
5. Notice how the import finishes without errors in the frontend, but the Resource Model is not listed on the Resource Model page
6. Notice the error in the server logs: 'list' object has no attribute 'itervalues'

**Expected behavior**
There is no obvious reason for the import to fail; I expected it to succeed with both listed Resource Models.
Also: I would expect either a clear error message to display on the frontend or the import to succeed.

**Your Arches Information**

*   Version used: master branch #bba6bd7dbc2bfe7381f68da90e0f5a97783f9ffe
*   Operating System and version (desktop or mobile): Ubuntu 16.04 (Docker for Windows)
*   Browser Name and version: Chrome

**Comment by veuncent** [comment]
**Update**: the same error occurs when I export the Resource Model from step 1 and import it again

**Comment by veuncent** [comment]
**Update**: Going back to Arches tag 4.3.1 everything works fine: I can export models and import them again without a problem

**Comment by mradamcox** [comment]
Yes, @ryan86 and I encountered this same issue yesterday. Specifically it seemed that if a resource graph is exported from master, you can't import it anywhere, but if it's exported from stable/4.3.x, you can.

**Comment by mradamcox** [comment]
I just created a new enhancement issue https://github.com/archesproject/arches/issues/4178, which could probably easily be address at the same this one.

**Comment by chiatt** [comment]
@robgaston @ryan86 Should this go into 4.4.x?

**Comment by robgaston** [comment]
@chiatt I think so, but the issue resolution hasn't been QA'd yet

**Comment by ryan86** [comment]
@chiatt and @robgaston I was able to import a resource model exported from master, but was not able to import the file posted in the in original comment of this ticket.

**Comment by chiatt** [comment]
@ryan86 Do you see the same error that @veuncent was seeing regarding `.itervalues` on a list?

**Comment by chiatt** [comment]
Nobody has noticed this issue recently
