### ISSUE TITLE
Updating Node name should update default card name

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4175]
If the card name is the default (e.g. New Node or similar) then setting the node name in the model should update the card name.  If the card name has been configured separately, that data should not be overwritten.

**Comment by azaroth42** [comment]
Running into this issue again. I have a Timespan with two dimensions, one for minimum duration and one for maximum duration.  This allows us to have an event that occurred over 2-3 days, sometime during a 30 day time period. 

The issue is that importing the Dimension branch means that the card name for both minimum and maximum are just "Dimension" and it's impossible to tell from the card view which is minimum and which maximum. I need to create an instance, and then look at the JSON-LD export to see which is which!

**Comment by azaroth42** [comment]
:anguished-bump-emoji:

**Comment by dwuthrich** [comment]
meets requirements
