### ISSUE TITLE
Graph Export Should Write Contents in Consistent Order

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#4178]
**Is your feature request related to a problem? Please describe.**
Currently, when working with graphs that are kept in version control, even the smallest change creates a diff on the entire file. This makes development difficult because it's impossible to track discrete changes to graphs.

**Describe the solution you'd like**
When a graph is exported from the UI, some sorting pattern should be applied to all of the objects. This could be alphabetical based on UUIDs, and use sortorder properties whenever possible. Ultimately, the point is that if a single card name is changed (for example), the diff between the two files should be just one line.

**Describe alternatives you've considered**
Can't think of any to address the problem I've outlined.

**Comment by chiatt** [comment]
Fixed in the latest
