### ISSUE TITLE
Update the JSON-LD export

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#4186]
The JSON-LD export should be semantically valid outside of an Arches context and be modelled in terms of RDF and how RDF handles types of data such as numbers, booleans, resource URIs, multiples and so on. The current export puts all of the 'leaf' node information (Arches Datatype information, serialised in plain JSON) as a literal value for a given node. It also reifies all the basic datatypes (number, boolean, etc) instead of exporting a single triple as expected.

**Comment by chiatt** [comment]
Hey @benosteen, I see this ticket is in progress, but unassigned. Would you happen to be working on it?

**Comment by benosteen** [comment]
Actually, I think that this specific ticket is wrapped up now with the PR
that pushed in branch 4186_somethingsomething. Should be closed now I think.

**Comment by chiatt** [comment]
Thanks @benosteen
