### ISSUE TITLE
[Docker] User should have option to turn off yarn install

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4190]
**Is your feature request related to a problem? Please describe.**
Our Docker entrypoint.sh currently always runs the `yarn install` command. Since this takes a long time, it is standing in the way of rapid development and deployment. 

**Describe the solution you'd like**
A flag to turn off `yarn install`

**Additional context**
Expect a PR for this soon.

**Comment by jmunowitch** [comment]
Solved with https://github.com/archesproject/arches/pull/4191
