### ISSUE TITLE
Create plugin model and migration

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4202]
we need a model to store plugins added to Arches
should be similar to widgets table; will additionally need an icon for navigation menu

**Comment by apeters** [comment]
@robgaston to test this it would be nice to have some documentation on how to register a plugin and the form of the json file that needs to be uploaded

**Comment by apeters** [comment]
@robgaston found in another ticket the way to register a new plugin via sql.  It would still be nice for this to be documented.

Meets requirements
