### ISSUE TITLE
Add plugins to the left navigation menu

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4203]
Plugins registered with arches should show up in the left navigation menu.  these should:
- display the plugin icon
- display the plugin name
- link to the plugin page

**Comment by robgaston** [comment]
the demo plugin can be tested by running the following sql:
```sql
insert into plugins(pluginid, name, icon, component, componentname, config)
    values (uuid_generate_v4(), 'Map', 'fa fa-globe', 'views/components/plugins/map', 'map-plugin', null);
```

then going to the plugin page at (inserting the ID generated by the above sql): http://localhost:8000/plugins/{plugin_id}

**Comment by jmunowitch** [comment]
Reviewed and looks good.
