### ISSUE TITLE
Implement plugin page

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4204]
We need a page to render plugins registered w/ Arches.

The url should accept a plugin UUID and return a page that renders the referenced plugin component (in a default state).

Plugin developers can use the querystring on this page to pre-seed their plugin with data as needed.

**Comment by robgaston** [comment]
the demo plugin can be tested by running the following sql:
```sql
insert into plugins(pluginid, name, icon, component, componentname, config)
    values (uuid_generate_v4(), 'Map', 'fa fa-globe', 'views/components/plugins/map', 'map-plugin', null);
```

then going to the plugin page at (inserting the ID generated by the above sql): http://localhost:8000/plugins/{plugin_id}

**Comment by apeters** [comment]
meets requirements
