### ISSUE TITLE
views.tile.post() does not handle all exceptions

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4212]
**Describe the bug**
Not all exceptions are handled during the posting of a tile (in `views.tile.post()`), resulting in no proper response is sent to the user at the frontend when an exception occurs. The spinner keeps on spinning, with a javascript error happening in the background (`response.responseJSON` in `new-editor.js` is undefined).

**Expected behavior**
The user should always receive some kind of response.

**Your Arches Information**

*   Version used: 4.3.1
*   Operating System and version (desktop or mobile): Ubuntu 16.04 (Docker)
*   Browser Name and version: Chrome

**Comment by chiatt** [comment]
@veuncent I'm going to close this issue because the PR, #5432 has been merged. If you think this ticket is still unresolved please feel free to reopen it.
