### ISSUE TITLE
Unfriendly widget focus on designer

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4236]
In the card portion of the graph designer, whenever I change the focus from one widget to another, the card reverts to the top.  This is probably fine in a card with only one, two, or three widgets, but I have a card with many more than that and therefore the widget that is in focus is scrolled off of the screen.

It would be more natural if the widget in focus came to the center of the screen rather than always scrolling to the the top.

**Comment by chiatt** [comment]
@adamlodge I don't think this is still an issue in arches master. Can you confirm?

**Comment by adamlodge** [comment]
resolved
