### ISSUE TITLE
Adding branch to resource model hangs system

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4239]
When adding a branch to a resource model, the system hangs on the spinny wheel.  Workaround is to just reload the page and the brach imports to the resource model with no problem... but not the best ux.

**Comment by chiatt** [comment]
This does not seem to be the case for all branches. In the disco-data-pkg, I'm able to add `HER Place`, `HER Designation and Protection` and `Right-HER` without issue. However, adding other branches such as `Existence-Precision`, results in a recursion error (`RangeError: Maximum call stack size exceeded`) in the card viewmodel's `isChildSelected` method: https://github.com/archesproject/arches/blob/7da5afc054e664c3c7cc3341464e8c141d35e836/arches/app/media/js/viewmodels/card.js#L33

**Comment by adamlodge** [comment]
meets reqt
