### ISSUE TITLE
D3 error when adding nodes to a branch

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4253]
When editing a branch causes a d3 error to occur: 

`d3.min.js?_dc=4.3.2:1 Error: <g> attribute transform: Expected number, "translate(NaN,NaN) scale(1…".`

D3 isn't needed for branch editing, so we probably just need to handle for this error.

**Comment by whatisgalen** [comment]
Added a branch to a testing resource model with console open and could not reproduce

**Comment by chiatt** [comment]
@whatisgalen You're right, when adding a branch to a resource model you won't see this error. However, you will see it if you create a new branch (independent of a model) and then try to add a node to it.

**Comment by chiatt** [comment]
Not seeing this error in 6.0
