### ISSUE TITLE
Firefox Double Click to Zoom Issue

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#426]
Firefox has a zoom issue within Arches Stable V3. 

Double Clicking within the map window has an unexpected behavior:
![Imgur](http://i.imgur.com/JWZ337e.gif)

This is confirmed on Firefox 44.0.2

**Comment by mradamcox** [comment]
I mentioned this issue at the end of this thread: https://groups.google.com/forum/#!searchin/archesproject/bojan/archesproject/U6cphG5zkFM/nciSLUncCwAJ

**Comment by jmunowitch** [comment]
Thanks @mradamcox. We are testing a few fixes right now, so we should get a proposed fix shortly.

**Comment by mradamcox** [comment]
slick gif, btw

**Comment by jmunowitch** [comment]
Thanks! We will be including instructions on how to create these gifs in the future to make it easier to demonstrate bugs in the future.

**Comment by jmunowitch** [comment]
Upgrading Openlayers from 3.1.1 to 3.2.0 fixed this issue.
This should fix #427, along with #270.
