### ISSUE TITLE
Mobile app is unaware when a project has been deleted on the Arches server

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4267]
Projects persist on a mobile device even after being deleted from the Arches server using the Mobile Survey Manager.  This means that a mobile device user can continue to edit data remotely without realizing their project no longer exists on the server.

There is no mobile device UI to alert a user of this state and its unclear what happens when a user "synchs" a project on the device.

**Comment by chiatt** [comment]
We could submit a request when the app launches or whenever they navigate to the project page to check if any projects have been deleted. 

However, maybe a better solution (but one that would require more planning) would be to use push notifications. I believe that would require sending messages from Arches to a PubSub channel that would then pass the notifications to the user's device. There are services for this such as PubNub, Firebase, or Urban Airship that do this, but of course we wouldn't want to hard code anything into arches that would commit implementers to a particular service. It would be nice to implement something that would allow developers to write an interface to whatever service they like.

**Comment by dwuthrich** [comment]
Most recent version of Arches addresses this issue
