### ISSUE TITLE
Create an issue_template.md and contributing.md to encourage better Issue reports

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#428]
A few good examples:
[ownCloud issue_template](https://github.com/owncloud/core/blob/master/issue_template.md)
[ownCloud contributing](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)
[Aurelia Moser’s Block](https://bl.ocks.org/auremoser/72803ba969d0e61ff070)
[Three.js issue_template](https://github.com/mrdoob/three.js/blob/master/.github/ISSUE_TEMPLATE.md)
[Three.js contributing](https://github.com/mrdoob/three.js/blob/master/.github/CONTRIBUTING.md)
[ansible issue_template](https://github.com/ansible/ansible/blob/devel/.github/ISSUE_TEMPLATE.md)
[ansible contributing](https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md)

**Comment by apeters** [comment]
this is done is it not?

**Comment by jmunowitch** [comment]
Yes, it should be considered done.
