### ISSUE TITLE
Uploaded files get lost after clicking 'Save'

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4301]
**Describe the bug**
Uploaded file links vanish (at random?) after clicking `Save edit`.

Sometimes after I uploaded a file and then try to display them in the frontend, the item has a status 'queued', where I would expect the status to be 'uploaded'. When this happens, the `url` property is also empty. 

**To Reproduce**
This seems to happen when a `Save edit` button appears at random after adding a file.

**Screenshots**
1. Initial form:
![1 initial form](https://user-images.githubusercontent.com/7893339/48674807-9f75ab00-eb50-11e8-9236-c896a2276c84.PNG)

2. After selecting files to upload:
![2 after selecting files to upload](https://user-images.githubusercontent.com/7893339/48674808-a00e4180-eb50-11e8-8709-9895725fb410.PNG)

3a. After clicking `Add`, normal outcome:
![3 after clicking add](https://user-images.githubusercontent.com/7893339/48674810-a00e4180-eb50-11e8-9c6d-dec8e7388609.PNG)

3b. After clicking `Add`, Bug outcome: Random `Save edit` button:
![3 after clicking add 2](https://user-images.githubusercontent.com/7893339/48674809-a00e4180-eb50-11e8-81b0-24e4b2b3815f.PNG)

4. After clicking `Save edit`:
![4 after clicking save](https://user-images.githubusercontent.com/7893339/48674811-a00e4180-eb50-11e8-91ed-dacafeba1aa6.PNG)

5. After page refresh: links to images are dead:
![5 after page refresh links to images are dead](https://user-images.githubusercontent.com/7893339/48674812-a00e4180-eb50-11e8-86d9-9a6a083b0b71.PNG)

6. Resource Report after this bug happened:
![6 resource report after bug](https://user-images.githubusercontent.com/7893339/48674813-a00e4180-eb50-11e8-8e8e-67029b8104dc.PNG)

**Expected behavior**
It seems the `Save edit` should not appear after adding a file to a card with only file nodes.

**Your Arches Information**

*   Version used: 4.3.3
*   Operating System and version (desktop or mobile): Ubuntu 16.04 (Docker)
*   Browser Name and version: Chrome

**Additional context**
See also this discussion on the forum: https://groups.google.com/forum/#!searchin/archesproject/queued%7Csort:date/archesproject/NeUiGw2E7Nw/jVPzrxtyAwAJ

**Comment by veuncent** [comment]
This is now happening quite often on our production server, now that our users are busy entering data

**Comment by veuncent** [comment]
I was able to trigger this by selecting a card with file nodes on the /resource page, then selecting a random other card, and then selecting that first card with file nodes again. 

1. Initial form
![1 initial form](https://user-images.githubusercontent.com/7893339/48983723-d456a480-f0f2-11e8-8f1e-0e65fa27d95d.PNG)

2. After entering data, before clicking 'Add'
![2 after entering data before clicking add](https://user-images.githubusercontent.com/7893339/48983724-d456a480-f0f2-11e8-877b-a539f3b4e86d.PNG)

3. After clicking 'Add'
![3 after clicking add](https://user-images.githubusercontent.com/7893339/48983725-d456a480-f0f2-11e8-8e43-bb022fd321b2.PNG)

4. After clicking 'Save edits'
![4 after clicking save edits](https://user-images.githubusercontent.com/7893339/48983726-d456a480-f0f2-11e8-8dc5-d2ed28aae65f.PNG)

4b. After clicking 'Save edits' - Report page (works as expected)
![4b after clicking save edits - report page works as expected](https://user-images.githubusercontent.com/7893339/48983727-d4ef3b00-f0f2-11e8-9055-d208bb64b8e2.PNG)

5. After clicking a different card
![5 after clicking a different card](https://user-images.githubusercontent.com/7893339/48983728-d4ef3b00-f0f2-11e8-829b-f05e33fecacd.PNG)

6. After clicking the initial (bugged) card again - Now the 'Save edit' button appeared while no edits were made
![6 after clicking the initial bugged card again - now the save edit button appeared while no edits were made](https://user-images.githubusercontent.com/7893339/48983729-d4ef3b00-f0f2-11e8-9ce7-6a52d13eaaed.PNG)

7. After clicking 'Save edits' - The file node is now emptied
![7 after clicking save edits - the file node is now emptied](https://user-images.githubusercontent.com/7893339/48983730-d4ef3b00-f0f2-11e8-9862-57dc57574038.PNG)

7b. After clicking 'Save edits' - Report page - File node is empty there as well and model is no longer displayed -At this point the data is still present in storage
![7b after clicking save edits - report page - file node is empty there as well and model is no longer displayed -at this point the actual file is still present in storage](https://user-images.githubusercontent.com/7893339/48983731-d4ef3b00-f0f2-11e8-89a6-b8d03a9713e5.PNG)

**Comment by chiatt** [comment]
Hey @veuncent I just merged a fix into master. Can you check if you still see this bug?

**Comment by veuncent** [comment]
Great, thanks @chiatt !
I won't be able to test before Saturday I'm afraid.
In the meantime: would this also fix the `Save edits` button appearing while no actual changes were made? That in itself seems pretty harmless, but still should probably not happen.

**Comment by chiatt** [comment]
@veuncent The two issues were actually related. You shouldn't see the `save edits` button appear.

**Comment by veuncent** [comment]
That's awesome, thank you!

**Comment by veuncent** [comment]
Fixed
