### ISSUE TITLE
Name Card Component Bug

### ISSUE THREAD

**Issue by reubenosborne1** [archesproject/arches#4304]
**Describe the bug**
Bug description: When a resource has more than one name entry, editing one of those entries causes the name to duplicate across all the other entries. This seems to be only a glitch in the UI as saving saves the correct values. Please see GIF attached. 

![namecarderror 1](https://user-images.githubusercontent.com/41572010/48843814-206eb580-ed90-11e8-92fe-d11c866f3e6c.gif)

 
I hope the GIF is sufficient evidence, making it any bigger seriously decreased quality. I can provided the original mp4 file. 

**Your Arches Information**

*   Version used: arches v 4.3.3
*   Operating System and version (desktop or mobile): ubuntu 16.04.5
*   Browser Name and version: firefox & chrome
*   Installation: occurs on all my installations and deployments. Including Arcade Lincoln.

**Comment by azaroth42** [comment]
Okay, thanks! Have moved to the validated issues milestone :)

**Comment by reubenosborne1** [comment]
This issue is still present. When editing a record with 2 names, the Test Record below has a historic name card entry and an alternative name card entry. When performing an edit on either name it copies the name across to the other card, can be fixed by refreshing. Also happens with more than 2 name cards. 

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/41572010/65041680-336dfa00-d94f-11e9-9643-5f38536f561b.gif)

* Import to note this only happens on editing a record, not in the initial creation.

**Comment by reubenosborne1** [comment]
Because the above GIF isn't too clear: 


1. A record with 2 or more names (may be other card entries as well) 
![test-names](https://user-images.githubusercontent.com/41572010/65042008-de7eb380-d94f-11e9-8e31-1f8b59e3ac7d.png)

2. Edit the record, TEST NAME 1 >> TEST NAME 1 *edit*. Can see the edit in both card entries. 
![edit_name](https://user-images.githubusercontent.com/41572010/65042012-df174a00-d94f-11e9-8823-955563e6e1b4.png)

3. Hitting refresh to fix and reveal true values. 
![after_refresh](https://user-images.githubusercontent.com/41572010/65042014-e0e10d80-d94f-11e9-9c20-b6ec8b543918.png)

**Comment by chiatt** [comment]
Hey @reubenosborne1, I've merged a fix for this into stable/4.4.x. If you have an instance running that branch, could you verify that it's fixed?

**Comment by reubenosborne1** [comment]
Hi @chiatt I have just switched branches from stable/4.4.2 --> stable/4.4.x... 
Appears to still be present: 


![Screenshot from 2019-10-01 11-40-48](https://user-images.githubusercontent.com/41572010/65955602-6da3c500-e440-11e9-95b3-a916f7fba46b.png)

**Comment by AJ-HistoricEngland** [comment]
We have just run into this bug at version 4.4.1 so I can help test etc

**Comment by chiatt** [comment]
Thanks @reubenosborne1 & @AJ-HistoricEngland. Unfortunately I'm not able to reproduce the bug on the latest version of 4.4.x.  You may need to clear your browser's cache to see the fix (but you've probably already tried that). If clearing the cache doesnt' help, can you verify that there were no issues when pulling the latest from 4.4.x? Line 79 of card-widget.js should look like this:
https://github.com/archesproject/arches/blob/eb1c3ec74580e8774bc2cf91f85e5f9793404027/arches/app/media/js/models/card-widget.js#L79

**Comment by reubenosborne1** [comment]
@chiatt I can confirm this is now fixed on 4.4.x!

**Comment by AJ-HistoricEngland** [comment]
Confirm that this worked for my 4.4.1 project - copying the card-widget.js into the project and inserting the if block and arches require as shown in the commit.

**Comment by chiatt** [comment]
@reubenosborne1 & @AJ-HistoricEngland  - That's great to hear. Thank you both for testing!
