### ISSUE TITLE
Image rendering dependent on case of file extension 

### ISSUE THREAD

**Issue by reubenosborne1** [archesproject/arches#4315]
**Describe the bug**
 Images are not being rendering correctly in reports. It appears that for certain resource models the case of an images file extension determines whether or not it gets rendered. 

Please see attached screenshots. I have the same image but with different file extensions .JPG and .jpg . In Heritage Resource the jpg image fails to render. However in the resource model Cultural artefact with the same two images both render.
In both cases I have increased the max file size well over the size of the two images. 

![heritageresourceimages](https://user-images.githubusercontent.com/41572010/48939069-ff7e9f80-ef0a-11e8-9931-e63d0245e536.png)

![culturalartefactimages](https://user-images.githubusercontent.com/41572010/48939148-3c4a9680-ef0b-11e8-99d6-42b8722f72fb.png)

**Your Arches Information**

*   Version used: 4.3.3
*   Operating System and version (desktop or mobile): Ubuntu 16.04.5
*   Browser Name and version: Chrome 
*   Link to your Arches Install (optional): 

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by azaroth42** [comment]
@reubenosborne1 This /could/ be something for the way that you've got your webserver configured that manages the images? However that they both display in a different report is puzzling.

Seems like a valid issue to be tracked down.
