### ISSUE TITLE
Cannot copy resources when certain cards contain data

### ISSUE THREAD

**Issue by reubenosborne1** [archesproject/arches#4316]
**Describe the bug**
 Please see example below. The copy function works fine until any entries under "condition assessment" are filled. In the example I have filled the condition description with the word testing and receive the copy error "Resource Copy Failed...
Sorry! The copy request failed. Please try again. Contact your system administrator if the problem persists." 

![copyfailed](https://user-images.githubusercontent.com/41572010/48939753-38b80f00-ef0d-11e8-895f-56a7d1b98966.png)

**Your Arches Information**

*   Version used: 4.3.3
*   Operating System and version (desktop or mobile): Ubuntu 16.04.5
*   Browser Name and version: Chrome
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by azaroth42** [comment]
@reubenosborne1 Can you try to provide more details as to when this occurs? It could be model or data related, rather than software. Thanks!

**Comment by reubenosborne1** [comment]
Hi @azaroth42. It appears this has been fixed on the master branch...Thanks!

**Comment by azaroth42** [comment]
Thanks! Closing :)
