### ISSUE TITLE
Limit To Search Result Pages which work

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#4318]
**Describe the bug**
When paginating through results in the right hand search area, it is possible to navigate to the 2000th page (10000 records) and show the results but the request to show results fails on page 2001.  The final page listed in the results pagninator link at the bottom of the results is 54144 and we have no way to turn off the option of clicking on that link.

Is there any way to up the limit so the pagination works for all records?

**To Reproduce**
Have over 10000 records in your Arches instance
1. Open Search
2. Scroll down to the pagination links at the bottom of the search panel
3. Click the end page (must be over 2000) or enter [arches instance]/search?no_filters=true&page=2001 into the browser url bar
4. See the following error at the top of the page: Request Failed...There was an error retrieving the search results

**Screenshots**
![image](https://user-images.githubusercontent.com/38533555/48954398-3a032f00-ef41-11e8-9b40-04f97ef41427.png)

![image](https://user-images.githubusercontent.com/38533555/48954491-99f9d580-ef41-11e8-9957-36941ce5deb1.png)

**Expected behavior**
Results from the final page are visible in the Search Results and no error message appears.

**Your Arches Information**

*   Version used: 4.1.1
*   Operating System and version (desktop or mobile): Windows Server 2016 in Azure
*   Browser Name and version: Chrome 70.0.3538.110  (64-bit)

**Additional context**
We have a total of 270718 resources in the application

**Ticket Background**
*   Found by: @

**Comment by azaroth42** [comment]
Validated that the bug is real.

**Comment by chiatt** [comment]
Likely related to #3440

**Comment by apeters** [comment]
fixed in the latest
