### ISSUE TITLE
Add ability to config widgets on number nodes to display number value with a comma

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4352]
This is a request from Rich for displaying high dollar amounts.

**Comment by adamlodge** [comment]
Two issues:
1. I am finding that using the formatting config causes the number value to revert to "0".
2. The edit that gets applied is set as provisional - even if i'm logged in as admin.

Rename attached txt file json.  It is a model you can use for testing.

[https://app.zenhub.com/files/49451058/5d44b420-0887-44f8-9fd1-6b2a137cc239/download](https://app.zenhub.com/files/49451058/5d44b420-0887-44f8-9fd1-6b2a137cc239/download)

**Comment by chiatt** [comment]
@adamlodge This should be working in the latest.

**Comment by adamlodge** [comment]
@chiatt It's better in that the values I pump in are sticking now, but the full capabilities of numeral.js seem not to be working.  For example, '$0,0.00' doesnt format with the dollar sign.

**Comment by adamlodge** [comment]
resolved
