### ISSUE TITLE
Export User Group Privileges with Resource Model

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4353]
A common use case when developing a models, is to create the model in a dev system, export the model and then implement in a separate production system.

In version 4.3, user groups are pre-defined, and user group privileges are assigned to the resource model as part of the design of the resource model.  Given that, it is intuitive that exporting the resource model could include exporting user group privileges that you have assigned to various nodegroups in the graph.

If that was the case, then it would be easy to transport a model's priveleges from the dev system to production system.  As it currently stands, user privs have to be re-implemented by hand.

**Comment by chiatt** [comment]
Covered by #2779
