### ISSUE TITLE
Scroll Height error when selecting a nav item in the main menu

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4359]
Selecting an item main nav menu (bar on the left) while it is collapsed results in the following browser error: 
```
index.js:149 Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at e.s.show (index.js:149)
    at HTMLAnchorElement.<anonymous> (index.js:79)
    at HTMLAnchorElement.dispatch (jquery.min.js?_dc=4.3.1:2)
    at HTMLAnchorElement.y.handle (jquery.min.js?_dc=4.3.1:2)
s.show @ index.js:149
(anonymous) @ index.js:79
```
This forces the user to click the same option second time in order for the app to navigate to the desired page.

**Comment by whatisgalen** [comment]
this is a known, unresolved bug as of version 3.0.4 of metisMenu: https://github.com/onokumus/metismenu/issues/144

**Comment by dwuthrich** [comment]
meets requirement
