### ISSUE TITLE
Ability to configure cards to enforce creation of unique tiles

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4375]
At present, it is possible on any card with cardinality of n to save tiles containing the same values over and over again. I would like to be able to configure a card  in the card designer to define the set of nodes that must (in combination) be unique to save a tile to the database.  This will impose a uniqueness integrity constraint that prevents entry of duplicate tiles.

**Comment by adamlodge** [comment]
meets reqt

**Comment by adamlodge** [comment]
I noticed a UI bug where this config apprears many times in the card design UI

![Screen Shot 2019-04-03 at 11.45.25 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/662c63ef-fd5a-4f99-8bb6-a8505104fa0e)

**Comment by chiatt** [comment]
@adamlodge In the latest we shouldn't be creating these extra constraint records. However, once these extra constraint records are created they will need to be removed from the app using the django shell or the database.

**Comment by adamlodge** [comment]
The unique constraint appears to work, but Arches is throwing the wrong error message when the constraint is violated. 

![Screen Shot 2019-12-23 at 1.08.13 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/6d745022-90ea-4746-84ee-fb6653c491ad)

**Comment by chiatt** [comment]
@adamlodge Can you take another look at this? I fixed the issued and updated it on qa.archesproject.org

**Comment by adamlodge** [comment]
meets reqt
