### ISSUE TITLE
bug: cant edit values in a tile that has child tile(s)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4383]
To reproduce:

1. Load attached resource model to Arches
2. Add a value to Parent Tile Node
3. Add a value to Child Tile Node
4. Try to edit the value in Parent Tile Node

System will hang

[https://app.zenhub.com/files/49451058/37fe3517-a282-41f9-9afb-07f68fee87b3/download](https://app.zenhub.com/files/49451058/37fe3517-a282-41f9-9afb-07f68fee87b3/download)

**Comment by adamlodge** [comment]
meets requirementr

**Comment by veuncent** [comment]
This may not yet work as expected: when I try to add data to a newly added node in an **existing node group**, the changes don't get picked up and the `Save edits` button does not appear.

**Comment by adamlodge** [comment]
By "existing node group", do mean existing node group instance/tile? Just
trying to replicate properly.

**Comment by veuncent** [comment]
Yes exactly that :) 

So in the resource editor I added some data to a few nodes in the same node group (resulting in a node group instance, if I understand the vocabulary correctly).

Then in the designer I added a new node to the node group. 

Subsequently in the resource editor I tried adding a value to the newly added node. This resulted in the 'Save edits' button not appearing.

**Comment by adamlodge** [comment]
meets reqt

**Comment by apeters** [comment]
if this is fixed, it should be closed

**Comment by chiatt** [comment]
@adamlodge I just tested this and it worked fine for me in the latest.
