### ISSUE TITLE
Update map and file widgets when provisional edits are approved or switched between users.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4384]
In most widgets, when a users approves a provisional edit or switches between available edits, the tile data in the widget immediately updates. This is not the case for the map and file-list widgets making review of these tiles very difficult.

Both widgets need to update when their data values are changed by a reviewer. Hopefully there is a single solution for these problems. If not this ticket should probably be split between issues for each widget.

**Comment by chiatt** [comment]
This issue should now be resolved for the iiif-widget as well.

**Comment by dwuthrich** [comment]
meets requirements.  And its great to see this working!
