### ISSUE TITLE
Make a survey's data related properties immutable once a user has downloaded a project 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4401]
In order to prevent couch data conflicts we need to prevent updating tile data in survey once a user has downloaded a project. We will continue to allow users to modify the:

- end date
- name
- basemap source
- users/groups

Other properties of a survey model will be immutable.

**Comment by chiatt** [comment]
@dwuthrich The lock is applied after the first sync rather than when the project was downloaded to a device.

**Comment by dwuthrich** [comment]
meets requirements
