### ISSUE TITLE
Default empty data field template has trailing "

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4416]
**Describe the bug**

When a resource instance does not have all of its fields populated, the default template tried to render a placeholder "no data" value.  This string has a trailing " character at the end of it that should be removed.

**To Reproduce**

Create a resource instance and leave some fields blank.

**Screenshots**

Note the " after 'No data added yet for Identifier' 

![screen shot 2019-01-11 at 2 36 29 pm](https://user-images.githubusercontent.com/871868/51063148-9207fa80-15ae-11e9-8367-ca608992c30a.png)

**Expected behavior**

No double quotes.

**Ticket Background**
*   Found by: @azaroth42

**Comment by mradamcox** [comment]
looks like this is fixed in master now, but not in 4.4.2.
