### ISSUE TITLE
Placing data nodes in a separate card results in disconnected graph

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4417]
**Describe the bug**

When a data collecting node is put into a separate card in the graph designer, the resulting RDF graph is not connected and thus the serialization drops the disconnected nodes.

**To Reproduce**

Take a model and put nodes in separate cards, then request the JSON-LD serialization.  Note that the data is present in the human readable report, but not the data.

It is present in the graph created by `get_rdf_graph()` but the URIs generated aren't the same.

This is an Acquisition with just one TimeSpan. Note that the timespan URI in the has_time-span property on the root node is `http://localhost:8000/tile/130bec65-38bc-4412-9324-f61660567d84/node/f4194887-c5c8-11e8-b95c-a4d18cec433a` but there are FIVE timespans created with different URIs, as the various tiles are encountered.

```
<http://localhost:8000/resources/3115b314-edd1-11e8-be57-a4d18cec433a> a ns1:E8_Acquisition ;
    rdfs:label "Acquisition of \"The poppy field\"" ;
    ns1:P2_has_type <http://vocab.getty.edu/aat/300417642> ;
    ns1:P4_has_time-span <http://localhost:8000/tile/130bec65-38bc-4412-9324-f61660567d84/node/f4194887-c5c8-11e8-b95c-a4d18cec433a> .

<http://localhost:8000/tile/11b97cc3-4ac7-4747-97fa-c2c71d2e2bd6/node/f4194887-c5c8-11e8-b95c-a4d18cec433a> a ns1:E52_Time-Span ;
    ns1:P83_had_at_least_duration <http://localhost:8000/tile/11b97cc3-4ac7-4747-97fa-c2c71d2e2bd6/node/f4194fc0-c5c8-11e8-8b92-a4d18cec433a> .

<http://localhost:8000/tile/43725511-29a5-49fb-82d0-6aaa36e44ec0/node/f4194887-c5c8-11e8-b95c-a4d18cec433a> a ns1:E52_Time-Span ;
    ns1:P84_had_at_most_duration <http://localhost:8000/tile/43725511-29a5-49fb-82d0-6aaa36e44ec0/node/f41968ae-c5c8-11e8-a72f-a4d18cec433a> .

<http://localhost:8000/tile/80c66ac9-f448-42ea-bd10-354bd64da4cd/node/f4194887-c5c8-11e8-b95c-a4d18cec433a> a ns1:E52_Time-Span ;
    ns1:P82a_begin_of_the_begin "1891-04-04"^^xsd:dateTime .

<http://localhost:8000/tile/faef6e53-18db-4900-b99e-6f971c679fb6/node/f4194887-c5c8-11e8-b95c-a4d18cec433a> a ns1:E52_Time-Span ;
    ns1:P82b_end_of_the_end "1891-04-04"^^xsd:dateTime .

<http://localhost:8000/tile/11b97cc3-4ac7-4747-97fa-c2c71d2e2bd6/node/f4194fc0-c5c8-11e8-8b92-a4d18cec433a> a ns1:E54_Dimension ;
    rdfs:label "None" ;
    ns1:P90_has_value 1 ;
    ns1:P91_has_unit <http://vocab.getty.edu/aat/300379242> .

<http://localhost:8000/tile/130bec65-38bc-4412-9324-f61660567d84/node/f4194887-c5c8-11e8-b95c-a4d18cec433a> a ns1:E52_Time-Span .

<http://localhost:8000/tile/43725511-29a5-49fb-82d0-6aaa36e44ec0/node/f41968ae-c5c8-11e8-a72f-a4d18cec433a> a ns1:E54_Dimension ;
    rdfs:label "None" ;
    ns1:P90_has_value 100 ;
    ns1:P91_has_unit <http://vocab.getty.edu/aat/300379242> .

<http://vocab.getty.edu/aat/300417642> a ns1:E55_Type ;
    rdfs:label "purchase (method of acquisition)"@en .

<http://vocab.getty.edu/aat/300379242> a ns1:E58_Measurement_Unit ;
    rdfs:label "days (units of time)"@en .
```

**Screenshots**

And this is what it looks like in the UI:

![screen shot 2019-01-11 at 3 06 54 pm](https://user-images.githubusercontent.com/871868/51064170-2ecc9700-15b3-11e9-833c-9521028f6b57.png)

**Expected behavior**

Only one timespan, linked from the root node.

Tagging: @benosteen  and @robgaston

**Comment by benosteen** [comment]
Question: 
 - if the "tile/{UUID}" is removed from the URI, does this lead to false equivalence? ie does a node/{UUID} match conceptually to what becomes an RDF node?

**Comment by azaroth42** [comment]
I believe it would then collide when there are multiple instances of the same branch.  e.g. if there were two timespans, the node/X would be the same. Can someone verify?

**Comment by azaroth42** [comment]
From our discussion today:

![screen shot 2019-02-06 at 11 51 40 am](https://user-images.githubusercontent.com/871868/52358254-a8667200-2a05-11e9-934a-ae9e4ec664ba.png)

The key to producing a model that exhibits this behavior is to have a semantic node that is NOT the top node, which are in separate cards. The most reasonable use for this is when there is a cardinality of 1:n followed by a cardinality of 1:n, such as whole object has many parts of object, and each part has many dimensions in the screenshot above. These thus have Allow Multiple Values turned on for the cards. This then happens when there are both data collecting and semantic nodes at the same level - in this case `label` and `dimension` within the `Part` object.

If preview of the graph is easier to see:

![screen shot 2019-02-06 at 11 54 41 am](https://user-images.githubusercontent.com/871868/52358464-07c48200-2a06-11e9-883f-7c721430f4d6.png)

**Comment by azaroth42** [comment]
This is fixed in the most recent branch, thank you to @apeters @robgaston and @benosteen !
