### ISSUE TITLE
Allow setting to control language tags in JSON-LD labels or not

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4418]
**Is your feature request related to a problem? Please describe.**

Language tags are only available for data imported via SPARQL from AAT. This makes them very inconsistent in their applicability, and thus utility.  Currently they're coded to be output (as they should be) in the JSON-LD, but it results in a poor developer API.

**Describe the solution you'd like**

Add a setting in settings.py to turn this functionality off, and only emit a string for the label without the language tag.

tagging @benosteen @robgaston 
Related to #4344

**Comment by azaroth42** [comment]
For reference, my local fix is just to take the `lang=c.language` parameter out of the call to `Literal()`

**Comment by benosteen** [comment]
Currently, the Literal is formed without a language tag, given the paucity of language identification for the term. This issue could likely be closed and a new issue opened if the need to tag the Literal values is found?

**Comment by azaroth42** [comment]
:+1: Agreed, closing.
