### ISSUE TITLE
Tiles do not validate on save via UI

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4451]
Tiles are only validated currently on import; we should also be validating tiles (ie validating values as per datatype) when they are saved via the UI (`arches/views/tile.py`).

**Comment by robgaston** [comment]
We should add exception based validation for save via the UI, API, and mobile app sync

**Comment by apeters** [comment]
@robgaston was the intent of this ticket to reflect back to the UI that a tile that contained invalid data was submitted?  Right now I can see on the server that the validate method was triggered during save, but nothing is reflected in the UI when this happens.

**Comment by apeters** [comment]
This looks good to me.  I like the error thrown to the UI.
