### ISSUE TITLE
Improve click and drag interaction in editor tree

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4454]
Currently, in the editor tree:
- dragging a card causes the parent tile to drag (we should prevent event propagation here)
- dragging a tile does not result in that tile being selected
- selecting a node does not expand that node

**Comment by mradamcox** [comment]
I wanted to add to this, I have often found it very difficult to turn on and off map overlay layers by clicking them, but because the drag is so sensitive. It's easy to drag the layer a tiny bit instead of getting a clean click on it.

**Comment by adamlodge** [comment]
Way better! Thanks!
