### ISSUE TITLE
Default Search button location is unintuitive

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4456]
Rich made the point that after making edits to his resource models, he wanted to go back to main map screen (the search page) to do more dispaly and editing.  It was not at all obvious to him that the magifying glass on the upper left was the button to push.  Instead, he was looking in the panel on the left where all of the other tools, plugins, etc... are located.  

I would propose adding a way to access the search button on the left panel.

**Comment by azaroth42** [comment]
I have frequently wondered how to get to search before remembering that it's the magnifying glass in the top right. So :+1: to the issue.

**Comment by adamlodge** [comment]
meets reqt
