### ISSUE TITLE
Mobile Survey Manager UI enhancements

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4462]
The MSM UI still requires the following enhancements before it's complete:

1. Fix account summary panel.  The panel should always show user name, user email, and last synch labels.  If no user name or email exist for an account, the UI should display "Not Set".  If the the user hasn't synched data yet, the UI should display "No Data Synched".  Remove the "no user name", "no user email" labels.

2. When selecting data to download, any models that have already been added to the survey should automatically be selected

3.  Add a status panel in the report for the state where the user has activated the survey and saved it.  This panel should state that the survey is now active.

4. Add a CSS class called "incomplete" to the mpm-card-content div when the survey status is incomplete.  Add a class called "ready" when the survey is complete and toggled active (but not saved), and a class called "active" when the survey is complete, toggled active, and has been saved.

**Comment by chiatt** [comment]
re #4437
