### ISSUE TITLE
Error syncing tiles whose resource instance has been deleted from the web app. 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4463]
If a user tries to sync a tile of a resource instance that has been deleted from they system, their sync will fail with the error:  `DoesNotExist: ResourceInstance matching query does not exist.`

**Comment by chiatt** [comment]
For the time being we are skipping sync of these tiles. Ultimately we want to delete them from couch.

**Comment by dwuthrich** [comment]
meets requirements
