### ISSUE TITLE
Delete/read/write privileges need to be enabled in api to support the mobile app

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#4472]

**Comment by apeters** [comment]
https://github.com/archesproject/arches/blob/master/arches/app/views/auth.py#L218

**Comment by apeters** [comment]
see #4423

**Comment by chiatt** [comment]
@apeters I noticed that top level cards are getting filtered by permissions, but lower level cards, if a user is allowed to edit the parent card, are not filtered even if they are fully restricted for the user.

**Comment by chiatt** [comment]
It turned out that my test user belonged to only the Crowdsource Editor group, but still had superuser status which was causing the issue that I saw. Once I removed that status, the cards were filtered as expected.
