### ISSUE TITLE
get_preflabel_from_conceptid fails in test suite environment

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#4480]
**Describe the bug**
I have written an import rdf unit test for the case where only a Arches Concept URI is passed as the concept with no label string to the `from_rdf` method on the concept datatype. The datatype code uses 'get_preflabel_from_conceptid' from arches.app.models.concept which attempts to look up the concept id in the elasticsearch index, given a language (or a None)

In the test suite, I use SKOSReader to load and save the concepts from a fixture thesaurus. However, get_preflabel_from_conceptid returns "" for the id (and all other fields too - the default) when run from a unit test. Importing the fixture file through the Arches RDM UI and then issuing the same command through a django shell works as expected and returns the correct result.

**To Reproduce**
1. Add this unit test to `tests/exporter/resource_export_tests.py` in the 'benosteen-4186_jsonld_export' branch:  https://gist.github.com/benosteen/594fe8177fa34ff5e57ff53d6ed2bba5
2. Get into the Arches environment and run that specific suite: 
`python manage.py test tests/exporter/resource_export_tests.py --settings="tests.test_settings"`
3. Result:
```
======================================================================
FAIL: test_jsonld_concept_match_no_label (tests.exporter.resource_export_tests.RDFExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/web_root/arches/tests/exporter/resource_export_tests.py", line 372, in test_jsonld_concept_match_no_label
    self.assertTrue(resp == "43d75450-7282-4754-af63-02e13032b73a")
AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
Trying to get a label from the concept node.
Using just the concept_id: '86be632e-0dad-4d88-b5da-3d65875d6239'
{'category': '', 'conceptid': '', 'language': '', 'value': '', 'type': '', 'id': ''}
```
Note how it successfully determines the concept UUID, but fails to find a matching prefLabel for it.

However, it succeeds outside of the test environment:
1. Load `tests/fixtures/data/rdf_export_thesaurus.xml` through the RDM web UI
2. Command line:
```
(ENV) root@f16ecbbae26f:/web_root/arches# python manage.py shell
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from arches.app.models.concept import get_preflabel_from_conceptid
>>> get_preflabel_from_conceptid("86be632e-0dad-4d88-b5da-3d65875d6239", lang=None)
{u'category': u'label', u'conceptid': u'86be632e-0dad-4d88-b5da-3d65875d6239', u'language': u'en-US', u'value': u'Painting', u'top_concept': u'31fa01c9-3f64-4b60-8e91-5ea253dd51f5', u'type': u'prefLabel', u'id': u'43d75450-7282-4754-af63-02e13032b73a'}
>>>
```

**Your Arches Information**
*   Version used: https://github.com/archesproject/arches/tree/benosteen-4186_jsonld_export

**Comment by azaroth42** [comment]
@robgaston Blocking API testing implementation, please can you take a look?

**Comment by robgaston** [comment]
@benosteen @azaroth42 My sense is that this is an issue w/ the test fixtures as used.  Are you sure that the concept you are referencing is being loaded into your test database?  It sounds like you may be expecting the data in your arches database to be available in the test database, which is not necessarily the case.  The test database is deployed separately and only has the fixtures that are loaded for testing, so you may need to amend that with the concepts that your tests expect.

**Comment by benosteen** [comment]
https://github.com/archesproject/arches/blob/benosteen-4186_jsonld_export/tests/exporter/resource_export_tests.py#L125

The setUp for the test suite loads the data into the database, or I presume this is the case as the other tests that depends on the concepts from the fixtures existing there are passing.

Taking this same set of SKOS information and importing it (as I detailed above) lets me successfully run the call that is failing in the test.

**Comment by apeters** [comment]
@benosteen can you confirm that "test" ES indexes are being created and that they are populated with the appropriate concept data?
