### ISSUE TITLE
Code in export rdf functionality is never called - dead? or a bug?

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#4481]
**Describe the bug**
There is a section of the code in the rdf export functionality that I added an exception to, to see what situation would cause it to run. So far, I have not discovered any fixture or circumstance that causes this exception to be thrown. I left it in when I rewrote how the tile data for these edges where handled.

https://github.com/archesproject/arches/blob/master/arches/app/utils/data_management/resources/formats/rdffile.py#L144

Either the code (and related functionality above it) is not needed any longer as it was added to deal with some edge cases to do with how Arches used to work, or that it should be running, which may be causing odd to trace errors in other ways.

**Expected behavior**
That there is a reason for this code to run. It is quite low-level and I am not sure I fully understand how it would be used.

**Comment by azaroth42** [comment]
Meta question: Suggests a `refactor` label, on the same level as `bug` and `enhancement` ?

**Comment by azaroth42** [comment]
Is this still true with recent updates?

**Comment by benosteen** [comment]
Nope
