### ISSUE TITLE
Fix card order in msm

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4487]
Currently the card order in the msm is not preserved when a user saves a survey. This can result in cards being unpredictably ordered in the mobile app. By default, cards should follow the order they are in in the graph designer. re archesproject/arches-mobile#305

**Comment by apeters** [comment]
This still seems broken to me.  I updated an existing graph in a mobile survey by re-ordering both the cards and the nodes, but neither of those edits seem to get down to the mobile app itself.

**Comment by chiatt** [comment]
@apeters If you change the graph you would need to resave the survey with those changes. The MSM card order is independent of the graphs card order once the survey is saved.
