### ISSUE TITLE
Sync history edit count should reflect the number of instances edited, not tiles

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4521]
In the msm summary, the edit could should read “resource(s) edited”

**Comment by dwuthrich** [comment]
@chiatt It appears that newly created resource are not reflected in the "resources edited" count

**Comment by chiatt** [comment]
@dwuthrich Did you see this on a survey on the QA machine?  I just tested locally with a couple of surveys and new instances are updating the count.

**Comment by dwuthrich** [comment]
meets requirements
