### ISSUE TITLE
Keep multiselect dropdown open for user and group dropdowns in the MSM

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4522]
Keep multiselect dropdown open for user and group dropdowns in the MSM so that users can select multiple items before the dropdown closes.

**Comment by robgaston** [comment]
this can be done using the `closeOnSelect` property documented here: http://select2.github.io/select2/#documentation

**Comment by dwuthrich** [comment]
The widget does not render properly after user makes a selection, as shown in the screen shot.  Note how the selection panel floats below the dropdown
![screen shot 2019-02-07 at 2 52 58 pm](https://user-images.githubusercontent.com/815185/52448274-3d419c00-2ae8-11e9-8360-c6beb7817324.png)

**Comment by dwuthrich** [comment]
meets requirement
