### ISSUE TITLE
MSM: Style of tree for new surveys is broken

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4533]
Note that the root node of the survey tree is not styled properly until user supplies a survey name.  Survey should have a default name to avoid this problem![Screen Shot 2019-02-07 at 2.55.43 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/c75bc48a-27db-4184-8fb7-2683c6a8255d)

**Comment by chiatt** [comment]
Looks great
