### ISSUE TITLE
Authentication is confused when running two instances on one host

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4541]
**Describe the bug**

When running two instances of Arches on the same host, authenticating to one instance as admin logs the other instance out.

**To Reproduce**

Start up two instances with separate elastic and postgres databases, one on :8000 and one on :8001.

Login to one as admin, log in to the other as admin _in the same browser_, and then try to do something back in the first instance. It will redirect back to the login page.

**Comment by mradamcox** [comment]
@azaroth42 I believe this is the setting I've used in the past to fix this: https://docs.djangoproject.com/en/1.11/ref/settings/#session-cookie-name. I think it would be reasonable to put this setting in a new project's settings, and make it something like APP_NAME + "session", etc.

**Comment by azaroth42** [comment]
And we can just put that into settings.py?

`SESSION_COOKIE_NAME = "session_linked_art_arches"`

Or somesuch?

**Comment by mradamcox** [comment]
yes, I just looked at my old notes for running multiple Arches 3 apps on a single domain, and I just used

    # unique session cookie ensures that logins are treated separately for each app
    SESSION_COOKIE_NAME = PACKAGE_NAME

so you can do whatever you want with that variable.

**Comment by mradamcox** [comment]
@azaroth42 Just wanted to check in, is this still an issue?

**Comment by azaroth42** [comment]
The SESSION_COOKIE_NAME seems to have solved it. If that's documented somewhere, I think we can close this.

**Comment by mradamcox** [comment]
Ok. Maybe the better resolution would actually be to just put

    # unique session cookie ensures that logins are treated separately for each app
    SESSION_COOKIE_NAME = PACKAGE_NAME

in the default settings.py file. @apeters do you think that would cause any issues?

We don't currently have a docs section about simultaneously running multiple Arches instances on the same domain, and it seems like kind of an edge case, but we could add it eventually.

**Comment by apeters** [comment]
@mradamcox this seems like a good solution.  @chiatt could we put this setting into our project template?

**Comment by chiatt** [comment]
@apeters Yeah - I'll go ahead and do that and merge it into 4.4.x and master.

**Comment by mradamcox** [comment]
@cyrus this looks good to me.
