### ISSUE TITLE
shebang line should come first in manage.py

### ISSUE THREAD

**Issue by beatboxchad** [archesproject/arches#4545]
**Describe the bug**
The Arches copyright notice appears before `#!/usr/bin/env python` in `manage.py`. This breaks execution of the script directly, which some software (such as Ansible's django_manage module) relies upon.

**To Reproduce**
1. Create an Arches project
2. In your project directory, `chmod u+x ./manage.py`
3. Try to execute it: `./manage.py es install`
4. See bash try to execute python:
```
(arches) chad@localhost:~/code/arches_projects/arches_4_3_x$ ./manage.py es install
./manage.py: line 17: 
ARCHES - a program developed to inventory and manage immovable cultural heritage.
Copyright (C) 2013 J. Paul Getty Trust and World Monuments Fund

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
: No such file or directory
./manage.py: line 21: import: command not found
./manage.py: line 22: import: command not found
./manage.py: line 25: syntax error near unexpected token `"DJANGO_SETTINGS_MODULE",'
./manage.py: line 25: `    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "arches_4_3_x.settings")'
```

**Expected behavior**
Invoking `manage.py` directly should work.

**My Arches Information**
*   Version used: 4.3.3
*   Operating System and version (desktop or mobile): Ubuntu 18.04
*   Browser Name and version: n/a

**Ticket Background**
*   Found by: @beatboxchad

**Comment by mradamcox** [comment]
@beatboxchad I'm not sure how this could work without anticipating the path to a user's virtual environment.

**Comment by beatboxchad** [comment]
@mradamcox following the standard practice, the shebang line `#!/usr/bin/env python` uses `env` to invoke python, which means whatever virtualenv is activated will be used.

**Comment by mradamcox** [comment]
@beatboxchad Nice, just read up more on the virtualenvs and shebang and you're totally right. I realize now that where I have altered the shebang to /path/to/my/env in prep for ansible, I could have put the generic /usr/bin/env path in, and that would ensure that the virtualenv that gets passed directly to the ansible django_manage command gets used, even though it's not in the shebang itself.

**Comment by chiatt** [comment]
I've moved the shebang line to the top.
