### ISSUE TITLE
resource-instance branch matching fails for multiple models

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4564]
**Describe the bug**

If there is a branch with a resource-instance datatype configured to allow multiple models, then the class of the resource-instance datatype is the super-class of the allowable models.  When the findBranch() function runs, it does a non-ontology-aware check of the branch's expected class to the incoming data's class. When it is not an exact string match, it fails.

Instead, it should check the classes of the resource-instance models to see if any of them match, in order to see if the data matches the branch. This was described in the Algorithm documentation:

> 	If the range in the model is a resource-instance, then check that the incoming node has the **same class as the top node of any of the referenced models**. If more than one model has the same top level class, then fail as the model is ambiguous. If there is exactly one possible model, then accept that node.

**To Reproduce**

* Create a Person model with the class Person
* Create a Group model with the class Group
* Create a model for a ManMadeObject that has a current owner which is a resource-instance and class Actor, with two possible models - either a Person or a Group.
* Try to create an instance of the ManMadeObject via the import API, with data that refers to either a Person or a Group rather than an Actor.

**Expected behavior**

Expected behavior is per the algorithm -- to check the referenced resource models classes, not the local ontology class

**Comment by azaroth42** [comment]
Verifying that this issue still exists.

**Comment by azaroth42** [comment]
Configuration and script to reproduce: 
[4564-reproduce.zip](https://github.com/archesproject/arches/files/3510708/4564-reproduce.zip)

**Comment by apeters** [comment]
@azaroth42 I imported the models and ran the script without issue.  Is an error supposed to be thrown?

**Comment by apeters** [comment]
Ok, I see the errors in the error log now.  Sorry about that.

**Comment by azaroth42** [comment]
Tests in place, now needs solution :)

**Comment by azaroth42** [comment]
The test for 4564 export still fails.

**Comment by azaroth42** [comment]
Agree fixed, closing
