### ISSUE TITLE
Design question: accessibility of read-only cards

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4570]
A design question falling out of work on #4535: 
Should users with read-only privs on cards higher in the tree and read-write privs on cards deeper in the tree be able to click on the read-only cards?  They should clearly be able to click on the tiles that have been generated from the cards (by other users), but it is unclear whether the cards themselves should be accessible given the function of a card is to add or edit data.

**Comment by dwuthrich** [comment]
Yes, I think users should be able to click on and read cards for which they have read-only privileges.

**Comment by adamlodge** [comment]
resolved
