### ISSUE TITLE
Arches should cache json-ld context files

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4575]
When importing an instance via JSON-LD, the system tries to download the context that is referred to in the incoming data in order to turn the JSON into the graph that it represents.  It does this for *every* incoming instance, resulting in hammering the context server for data that it has only just retrieved moments before.

Instead, it should use a document loader to cache the resource for a certain amount of time and use the cached version instead.

**Comment by azaroth42** [comment]
As a point of comparison, a single very simple record with a context takes 2.5 seconds to import. The same process with the data expanded (e.g. no context) takes 0.21 seconds.

Caching would not improve the performance all the way to the factor of 10, but would certainly make a significant difference.

**Comment by apeters** [comment]
this might give us some insight on how to achieve this:
https://github.com/jakearchibald/web-platform-tests/blob/master/annotation-vocab/tools/vocab_tester.py

**Comment by azaroth42** [comment]
Heh. Note the original author of that piece of code in the header block ;)

It's not hard to do -- it just needs the document loader to be overridden to read for disk by preference rather than from the network.

**Comment by apeters** [comment]
@azaroth42 you mention that there are some issues to work out on your side first.  What are those?

**Comment by azaroth42** [comment]
The issue is minor -- it's whether the context currently has the right headers for web caching or not. This doesn't prevent it from being cached, just that it might not be cached appropriately in a vanilla web cache environment.

**Comment by azaroth42** [comment]
Solution in #5858 is good for in-memory caching, but doesn't persist between instantiations. In a web server environment, will this still require a call for every request to either GET or POST via JSON-LD or will it sit in memory indefinitely?  For apache, I think it will be retrieved once per apache thread's lifespan?

 It would be good to:

* Check for a context as part of the ontology package to avoid any network overhead
* Persist a retrieved context ... somewhere. To a table in postgres with its URI and date of retrieval?
* Have a UI to manually clear a retrieved context (forcing a refresh to occur next time it's needed)
* Optionally, periodically refresh contexts (once a week, thus needing the date of retrieval?)

And to update on the internal question -- we do pass the right headers for caching of documents (at least we do since December when they were fixed) but the underlying PyLD implementation doesn't use them anyway.

**Comment by benosteen** [comment]
Would wrapping the get_context function in something like a
@functools.lru_cache
wrapper be a stopgap for this? Ideally it would be in the pyld
implementation for the function I'd think.

**Comment by apeters** [comment]
@azaroth42  since the document loader is initialized when the "rdffile.py" module is imported, it should only be imported once and therefore apply while the server is running.  It would only be reinitialized if the server were restarted.  

So it should work across web requests. 

The only issue then is that the cache becomes stale.  We could do something clever like refresh the cache after a certain period of disuse and that way requests happening in close proximity (in time) to one another would use the cache, but if the last time the cache was accessed was over (say a week/month/etc...) then we pull a fresh copy from the web.

**Comment by azaroth42** [comment]
That's good, that it would only refresh with a server restart. 

In my comment above, I think there's a couple of options for the cache refresh -- if it doesn't need to be persisted to disk, then just a setting for cache refresh periodicity :)

**Comment by azaroth42** [comment]
This is closed by 5884.
