### ISSUE TITLE
Mobile App: Back button in the editor should always move the user back up the form tree

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4579]
Currently, when accessing an instance editor from the resource report, pressing the back button (upper left, located next to the instance identifier) returns the user to the report.

Desired behavior:
Pressing the back button should move the user up the card tree to either the new resource page or instance list page (depending on where the user initiated the edit session).

**Comment by robgaston** [comment]
Issue moved to [archesproject/arches-mobile #436](https://github.com/archesproject/arches-mobile/issues/436) via [**ZenHub**](https://www.zenhub.com/)
