### ISSUE TITLE
Arches Application on Web Server is not Used When Authenticating from Mobile App

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#4585]
**Describe the bug**
I recently noticed that even though there was no application created on an Arches deployment, as documented here (https://arches.readthedocs.io/en/latest/api/#authentication), I was still able to connect via the mobile app.

The deployment in question is the qa machine that Farallon members have set up. Even as of this writing, visiting the /o/applications page on that server shows:
![image](https://user-images.githubusercontent.com/10427268/52974375-e3ae5c80-3386-11e9-8a65-07ab867f99cf.png)

I have been able to connect to this server from the mobile app with my user credentials, even though there are no applications defined.

Final note is that I can't guarantee that there was not an application on the web deployment at the time I initially connected to it, as I know that the qa server db is deleted and remade now and then. So it's possible that my initial connection was made while there was an application, but certainly now the connection persists, even though there is no application.

**Your Arches Information**

*   Version used: 4.4.x
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Ticket Background**
*   Found by: @mradamcox

**Comment by chiatt** [comment]
Hey @mradamcox, it looks like there is currently an application on the qa machine (http://qa.archesproject.org/o/applications/1/). I have been managing that machine and have not deleted or created any applications since the one that is currently available on the machine. The client id in `o/applications/1` is the same as what listed in the settings.py file.

**Comment by chiatt** [comment]
I just changed the owner of the application to admin, so that the admin user can see/manage the application.

**Comment by mradamcox** [comment]
Oh, interesting, thanks for checking that out, glad it was an easy fix. It's definitely confusing because the message in the screenshot above does not make it clear (or really even hint at the fact) that applications are user-specific.
