### ISSUE TITLE
Mobile Survey Nomenclature Changes 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4591]
The following changes should be made in the mobile survey manager:

- Arches Mobile -> Arches Collector
- Mobile Survey Manager -> Arches Collector Manager
- synch -> sync
- survey -> project

**Comment by mradamcox** [comment]
also:
synched -> synced

**Comment by mradamcox** [comment]
I will change "survey" to "project" in all of the in-app help for the Arches Collector Manager.

**Comment by mradamcox** [comment]
Also, urls should be changed.

**Comment by chiatt** [comment]
Good point. Thanks @mradamcox

**Comment by dwuthrich** [comment]
meets requirements
