### ISSUE TITLE
Indicate in the graph designer and resource editor which cards participate in the descriptor function

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4596]
It would be great if there were some indication as to which cards participate in one or more descriptor functions as these are often key tiles that a user wants to be sure to create.

**Comment by chiatt** [comment]
This would be useful in the Collector manager to help users select the descriptor cards for a mobile project. If we update the resource instance widget to allow the creation of new instances, it would also help a user in the widget configuration to identify those cards that need to be completed in order to recognize a newly created instance.

**Comment by dwuthrich** [comment]
meets requirements
