### ISSUE TITLE
A default report template improvements

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4613]
The default report template has a gray element between the title bar and the report content. The report content is immediately below it without any space making it look a bit awkward. The gray element should perhaps be white providing space between the content and the title bar. ![Screen Shot 2019-02-22 at 5.53.43 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/ede9b970-b788-4148-bd7a-a77aeac7152a)

**Comment by whatisgalen** [comment]
this is a known, unresolved bug as of version 3.0.4 of metisMenu: https://github.com/onokumus/metismenu/issues/144

**Comment by chiatt** [comment]
meets requirements
