### ISSUE TITLE
Provisional edits from mobile do not appear in edit history 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4619]
Provisional edits from mobile do not appear in edit history and provisional user name does not appear in edit log.

**Comment by dwuthrich** [comment]
@chiatt There's an issue with multiple tiles getting passed as a single edit into Arches provisional editor panel

**Comment by chiatt** [comment]
Hey @dwuthrich, I think this should be working properly now.

**Comment by dwuthrich** [comment]
meets requirements
