### ISSUE TITLE
Improve postgres version check during setup

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4642]
There is a postgres version check during the arches install that checks for version 9. Currently arches is supported by at least 9 through 11.

**Comment by chiatt** [comment]
For the 4.4.1 release I disabled the version check to prevent an error during installation from pip.

**Comment by apeters** [comment]
Do we want to have a check anymore?

**Comment by chiatt** [comment]
@apeters I don't think we need to check. It seems like enough to keep our docs updated to inform admins of the proper requirements.

**Comment by apeters** [comment]
meets requirements
