### ISSUE TITLE
Identify candidate task queue and message broker options for task management in Arches

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4666]
Celery as a task queue with RabbitMQ as the message broker seem to be likely candidates, but would it make sense to use alternative technologies (e.g. Redis instead of Rabbit)? We should produce a list of possible technologies for discussion.

**Comment by chiatt** [comment]
Worth looking into: http://policystat.github.io/jobtastic/

**Comment by apeters** [comment]
https://denibertovic.com/posts/celery-best-practices/

I think at this point, Celery seems like our best bet.  It's very well documented and sets the standard as far as Python integration goes.

As far a what broker to use (Rabbit MQ, redis, etc...) Arches should allow an admin to make that choice.  In fact Arches should, as much as possible, be agnostic of the task manager it uses to manage long running/memory intensive tasks. 

Redis vs. RabbitMQ: https://www.linkedin.com/pulse/redis-vs-rabbitmq-message-broker-vishnu-kiran-k-v

**Comment by chiatt** [comment]
So far there haven't been any objections to this strategy so I'm closing this ticket.
