### ISSUE TITLE
Create a workflow step for creating geojson tiles

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4670]
@chiatt commented on [Wed Mar 06 2019](https://github.com/archesproject/consultations-pkg/issues/1)

The consultations workflow will have a map widget similar to the core arches widget but with a task panel and geometries list and refactored controls. ![Screen Shot 2019-03-06 at 11.43.13 AM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/24b79369-41ba-4417-9148-aa973d268b9f)

**Comment by chiatt** [comment]
Some of the UI for this component is being done as part of archesproject/consultations-pkg#6, but in the meantime a developer could start on the task and geometry lists.

**Comment by dwuthrich** [comment]
meets requirements
