### ISSUE TITLE
Refactor related resources

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4678]
Currently the related resources page in Arches only represents relationships between resource instances and not those between a tile of an instance and another instance. These tile to instance relationships should also be represented in the UI.

**Comment by adamlodge** [comment]
I thought I wrote a ticket for this some time ago, but I cant seem to find it.  There are some broader design questions here, like:

1> Is it desirable to have "related resources" now that we have resource-instance data type?  I think that I would argue no, but there is definitely room for debate on that.

2> If we are to keep both flavors of instance relationships for some reason, should they be differentiated in the related resources ui in a specific way?

...and probably other questions too.  Use cases welcome.

**Comment by chiatt** [comment]
There definitely needs to be more discussion about this ticket, but for now I wrote it so that both types are included. It would be really disruptive to force existing implementations to modify their schemas to support the newer resource instance type. I think both can coexist peacefully.

**Comment by mradamcox** [comment]
@adamlodge Here's the ticket you wrote https://github.com/archesproject/arches/issues/3121 I remember commenting on it.

**Comment by chiatt** [comment]
Closing because of the implementation of bi-directional instance relationships
