### ISSUE TITLE
Create tabbed report template

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4684]
Create a report template with cards organized under tabs. Consult with @ryan86 as this may be able to leverage work from another project.

<img width="1192" alt="screen shot 2019-03-06 at 3 32 56 pm" src="https://user-images.githubusercontent.com/1877663/53921474-61c85f80-4025-11e9-8924-218f14acb01f.png">

**Comment by dwuthrich** [comment]
@chiatt Just to be clear: the tabs in the report template do not necessarily correspond to workflows or steps in workflows.  They're just tabs that happen to be styled in a similar way to tabs in a workflow.

**Comment by chiatt** [comment]
@dwuthrich Ah, got it. I've updated the description.

**Comment by chiatt** [comment]
Per a conversation with @dwuthrich, tab list should be sortable and confirm that changes to tab configs are dynamically updated in the preview report.

**Comment by dwuthrich** [comment]
meets requirements
