### ISSUE TITLE
Allow a callback to be passed to the tile model's save method.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4693]
Developers may need to perform some action after a tile is saved such as navigate to a different card. The save method currently takes a callback to handle errors if save fails, but does not have a parameter for a successful save.

**Comment by chiatt** [comment]
Hey @robgaston - giving this to you for QA. There isn't much to test here, but maybe you could glance at the code and see if there might be a better or more flexible way to approach this. I implemented it to support creating a parent card and navigating to a child card with one click event (which I used in a custom card component).

**Comment by robgaston** [comment]
@chiatt I think this is fine ATM, as it's what we've already done for failure handling; we might refactor this to use promises though, which should allow a user to implement logic w/o having to handle callbacks in the tile save code
