### ISSUE TITLE
Add Resource Type icons to Related Search dropdown menu

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4698]
**Is your feature request related to a problem? Please describe.**
In the Related Resources search bar only resource names are shown, but some users use the same names in e.g. a heritage site resource and the 3d model resources related to it, so in the search dropdown you would not be able to distinguish between them.

**Describe the solution you'd like**
Having e.g. the resource type icon in that search dropdown would make a big difference.

**Additional context**
This idea came from feedback from Arches users @ Global Digital Heritage.

**Comment by chiatt** [comment]
Resolved under #8303
