### ISSUE TITLE
Bug: es index not clearing out on package load

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4700]
I had an Arches instance running with a few test resources in it.  I wanted to see some non-business-data-related changes to the package, so i pulled an updated package from git (which lacks business data), and ran the load_package command

```python manage.py packages -o load_package -s /Users/adamlodge/repos/sfport-pkg -db true -y```
...no errors

But to my surprise, the previously-existing resources continued to show in the map and search results.  When I try to edit the resources or map, I get an error indicating that the resources do not exist.  It looks as though these old resources are not being cleared from the index on package load.

using elasticsearch-6.6.2

**Comment by mradamcox** [comment]
@adamlodge can you check what arches branch you are working with? ES 6.6.2 only works with `master` (just found this out) and ES 5.x is necessary to work with `stable/4.4.x`. If you have cross versions, maybe the index management didn't work as normal. I can confirm that generally setup_db does work as expected (all resources removed from all ES indexes).

**Comment by apeters** [comment]
@adamlodge is this still an issue for you?

**Comment by adamlodge** [comment]
yes.  Cyrus duplicated the issue this morning.

**Comment by apeters** [comment]
I'm not able to reproduce this bug (@chiatt  or @adamlodge can you help?)

**Comment by adamlodge** [comment]
I'll close the issue.  @chiatt sussed it out, and fixed it under another ticket.  Was the result of resource instance records that had no tiles associated to them.
