### ISSUE TITLE
Add GeoJSON  Import Button/Paste Box on Search Page

### ISSUE THREAD

**Issue by StucakeGLHER** [archesproject/arches#4701]
**Is your feature request related to a problem? Please describe.**
No, it’s a suggested enhancement as currently possible through the command line.
**Describe the solution you'd like**
Having a button/box on a card to import or paste a GeoJSON file to link to a resource e.g. A site/activity polygon or the extent of a heritage asset polygon created in an external GIS  (as suggested for the GLHER Consultation Casework Module).
**Additional context**
This idea came from discussions with DW and the Arches HER team (SC & AM). 
Hope this makes sense.

**Comment by dwuthrich** [comment]
Note that this ticket is specifically to add the paste GeoJSON functionality to Arches' search page.  This functionality already exists for the editor.

**Comment by chiatt** [comment]
@dwuthrich This feature is now in v5, right?

**Comment by dwuthrich** [comment]
meets requirements
