### ISSUE TITLE
`python manage.py migrate` requires postgres superuser account

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#4707]
**Describe the bug**

(Working towards a solution to #2636.)

From the Postgres documentation:

> Loading an extension requires the same privileges that would be required to create its component objects. For most extensions this means superuser or database owner privileges are needed. The user who runs CREATE EXTENSION becomes the owner of the extension for purposes of later privilege checks, as well as the owner of any objects created by the extension's script

When deploying Arches, especially with shared database provisioning (eg Amazon RDS), it is poor practice to run an application with superuser-level permissions. 

For deployment, it is better for the insufficient permissions exception to be caught and logged, with the deployment process handling anything that requires elevated permissions in a more controllable, inspectable method (eg via a .sql file, rather than relying on running a command with the Arches codebase).

**Desired Behavior**

Catch any `django.db.Error` Exceptions thrown by the CreateExtension migration operation. This will allow `python manage.py migrate` to complete successfully with a normal user with logged warnings, and assume that the deployment process correctly adds in the required extensions to the DB prior to running the application. (For example, the extension could be added to the `public` schema prior to spinning up the Arches instance.)

When run with a db superuser account, the migrate functionality should remain as it is.

**Comment by mradamcox** [comment]
@benosteen What do you think is the best way forward for this ticket? With your fix, the migration command will not error out if run by a non-superuser so as you say the issue is kind of solved.

If we want to go further, I was thinking we could more clearly document the postgis template creation, and advise that users also install the `uuid-ossp` extension into it. That would mean that the Arches database (when made from the postgis template which is how the new `setup_db` command works) will have both of those extensions and no CreateExtensions would be needed, so they could be fully removed from the migrations. Going that route, it may also be good to check for these extensions prior to migrations being run, and cancel the operation if they are not present...

**Comment by benosteen** [comment]
I'm firmly in the camp that any extraneous one-off db set up (eg steps
beyond creating tables and functions an app needs) should not be done by a
code regularly run within the app's environment. Stand-alone script for
setup, divorced from the app!

I would greatly prefer the migrate to check to see if the template is
correct and present, or hard fail otherwise. To put it into
container/deployment context, the Arches container is at best 1.5GB in
size. If all you want as a sys/devops, is to get some DB clusters set up
and ready to deploy Arches instances to when you need (asynchronously),
having to pull a large container and run a fully configured multi-layered
environment (cluster env -> container env -> python env -> arches
shell/command) just to run 6? lines of SQL that requires none of that
config aside from where to aim at? It is not great!

Ben

**Comment by veuncent** [comment]
I am firmly in the camp of automating as much as possible :)
The installation of Arches has clearly been a great hurdle for many users, and the Docker image was supposed to ease that by providing a way to get started with a single command. 

Even though requiring superuser credentials is less than ideal, adding more manual installation steps is also not. Is there a middle road? E.g. somewhere along the lines of your suggestion in #4882 to optionally provide the superuser credentials?

**Comment by mradamcox** [comment]
@veuncent As you can see from the PR I made related to this: https://github.com/archesproject/arches/pull/4833

At the moment, if the default user that Arches has been given has superuser status, then everything proceeds as before.

**Comment by mradamcox** [comment]
@benosteen What would you say to closing this ticket? I think that we have made progress, and achieved what you had specifically written this up for initially. A new ticket that addresses the broader question of "what is a best practices Arches installation" would be the best next step in my opinion.

**Comment by benosteen** [comment]
Sure, sounds good.
