### ISSUE TITLE
Arches Collector requires Guest group to download to devices

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4717]
Collector projects assigned only to users in the Graph Editor group will not download to a device. The project also needs to be assigned to the Guest group. Projects should download to a device as long as the user is assigned to the project. No other groups or users should be required.

**Comment by chiatt** [comment]
This issue appears limited to the iOS emulator and devices. When making a request from an iOS device to `/mobileprojects?status`, the request is always made as an anonymous user, regardless. This is not the case from a browser or android device.

**Comment by chiatt** [comment]
@dwuthrich To QA this you will need to update collector in your emulator or on your device. If on your device, just plug your phone into your machine and run: 
```
yarn ios-mojave
```
The QA machine is updated with the latest 4.4.x, so you can test against that machine. Also, I get a error after installing on a device (below) but it occurs after the build is `successful` and seems inconsequential.


```
Error 0xe8000022: The service is invalid. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
Error: Error code 253 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/cyrus/Documents/projects/GCI/arches4/arches-collector/arches-mobile/platforms/ios/build/device/ArchesCollector.app
error Command failed with exit code 1.
```

**Comment by dwuthrich** [comment]
meets requirement
