### ISSUE TITLE
bug: ES seems to indicate authoritative edits are provisional

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4725]
I create a new tile (as the admin user) which was captured in the db as authoritative.  I verified this by looking at the tile record in pgadmin to see that the tiledata column was populated, and not the provisionaledits column.

When the new resource is displayed in search, it is marked as provisional.  

Further, the resource editor recognizes that it is authoritative, so there is no way to change its status.

**Comment by adamlodge** [comment]
@chiatt Your fix works - mostly.  I wouldnt normally think to test this, but I created a valid resource with a single tile.  It indexed properly.  Then I went back to edit mode and deleted that tile.  The resource continues to exist, but is marked provisional in the ui. It seems like any time that a resource instance lacks tiles, it ought to cease to exist.  The good news is that at least now i can get back into edit mode in these cases - which i could not do before.

**Comment by adamlodge** [comment]
@chiatt and I talked.  We think the ideal solution is this:
If there is only one tile in an instance, and user tries to delete that tile, then user should be prevented from doing that and given a message saying that this is the only data tile in the resource, and that if you want to delete the resource, then use the delete resource button.  This does not preclude user from issuing updates to the sole remaining tile.

**Comment by dwuthrich** [comment]
@adamlodge @chiatt A slight riff on your proposed solution: when you alert the user with a message, present them with the option to delete the instance in the alert box (instead of making them close the alert, open the manage menu, and select the delete resource option).

**Comment by adamlodge** [comment]
Original ticket issue is resolved.  I'm gonna close this and open a new one to address the tile-less resource bug
