### ISSUE TITLE
Graph Manager: Editing Semantic Node requirements

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#473]
Once a semantic node has a child node that is also semantic the following should happen:

- The parent semantic node's class should no longer be editable (e.g.: the user can no longer change the ontology class)

- The parent semantic node's data type should no longer be editable (e.g.: user cant change the data type to "string")

**Comment by apeters** [comment]
For simplicity's sake I would suggest that we allow a user to create any combination of node datatypes and classes as they wish.  Semantic nodes really have no impact on how we collect data or reconstitute graphs from the data.

**Comment by robgaston** [comment]
What is the outcome here?

**Comment by dwuthrich** [comment]
We should enforce bullet #1 (parent ontology class is set once user defines child ontology class and property).  I have no objection to allowing a semantic node to be "any data type".

**Comment by apeters** [comment]
I'm not sure I understand the reasoning behind this.  
If the rules laid forth by the underlying ontology allow the parent ontology class to change why not let it change?  We already let it change for nodes with other data types.  What makes the semantic type so special.

**Comment by apeters** [comment]
I would like to close this with the outcome that we allow semantic nodes to be managed just like any other node.
