### ISSUE TITLE
Bug: problem adding tile with null geometry

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4734]
Getting an error when saving a card that contains a geometry node if the geometry value is not populated.  Note that geometry node is not "required".

![Screen Shot 2019-04-02 at 8.02.50 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/3afbc580-700e-4c28-9213-4030ebfd30f5)

**Comment by chiatt** [comment]
This is working now, right @adamlodge?

**Comment by adamlodge** [comment]
working
