### ISSUE TITLE
Graph Manager: Delete Node Button not working properly

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#476]
Clicking the delete button on a node does not work as intended.

Pressing the button appears not to make any changes to the graph.  However, trying to reload graph after pressing the button breaks the graph manager (uncaught django error keeps page from loading)

**Comment by dwuthrich** [comment]
Delete button does delete node, but also seems to automatically close node editor form.  Node form should stay open and default to parent of deleted node.

**Comment by robgaston** [comment]
@dwuthrich this should be fixed now in `master`

**Comment by dwuthrich** [comment]
meets requirements
