### ISSUE TITLE
Upgrade ES to 7.0.0

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#4775]

**Comment by benosteen** [comment]
It's worth pointing out that backwards compatibility for this upgrade would
be nearly essential for us. For some perspective, Amazon Elasticsearch
Service only supports up to version 6.5 so we are now having to create
containers of our own (and so, administrate them) for Elasticsearch, rather
than rely on this service. While I can foresee the service adopting 6.6 and
6.7 in due course, 7.0 could take a while.

As we are using AWS for our development, staging and production
environments, this is a concern for us.

Ben

**Comment by mradamcox** [comment]
It would also be nice to have this ticket attached to an actual release/approximate date, not just a task. Software upgrades like this can be difficult, or impossible, for users to adopt on short notice.

**Comment by chiatt** [comment]
It looks like Amazon ES Service no supports ES 7. https://aws.amazon.com/elasticsearch-service/faqs/?nc=sn&loc=6

**Comment by apeters** [comment]
Yeah, I just saw this.  Nice to know that this is not a potential blocker anymore.

**Comment by dwuthrich** [comment]
meets requirements
