### ISSUE TITLE
Map/List Interaction on Search

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4776]
Not sure if this is a functionality regression or a request for enhancement, but:

On the search page, there is no interaction between search results (in the left pane) and the resources on the map.  It would be nice if when I hover over a given result, it indicates itself on the map.

Also (and maybe this is a separate issue), filtered search results do not filter on the map.  That is, the list on the left reduces based on a user-defined search, but the map continues to show all resources.  This may be by design, but not sure.

![Screen Shot 2019-04-15 at 8.22.05 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/243343a4-7c6d-48af-9890-8f3a83c3c14a)

**Comment by chiatt** [comment]
@adamlodge There should be filtering and interaction between the "Map Marker" overlay which shows your search results on the map (black teardrop markers by default) and the search results list. It looks like from your screenshot you have a different overlay than "Map Marker".

**Comment by adamlodge** [comment]
resolved
