### ISSUE TITLE
If the map search rectangle (or possibly any other setting) in the admin Settings web interface gets corrupted it becomes impossible to access the Arches web interface

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#4780]
See this message on the google groups here: https://groups.google.com/d/msg/archesproject/D6N0FYk0BsY/xDsayvHNBAAJ

updating line 40 in `arches/app/utils/context_processors.py` to this:
`default_center = {'coordinates': [0,0]}`
should fix the issue

**Comment by robgaston** [comment]
look good to me
