### ISSUE TITLE
System setting can be deleted

### ISSUE THREAD

**Issue by JiachengYin** [archesproject/arches#4806]
An Arches project's system setting webpage allows an authorised user to completely remove any part of the system setting by clicking a big yellow button, which will probably cause the search page to fail. 

Here are screenshots of an error generated by removing the project extent node.

![Outlook-re23diri](https://user-images.githubusercontent.com/50096988/56883700-cdb9c800-6aaa-11e9-8bc0-10878600b43a.png)
![Outlook-wl33p1um](https://user-images.githubusercontent.com/50096988/56883704-d1e5e580-6aaa-11e9-9a52-a446a8410fc3.png)

**Comment by mradamcox** [comment]
@JiachengYin this was actually just addressed in this ticket: https://github.com/archesproject/arches/issues/4780

The fix will be in the next release of Arches.
