### ISSUE TITLE
Graph Manager - Move node (drag and drop) not working properly

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#481]
An error is being thrown that causes drag and drop to fail.  This may be due to our latest ontology work.

**Comment by dwuthrich** [comment]
D3 tree does not refresh after dropping node to new parent.

**Comment by dwuthrich** [comment]
Actually, the d3 graph does update, its just delayed.  We should add a UI element (such as a spinning logo) on the d3 panel to let the user know that Arches is processing the graph edit,

**Comment by apeters** [comment]
Sounds good, I'll add that

**Comment by dwuthrich** [comment]
After performing drag and drop of a node branch, the large red circles (indicating valid drop points) persist.  They should no longer be displayed after dropping the node branch

**Comment by apeters** [comment]
I can't reproduce this behaviour.

**Comment by dwuthrich** [comment]
meets requirements
