### ISSUE TITLE
Reflect resouce model changes in existing tile data

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4826]
Currently, if an admin adds or removes nodes from a resource model, these changes are not reflected in the tile data. If a graph editor has set the OVERRIDE_RESOURCE_MODEL_LOCK to true, changes that they make to the graph should update their tile data so that the graph and tiles do not end up in disagreement.

**Comment by chiatt** [comment]
re #4825

**Comment by dwuthrich** [comment]
@chiatt Is (or will) OVERRIDE_RESOURCE_MODEL_LOCK a system setting defined in the settings.py file?

**Comment by chiatt** [comment]
@dwuthrich Yeah - OVERRIDE_RESOURCE_MODEL_LOCK is currently in settings.py. The default value is `False`, preventing graph editors from making schema changes to cards with business data.

**Comment by chiatt** [comment]
This will be addressed by future graph work conducted by @chrabyrd
