### ISSUE TITLE
Dockerfile: Use Multistage build to shrink deployed container size

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#4850]
The current size of the Arches docker container image is 2.7GB. It includes all of the build and dev packages required to create the python library wrappers for a number of dependencies, many of which are not needed during runtime.

**User Story**
Use a temporary container environment to build the necessary python wheels for the Arches dependencies, and copy them across to a clean base image, installing only the packages required to run Arches.

**Definition of Done**
A new Dockerfile which carries out the multistage build, and results in a more focussed container image that has no loss of functionality. Reducing the footprint of the application as well means that there are fewer critical security updates to track in production outside of OS level updates.

**Comment by chiatt** [comment]
Issue resolved in #4851
