### ISSUE TITLE
Arches Collector does not download existing resource instances

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4853]
Not sure if this is an Arches or Arches Collector issue, but after creating an Arches Collector does not download data to local device.

To recreate:
1. Create new project using Arches Collector Manager
2. Be sure to select "Allow users to download data" in the data card, confirm that then models in the project are selected
3. Save and activate project
4. Sync with project from a mobile device (I tested with the iOS Xcode simulator and Chrome)
5. Open project, observe that existing data are not downloaded to device.

After checkin the console in Chrome, I saw this error:

GET http://localhost:8081/couchdb/project_167761d3-2178-45d8-82f0-88d412f8728e/?_nonce=1559080644224 403 (Forbidden)

Not sure if its related to the problem or not.

**Comment by chiatt** [comment]
This seems to be working on the latest from 4.4.x. @dwuthrich Is it possible you were downloading from master running on your local machine? Currently we have just been testing against the 4.4.x branch.

**Comment by dwuthrich** [comment]
@chiatt Yes, I'm testing with master.  I'll try to reproduce with 4.4.x

**Comment by chiatt** [comment]
This issue occurs on master and not 4.4.x, and should be resolved before the 4.5.0 release.

**Comment by whatisgalen** [comment]
working in latest
