### ISSUE TITLE
Advance Search returns errors automatically with date searches

### ISSUE THREAD

**Issue by RossWorkman** [archesproject/arches#4872]
**Describe the bug**
Whenever attempting to run or even open an advance search with a field that requires a date (using the calendar box or even without), the advance search automatically returns an error "Invalid Date Specified" or "strptime() argument 1 must be string, not None" in the case of calendar boxes. Search is only able to be conducted if a date is entered into the date field. 

**To Reproduce**
1. Go to default arches landing page
2. Click on 'Search'
3. Click on 'Advanced Search'
4. Choose an advance search option that has a date field
5. Error will automatically appear on screen

**Screenshots**
![1](https://user-images.githubusercontent.com/32510383/58803696-03048900-8608-11e9-96bb-6de5ccb2ac9f.png)
![2](https://user-images.githubusercontent.com/32510383/58803703-0566e300-8608-11e9-91a3-aa3b4a0cafc1.png)

**Expected behavior**
Advance Search can be conducted on any of the search terms, without a date needing to be put in

**Your Arches Information**
*   Version used: 4.4.1
*   Operating System and version (desktop or mobile): Windows 7 (Desktop)
*   Browser Name and version: Google Chrome 74.0.3729.169

**Comment by RossWorkman** [comment]
Hey folks. 
Could you let me know when you've got a chance to look over this issue and update me on its progression, as the current project I am working on needs to know if we will have to go live with this issue in place. Either in this thread or to my email (Ross.Workman@Historicengland.org.uk) would be much appreciated.

Thanks!

**Comment by chiatt** [comment]
Thanks @RossWorkman for submitting this. We will meet on Thursday to prioritize tickets and let you know then if we can get it into the 4.4.2 release.

**Comment by chiatt** [comment]
Hey @RossWorkman, @apeters merged in a fix for this yesterday, so it will be resolved in the upcoming 4.4.2 release sometime later this month.

**Comment by chiatt** [comment]
Works as expected in 4.4.x (including 4.4.2) and master.
