### ISSUE TITLE
Projects fail to update if any collector projects are missing beginning or end dates

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4884]
The serialize mobile projects method errors if one or more projects is missing a start or end date.

**Comment by chiatt** [comment]
@dwuthrich This was the issue on Wednesday that was preventing projects from updating on a device from the QA site. One of the projects on QA was missing start and end dates causing an error in a date calculation. I've fixed the issue, so to verify it's fixed, just remove a start or end date from any project and try to update projects on your device.

**Comment by dwuthrich** [comment]
meets requirements
