### ISSUE TITLE
Edit History as JSON-LD (Activity Stream)

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#4938]
**Is your feature request related to a problem? Please describe.**
There is a need to keep one or more external systems synchronized with the data being managed in Arches, and for a way to see if a resource has been edited or altered within a given time period.

**Describe the solution you'd like**
An API that produces a machine-readable form, preferably JSON-LD, of the edit history of the items managed by a given Arches instance. The Activity Streams 2.0 Vocabulary defines a set of abstract types and properties that describe past, present and future Activities and would be a good choice to express this. IIIF.io has already adopted this as a means for activity interchange.

The API would be simple:

- `/history` - a URI that returns a JSON-LD document with details about the edit log, represented as an `OrderedCollection`. This MUST give the `first` and `last` pages of the Activity Stream. The first page will contain the oldest activities, with the last containing the most recent.
- `/history/N` - a URI that resolves to a JSON-LD `OrderedCollectionPages` for page `N` of the Activity Stream.

**Comment by azaroth42** [comment]
Done :)
