### ISSUE TITLE
Default value config does not populate

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4967]
When defining a default value for a widget in a card, the config on the right panel of the card editor does not display the information indicating what the default value is.   The default value does appear in the widget itself, but often widgets containing a defulat value are also set to not "make widget visible", in which case there is no way to see that a default value has been set.

Screenshot shows the a scenario where the widget is set to display.
![Screen Shot 2019-07-01 at 1.09.28 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/b9da7291-c8ad-4244-b5b2-5123193a2be8)

**Comment by chiatt** [comment]
Fixed in 6.x
