### ISSUE TITLE
Drop downs dont filter on android

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4972]
![Screenshot_20190703-121525_ArchesCollector.jpg](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/47b5b7c1-cb14-4c26-a493-47570768bc58)

**Comment by adamlodge** [comment]
This is resolved on sf planning's APK build.  Is it resolved in master?

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-collector #555](https://github.com/archesproject/arches-collector/issues/555) via [**ZenHub**](https://www.zenhub.com/)
