### ISSUE TITLE
Map card draw tools: add ability to select features from a given overlay

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4982]
The user should have to select this option from the existing draw tools dropdown, at which point the layer for selecting features should show up on the map and clicking on one should add that feature as a drawing to the current node.  There should be some way for an implementer to declare the layers/sources that should be used for this feature.

**Comment by robgaston** [comment]
@dwuthrich this is implemented in the "Map" card for the "Application Area" resource model in archesproject/consultations-prj#111

**Comment by dwuthrich** [comment]
@robgaston after pulling the latest from consultations and arches, I do not see the expected entry in the draw tools dropdown, nor anything in the model designer card to indicate that this functionality is available.

**Comment by robgaston** [comment]
@dwuthrich please try pulling the latest again on both repos, you should be able to use this as shown
![O65NeK6KUO](https://user-images.githubusercontent.com/1187406/62333935-6e3cd100-b47a-11e9-8420-a3d3c07a74c7.gif)

**Comment by robgaston** [comment]
@dwuthrich I think that you will also need to reload the package

**Comment by dwuthrich** [comment]
meets requirements
