### ISSUE TITLE
New map component: allow for custom overlay popups

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4983]
The new map component should support custom overlay popups (either with html content or a url in the feature properties) as we do with the existing map widget.

**Comment by bferguso** [comment]
@chiatt  - Has anyone taken this on? I've taken a cut at this for one of the BC Gov requirements. If nobody has taken it on I'll create a PR and submit what I have, otherwise I'll stand down if there is already a proposed/desired solution.

**Comment by chiatt** [comment]
@bferguso - Nobody has started on this. It would be great to see what you've got.
