### ISSUE TITLE
New map component: implement a map card component for relating resource instances

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#4989]
We need a map card component that will allow a user to manage a `resource-instance-list` node by selecting resources from a map overlay.  This new card component should use our new generic map component: (https://github.com/archesproject/arches/blob/master/arches/app/media/js/views/components/map.js)

This will be used initially in the consultation project for the Application Area - "Relate Heritage Resources" card

There is an existing map card component (that implements draw tools for `geojson-feature-collection` nodes) which shows a pattern for extending the map component as a card component which can be used for this ticket as well.

**Comment by robgaston** [comment]
We should probably consider prototyping this first as a component in the consultations project built very directly to those requirements (as they are specific and driving this requirement).  Then we can explore the possibility of making that component more reusable and including it w/ Arches (as we do the map card component).

This component could still follow the patterns set forth in the existing map card component, as previously mentioned.

**Comment by dwuthrich** [comment]
meets requirements
