### ISSUE TITLE
JSON text format causes loading error on Ubuntu

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5011]
Loading resource models with advance styling fails on linux (not a problem on MacOS) due to a parsing error caused by tab and newline characters. Most likely the advanced json is getting saved to postgres as a string rather than json. This issue also occurs when loading tile data with the rich text editor datatype .

https://stackoverflow.com/questions/25871477/postgresql-text-to-json-conversion

```
Total time to load concepts: 0:05:10.895239 s
loading resource models and branches
consultations_prj/pkg/graphs/branches/Address.json
consultations_prj/pkg/graphs/resource_models/GLHER_Heritage_Asset.json
consultations_prj/pkg/graphs/resource_models/GLHER_Heritage_Asset_Historic_Aircraft.json
consultations_prj/pkg/graphs/resource_models/GLHER_Archive_Source.json
consultations_prj/pkg/graphs/resource_models/GLHER_Application_Area.json
consultations_prj/pkg/graphs/resource_models/GLHER_Heritage_Asset_Maritime_Craft.json
consultations_prj/pkg/graphs/resource_models/GLHER_Activity.json
invalid input syntax for type json
LINE 1: ...1e-5463-11e9-b5f5-000d3ab1e588'::uuid, "config" = E'{"addToM...
                                                             ^
DETAIL:  Character with value 0x0a must be escaped.
CONTEXT:  JSON data, line 1: {"addToMap": true, "advancedStyle": "[

consultations_prj/pkg/graphs/resource_models/GLHER_Actor_Organization.json
consultations_prj/pkg/graphs/resource_models/GLHER_Actor_Person.json
consultations_prj/pkg/graphs/resource_models/GLHER_Consultation.json
consultations_prj/pkg/graphs/resource_models/GLHER_Bibliographic_Source.json
```

**Comment by chiatt** [comment]
It may actually be due to the JSONSerializer serializing newline characters as `\n` rather than `\\n`. On macos `\n` is not an issue, but on Ubuntu, JSON with unescaped newlines will not save to postgres.

**Comment by whatisgalen** [comment]
was unable to successfully run arches 5 on ubuntu virtual machine

**Comment by whatisgalen** [comment]
There are several causes for this issue (not being able to execute the SQL query, thus unable to import business data):

One example is when a single or double quote is not closed (in a csv file), likely related to instances of one line somehow getting split over several lines:

![Screen Shot 2020-02-06 at 5 53 14 PM](https://user-images.githubusercontent.com/8366985/73994238-b812e200-4909-11ea-8ca2-cd0099dbd50a.png)

Other causes are related to escaped quotes (`\"`) and possibly the characters: `\t` and `\n`. Replacing the former with a single quote and removing any occurrences of the latter enables business data to be imported successfully.

**Comment by ryan86** [comment]
I was able to solve this by removing the following two lines from a preliminary sql file:
```
SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
```

Not sure which line did or if it was a combination of the two. Also, was not able to test affects of removing these two lines on the rest of the application.

**Comment by chiatt** [comment]
Problems addressed by @ryan86's suggestion above.
