### ISSUE TITLE
gunicorn is missing from the Docker run container

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#5014]
**Describe the bug**
The multistage docker container build builds the gunicorn package, but the run container is missing the line to install it (as it is not currently part of the `requirements.txt` normal route for installation).

**Expected behavior**
To run pip install gunicorn...

**Comment by mradamcox** [comment]
@benosteen just looking through tickets, can this be closed now?

**Comment by benosteen** [comment]
I believe so. The docker config will have to be updated with the new dependencies soon anyway and if this fix hasn't got to where it needs to be, we'll find out soon.
