### ISSUE TITLE
Remove hard-coded media url

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#5022]
media url in "arches/arches/app/templates/views/mobile-survey-manager.htm" are hard coded and should use static directory variable.

**Comment by chiatt** [comment]
duplicate of #4093

**Comment by mradamcox** [comment]
@chiatt as you are calling this a duplicate of a ticket that I opened, I looked into it, and I'm pretty sure it's not a duplicate at all. Could you give a reason for why you think this is a duplicate?

A quick bit of research leads me to think that this line https://github.com/archesproject/arches/blob/master/arches/app/templates/views/mobile-survey-manager.htm#L31 is what @njkim is referring to above. However, as you can see from my ticket, I was using Arches 4.3, and in stable/4.3.x that specific line does not exist; there is no hard-coding of media URLs in that template: https://github.com/archesproject/arches/blob/stable/4.3.x/arches/app/templates/views/mobile-survey-manager.htm

**Comment by chiatt** [comment]
Hey @mradamcox, you're right. It's not a duplicate.

**Comment by chiatt** [comment]
Hey @njkim, Can you confirm this was resolved based on your last arches deployment?

**Comment by chiatt** [comment]
Meets requirements
