### ISSUE TITLE
get_tile_data method doesn't return anything when there is more than 1 provisional edit

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5032]
This will be an issue when calling functions (like the one on line 262 - https://github.com/archesproject/arches/blob/master/arches/app/datatypes/base.py#L262) expect a valid object.

https://github.com/archesproject/arches/blob/8acdc091f5e38d03c36c3140246d74377de12aff/arches/app/datatypes/base.py#L255-L260

I think if we're willing to return a provisional edit when there's only one, we should just return the first provisional edit no matter how many there are.

**Comment by chiatt** [comment]
This check `len(tile.provisionaledits.keys()) == 1: ` is probably done to ensure the provisional edits are valid. A tile with no authoritative data should never have more than one provisional edit. We should move that check into a `try` block and raise an error if the tile has any other number of provisional edits. Also - if a tile has no authoritative or provisional data, this method should probably explicitly return `None`.

**Comment by chiatt** [comment]
There are other places where we do a similar check such as the primary descriptor function. These issues will be addressed as part of this ticket: #6627
