### ISSUE TITLE
New Map Card Component: Overlays settings are not preserved after adding a new geometry

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5048]
When creating a geometry with an overlay set to visible, the card component refreshes after a user saves a geometry edit.  This appears to result in the overlay visibility being reset to off.  See: https://recordit.co/IcXy8GaEOc

**Comment by robgaston** [comment]
@dwuthrich this is a much broader issue w/ adding a new tile in the resource editor; that is, after adding a new tile the entire card component is re-rendered, which is what causes the unexpected state change (esp. obvious w/ overlays) after clicking "add".  This only occurs currently when adding a new tile, but adjusting/enhancing the behavior here would have additional benefits for custom card components beyond the symptom that you are seeing here.  Unfortunately, I think that the fix here will therefore be a significant undertaking, but the benefits seem significant as well.

**Comment by dwuthrich** [comment]
@robgaston Not surprised to hear that this is a broader issue.  Thanks for pointing out that this is a chance to enhance how custom card components work.  Just wondering how you define "significant undertaking" to address this issue.

**Comment by robgaston** [comment]
@dwuthrich it's a bit hard to say, but it will require some reworking of the resource editor (and how it instantiates card components).  I would think on the order of days (as opposed to hours or weeks).  Probably less than a person-week but more than a person-day.  I would need to spend more time digging into the exact cause and potential solutions to narrow that window

**Comment by robgaston** [comment]
fixed in #5250

**Comment by dwuthrich** [comment]
meets requirements
