### ISSUE TITLE
New Map Card Component: Allow user to cancel active edit

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5049]
When creating a new geometry, the user can't cancel their current geometry (for example by pressing the esc key).  It appears that the user must complete the edit, then select the geometry and delete it.  

Its very easy for a user to press the "delete this record" button by mistake, thereby deleting all the geometries in the card instead of the specific geometry.

A possible UX enhancement: highlight the row in the geometry list widget (located immediately under the "add new feature..." dropdown to make it clearer to the editor the specific geometry that they are working on.

**Comment by robgaston** [comment]
@dwuthrich included in this work is the disabling of card level buttons (add, delete, cancel) while actively editing geometries

**Comment by dwuthrich** [comment]
meets requirements
