### ISSUE TITLE
Related Resource widget: user can't delete a selection from widget 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5088]
Once a user has made a selection, there's no way to undo it.  As with concept widgets, we should allow user to unselect by showing a remove button in the select2 component.

See; http://recordit.co/aihHtl5cNd

**Comment by dwuthrich** [comment]
@ryan This still appears to be an issue.  To reproduce: 
logon to lincoln_release, 
go to advanced search, 
select Lincoln Investigative Activity - Phase Type Assignment
select a value from the Activity type dropdown
Notice that the user cannot delete their selections

**Comment by chiatt** [comment]
No longer an issue because of new rr widget.
