### ISSUE TITLE
Graph Manager: Alert Message

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#509]
Alert messages should be placed in the "card-alert-panel" div (see arches_designer_v2.html line 1474).  Demo of the panel: http://archesproject.github.io/mockups/arches_designer_v2.html  go to card manager (data widgets and cards in menu), select a card, the press "discard edits"

**Comment by robgaston** [comment]
This is addressed in #522 (merging shortly).

As part of this ticket, I added the global alert view model and implemented it in the graph manager for confirming navigation when forms have unsaved data.

additional instances of alerts should be handled in separate tickets (eg #518 )

**Comment by dwuthrich** [comment]
Creating new graph now results in Arches displaying 3 alert boxes (all empty), and warning does not appear card alert panel.  See attached files

![arches2](https://cloud.githubusercontent.com/assets/815185/15943808/94e0738a-2e3f-11e6-864e-afa240d72bd3.png)
![arches1](https://cloud.githubusercontent.com/assets/815185/15943809/94e29ade-2e3f-11e6-8512-70770a5dcb55.png)

**Comment by robgaston** [comment]
@dwuthrich did you clear your cache? It looks to be working fine here: http://dev.archesproject.org/graph/0c423cfc-2e7b-11e6-83f7-02703667c931/settings

Try changing the name, then click the 'Exit' button in the top right

**Comment by robgaston** [comment]
confirmed that the above was a local cache issue.

Should also:
- [ ] move existing node form alert to global alert

**Comment by dwuthrich** [comment]
meets requirements
