### ISSUE TITLE
Concept labels with unicode return double encoded form

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5096]
After importing a concept into the RDM from AAT that has unicode in the label, the response from the JSON-LD writer double encodes the unicode characters.

To reproduce:

* Import http://vocab.getty.edu/aat/300015050 via sparql into the RDM
* Put it into a collection and set a property to use that collection (e.g. p45_consists_of from a Man Made Object)
* Create an instance with that concept
* Retrieve it from /resources/uuid

Got:
```
{'@context': 'https://linked.art/ns/v1/linked-art.json', '_label': 'Label', 'id': 'http://localhost:8000/resources/156aa24e-3cee-4215-ae3d-7433bb210fdf', 'identified_by': [{'content': 'Name', 'type': 'Name'}], 'made_of': [{'_label': "peinture \\u00E0 l'huile (oil paint)", 'type': 'Material'}], 'type': 'HumanMadeObject'} 
```

Expected:
```
{'@context': 'https://linked.art/ns/v1/linked-art.json', '_label': 'Label', 'id': 'http://localhost:8000/resources/156aa24e-3cee-4215-ae3d-7433bb210fdf', 'identified_by': [{'content': 'Name', 'type': 'Name'}], 'made_of': [{'_label': "peinture \u00E0 l'huile (oil paint)", 'type': 'Material'}], 'type': 'HumanMadeObject'} 
```

**Comment by benosteen** [comment]
The following encapsulates the current functionality:

```>>> import rdflib, json
>>> from rdflib import Literal, Graph, URIRef, RDFS
>>> from pyld.jsonld import from_rdf, framing
>>> from StringIO import StringIO
>>>
>>> name = u"Röttigen"
>>> l = Literal(name)
>>> g = Graph()
>>> g.add((URIRef("http://example.org/1"), RDFS.label, l))
>>> len(g)
1
>>> print(g.serialize(format='nt'))
<http://example.org/1> <http://www.w3.org/2000/01/rdf-schema#label> "R\u00F6ttigen" .


>>> export = g.serialize(format='nt')
>>> type(export)
<type 'str'>
>>> export
'<http://example.org/1> <http://www.w3.org/2000/01/rdf-schema#label> "R\\u00F6ttigen" .\n\n'

>>> js = from_rdf(export, {'format': 'application/nquads', 'useNativeTypes': True})
>>> framing = {"@omitDefault": True, "@omitGraph": False, "@id": "http://example.org/1"}
>>> js = frame(js, framing)
>>> json.dumps(js, indent=True, sort_keys=True)
'{\n "@graph": [\n  {\n   "@id": "http://example.org/1", \n   "http://www.w3.org/2000/01/rdf-schema#label": "R\\\\u00F6ttigen"\n  }\n ]\n}'
>>> out = json.dumps(js, indent=True, sort_keys=True)
>>> dest = StringIO(out)
>>> with open("export.json", "w") as e:
...   e.write(dest.read())
...
>>>
(ENV) root@d4e7140c20bf:/web_root/arches# cat export.json
{
 "@graph": [
  {
   "@id": "http://example.org/1",
   "http://www.w3.org/2000/01/rdf-schema#label": "R\\u00F6ttigen"
  }
 ]
}```

**Comment by benosteen** [comment]
N-Triples is explicitly ASCII in its encoding according to the standard, hence the escaping backslashes.

**Comment by benosteen** [comment]
This is related to #5137

**Comment by azaroth42** [comment]
Urgh! 😿 Great sleuthing! That's going to be a problem in our toolchain across the board.
The solution will need to involve avoiding the serialization / parse step given backslash escaping requirement in NT.  I'll try and find out if anyone else has hit this.

**Comment by azaroth42** [comment]
This looks promising: https://github.com/zimeon/rdflib-pyld-compat 
And I know the author. Have reached out as to status of the work.

**Comment by azaroth42** [comment]
I have set up a call with the rdflib-pylib-compat author for today, will report back as to whether it's appropriate to use here.

**Comment by azaroth42** [comment]
I fixed an issue in the code above, now merged in master, that prevented it from working in Python 2.7.

I can reproduce the code above with the expected results by replacing the serialize/parse section with the conversion function:

```
from rdflib import Literal, Graph, URIRef, RDFS
from pyld.jsonld import from_rdf, frame
from rdflib_pyld_compat import pyld_jsonld_from_rdflib_graph

name = u"R\xf6ttigen"
l = Literal(name)
g = Graph()
g.add((URIRef("http://example.org/1"), RDFS.label, l))
print(g.serialize(format='nt'))
js = pyld_jsonld_from_rdflib_graph(g)
print(js)
```

This prints:

```
<http://example.org/1> <http://www.w3.org/2000/01/rdf-schema#label> "R\u00F6ttigen" .
[{u'http://www.w3.org/2000/01/rdf-schema#label': [{'@value': u'R\xf6ttigen'}], '@id': u'http://example.org/1'}]
```

Note the `u` before the value ... it's not escaped, as in the NT serialization.

@benosteen could you try this in the Arches code?

**Comment by benosteen** [comment]
I went with an easier fix - switching to use ConjunctiveGraph rather than the default Graph class, which allows for an NQuads export that can be cleanly parsed by pyld and correctly encodes into UTF-8 rather than being forced into ASCII encoding.

Pull request #5181 contains these fixes.

**Comment by azaroth42** [comment]
Sweet :) As simple as possible!

**Comment by benosteen** [comment]
#5181 merged in a fix for this issue to master
