### ISSUE TITLE
Address the difference between node names and widget labels

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#5104]
**Describe the bug**
Currently, when looking at the graph manager of a resource model, editing a node name will edit the card label on the first level of that branch (see first gif). This does not occur when editing the node name on a deeper level of the branch, for example on the third or fourth node of a branch. The screenshots below show this, as the screenshot on the bottom has not reflected a change to the widget label.

**Additional context**
http://g.recordit.co/NdY01SGvqg.gif

<img width="773" alt="Screen Shot 2019-08-13 at 12 14 00 PM" src="https://user-images.githubusercontent.com/38868744/62970278-fc428100-bdc3-11e9-9f82-b7985866d536.png">
<img width="1025" alt="Screen Shot 2019-08-13 at 12 14 13 PM" src="https://user-images.githubusercontent.com/38868744/62970296-049abc00-bdc4-11e9-939f-456e45958128.png">

**To Reproduce**
1. Go to the Resource Model manager, and select a model
2. Click on a node and edit the node name
3. Click on the card manager and see if changes are reflected
4. Repeat on a deer node

**Expected behavior**
The widget label should default to the node name but should allow the user to change the widget label in the card manager without affecting the node name.

**Your Arches Information**

*   Version used: 4.4
*   Found while using the Cardinality-Depth model in the arches-test-package

**Comment by chiatt** [comment]
This is no longer an issue in 5.1
