### ISSUE TITLE
Newest version of master breaks the map widget when using the default card

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#5114]
**Describe the bug**
I pulled the newest commits from the master branch of arches and when I navigated to the map widget I could no longer interact with it. There are a few menus blocking the map and the user cannot interact with the widget.

**To Reproduce**
1. Pull the latest version of master
2. Click on a resource model that has the default map widget card or navigate to the project extent tab in system settings
3. Observe

**Screenshots**
<img width="1440" alt="Screen Shot 2019-08-14 at 12 11 05 PM" src="https://user-images.githubusercontent.com/38868744/63049085-bf8e8c80-be8c-11e9-8bec-a77cab9e019c.png">

**Expected behavior**
The map widget should function as normal, allowing the user to fully interact with it.

**Your Arches Information**

*   Version used: Master as of 12 pm on Wed, August 14, 2019
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**
I checked to see if this bug occurred on other peoples instances of arches, which it does.

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
No longer an issue in the latest
