### ISSUE TITLE
Import fails to match branch when repeated property/class despite unambiguous candidate

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5121]
**Describe the bug**

If two branches coming from a single node have the same property and class combination, then the import algorithm incorrectly determines there to be an AmbiguousGraph exception in some circumstances.

For example, if one branch is a single resource-instance datatype, and the other is semantic with additional properties, then the code throws AmbiguousGraph for incoming data that includes values for the properties that could never be below the resource-instance.

**Use Case**

Linguistic Objects are used for the textual content of a scholarly article. That text can refer to an object, therefore:  Object is_referred_to_by TextOfArticle.  GCI scientists write articles about their work and the objects. These are full resource models, as they need to track the digital file upload. Thus the reference from the Object to the Text is a resource-instance.

Linguistic Objects are also used to capture descriptions of various sorts which are inline within the model, such as a physical description of the object, the provenance of the object, a bibliography of the object and so forth.  These are branches that have content, type and language. Thus the reference from the Object to the Description is to a semantic node.

**Comment by azaroth42** [comment]
Config and code to reproduce with current master: 
[5121-reproduce.zip](https://github.com/archesproject/arches/files/3507314/5121-reproduce.zip)
 
(e.g. set up an instance with these models and concepts, then run send-5121.py.  Update the code (in the obvious way) to send to the right port if you're not on 8001.

**Comment by apeters** [comment]
@azaroth42 I set up the test as described and it seemed to run fine.  Is there something else I'm missing?

**Comment by apeters** [comment]
Ok, I see the errors in the error log now.  Sorry about that.

**Comment by azaroth42** [comment]
Tests in place via 5490, needs solution.

**Comment by azaroth42** [comment]
@apeters and @azaroth42 think there's still an issue here:
https://github.com/archesproject/arches/blob/json_ld_enhancements/arches/app/utils/data_management/resources/formats/rdffile.py#L373-L399

with the way that the concepts are discovered, as label is not unique to concepts.

**Comment by azaroth42** [comment]
Agree fixed, including per previous comment. Closing.
