### ISSUE TITLE
New Datatype for External URIs

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5125]
**Is your feature request related to a problem? Please describe.**

The current set of datatypes do not allow the distinction between a string that happens to be a URI, and an actual URI for a resource.  This distinction is important in Linked Data (and thus JSON-LD), the same way that the string `"2"` is different from the integer `2`.

**Describe the solution you'd like**

A new datatype that allows only a single URI to be entered, and then imports / exports as a URI rather than as a string.

**Comment by benosteen** [comment]
I've created a package with a provisional URI datatype 
https://github.com/thegetty/arches-urldatatype

While the usual functionality is present (text search on URL label, edit, report view, JSON-LD export), the JSON-LD Import does not function. The list of handled datatypes is hardcoded in the core JSON-LD import reader method. (This extension does include `from_rdf` datatype handling code which the JSON-LD import reader may make use of if it widened the datatypes it handled.)

**Comment by azaroth42** [comment]
Closing, given that the package has its own repo for issues :)
