### ISSUE TITLE
Allow concepts to be associated with concepts in JSON-LD import/export

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5136]
**Is your feature request related to a problem? Please describe.**

In the graph manager, it is possible to associate a concept with another concept. However in the original specification for the JSON-LD import/export, we considered concepts to be leaf nodes and any branches below them should be ignored. That turns out to have been shortsighted, as there is a very useful scenario for this pattern.

Related to #5126, if there are multiple types of types for a particular class, then it is useful to distinguish which is which.  For example, there are many nationalities, and without a hint that a particular type represents a nationality, a client system would need to know all possible nationalities in order to render a label of "Nationality" rather than just "Type".

The easiest way to manage this is to say that the Person is of type British, and that British is of type Nationality.  The same would apply to ethnicity, gender, profession for people. Or for object type for objects.

**Describe the solution you'd like**
Continue to process branches of concept and concept-list, especially for further concepts.

In the case of concept-list, then every concept in the list should inherit the concept from the branch.

**Describe alternatives you've considered**

We considered other modeling patterns, but they all resolve back to something very similar to this.

**Comment by apeters** [comment]
@azaroth42 is there a test script (like others that you've created) that can reproduce the issue?

**Comment by azaroth42** [comment]
Will build one :) Assigned myself until done.

**Comment by apeters** [comment]
@azaroth42 What does this mean 

>  "In the case of concept-list, then every concept in the list should inherit the concept from the branch."

**Comment by azaroth42** [comment]
Sorry, that's concise but definitely not clear :)

I mean that if there's a concept-list with multiple concepts (say the node is for Nationality of a person, then I might have two or more nationalities, New Zealand and British), then each of those concepts in the import/export should have the concept (nationality) that's associated with the concept-list node.

eg:

```
Person has-type New-Zealander ; New-Zealander has-type Nationality 
Person has-type British ; British has-type Nationality
```

But in the model that would be just
```
top-semantic-node has-type concept-list ; concept-list has-type concept ;
```

**Comment by azaroth42** [comment]
Test cases to reproduce the issue:
[5136-reproduce.zip](https://github.com/archesproject/arches/files/3764141/5136-reproduce.zip)

**Comment by azaroth42** [comment]
Ooops, typo in the above script -- the 5136d send should (of course) send `data4` not resend `data3`.

**Comment by azaroth42** [comment]
Confirming that this issue also exists for resource-instance and resource-instance-list types.

In concept_types, the UUID of the resource-instance is passed in domain tile data, but it's not processed into the right URI.

**Comment by azaroth42** [comment]
Note that my baseline code to get it working has hard coded datatypes which, per #5299, is a terrible idea.

https://github.com/archesproject/arches/blob/json_ld_enhancements/arches/app/datatypes/concept_types.py#L150-L152

This should be refactored to call a function on the datatype to construct the appropriate URI and return it, rather than hand crafting within the concept code.  For other datatype chains (concept -> resource-instance for example) this would also be required, otherwise code like this proliferates throughout the datatype universe.

**Comment by azaroth42** [comment]
Tests in place. Solution in place for review.

**Comment by azaroth42** [comment]
Agree fixed, closing.
