### ISSUE TITLE
Graph validation on import

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#514]
We should enhance the Graph model to validate a graph on save according to the following rules:
- [x] The root node of a "Resource" can only be a semantic node, and must not be a collector
- [x] A node group that has child node groups may not itself be a child node group
- [x] A node group can only have child node groups if the node group only contains semantic nodes
- [x] if graph has an ontology, nodes must have classes and edges must have properties that are ontologically valid
- [x] if the graph has no ontology, nodes and edges should have null values for ontology class and property respectively

I propose that we throw an exception in the model on validation failure which we can catch and handle accordingly in the import logic (as well as in the views).

On validation failure the import logic should alert user of failure & reason, break execution and rollback any changes.

**Comment by dwuthrich** [comment]
meets requirements
