### ISSUE TITLE
New map card component does not retain local users' basemap/overlays selection on cards with n-cardinality

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5140]
When working with a card of n-cardinality, the map component reverts to the default basemap instead of the user's selected basemap when switching between cards.  This is true of overlays as well.

See: https://recordit.co/RIbCSXrjAi

**Comment by robgaston** [comment]
fixed in #5250

**Comment by dwuthrich** [comment]
meets requirements
