### ISSUE TITLE
UI: The root node of "Resource" can only be a semantic node

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#515]
- [x] In graph settings form, disable radio buttons for resource/graph when the root node of a graph has a datatype other than 'semantic'.
- [x] ensure default root node in new graph/resource has datatype 'semantic'
- [x] hide or disable datatype dropdown on root node in graph manager if graph is a resource

**Comment by apeters** [comment]
because this is only enforced in the UI, we will have to add this check during import as well
