### ISSUE TITLE
UI: disable 'is collector' switch in node form based on grouping rules

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#517]
Need to enforce the following rules in the node form re: node grouping:
- A node group that has child node groups may not itself be a child node group
- A node group can only have child node groups if the node group only contains semantic nodes

Should hide/disable switch if node is not a collector &:
- [x] node group has a parent node group
- [x] node group includes nodes (current node & downstream nodes excepted) w/ datatype other than 'semantic'

**Comment by robgaston** [comment]
Will be difficult to test fully until #541 is resolved.

**Comment by apeters** [comment]
This doesn't seem to work when appending branches that have groups defined within them.
Try appending 3 or more Node/NodeType branches end-to-end. Each Node/NodeType branch is part of a node group.

**Comment by robgaston** [comment]
Perhaps we should track append branch in another ticket - this was really meant to be just about the node form UI - that is the update node task.

What do you think, @apeters ?

**Comment by apeters** [comment]
yeah, let's do that

**Comment by robgaston** [comment]
opened #563

**Comment by robgaston** [comment]
new rules:
- [ ] hidden for resource root node
- [ ] disabled if node is not a collector and node group has a parent node group
- [ ] disabled if node is not a collector and node group includes nodes (current node & downstream nodes excepted) w/ datatype other than 'semantic'
- [ ] disabled for graph root if graph has more than one node
- [ ] disabled if node is in a node group with non-semantic nodes that is a child nodegroup
- [ ] should be labeled 'Make sub-card' for nodes that are downstream of the card root

**Comment by apeters** [comment]
Looks like the "make card" switch is always disabled for a graph root.

The way it is right now, we can't recreate a single ungrouped node.
