### ISSUE TITLE
Default Logging level should be INFO or WARNING not DEBUG

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#5182]
**Describe the bug**
The default logging level in the settings.py is set to debug, which means that every log message will be output to stdout. As use of the standard logging function increases, it will make it more important that the default should be at a more reasonable level (such as warning or info)

eg
https://github.com/archesproject/arches/blob/master/arches/settings.py#L354

**Expected behavior**
By default, the logger should put INFO, ERROR and WARNING level messages to the console, but not the DEBUG level messages which will be far more verbose.

**Comment by chiatt** [comment]
Completed
