### ISSUE TITLE
deleted resources remain on the map

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#5183]
I have noticed that some resource geometries remain on the map after the instance was ostensibly deleted.  On db inspection, it appears that the resource is indeed deleted from the underlying tables and es index, but not removed from mv_geojson_geoms.

@robgaston acknowledges that a long-term solution would be to revise how resource layer overlays are read to not use materialized view, but a simple short term solution will be to refine the refresh logic for the view.

**Comment by chiatt** [comment]
Hey @adamlodge, @robgaston, @whatisgalen - I think we have since made changes to the view refresh right?

**Comment by chiatt** [comment]
This appears resolved in 6.0.
