### ISSUE TITLE
Graph Manager: Ensure user can't delete root node from a graph

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#519]
## Expected Behavior
It shouldn't be allowable to completely delete the root node from within the graph manager.  This results in unexpected behavior.  Instead, pressing the "delete" button when the root node is selected should show an alert warning the user that they are attempting to delete all Children nodes.  User can cancel or go ahead and delete all children nodes but leaving the top node.

## Current Behavior
Arches deletes the top node and all children without warning

**Comment by apeters** [comment]
@dwuthrich This has been fixed for a while.  When selecting the root node the "trash can" icon disappears.  Am I missing something?

**Comment by dwuthrich** [comment]
@apeters I was able to delete the root node during testing, though I can't seem to reproduce it now.  I'll close this ticket and open a new one if I can reproduce the steps.
