### ISSUE TITLE
Track workflow data that needs to be deleted when quitting a step

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5190]
Currently the a workflow's state tracks the data that each step needs to rebuild itself. However, if a user 'quits' a workflow, all of the data created by the workflow will need to be deleted. In most cases this is just the resource instance that a step has created. In some cases, a workflow only builds onto the branch of an existing instance. Therefore, if each step sets to the state what needs to be destroyed on quit, the workflow can just access the state and delete any tiles or other artifacts that need to be removed.

**Comment by robgaston** [comment]
Would we only clean up data when the user clicks "Quit"?  What would happen if the user closes the browser window?  I'm wondering if it might be confusing to delete the created records when aborting a workflow in some cases and not others...

**Comment by chiatt** [comment]
Notifying a user that they are about to delete data is in this ticket: https://github.com/archesproject/arches/issues/5294

**Comment by dwuthrich** [comment]
meets requirements
