### ISSUE TITLE
Model flag to omit empty fields in report

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5214]
**Is your feature request related to a problem? Please describe.**

Reports for long models can be very long, and if the data is only sparsely populated, then the report can be full of `None` entries.  It would be nice to be able to not display these in the report cards.

**Describe the solution you'd like**

A configuration flag on the model (model's card) that determines whether or not None values will be displayed (as currently) or omitted from the report along with their widget label.

**Comment by azaroth42** [comment]
Doesn't work for me?
![Screen Shot 2020-08-14 at 12 30 03 PM](https://user-images.githubusercontent.com/871868/90271692-35279280-de2a-11ea-8a60-dd45dc84cad0.png)

Also ... it would be good to have a way to set this as the default as an administrator.

**Comment by azaroth42** [comment]
If the empty field (not hidden) is in the middle of a card, then the other values now slide up and get the wrong labels associated with them.

e.g. here is a note that has a language but not a type. However the value for language slides up into the type slot.

![Screen Shot 2020-08-14 at 2 01 55 PM](https://user-images.githubusercontent.com/871868/90279223-cc92e280-de36-11ea-9bf5-b166def2c839.png)

**Comment by chiatt** [comment]
Hey @ryan86 - I noticed default summary reports are not showing widgets even if data is available in the presented tile.

![image](https://user-images.githubusercontent.com/1877663/90424485-0fd99500-e073-11ea-87e8-49371cf13c8a.png)

**Comment by chiatt** [comment]
This is working as expected in the default card
