### ISSUE TITLE
Tabbed report initializes with rightmost tab open, not leftmost

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5218]
**Describe the bug**

In a left to right language, it is intuitive to start with the left most section as the first to read. The tabbed interface defaults to the rightmost tab being displayed on page load, which is unintuitive.

Leftmost tab should be opened by default.

**Comment by chiatt** [comment]
This appears fixed to me in the latest. Maybe @robgaston fixed it will working on tabbed report components? In any case @azaroth42 could you please verify that it's resolved?

**Comment by robgaston** [comment]
I think that what is actually going on here is that the default tab is the one which is active when you save the report in the designer.  I suppose this gives you a greater degree of control as a designer, but it also seems pretty unintuitive to me.... perhaps we should rework this to be a more explicit selection by the user.

**Comment by azaroth42** [comment]
Yes, that "solves" the problem ... but is not intuitive at all.
