### ISSUE TITLE
Long card labels do not wrap

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5219]
**Describe the bug**

For top level cards that contain only a single resource-instance reference, the title of the card can be quite long. In the report, these titles do not wrap over lines and instead end up underneath the data.  If there isn't any data, then they end up under the "No data added yet" default text.

**Screenshots**

![Screen Shot 2019-09-01 at 2 34 27 PM](https://user-images.githubusercontent.com/871868/64082579-002c3980-ccc6-11e9-905f-8d57186fab1c.png)

**Expected behavior**

Long title should wrap to the next line

**Comment by azaroth42** [comment]
Is the new expected behavior to truncate rather than wrap?

![Screen Shot 2020-01-06 at 11 52 36 AM](https://user-images.githubusercontent.com/871868/71844486-18003980-307b-11ea-82d4-19792f3dbe71.png)

Truncation is better than the text overwriting of course, but wrapping seems preferable. If you need a little explanation (like "Person or Group that performed this activity"), then truncating it doesn't actually help with that.

**Comment by dwuthrich** [comment]
@azaroth42 should be fixed in master

**Comment by azaroth42** [comment]
:+1: Agree fixed, thank you kindly!
<img width="351" alt="Screen Shot 2020-01-09 at 4 31 06 PM" src="https://user-images.githubusercontent.com/871868/72115928-85bb9800-32fd-11ea-9a4b-cd8ccf4efb44.png">
