### ISSUE TITLE
Branches not in graph duplicated in cards

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5220]
**Describe the bug**

In configuring a Group model, I find that I have two cards for my one Dissolution branch.

**Screenshots**

Graph Nodes:
![Screen Shot 2019-09-01 at 3 13 20 PM](https://user-images.githubusercontent.com/871868/64082904-36b88300-cccb-11e9-8a4d-e7bf95b3a696.png)

Resulting Cards:
![Screen Shot 2019-09-01 at 3 12 14 PM](https://user-images.githubusercontent.com/871868/64082905-391add00-cccb-11e9-8d91-fe70cf02e300.png)

**Expected behavior**

There should not be two cards for Dissolution!

**Comment by chiatt** [comment]
@azaroth42 Are you still seeing this issue?

**Comment by azaroth42** [comment]
No, but I'm reminded that there's a similar, transient and hard to duplicate issue of repeated cards. Will make a new ticket.
