### ISSUE TITLE
As a Resource Designer I want to select valid graphs from my Arches library so that I can quickly build a resource graph with just the data content that is important to me

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#523]
## Acceptance Criteria
- [x] After creating a new resource, I can browse a library of graphs and select those that I want to add to my resource definition
- [x] Cards can be dragged from the list of available cards onto the Resource
- [x] After selecting a graph, Arches allows me to define the property that connects the graph with my resource node

## Definition of Done
UI supports this user story

**Comment by apeters** [comment]
Generating a list of graphs should be easy.  Harder though to understand which graphs have been added (and hence should not be shown) to a resource (see #526 for more details about this).

**Comment by dwuthrich** [comment]
meets requirements
