### ISSUE TITLE
RTF widget - edit detection fails when moving back and forth between cards

### ISSUE THREAD

**Issue by AJ-HistoricEngland** [archesproject/arches#5235]
**Describe the bug**
RTF widget fails to pickup changes and display the save and cancel buttons if you move back and forth into its card.

**To Reproduce**
1) Start creating a new resource or edit an existing one.
2) Add and new entry for a card with an RTF node.
3) Complete the data including the RTF widget.
3) Click Add
4) click out of the card to another card.
5) Go back to the card entry just created and edit the rtf value.
6) The save edit and cancel edit buttons do not show - don't seem to detect the RTF dirty state.
7) to fix you need to click into another card and then back in for the buttons to appear.

**Screenshots**
![FjPhNX9X0k](https://user-images.githubusercontent.com/25295526/64431287-077e8900-d0b2-11e9-92ec-67d0e540ec30.gif)

**Expected behavior**
The Save and Cancel edit buttons should always show after the RTF input receives a change to its data

**Your Arches Information**

*   Version used: 4.4.1
*   Operating System and version (desktop or mobile): Windows 10
*   Browser Name and version: Brave/Chrome/FF

**Comment by chiatt** [comment]
Works as expected.

**Comment by AJ-HistoricEngland** [comment]
Great, thanks guys! Is there another 4.4.x release due? In the mean time I'll look to amend our project with the code changed in #5332
