### ISSUE TITLE
Map Card Component: hover styles for related application areas 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5255]
When using the related application area card, it would be a better UX if we could style a geometry on mouse over (e.g.: a hover style).  Also, there's no way to return the map to the selected geometry(ies); the user has to zoom out, identify the selected geometry, then zoom in to see their selected application area. 

See: https://recordit.co/dNoSyVroMi

This ticket describes a specific case, but it would be great to implement a solution that works generically for any overlay that supports geometry selection.

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #503](https://github.com/archesproject/arches-her/issues/503) via [**ZenHub**](https://www.zenhub.com/)
