### ISSUE TITLE
Implement Date+Time Picker widget

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5256]
The current date widget only allows the selection of a date, and not a particular time of day.  When the information is being newly entered, and the activity being described is either current or very recent, we very likely know more than just the day.  For example in DISCO, we might wish to record the exact start and end of an experiment, rather than just the day that it occurred on. This could be important, for example, when correlated against weather or other time variable factors.

**Comment by chiatt** [comment]
This has been merged in, but there is still and issue with advanced search #6492
