### ISSUE TITLE
Cannot create geospatial data with new map card component

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5261]
It is possible to create new instances while Arches is processing long running imports (e.g.: lincoln_release).  For example, creating a new Activity instance and is allowed.  However, the map card component fails to initialize with the following errors (which appear to be related to trying to access search overlays such as the hex bin) while data are loading.

**Comment by dwuthrich** [comment]
![Screen Shot 2019-09-10 at 4 04 49 PM](https://user-images.githubusercontent.com/815185/64656780-66f7d400-d3e5-11e9-9bdb-8478b210a142.png)

**Comment by dwuthrich** [comment]
Update: even after loading data, the map card component does not show map, precluding the ability to manage geospatial data.

To reproduce, update a model in the lincoln release package to use the new map card component.  Attempt to edit data with the new component and note the issue

**Comment by robgaston** [comment]
the package used in writing this ticket was on an outdated version of mapbox gl js - the solution here was to update client-side packages.
