### ISSUE TITLE
Big unclosable incomprehensible "New" box appears on edit and report view

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5265]
**Describe the bug**

See the subject and the screenshot! This is running on master as of 2019-09-10.

**Screenshots**

![Screen Shot 2019-09-11 at 1 15 37 AM](https://user-images.githubusercontent.com/871868/64680099-f75c0600-d431-11e9-9ab4-2e4546b75841.png)

**Comment by azaroth42** [comment]
Ahh, it appears whenever you try to create a resource-instance link. I guess to create a new resource of a different model. Can we please have the old UI back while this is being developed, as it's impossible to interlink resources at the moment.

**Comment by dwuthrich** [comment]
This is also a problem when trying to access a related resources node in Arches Designer.  See:https://recordit.co/KFwuv9eugQ

**Comment by chiatt** [comment]
Hey @azaroth42 & @dwuthrich, I just merged a fix for this. When you get a chance can you pull from master and confirm it's reloved?

**Comment by azaroth42** [comment]
Hooray, thanks @chiatt! Works for me in current master :)  I like the new (?) ability to create a new resource in the form of something else. I guess that it picks only the card that is designated as being the name descriptor function?

**Comment by dwuthrich** [comment]
@azaroth42 It picks the top card in the card tree, as defined in Arches Designer.  A (probably) good future enhancement would be to allow the designer to specify which card to show when creating a new instance

**Comment by azaroth42** [comment]
Ahh, I'll check that the top card is always name in my models then :)

**Comment by dwuthrich** [comment]
meets requirements
