### ISSUE TITLE
Graph Manager: Defining Domain Node Workflow

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#527]
Defining a domain node in a graph implies that the designer will need to associate it with a concept in the RDM.  

## Expected Behavior
When creating a node with the domain data type, Arches should allow the graph designer to select the top concept for the domain from a list of existing concepts in the RDM.

The Dropdown should allow the graph designer to add a new top concept to the RDM if the designer wants to associate the domain node with a concept that doesn't already exist in the RDM 

## Current Behavior
Currently this ability isn't supported

**Comment by dwuthrich** [comment]
based on discussion on 6/14, the most compelling way to support this requirement will be to allow the graph designer to link an E55 node to an RDM concept when they are configuring the data entry card (e.g.: in the "Card Manager" workflow)

**Comment by robgaston** [comment]
Based on our latest thinking, we will need to first provide support for storing JSON configurations on the `nodes` table based on the selected data type.

The form for defining a node configuration (and therefore selecting the top level concept) should be presented in the nodes form in the Graph Manager, rather than in the Card Manager.

**Comment by dwuthrich** [comment]
Is this true?  Does the form for defining the top concept of a “domain” node need to be in the Graph Manager?  There is benefit to keeping it in the Card Manager (e.g.: a Domain expert or RDM person could make the selection instead of the more “restrictive” graph manager role).



Dennis Wuthrich
CEO Farallon Geographics  |  www.fargeo.com <http://www.fargeo.com/>
601 Montgomery St, Suite 1095 | San Francisco, CA  94111
T 415 227 1140  |  Cell 415 317 2771

**Comment by robgaston** [comment]
It should probably appear in both the card manager and the graph manager.

But more to the point - this configuration object must be stored in the `nodes` table and not in the `cards_x_nodes_x_widgets` table, as these configurations are not purely for presentation purposes  (as the widget configurations are).

Presenting this form in both places should be almost trivial.  I think we will want to allow people working the Graph Manager to edit these configurations without jumping to the Card Manager.

My primary concern here is that (as we've done w/ cardinality) these configurations are associated to the `nodes` records rather than the `cards_x_nodes_x_widgets` records and that the form we present (where ever it resides) is based on the data type and configuration object defined in the `nodes` table (as they are not simply about presentation).

**Comment by dwuthrich** [comment]
Agree that the main point we're talking about nodes.  But it is a UI concern as to where a user interacts with this.  And having the form in both Graph and Card Manager probably makes sense.

**Comment by robgaston** [comment]
Cool, we can target to have them in both (just like we are doing w/ validations right now).

Important point here is that this form should implement our new `nodes.config` column (re: #735)

Thanks for the input!

**Comment by robgaston** [comment]
related to #736 - need to load authority document data before we can implement this

**Comment by ryan86** [comment]
There is concept data in the arches resource json that is loaded by default when import_json is called. If authority document load is a blocker I think this data can be used to complete this ticket.

**Comment by robgaston** [comment]
I think we should hold off on this ticket until things settle generally around our concept data.  This includes:

- finalizing loading of authority documents
- revisiting RDM and indexing of concept data (as this will probably have an impact on the UI for selecting a top level concept)
- a mockup or spec for top level concept selection tool in node/widget forms

Also, this work is related to (and should probably be done in conjunction with) #724

**Comment by apeters** [comment]
Technically the domain node is powered not by Top Concepts, but concepts that are defined as Collectors (ie show up in the Dropdown Lists category of the RDM.

**Comment by dwuthrich** [comment]
This could really simplify things.  Maybe the concept node automatically creates a collector in the Dropdown lists category of the RDM (meaning that the user doesn't need to do this manually).

The RDM Manager would then define which concepts are included in the dropdown list category associated with each concept node

**Comment by robgaston** [comment]
That would work well - then we would still probably need to use the node config to store the pointer to that collector (uuid), but we wouldn't need to present any UI to the end user for managing this value (as we could automatically create it on node save).

What this does imply is a way to hook into saving of new nodes and execute some logic based on the node's selected datatype.

**Comment by dwuthrich** [comment]
Yes, it probably avoids the need for UI and sets a pattern for saving new nodes.

It also suggests that import/export of resources/graphs is simplified.  Importing an existing resource/graph now only requires adding collector nodes in the RDM of the target Arches instance.  Actually populating the collector nodes becomes a configuration workflow for the RDM manager

**Comment by apeters** [comment]
> What this does imply is a way to hook into saving of new nodes and execute some logic based on the node's selected datatype.

I don't quite get what you mean?

Once a designer has selected a Collector concept as powering the dropdown for a node.  That uuid is saved in the config object.  The domain data type and associated widget then are smart enough to use that uuid to generate a list of values to populate the dropdown.  The node itself just stores a concept id.  And validation can automatically happen against the users selected value and the values defined in the Collector concept based on nodes config stored in the cards_x_nodes_x_widgets table.

**Comment by robgaston** [comment]
@apeters I guess I'd expected that we would create a collector node when a new node w/ datatype 'concept' was saved.

Is the idea, then, that a collector concept must already exist in the RDM before the node can be assigned to it?

**Comment by apeters** [comment]
Another wrinkle. @adamlodge mentioned that designers might want to further filter the list of concepts presented to the user, but still validate against a superset of that list.  To achieve this filtering of the list might not happen with a Collector concept, but in a filtering function applied after the fact (either client-side or server-side)

**Comment by robgaston** [comment]
@apeters that further filtering would be driven in the widget config.  ie our 'concept' widget can provide for client level filtering mechanisms

**Comment by apeters** [comment]
>Is the idea, then, that a collector concept must already exist in the RDM before the node can be assigned to it?

@robgaston yeah, that was my understanding (simplifies things in my estimation)

**Comment by robgaston** [comment]
@apeters nice, I agree that would simplify things

**Comment by dwuthrich** [comment]
@robgaston @apeters I think that creating a concept node should automatically create a collector concept.

**Comment by apeters** [comment]
@robgaston, yeah I think we should keep the 2 use cases separate, ie:
- Management of concepts and dropdowns is done in the RDM
- Assignment of what Collector concept to associate with which domain datatype node happens in the Card Manager

**Comment by dwuthrich** [comment]
This make managing skos files independent of designing graphs/resources

**Comment by apeters** [comment]
>I think that creating a concept node should automatically create a collector concept.

@dwuthrich I think that might lead to a lot of junk in the RDM.  

> This make managing skos files independent of designing graphs/resources

We SHOULD keep these two functions independent, which is why we should only allow Card/Graph Designers to select from a know list of Collector concepts.  If we want we can provide a link to add a new concept in the RDM (assuming they have the privileges).

**Comment by apeters** [comment]
I think this will also reinforce the different workflows.  ie:
- Management of concepts and dropdowns is done in the RDM
- Designing cards is done in the Card Manager

**Comment by adamlodge** [comment]
@dwuthrich: hopefully this clarifies a bit...

When we load authority files we create both a top node concept and a collector concept (as two separate concepts.)  I know that we have spoken about the two interchangeably in the past, but they are saved as seperate concepts. In the 90% case where we load authority files, we create both a "top node" and separately as a collector concept (to power dropdowns for E55s.)  These collector concepts will be readily available for use by domain/concept nodes in the graph.  

In the 10% case, RDM users will manually create custom collections of concepts (custom collections) which are made available for use by domain/concept nodes after they are created.

**Comment by apeters** [comment]
I think this workflow is working now.

**Comment by dwuthrich** [comment]
meets requirements
