### ISSUE TITLE
Notification banner is not rendering in workflow steps. 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5273]
The default card component has a pageVm object that creates the error notification at the top of the page view. This is undefined when the card component is created in a workflow step, causing errors to fail silently.

  ![Screen Shot 2019-09-12 at 11.00.06 AM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/693613ed-af2c-4f41-830b-d16a8b508f8e)

**Comment by dwuthrich** [comment]
meets requirements
