### ISSUE TITLE
Graph Manager: Move Node Form alerts to global alert panel

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#528]
## Expected Behavior
User alert messages should be displayed in the global alert panel

## Current Behavior
Node form is used to display alerts in the Graph Manager

**Comment by robgaston** [comment]
fixed in #531

**Comment by dwuthrich** [comment]
Alert displays as expected.  However, canceling from the alert form dismisses the Node CRUD form.  Instead, form should stay open but edits should be discarded

**Comment by robgaston** [comment]
I think what we want to happen is the following:

- if the user clicks 'cancel' (meaning, cancel the change in selection) or the 'x' button the form should remain open with the original node selected and the edits remain in place
- if the user clicks okay, then the edits are discarded (as explained in the alert itself) and the users action that triggered the alert proceeds
- if the user triggered the alert by selecting another node (either through the graph or the node list), then the newly specified node should be selected and loaded into the node form

**Comment by dwuthrich** [comment]
meets requirements
