### ISSUE TITLE
As a Resource Manager, I want to manage resource definitions to ensure that I'm working with just the resources that I want

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#529]
## Acceptance Criteria
- [ ] A Resource may be deleted, but only if no instances are associated with it
- [ ] A Resource may be modified (e.g.: the resource graph may be modified), but only if no instances are associated with it
- [ ] A Resource may be made "inactive" so that no new resource instances can be created
- [ ] A Resource may be cloned at any time.  Cloning a Resource means copying its settings, graph, card configurations, forms, and reports
- [ ] Unit Tests passed 
- [ ] Documentation

**Comment by apeters** [comment]
I'm closing this because I believe that we most of the desired functionality described above is now included in the application
