### ISSUE TITLE
Map Overlays do not layer as defined in the overlay panel, drag&drop overlays breaks display

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5297]
The order of overlays in the overlays panel should inform the z-index of layers.  However, this is not the case and using the drag&drop causes overlays to disappear from the map: https://recordit.co/lpYSUm9X24

**Comment by robgaston** [comment]
This seems to stem from an issue with our usage of the knockout `sortable` binding handler.  I haven't yet been able to solve the issue, but what I've observed is that on occasion (conditions as yet unknown) using the drag-and-drop resort functionality results in duplicate entries in the overlays array (which then results in errors).

**Comment by dwuthrich** [comment]
There is still an issue with drag&drop of overlays; results in the dragged overlay dropping from the list of overlays.  See: https://recordit.co/DxuDjlw7RU

**Comment by chiatt** [comment]
@apeters and I confirmed that overlays are now rendering properly in the latest after dragging and dropping layers.
