### ISSUE TITLE
[Extension] datatypes not processed for JSON-LD import

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5299]
**Describe the bug**

The code here: https://github.com/archesproject/arches/blob/master/arches/app/utils/data_management/resources/formats/rdffile.py#L478 

has a hard-coded list of datatypes to check for. The subsequent algorithm does not have a fallback case, it only explicitly checks for semantic (line 488) and resource-instance (line 516). After this, the loop ends with all other datatypes being dropped.

This is likely part of the cause of concept-list and resource-instance-list not being processed, as they will not be caught here.  It also means that additional datatypes installed from packages, such as a [URL datatype](https://github.com/thegetty/arches-urldatatype), will not be processed despite having a `from_rdf()` function defined.

**To Reproduce**

Install a datatype package and try to import an instance that uses it.
(Or any other datatype not listed above)

**Ticket Background**
*   Found by: @benosteen

**Comment by azaroth42** [comment]
Could this be as simple as testing the value of datatype.is_a_literal_in_rdf() and if the value is False, then recursing, and if True, then stopping?

With the exception of concept, which is covered by #5136 anyway, the entries in L478 is the set of builtin datatypes that map to literals. 

Thus something like:

```
if found_node['node'].datatype.is_literal_in_rdf() and json_data_is_valid(found_node['node'], jsonld_graph):
    self.logger.debug("Matched {0} and the json fragment is valid".format(datatype))
    return found_node
```

Would catch the literal types, and then go back to something closer to the original code commented out at line 525 that doesn't check for datatypes explicitly.

(Making test cases for this and #5136 but it means cloning my environment again to avoid using the Linked Art ontology)

**Comment by azaroth42** [comment]
Rather than relying on (e.g.) https://github.com/thegetty/arches-urldatatype, I think we should make a test case package that installs a literal datatype and a non-literal. 
Deferring building a test until we can discuss what is the most stable to build on.

**Comment by azaroth42** [comment]
Another thought ... if someone were to make a datatype that should act exactly like "semantic", **including the peek-ahead**, but with one slight tweak then there's no way currently to implement that as the peek-ahead is determined by the test in `findBranch()` and semantic doesn't have a class that defines it (as far as I can see?)

**Comment by apeters** [comment]
Let's create a semantic datatype and add a method to the base class to process the branch and populate that method with this
```  
  if found_node['node'].datatype == 'semantic':
    self.logger.debug("Node is semantic node. \
        Recursively search for the children of this node and match to branch.")
    self.logger.debug('now searching children of {0} node UUID {1}'.format(
        found_node['node'].name, found_node['node'].pk)
    )
    for ontology_prop in self.findOntologyProperties(jsonld_graph):
        try:
            self.logger.debug("Matches {0}?".format(ontology_prop))
            branch = self.findBranch(found_node['children'], ontology_prop, jsonld_graph[ontology_prop])
        except self.DataDoesNotMatchGraphException as e:
            self.logger.error("Data supplied does not match")
            found_node['remove'] = True
            invalid_nodes.add((found_node['node'].name, found_node['node'].pk))
        except self.AmbiguousGraphException as e:
            # Not sure this will be called, given the structure of this code
            # Adding a debug logger just in case it might
            self.logger.debug(
                "AmbiguousGraphException thrown while iterating through semantic node children."
                )
            # print 'threw AmbiguousGraphException'
            # print nodes_copy
            pass
```

**Comment by azaroth42** [comment]
Demo data type for literal could be color - reports as a string "#FFFFFF" (etc) 
Demo data type for non-literal - clone of semantic with no other features, other than being in an extension

**Comment by azaroth42** [comment]
@apeters I can't build a test for this until there are the datatypes to test with.

**Comment by azaroth42** [comment]
:-1: 

https://github.com/archesproject/arches/blob/json_ld_enhancements/arches/app/utils/data_management/resources/formats/rdffile.py#L379-L390

Is still very data type dependent.

**Comment by azaroth42** [comment]
:+1: Looks good to me. Haven't tested by creating a new datatype, but the tests with datatypes pass and reading through the code, nothing refers to datatypes by name, only their features via extensible functions.

**Comment by azaroth42** [comment]
Agree fixed :)
