### ISSUE TITLE
Map Card: Add a tool for buffering a feature for use as a drawing

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#5320]
We need to add a tool to the map card that will allow a user to select a feature for buffering, and use the buffered geometry as a new drawing.

**User Story**

As an editor, I want to buffer a feature in the map card and use this as a drawing in a geojson feature collection node value.

**Definition of Done**

**Ticket Background**
Follow up with @robgaston on how this should work in the Map card UI. Will possibly be driven by map pop ups.

**Comment by chiatt** [comment]
Implemented in #6951
