### ISSUE TITLE
Add widget "name" to widget.attributes object

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5324]
Among the things needed to instantiate a component to show tile data paired with its widget label is the widget `name`. Example:
```
<td style="border:1px solid black;" data-bind="component: {
            name: widget.widgetLookup[widget.widget_id()].name,
            params: {
                 tile: tile,
                 node: widget.node,
                 config: widget.config,
                 label: widget.label(),
                 value: tile.data[widget.attributes.node_id()],
                 state: 'display_value',
                   }
}"></td>
```
While the name is available via the route of widgetLookup, it might streamline things a bit if the name were just another observable in the `widget.attributes` object.

**Comment by robgaston** [comment]
It probably shouldn't be an observable, as this value is an immutable (at run time) member of the `widgets` table (not the `cards_x_nodes_x_widgets` table, which is what is represented by the `Widget` viewmodel referenced above.  It might be nice to attach the entire `widgets` record to this viewmodel, but we should not conflate onto `attributes` values which are not members of the record that this model is meant to manage.

**Comment by chiatt** [comment]
Closing based on @robgaston's explanation
