### ISSUE TITLE
Active Consultations: Concepts and Resource Instances are displayed as UUIDs not labels

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5333]
There is a regression in Active Consultations where concept labels and resource instances are displayed as UUIDs not labels or instance identifiers (in the case of resource instances).

![Screen Shot 2019-10-01 at 1.45.36 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/e2276a9d-d2be-441b-8bba-c43bb958eafc)

**Comment by robgaston** [comment]
the simplest way to address this would be to use our existing widgets in their `display_value` state as we do here: https://github.com/archesproject/consultations-prj/blob/master/consultations_prj/templates/views/components/reports/consultations-status.htm

**Comment by robgaston** [comment]
Issue moved to [archesproject/consultations-prj #333](https://github.com/archesproject/consultations-prj/issues/333) via [**ZenHub**](https://www.zenhub.com/)
