### ISSUE TITLE
Replace basestring and unicode() with str and str()

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5342]
All instances of basestring with str and the unicode() builtin method with the str() builtin method. Also remove the b' prefix. This is used twice on lines 104 and 117 in arches/app/models/migrations/0010_4_1_0.py

It may be best to first make these changes with 2to3, and then confirm these changes have been made as expected. To target these specific changes run: `2to3 -w -n -f unicode -f basestring arches`

**Comment by whatisgalen** [comment]
no occurrences of either basestring or unicode, closing
