### ISSUE TITLE
Convert sibling imports to relative imports and import StringIO and cpickle from standard lib

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5354]
1. Convert sibling imports to relative imports: `2to3 -w -n -f import arches`
2. Make StringIO and pickle imports v3 compatible. After running `2to3 -w -n -f imports arches`, include changes to StringIO and pickle imports, but do not include changes to the urllib usage

**Comment by chiatt** [comment]
Changing pickle and StingIO imports causes a unicode error, so that change should be made after the v3 upgrade.

**Comment by whatisgalen** [comment]
pickle and StringIO imports work as expected post v3 upgrade, closing
