### ISSUE TITLE
package_load breaks 

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5382]
package load is breaking due to errors related to concepts/collections

**Comment by mradamcox** [comment]
It strikes me that the encoding may need to be set to 'utf-8' in this update? Has it been tested with non-ascii characters?

**Comment by whatisgalen** [comment]
@mradamcox thanks for catching that -- I just pushed a change to this python3 branch so that by default import of csv files uses utf-8 encoding.

**Comment by chiatt** [comment]
Works as expected
