### ISSUE TITLE
When reindexing the database, there appears to be a mismatch with the number of concepts indexed

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5384]
When running: `python manage.py es index_database`
This status message appears (when using the consultations package)
> Indexing concepts
Status: Failed, In Database: 16946, Indexed: 16776, Took: 7 seconds

**Comment by whatisgalen** [comment]
Still seeing this error on latest master

**Comment by apeters** [comment]
this is best tested with the consultations package because it has orphaned concepts

**Comment by chiatt** [comment]
Works as expected
