### ISSUE TITLE
Implement PostGIS MVT API

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#5394]
as part of the move to Python 3, we are likely to retire TileStache.  As part of this, we need a new solution to serving resource data up are vector tiles.  We propose extending the API to include an MVT (mapbox vector tile) endpoint, which would use the default functions `ST_AsMVT` and `ST_AsMVTGeom` that PostGIS provides. 

Note: as part of this, we may need to move to PostGIS 3 (which will be released imminently) in order to support `feature-state` in mapbox gl js (https://github.com/postgis/postgis/pull/303)

**Comment by mradamcox** [comment]
What would happen if for some reason we weren't able to move to PostGIS 3? This sounds great overall.

**Comment by robgaston** [comment]
@mradamcox not sure I follow... do you mean if the project can't move to PostGIS 3 or a specific implementor?

if the project moves to PostGIS 3 (which seems likely), then all implementations will be required to upgrade when moving to arches 5.  If they cannot for some reason, then they will not be able to migrate to arches 5 (just as with the other dependencies being upgraded).

if for some reason the project cannot upgrade to PostGIS 3 (which seems very unlikely) then we will need to re-evaluate, but as implemented everything we had working w/ TileStache works using PostGIS expect for `feature-state`, which we use for hover styling.

**Comment by mradamcox** [comment]
@robgaston Yeah, I meant the latter, but both are relevant. Sounds like it's PostGIS 3 or bust. This may be difficult as it seems to require postgres 12 https://postgis.net/2019/08/11/postgis-patches/ which is not yet available on Amazon RDS, which some Arches users use. (I'm not sure about corresponding Azure services.) However, Arches 5 is presumably still at least a few months away so maybe that will become a non-issue soon enough.

**Comment by robgaston** [comment]
@mradamcox I don't think that postgis 3 requires postgres 12, from the link you posted:

> PostGIS 3.0.0rc2
> The PostGIS development team is pleased to release PostGIS 3.0.0rc2. This will be the final RC before release. **This release works with PostgreSQL 9.5-12 and GEOS >= 3.6**

**Comment by mradamcox** [comment]
I was thinking of right after that where it says

> Best served with PostgreSQL 12beta3. Designed to take advantage of features in PostgreSQL 12 and Proj 6

and assumed that some of the things you wanted were these new things in pg 12.

**Comment by robgaston** [comment]
@mradamcox the change that we need in postgis 3 is just a minor change to the `ST_AsMVT` function that supports assigning feature ids; I believe that it does not depend on any new features of postgres 12 or proj 6

**Comment by dwuthrich** [comment]
meets requirements
