### ISSUE TITLE
Graph Manager: Alert user if top node is a collector when changing Graph to Resource

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#540]
### Bug Report

When trying to change a graph to a resource the option button (under the status tab in the settings form) may appear unresponsive.  This can happen if the graph's top node is a collector, which is not allowed for a resource.  In such cases, Arches should alert the user that the graph they are working with has a collector top node.  This will let the user know they'll need to edit the graph's top node before attempting to convert the graph to a resource

**Comment by dwuthrich** [comment]
Alert should appear when user selects the "status" tab

**Comment by robgaston** [comment]
Perhaps, given the increasing distinction between graphs and resources (in terms of validation rules, etc.), we should consider just removing the ability to change this value in the UI entirely (thus removing the ability to switch between graph and resource).

**Comment by dwuthrich** [comment]
meets requirements

**Comment by dwuthrich** [comment]
meets requirements
