### ISSUE TITLE
Report Template: Map template no longer shows map

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5405]
Instances that have been configured to use the map report template no longer display a map in the resource editor

![Screen Shot 2019-10-18 at 1.24.06 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/947dff2c-83d0-41d9-944d-4d9b21fd4a4f)

**Comment by robgaston** [comment]
fixed in `python3`

**Comment by dwuthrich** [comment]
meets requirements
