### ISSUE TITLE
Nodegroup data no longer cascades on update

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#541]
When updating a node's collector state via the node form, the node group information does not seem to cascade up/down the graph properly.

This could be an error in the logic that handles the cascading, or it's possible that it has something to do w/ not updating nodegroup information properly on branch append.

In either event, it makes testing the node grouping rule enforcement (#517 & #534) difficult because nodegroups behave in unexpected ways.

**Comment by apeters** [comment]
can you add some code comments to this? Thanks
