### ISSUE TITLE
cannot save tile with DomainDataType

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5411]
to reproduce:

If consultation-prj is loaded, try adding new resource instance of Actor and then try to save a tile for the "Name(s)" card, picking a domain value for "Currency"

**Comment by whatisgalen** [comment]
Pausing this due to the following unanswered questions:
1) Is there a way to grant a user group/role permission to one plugin and not another?
2) should all user groups for a project by default have the "view all plugins" permission (aka `view_plugin`)?
cc @apeters @robgaston @dwuthrich

**Comment by chiatt** [comment]
Works great in latest
