### ISSUE TITLE
adding related resources can inadvertently double-add a resource, cause buggy delete

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5414]

**Comment by chiatt** [comment]
@whatisgalen Does this apply to the generic resource to resource relationship or the newer node to instance relationship?

**Comment by whatisgalen** [comment]
I'm not 100% sure which relationship, but the issue happened when I was editing a resource instance and I clicked "Related Resources" in the editor tree, and then was adding other instances in the select2 dropdown input, clicking "add"

**Comment by whatisgalen** [comment]
works as expected (tested using new bidirectional resource relations)
