### ISSUE TITLE
Rename default db postgis template to "template_postgis"

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5454]
Arches assumes a postgis template name of "template_postgis_20", which doesn't exist by default in newer versions of postgres/postgis and which throws an error on initial install.  What should exist is a template named "template_postgis" which we should standardize on in our settings.py file.

**Comment by chiatt** [comment]
@apeters It looks like the Ubuntu install script still creates a postgis_20 template

**Comment by apeters** [comment]
thanks for catching that @chiatt.  I usually filter out .sh files when i do global searches, so those files fell through the cracks.

**Comment by chiatt** [comment]
Looks great
