### ISSUE TITLE
Allow host/model/uuid as resource-instance reference for import

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5465]
**Is your feature request related to a problem? Please describe.**

While it's not necessary to validate that the UUID of a resource-instance reference being imported is of the correct model (e.g. that the given UUID that goes into a Place node is actually an instance of the Place model), it would certainly prove troublesome down the line.

If the resource has not been created yet, then there is no way to determine its model from just a UUID.  Given that there must be the opportunity to backfill like this (to avoid a circular reference case being unable to be created) then there should be a way to define the model up front during import.

**Describe the solution you'd like**

The solution discussed was to use a URI for the resource that includes the UUID or slug of the model.  Thus if the slug is "place", then the reference could be `http://localhost:8000/resources/place/uuid-goes-here` and the importing code could check that the model is available for use by that resource-instance.

This comes from discussion of #4564

**Comment by apeters** [comment]
fixed in the latest
