### ISSUE TITLE
Rename "Import Graph" to "Import Model" in graph designer menu

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5494]
**Describe the bug**

The Manage menu for graph designer refers to models as both Graphs (Import Graph) and Models (Export Model).  This is confusing, and should use consistent terminology.

**To Reproduce**

Click on the Manage menu in Graph Designer.

**Screenshots**

![Screen Shot 2019-10-31 at 12 09 49 PM](https://user-images.githubusercontent.com/871868/67978533-905c0180-fbd7-11e9-8b9d-aa4d6535e9d7.png)

**Expected behavior**

References should be consistent. All of the other items use "Model", and thus so should Import.

**Comment by apeters** [comment]
fixed in the latest
