### ISSUE TITLE
Setting default value for concept-select does not trigger dirty state

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5501]
**Describe the bug**

If a widget is not visible, then changing the default value does not trigger a dirty state, and thus enable the Save Card Edits button.  However adding a default value needs to be saved, regardless of the visibility of the card.

**To Reproduce**

* Go to the card of a concept data type. 
* Set the card to not be visible
* Save the card
* Change the default value.

**Comment by chiatt** [comment]
Fixed in the latest
