### ISSUE TITLE
bulk_create for relations

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5513]
presently (commented out), `bulk_create` for relations throws an error about breaking the table's rules. Fixing this problem could make this section of package_load run faster

**Comment by chiatt** [comment]
@apeters If we bulk load instances with the resource instance datatype, will the relationship record be created or would we need to load a relations file? If we don't need the relations file for the new datatype, maybe we should delete this ticket?

**Comment by chiatt** [comment]
Closing as this issue falls under #6442
