### ISSUE TITLE
Update UI to reflect the new naming of the 'Collector' switch

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#552]
Names to use instead of "Collector" can tentatively be:
1. Root Card (on the root node show as disabled)
2. Make Card (on any child of root that isn't contained by a group other than the root group)
3. Make Sub Card (on any child of a group this isn't the root group)
The switch should be disabled for any node that is a child within a Sub Card

**Comment by robgaston** [comment]
This is sort of hard to test with a resource given how parent groups currently
cascade - I'd recommend testing w/ a new graph probably.

Also, we need to open a ticket for fixing the way the root card's group cascades
down to child nodes nodegroups as a parent group.

**Comment by apeters** [comment]
Yeah, I don't know if I can evaluate this and I can't seem to get the UI to show "Make Card" as the text of the switch.

**Comment by robgaston** [comment]
You should be able to test w/ a new graph.  Check out this screen capture showing the labels update:
![1esap2fneu](https://cloud.githubusercontent.com/assets/1187406/16099564/c4d8f076-330d-11e6-9a99-ae14f6a9df63.gif)
