### ISSUE TITLE
Search results no longer show resource name, description

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5537]
![Screen Shot 2019-11-09 at 3.36.00 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/98901db3-0815-43fe-ae74-70fa8d27a138)

**Comment by chiatt** [comment]
@dwuthrich I noticed this over the weekend. I pushed a fix yesterday. I didn't see this ticket at the time. I wrote #5538 and did my work against that ticket number, so I'm going to close this ticket and give you #5538 to QA.
