### ISSUE TITLE
Write logic to export search results in shp format

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5545]

**Comment by apeters** [comment]
I get an error when trying to open the .zip file from shp download (I don't get this from .csv download)

**Comment by chiatt** [comment]
@apeters I'm not getting an error. What error are you seeing?

**Comment by chiatt** [comment]
Oh - I'll bet you don't have any geometries included as exportable nodes.

**Comment by apeters** [comment]
this works in the latest
