### ISSUE TITLE
Graph Manager: Adding E62 (String primitive) to a graph is not possible

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#556]
### Bug Report

Arches won't allow user to add an E62 class (string primitive) to a graph 

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by apeters** [comment]
You can, but you may have to unselect the currently selected property to get the E62.String class to show up.  Remember that those 2 dropdowns are filter each other.  If a property is selected it could be filtering out the E62.String class.

**Comment by dwuthrich** [comment]
meets requirements
