### ISSUE TITLE
update arches requirements in arches docs

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5567]

**Comment by whatisgalen** [comment]
see this PR for reference:
https://github.com/archesproject/arches-docs/pull/146

**Comment by mradamcox** [comment]
thanks @whatisgalen! in the future you can put tickets like this directly in the arches-docs repo, that way, if you need to, the #ticketnumber references that you put in commit messages when changing the docs can directly reference this ticket.

**Comment by chiatt** [comment]
Yeah @mradamcox, docs was the right spot for this ticket.  Transferring.

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-docs #161](https://github.com/archesproject/arches-docs/issues/161) via [**ZenHub**](https://www.zenhub.com/)
