### ISSUE TITLE
Add new ubuntu_setup bash script to include dependency updates

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#5569]
**User Story**
A new setup script should be shipped with Arches that will install the dependencies on Ubuntu. The newly targeted versions are:
Postgres 12
PostGIS 3
Elasticsearch 7 (this is a new addition to the setup script)

Node/Yarn, CouchDB, and Java (only used for Elasticsearch) don't need to be updated.

**Acceptance Criteria**
-   [ ] all arches dependencies install by running the script

**Definition of Done**
A new script will be added to arches/arches/install. Ultimate it should take the place of `ubuntu_setup.sh` but I think for this ticket making an additional (and clearly named) file should be sufficient.

**Comment by mradamcox** [comment]
@chiatt I think this can be closed now, right?

**Comment by chiatt** [comment]
@mradamcox - It is. Thanks for that PR!
