### ISSUE TITLE
Graph Manager: Node Form seems to take some time to be responsive after appending a node

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#557]
### Bug Report

After appending a node to a graph,  the node form takes time to appear or to become responsive.  We should include a UI element (e.g.: spinner) to indicate to user when the node form is ready for interaction.  

This spinner should appear in the node form panel (as opposed to on the page)

**Comment by apeters** [comment]
No need to add a spinner as the form now updates much faster.

**Comment by dwuthrich** [comment]
meets requirements
