### ISSUE TITLE
Graph Manager: Add Graph dropdown to Settings, Graph Manager title bars

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#558]
### Bug Report

It would be convenient to be able to toggle between graphs/resources from both the settings page and the graph manager pages.  

If easy, we should include a dropdown (like the UI shows for data entry cards) that would allow the user to toggle between graphs/resources without having to return to the Resource Designer home page.

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by robgaston** [comment]
@dwuthrich Unless I'm mistaken, I think we've already got this feature - see the screen capture below:

![nz6mtmiu3l](https://cloud.githubusercontent.com/assets/1187406/16089444/f99d8804-32df-11e6-931c-490671bf3abf.gif)

Is this the feature that you're referring to here, or am I missing something?

**Comment by dwuthrich** [comment]
meets requirements
