### ISSUE TITLE
Write a task notifying a user that their export is available for download

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5582]
If a user executes a search export, their export file is saved to the file system. Once it's saved, they need to be notified that the export is done and provided a link to the file for download.

**Comment by apeters** [comment]
@whatisgalen 
I make some comments related to `app/tasks.py` and `utils/zip.py` that need to be addressed.

**Comment by chiatt** [comment]
@apeters Regarding the comments you had the for the path of the search export files, I'm going to address them in this ticket: https://github.com/archesproject/arches/issues/5605.

**Comment by apeters** [comment]
works in the latest
