### ISSUE TITLE
Graph Manager: Top node name of new graph should default to graph name

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#559]
### Bug Report

On creation of a new graph: use the graph name as the default name of the graph's top node.

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by robgaston** [comment]
should we allow the name of the root node of a graph to ever be different from the name of the graph itself?

Currently these are distinct values ( and ), and are assigned independently in the UI… I’m wondering if perhaps we should just always keep these two values in sync (and, thus, [potentially] remove entirely….).

**Comment by robgaston** [comment]
decided to just rename the root node of the graph to "Top Node"

**Comment by dwuthrich** [comment]
meets requirements
