### ISSUE TITLE
rdffile.py get_resource_id() doesn't work

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5599]
**Describe the bug**

Further to #5095, the `get_resource_id` in rdffile doesn't work.

In particular:

* `@id` will always be a single string, so no point iterating through a singleton list.
* It doesn't check for urn:uuid:[uuid-here]
* When you turn it on via `use_ids`, it then tries to get the resource ... which for PUT does not exist yet, and hence fails.

This would be valuable for POST to /resources/model-slug/  to use the internal URI.  

There should be a test for this ... but that would mean a way to manipulate use_ids!

**Comment by azaroth42** [comment]
I believe that this is fixed in v5

**Comment by chiatt** [comment]
@azaroth42 Can you confirm if this is an issue an go ahead and close it if it looks okay?

**Comment by azaroth42** [comment]
Yup, we fixed by rewriting the whole thing :)
