### ISSUE TITLE
Ensure that only the user that downloaded a search export has access to the URL

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5605]
To ensure that only the user that has requested a search export has access to it, we should create a database record for each search export zip file. Url to download the file should point to a Django view that checks if the user has access to the file before it is downloaded.

**Comment by apeters** [comment]
@chiatt I'm not even sure how to test this as I can't seem to get a "link".  Downloads happen by button press and no "link" is available.

**Comment by chiatt** [comment]
@apeters The link should appear in your notifications

**Comment by apeters** [comment]
fixed in the latest, makes me wonder if we should allow downloads by the `anonymous` user
