### ISSUE TITLE
Geometry type config is cleared when a user adds multiple geometry nodes to a graph

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5606]
When a user adds multiple geojson-feature-collection nodes to a graph, the widget config for the second node can lose the geometry types that the widget can collect  (Point Line and Polygon by default). When a user tries to edit data for that node, they will find that they cannot create any geometry types.

**Comment by robgaston** [comment]
@chiatt I think that this is fixed in the latest - can you please confirm?

**Comment by chiatt** [comment]
The problem is resolved in the latest.
