### ISSUE TITLE
Add notification type schema

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5613]
Users will need to be able to indicate what kinds of notifications they want to be alerted to and how they want to be notified. Each notification type will need a 

- typeid
- name 
- email template (likely a path to the django template file)
- preferred notification methods (defaults)

A user_x_notification_types table will also be needed with

- user FK
- notification type
- preferred notification methods (email, web)

A foreign key to the notification type table will also need to be added to the notification table

**Comment by apeters** [comment]
working in the latest
