### ISSUE TITLE
Verify that core datatypes deliver proper human readable values to export

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5617]
The file datatype for example needs to provide a link to the file in Arches

**Comment by whatisgalen** [comment]
@apeters as part of this ticket, I wasn't sure what the best "human readable" format for edtf datatypes was so I just changed it to read from the node's `"value"` key.

**Comment by apeters** [comment]
i think we can remove the `get_tile_data` method on the `FileListDataType`.  This was throwing an error for search export

**Comment by apeters** [comment]
fixed in the latest
