### ISSUE TITLE
disable appending of branches that violate grouping depth constraint

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#563]
In the graph manager UI, we need to somehow prevent users from appending branches to a graph that will create invalid graphs based on grouping depth.

To do achieve this, a few ideas come to mind... we could:
- [x] filter the branch list to exclude branches that would create an invalid graph
- [x] disable branches in the branch list from being selected when they would create an invalid graph
- [x] disable the 'append branch' button in the branch info panel when the appending the branch would result in an invalid graph

The rules the UI will have to follow:
 - Any Graph can be appended to a Resource as long as the Graph has at it's root a node group
 - Any Graph can be appended to any other Graph as long as the resultant Graph doesn't have more then 1 level of nested node groups

**Comment by robgaston** [comment]
@apeters it looks like we still need to disable the ability to append a branch when the root of a graph is not card/collector (ie the 'single node graph' case) (related to my incoming fix for #517 [PR #583])

**Comment by apeters** [comment]
This appears to be fixed as long as #614 is fixed
