### ISSUE TITLE
Shapefile Export: Only enable Step 3: Email Address when Celery is configured and query exceed limit

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5651]
For large downloads with Celery enabled, Arches will alert the user when their file is ready for download.

The download panel includes a place for users to enter an email address for Arches to email a notification when the download file is ready.

This input field should be enabled when the query results exceed the search download limit AND Celery is enabled.

This input field should be hidden if Celery is not enabled

**Comment by apeters** [comment]
fixed in the latest
