### ISSUE TITLE
Search Results Export: Duplicate field names cause Arches UI to hang

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5652]
Trying to save a search export field name that is a duplicate causes Arches to hang on the refresh screen.

Arches throws the following errors in browser console:

jquery.min.js?_dc=5.0:2 POST http://localhost:8081/node/e4b3562b-343a-11e8-b509-dca90488358a 500 (Internal Server Error)
send @ jquery.min.js?_dc=5.0:2
ajax @ jquery.min.js?_dc=5.0:2
_doRequest @ abstract.js?_dc=5.0:87
save @ node.js?_dc=5.0:301
viewModel.saveNode @ graph-designer.js?_dc=5.0:192
viewModel.saveSelectedNode @ graph-designer.js?_dc=5.0:207
(anonymous) @ knockout-latest.js?_dc=5.0:100
dispatch @ jquery.min.js?_dc=5.0:2
y.handle @ jquery.min.js?_dc=5.0:2
graph-designer.js?_dc=5.0:193 Uncaught TypeError: Cannot read property 'success' of undefined
    at n.<anonymous> (graph-designer.js?_dc=5.0:193)
    at n.callback (node.js?_dc=5.0:295)
    at Object.complete (abstract.js?_dc=5.0:90)
    at u (jquery.min.js?_dc=5.0:2)
    at Object.fireWith (jquery.min.js?_dc=5.0:2)
    at k (jquery.min.js?_dc=5.0:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js?_dc=5.0:2)
(anonymous) @ graph-designer.js?_dc=5.0:193
callback @ node.js?_dc=5.0:295
complete @ abstract.js?_dc=5.0:90
u @ jquery.min.js?_dc=5.0:2
fireWith @ jquery.min.js?_dc=5.0:2
k @ jquery.min.js?_dc=5.0:2
(anonymous) @ jquery.min.js?_dc=5.0:2
load (async)
send @ jquery.min.js?_dc=5.0:2
ajax @ jquery.min.js?_dc=5.0:2
_doRequest @ abstract.js?_dc=5.0:87
save @ node.js?_dc=5.0:301
viewModel.saveNode @ graph-designer.js?_dc=5.0:192
viewModel.saveSelectedNode @ graph-designer.js?_dc=5.0:207
(anonymous) @ knockout-latest.js?_dc=5.0:100
dispatch @ jquery.min.js?_dc=5.0:2
y.handle @ jquery.min.js?_dc=5.0:2

What should happen:  We should show user a warning that they're trying to save a duplicate field name, and tell them which node is already configured with the name

**Comment by chiatt** [comment]
Closing this because it will be resolved as part of #5641
