### ISSUE TITLE
Create config files for supervisor/celery setup

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5667]
**User Story**

Enables the user to copy and modify configs and to setup supervisor/celery on their linux machine (by following the related docs)

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [x] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
meets requirements
