### ISSUE TITLE
DateTime datatype needed to capture sub-day time granularity

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5669]
**Is your feature request related to a problem? Please describe.**

For non-historical events, such as a conservation scientist performing an experiment in the modern day, we know the time at which the activity occurred to a much finer granularity than just the date.

The current date datatype only supports, as expected, Year / Month / Day, and now down to hours, minutes, seconds, subseconds or timezones.

**Describe the solution you'd like**

A new datatype  should be added that can record and make searchable hours/minutes/seconds and process timezones if specified.

Data in RDF should be expressed as per date -- as a xsd:dateTime in ISO format.
Incoming data should persist these values, from this format.

**Additional context**

* Discussed with @apeters and @dwuthrich on call 2019-12-10.
* Important for DISCO and surprised that it hasn't come up for consultations (etc)

**Comment by chiatt** [comment]
re #6043

**Comment by chiatt** [comment]
The date datatype now supports the following formats: https://github.com/archesproject/arches/blob/0e1832b4a4edd0cdba5d9366fe8bd57cdd2e608d/arches/settings.py#L428-L441

The widget still needs to be updated per ticket: #5256. re archesproject/arches-collector#610
