### ISSUE TITLE
Collector Manager Map Extent is broken

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5673]
Trying to define the map extent for a Collector project fails.  See:
![Screen Shot 2019-12-11 at 2.02.42 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/264953fb-91ce-44aa-b1aa-48cbc437231e)

**Comment by chiatt** [comment]
@robgaston Did you fix this already? It seems to be working for me in the latest.

**Comment by robgaston** [comment]
yep - fixed.
