### ISSUE TITLE
Strings that look like dates breaks the indexer

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5677]
**Describe the bug**

After loading a document that has a string datatype field that has a value which sometimes looks like a date and sometimes does not, elasticsearch will subsequently complain for every single record that it can't index the offending record.

Despite a datatype being set to `string`, the document produced for elasticsearch does not map this explicitly to a string. When the automapper first determines how to index the field, it selects either date or string and then fails subsequently when encountering the other.

**To Reproduce**
1. Create a model with a string literal
2. Create an instance with the field set to a date-like string, such as "2000-01-01"
3. Create a second instance with the field set to a non-date-like string, such as "fish"
4. Observe the indexing failure

**Screenshots**

```
2019-12-12 10:44:47,141 arches.app.search.search WARNING  2019-12-12 10:44:47.141069: WARNING: failed to index document: { ...

 'data': {'5c7b85ea-1872-11ea-8ff9-acde48001122': '1690-06-30'}, 'nodegroup_id': UUID('5c7b1b00-1872-11ea-8ff9-acde48001122'), 'sortorder': 0, 'provisionaledits': None}, {'tileid': '3a382cfe-f7c4-44e3-a983-40a99d2ccae1', 'resourceinstance_id': UUID('00748c09-7853-42be-bf63-fd2507b80ce1'), 'parenttile_id': UUID('04baecf3-f70b-49bf-8646-67ff0fc28657'), 'data': {'5c7b7f82-1872-11ea-8ff9-acde48001122': '1690-07-01', '5c7b8d2e-1872-11ea-8ff9-acde48001122': '1690-06-30', '5c7b967a-1872-11ea-8ff9-acde48001122': '1690-06-30 to 1690-06-30'}, 'nodegroup_id': UUID('5c7b29e2-1872-11ea-8ff9-acde48001122'), 'sortorder': 0, 'provisionaledits': None},
...

 {'string': 'offered at auction', 'nodegroup_id': '5c7b5336-1872-11ea-8ff9-acde48001122', 'provisional': False}, {'string': 'Auction of Lot Br-A45 [B]0022 (1690-06-30)', 'nodegroup_id': '5c7b67a4-1872-11ea-8ff9-acde48001122', 'provisional': False}], 'dates': [{'date': 16900701, 'nodegroup_id': '5c7b29e2-1872-11ea-8ff9-acde48001122', 'nodeid': '5c7b7f82-1872-11ea-8ff9-acde48001122', 'provisional': False}, {'date': 16900630, 'nodegroup_id': '5c7b29e2-1872-11ea-8ff9-acde48001122', 'nodeid': '5c7b8d2e-1872-11ea-8ff9-acde48001122', 'provisional': False}], 'domains': [{'label': 'note', 'conceptid': '20d28e7a-0d4f-4055-b1cd-cf6f264e8432', 'valueid': '5e89d4e0-392c-4ad4-bd02-e5254e8a4740', 'nodegroup_id': '5c7b2474-1872-11ea-8ff9-acde48001122', 'provisional': False}, 
...
Exception detail: RequestError(400, 'mapper_parsing_exception', "failed to parse field [tiles.data.5c7b967a-1872-11ea-8ff9-acde48001122] of type ***[date]*** in document with id '00748c09-7853-42be-bf63-fd2507b80ce1'. Preview of field's value: '1690-06-30 to 1690-06-30'")
```

**Expected behavior**
The elastic mapper should reflect the datatype of the data ... which is `string` and index only as a string, despite looking (sometimes) like a date.

**Your Arches Information**

master as of 2019-12-12

**Comment by chiatt** [comment]
@azaroth42 Is this still an issue?

**Comment by azaroth42** [comment]
I can't reproduce in current master by following above steps. Closing.
