### ISSUE TITLE
Repeated nodes to cardinality 1 branch incorrectly error

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5687]
**Describe the bug**

Although the export works as expected when created by hand, if there is a concept-list that has multiple values, and then has a concept with cardinality 1 associated, then the second instance in the concept-list will cause an error, when the import attempts to re-add the same value into the concept.

**To Reproduce**

* Create a model with a concept-list
* Add a concept with cardinality 1 as a child node
* Try to import two concepts into the concept-list, each with the same child concept 
* Observe, eg:

```
ValueError: Attempt to add a value to cardinality 1, non-list node http://www.cidoc-crm.org/cidoc-crm/P2_has_type http://www.cidoc-crm.org/cidoc-crm/E55_Type:
 {'@id': 'http://vocab.getty.edu/aat/300435443', '@type': ['http://www.cidoc-crm.org/cidoc-crm/E55_Type']}
```

**Expected behavior**

Given discussions and experiments to date, we didn't encounter this issue!

What would be good to happen is that it checks the current values to determine if the value is already there and does not re-add it, and thus does not trigger the error.

**Comment by azaroth42** [comment]
The fix:

in rdffile.py, in `data_walk()`

```
                    elif branch[0]["cardinality"] != "n":
                        # Determine if the value is the same as the current value
                        # If so, then no-op
                        bnode = result[bnodeid][0]
                        if node_value == bnode['tile'].data[bnodeid]:
                            pass
                        else:
                            raise ValueError(f"Attempt to add a value to cardinality 1, non-list node {k} {clss}:\n {vi}")
```

**Comment by azaroth42** [comment]
Fixed in v5.

**Comment by apeters** [comment]
fixed in the latest
