### ISSUE TITLE
Photo Gallery card only allows upload of 1 image, even if node is configured to support more than 1 image

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5694]
Although the Photo Gallery widget allow you to select multiple images, it only uploads the last image selected into the card, even if the node has been configured to allow multiple images

**Comment by chiatt** [comment]
Issue moved to [archesproject/consultations-prj #426](https://github.com/archesproject/consultations-prj/issues/426) via [**ZenHub**](https://www.zenhub.com/)
