### ISSUE TITLE
"load more" button UI issue in Related Resources manager

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5743]
Pictured below, "load more" button which doesn't seem to do anything but is blocking text
![Screen Shot 2019-12-20 at 2.23.49 PM.png](https://images.zenhubusercontent.com/5c509a380c48b719f602bab4/f48f044d-0d86-4e89-aa70-960b00327880)

**Comment by chiatt** [comment]
I'm closing because I am pretty confident this is the same problem causing #5609
