### ISSUE TITLE
arches-project creates bareword APP_NAME not string

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5751]
**Describe the bug**

When creating a project, the generated settings.py has a bareword interpreted as a variable instead of a string for the APP_NAME setting.

eg:

```
APP_NAME = rob_tests
```

When it should create:

```
APP_NAME = "rob_tests"
```

**To Reproduce**

Create a project, look at proj/settings.py

**Comment by chiatt** [comment]
Resolved in this commit: https://github.com/archesproject/arches/commit/0c3984c2b788ae30423995112863a594991185aa
