### ISSUE TITLE
Map Legend: Images must be served from Arches

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5754]
We use a rich text editor widget to define a resource layer or overlay's legend entry.  If a user wants to add an image as part of the legend, they can define a URL to the image.

We should provide a default folder within a project (perhaps media/legend) as the location to place image files for inclusion in the legend and confirm that the legend portion of the map widget does indeed display images

**Comment by robgaston** [comment]
@dwuthrich I don't think that there is anything we really need to add to arches here to support this.  The natural place for a user to put images that they want to use in the legend would be along with other static image files in `media/img`, which could then be used in legend html just as we would images in our regular html templates

**Comment by dwuthrich** [comment]
@robgaston If a user wanted to create legend images for models in a project (as opposed to core Arches), would they simply add the media/img folder to their project?

**Comment by robgaston** [comment]
@dwuthrich that’s right; the media folders in both arches and your project are both hosted as static files by default

**Comment by mradamcox** [comment]
If these layers are served from geoserver you can request a legend graphic directly from there with a url too... Not sure if that's relevant her but thought I'd point it out.

**Comment by dwuthrich** [comment]
@robgaston Thanks for confirming.  @mradamcox Appreciate the reminder that Geoserver can supply the legend via a service.  Closing, as this seems to be primarily a documentation issue
