### ISSUE TITLE
Issue with clicking on button in vertical menu bar

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5755]
A user must click a button the vertical menu bar twice before Arches recognizes the selected link.  The first button click is ignored.  This is an annoying UX

**Comment by dwuthrich** [comment]
see: https://recordit.co/WOZKeRcNvd

**Comment by chiatt** [comment]
This is due to a bug in the metismenu.js package. The resolution is to rewrite the vertical menu without the metismenu package.

**Comment by chiatt** [comment]
Duplicate of #4359
