### ISSUE TITLE
Update width of Photo Gallery Card Thumbnail Container when user adjusts node-tree width

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5767]
The width of the thumbnail  container is a calculated value (window width minus the width of the sum of divs outside the thumbnail container).  When a user drags the node tree container width (or clicks on a button on the vertical menu of the Photo Gallery Card) the width value should be re-calculated.

See: http://recordit.co/SuSmAxUwE2

**Comment by chiatt** [comment]
Issue moved to [archesproject/consultations-prj #429](https://github.com/archesproject/consultations-prj/issues/429) via [**ZenHub**](https://www.zenhub.com/)
