### ISSUE TITLE
Develop the Card Manager Page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#578]
<img width="1089" alt="screen shot 2016-06-23 at 2 00 23 pm" src="https://cloud.githubusercontent.com/assets/823773/16320083/e9c13158-394a-11e6-994c-27243320d018.png">

The work associated with this Epic is represented only in the page above.  The actual work to configure a card will happen in another Epic.

**Comment by dwuthrich** [comment]
meets requirements
