### ISSUE TITLE
Create Card Manger Landing Page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#579]
<img width="1089" alt="screen shot 2016-06-23 at 2 00 23 pm" src="https://cloud.githubusercontent.com/assets/823773/16320940/40d4b86c-394f-11e6-879d-faac1351c55d.png">

Reference this mockup:
http://archesproject.github.io/mockups/arches_designer_v2.html

This ticket is only about the container and endpoint.

**Comment by robgaston** [comment]
@apeters Can you quickly outline some steps for verifying that this is working?  So far, I've been unable to get cards to show up on the page at all, though the page itself loads and the side panel slides in as expected when clicking on the 'add card' button.  I can't seem to get any cards to show up in that panel, though.  Thanks.

**Comment by apeters** [comment]
@robgaston the panel only shows 'active' graphs, could that be the issue?

**Comment by dwuthrich** [comment]
meets requirements
