### ISSUE TITLE
Search Results export: appears only geometries (not other nodes) are included in shapefiles

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5793]
When opening exported shapefiles in QGIS, geometries show up in the map window.  However, opening the associated attribute table shows that no node values are present.

**Comment by dwuthrich** [comment]
This is partially fixed.  Attributes now appear, but not all nodes (as compared to the csv format download), are present.

**Comment by chiatt** [comment]
@dwuthrich This looks okay with the data I'm testing with. What package and search query are you using?

**Comment by chiatt** [comment]
@dwuthrich Could it also be that there is no geometry value in some of the resource instances? If there is no geometry value, CSV export will produce a record that cannot be exported to a shapefile.

**Comment by apeters** [comment]
this appears to be fixed in the latest
