### ISSUE TITLE
Create Card Template for use on the Card Manger landing page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#580]
<img width="258" alt="screen shot 2016-06-23 at 1 33 03 pm" src="https://cloud.githubusercontent.com/assets/823773/16319218/21ba5fde-3947-11e6-8cb4-fd3d111f97bc.png">

Mockup:
http://archesproject.github.io/mockups/arches_designer_v2.html

This template get's used for existing cards within a graph and as a list of available cards

**Comment by robgaston** [comment]
Decisions re: Card tile template:
- title will show card name
- body will show description (pulled by default from source graph record)

**Comment by dwuthrich** [comment]
meets requirements
