### ISSUE TITLE
Overlays: drag and drop does not work properly

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5800]
Dragging a layer and dropping results in its entry disappearing.  Reordering does not work when a layer is not displayed.  See: https://recordit.co/mU1upJDi85

**Comment by chiatt** [comment]
@dwuthrich I'm not seeing the same issue on my instance. Is there an error in the browser console when this occurs?

**Comment by chiatt** [comment]
@dwuthrich, @robgaston I was able to reproduce this on the QA machine running consultations. I confirmed that the version of mapbox-gl was the same as my local instance and the issue still occurred. I then reloaded the consultations package and the problem was gone.

**Comment by dwuthrich** [comment]
meets requirements
