### ISSUE TITLE
File widget: saved file names are not indexed

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5801]
To reproduce: upload files and save.  Try searching on an uploaded file name in search and note that no match is returned

**Comment by dwuthrich** [comment]
This still isn't working.  To reproduce:

1. Go to files card in consultations
2. Upload and save a text file.  Note the name of the file
3. Go to search and enter file name.  Note that search does not return an entry matching the file name

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-for-science-prj #69](https://github.com/archesproject/arches-for-science-prj/issues/69) via [**ZenHub**](https://www.zenhub.com/)

**Comment by adamlodge** [comment]
works
