### ISSUE TITLE
buggy UI in card manager w/ map card

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5805]
to reproduce: create a geojson feature collection node, select the card in the card manager

see pictured below:

![Screen Shot 2020-01-06 at 2.30.58 PM.png](https://images.zenhubusercontent.com/5c509a380c48b719f602bab4/8954f264-a002-4f7a-8571-b8a0ec7ec170)

**Comment by robgaston** [comment]
@whatisgalen I have not been able to reproduce this - likely there is some other conditions for reproduction not mentioned above.  Could you please take a look?

**Comment by whatisgalen** [comment]
@robgaston  I'm able to reproduce this on a model that was cloned, but I am not able to reproduce on a brand new model. I think we can close this maybe in favor of opening another ticket (perhaps for 5.1) to do more rigorous testing of cloned models.
