### ISSUE TITLE
domain datatype validation error

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5806]
when selecting a domain_value for a testing model, (of which there are 2 hard-coded strings) get this error:
TileValidationError: "Multiple domain values were found for '95a0be5a-6eb6-4b19-a5a5-1f267dd5dc68' .                          Please use an explicit id instead of a domain string value. This data was not imported."

Unsure how exactly to reproduce, but has since emerged after pulling the latest

**Comment by chiatt** [comment]
@whatisgalen If 95a0be5a-6eb6-4b19-a5a5-1f267dd5dc68 is a nodeid, I would find its graph and look at how the node is configured.

**Comment by whatisgalen** [comment]
this was caused by a cloned model using the same values, reasonably considered an edge case, closing
