### ISSUE TITLE
Ordering for overlays in the map manager

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#5817]
Currently, there is no way to define default ordering for the the overlays/layers in the legend and the map. (To be clear, this is distinct from the ability for users to re-order overlays in the search map legend on a session by session basis - which is already implemented.)

I think there should be a configuration in the overlays section of the map layer manager to define the default ordering for all of the layers.

**Comment by chiatt** [comment]
Duplicate of #8928
