### ISSUE TITLE
Create command to populate package from Arches instance

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#5818]
As an implementor, a common pattern is to use a pre-production (sandbox) instance of Arches to load data, test and refine models, configure overlays and basemaps, and generally dial in a myriad of details for the implementation that will eventually make their way to a separate production instance of Arches. The most obvious way to smoothly make this migration from test to prod is to populate a package with all of the configurations, reference data, concepts, etc..  that were implemented by hand in that sandbox instance.  

Given that, it would be nice to have a command that not only creates an empty package template, but also populates that template with all of the configs, reference data, and biz data pulled from a pre-prod Arches instance so that it can be easily loaded to a prod Arches instance.

This concept could be pushed even further to the project level to include things like splash page images and such.

**Comment by chiatt** [comment]
Hey @adamlodge, isn't this covered by #2779?

**Comment by chiatt** [comment]
see #2779
