### ISSUE TITLE
test cloning of models

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5819]
issues discovered specific to cloning:
- if a model uses a domain or domain-list node and the original values get preserved through cloning, this will prevent tile saves for that node due to non-unique values (see tile validation)
- if a model has a geojson feature collection node using the Map Card, the cloned model card configuration UI will break and possibly other consequences for this node/card (on the clone)

**Comment by chiatt** [comment]
Divided ticket into #5901 and #5902
