### ISSUE TITLE
equality query in Adv. search against a numeric field throws an error

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5826]
![Screen Shot 2020-01-08 at 2.46.48 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/81244318-ea5e-4494-b8ef-5c76d53303e7)

We're using a "Match" query when we should probably just be using a range query with "gte" and "lte"

**Comment by whatisgalen** [comment]
working in the latest, closing
