### ISSUE TITLE
Create an Add-In for ArcGIS Pro to Allow ESRI Users to edit Arches instance data

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5869]
From the SOW:

Farallon will develop an Add-In that manages an ArcGIS Pro user’s abilty to work with Arches data in near-real time.  The Add-In will:

- Require that an esri ArcGIS Pro user log-in to Arches to authenticate their credentials and determine their data access privileges
- Cache a user’s session metadata locally within esri (e.g.: authentication tokens, edit history data, etc.)
- Determine which Arches models an esri user has privileges to access and allow them to request data to edit 

The Add-In will use the GeoServices published by Arches to display data on a map within ArcGIS Pro.  When users select a specific location from the GeoService, the Add-In will query the Arches API (Application Programming Interface) and request the suite of data for the data instance (compatible with the user’s privileges) and the model metadata needed to properly represent the data.  

Esri users with the appropriate privileges will be able to edit or delete existing Arches data by clicking on an Arches GeoService geometry.  The Add-In will allow esri users to create new data to push into Arches by clicking a button and creating a new record.

**Comment by robgaston** [comment]
presumably, we should create a new repo for this plugin and ultimately track our work on this there

**Comment by apeters** [comment]
closing this in favor or this ticket here: https://github.com/archesproject/arches-esri-add-in/issues/1
