### ISSUE TITLE
Create an endpoint that can update Arches resource instance data

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5871]
From the SOW:

The Add-In will be responsible for managing the transfer of instance data between Arches and ArcGIS Pro.  This means that when an esri user saves information, the Add-In will use Arches API to push data to Arches and retrieve any new data that may have been created by other Arches users.

As with Arches web editor, data edits will be considered provisional unless the esri user logs in with appropriate credentials.

**Comment by chiatt** [comment]
Meets requirements
