### ISSUE TITLE
ES Indexing may fail when there is a provisional edits

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#5873]
**Describe the bug**

The indexing database for elasticsearch (running "python manage.py es index_database") may fail,
when a provisional edits are present in the database.

It is specific for the file-list data type, but there can be other data type has the same issue.

This is probably due to the append_to_document will try to access the tile data which may not be available for the provisional edits.

**Comment by chiatt** [comment]
Works as expected in the latest
