### ISSUE TITLE
alert panel on graph manager not working

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#588]
repro steps:
1) open graph settings page for any graph
2) edit the name field, but don't click save
3) click the exit button

expected behavior:
the alert should show up confirming the user's desire to navigate or save first

actual behavior:
alert is not shown and navigation appears to not work as a result

I suspect this may have been caused in by some style changes to the alert panel.  We should confirm our fixes here don't ding alert panels on other pages as I suspect may have happened here.

**Comment by dwuthrich** [comment]
meets requirements
