### ISSUE TITLE
improve package.json management

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#5913]
currently, users need to manage package.json for both arches and their projects with duplicated dependencies.

Instead, we should allow packages to define arches as a dependency such that project dependencies can be managed separately.

This will require moving package.json back to the project root directory

**Comment by chiatt** [comment]
The following libraries do not load into the project when arches is declared as a dependency:

- eonasdan-bootstrap-datetimepicker
- metismenu
- jquery-migrate
