### ISSUE TITLE
Deleting node sometimes deletes parent node

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#592]
repro steps:
- create a new resource
- append the 'Node/Node Type' graph to the top node
- click the 'Node Type' node in the graph
- click the trash can to delete node
- click the trash can to delete 'Node' node

expected behavior:
- Node should be available to delete

actual behavior:
- Trying to delete 'Node' results in an error.  Refreshing the page seems to show that the 'Node' node was deleted

screencast:
![uqpbwb580w](https://cloud.githubusercontent.com/assets/1187406/16748714/a46e7c8a-477a-11e6-9324-46d3957843ed.gif)

**Comment by apeters** [comment]
appears fixed on my local machine
