### ISSUE TITLE
Updated Graph/Resource List Page Design

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#593]
Rework the graph/resource list page as per the minor changes in this latest mockup: http://archesproject.github.io/mockups/arches_designer_v2.html

changes:
- updated header with:
    - toggle for 'Resources' and 'Graph Library'
    - 'Find' button w/ chosen dropdown with graphs & resources grouped
- content of list is filtered based on selection in header ('Resources' or 'Graph Library')

**Comment by dwuthrich** [comment]
meets requirements
