### ISSUE TITLE
Error in graph designer when trying to change node type

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5966]
After creating a model, adding instances, then deleting instances I get the following error when changing a data type:

Unable to save collector project, failed to connect to couchdb.

This save operation has nothing to do with collector projects and couchdb is running.

![Screen Shot 2020-03-06 at 11.07.19 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/66c5966e-9c13-4759-a5de-48514da2d99c)

**Comment by chiatt** [comment]
No longer able to reproduce.
