### ISSUE TITLE
IIIF card: need to support search-based selection of IIIF endpoint in addition to direct entry of URL

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5972]
The IIIF card will need to support a way to configure the URL input box to support search of valid IIIF URLs.  Possible approaches might include:

1. Defining a resource model and the node containing a IIIF manifest URL as a way of defining the IIIF endpoint in. the card.

2. Defining an search service (e.g.: an API endpoint) that supports search of IIIF manifest URLs

**Comment by robgaston** [comment]
@dwuthrich to my knowledge, no such service as 2 exists, so it would have to be 1 or something like it.  That being said, I'm wary of adding this into the card component itself - IMHO this would be better handled in a separate workflow step as the mockup suggests

**Comment by dwuthrich** [comment]
@robgaston Not all IIIF card users will access the card from a workflow, so we should be thinking about how to ease discovery of manifest URLs when the card does not participate in a workflow

**Comment by robgaston** [comment]
@dwuthrich that's fair, but it is unclear to me how to do that in any kind of a generic way; further discussion is probably required

**Comment by dwuthrich** [comment]
@robgaston Agreed that we need to discuss how to address this issue in a generic way

**Comment by robgaston** [comment]
Should implement a very simple table-based lookup here for the generic case

**Comment by dwuthrich** [comment]
meets requirements
