### ISSUE TITLE
Active consultations plugin: sorting by date is reversed

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5974]
In the active consultations plug-in, sorting by date is reversed.  Selecting "Log Date: newest to oldest" lists the oldest logged consultation first.  Selecting "Log Date: oldest to newest" lists the newest first

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #515](https://github.com/archesproject/arches-her/issues/515) via [**ZenHub**](https://www.zenhub.com/)
