### ISSUE TITLE
Consultations pop up does not show related application area

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5975]
The application area name is not displayed in the consultation map pop-up.  

What should happen:
> Show name of related application area(s) if it exists in the consultation instance
> Print "No related application area" if no app area exists in the consultation instance

![Screen Shot 2020-03-11 at 10.27.39 AM.jpg](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/d28c1f2f-96ba-40c7-a5b8-0eb1db2ce179)

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #502](https://github.com/archesproject/arches-her/issues/502) via [**ZenHub**](https://www.zenhub.com/)
