### ISSUE TITLE
Consultations search: overlay map popups do not work

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5976]
In the consultations search page, users can add map overlays.  Clicking on a vector in the map overlay breaks the map pop-up panel.

What's happening:
1. Clicking on an overlay vector does nothing when no map popup is visible (even though this works in Arches' default search page)
2. Clicking on an overly vector when a consultation pop up is open causes the search page to attempt to load the overlay vector data into the consultations map pop up.

What should happen: 
Clicking an overlay vector should show a popup, as is done in the default search page

https://recordit.co/PzoybXb799

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #518](https://github.com/archesproject/arches-her/issues/518) via [**ZenHub**](https://www.zenhub.com/)
