### ISSUE TITLE
Consultations Report: Status header is red, regardless of date/status of consultation

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5977]
The consultation status header in the info box on the first page of the report is always red (see attached image).

What should happen:
> For active consultations, header color should match the logic in the Active consultations plugin
> For in-active consultations, header color should be #f8f8f8![Screen Shot 2020-03-11 at 10.57.43 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/3027725e-3dc8-4c17-8932-6ee56fb20913)

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #466](https://github.com/archesproject/arches-her/issues/466) via [**ZenHub**](https://www.zenhub.com/)
