### ISSUE TITLE
Consultations Report: show related application area in the map header

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5978]
Currently, the map header shows the location of the consultation geometry, but not the related application area(s).

What should happen:
Map header should display both the consultation geometries and the related application area geometries

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #464](https://github.com/archesproject/arches-her/issues/464) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #465](https://github.com/archesproject/arches-her/issues/465) via [**ZenHub**](https://www.zenhub.com/)
