### ISSUE TITLE
Resource Editor Tree: Add a tool to clone tiles (where card cardinality is "n")

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#5984]
In the resource editor tree, it would be helpful if there was a way to clone existing tiles for cards that have a cardinality of "n".  This might be done by right clicking on the tree node and selecting from a context menu, or as a button that appears in the tree node itself.

**Comment by chiatt** [comment]
re #5772

**Comment by chiatt** [comment]
This is completed
