### ISSUE TITLE
Geojson data type: Add selected class to show which geometry is currently selected in map and workbench cards

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5985]
UX would be improved if we can style the currently selected geometry in the list of geometries.  

See: https://recordit.co/Aj9M7xkTAt

**Comment by robgaston** [comment]
@dwuthrich shown here is not the geojson datatype, but the annotation datatype.  Also, the screen capture shows zooming to the feature, not "selecting" it (which is done by clicking "Edit").  When a feature is "selected" (or in the edit state), it should already show as highlighted in both the table and on the canvas.

**Comment by robgaston** [comment]
@dwuthrich you can also "select" features by clicking on them on the map

**Comment by dwuthrich** [comment]
@robgaston  Thanks for the clarification.
