### ISSUE TITLE
File Viewer Card: In data tab, select file be clicking on the row in the table listing available files

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5987]
Users can add additional data to a chart by selecting a file from the Data tab of the card.  Currently, a user has to click the "+" button to select the file.

What should happen:
1. User should be able to click on the row to toggle adding/removing the data file to the chart
2. By default, we should show an icon in front of the file name.  Icon: fa-check-circle color: #f2f2f2.  Selecting the file should update the color of the icon to #3acaa1.  Remove the "+" button

**Comment by chiatt** [comment]
No longer applies
