### ISSUE TITLE
Enhance IIIF Gallery: support full screen view

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#5996]
@dwuthrich commented on [Fri Mar 06 2020](https://github.com/archesproject/arches-for-science-prj/issues/47)

Update the IIIF gallery component as follows:

1. Allow image gallery to expand to full height of card component (whether in a workflow step or in a resource editor)
2. Allow user to reduce image gallery to normal size (via down carat next to "Gallery" label in mockup)
3. Allow user to hide gallery (via hide gallery link)
4. Allow user to filter current set of canvases in the currently selected IIIF manifest (see mockup)
5. Provide a toggle to allow user to select a new IIIF endpoint (e.g.: "image" link in mockup)
6. Show canvases in manifest in a grid, make each canvas thumbnail larger
7. Show the canvas' label below the thumbnail
8. If the canvas has been annotated, highlight the border of the thumbnail and show the number of annotations below the canvas label![Screen Shot 2020-03-06 at 3.51.30 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/fdb21f9f-3b28-423f-9c05-2ced0d1cdfa0)

**Comment by dwuthrich** [comment]
meets requirements
