### ISSUE TITLE
Uploading documents panels contain misspelled word: 'drop' as 'dop'

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6007]
@rebecca23williams commented on [Wed Feb 19 2020](https://github.com/archesproject/arches-her/issues/451)

#### describe the issue
The uploading documents sections across all cards that contain them display the word 'dop' rather than 'drop'.

![uploadDocsPanel](https://user-images.githubusercontent.com/47248246/74819086-bed12a00-52f7-11ea-8454-917a23b9c752.png)

**Comment by dwuthrich** [comment]
meets requirement
