### ISSUE TITLE
Resource-instance datatype: config node to point to a graph and specify a default ontology property and reverse ontology property

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#6019]
When designing a graph that has a resource to resource datatype, we need to be able to specify an ontology property and reverse property (if the graph is semantic).

For backward compatibility, the ontology property can be optional

**Comment by dwuthrich** [comment]
meets requirements.  Will write a ticket on enhancing how to label properties

**Comment by dwuthrich** [comment]
meets requirements
