### ISSUE TITLE
Add card page: drag & drop

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#602]
allow for drag & drop from card list on left to add to resource

**Comment by dwuthrich** [comment]
Drag and Drop a single card from the card library to the resource panel results in multiple copies of the card appearing on the resource panel

**Comment by robgaston** [comment]
@dwuthrich Looks to be working in the latest:

![ugzgnqjmta](https://cloud.githubusercontent.com/assets/1187406/16927728/b913dd6a-4ce3-11e6-8744-0a1b6e637f30.gif)

Am I missing something in the repro steps here?

**Comment by dwuthrich** [comment]
Here's what I get when working on dev.archesproject.org
http://recordit.co/wOSckkTBMB

**Comment by dwuthrich** [comment]
meets requirements
