### ISSUE TITLE
Domain Values in a branch causing errors when used in multiple resources models

### ISSUE THREAD

**Issue by Philbox** [archesproject/arches#6037]
**Describe the bug**

If a datatype of Domain Value is assigned to a node in a branch, and the values added to the node, when the branch is then added to 2 or more resource models it throws out a tile validation error when attempting to create a new instance
![image](https://user-images.githubusercontent.com/16647003/77753889-44947380-7022-11ea-80e6-53b56261ec85.png)
 . 

**To Reproduce**
1. Create a branch with a node with datatype Domain Value
2. Add Domain Values to the node
3. Add the branch to Resource Model 'A'
4. Create an instance of Resource Model 'A' using the branch- No error
5. Add the branch to Resource Model 'B'
6. Create an instance of Resource Model 'A' using the branch - Error

**Screenshots**

![image](https://user-images.githubusercontent.com/16647003/77754240-d43a2200-7022-11ea-9317-4ff364b1db36.png)

**Expected behavior**

I expect the branch to allow the creation of an instance using the domain values

**Your Arches Information**

*   Version used: 5
*   Operating System and version (desktop or mobile): Windows 10
*   Browser Name and version: Chrome Version 80.0.3987.149 (Official Build) (64-bit)
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @Philbox

**Comment by chiatt** [comment]
Hey @Philbox - Can you confirm that this is still an issue. It should be fixed in the latest by this PR: https://github.com/archesproject/arches/pull/6053/files

**Comment by chiatt** [comment]
Closing unless the problem presents itself again
