### ISSUE TITLE
Min / Max zoom settings have no effect in v5

### ISSUE THREAD

**Issue by reubenosborne1** [archesproject/arches#6038]
**Description**
I have noticed that the values of "Min Zoom" and "Max Zoom" , in system settings, have no effect in Arches v5.
Seems to always be a full range of zoom (e.g 0, 20)...

**Your Arches Information**

*   Version used: 5
*   Operating System and version (desktop or mobile): Ubuntu 18.04LTS
*   Browser Name and version: Google Chrome Version 80.0.3987.87

**Ticket Background**
*   Found by: @reubenosborne1

**Comment by chiatt** [comment]
Hey @reubenosborne1, I've merged a fix into master. Can you confirm that it's resolved when you get a chance?

**Comment by njkim** [comment]
The max/min zoom works as expected
