### ISSUE TITLE
IIIF card: image does not display properly when user dismisses workbench panel

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#6080]
@dwuthrich commented on [Wed Mar 18 2020](https://github.com/archesproject/arches-for-science-prj/issues/77)

The IIIF image does not refresh properly when a workbench side panel is dismissed.  User has to resize browser window for leaflet to display image properly: https://recordit.co/ruaHykxBqc

**Comment by dwuthrich** [comment]
meets requirements
