### ISSUE TITLE
IIIF card does not allow provisional editors to create new tiles

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#6089]
Resource editors with full CRUD permissions but who are not members of the Resource Reviewer group can not add new annotation tiles

**Comment by whatisgalen** [comment]
this works as expected however one small note is that when the provisional editor has saved their edit, the icon in the card in the card tree does not get colored yellow as expected thus it was unclear at the time if I had saved only a provisional edit or in fact somehow saved an authoritative edit. When logging in as Admin all indications show the yellow / provisional edit styling thus it seemed to have worked fine.
