### ISSUE TITLE
File datatype import does not create file table record

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#6093]
When importing a file from a csv/json import does not create a record in the file table. The following information is stored in the file table: fileid, path, tileid

This can cause files that are imported (as opposed to created in the UI) to not be deleted from the file system when deleted from the UI.

**Comment by chiatt** [comment]
Perhaps import and export should etl the 'files' table records. During import, after the resource instance load is done, we would recreate the files records from a csv file similar to how we manage related resource records.

**Comment by njkim** [comment]
It works as expected
