### ISSUE TITLE
Uploaded files are served directly from the web server without authentication

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6094]
Uploaded files are served directly by the web server running Arches. If someone has the url to a file, they can access it without authentication. We should allow admins to configure arches so that file requests are proxied over a login protected view. The accepted answer of this post describes one way of doing this:

https://stackoverflow.com/questions/9454302/protecting-user-uploaded-files-django

Ideally the use of the proxy view would be optional because serving files directly from Apache or other web server is more performant than proxying requests. Also, in many cases, node and resource permissions are probably sufficient in preventing unauthorized people from getting file urls.

**Comment by apeters** [comment]
fixed in the latest
