### ISSUE TITLE
Reports: Resource instance reports should support a new "summary" context

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#6124]
Resource instance reports should provide support for a new "summary" context.  This summary report should be generic for the default report template, but could be customized for specific resource models at the project/package level.

Summary reports might nest summaries of other related resource instances.  We should consider if the proposed "summary" context is suitable for this use case, or it this is in fact a distinct context (ie "nested summary" or similar).

Examples of where this could be used would be in a new search component that renders a summary of the selected result instance(s) or in a workflow step or card component that provides a richer interface for selecting (related?) resource instances.

**Comment by chiatt** [comment]
Looks great
