### ISSUE TITLE
new-multi-tile-step workflow component styling

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#6148]
The card component `new-multi-tile-step` has a button labeled "continue" that does not appear at the bottom of the UI as intended. Reproducible in arches-for-science project, activity workflow

![Screen Shot 2020-05-01 at 3.36.12 PM.png](https://images.zenhubusercontent.com/5c509a380c48b719f602bab4/82774086-bcf2-42f5-a5f7-9ecb664734bb)

**Comment by chiatt** [comment]
Fixed in #6183
