### ISSUE TITLE
Card Manager: Better Error Message when trying to add card whose CRM Class doesnt support a property to connect to resource

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#617]
#### Expected Behavior

Arches message should be more helpful when an error occurs in the card manager.  For example, Arches should state that the graph can't be connected to a resource for a specific reason, not a generic "contact admin"
#### Current Behavior

When dragging a card onto the resource in the card manager, an error message is thrown the says "contact admin" when the reason is that the graph's top node and the resource's top node can't be connected via a valid CRM property
#### Steps to Reproduce (for bugs)
1. Create a resource with an "E7_Activity" as the root class
2. Create a branch with "I1_Argumentation" as the root class
3. Go back to your resource and click "Data Widgets and Cards" then "Add Card"
4. Notice that the card based on the branch you just created (with "I1_Argumentation") is available to append (it shouldn't be and in fact is filtered out when using the graph manger)
5. Try to add the card to the resource, see the error message pop up

![screen shot 2016-10-20 at 12 29 07 pm](https://cloud.githubusercontent.com/assets/823773/19574855/dd22e9fe-96c0-11e6-8bea-9b3e877b4c05.png)

**Comment by chiatt** [comment]
It looks like this bug may have been resolved by filtering out unsupported CRM classes from available cards.  I followed the steps to reproduce the error and when I go to 'Data Widgets and Cards' I do not see the branch I created with 'I1_Argumentation' as the root node.

**Comment by dwuthrich** [comment]
meets requirements
