### ISSUE TITLE
enable configuration of remotely-hosted iiif manifest json and cantaloupe server

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#6180]
currently the file_to_iiif function assumes that the cantaloupe server is local (via hardcoded port) and also serves the manifest json locally via "uploaded files" directory in the project

**Comment by chiatt** [comment]
This can probably just be a setting

**Comment by chiatt** [comment]
It looks like there is now a setting for the Cantaloupe endpoint. There is probably more work to be done to support a remote Cantaloupe server, but for the time being I am going to close this ticket until there is an immediate use case.
