### ISSUE TITLE
Update UI of Resource-to-Resource manager

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#6182]
Need to include Node-to-Resource data in the “Related Resources” search filter and force directed graph visualization. We need to improve the current presentation of the related resource force directed graph as follows:

- Upgrade the current visualization library (e.g.: D3.js v3.x to v5.x) (re #6469)
- Improve how relationships between instances are displayed

**Comment by apeters** [comment]
@chiatt Could you QA this ticket.  Everything has been merged into master for a while.  I think you could probably just close this, but maybe you can just quickly review all the areas in the app where the R-I instance widget and datatype are used just to make sure everything is functioning.

**Comment by chiatt** [comment]
@apeters This got a pretty thorough review during the release testing.
