### ISSUE TITLE
Update Node api endpoint to handle datatypes other than geometries

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6185]
Currently the tile api is really intended to handle data for the geojson datatype. It should be updated to process data for any datatype.

**Comment by apeters** [comment]
I thought that we were going to make this a more general method that would take in an incoming format to use in deciding how to transform the data .
eg: process_api_data --> transform_data(format='arcgisjson')

**Comment by ryan86** [comment]
@apeters we added the 'transform_value_for_tile' and 'update' methods to the datatypes to support generic transformation of incoming data and update of existing tile data with that incoming data if necessary. In the nodeValue endpoint in api.py you'll now see we call `data = datatype.transform_value_for_tile(data, format=format)` then later `data = datatype.update(tile, data, nodeid, action=operation)` (the latter only when we are appending to existing tiledata).

**Comment by chiatt** [comment]
Yeah - I think the process_api_data method was left in after @ryan86 added `transform_value_for_tile`. I believe it's no called anywhere. I'll go ahead and remove it.

**Comment by apeters** [comment]
I think the title of this should be "update NODE endpoint...." (I'll edit the title to reflect that)
in any case this is fixed in the latest
