### ISSUE TITLE
Changing default value in graph designer for concept card doesn't trigger dirty state

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6189]
**Describe the bug**

When you change the default set of values for a concept / concept-list node in the card in graph_designer, it does not set the dirty state flag and thus you can't save the change.

The workaround is to change the name of the card, set the new defaults, save, then change the name back, and save again.  Clearly this is very inefficient use of administrator time!

**To Reproduce**

Make a model with a concept in it.
Set the default value for the concept in the card.
Save and reload
Change the default value in the card.
See that the save changes button does not appear.

**Expected behavior**

Changing the default should trigger dirty state to allow saving.

**Your Arches Information**

Current master.

**Comment by chiatt** [comment]
Use the textInput binding

**Comment by azaroth42** [comment]
Working for me now in master.

**Comment by chiatt** [comment]
Thanks @azaroth42
