### ISSUE TITLE
As a user I want to be able to view the different components of a card (card, subcard, widget) so that I can select them for editing

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#620]
![screen shot 2016-07-19 at 10 00 51 am](https://cloud.githubusercontent.com/assets/823773/16958982/bf43c1d2-4d97-11e6-8241-3b7250c6b54d.png)

### User Story
The tree based layout should reflect the names of each card, subcard, or widget and should update when a user updates those attributes of the selected item.

#### Acceptance Criteria
- [ ] Card labels should default to graph names
- [ ] Sub card labels should default to node names
- [ ] Widget labels should default to node names
- [ ] Unit Tests passed
- [ ] Documentation

**Comment by dwuthrich** [comment]
meets requirements
