### ISSUE TITLE
Card container editor - as a user I want to be able to edit the attributes of a card container 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#621]
![screen shot 2016-07-19 at 10 26 26 am](https://cloud.githubusercontent.com/assets/823773/16959732/4c5e64ca-4d9b-11e6-8f0f-9fc4d696a6a1.png)

#### Acceptance Criteria
- [x] Settings should default to Visible and Active
- [x] Unit Tests passed
- [x] Documentation

**Comment by dwuthrich** [comment]
meets requirements
