### ISSUE TITLE
Cards in Editor and Designer do not align

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6221]
**Describe the bug**

After creating a model in the graph designer and setting up the cards, the resource editor does not use the same cards.

Graph Designer cards tab, with nicely structured tree:

![Screen Shot 2020-05-27 at 1 27 47 PM](https://user-images.githubusercontent.com/871868/83068956-fa2d7400-a01d-11ea-8996-edf127e3f59b.png)

And the Editor view, where all the entries are collapsed into the top node, but the structure still appears.

![Screen Shot 2020-05-27 at 1 21 26 PM](https://user-images.githubusercontent.com/871868/83068971-0285af00-a01e-11ea-99f5-1664539039a0.png)

There is a bug with importing data for this structure as well, which may or may not be related.
All the data finds the right branches, but only one branch is shown.

**To Reproduce**

Build any structure as shown above and set the semantic nodes to be in separate cards.

**Expected behavior**

The editor cards should be the same as the graph designer cards.

**Your Arches Information**

Current master. Same under both linux and macosx.

**Comment by azaroth42** [comment]
This also seems to be the cause of the data import/export woes:

The view of the filled out form in the editor of this model above:

![Screen Shot 2020-05-27 at 2 29 46 PM](https://user-images.githubusercontent.com/871868/83074210-a96e4900-a026-11ea-891f-1eeac1e8f384.png)

But only the person and the label are there, none of the other data, in the export:

![Screen Shot 2020-05-27 at 2 30 11 PM](https://user-images.githubusercontent.com/871868/83074262-b9862880-a026-11ea-9e61-4477fe218521.png)

Happy to try and diagnose further ... let me know what I can do?

**Comment by azaroth42** [comment]
Test case (ontology, rdm files, model ... probably not all necessary):

[test_case.zip](https://github.com/archesproject/arches/files/4692006/test_case.zip)

**Comment by azaroth42** [comment]
Experiments say: Could be cache related...

**Comment by chiatt** [comment]
Hey @azaroth42 I think I resolved this problem. Could you please confirm that you don't see it any more and if so, close this ticket?

**Comment by azaroth42** [comment]
Yep, no longer see it, so was doubtless the cache :)
