### ISSUE TITLE
Card editor - as a user I want to be able to edit the attributes of a card

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#623]
The card manager has a tabbed interface with 5 tabs:

- Settings
- Advanced Settings
- Validations
- Permissions (see #624 for specific ticket)
- Help Text (see #625 for specific ticket)

**Settings Tab**
![screen shot 2016-07-19 at 11 44 37 am](https://cloud.githubusercontent.com/assets/823773/16962463/91147f04-4da6-11e6-91c3-0c342b8fdad0.png)

**Advanced Settings Tab**
![screen shot 2016-07-19 at 11 44 46 am](https://cloud.githubusercontent.com/assets/823773/16962525/d81d644c-4da6-11e6-99fb-be300619168c.png)
Clicking the allow multiple values switch updates the form to the right to show the representation of multiple values

**Validations Tab**
![screen shot 2016-07-19 at 11 44 53 am](https://cloud.githubusercontent.com/assets/823773/16962526/d826693e-4da6-11e6-92ad-2115f3735f19.png)

**Permissions Tab**
see #624 for specific ticket
![screen shot 2016-07-19 at 11 45 00 am](https://cloud.githubusercontent.com/assets/823773/16962527/d82696de-4da6-11e6-824b-7c2b89f7fd8b.png)

**Help Text Tab**
see #625 for specific ticket
![screen shot 2016-07-19 at 11 45 09 am](https://cloud.githubusercontent.com/assets/823773/16962541/ef91f61a-4da6-11e6-925a-3df8136a6e6b.png)
Toggling the switch shows/hides the help text form see ticket #625 for details

#### Acceptance Criteria
- [x] Settings tab complete
- [x] Advanced settings tab complete
- [x] Validations tab complete
- [x] Unit Tests passed
- [x] Documentation

**Comment by dwuthrich** [comment]
meets requirements
