### ISSUE TITLE
Support multiple cards per workflow step

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6238]

**Comment by azaroth42** [comment]
:+1: from me.

Uses seem obvious, but at the very least:

* Add activity dates and a display Name for the timespan in a single step
* Add all of the resource-instance and concept datatypes into a single step
* Add core fields such as name and classifications into a single step

**Comment by chiatt** [comment]
In discussing this issue with @robgaston we decided that given the complexity of this problem it is more practical to write custom steps driven by the api that can provide this functionality.
