### ISSUE TITLE
As a user I want to be able to manage the permissions on a card so that I can control access CRUD operations on that card

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#624]
### User Story 
Related to #398 

**Permissions List**
The permissions list displays a list of available groups and users in the system and any associated permissions that user/group has on the selected card

Selecting an item in the permissions list brings up the appropriately initialized Permissions form
![screen shot 2016-07-19 at 11 45 00 am](https://cloud.githubusercontent.com/assets/823773/16963035/413dac78-4da9-11e6-8ce7-c8f90df478af.png)

**Permissions form**
The permissions form allows a user to apply specific permissions to the selected card for the selected user or group
![screen shot 2016-07-19 at 12 09 00 pm](https://cloud.githubusercontent.com/assets/823773/16963100/9f8d6b9c-4da9-11e6-9863-d43cbd3ecfd6.png)

#### Acceptance Criteria
- [ ] Settings are persisted to the database
- [ ] Integration Tests pass <-- we definitely want tests!
- [ ] Documentation

**Comment by dwuthrich** [comment]
meets requirements
