### ISSUE TITLE
As a user I want to be able to manage any help text associated with a card

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#625]
**Help text switch**
![screen shot 2016-07-19 at 11 45 09 am](https://cloud.githubusercontent.com/assets/823773/16963971/e0b7913e-4dad-11e6-84cd-5d56fde9abc8.png)
Toggling the switch shows/hides the help text form below and also the help icon on the right

**Help text form**
![screen shot 2016-07-19 at 12 53 47 pm](https://cloud.githubusercontent.com/assets/823773/16964363/e39f470a-4daf-11e6-8bc9-d8e2dd3c0529.png)
Toggling the perview switch shows/hides the help text form preview below

**Help text preview panel**
![screen shot 2016-07-19 at 12 51 30 pm](https://cloud.githubusercontent.com/assets/823773/16964303/8d447826-4daf-11e6-8ab5-654b5f4dfe9c.png)

#### Acceptance Criteria
- [ ] Unit Tests passed
- [ ] Documentation

**Comment by dwuthrich** [comment]
meets requirements
