### ISSUE TITLE
CLI command to load via JSON-LD

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6257]
**Is your feature request related to a problem? Please describe.**

At the moment, JSON-LD documents can be loaded one at a time via the web API. For a few instances, or for making point updates this is fine and a good pattern.
However, if the user has command line access to the server, it is much more efficient and practical to use a CLI to load the data off of disk.

There should be a command that allows data to be loaded in this fashion.

**Describe the solution you'd like**

`manage.py load_jsonld` with options to configure which models and data  to load.

```
  -s SOURCE, --source SOURCE
                        the directory in which the data files are to be found
  -f, --force           reload records that already exist
  --nobig               Do not attempt to load records > 250kb
  -m MODEL, --model MODEL
                        the name of the model path to load (eg auction_of_lot)
  -b BLOCK, --block BLOCK
                        the name of the block in the model path to load (eg
                        00)
  --max MAX             Maximum number of records to load per model
  --fast FAST           Use bulk_save to store n records at a time
  -q, --quiet           Don't announce every record
  --skip SKIP           Number of records to skip
  --suffix SUFFIX       file suffix to load
```

**Describe alternatives you've considered**

This pattern has worked for me for multiple projects now, after several iterations.

PR coming!

**Comment by azaroth42** [comment]
More verbose documentation:

To load all data from all models, one record at a time:

	$ manage.py load_jsonld -s <path-to-data>

Other options:

* Load a single model, by name (as above):

	$ ... -m <name-of-model>

* Load files that end in a particular suffix, rather than all files in the directories

	$ ... --suffix <suffix>

* Don't store/index one by one, instead every n records  [500 or 1000 are good numbers]

	$ ... --fast <n>

* Don't print out every record UUID, only timing data or warnings

	$ ... --quiet

* Force overwriting of records that already exist, rather than skipping

	$ ... --force

* Skip n records before starting to process

	$ ... --skip <n>

* Stop after processing n records

	$ ... --max <n>

* Don't load records larger than n kb in file size

	$ ... --toobig <n>

* Load only a subset of the data, by subdirectory block name

	$ ... --block <block>

For example:
	$ manage.py load_jsonld ... --block 00
would load only records in subdirectory 00

* Load a slice of the data, by set of blocks

	$ ... --block <n-blocks>,<max-blocks>

For example:
	$ manage.py load_jsonld ... --block 1,8
would load the first slice of 8 slices, thus blocks 00, 08, 10, 18, etc.	
This is most useful when loading in parallel, where each process loads a given slice.

**Comment by apeters** [comment]
works as designed
