### ISSUE TITLE
As a user I want be able to configure the widget associated with a card

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#626]
The widget manager has a tabbed interface with 3 tabs:

- Settings
- Advanced Settings
- Validations

**Settings Tab**
If a widget is attached to an E55 domain value,  then allow the user to select a top concept to use to populate the dropdown values with.
![screen shot 2016-07-19 at 2 04 55 pm](https://cloud.githubusercontent.com/assets/823773/16966538/da7adf2c-4db9-11e6-9a1b-b14bf289c3da.png)

**Advanced Settings Tab**
![screen shot 2016-07-19 at 2 05 03 pm](https://cloud.githubusercontent.com/assets/823773/16966539/da809eb2-4db9-11e6-877a-266490f706ce.png)

#### Acceptance Criteria
- [x] Settings tab complete
- [x] Advanced settings tab complete
- [x] Validations tab complete
- [x] Unit Tests passed
- [x] Documentation

**Comment by dwuthrich** [comment]
meets requirements
