### ISSUE TITLE
bump couch from 1.2 to 2.x

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#6267]
the latest 2.x. version is 2.3.1 for couchdb
Note: the latest version available via pip is 1.2, thus to upgrade to newer versions we may either have to use this lib: https://pypi.org/project/CouchDB2/ or else switch to a manual/scripted install of couchdb

**Comment by mradamcox** [comment]
related to #6798

**Comment by chiatt** [comment]
Closing as this is now covered by #6798
