### ISSUE TITLE
As a user I want to be able to preview the form while I'm editing the associated settings of the form

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#627]
![screen shot 2016-07-19 at 2 20 46 pm](https://cloud.githubusercontent.com/assets/823773/16967040/1791ab14-4dbc-11e6-9306-24260e70d9b2.png)

#### Acceptance Criteria
- [x] Preview reflects the current state of associated settings (labels, etc..)
- [x] Display order of tabs and widgets is managed via drag and drop operations
- [x] Unit Tests passed
- [x] Documentation

**Comment by robgaston** [comment]
I'm going to keep this in progress pending integration of work on #625

**Comment by dwuthrich** [comment]
meets requirements
