### ISSUE TITLE
Add -y override to load_package

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6272]
**Is your feature request related to a problem? Please describe.**

When there are a lot of models and branches (such as Arches for Science), reloading the package over top of an existing installation is Y rather Y time Y consuming Y with Y pressing Y everY time.

**Describe the solution you'd like**

add a -y flag, similar to remove_resources that means you don't have to manually hit Y all the time.

**Describe alternatives you've considered**

In unix you can do `command | yes` or something like that, but that doesn't help for windows, and is inconsistent with remove_resources.

**Comment by chiatt** [comment]
There is a -y flag (I'll make sure it's documented)
