### ISSUE TITLE
(6263) Card/model update incomplete

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6277]
**Describe the bug**

I created a new project from current master to avoid any migration issues, and set up three trivial models - thing, place, person.  I have the production activity in thing with a resource-instance-list to person and a resource-instance to place. 

* In the graph manager, it still shows place to place in the relationship management section, not thing to place / place to thing.

![Screen Shot 2020-06-11 at 9 15 20 AM](https://user-images.githubusercontent.com/871868/84389557-36d3a080-abc4-11ea-99b4-25fdb0b72159.png)

* And the associated cards have a bug about finding the graph config.

![Screen Shot 2020-06-11 at 8 41 48 AM](https://user-images.githubusercontent.com/871868/84389600-48b54380-abc4-11ea-805d-4617d13df12f.png)

**Comment by chiatt** [comment]
@azaroth42 Can you confirm that this is still an issue? I think @apeters may have fixed it.

**Comment by azaroth42** [comment]
Agree this is fixed. Closing.
