### ISSUE TITLE
Create a card switcher dropdown in the header as an alternate way to select the card to edit

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#629]
<img width="550" alt="screen shot 2016-07-19 at 2 44 48 pm" src="https://cloud.githubusercontent.com/assets/823773/16967728/6c0fdd8e-4dbf-11e6-8a6f-2b5cddfd73ff.png">

**Comment by robgaston** [comment]
Looks like this is the same widget as #603 but on the card editor page.  We should be able to centralize the js and template here for reuse across both pages.

**Comment by dwuthrich** [comment]
meets requirements
