### ISSUE TITLE
Concept functions create too many searchengine instances

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6292]
**Describe the bug**

Each time a search engine is created it opens at least one connection to elasticsearch, and those connections take time to tear down when the search engine goes out of scope and is garbage collected. Thus, if too many search engines are created, the operating system runs out of file handles and blows away the offending processes.

The app.models.concepts function at the end of the file create search engines every time they are called in order to look up concepts by various properties. A single call to `get_preflabel_from_valueid` will create three search engine instances, as it called `get_preflabel_from_conceptid` and `get_concept_label_from_valueid`, each of which also create instances.

These functions get called during concept.from_rdf() parsing. So in bulk load of a model that has a lot of concepts, the number of search engine instances gets quickly out of control and the process gets killed.

Apart from rewriting the entire concept / rdm subsystem, some possible fixes:

* Pass a search engine instance through the datatype into these functions.  The issue is then the constructor for the datatype is inconsistent, as no other datatype needs a search engine instance.
* Rewrite the functions as nasty SQL queries against the concept and value tables in postgresql.
* Create a global scoped searchengine that these functions can reference.

**Expected behavior**

Arches should not create so many searchengine instances! :)

**Your Arches Information**

Master as of 2020-06-16

**Comment by apeters** [comment]
added a few tweaks to what @azaroth42  submitted
