### ISSUE TITLE
Branch Identification

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6300]
**Is your feature request related to a problem? Please describe.**

The system (sensibly) adds branch by copying the structure, rather than referencing it. This means that the branches can be customized after import, and don't get out of sync with the data if the branch definition changes.  The downside is that the model doesn't know that it has a copy of a branch, and there are many benefits to knowing that a branch in a model came from a particular branch definition:

* Code could list the uses of particular branches in models.  For example, basically every model has a Name branch and a Statement branch.  If either branch changed, it would be nice to be able to evaluate each usage to see if it should be updated to track the new structure or not. 
* Documentation can be constructed using these branch identifiers. For example, rather than cutting and pasting the documentation for the Name branch into every model (or worse, the Classification documentation into basically every semantic node), instead it could refer to the branch with its documentation. This doesn't obviate the need for custom documentation, but provides sensible defaults.
* It provides a way to track alignment with other definitions or conceptual models.  The Name branch in the A4S Person model /is/ the Name branch from ARM, which /is/ the Name branch from Linked Art. A single identifier for all of these would let us construct better references to further documentation that is externally maintained.
* It provides a hook for other application logic to be built from.  For example, if a Name advertises itself as being the linked-art-personal-name, then a renderer could have custom handling that makes use of that particular structure. Similarly, that structure could be associated with a schema that describes in machine understandable terms exactly what fields are expected, so that data can be validated using json-schema (or other) before coming into Arches. 
* It demonstrates the consistency of the modeling, both internally and with external specifications.  If a model has the same branch identifiers everywhere, then it is very consistent. And if those branch identifiers are well-known from external specifications, then it is provably externally consistent as well.
* It would validate the ARM approach of constructing a toolkit of models and branches. Usage of these branches would be obvious in the configurations of systems, and could then generate automatic reports (if the admin allowed it) that showed the benefit to the community.
* It allows ease of migration into other systems or incompatible future versions. Rather than having to process every node, the branches could be handled in a hierarchical fashion using these identifiers in the models.

(I'll stop there, I hope I've convinced you by now!)

**Describe the solution you'd like**

Each Model and Branch should have a field for an identifier separate from the name. This is to allow the names from external specifications to be used, and for the name to be at least somewhat human readable rather than a UUID.  So the Linked Art branch for Name could have a `name` field of `la-simple_name`, but a name of `Name`.  UI would be a text box, needs a field in the root configuration for saving the field.

Each Node should have a field that has the identifier of a branch, as above. When a branch is added to a model, the node in the model would keep a copy of the branch's identifier.  The UI should still be a text box, in case the branch is subsequently changed and is no longer a direct copy of the original branch. Or it refers to an externally specified structure that isn't a branch in the system directly. It needs a field per node to store the value.

Possible enhancements:

* Allow auto-complete or validation of the name against the list of such names of branches in the system. 

**Describe alternatives you've considered**

We considered whether this could be the same value as #6299 and concluded that it could not, as there could be the same branch (e.g. Statement) in multiple slots of the same model.

**Additional context**

This comes from @habennin and @azaroth42 discussion of documentation for A4S, but again is much wider in application.

**Comment by apeters** [comment]
I think we decided that this in fact could be handled by using specific keys from within the description field via #6340
