### ISSUE TITLE
UUID validation error can occur on resource instance creation if user is not superuser

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6301]
The instance permission check is run before an instance has a resourceid. This causes a UUID validation error because the resourceid is '' instead of a valid uuid.

**Comment by chiatt** [comment]
Hey @adamlodge, All you have to do to QA this is create a new user that has only Resource Editor permissions. Then create and save an instance with that new user.

**Comment by adamlodge** [comment]
resolved
