### ISSUE TITLE
CSV Import: Create spreadsheet from model branch to ease csv data import into nested branches

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#6303]
Most Arches users want to import legacy business data into an Arches project using csv files.  However, csv are poor at representing the hierarchical data structures that nested Arches graphs allow.  In fact, you would need a series of csv files with a way of definitively identifying how hierarchical data are related to import data into a deeply nested Arches model

Luckily, once a branch has been defined, we could readily create the csv files needed to represent each node group.  So long as a user enters data properly, and these files are loaded in the proper order, it would be possible to import hierarchical data into a branch via a set of related csv files.

What should happen under this ticket:
> Define the methodology for creating the necessary csv files, naming conventions, and import order strategy for allowing a user to create the csv files necessary to import data into a specific branch of a model

**Comment by chiatt** [comment]
Great, thanks @dwuthrich
