### ISSUE TITLE
Setting node to not-own card when sub-node has own card errors

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6308]
**Describe the bug**

When trying to set a node to not be placed in a separate card and that node has a sub-node that is also set to go into its own card, the system has an unhandled exception resulting in the eternally spinning wheel of doom.

The structure that breaks:

* {A} Top Node of current branch
  |
  + {B} sub branch (in own card)
      |
      +  {C} Sub-node of {B} (in own card)

Trying to set own card to false for node {B} generates the error. Ontology and node datatypes do not matter.

**To Reproduce**

1. Create a branch.
2. Add node {B} and make sure it goes into a separate card
3. Add node {C} to {B} and make sure it goes into a separate card
4. Try to set node {B} to NOT go into a separate card.
5. Experience spinning ball of doom.

**Screenshots**
![Screen Shot 2020-06-22 at 9 23 34 AM](https://user-images.githubusercontent.com/871868/85292897-95bdd300-b46a-11ea-8a22-a79ddbab6e0f.png)

**Expected behavior**

I don't know what /should/ happen in this case, but I know it shouldn't generate an unhandled exception!  Easiest would be to trap for this case and return a message saying that a downstream node is in a separate card, and that isn't allowed. Or if it is allowed (not sure what the UI would be?!) then fix the bug.  To collapse all downstream nodes into a single card automatically would probably be very confusing to the user.

**Your Arches Information**
* Version: Current master (2020-06-22)

**Comment by azaroth42** [comment]
Urgh. When the subnode doesn't have its own card and it is imported ... it disappears!

**Comment by chiatt** [comment]
Works in the latest
