### ISSUE TITLE
child nodes of concept, resource-instance not selectable in graph manager

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6310]
**Describe the bug**

In a branch, if the root node is concept, concept-list, resource-instance or resource-instance-list, then child nodes are not selectable.  All other datatypes (at least that I tried) worked fine.
Ontology is not necessary for this bug to show up.

Annoying work around is to change the type of the node to semantic, configure the child nodes and then set it back to being a concept or resource-instance.

**To Reproduce**

1. Create a branch and set the top node to be a concept
2. Add a node to the branch.
3. Try to select it.

**Screenshots**
![Screen Shot 2020-06-22 at 10 04 49 AM](https://user-images.githubusercontent.com/871868/85296930-192df300-b470-11ea-9550-d6cec9a7401f.png)

**Expected behavior**

The node should be selectable regardless of the datatype of the parent node.  At the very least it would need to be selected in order to delete it!

**Your Arches Information**

* Version:  Current master 2020-06-22

**Comment by azaroth42** [comment]
Urgh. The work-around doesn't actually work, because (in combination with #6308) the child node disappears out of the model. This is blocking for DISCO.

**Comment by azaroth42** [comment]
Still an issue.

**Comment by azaroth42** [comment]
(revalidated with current master)

**Comment by chiatt** [comment]
It looks like the problem is related to not being able to modify the datatype configs.
