### ISSUE TITLE
Update mobile survey / collector logic to support new resource-instance datatype

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#6326]

**Comment by njkim** [comment]
The collector downloads the project with the models and the resource instances properly and you can create a new resource instance. But there seems to be some problems with sync.

**Comment by apeters** [comment]
@njkim can you elaborate about the issue with Sync?

**Comment by apeters** [comment]
this was fixed by 
https://github.com/archesproject/arches-collector/pull/612
https://github.com/archesproject/arches/pull/6506
