### ISSUE TITLE
Get to related resources visualization UI from report

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6359]
**Is your feature request related to a problem? Please describe.**

In the resource report, the related resources section at the bottom is populated with the resource instance links per model. This is great!

In the search view, there is a nice visualization of these relationships.
This is great!

What would be REALLY great is if you could get from the report view to the visualization.

**Describe the solution you'd like**

A link to the visualization, or a widget that could be dropped into a tab of the report.

**Comment by chiatt** [comment]
Duplicate of #6448
