### ISSUE TITLE
Related Resources UI renders unusable icons

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6367]
**Describe the bug**

When not logged in as a user who can edit resources, there are still icons in the list of related resources for delete the resource (🗑️ ) and ... do something else (🔀) ??

Both generate internal server errors when clicked ... which is at least better than actually deleting or ... whatever the twisty arrows are supposed to do. 

**To Reproduce**
1.  Set up some related resources
2. Go to search
3. Click to the related resources UI
4. Click the nine dots to get to list view
5. Observe and click the trash can.

**Expected behavior**

These icons shouldn't be rendered to users that cannot use them. And should have help text for users that can.
(or, preferred, just get rid of them from this UI)

**Comment by chiatt** [comment]
Hey @azaroth42, the table/force directed graph toggle buttons are no longer available in search, so you can no longer get to those buttons. Given that, is it okay if I close this?

**Comment by chiatt** [comment]
Because the table isn't available in search, it should not be possible for non-editors to see the related resource buttons.
