### ISSUE TITLE
Business data export fails for models with / (etc) in name

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6378]
**Describe the bug**

If you put a / in the name of a model, then when you come to export the data for it, the code naively drops it into the filename.

`FileNotFoundError: [Errno 2] No such file or directory: 'pkg/business/Auction_/_Exhibition_2020-07-08_09-03-58.json'`

Don't name your models `../../../../etc/passwd` ;)

Workaround is, of course, to not put the characters in the model name, but that shouldn't be a restriction or if it is, then it should be enforced.

**To Reproduce**
1. Make a model with / in its name
2. Try to export the instances of it.

**Expected behavior**
Export code should escape or otherwise remove any filesystem characters such`..`, `/` or `\`, `~` and so on.

**Your Arches Information**

Current master.

**Comment by chiatt** [comment]
Resolved in PR #6500
