### ISSUE TITLE
Resource Manager should use subtitle, not description, under icon

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6382]
**Is your feature request related to a problem? Please describe.**

The abstract / description of a model should be able to be lengthy, to inform users about its purpose and usage.
In comparison, the model's subtitle is short, in order to render under the name in the graph designer.

Currently the resource manager with the nice "tiles" or "cards" for creating new resources has a limited amount of space for text under the icon and no way to expand that text. It seems like it should use the subtitle (intended to be short) not the description (intended to be informative).

**Describe the solution you'd like**

* Add subtitle into createable_resources in views/base.py
* bind subtitle instead of description in templates/views/resource.htm

(Also nice would be to expose color to potentially customize the grid)

**Describe alternatives you've considered**

Copying the abstract into the first line of the description and hoping the cutoff works. Poor choice as it never quite works, and always has ... at the end.

**Comment by azaroth42** [comment]
This is perhaps a little garish, but I hope it proves the point:

![Screen Shot 2020-07-09 at 12 42 02 PM](https://user-images.githubusercontent.com/871868/87067144-a8ae0280-c1e1-11ea-8dba-6cd27f5fbf76.png)

**Comment by chiatt** [comment]
Works as expected.
