### ISSUE TITLE
Null value for (non-required) resource-instance node generating Type Error 

### ISSUE THREAD

**Issue by michaeltfisher** [archesproject/arches#6419]
**Describe the bug**
Arches seems to be expecting a value for the resource-instance node (in this case, Actor Name) of a child card, but getting a null value (as it's not a required field), and then throwing up the Type Error. This doesn't occur when accessing the child card from the card tree; only when accessing it from the top card.

**To Reproduce**
1. Go to any Top Card with a child card of n-cardinality that contains multiple nodes, including a resource-instance node
2. Enter values other than the resource-instance node value
3. Click 'Add'

**Screenshots**
<img width="1940" alt="Screenshot 2020-07-16 at 16 54 14" src="https://user-images.githubusercontent.com/41090686/87698555-8d1b9c80-c78b-11ea-8024-8b4dcd1c8e22.png">

**Expected behavior**
Parent tile created; non-null values added; no issues with null resource-instance value

**Traceback**
[Thu Jul 16 12:02:35.426197 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656] 2020-07-16 12:02:35,426 arches.app.views.tile ERROR    Saving tile failed [Tile id: ]                      [Exception message: TypeError]                      [Exception trace: Traceback (most recent call last):
[Thu Jul 16 12:02:35.426216 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656]   File "/home/archesdev/arches/arches/arches/app/views/tile.py", line 134, in post
[Thu Jul 16 12:02:35.426221 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656]     tile.save(request=request)
[Thu Jul 16 12:02:35.426225 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656]   File "/home/archesdev/arches/arches/arches/app/models/tile.py", line 337, in save
[Thu Jul 16 12:02:35.426229 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656]     datatype.pre_tile_save(self, nodeid)
[Thu Jul 16 12:02:35.426233 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656]   File "/home/archesdev/arches/arches/arches/app/datatypes/datatypes.py", line 1679, in pre_tile_save
[Thu Jul 16 12:02:35.426237 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656]     "resourceinstanceidto_id": related_resource["resourceId"],
[Thu Jul 16 12:02:35.426241 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656] TypeError: string indices must be integers
[Thu Jul 16 12:02:35.426246 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656] ]
[Thu Jul 16 12:02:35.426252 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656] 
[Thu Jul 16 12:02:35.426761 2020] [wsgi:error] [pid 20434:tid 139962711561984] [remote 129.67.116.182:56656] Internal Server Error: /tile

**Comment by chiatt** [comment]
Hey @michaeltfisher - are you still seeing this issue in the latest?

**Comment by chiatt** [comment]
Hey @michaeltfisher, We have not been able to reproduce this. I'm going to close this ticket, but if you're still seeing it, feel free to reopen it.
