### ISSUE TITLE
Relationship records cannot be deleted if their corresponding tile is deleted

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6453]
If a user creates a tile with a resource instance datatype, the tile and relationship record are created. If the user then deletes the tile, the relationship records persist and the user cannot delete them in the Related Resources view in the editor.

**Comment by apeters** [comment]
shouldn't this be handled by this in the `on_delete=models.CASCADE` setting in the `ResourceXResource` table?
```    
tileid = models.ForeignKey(
        "TileModel", db_column="tileid", blank=True, null=True, related_name="resxres_tile_id", on_delete=models.CASCADE,
)
```

**Comment by chiatt** [comment]
@apeters It could be the index is persisting and that's why it still appears in the UI

**Comment by azaroth42** [comment]
I can confirm this.  I had to do the same (or rather I deleted directly out of the index via the python elasticsearch library)
