### ISSUE TITLE
Graph validation does not allow relationships with multiple range classes

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6456]
**Describe the bug**

In SKOS, there is a single property `skos:member` that has a range with multiple classes -- skos:Concept and skos:Collection.  In other words, either of skos:Concept or skos:Collection can be the target of a `member` relationship.

After constructing the ontology with this pattern (two range assertions), the graph will not validate because in models/graph.py, at line 1408 (and following) the system iterates through both, and one of the two does not match.

Either there should be a single merged list, or it should make sure that at least one of the lists matches, rather than requiring all of them to match.

**To Reproduce**
1. install an ontology with a property that has multiple range classes
2. try to use that property in a model.

**Expected behavior**

Any of the classes should fulfill the condition, rather than (impossibly) requiring all of them to be present.

**Comment by chiatt** [comment]
Resolved in #6457
