### ISSUE TITLE
Allow string datatype to manage language and direction

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6458]
**Is your feature request related to a problem? Please describe.**

In some data structures, a string can be annotated with two properties - the language of the string (as available currently in the RDM, only) and the direction of the string (right-to-left or left-to-right, not available anywhere at the moment).

This functionality is important for internationalization of data in situations where the ontology does not provide a class with properties to manage the information.

**Describe the solution you'd like**

Extend the string data type to optionally allow these additional values.

**Describe alternatives you've considered**

Requiring the use of a semantic node with value/language/direction properties anywhere that language/direction is needed.

**Additional context**

Considerations / References:  
* https://www.w3.org/TR/json-ld11/#string-internationalization
* https://www.w3.org/TR/string-meta/
* https://w3c.github.io/rdf-dir-literal/

**Comment by chiatt** [comment]
Fixed in #7885
