### ISSUE TITLE
Localize dynamic UI labels

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6471]
Use django-modeltranslation (https://django-modeltranslation.readthedocs.io/en/latest/index.html) to manage the translation of dynamic UI labels. Implement translation for anything with a string that's visible to the user. This will include strings in:
    - cards
    - widgets
    - graphs
    - nodes
    - import/export

**Comment by apeters** [comment]
Closing because there are more specific tickets that supersede this ticket
