### ISSUE TITLE
The photo gallery card thumbnail container arrow-buttons no longer respect user interaction

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6504]
**Describe the bug**
( Lack of ) interaction can be seen here: http://recordit.co/RNnI0jnVLV.gif

The previous/next arrow buttons in the thumbnail container of photo gallery cards no longer respects user interaction. There is no cursor change to indicate a clickable element, either.

**To Reproduce**
1. Create a Photo Gallery Card
2. Populate the resource with multiple photos
3. Attempt to navigate between photos by clicking the thumbnail container arrow buttons.

**Screenshots**

( Lack of ) interaction can be seen here: http://recordit.co/RNnI0jnVLV.gif

**Expected behavior**

The arrow buttons should cycle through previous / next photos.

**Your Arches Information**

*   Version used: SHA ec96b61376a4f9d3d1dde0afb93bc867e5cc735a
*   Operating System and version (desktop or mobile): macOS Catalina
*   Browser Name and version: Chrome 84.0.4147.105 (64-bit)
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @chrabyrd

**Comment by chiatt** [comment]
Resolved in #6509
