### ISSUE TITLE
Scrambled node labels and values

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6511]
Data entered and saved in one field on a card is shown as being in another field on the report.  

In this example, values saved in the "Owner" field are displayed as being in the "Fiscal Year" field.
See attached screenshots:

Data entry card:
![Screen Shot 2020-08-10 at 10.01.55 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/a3531981-3ed4-428c-ae88-5a61d513545b)

Report:
![Screen Shot 2020-08-10 at 10.02.14 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/3f374579-8931-40d7-a623-2b71b5170ac9)

**Comment by chiatt** [comment]
Possibly related to: #6348
