### ISSUE TITLE
Reduce searchengine instances further

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6518]
**Describe the bug**

Further to #6292, there is a need to further reduce the number of search engine instances, especially when loading data.
When running only 16 loads in parallel, the HTTP connection pool explodes.

PR coming to reduce the number significantly (if not ubiquitously)

**To Reproduce**

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
Resolved in #6519
