### ISSUE TITLE
Adding a node to a grouped card breaks UI

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6522]
**Describe the bug**
In the designer, group two cards together. Then add a node to the grouped ( _not_ grouping ) card. The UI will break and an error will be thrown. Can be lower priority, a refresh fixes this.

Error message: https://pastebin.com/XgXwdaiE
UI seen here: http://g.recordit.co/wwZdLGhFBS.gif

**To Reproduce**
1. Create a new resource model
2. Add two top nodes, and give them children
3. Go to the card designer view, and group the cards together.
4. Go back to the graph designer view, and add a node the grouped card.
5. Navigate to the card designer view, and click on the grouping card.

**Screenshots**
UI seen here: http://g.recordit.co/wwZdLGhFBS.gif

**Expected behavior**
The grouping card should show the newly added node.

**Your Arches Information**

*   Version used: Arches 5.0
*   Operating System and version (desktop or mobile): macOS Catalina
*   Browser Name and version: Chrome 84.0.4147.105 (64-bit)
*   Link to your Arches Install (optional):

**Additional context**
Error message: https://pastebin.com/XgXwdaiE
UI seen here: http://g.recordit.co/wwZdLGhFBS.gif

**Ticket Background**
*   Found by: @chrabyrd

**Comment by apeters** [comment]
this might also be related to #5710 and #6565
