### ISSUE TITLE
Deleting child nodes doesn't affect the card designer view until refresh.

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6524]
**Describe the bug**
In Arches Designer, when a child node is deleted the card remains unaffected until page refresh.

UI seen here: http://g.recordit.co/Qoeqj4RZhJ.gif

**To Reproduce**
1. Create a new resource model
2. Create top nodes. Add child nodes to them.
3. Navigate to the card designer view. Notice the number of nodes.
4. Navigate to the graph designer view, and remove a child node.
5. Navigate to the card designer view, and notice the node has not been deleted.

NOTE: As seen in the gif, any interaction with the deleted node throws a 500 error. This is expected. Backend error message is here: https://pastebin.com/mYjBdJ0J . Not putting elsewhere in ticket because it's expected.

**Screenshots**
UI seen here: http://g.recordit.co/Qoeqj4RZhJ.gif

**Expected behavior**
The card designer view should not show the deleted nodes.

**Your Arches Information**

*   Version used: SHA 9ea7a679b88e013f49af0bc80dab27a1755bf470
*   Operating System and version (desktop or mobile): macOS Catalina
*   Browser Name and version: Chrome 84.0.4147.105 (64-bit)
*   Link to your Arches Install (optional):

**Additional context**
UI seen here: http://g.recordit.co/Qoeqj4RZhJ.gif

**Ticket Background**
*   Found by: @chrabyrd

**Comment by azaroth42** [comment]
Confirmed. Also, when creating new nodes they sometimes appear twice in the card list until refresh.

**Comment by chrabyrd** [comment]
> Confirmed. Also, when creating new nodes they sometimes appear twice in the card list until refresh.

hmmm I can't seem to repro this @azaroth42 , if you can show how to reproduce this I'd be happy to take a look 👍
