### ISSUE TITLE
cards from branch-appended nodes not loading in workflows

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#6548]
To reproduce:
- create a branch
- append this branch to a resource model
- assign the nodegroups from the newly appended branch child-nodes in the resource model to the plugins/workflow js file
- initiate the workflow
- verify whether cards are loading

**Comment by chiatt** [comment]
I think this issue is resolved in the latest iteration of workflows as it didn't come up during any of the recent AfS workflow development.
