### ISSUE TITLE
Adding long annotations results in unusable UI and error throw

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6557]
**Describe the bug**

UX seen here: http://g.recordit.co/xWTs9QUVN3.gif
Error here: https://pastebin.com/a9rDmmTb

Data used: http://api.bl.uk/metadata/iiif/ark:/81055/vdc_00000004216E/manifest.json

**To Reproduce**
1. Navigate to Arches designer
2. Create a resource model with a node of type `annotation`
3. Navigate to `Add New Resource`
4. Create a new resource with a large annonation ( data used: http://api.bl.uk/metadata/iiif/ark:/81055/vdc_00000004216E/manifest.json )
5. Notice the unusable UI and error throw.

**Screenshots**

UX seen here: http://g.recordit.co/xWTs9QUVN3.gif

**Expected behavior**
Expect no error thrown, and the UI to be in such a way that the user retains access to buttons.

**Your Arches Information**

*   Version used: SHA 9b17cc8a8e4540c9378aed1820f59271e9f96597
*   Operating System and version (desktop or mobile): MacOS Catalina
*   Browser Name and version: Chrome 84.0.4147.135 (Official Build) (64-bit)
*   Link to your Arches Install (optional):

**Additional context**
UX seen here: http://g.recordit.co/xWTs9QUVN3.gif
Error here: https://pastebin.com/a9rDmmTb
Data used: http://api.bl.uk/metadata/iiif/ark:/81055/vdc_00000004216E/manifest.json

NOTE: Same-origin policy blocked a cookie and 2 images, but I think at least the unusable UI is unrelated. The error throw _may_ be related, but will take further investigation.

**Ticket Background**
*   Found by: @chrabyrd

**Comment by chiatt** [comment]
May be resolved by using a more appropriate card

**Comment by njkim** [comment]
The error seems to be resolved in 5.2.x. (The error does not appear on the console with 5.2.x.)

**Comment by chiatt** [comment]
Resolved in #7051
