### ISSUE TITLE
Collector Appears to Not work with https-enabled Arches Deployments

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6562]
When working with https deployments, Collector is unable to pull down mobile collection projects.  Not sure if the solution is in modifications to Collector itself, or in network configurations.  Either way, most production Arches deployments are (or should be) https-enabled and there should be a clear pathway to make Collector work with them.

**Comment by whatisgalen** [comment]
Was unable to reproduce on an https / SSL deployment. 2-way sync worked successfully using arches/master (which uses celery for sync as of v5 release)

**Comment by adamlodge** [comment]
Looks like the symptom that we were attributing to ssl may have been caused by a separate issue where celery was not running.  Galen conducting tests to pin this down and verify.

**Comment by chiatt** [comment]
This issue may to apply to 5.0, but does not occur master.
