### ISSUE TITLE
Domain default value doesnt clear or reset when domain list is rebuilt

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6576]
this issue may also surface when a domain node is cloned as part of a model or branch.   Another related item is that ui indicates that there is no default value in these cases, but export of the model to json indicates that the invalid domain value is still set as the default.

Hoping to get this resolve on 5.0 for use with ATM.

**Comment by adamlodge** [comment]
I've seen this happen and resolved with a workaround that required me to delete the entire node and rebuild from scratch in order to create new node configuration.  Unfortunately, I couldnt reproduce the sequence of steps that caused this issue in the first place.

**Comment by chiatt** [comment]
@adamlodge Did you say that this issue was no longer an issue in one of the stand-up meetings?
