### ISSUE TITLE
Logging in as a user not assigned to any groups causes an un-trapped Django error

### ISSUE THREAD

**Issue by ads04r** [archesproject/arches#6587]
**Describe the bug**
If a normal user is created but not assigned to one or more groups, the user may log in but any attempt to view the index page produces an error, from arches/app/utils/context_processors.py

**To Reproduce**
1. Log in as an admin user
2. Go to the Django admin page
3. Create a user, set a password, but do not assign the user to any groups, or give admin access to the user
4. Log out
5. From the Arches main page, click Sign In and log in as the new user
6. Error appears.

**Expected behavior**
The user should be able to at least log in, even if they cannot view or edit any data.

**Your Arches Information**
*    Version used: 5
*    Operating System and version: Desktop. Server is Ubuntu, Client is Windows
*    Browser Name and version: Firefox (also reproduced in Chrome)
*    Link to your Arches Install (optional): (local)

**Ticket Background**
*   Found by: @ads04r

**Comment by chiatt** [comment]
Resolved in #6591
