### ISSUE TITLE
Provide support for Arches JSON format for the API resources PUT method

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#6638]
**Description**

Provide support for Arches JSON format for the API resources PUT method. Currently it only appears to support JSON-LD while the GET method support both JSON and JSON-LD.

**Comment**
We have developed this for our v5.0.0 implementation and will be looking to submit a PR to stable/5.0.x on completion of testing.

**Comment by chiatt** [comment]
Thanks @AJ-HistoricEngland, looking forward to your PR.

**Comment by aj-he** [comment]
This is now including POST verb and targeting 5.2.x. PR incoming from @khodgkinson-he
