### ISSUE TITLE
default report fields not lining up with values correctly

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6639]
This screenshot is a "fiscal_year" resource in the usdssc package. Im hoping the solution can be a generic Arches solution and not a custom template for usdssc.

![Screen Shot 2020-09-22 at 3.53.24 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/8dacac4b-62fa-4fc4-8fa9-903a1535e4ee)

**Comment by chiatt** [comment]
This is probably a similar issue as here: https://github.com/archesproject/arches/pull/6514/files

In that case all of the values appeared shifted from their labels when a number widget had no value. The solution was just to make sure that 'None' was entered in the report if there was no value.
