### ISSUE TITLE
Tweaks to Ubuntu installation script

### ISSUE THREAD

**Issue by patml1** [archesproject/arches#6654]
1. In two places in the ubuntu script **arches/arches/install/ubuntu_install.sh** ( 4 Dec 2019 version) keys are fetched after they are wanted. This can be cured by swapping lines 11 and 12 (the first two in the postgres installation) amd lines 40 and 41 (in the couch-db installation).

**Comment by chiatt** [comment]
Hi @patml1, Thanks very much for your suggestion. I looked at the code and I think I see what you mean, but my understanding is that the key is needed for the installation rather than simply adding the repo. The installation order in the install script is consistent with the postgres installation docs for Ubuntu. https://www.postgresql.org/download/linux/ubuntu/, so I don't think the order is necessarily a problem.

**Comment by patml1** [comment]
Hello Cyrus,

Thanks for looking at this.

I agree that should be the case. To revisit it, I created a virgin Ubuntu Virtualbox machine to test it, wgot a fresh install_ubuntu.sh from the git repository and ran it. After elasticsearch installed OK I said no to the rest, took a snapshot of the virtual machine, and then manually copied the first line from the install_postgres function as follows:

pat@VBUB1804:~$ sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main"
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:3 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]   
Hit:4 https://artifacts.elastic.co/packages/7.x/apt stable InRelease           
Hit:5 http://dl.google.com/linux/chrome/deb stable InRelease                   
Get:6 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB] 
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Get:8 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [103 kB]   
Err:8 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease            
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
Reading package lists... Done
W: GPG error: http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
E: The repository 'http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
pat@VBUB1804:~$

I then reverted to the snapshot and ran:

pat@VBUB1804:~$ wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
[sudo] password for pat: 
OK
pat@VBUB1804:~$ sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main"
Hit:1 http://gb.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]   
Get:3 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [103 kB]   
Get:4 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB] 
Get:5 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [222 kB]
Get:6 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main i386 Packages [221 kB]
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Hit:8 https://artifacts.elastic.co/packages/7.x/apt stable InRelease           
Get:9 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Hit:10 http://dl.google.com/linux/chrome/deb stable InRelease                  
Fetched 798 kB in 6s (138 kB/s)                                                
Reading package lists... Done

A bit strange that they aren't fetched in the same order but it does succeed with ten items rather than binning out after seven.

I am absolutely new to all this and don't really understand what is happening at each step so please bear with me if I am missing something obvious or worrying about something trivial. The rest of the script ran OK with the exception of a warning about 'non-standard escape in a string literal' when creating the extension postgis. The extension does seem to get created OK anyway.

Thanks again for your time. I let it run through and managed to get Arches running so agree there is no urgent need to change anything, and guess that it managed to find what it neede without those extra bits from the repository..

Best,
Pat
