### ISSUE TITLE
Option to include all js and css dependencies locally during install

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#667]
During development, it has been hugely useful to work on my app without needing to be connected to the internet.  It would been nice to make this an option during the install wizard. Or, perhaps, make it the default configuration.  For my own purposes, I just downloaded all of the js and css files listed in base.htm, placed them within the app, and changed the paths in base.htm accordingly.  This was a relatively small amount of effort with huge benefits.

The only remaining internet connectivity dependencies are a font or two (which could maybe be installed locally?) and the basemap layers, which are only useful for a very small portion of development tasks anyway....

#### Acceptance Criteria
arches may be installed with all js and css resources stored locally

**Comment by apeters** [comment]
There have been several times when I too wished I could do development disconnected from the internet.

In fact a requirement for the mobile app is that it run disconnected.  This may be enough to warrant allowing the web app to be run disconnected as well.  I'm sure we could easily add a switch to the install wizard to allow this to happen.  Or maybe we load everything locally and have a fallback to the web.  There are several possibilities here...at least for development.

+1

**Comment by robgaston** [comment]
@mradamcox With the latest on `master`, all client resources are hosted locally.  There is now an additional build step that is required to get the client-side packages.  It uses [Node.js](https://nodejs.org/en/), so you'll need to install that, then run the following commands from the arches project root directory:
```
npm install -g bower
bower install
```
