### ISSUE TITLE
Allowing App-specific email config

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#6673]
**User Story**
 
As a user I want to be able to:
* Set the 'from' email to a value in settings
* Use the application name in the User change notification email
 
 
**Acceptance Criteria**
-   [x] DEFAULT_FROM_EMAIL is added as a setting in settings.py and settings.py-tpl
-   [x] The from email can be set using the new DEFAULT_FROM_EMAIL setting.
-   [x] The APP_NAME setting is used in the email sent to the user once their details have been changed.
-   [x] You're changed to Your in the user change e-mail subject line.
-   [x] Unit Tests passed

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: Historic England
*   Designed by: Historic England

**Comment by chiatt** [comment]
@csmith-he Thanks very much for these improvements
