### ISSUE TITLE
Export email link incorrect

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#6675]
**Describe the bug**

The link within the email sent for a completed export contains a UUID (the export session UUID?) rather than a link to the ZIP file for download.

**To Reproduce**
1. Go to Search and zoom to a scale where you can see resource geometry on the map
2. Open Filter
3. Select 'Search by Map Extent' from the 'Select a filter' dropdown list
4. Close Filter and Open 'Search Export'
5. Retain all default values and enter your email address
6. Click Download button
7. Wait for email to be received and hover over the 'Download Now' link
4. See UUID rather than a valid link to a ZIP file

**Screenshots**
![image](https://user-images.githubusercontent.com/38533555/94945131-1ceefe00-04d2-11eb-81a7-aed61e76336e.png)

**Expected behavior**
The link would be to a ZIP file in the files folder for the Arches installation

**Your Arches Information**

*   Version used: stable 5.0.x
*   Operating System and version (desktop or mobile): Windows 10 Desktop
*   Browser Name and version: Chrome 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
We have a fix in place in our application - this is us feeding the fix back to Arches Core now we know it works.

**Ticket Background**
*   Found by:  Historic England

**Comment by csmith-he** [comment]
I'll send in a pull request for the fix next Monday

**Comment by chiatt** [comment]
Resolved in #6677
