### ISSUE TITLE
Indicate that advanced search is in play in search results

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6680]
As a user who is using search, I can add filters to search using the advanced search tab, and then click back to the map tab.  After clicking to the map tab, the search results still take the advanced search parameters that you entered into play, but you can only still see the filters applied in simple search.  It would be nice to provide some kind of visual indication (maybe change the color of the advanced tab) that gives a visual cue that advanced search parameters are effect the content of the search results.

**Comment by chiatt** [comment]
In the latest there is a tag indicating that there is an advanced search query applied
