### ISSUE TITLE
Ability to define viewable, but non-editable nodes in cards

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6682]
There are two known use cases where it would be convenient to be able to configure a node as non-editable within a card - ostensibly greyed out to indicate value cant be changed.   Being able to see the value, btw, is (as is not the case if you make the widget invisible in the card) is not a sufficient solution.

Two use cases:
1> Data are imported on a recurring basis to resource instances.  In these cases, the data are managed elsewhere and should not be changed, but other nodes in the same model and card are hand-entered in Arches, and seeing those imported values has impact on the hand-entered value.

2> Node contains a function-calculated value based on values in other nodes that are hand-entered. 

BTW - using card privileges to solve this problem is insufficient because there can be a single card/nodegroup that contains both hand-editable and calculated node values.

**Comment by chiatt** [comment]
Resolved in #6863
