### ISSUE TITLE
Setting domain values to domain-radio-widget on card designer makes other configs fall off the page

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6725]
Hopefully this image is illustrative.  I can demonstrate if helpful.
![Screen Shot 2020-10-15 at 8.26.45 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/d7d2a877-516d-4a8f-8918-3a0d9036b436)

**Comment by chiatt** [comment]
Fixed in #6996
