### ISSUE TITLE
In the search force-directed graph, node labels can hide the node-hovering interaction

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6742]
**Describe the bug**

Currently in our search's force-directed graph, the desired behavior of a user hovering over a node is to highlight the node itself, as well as any links and partner nodes. This interaction is sometimes tricky, as node labels prevent the hover event.

We should change the labels to include the node hover event.

**To Reproduce**
1. Navigate to the search force-directed graph
2. Hover on a node/label. Notice the interaction

**Screenshots**
N/A

**Expected behavior**
When a user hovers over a label, the node hover event should fire as well.

**Comment by chiatt** [comment]
Since this ticket was created we have switched to the new Cytoscape visualization. In the new visualization the node labels do not prevent hover interaction with the node.
