### ISSUE TITLE
Advanced search facet options should be clearly labelled an not contain duplicates

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6746]
**Describe the bug**

Currently the advanced search facet options are not clearly labelled and have duplicate entries. These are likely not `true` duplicates, but rather shortening of longer names (eg. Date, Date, Date -> Date Collected, Date Observed, Date Recorded).

UI: https://ibb.co/NygtFMs

**To Reproduce**
1. Load AFS
2. Navigate to Search
3. Click on the Advanced Search tab. Notice the facet entries.

**Screenshots**

UI: https://ibb.co/NygtFMs

**Expected behavior**

There should be clear, unduplicated labels

**Comment by azaroth42** [comment]
I don't think this is a core Arches bug, but a configuration one. And mea culpa on the labels in A4S :)

**Comment by apeters** [comment]
I think the issue here is that ONLY using the card name in the Adv. Search panel can produce a lot of what appear to be duplicate names.  If those card names could be prepended with the containing card name that might reduce the confusion.

**Comment by chiatt** [comment]
There is now an `i` button on each facet. Clicking it will show the node alias tree for the card to help users identify the right card. 
<img width="290" alt="image" src="https://github.com/archesproject/arches/assets/1877663/3fbf18c4-4470-42cb-9146-b45f5459c470">
