### ISSUE TITLE
Export search shapefile error

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6749]
**Describe the bug**

Exporting search results works when the desired filetype is CSV, but throws an error when the type is `Shapefile`

Error message: `Either no instances were identified for export or no resources have exportable geometry nodes                Please confirm that the models of instances you would like to export have geometry nodes and that                those nodes are set as exportable`

These are `Consultation` resources in arches-her, and _should_ have exportable geometry nodes.

**To Reproduce**
1. Load arches-her package
2. Navigate to advanced search
3. Search only for Consulatations
4. Export results as a shapefile

**Screenshots**

**Expected behavior**

This should return a correct shapefile.

**Comment by chiatt** [comment]
It could be that there was no export name defined for those nodes. If that's the case we should mention that in the error message.

**Comment by chiatt** [comment]
Should be addressed by #6815
