### ISSUE TITLE
Search export UI doesn't correctly detect celery instance

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6751]
**Describe the bug**

The search export UI doesn't recognize that celery is running. However the button can still be interacted with and produces the correct result.

UI: https://ibb.co/DCZW9NW

**To Reproduce**
1. load arches_her package
2. start celery
3. navigate to search and download more than the export limit
4. Notice erroneous UI / functional UX

**Screenshots**

UI: https://ibb.co/DCZW9NW

**Expected behavior**

The UI should recognize the running celery instance.

**Comment by chiatt** [comment]
Tested this recently with another project and it worked as expected.  I suspect the issue here is that arches_her overrides core search with a custom view, so I'm going to move this ticket to that project.

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches-her #528](https://github.com/archesproject/arches-her/issues/528) via [**ZenHub**](https://www.zenhub.com/)
