### ISSUE TITLE
In the Resource creation view, the button to switch from graph to table is only partially clickable

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6760]
**Describe the bug**

The button to switch from force-directed graph to table in the resource creation view is only partially clickable.

UX: https://recordit.co/kwPEuKum35

**To Reproduce**
1. Navigate to the resource creation page
2. Attempt to navigate between force-directed graph and table in the Related Resources subview

**Screenshots**

UX: https://recordit.co/kwPEuKum35

**Expected behavior**
The entire button should be clickable.

**Comment by chiatt** [comment]
Button has been replaced with tabs in the latest.
