### ISSUE TITLE
Errors are thrown when user with provisional access accesses report with provisional edits

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6761]
**Describe the bug**

UI: https://ibb.co/qNchBWv

**To Reproduce**
1. Load a package, afs was used here
2. Create a user with Resource Editor permissions
3. Edit a Resource, notice the errors thrown

**Screenshots**

UI: https://ibb.co/qNchBWv

**Expected behavior**
There should be no errors thrown, and the user should get a direct notification if they've submitted provisional edits that the changes have been submitted.

**Comment by chiatt** [comment]
Wasn't able to reproduce this issue after merging: #9704
