### ISSUE TITLE
Support search for null values in advanced search

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6772]
Need to write a search filter that searches for instances where a node's value is null. Currently, the system only contains search operators that require a value to filter on.  Best solution will expand the set of operators to include "is null".  

IMHO - this operator should (under the covers) look for both nulls and empty strings as the difference between the two for actual users is irrelevant.

![Screen Shot 2020-12-03 at 2.51.43 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/04f13609-a891-4972-a471-0428ae29964a)

**Comment by adamlodge** [comment]
The scope of this ticket should be expanded to include all non-semantic data types.

**Comment by chiatt** [comment]
Resolved in #6772
