### ISSUE TITLE
replace space character with underscore in filename when resource model .json or .mapping exported from arches

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#6775]
**User Story**

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
I'm going to close this for now unless there is a pressing need for this feature.
