### ISSUE TITLE
Tile Validation Error for Domain Values

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#6785]
**Describe the bug**

The issue manifests in an attempt to select a domain value that has been added to the graph from a branch which has also been attached to another resource model in the application.  When attempting to save the domain value, an error message appears:

![image](https://user-images.githubusercontent.com/38533555/97160265-fc822e80-1773-11eb-91cc-0eeae18b7b05.png)

**To Reproduce**

1. Create a branch with a domain node datatype and add values.
2. Add the branch to two resource models.
3. Create a resource from one of those two models and select a domain value
4. Error message appears.

**Expected behavior**
The user will be able to select a value and save it successfully.

**Your Arches Information**

*   Version used: Arches Stable 5.0.x
*   Operating System and version (desktop or mobile): Windows 10 desktop
*   Browser Name and version: Chrome  86.0.4240.75
*   Link to your Arches Install (optional):

**Additional context**

domain_val_node_query = models.Node.objects.filter(config__contains={"options":[{key: value}]}).filter(nodeid=node.nodeid)

We have created a local fix by adding a second filter to the domain_val_node_query within the Domain datatype class validation (without it, it brings back all domain nodes with the string value in the database) but it does not pass unit testing because the nodeid isn't being passed through which we're wondering might be indicative of a greater problem with what is being passed through as part of the BaseDataType object.

We can provide JSON files for two (test) resource models using the same branch to replicate the issue if that helps.

Not sure if this is the same issue as #6774 - @chiatt can you confirm whether this is the case or not, please?

**Ticket Background**
*   Found by: Kingsley Hodgkinson, Historic England

**Comment by chiatt** [comment]
Thanks @csmith-he. This is actually a different issue. I think it should already be fixed with this commit: https://github.com/archesproject/arches/pull/6564/files

It looks like the lines that raise this error are commented out in the latest on 5.0.x:
https://github.com/archesproject/arches/blob/8451e2835112463de7cb11023f18c15927f913aa/arches/app/datatypes/datatypes.py#L1325-L1334

**Comment by chiatt** [comment]
Hey @csmith-he, I think this is resolved, but if you're still seeing the bug, let me know and feel free to reopen this issue.
