### ISSUE TITLE
load_package command should -bulk switch when loading data

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6796]
My testing indicates that we dont take advantage of the performance enhancements afforded by the -bulk on the import_business_data command when loading data as part of load_package.  Unless there is some reason not to (that I am unaware of), we should use the -bulk switch on load_package.

**Comment by chiatt** [comment]
One problem with using bulk is that arches functions are not run on bulk import.

**Comment by chiatt** [comment]
This is a good suggestion @adamlodge, but I am going to close it because we first need to resolve some of the issues associated with bulk load. re #6442, #5512, #5804
