### ISSUE TITLE
Update CouchDB to 3.x

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#6798]
**Describe the bug**

Arches currently only works with CouchDB 2.x, which is outdated and a little trickier to install. It would be good to update it to work with 3.x

**To Reproduce**
1. Install the latest couchdb release (which is currently what happens in the ubuntu_setup.sh script)
2. Set all other configurations necessary to connect to the Arches Collector app
3. Attempt to connect to the app. You'll likely get a silent failure in the app, and an error in the apache/arches logs.

**Your Arches Information**

*   Version used: 5.0
*   Operating System and version (desktop or mobile): Ubuntu 18, Android/iphone

**Additional context**
We can also update the ubuntu_setup.sh script to install 2.x (and should) but this upgrade should happen eventually.

**Ticket Background**
*   Found by: @coherit

**Comment by chiatt** [comment]
@mradamcox Have you managed to install CouchDB 2.x on Ubuntu 20?

**Comment by mradamcox** [comment]
@chiatt no, we hadn't tried until now, and testing locally now I see that the `sudo apt-cache policy couchdb` command in the docs which lists available versions does not list a 2.x version on ubuntu 20. I can't look further into it at this time, but I'd say that generally this makes the Arches upgrade more urgent.

**Comment by mradamcox** [comment]
To add a little more detail here just for good measure: The docs call for the following command to find the available 2.x release for your system. As you can see, this printout from ubuntu 20 only shows 3.x options.

```
~$ sudo apt-cache policy couchdb
couchdb:
  Installed: (none)
  Candidate: 3.1.1~focal
  Version table:
     3.1.1~focal 500
        500 https://apache.bintray.com/couchdb-deb focal/main amd64 Packages
     3.1.0~focal 500
        500 https://apache.bintray.com/couchdb-deb focal/main amd64 Packages
```

**Comment by chiatt** [comment]
Updating CouchDB would require an update to Collector, but because Collector is not supported by v7, there are no plans to release a Collector update.
