### ISSUE TITLE
Add setting to indicate that Celery is configured and running

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6804]
We do a check in several places throughout the application to determine if celery is running. If it isn't, the check can be expensive doubling the time it takes to run tests. Instead of doing the check in the application, we should only do it once in settings.py where we set a setting with the Celery status.

**Comment by mradamcox** [comment]
This would be *really* nice if it also suppresses the error logging that happens constantly when a celery broker is not available.

**Comment by azaroth42** [comment]
:100:

**Comment by chiatt** [comment]
Duplicate of #6803 and resolved in #6806
