### ISSUE TITLE
Yarn permissions error when creating projects on Ubuntu Server 18.04

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6805]
The [ubuntu_setup.sh](https://github.com/archesproject/arches/blob/master/arches/install/ubuntu_setup.sh) script installs yarn with sudo which results in the yarn  `~/.config` dir getting permissions for root rather than the user. This causes a permissions error when a user then tries to create a project. Note this only occurs on Ubuntu server, not desktop. https://github.com/archesproject/arches-docs/issues/167#issuecomment-567409153

**Comment by mradamcox** [comment]
@chiatt I think that adding this to the end of the yarn install section should fix it:

    sudo chown $USER:$USER $HOME/.config -R

**Comment by mradamcox** [comment]
Or, trying `npm install -g yarn` ([L50](https://github.com/archesproject/arches/blob/master/arches/install/ubuntu_setup.sh#L50)),  without `sudo`, though you may have tried this already.

**Comment by chiatt** [comment]
No longer an issue since moving to npm
