### ISSUE TITLE
export to shapefile broken

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6811]
I get this error when trying to export to shapefile.  It doesnt appear to be a data problem as I'm getting this on two different projects.
![Screen Shot 2020-10-30 at 8.00.49 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/82415e58-59cc-4d53-9fdb-229aa730896f)

**Comment by chiatt** [comment]
Resolved by #6815
