### ISSUE TITLE
Include settings_local.py in default app, and have MODE='DEV' in it but commented out.

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#682]
This would ease the current process for creating a dev install, and reduce a step for everyone who needs to add a few local settings.  Also, a sentence at the top of settings_local.py explaining how its variables will overwrite those in settings.py would be nice.

**Comment by apeters** [comment]
the only issue with that is that if someone should accidentally commit that file, then presumably they've updated the public file with potentially sensitive information.
