### ISSUE TITLE
check_if_celery_available method not working

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#6866]
**Describe the bug**

Core arches ``task_management.check_if_celery_available()`` does not return `True` even if celery is in fact running

**To Reproduce**
1. Spin up USD SSC project
2. Ensure rabbitmq & celery are running
3. Go to "Initiate Fiscal Year" workflow
4. Advance to step "upload parcel billing data" and upload attached file
4. Note that the terminal running celery does not show "task received" and that the frontend console should show an object whose message is "celery not running"

Notte the relevant section of code where the check method is used:
https://github.com/fargeo/usdssc/blob/master/ssc/views/process_csv.py#L165

[nbs_parcels.xlsx](https://github.com/archesproject/arches/files/5526171/nbs_parcels.xlsx)

**Comment by chiatt** [comment]
I just tested the celery check and it's working as expected in stable/5.1.x and master, so I'm going to transfer this issue to the usdssc project.
