### ISSUE TITLE
The report does not show the resource instance name (displayname) properly

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#6876]
**Describe the bug**

![Screen Shot 2020-11-13 at 8.52.51 AM.png](https://images.zenhubusercontent.com/5c6c877ade77103362c0ab7e/9a85fd66-b43a-4d38-8306-0cbf1c5c0839)

**To Reproduce**

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
Resolved in #6878
