### ISSUE TITLE
EDTF Widget: Add ability to show examples of valid date encoding in the widget

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#6896]
The EDTF widget looks like any other input widget.  But it expects data to be entered according to strict rules.

We should add a link to the widget that, when clicked, shows a panel that displays examples of valid date strings.

Ask @dwuthrich for explanation of the proposed UI.

**Comment by ryan86** [comment]
Blank format panel now appears near label of EDTF widgets in resource editor. Work is in `6896_edtf_formats_panel` branch
