### ISSUE TITLE
Arches Editor: Show card without requiring extra button click

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#6897]
Arches Editor seems to have reverted such that a user has to click a second button to display a card when entering information to a branch for the first time.

See: https://recordit.co/2HAVFnQnNZ

-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-Now in ticket: https://github.com/archesproject/arches/issues/6919-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-
For nested Cards, the initial selection of the card requires 2 button clicks: https://recordit.co/Ivnrw0b4QR

What should happen: Arches should show the form when selecting the branch to edit for cards.  For nested cards the editor should put the card in a state allowing the user to select the card to be edited

**Comment by ryan86** [comment]
Split this ticket in two because resolving for nested cards requires a change to tile save logic. 

Ticket for nested cards: https://github.com/archesproject/arches/issues/6919
