### ISSUE TITLE
Better handle duplicate geoms on map

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6898]
Sometimes separate resource instances share a common duplicate geometry.  Would be nice if Arches did a better job of acknowledging that the geom you are clicking on on a search map has two features at that given location.  

Currently, I handle this by using transparency on my features and relying on the degree of opaqueness of the features to determine if there are many at that location - but this is less than optimal.  There are many potential design approaches to resolving this in a better way.

**Comment by chiatt** [comment]
Resolved in #8038
