### ISSUE TITLE
Arches Editor: Show nested cards without requiring extra button click

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#6919]
For nested Cards, the initial selection of the card requires 2 button clicks: https://recordit.co/Ivnrw0b4QR

What should happen: Arches should show the form when selecting the branch to edit for cards. For nested cards the editor should put the card in a state allowing the user to select the card to be edited

Note: For nested cards, currently the initial click creates a parent tile. Resolving this ticket without modifying tile save logic could potentially lead to orphaned parent tiles.

**Comment by chiatt** [comment]
Resolved in #7035
