### ISSUE TITLE
support deferred indexing for tile.delete

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#6923]
the Tile proxy model ``save`` method supports not indexing via the kwarg ``index=False``. Given that its ``delete`` method also indexes, for the same reasons it should also support not indexing via kwarg.
**User Story**

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by apeters** [comment]
merged by #6933
