### ISSUE TITLE
Crosshair mode activated when drawing geometry

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#6930]
**User Story**

As a user, I want to have the crosshair cursor mode activated when geometry is being drawn.  This is to allow greater accuracy when placing geometry vertices.

**Acceptance Criteria**
-   [X] Cursor is a crosshair when geometry editing mode is activated.
-   [X] Local installation check passed
-   [X] Unit tests passed

**Notes**
We have this fix in a local application so we'll feed this back into Core Arches at stable/5.1.x

**Ticket Background**
* Sponsored by: Historic England
* Suggested by: Historic England
* Designed by: Historic England

**Comment by chiatt** [comment]
resolved in #6947
