### ISSUE TITLE
Improve labels under Manage dropdown in Arches Designer Front page

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6959]
IMHO: Export, Clone, and Delete should say: "Export Model", "Clone Model", "Delete Model" respectively.

This is in order to mitigate the possibility of confusing exporting, cloning, or deleting instances versus the model.

![Screen Shot 2020-12-17 at 11.00.02 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/73e94fb0-90b4-4cb0-bd4f-291f7c17aace)

**Comment by chiatt** [comment]
Fixed in #8446
