### ISSUE TITLE
update widgets according to latest mockups

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#698]
the following existing widgets need to be revisited for compliance w/ latest [mockups](http://archesproject.github.io/mockups/arches_widgets.html):

- [ ] [text](https://github.com/archesproject/arches/blob/master/arches/app/media/js/widgets/text.js)
- [ ] [switch](https://github.com/archesproject/arches/blob/master/arches/app/media/js/widgets/switch.js)
- [x] [datepicker](https://github.com/archesproject/arches/blob/master/arches/app/media/js/widgets/datepicker.js)

We also have an existing [select](https://github.com/archesproject/arches/blob/master/arches/app/media/js/widgets/select.js) widget, but this one will be a fair bit more complicated than these three, so I'd suggest handling it as part of another ticket.

**Comment by chiatt** [comment]
@robgaston Should I close this ticket? It's covered now by tickets for individual widgets.

**Comment by robgaston** [comment]
@chiatt Yeah, that makes sense to me
