### ISSUE TITLE
edtf field doesnt display properly in the details tab

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#7006]
![Screen Shot 2021-01-14 at 8.28.38 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/bd687eeb-1656-42e0-ad60-43caf3abdb9d)

Data showing in the editing card.  It also displays properly in the generic report.
![Screen Shot 2021-01-14 at 8.29.58 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/4ed0bee4-ea2e-4077-bb2f-d734fe6346da)

**Comment by chiatt** [comment]
Fixed in #7079
