### ISSUE TITLE
The annotation card tree does not show the useful information

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#7053]
The iiif annotation card tree does not show any useful information, showing [object object] instead.
It would be nice to show the number of annotations in the tile.

**Screenshots**
![Screen Shot 2021-01-28 at 11 25 45 AM](https://user-images.githubusercontent.com/17627335/106188620-0c872100-615c-11eb-8838-a8ebb18af336.png)

**Comment by chiatt** [comment]
Resolved in #7055
