### ISSUE TITLE
KeyError when checking for constraint violations on provisional values

### ISSUE THREAD

**Issue by ads04r** [archesproject/arches#7089]
**Describe the bug**

We have a resource model (Grid Square) that may be referenced from another (Heritage Place). If a user without reviewer rights creates a Grid Square, it succeeds and creates a provisional item. However, from this point onwards no users can create Grid Squares. All attempts to create one result in the creation of a Grid Square with no tiles, and the user receives a KeyError.

The error is thrown in the check_for_constraint_violation method in arches/app/models/tile.py. Looking at exported data I see that provisional values do not store their data within the 'data' property of the tile, and this function attempts a comparison between items within this data dictionary without first checking the key exists.

**To Reproduce**
1. Log into the EAMENA database as an editor user (not a reviewer)
2. Create a grid square.
3. Attempt to create another grid square (as any user)

**Screenshots**

![arches-keyerror](https://user-images.githubusercontent.com/3020337/107086120-730dde00-67f1-11eb-8f04-208c7061110e.png)

**Expected behavior**
The second, and all subsequent, grid squares should be created, and their tiles populated, without error (unless the user enters a grid square ID that has already been used, in which case an error should be thrown).

**Your Arches Information**

*   Version used: 5.2 (but also 5.0 and 5.1)
*   Operating System and version (desktop or mobile): Windows / Desktop
*   Browser Name and version: Firefox
*   Link to your Arches Install (optional): Currently not public

**Additional context**
* The Grid Square resource model contains a string value which is a unique identifier, which is probably why we do not see this behaviour on our other resource models.
* In identifying this issue, I became aware of #6701 which suggests ensuring all data keys exist on tile creation. Once the issue described in this ticket is resolved, the problem described in this ticket will most likely not happen again.

**Ticket Background**
*   Found by: Mike Fisher

**Comment by chiatt** [comment]
Resolved in #7098
