### ISSUE TITLE
As a user, I want to be able to associate functions to widgets and cards in the card designer

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#709]
I need a way to assign multiple functions to both cards and widgets in the card designer.

This should be done via a multi select dropdown in both the card and widget configuration forms.

The options in the dropdown should be filtered based on the context (card or widget & datatype).

#### Acceptance Criteria
- [x] Filtered dropdown of functions in card form
- [x] Filtered dropdown of functions in widget form
- [x] Ability to save functions added to widgets & cards
- [x] Unit Tests passed
- [x] Documentation

**Comment by dwuthrich** [comment]
meets requirements
