### ISSUE TITLE
Card Desiger: Card-level cardinality tile

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#716]
If user selects cardinality = n for a Card, a tile is shown to indicate where saved node group values will be rendered.  Currently, form allows user to add a "Tile Name"

Arches should allow the user to indicate the Tile Name should include the values for the nodes in the node group.  For example, if the Node Group included Address (string) and Address Type (domain), the Tile title could allow the user to define the title as:

Address: [Address], Type [Address Type]  such that the Card would show a tile as:

Address: 601 Montgomery St., San Francisco, Type: Primary

**Comment by apeters** [comment]
Currently we show the first node/value pair as the "Tile name".  The user currently has no control over this (and probably shouldn't).
