### ISSUE TITLE
Widget Report Template

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#718]
Widgets ship with CRUD forms designed to support creation/editing of data.   

Widgets should also define the manner in which related data should be rendered in a report.  We'll need to decide if each widget should include the report template or if the report template should be defined independently of the CRUD widget.

**Comment by robgaston** [comment]
This is done - we just need to develop the templates for each widget (which I think should be done as part of the individual widget tickets)

**Comment by dwuthrich** [comment]
agreed that this ticket now is part of individual widget creation
