### ISSUE TITLE
Widget: Default config of String Widget

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#721]
What should be the config for the default String Widget and String datatype be

**Comment by jmunowitch** [comment]
### Default Widget Config:
```
{
    'inputmask': '*',
    'defaulttext': 'Default Text',
    'maxlength': '255'
}
```
inputmask options could be a regex expression to force specific inputs

### Default Datatype Config:
```
{
   'content': 'My Content String'
}
```

**Comment by robgaston** [comment]
here's what I'm thinking:

### Default Widget Config:
```
{
    "inputmask": "*",
    "defaulttext": "",
    "maxlength": 255,
    "placeholder": "Enter text"
}
```

### Default Datatype Model:
a javascript string primitive (empty by default)
```
""
```

**Comment by dwuthrich** [comment]
meets requirements
