### ISSUE TITLE
Widget: Default config of Number Widget

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#722]
What should be the config for the default Number Widget and Number datatype be

**Comment by jmunowitch** [comment]
### Default Widget Config:
```
{
    'inputmask': '*',
    'defaultnumber': '100.5',
    'decimals': '2'
}
```
inputmask options could be a regex expression to force specific inputs
decimals is the number of decimal places accepted

### Default Datatype Config:
```
{
   'content': '352.52'
}
```

**Comment by apeters** [comment]
min/max allowed values?

**Comment by jmunowitch** [comment]
@apeters: I have updated the above comment with a max and min allowed values.

**Comment by robgaston** [comment]
We should use real numbers:

### Default Widget Config:
```
{
    "defaultnumber": 0,
    "max": null,
    "min": null
}
```

### Default Datatype Model:
a javascript number
```
0
```

**Comment by dwuthrich** [comment]
meets requirements
