### ISSUE TITLE
Widget: Default config of Geometry Widget

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#723]
What should be the config for the default Geometry Widget and Geometry datatype be

**Comment by jmunowitch** [comment]
### Default Widget Config:
```
{
    'geometrytype': '*'
}
```
geometrytype options could be:
- points
- lines
- polygons
Multiple types would be separated by a comma. `'points,lines'`

### Default Datatype Config:
```
{
   'geometry': 'WKT or WKB',
   'SRID': 'EPSG:4326',
   'title': 'my geometry',
   'description': 'is the best geometry'
}
```
Geometry storage is up for discussion. WKT or WKB makes sense. 
filehash would be something chosen on a system wide basis. I would suggest SHA256.

**Comment by dwuthrich** [comment]
Note that a geometry widget will be presented in the UI as a map, so additional options to consider might include default basemap, default geocoding service, support for keyed-in coordinates, allow creation of geometry via kml/geojson.

**Comment by jmunowitch** [comment]
I added a few more options to the Widget Config:
### Default Widget Config:
```
{
    'geometrytype': '*',
    'defaultbounds': '(-122.409693, 37.786236), (-122.394748, 37.798745)',
    'databoundary': 'WKT or WKB polygon boundary',
    'inputtype': '*',
    'defaultbasemap': 'stamen-toner-lite',
    'basemaps': 'stamen-toner-lite,stamen-terrain, stamen-watercolor, mapbox-streets, mapbox-vintage',
    'defaultgeocoder': 'mapzen-search',
    'geocoders': 'mapzen-search, mapbox-geocoding, googlemaps-geocoding',
    'geolocate': 'true',
    'measurements': 'true',
    'interactive': 'false',
    'rotation': 'true'
}
```
geometrytype options could be:
- points
- lines
- polygons
Multiple types would be separated by a comma. `'points,lines'`
defaultbounds represents the default geographical bounding box, set by the southwest and northeast points in longitude and latitude.
databoundary is a boundary that limits the area that geometry can be collected.
inputtype options could be:
- drawn
- coordinates
- upload
Multiple types would be separated by a comma. `'drawn,upload'`
measurements would allow a user to pull up a measurement tool
interactive could generate a static map that a user would not be able to pan or zoom
rotation could prevent a user from rotating the map, to ensure that north is always up.

**Comment by apeters** [comment]
looking at the map settings and initial config that mapping libraries like OL3, leaflet, et al. offer might also be informative when thinking about the "Default Widget Config".

What about min/max zoom?  What about other user controls like drawing tools?

**Comment by dwuthrich** [comment]
meets basic requirements
