### ISSUE TITLE
Height incorrectly calculated in various places, results in vertical double scroll

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#7232]
This unwanted behavior can be seen in various places in arches-core, and may have many different roots depending.

An example of this ( and found root-cause! ) appears to be in the report page. In any arches instance, navigate to `http://localhost:8000/report/${UUID}` . Notice how there's a double-vertical-scroll and a non-standard footer.

The vertical double-scroll in this case appears to stem from the `scroll-y` class. Currently `scroll-y` has a set height of 100vh, without taking into account the 50px-tall top navbar. Taking into account the extra height ( via `calc` ) appears to remediate the issue in this case. 

Is this change 'safe' enough to go into core? Otherwise in can be implemented on the project or report theme level.

**Comment by chiatt** [comment]
Resolved in #7233
