### ISSUE TITLE
Photo workbench panel shows all card nodes, even if they are configured as invisible in the card designer

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#7247]
In the photo gallery card, the edit panel shows all nodes in the card even if a node's visibility parameter has been configured as invisible.

This behavior can be seen in the Arches-HER package: add an image to the photos branch on the Consultations site visit card and compare to how the card is configured in Arches Designer

**Comment by chiatt** [comment]
Fixed in #7258
