### ISSUE TITLE
Widget: Default config of Boolean Widget

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#725]
What should be the config for the default Boolean Widget and Boolean datatype be

**Comment by jmunowitch** [comment]
### Default Widget Config:
```
{

}
```

### Default Datatype Config:
```
{

}
```

This is pretty empty. Default True/False. 

We could do something related to the option to change the nomenclature, such as
True/False
On/Off
Active/In-Active

**Comment by apeters** [comment]
> We could do something related to the option to change the nomenclature, such as
True/False
On/Off
Active/In-Active

I like that idea

**Comment by robgaston** [comment]
perhaps....

### Default Widget Config:
```
{
    "trueLabel": "True",
    "falseLabel": "False"
}
```

### Default Datatype Model:
a javascript boolean primitive 
```
false
```

**Comment by robgaston** [comment]
@chiatt The `radio-boolean` widget looks great.  It looks like the default widget for the 'boolean' datatype (`switch`) needs some attention though.  We still need to add the form there that lets the user specify the `subtitle` value.  I think it just needs to be added to the widget template (as we are already managing subtitle as part of the widget configuration for `switch`).  Could you please add that in?

**Comment by chiatt** [comment]
@robgaston Thanks Rob - I didn't see the switch in the mockups - so I left it alone for the time being, but I'll go ahead and finish that up.

**Comment by chiatt** [comment]
@robgaston Hi Rob - I added the subtitle to the widget configuration

**Comment by robgaston** [comment]
@chiatt the widgets look good to me.  I notice that the `radio-boolean` widget is currently the default widget for the 'boolean' data type, while I was expecting the `switch` widget to be the default.

@dwuthrich which widget should we use as the default?

**Comment by chiatt** [comment]
@robgaston Thanks Rob - the mockups showed the radio, so I made that the default

**Comment by robgaston** [comment]
From @dwuthrich:

> Default for the boolean widget should be the radio buttons

**Comment by dwuthrich** [comment]
meets requirements
