### ISSUE TITLE
Widget: File Upload Widget

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#726]
What should be the config for the default File Widget and File datatype be

**Comment by jmunowitch** [comment]
### Default Widget Config:
```
{
    'accept': '*'
}
```
accept options are the same as HTML accept options:
- A file extension starting with the STOP character (U+002E). (E.g.: ".jpg,.png,.doc")
- A valid MIME type with no extensions
- audio/* representing sound files HTML5
- video/* representing video files HTML5
- image/* representing image files HTML5
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes

### Default Datatype Config:
```
{
   'url': '/usr/local/my-file.pdf',
   'title': 'my file',
   'description': 'it has all my passwords in it, do not touch!',
   'filehash': 'somethingreallylong!!!'
}
```
filehash would be something chosen on a system wide basis. I would suggest SHA256.

**Comment by dwuthrich** [comment]
Max allowable file size should also be a config option

**Comment by jmunowitch** [comment]
How about this update to the Widget Config:
### Default Widget Config:
```
{
    'accept': '*',
    'maxfilesize': '*'
}
```
accept options are the same as HTML accept options:
- A file extension starting with the STOP character (U+002E). (E.g.: ".jpg,.png,.doc")
- A valid MIME type with no extensions
- audio/* representing sound files HTML5
- video/* representing video files HTML5
- image/* representing image files HTML5
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes
maxfilesize options:
- A * is no limit
- other values should follow the following formula: <number><letter designation>. Examples being: 10B, 10K, 10M, 1G.
- A number value with no letter designation is defaulted to bytes

**Comment by jmunowitch** [comment]
Something to consider for maxfilesize: Do we want to set different limits on different filetypes?

e.g. If this widget config allows both audio and video being uploaded, should someone be able to set a maxfilesize for audio, and a different maxfilesize for video?

**Comment by dwuthrich** [comment]
We might have separate widgets for audio vs. video files, so I think we can live without needing to specify different file sizss on different file types (at least for now).

**Comment by dwuthrich** [comment]
meets requirements
