### ISSUE TITLE
Clicking on search map icon breaks search results panel display

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#7261]
**Describe the bug**

When clicking on a resource instance on the search map in Arches-HER, the search results panel is updated such that panel containing filters for resource type and QA type disappears, as shown on the following screen capture:

https://recordit.co/vZIq55Ug6R

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
Resolved in the latest
