### ISSUE TITLE
Workflow Multi-tile step shows all nodes, even hidden nodes

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#7267]
In the Site visit workflow, the site visit attendees step allows the user to add information about people who attended a site visit.

After entering and saving attendee data, Arches shows the user's input as a tile on the right side of the workflow step.  As currently implemented, the widget shows the user's input AND ANY ADDITIONAL nodes on the card, even those configured as invisible.

What should happen: the widget should only display node values that have been configured at "visible" in the card designer

**Comment by chiatt** [comment]
Resolved in #7273
