### ISSUE TITLE
Graph Manager: Multiple Semantic Nodes in a Graph affect sub cards

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#729]
### Bug Report

Starting a graph with a string of semantic nodes forces all data entry nodes into a single sub-card

#### Expected Behavior

User should be able to define a semantic path (eg: multiple semantic nodes start with top node) and still be able to implement multiple sub cards

**Comment by apeters** [comment]
this appears to be fixed.
![screen shot 2016-10-20 at 12 46 12 pm](https://cloud.githubusercontent.com/assets/823773/19575403/3f67f134-96c3-11e6-87fc-934805ef2628.png)
