### ISSUE TITLE
In label based graph endpoint cardinaltiy n cards sometimes return an object rather than array

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#7303]
The label based graph endpoint `resources/[uuid]?format=json` returns an array of tiles if a card has a cardinality of n and there is more than 1 tile for the card. However, if there is only one tile, the endpoint returns a tile object rather than array with 1 tile. This can make programming against the api a bit tricky because the developer does not know whether the value will be an object or an array. To resolve this issue, the value for a cardinality n card should always be an array regardless of the number of tiles.

**Comment by chrabyrd** [comment]
fixed in #7315
