### ISSUE TITLE
css fixes

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7304]
**Describe the bug**

The graph name header div can become displaced if a project adds a nav-header. Also the search results div in search appears off center due to its positioning

**To Reproduce**

**Screenshots**

![Screen Shot 2021-04-09 at 1 44 18 PM](https://user-images.githubusercontent.com/8366985/114238670-de7f4380-9939-11eb-88b7-c735b6fc283d.png)
![Screen Shot 2021-04-09 at 1 46 08 PM](https://user-images.githubusercontent.com/8366985/114238765-01115c80-993a-11eb-9f35-eefdfa7a574b.png)

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chrabyrd** [comment]
This should now be fixed  #7292
