### ISSUE TITLE
Some workflows create multiple resources

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#7307]
This is reproducible in the consultations workflow in arches-HER, but is indicative of a deeper issue that lives in core. 

If the nodegroup_id param of a workflow step isn't the top-level node of the resource, 2 resources are created. One containing the tile data from the workflow step; and a blank, unrelated resource containing the parent node structure.

We are getting this extra tile/resource creation without any workflow interaction (eg the work saving a step multiple times). We should leverage this 'free' behavior from the arches system. 

The currently-proposed solution is to dig into how to relate these two tiles on creation or save via resource_id.

**Comment by chiatt** [comment]
Resolved in #7308
