### ISSUE TITLE
The related resource section of the default report shows erroneous relations in the section that reference the same type as the subject of the report

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#7334]
See the image below.
You can in the section entitled "Ruscha Negative" that the same resources are referenced in the above sections.  The references in "Ruscha Negative" are incorrect.

![Screen Shot 2021-04-20 at 3.29.50 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/192d0238-6a08-4159-8a17-83ff7eb0f61b)

**Comment by chiatt** [comment]
Resolved in #7372
