### ISSUE TITLE
Data model changes to support node level configuration

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#735]
- [x] Add JSON columns: `d_data_types.default_config` and `nodes.config` to support configuring nodes for datatype (eg define top level concept for a concept value)
- [x] Add a column to `d_data_types` to support defining a datatype level validation function (python), much like the `validations` table does
- [x] Add a cross table, `d_data_types_x_validations `, for relating `d_data_types` records to `validations` records

**Comment by apeters** [comment]
I'm unsure if we want to add a foreign key to the d_data_types in the validations table.
It seems highly possible that a single validation applies across data types (for example a "required" validation)

**Comment by robgaston** [comment]
@apeters perhaps for those validations that are not datatype specific we can just leave the foreign key as null.

This way we can allow for both datatype specific and generalized validation functions.

What do you think?

**Comment by apeters** [comment]
That would work.  
My other question is the need for such a thing?
We have a `validations` table we have a `validation_x_nodes` table that links a validation to a node and a node has a datatype.

**Comment by apeters** [comment]
Is this simply to be able to filter the list of validations when a user selects a datatype?

**Comment by robgaston** [comment]
Yeah, but that `validations_x_nodes` is just the linking record.

I think what we need is a way from just the `validation` record itself to know if that particular method can be used by this node.

An example would be a validation for 'geometry' data types that checks that geometries are within a particular extent.

**Comment by robgaston** [comment]
@apeters yeah, this is so that in the validations dropdown we can filter out any validation methods that are not usable given the selected data type.

**Comment by robgaston** [comment]
(and thereby allow for the creation of data type specific validation methods)

**Comment by apeters** [comment]
@robgaston, so this makes me think we may want a `d_data_types_x_validations` table.

for example: we're now comfortable with having multiple datatypes that are essentially string based (text, richtext, etc..) and we've also talked about making extended list datatypes from primitives like a list version of strings datatype

with a join table we could attach validations to as many datatypes as makes sense

**Comment by robgaston** [comment]
@apeters That makes sense to me - it's probably the most flexible design.  I'll update the ticket accordingly.

@ryan86 You'll want to use the [Django `ManyToManyField`](https://docs.djangoproject.com/en/1.10/topics/db/examples/many_to_many/) to handle these relationships (as we discussed earlier today with `Node.validations`.
