### ISSUE TITLE
Update Disambiguated ( Label-based ) graph to return more descriptive data, potentially changing the graph shape

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#7357]
There has been some developer discussion around updating `label_based_graph` to return more descriptive data.
Currently it has been proposed that we add two additional data points to the uncompacted return, `datatype` and `label`.

`label` is a reference to the `cards_x_nodes_x_widgets.label` table column. 
`datatype` is a reference to the `d_data_types.datatype` table column.

We plan to create a separate utility function for getting `label` data from `resource_id`. This will exist behind its own API endpoint, and also be leveraged ( via function, not API ) in the label_based_graph.

The proposed changes can take several different shapes, 4 of which have been briefly discussed among a small team. 

### A

- integrates `label` and `datatypes` into current graph shape
- non-breaking change
- need to specifically run logic to integrate `label` data with each node

```
"displaydescription": "<Description>",
"displayname": "sdfg",
"graph_id": "076f9381-7b00-11e9-8d6b-80000b44d1d9",
"legacyid": null,
"map_popup": " sdfg",
"resource": {
    "Heritage Asset Names": [
        {
            "@node_id": "676d47f9-9c1c-11ea-9aa0-f875a44e0e11",
            "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
            "@value": "NON_DATA_COLLECTING_NODE",
            "@label": "Asset Names",
            "@datatype": "semantic",
            "Asset Name": {
                "@node_id": "676d47ff-9c1c-11ea-b07f-f875a44e0e11",
                "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                "@value": "sdfg",
                "@label": "Name",
                "@datatype": "string",
            },
            "Asset Name Currency": {
                "@node_id": "676d47fd-9c1c-11ea-9d73-f875a44e0e11",
                "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                "@value": "Former",
                "@label": "Currency",
                "@datatype": "semantic",
                "Asset Name Currency Metatype": {
                    "@node_id": "676d4802-9c1c-11ea-a30f-f875a44e0e11",
                    "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                    "@value": "Currency Type",
                    "@label": "Currency",
                    "@datatype": "number",
                }
            },
        }
    ]
},
"resourceinstanceid": "e954c3ca-64de-411a-8d92-f1a45258e7d2"
```

### B

- adds top-level `resource_labels` key with a map of `node_id` to `label`
- non-breaking change
- does NOT require complex additional logic for graph integration

```
"displaydescription": "<Description>",
"displayname": "sdfg",
"graph_id": "076f9381-7b00-11e9-8d6b-80000b44d1d9",
"legacyid": null,
"map_popup": " sdfg",
"resource": {
    "Heritage Asset Names": [
        {
            "@node_id": "676d47f9-9c1c-11ea-9aa0-f875a44e0e11",
            "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
            "@value": "NON_DATA_COLLECTING_NODE",
            "@datatype": "semantic",
            "Asset Name": {
                "@node_id": "676d47ff-9c1c-11ea-b07f-f875a44e0e11",
                "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                "@value": "sdfg",
                "@datatype": "string",
            "Asset Name Currency": {
                "@node_id": "676d47fd-9c1c-11ea-9d73-f875a44e0e11",
                "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                "@value": "Former",
                "@datatype": "semantic",
                "Asset Name Currency Metatype": {
                    "@node_id": "676d4802-9c1c-11ea-a30f-f875a44e0e11",
                    "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                    "@value": "Currency Type",
                    "@datatype": "number",
                }
            },
        }
    ]
},
"resource_labels": {
    "676d47f9-9c1c-11ea-9aa0-f875a44e0e11": "Asset Names",
    "676d47ff-9c1c-11ea-b07f-f875a44e0e11": "Name",
    "676d47fd-9c1c-11ea-9d73-f875a44e0e11": "Currency",
    "676d4802-9c1c-11ea-a30f-f875a44e0e11": "Currency Type"
},
"resourceinstanceid": "e954c3ca-64de-411a-8d92-f1a45258e7d2"
```

### C

- changes the graph shape to better decouple `@tile_data` from generic data
- BREAKING change
- smaller, DRY-er response
- requires potentially complex refactor of`label_based_graph` logic

```
"displaydescription": "<Description>",
"displayname": "sdfg",
"graph_id": "076f9381-7b00-11e9-8d6b-80000b44d1d9",
"legacyid": null,
"map_popup": " sdfg",
"resource": {
    "Heritage Asset Names": {
        "@node_id": "676d47f9-9c1c-11ea-9aa0-f875a44e0e11",
        "@value": "NON_DATA_COLLECTING_NODE",
        "@datatype": "semantic",
        "@tile_data": [
            {
                "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                "Asset Name": {
                    "@node_id": "676d47ff-9c1c-11ea-b07f-f875a44e0e11",
                    "@datatype": "string",
                    "@value": "sdfg",
                },
                "Asset Name Currency": {
                    "@node_id": "676d47fd-9c1c-11ea-9d73-f875a44e0e11",
                    "@value": "Former",
                    "@datatype": "semantic",
                    "Asset Name Currency Metatype": {
                        "@node_id": "676d4802-9c1c-11ea-a30f-f875a44e0e11",
                        "@value": "Currency Type",
                        "@datatype": "number",
                    }
                },
            }
        ]
     }
},
"resource_labels": {
    "676d47f9-9c1c-11ea-9aa0-f875a44e0e11": "Asset Names",
    "676d47ff-9c1c-11ea-b07f-f875a44e0e11": "Name",
    "676d47fd-9c1c-11ea-9d73-f875a44e0e11": "Currency",
    "676d4802-9c1c-11ea-a30f-f875a44e0e11": "Currency Type"
},
"resourceinstanceid": "e954c3ca-64de-411a-8d92-f1a45258e7d2"
```

### D

- all points of choice C
- need to specifically run logic to integrate `label` data with each node

```
choice C but with integrated "resource_labels"
```

.
.

**Comment by robgaston** [comment]
I prefer choice B, but all of the above ignore the fact that nodegroups (or cards) have separate labels from nodes (or widgets).  As such, I'd think that the label lookup should have an object for each node ID with two properties: one for card label and one for node label.

**Comment by apeters** [comment]
I agree with Rob that none of these examples take into account card labels (essentially a label for a group of nodes).  
As for the format of the return I would vehemently say that we should choose A.  Why?  Because that's the pattern we've established and it would be consistent.  All other values are attached directly to the object and are not lookups.  Plus contextually it's just nicer when you have to inspect the JSON directly which is something I do that a lot.

In the example below takes into account the additional following properties
```
@card_title
@card_subtitle
@widget_label
```
Also notice that if a node doesn't collect a value then it doesn't have an @value": "NON_DATA_COLLECTING_NODE" property/value

```
"displaydescription": "<Description>",
"displayname": "sdfg",
"graph_id": "076f9381-7b00-11e9-8d6b-80000b44d1d9",
"legacyid": null,
"map_popup": " sdfg",
"resource": {
    "Heritage Asset Names": [
        {
            "@card_title": "Heritage Asset Names",
            "@card_subtitle": "Enter the resource name and its respective type.",
            "@node_id": "676d47f9-9c1c-11ea-9aa0-f875a44e0e11",
            "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
            "@widget_label": "Asset Names",
            "@datatype": "semantic",
            "Asset Name": {
                "@node_id": "676d47ff-9c1c-11ea-b07f-f875a44e0e11",
                "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                "@value": "sdfg",
                "@widget_label": "Name",
                "@datatype": "string"
            },
            "Asset Name Currency": {
                "@node_id": "676d47fd-9c1c-11ea-9d73-f875a44e0e11",
                "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                "@value": "Former",
                "@widget_label": "Currency",
                "@datatype": "semantic",
                "Asset Name Currency Metatype": {
                    "@node_id": "676d4802-9c1c-11ea-a30f-f875a44e0e11",
                    "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
                    "@value": "Currency Type",
                    "@widget_label": "Currency",
                    "@datatype": "number"
                }
            },
        }
    ]
},
"resourceinstanceid": "e954c3ca-64de-411a-8d92-f1a45258e7d2"
```

Another thing to keep in mind is that if the long term goal is to use this api to power future default reports in arches core, then we'd also want to consider adding additional meta data like:
```
@visible
@nodegroupid (although strictly speaking @card_title could be enough to understand which nodes are grouped)
@template
```

as a point of reference, an "all lookup" style would look like this, which would be backward incompatible and not something I'm advocating for

```
"displaydescription": "<Description>",
"displayname": "sdfg",
"graph_id": "076f9381-7b00-11e9-8d6b-80000b44d1d9",
"legacyid": null,
"map_popup": " sdfg",
"resource": {
    "Heritage Asset Names": [
        {
            "@node_id": "676d47f9-9c1c-11ea-9aa0-f875a44e0e11",
            "Asset Name": {
                "@node_id": "676d47ff-9c1c-11ea-b07f-f875a44e0e11"
            },
            "Asset Name Currency": {
                "@node_id": "676d47fd-9c1c-11ea-9d73-f875a44e0e11"
                "Asset Name Currency Metatype": {
                    "@node_id": "676d4802-9c1c-11ea-a30f-f875a44e0e11"
                }
            },
        }
    ]
},
"resourceinstanceid": "e954c3ca-64de-411a-8d92-f1a45258e7d2"
"lookup":{
    "676d47f9-9c1c-11ea-9aa0-f875a44e0e11": {
        "@card_title": "Heritage Asset Names",
        "@card_subtitle": "Enter the resource name and its respective type.",
        "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
        "@widget_label": "Asset Names",
        "@datatype": "semantic"
    }
    "676d47ff-9c1c-11ea-b07f-f875a44e0e11": {
        "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
        "@value": "sdfg",
        "@widget_label": "Name",
        "@datatype": "string"
    },
    "676d47fd-9c1c-11ea-9d73-f875a44e0e11": {
        "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
        "@value": "Former",
        "@widget_label": "Currency",
        "@datatype": "semantic"
    },
    "676d4802-9c1c-11ea-a30f-f875a44e0e11": {
        "@tile_id": "c531f990-ab5f-4ef2-b83f-177e5f9c213a",
        "@value": "Currency Type",
        "@widget_label": "Currency",
        "@datatype": "number"
    }
}
```

**Comment by chrabyrd** [comment]
@robgaston @apeters 

++ good eye, will update the options with the correct info

@apeters 

I've given myself more space than usual to respond to this so that I can hopefully better communicate my thoughts about API response normality ( really graph normality ) than in previous attempts :-)

While I have no strong opinions about option A, B, C, or D; I have an unshakably strong opinion about ensuring the `@value` key is on 100% of graph nodes.

Arches semantics are !fun! , so to keep my head straight I'd like to clarify some some basic assumptions and nomenclature beforehand.

Essentially for discussion's sake I'll be talking in general graph-theory terms:
- every data point is a node
- top node means top graph node of `resource` key in response. In Arches this is a nodegroup/card I believe. 
- child node means child of top node. In Arches I believe this is exclusively a `Node` object.
- empty means contains a value, NOT ( contains a value || has child nodes with value )

Graph normality is a scale. 

On the lowest end it's a free-for-all with no rules. Any node could have any key, so `@potato`, `@dog`, etc are all potential keys, and the consumer can only know what's available on read.

On the highest end, every node has the exact same shape and properties. In the example you're advocating for, each node would have an `@card_title`, `@card_subtitle` keys and would take the shape of an array, even if it's impossible for the data to exist naturally in that state.

Neither extreme is fantastic for development; it's the developer's burden to find a happy medium that results in the best API consumer experience.

I can completely get behind changes like NOT having `@card_title` on child nodes; it's impossible for a child node to have this data. However both top nodes and child nodes have conditions where an `@value` key can exist. So it should _always_ exist for every node. We should not be able to have one top node in the graph contain an `@value` key, and another top node in the graph not.

Conditionally displaying `@value` also shifts a burden to the API consumer. 

Currently, how can you tell if a node has the ability to collect data, but is empty?

`if !node[@value] || node[@value] === NON_DATA_COLLECTING_NODE`

How would this change with the proposed implementation?

`if node.hasOwnProperty('@value') && !node[@value]`
OR
`if node[@value] && ( node[@value] !== 'None' || node[@value] !== '')`

Adding the need for inflection logic or a complex if-statement in consuming API is a step backwards IMO.

Please do not take this rejection of conditionally displaying the `@value` key to be an embrace of the status-quo. I'm in agreement that it's imperfect and could use a change. 

Since we're now in the mindset of adding keys, should we consider something like a `@can_collect_data` key? That would factor out this dual-functionality we've currently put on `@value` ( the ability to tell if a node collects data, and the value of that data ).

A very minor tangent: My logic in accepting the denormalization of the `compact` flag involves there being a normalized graph that we can reference if we need to. This change undermines that logic. I cannot understate how strongly I feel about _not_ implementing this change.

**Comment by chiatt** [comment]
This issue is resolved with the adoption of a shape closest to **A**
