### ISSUE TITLE
Add tab-container overflow arrows to tabbed workflow

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#7358]
Currently in the tabbed workflow, there isn't great signposting that the tab container is scrollable. 

We should add arrow buttons around the tab container in a viewport-width-bound container, with logic to enable/disable scroll behavior and button UI depending on available x-overflow.

For reference, we have similar logic in the photo-gallery workbench

**Comment by chiatt** [comment]
Resolved in #7472
