### ISSUE TITLE
Add support to node form for datatype configuration form

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#736]
As we are doing with widgets, we need a node level configuration form that will leverage the data model changes in #735

By default, we only need a configuration form for the 'domain' datatype (which should be renamed to 'concept'), which simply needs to support defining a top level concept.

**Comment by robgaston** [comment]
related to #527 
We will support the feature described therein as a node configuration form.

We have not yet fully decided if the form should reside in the Graph Manager, the Card Manager or both yet.  See the comment thread in #527 for details.

**Comment by robgaston** [comment]
Datatype/node configuration is functional, but not fully implemented for the 'concept' datatype.  Currently the config form is just a text input meant to show the ability to save and load node configurations.

We will need to update this input to be a tool for selecting a top level concept, but will need to first have authority documents loaded, so I am putting this ticket ( #527 ) back into the backlog until such time.

**Comment by dwuthrich** [comment]
meets requirements
