### ISSUE TITLE
Create new related resources graph visualization component

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#7360]
We need the scaffolding for a component that reworks/replaces our existing related resources component.

For this ticket, we should create the basic component files extending our "workbench" layout (as shown in the mockup below), stub out the tabs as mocked up, and stub out the visualization element using Cytoscape.js.

This component should be API driven for all data retrieval, expecting to be instantiated with a resource ID.

[Full Mockup](https://app.zenhub.com/files/49451058/dfff9fbb-b13d-4d59-9290-90469dc09d37/download)

**Comment by chiatt** [comment]
Remaining work on this issue will be addressed in followup tickets.
