### ISSUE TITLE
The form does not load properly when the tiles are deleted in a multi-tile step 

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#7373]
For example in the site-visit attendees step,

![Screen Shot 2021-04-29 at 3.44.58 PM.png](https://images.zenhubusercontent.com/5c6c877ade77103362c0ab7e/0fb85b9c-0a78-46ff-a906-fcf595f4727d)

**Comment by chiatt** [comment]
@njkim I wasn't able to reproduce this. Are you still seeing it in your instance?

**Comment by chiatt** [comment]
It looks like this is still an issue, but it is masked by the fact that the step advances, even if the step has already been completed, before a user can see the card report appear.

**Comment by chiatt** [comment]
No longer an issue in the latest
