### ISSUE TITLE
Add missing unregister / list operations to report management command

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#7374]
The report.py management command accepts operations to unregister, list and update a report, however the methods have not been implemented. This causes an error when trying to run any of those operations:

```AttributeError: 'Command' object has no attribute 'list'```

**To Reproduce**
1. Activate the venv and go to the arches project directory and activate : 
`# source ENV/bin/activate && cd arches`
2. Run the report management commands to list, unregister or update a report
`# python manage.py report [list | unregister | update]` or
`# python manage.py report unregister -n '<report componentname>'` or
`# python manage.py report update -s '<report json config file>'`
3. See error as above

**Expected behavior**
The management function should list, unregister or update the report.

**Arches Information**

*   Version used: 5.1.3
*   Operating System and version (desktop or mobile): Linux CentOS 7
*   Browser Name and version: n/a

**Ticket Background**
*   Found by: @bferguso

**Comment by chiatt** [comment]
Resolved in #7942
