### ISSUE TITLE
If a user deletes the "Default Map Settings" in the UI then the setting page hangs and can't be restored.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#7377]
![Screen Shot 2021-04-30 at 1.45.08 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/470c736f-38db-4b78-91d4-bfb9b973fa3c)

This is actually a bug.  Some default system settings that are stored in settings.py get nulled out if they happen to be in the system settings model.  

this should actually default to those settings but in fact those settings end up being "None"
```
    except:
        min_zoom = settings.MAP_MIN_ZOOM
        max_zoom = settings.MAP_MAX_ZOOM
        default_zoom = settings.DEFAULT_MAP_ZOOM
```
https://github.com/archesproject/arches/blob/master/arches/app/utils/context_processors.py#L46-L48

**Comment by chrabyrd** [comment]
resolved in #7378
