### ISSUE TITLE
Have Search Results Details report optionally leverage label_based_graph API

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#7388]
Rough-out document of arches-core and various project data needs : https://docs.google.com/spreadsheets/d/1xsvtUZpgga8_xtpHTph-UeMzSvu94wWr7DRhcsAMVRE/edit?usp=sharing

Investigation round 2:
https://docs.google.com/spreadsheets/d/13x29WSh4e2HdZKGMaOAGqBDd2jSwLYxZJiGIMMe67x0/edit?usp=sharing

**Comment by apeters** [comment]
closed by re #7441
