### ISSUE TITLE
load_package defer_indexing doesn't actually defer indexing of resources in bulk

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7405]
**User Story**

when using the `bulk` flag, resources/tiles imported as part of the broader `load_package` operation get indexed at the time of ingestion/save even if `defer_indexing` is `True`, instead of deferring the indexing of these imported business data until the end of the parent operation

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by whatisgalen** [comment]
closing as after multiple tests/scenarios, deferring indexing while using the bulk flag performed only as fast as when indexing was not deferred, not faster, therefore for now it seems indexing should always happen in the `Resource.bulk_save` method.

**Comment by aj-he** [comment]
@whatisgalen I disagree that the indexing should always happen in `Resource.bulk_save` as `--bulk_load` is an option for package loading and package loading defers indexing to the end. So you end up indexing twice if you package load and use the `--bulk_load` option.

Plus, my fix which allows bulk_save to be used for appending after the initial resource creation (e.g. you have two CSV files one creates resources, the other adds more branch data), will mean that I'll be forced to sit through 2 indexing operations without the choice to prevent indexing.
