### ISSUE TITLE
collapsible graph/card lists in adv search

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7413]
**User Story**

It would be great to be able to collapse each graph's list of its card for a easier UI 

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
Resolved in #7414
