### ISSUE TITLE
geom datatype advanced style cloning bug

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7428]
**Describe the bug**

Somewhat convoluted, but bear with me:
If you have a graph called Historic District and you end up configuring advanced styling in its Resource Layer (in the Map Layer Manager), e.g. fill-color and what not, this advanced styling gets saved in a config object where the map source makes reference to `resource-[nodeid]`. 

If you clone Historic District and call it Historic District v2, it retains this same advanced styling however the references to the map source names remain the same. The problem here is now you're pointing to a source generated for a `nodeid` that is on a different graph (and may no longer exist). This can break the map filter in search if you end up marking the first graph "Inactive" because there still remain references to this map source which cannot be found.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
This is likely related to #5902

**Comment by whatisgalen** [comment]
A more fundamental solution here would be to implement graph versioning so that graphs wouldn't have to be cloned to be iterated over.

That notwithstanding, other than manually doing a find-and-replace of one nodeid with another in the json, there's literally no way to preserve the styling without breaking the map. To cause the least harm, I think when a graph gets cloned the map styling should just be removed altogether with some kind of alert to the user like "You will need to set map styling for this new graph." 

Otherwise we should look at alternative ways of generating these layer names that do not include a nodeid / some value unique to a graph.

**Comment by chiatt** [comment]
Resolved in #7432
