### ISSUE TITLE
bridge (import/export) to WikiData.org and Commons.Wikimedia.org

### ISSUE THREAD

**Issue by zblace** [archesproject/arches#7443]
Not sure if this was discussed before or elsewhere, but making a bridge (import/export) to WikiData.org and Commons.Wikimedia.orgsounds like something worth doing to both collect from and contribute to Wikipedia/Wikimedia sister projects.

**Comment by zblace** [comment]
OK - I will asume this is not urgent or attractive to anyone here until I get any different and direct feedback :-)

**Comment by azaroth42** [comment]
My totally unofficial two cents -- this has been discussed, but is very complicated to do in a generalized fashion, and especially with something like wikidata where the ontology is constantly shifting. And even if the remote ontology were reliable, there's still the mapping to the ontology used in the arches models to contend with.

**Comment by chiatt** [comment]
This seems like a feature that, at least initially, would probably be implemented as in project to explore how to address the issues raised by @azaroth42. For that reason I'm going to close this ticket, but the conversation can be continued on the forum here: https://community.archesproject.org/t/bridging-import-export-wikidata-org-and-commons-wikipedia-org/1198
