### ISSUE TITLE
Geometry editor fails on first attempt to create new geometry

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#7445]
When working in a geometry card, the user's initial digitization effort fails.  As shown in the following video, when the user selects a geometry creation tool such as the add new polygon, Arches seems to create a geometry,  But when finishing the digitizing effort the geometry is lost.  Attempting to create a geometry a second time succeeds.

https://recordit.co/Ajr560JB9V

**Comment by chiatt** [comment]
Hi @dwuthrich - I tested this with the Consultation Location card in Consultation, but did have any problems. Could you try testing geom creation in Consultation Location to check that the error is occurring for you there as well?

**Comment by chiatt** [comment]
I suspect this might be due to conflict issue between the basemap and the related resource map card. I've swapped all of the problematic basemaps out with versions that work with the card so this issue shouldn't occur again. I'm going to close this for now unless it reoccurs.
