### ISSUE TITLE
Hovering over a related resource item in the Related Resource Map Card causes the map to flicker

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#7447]
When a user relates a resource in the Related Resource Map card, and the overlay for the related resource is not visible, the map flickers when the user hovers over the resource name (see video).

What should happen?  If the corresponding overlay isn't enabled, the map should not flicker.

If the overlay is enabled, It would be nice to support zooming to the resource instance on clicking the instance name, in addition to highlighting it on the map when hovering over the name.

https://recordit.co/4fYOlvM9ee

**Comment by dwuthrich** [comment]
Note that the flicker happens even if the overall for the related resource has been added to the map

**Comment by chiatt** [comment]
Issue addressed by `Some basemaps cause related resource map card to fail` #651
