### ISSUE TITLE
indexing optimizations

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7485]
Methods related to indexing don't always use the most performant code. This Issue seeks to make performance enhancements mostly through implementation of dict and list comprehensions. This issue also seeks to implement dict and list comprehensions throughout core arches where appropriate, including Resource and Tile proxy models, concepts, Card and Graph.

**User Story**

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
Closing re #7487
