### ISSUE TITLE
create a management command to index resources by type

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7488]
**User Story**

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
Resolved in #7490
