### ISSUE TITLE
Graph relationship management UI unclear

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#749]
In the Graph Manager, when creating a relationship between two Graphs, the label for the dropdown of possible relationships to select is "Relation to parent". This is confusing, as the relationship is actually _from_ the parent to the child that was just added, rather than from the child to the parent.

As a data modeler, I create two graphs, an E7 Activity and an E40 Legal Body that can carry out that Activity and want to link the two together with the P14 carried out by relationship.  In order to add this relationship, I have select the Legal Body node, and say that the relationship from that node to the parent is carried out by, which is not correct.

Requested Change:  Modify the UI template to say "Relationship from Parent"

Nice to Have:  Dynamically generate the UI to say "Relationship from [name of parent node]"

Nice to Have: Below the dropdown, dynamically generate text:  "[name of parent node] [name of relationship] [name of currently selected node]", e.g. `Activity p14_carried_out_by Legal Body`

**Comment by jmunowitch** [comment]
Thanks @azaroth42. We are taking a look at this and should be adding it to our current Sprint.

**Comment by dwuthrich** [comment]
meets requirements
