### ISSUE TITLE
JS error on default Arches landing page - jquery-migrate + revolution-slider

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#7500]
**Describe the bug**
I just created brand new projects from tags 5.1.1, 5.3.1, and branch stable/5.2.x and all of them had this same error on the landing page dev tools console output:

`Uncaught TypeError: a.event.addProp is not a function`

![image](https://user-images.githubusercontent.com/10427268/120851379-5c2c8d80-c53e-11eb-85bd-12da1041ed32.png)

**To Reproduce**
1. Go to the default Arches landing page

**Your Arches Information**

*   Version used: 5.1.1, 5.3.1, stable/5.2.x

**Additional context**
It may be that the revolution-slider plugin is trying to use a jquery-migrate function that has been deprecated, as described here: https://stackoverflow.com/a/37791711/3873885.

**Ticket Background**
*   Found by: @mradamcox

**Comment by robgaston** [comment]
does the error mentioned cause any issues with behavior on the page?

To resolve this, i'd say we should probably upgrade or remove the revolution-slider plug-in if possible.

**Comment by mradamcox** [comment]
As far as I can tell, everything does display correctly. I added another slide to index.htm and that also works.

**Comment by chiatt** [comment]
This seems to be fixed in the latest. I just tested with a new project created from 5.2.x and I'm not getting the error. However, I don't see where it was fixed. @mradamcox if you see the error again, please reopen.
