### ISSUE TITLE
Add visual cue to indicate that the application is in DEBUG mode

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#7517]
When the application is in DEBUG mode, we should provide some visual indication in the application of this.  This will alert system administrators in case they are inadvertently running in DEBUG mode in production.

However we achieve this it should be a visual cue that is obvious to any visitor but doesn't impact the layout of the DOM.

Here is an example of how Flutter handles this by default (see banner in upper right hand corner): 

![image](https://user-images.githubusercontent.com/1187406/122123369-c23cce80-cde2-11eb-9e72-ebda917c1eea.png)

**Comment by chiatt** [comment]
Fixed in #8637
