### ISSUE TITLE
The undo dirty state doesn't update when coming back to a step when using the NonTileBasedComponent in the component based step

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#7526]
@apeters commented on [Fri Jun 18 2021](https://github.com/archesproject/arches-for-science-prj/issues/379)

To reproduce (using AFS):
Enter data for the select-phys-thing-step (first step in the Upload Dataset workflow), then go the next step.
Then go back to the select-phys-thing-step, make a change and hit the undo button.
Notice that the value is correctly undone, but the undo button persists.

**Comment by chiatt** [comment]
Resolved in #7527
