### ISSUE TITLE
As a form editor, I want to be able to edit the attributes associated with a form and be able to manage the cards associated with a form

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#753]
**Data entry cards**
![screen shot 2016-09-07 at 10 06 02 am](https://cloud.githubusercontent.com/assets/823773/18321656/c4af1860-74e3-11e6-9ccd-e37e24f845a2.png)

![screen shot 2016-09-07 at 10 05 22 am](https://cloud.githubusercontent.com/assets/823773/18321671/d46146fc-74e3-11e6-93d0-3b162c40573b.png)

**Comment by dwuthrich** [comment]
meets requirements
