### ISSUE TITLE
As a form editor, I want to be able to edit the form identifiers associated with a form

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#754]
**Form identifiers**
![screen shot 2016-09-07 at 10 11 32 am](https://cloud.githubusercontent.com/assets/823773/18321619/8e79aed6-74e3-11e6-9761-bbeb9d176049.png)

**Comment by apeters** [comment]
The UI has been updated a little bit (now only 3 tabs).
See #751 for changes

**Comment by dwuthrich** [comment]
meets requirements
