### ISSUE TITLE
Change manifest primary key to UUID

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#7540]
Currently the primary key for a iiif_manifest record is an integer. It should be changed to a UUID to be consistent with other Arches models.

**Comment by aarongundel** [comment]
@chiatt was the official determination here that this was going to be abandoned or postponed?

**Comment by chiatt** [comment]
Thanks @aarongundel - I spoke with @robgaston, @apeters & @chrabyrd and we concluded there isn't any harm to leaving it as it is, so I'll go ahead and close this.
