### ISSUE TITLE
registering a report doesn't use the componentid in the json config

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7543]
when registering a new report, if the config json contains a componentid, this doesn't get automatically used for saving the report to the db. instead a new uuid gets generated. It would be ideal if the register logic could look for the componentid and use that if one exists in the provided config son

**Comment by aarongundel** [comment]
@whatisgalen just to clarify here - is what you're looking for when registering the report "templateid" instead of "componentid"?

**Comment by chiatt** [comment]
The templateid is essentially the componentid in this case (It's the widgetid for widgets and the componentid for card components). I think the templateid would meet @whatisgalen's suggested use case, so I'm going to close this ticket.
