### ISSUE TITLE
Interacting with feature nodes in the iiif annotator creates duplicate rows in UX geometry table

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#7579]
see https://recordit.co/OFMijn0tO1

**Comment by robgaston** [comment]
based on some initial testing, I observed that this bug was not present prior to #7570

**Comment by robgaston** [comment]
specifically, these changes appear to be the cause (when rolled back, this bug is resolved): https://github.com/archesproject/arches/blame/973ec03316e3f987410a772861b4bfdd17727d67/arches/app/media/js/views/components/iiif-annotation.js#L98-L102

**Comment by chrabyrd** [comment]
@robgaston yep! good eyes, just balancing the undo with new changes to the afs workflow component now :)

**Comment by chrabyrd** [comment]
fixed in https://github.com/archesproject/arches/pull/7580
