### ISSUE TITLE
map is broken after upgrade to OL 3.2

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#758]
after this commit re c34a941, the map appears to be broken

go to [http://localhost:8000/map](http://localhost:8000/map) to confirm (running v3 of course)

we need to fix this ASAP!

**Comment by jmunowitch** [comment]
@apeters: Is the issue that the basemap is no longer working, or is OL not instantiating?

**Comment by jmunowitch** [comment]
Looks like this was an issue with an older version of an Arches v3 App.  Updating to the latest v3 App seemed to solve it.
