### ISSUE TITLE
include resourceinstanceid in report RR's list

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7591]
the report model offers the display name, the "link", and the relationship of a given RR for a resource instance. To get the resourceinstanceid one has to parse it from the link text, but it would be a bit more streamlined if "resourceinstanceid" were simply available as part of the RR object
**User Story**

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
Resolved in #7592
