### ISSUE TITLE
Shouldn't call save method on any child object outside of the parent object save in card.py

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#761]
on around [line 107 of card.py](https://github.com/archesproject/arches/blob/master/arches/app/models/card.py#L107) the `widget_model` is saved during card object creation.  This can polute the database if the user is not careful.

`if widget_model.pk == None:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`widget_model.save()`

**Comment by chiatt** [comment]
It looks like this has been addressed
