### ISSUE TITLE
override termfilter bug for resource instance select

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#7645]
**Describe the bug**

When overriding the termfilter in resource instance select with a function, calling that function causes an explosion because "data" is not defined.

**To Reproduce**
1. Using AFS
2. Start Upload DataSet Workflow
3. Pick a project
4. Try to pick a thing
5. Check console for error

**Screenshots**

**Expected behavior**
The term filter should be able to be overriden.  The issue is that data was replaced in a recent PR with a "QueryString" object.

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
Resolved in #7646
