### ISSUE TITLE
Datetimepicker widget is positioned incorrectly

### ISSUE THREAD

**Issue by coherit** [archesproject/arches#7649]
**Describe the bug**
When using the Time Filter on the Search page, clicking on the To input box causes the datetimepicker widget to appear in the center of the viewport rather than attached to the input box. 

**To Reproduce**
1. Go to /search
2. Click on the calendar icon to open the Time Filter
3. Click on the To input box. 
4. You'll notice the bug: the calendar appears in the center of the screen. 

**Screenshots**
![Inked106930394-7ca92000-66e3-11eb-8c30-4518056ac7de_LI](https://user-images.githubusercontent.com/3217017/127185901-ecaab2f9-c208-4756-bb42-f31e36cf65fe.jpg)

**Expected behavior**
The datetimepicker should appear as it does when you click From (just under the input box).

**Your Arches Information**
*   Version used: 5.1.x, 5.2 beta
*   Operating System and version (desktop or mobile): Ubuntu server 18
*   Browser Name and version: chromium
*   Link to your Arches Install (optional): local dev box

**Additional context**
This is caused by a known "feature" of the boostrap datetimepicker. Basically, if the container that the input field is not position:relative, then this positioning bug occurs. Fix can be applied to arches.css (tag is .calendar.picker). I will submit this fix for review as a new PR. 

**Ticket Background**
*   Found by: @kkemp85 as part of https://github.com/legiongis/fpan/issues/183  Tested and confirmed in vanilla 5.1.x and 5.2.b by @coherit.

**Comment by chiatt** [comment]
Resolved in #7650
