### ISSUE TITLE
"tiles" argument in search_results view doesn't get handled properly

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7669]
**User Story**

when the ``search_results`` url gets called with a request, the request object has a parameter called ``tiles`` which is either true or false. When this parameter gets checked in the Django view, it looks like this:
``if request.GET.get("tiles", None) is not None:``
The problem here is that **any** value, whether ``"false"`` or ``"true"`` will make this statement evaluate to ``True``. It would be better and more logical if the value for ``"tiles"`` on the request object was evaluated as a boolean and proceed from there.

**Acceptance Criteria**
-   [ ] <FILL IN>
-   [ ] <FILL IN>
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
resolved in #7671
