### ISSUE TITLE
Widget: Resource Listing Widget

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#767]
What should the config for the default Resource Listing widget and Data Type Model Be.

**Comment by jmunowitch** [comment]
### Default Widget Config:
```
{
    'resourcelistings': '*'
}
```

### Default Datatype Data Model:
```
{
   'resource': 'd1e9492a-4952-4e7a-9c3c-5d0b4228e844',
}
```

**Comment by dwuthrich** [comment]
Data type should be "resource listing", the intent is to select the UUID of a resource.  
WIdget should be a select widget. 
Config should allow user to select which resources will be listed in the widget

**Comment by robgaston** [comment]
Something like this:
### Default Widget Config:
`allowedResources` is an array of `graphs.graphid` values
```
{
    "allowedResources": ["22000000-0000-0000-0000-000000000002", "11111111-0000-0000-0000-191919191919"]
}
```

### Default Datatype Data Model:
an array of `resource_instances.resourceinstanceid` values
```
['d1e9492a-4952-4e7a-9c3c-5d0b4228e844', 'd1e9494d-4952-4e7a-9c3c-5d0b4228e863']
```

the widget would be a multiselect dropdown containing an entry for each record in the `graphs` table where `graph.isresource = true`; display value in the dropdown would be `graph.name`

**Comment by robgaston** [comment]
(see changes to above comment - note difference between config form and widget itself)

**Comment by apeters** [comment]
fixed in the latest
