### ISSUE TITLE
As a data editor, I want to be able to view a list of resources that were recently added to the system

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#769]
![screen shot 2016-09-07 at 10 32 55 am](https://cloud.githubusercontent.com/assets/823773/18322223/7ff49c24-74e6-11e6-848f-4fcdc60efb81.png)

**Comment by apeters** [comment]
Even though we don't have all the table columns populated we should still close this ticket.  We can open new ones for adding more data.

**Comment by dwuthrich** [comment]
meets requirements
