### ISSUE TITLE
Add exclusions to bulk resource endpoint

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#7711]
**User Story**

Adding exclusions to the bulk resource endpoint will improve performance.

**Acceptance Criteria**
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**
Exclusions are added to bulk resource endpoint

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
Resolved in #7712
