### ISSUE TITLE
New option to export data as HTML documents

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#7723]
Users often request the ability to export resources from a search in a format more like a report (PDF etc.). Currently the only option is to export it in a data set or data feed format.

This ticket proposes an export option to generate an collection of html documents containing one or more resources and allow developers to create formatted template for each model.

The export function should work using the standard export functionality.

**User Story**

As an Arches user I need to be able to export my searches into easy to read and well presented documents so that my customers have an easily accessible way to read the information without needing to process it further.

**Acceptance Criteria**
-   [ ] Users must be able to export search results as an html document
-   [ ] HTML templates must be easily written by developers
-   [ ] the templates can be added easily to a project
-   [ ] the foreground and background downloads must have a suitable threshold based on performance
-   [ ] any resources for models without a template must be ignored.
-   [ ] the HTML option is hidden if there are no valid templates.
-   [ ] an example template is provided as part of a new project.
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @aj-he 
*   Designed by: @aj-he

**Comment by chiatt** [comment]
Resolved in #7825
