### ISSUE TITLE
resource-component-abstract should use the beta endpoint

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#7742]
**Is your feature request related to a problem? Please describe.**
I cannot retrieve referenced resources from the non-beta disambiguated endpoint.  

**Describe the solution you'd like**
resource-component-abstract should use the beta version of the disambiguated endpoint.  Related resources are not currently available.

**Describe alternatives you've considered**
can't think of any alternatives to using the beta endpoint other than backporting code to the non-beta version - seems like a heavy lift.

**Additional context**
discussed with cyrus; suggested we add this to the workflows_dev branch, which contains breaking changes and will eventually merge back to stable/5.2.x

**Comment by chiatt** [comment]
Fixed in #7755
