### ISSUE TITLE
Unhandled intermittent ConnectionResetError when testing for celery

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#7768]
**Describe the bug**

Sometime when moving between pages, the celery test encounters an unhandled `ConnectionResetError`, which causes the page to present 500 error page.

You can see the error occuring in the celery process console, but it is not clear why. Handling it in the same way as a `BrokenPipeError` is the solution

**Ticket Background**
*   Found by: @aj-he

**Comment by chiatt** [comment]
Fixed in #7770
