### ISSUE TITLE
Resource models should support being "published"

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#7783]
Arches should include in the designer a way to "publish" resource models and track "publishing events" alongside resource models going forward.  These should include enough information for developers to reliably depend on a particular published version of a model in developing a project.  Packages should be able to specify their dependent published models on load such that alerts could be generated by the system if dependent models were modified.

From RDM requirements:

> To support the RDM's requirement for managing graph model content, the Arches Designer needs to be updated to support “freezing” of a model shape. This will allow Arches package developers
> to introduce models that require branches of a particular shape. Once an Arches model has been
> designed, a user will need to “un-freeze” the model to modify it and “publish” it before it can support
> data entry tasks again.
> 
> Introducing the concept of publishing Arches models will:
> - Substantially decrease the time it takes to load Arches Editor and Arches Designer pages,
> making Arches appear much faster to users
> - Allow developers to be certain that models and model branches conform to required shapes
> so that they can implement functions, plugins, and workflows in an Arches package
> - Make it possible to warn users when they are attempting to alter a model (or portion of a
> model) required by an Arches package
> 
> As the RDM will be developed using Arches’ semantic modeling capabilities, and because the RDM
> models will be required to include a core set of attributes, it will be essential to implement a method
> for publishing models.
> 
> Publishing models means that we will be able to cache model designs. Model caches mean that
> Arches will only need to query its database once (for example, the first time any user enters Arches
> editor for the model) instead of every time every user wishes to create or edit a resource instance.
>

**Comment by chrabyrd** [comment]
solved in #7934
