### ISSUE TITLE
Cache serialized graph proxy model for resource models on publish

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#7784]
When Arches models are published, we should be able to cache the complete & serialized graph data during that publish event.

Based on these requirements, a suitable caching/indexing method for these data should be determined and implemented.

When available, all code that relies on serialized graph data should use the cached versions.

Already published models should be cached on package load, and there should be a management command to cache all published graphs on demand.

Since user permissions are applied outside of the graph design/publishing process (ie they are usually applied as part of a project, not package development), they should be cached separately (see: #7785).

**Comment by chiatt** [comment]
Hey @robgaston About a year ago I wrote a simple command for managing the graph cache.
arches/arches/management/commands/cache.py

It's actually all ready to be implemented in package load: https://github.com/archesproject/arches/blob/e768cd0a533df4ac6b563381fb579a73fc33fa79/arches/management/commands/packages.py#L810-L812

`cache_graphs` just needs to be called after all graph elements (functions, cards, etc..) have been successfully loaded.
