### ISSUE TITLE
Prehistoric date indexing causing integer out-of-bounds error

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#7796]
**Describe the bug**

If you index an EDTF date of say -2580000 (years) for a prehistoric period, the `ExtendedDateFormat` class creates a sortable value that exceeds the bounds of an integer.

Currently the mappings for the resource index use `integer` and `integer_range` type, which are affected.

This needs to be changed to `long` and `long_range` types respectively.

**Ticket Background**
*   Found by: @aj-he

**Comment by aj-he** [comment]
@chiatt assign to me... PR incoming

**Comment by chiatt** [comment]
Fixed in #7797
