### ISSUE TITLE
As a user, I need to be able to search for resources stored in the system and additionally filter the results temporally, and spatially and potentially other undefined ways as well

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#780]
**General Text Search**
![screen shot 2016-09-09 at 11 54 31 am](https://cloud.githubusercontent.com/assets/823773/18400146/75ee2066-7689-11e6-8bbb-a2e2f8b9462d.png)

The panel on the right shows the location where filters/functions can use additional space for their specific ui needs and also where resource report preview (not shown) can take place.

The search module will be used in at least a couple of places: in it's own dedicated page, and as a way to select related resources during data editing operations.

The default filters that come with the search module, are temporal and spatial filters(the 2 rightmost icons).  The search module should allow for additional filters/functions to be applied easily.
![screen shot 2016-09-09 at 12 01 32 pm](https://cloud.githubusercontent.com/assets/823773/18400147/75f27ea4-7689-11e6-9fb0-c952e7690f80.png)

**Comment by dwuthrich** [comment]
meets requirements
