### ISSUE TITLE
As a user I need a page to help me manage resource that are related to the resource I'm currently editing

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#782]
**Overview**
![screen shot 2016-09-30 at 9 54 28 am](https://cloud.githubusercontent.com/assets/823773/18999732/f2aa7c56-86f3-11e6-9335-67b169b9e186.png)

**Drag and Drop area where selected resources appear(#784)**
![screen shot 2016-09-30 at 9 56 24 am](https://cloud.githubusercontent.com/assets/823773/18999797/3e267ea0-86f4-11e6-9cc7-9cb09a2a7dd8.png)

**Form to edit the details of the relationship (#783)**
![screen shot 2016-09-30 at 9 56 34 am](https://cloud.githubusercontent.com/assets/823773/18999796/3e24c484-86f4-11e6-836f-db3b99751868.png)

**Comment by dwuthrich** [comment]
meets requirements
