### ISSUE TITLE
Advanced search - related resource summary pops up with Associated facets

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#7829]
**Issue Description:** When selecting any of the associated Advanced Search facets, a Related Resource Summary box also pops up which does not need to be there. This box is also unusable, and you cannot close it. The box does not disrupt using the advanced search, and you can only just see it so the right-hand side of the facet, unless you scroll along to reveal it:

![image](https://user-images.githubusercontent.com/78143228/127498527-79c0c073-fe06-4f7d-8061-0af8b51aec0a.png)

**Comment by chiatt** [comment]
Resolved in #7911
