### ISSUE TITLE
As a data editor, I need a form to edit the relationship between resources

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#783]
The form should expect to be able to edit the relationship between a single source resource and multiple target resources.

We should also consider using a graph to manage and store relationship data.
![screen shot 2016-09-30 at 9 56 34 am](https://cloud.githubusercontent.com/assets/823773/19000003/1d8c9b60-86f5-11e6-93f4-6449e5347e78.png)

**Comment by chiatt** [comment]
Duplicate of #1329
