### ISSUE TITLE
Discard edit doesn't do anything when moving a node in the graph manager

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#789]
#### Steps to Reproduce (for bugs)

1. Create a graph and append a node/nodetype graph to the root
2. Move the node type node to the root
3. Observe that the "save edits" and "discard edits" buttons are shown
4. Click "discard edits"
5. Observe that the graph is unchanged

Moving a node should be like appending a graph.  
When appending a graph to a root node, the "save edits" and "discard edits" buttons are not shown because the save happens immediately without further user intervention.

**Comment by apeters** [comment]
can't test this until #1003 is fixed

**Comment by robgaston** [comment]
#1003 was fixed in #1004
