### ISSUE TITLE
Fix i8ln tests related to bad string data

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#7905]
**Describe the bug**

There are many tests with bad string data in the internationalization of business data branch.  These should be fixed, and are probably the lowest hanging fruit of test fixes.  

**To Reproduce**

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by apeters** [comment]
closed by #7930
