### ISSUE TITLE
GeoJSON api fails to serve data loaded via CSV

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#7955]
**Describe the bug**

The geojson api fails where geometry data has been loaded via import_business_data. This is because features don't have the `nodeId` property added to them through this process, unlike when drawn in the geojson-feature-collection widget.

Therefore, when the `nodeId` value is checked at the point below, it errors and the feature is excluded.
https://github.com/archesproject/arches/blob/33c3de8fea01041e889ed350d7b92c0a577bd1db/arches/app/views/api.py#L362-L363

The `nodeId` key should be added as part of the GeoJSON datatype `transform_value_for_tile` function.

**To Reproduce**
1. Load geometry data via `import_business_data` that includes geometries.
2. Try and view that data in a map client using the geojson api

**Screenshots**

**Expected behavior**
Data loaded via `import_busniess_data should be visible via the geojson api

**Your Arches Information**

*   Version used: 6.0.0
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @aj-he

**Comment by aj-he** [comment]
@chiatt please assign me as I'll submitting a fix shortly.

**Comment by robgaston** [comment]
@aj-he I think we don't want to require the `nodeId` property, so I think that the proposed fix ("The nodeId key should be added as part of the GeoJSON datatype transform_value_for_tile function.") here is not what we want.  Rather, we should adjust the GeoJSON API endpoint to not throw an error where that property is missing.  The goal of the lines you show above is to simply remove that property where it is present in the geojson features.
