### ISSUE TITLE
Accessibility - Resource Manager - resource model text is cut off

### ISSUE THREAD

**Issue by phudson-he** [archesproject/arches#7959]
The text explaining what the resource model is for is cut off on the majority of the resource models. This issue has been previously fixed our HE Warden implementation of Arches. The layout of the boxes can be slightly changed to include scroll bars so that users can scroll to see all the text.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/52997281/140763511-57248c0b-242d-4bef-8ffe-4ef95b090213.png)

Screenshot of fix:
![image](https://user-images.githubusercontent.com/52997281/140763581-7242a873-3ab7-4602-9ae0-03d1b5195cb1.png)

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @rlwilliamss
*   Designed by: @phudson-he

**Comment by phudson-he** [comment]
Working on this, will raise PR when done

**Comment by phudson-he** [comment]
PR Raised #7973

**Comment by aj-he** [comment]
Confirmed that this is not explicitly an accessibility requirement. Instead it is a part of a text spacing guideline where increases to text spacing should not force text to be cut off. Will review graph subtitles in implementation.
