### ISSUE TITLE
Indexing management commands to use multiprocessing

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#7963]
**User Story**
As a developer
I would like indexing management commands to be able to run in parallel processes
so that large amounts of data can be indexed more quickly.

**Related Issues**
#4858

**Acceptance Criteria**
-   [ ] there should be an optional flag in the indexing commands to enable multiprocessing
-   [ ] it should create a process per core/thread by default
-   [ ] you should be able to set a limit to the number of processes if the default is too high
-   [ ] stdout information should be handled by a logger.
-   [ ] stdout information should appear similar to standard functionality
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**
The indexing process completes using both multiprocessing and non-multiprocessing and the indexes achieve the same state.

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @aj-he 
*   Designed by: @aj-he

**Comment by aj-he** [comment]
@chiatt @robgaston I have a working prototype brought together from my Warden load hacking days that is 99% there, but I am having a minor issue with the term indexing (resource indexing appears ok). I am going to look into this a bit further but I might need someone else to perhaps discuss solutions with if I'm not able to get to the bottom of things.

Please assign to me and I'll get a PR submitted in the next few days.

**Comment by chiatt** [comment]
Resolved in #8004
