### ISSUE TITLE
Refine Profile Manager email message when settings.ADMINS is not defined

### ISSUE THREAD

**Issue by RobOatesHistoricEngland** [archesproject/arches#7979]
When settings.ADMINS is not defined, the email from the Profile Manager reads something like:

Your Arches profile was just changed.  If this was unexpected, please contact your Arches administrator at .

When it should be more like:

`Your Arches profile was just changed.  If this was unexpected, please contact your Arches administrator.`

Only when settings.ADMINS is defined, the email should be:

`Your Arches profile was just changed.  If this was unexpected, please contact your Arches administrator at persons.name@email.com.`

Where persons.name.email.com is taken from settings.ADMINS[0][1]

**User Story**
Refine the generated email to take in to account the possible absence of settings.ADMINS.  In addition, in the exception block, log the error instead of printing it when the email fails to send.

**Definition of Done**
Generated email reads as above dependant on settings.ADMINS values.

**Ticket Background**
*   Suggested by: @RobOatesHistoricEngland

**Comment by chiatt** [comment]
Resolved in #7984
