### ISSUE TITLE
GeoJSON API support for Koop pass-through requests

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#8003]
Improve performance of Koop service by supporting more of the Geoservice API Query method. 

Where models have large numbers of geometries, sending the complete geometry set for a node will often provide a very slow experience or will timeout.

**Acceptance Criteria**
-   [ ] no breaking changes to existing behaviour
-   [ ] supports bounding box filter in any projection
-   [ ] support simplification
-   [ ] support objectid query
-   [ ] fetch extent information
-   [ ] Unit Tests passed
-   [ ] Documentation

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @aj_he
*   Designed by: @aj_he

**Comment by chiatt** [comment]
Hey @aj-he, is this something you are currently working on or just proposing?

**Comment by robgaston** [comment]
@chiatt I was given a demo earlier this week of work that @aj-he has done towards this end.  Not sure if that will be a long term solution, but it did certainly improve performance

**Comment by aj-he** [comment]
@chiatt as @robgaston says, I am working on it at the moment.

**Comment by aj-he** [comment]
This work has taken a change in direction and will no longer be making a change to the GeoJSON API at this time.  Closing
