### ISSUE TITLE
Create a Setting to Completely Disable Search Exports for Anonymous Users

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#8010]
**User Story**

Create a setting that allows an application administrator to completely disable search exports for anonymous users.

**Acceptance Criteria**
-   [ ] There is a setting in settings.py that disables anonymous exports.
-   [ ] The setting by default allows exports for anonymous users.
-   [ ] When accessing search page as an anonymous user, the export button and panel **should not** be visible/accessible if the setting is set to True
-   [ ] When logged in with a named user or the setting is set to False, the export button and panel **should** be visible/accessible.
-   [ ] The export API endpoints do not allow exports to occur if unauthenticated
-   [ ] Unit Tests passed
-   [ ] Documentation

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @ Historic England (as part of the Keystone project)
*   Designed by: @ @csmith-he

**Comment by chiatt** [comment]
It probably would be better to make this a list of groups, rather than just the guest user.
