### ISSUE TITLE
Workflows - certain buttons not fully visible on smaller screens

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8016]
**Issue Description:** (Priority 1 Bug) - When creating a new resource through the Consultation workflow, e.g., a Person, on a smaller screen (laptop) some of the buttons at the end of the steps are not fully visible.

Steps to reproduce:
1) Open a new Consultation workflow  
2) Fill out all the steps until you reach the Reference Numbers step
3) Type ‘Create’ into the Agency drop down and select to create a new Person record:

![image](https://user-images.githubusercontent.com/78143228/127494392-643f55d3-904d-4cfd-82a8-5bb2fc3a9c07.png)

4) In the Names tab, the Add and Delete buttons are not fully visible – they are still clickable, but the button text is cut off:

![image](https://user-images.githubusercontent.com/78143228/127494425-c114c5c7-276b-4fc4-a888-cf8dab13f9da.png)

Additionally, in the External Cross References section of create new Digital Object, when you add a URL for link, this pushes the Add and Delete buttons out of view of the user, and there is no scroll bar to scroll down to the buttons:

![image](https://user-images.githubusercontent.com/78143228/129011979-50f3a0e9-d43c-4f4c-bac2-955ad42e4d52.png)

**Comment by chiatt** [comment]
Resolved in 6.0
