### ISSUE TITLE
Unable to edit Saved Searches

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8018]
Issue Description: (Priority 1 Bug) Saved Searches – Once you have created a saved search you cannot edit them as you cannot access the far right of the card where the Edit button is usually located. There needs a be a horizontal scroll bar so we can access the button, or it could be moved elsewhere so it is in view. The screenshot shows where you cannot view the end of the search URL:

![image](https://user-images.githubusercontent.com/78143228/127499774-7f8b6ffb-4272-41ab-850d-0118e15f9041.png)

**Comment by chiatt** [comment]
Resolved in #8024
