### ISSUE TITLE
Enhance Arches security with two-factor authentication

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#8022]
To improve the user security of Arches implementations, two-factor authentication should be optionally implemented as part of user authentication.  To support this we will need to identify the best way to integrate two-factor authentication into Django, and then provide a way for users to optionally implement this at the project-level.

> Version 2 of the RDM will be able to support subscription services for thesauri objects such as concepts and collections.  To further improve user permissions and enhance Arches’ security... will implement two-factor authentication

**Comment by chrabyrd** [comment]
resolved in #8079
