### ISSUE TITLE
As a report designer I need to be able to configure the specific details of a Map Template Header report 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#803]
Items needing configuration:
- [ ] Basemaps available
- [ ] Other layers to show (make available)
- [ ] Whether to provide map tools or not
- [ ] other config items??

**Additional sections as determined by the template**
![screen shot 2016-09-14 at 11 06 58 am](https://cloud.githubusercontent.com/assets/823773/18524050/b2664826-7a6b-11e6-89a2-d1f4d43e6b73.png)

**Comment by chiatt** [comment]
I moved the configuration for displaying map tools in a report report header into ticket #1209

**Comment by apeters** [comment]
The configurations look good.  The map doesn't seem to zoom to the geometries in the instance and I've made a ticket for this ( #1215 ).
