### ISSUE TITLE
Database functions for creating spatial views

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#8042]
To aid the quick creation of spatial views for use with pg_featureserv, create a set of functions that will create the necessary view objects and functions to provide datatype display values.

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @aj-he
*   Designed by: @aj-he

**Comment by chiatt** [comment]
@aj-he, @robgaston I wonder if the functions proposed here might be very similar to those used to support the relational data model. Specifically ```__arches_get_labels_for_concept_node``` comes to mind.

**Comment by chiatt** [comment]
@aj-he Is this something that you are actively working on, or just a proposal?

**Comment by aj-he** [comment]
@chiatt @robgaston This is something that I have been working on to supply feature services to ArcGIS Pro using featureserv instead of koop.

I have tried to keep an eye on the relational work but there may be overlap. I am definitely using the sluggify function. Once I am happy that there is something working I'll raise a PR so we can look at where the overlaps are.

One thing I have not been doing is taking account of internationalisation/languages for concepts/domain etc. datatypes.
