### ISSUE TITLE
default values in i8ln string type cause validation to fail

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8052]
**Describe the bug**
Default values in a string card do not work - because they are plain strings and not objects, they do not validate and tiles fail to save.

**To Reproduce**
1. In the graph editor, Set default to any non-empty value in a string card.
2. Attempt to create a resource with the default value.  It will fail to validate and the tile will not save.

**Expected behavior**
We should transparently allow for users to input default values in multiple languages, and save those values as objects - not strings.

**Your Arches Information**

*   Version used: 7.x
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**
This is a 7.x i8ln bug.  

**Ticket Background**
*   Found by: @aarongundel

**Comment by aarongundel** [comment]
related to #7980

**Comment by aarongundel** [comment]
After discussion with @apeters we decided to remove the default value from the widget manager and move it to the textbox itself to take advantage of the language switcher functionality.  Additionally, we removed the defaultValue from i18n_properties so it would behave more like the business data it represents.  This seems to have corrected the issue.

**Comment by apeters** [comment]
fixed by #8069
