### ISSUE TITLE
rich text widget doesn't respect changes to "disabled" attribute

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8077]
**Describe the bug**

The rich text widget doesn't respect changes to the disabled attribute.  It cannot be changed after the fact.  

**Screenshots**

**Expected behavior**
If the value of the widget's "disabled" observable changes, then the rich text editor (ckeditor) should respond accordingly

**Your Arches Information**

*   Version used: 6.1
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
I'm going to leave this open until it is cherry-picked into the 6.0.x branch with the intent of getting it into 6.0.2.
