### ISSUE TITLE
Null Nested semantic nodes show up in label based graph v2

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8089]
**Describe the bug**

"null" (that is, only containing a @nodeid and @tileid) nested semantic nodes show up in label based graph v2.  If the parent has no tile, this should not happen.  

**To Reproduce**
1. Use AFS
2. Spin up a new physical thing
3. Add a new production event
4. Check out the uncompacted label based graph v2 output
5. Note the null object Production_Statement_name shows up underneath the null object production_statement

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used: 6.0.x
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chrabyrd** [comment]
fixed in #8106
