### ISSUE TITLE
Add a build step (compiler/compressor) for front-end assets

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#8090]
> Add a user interface build step (compiler/compressor) to enhance the load and interaction speeds of Arches Designer and Editor.  This will have the added benefit of speeding up all Arches pages

We should investigate the various options available here (webpack, parcel, etc) and how they could integrate with our Django static files pipeline.  Preferably, the solution would support AMD (`define`/`require`) as well as others (CommonJS, ES Modules, etc) so that our existing JS files would be supported, but we could start to move away from AMD.  Note that we are currently using `django_compressor` to support SASS, which has potential to be a part of this solution.  The solution should strive to account for all client side assets (JS, CSS, images, etc).

**Comment by chrabyrd** [comment]
resolved in #8090 🎉
