### ISSUE TITLE
Remove opacity from loading-mask

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8096]
**Describe the bug**

Loading-mask opacity causes excessive repaints and bogs down performance.  Removing it improves load times/experience.
There may be other places where opacity is causing excessive repaints that we can identify/remove.  

This ticket is related to #8091 

**Your Arches Information**

*   Version used: 6.0.x
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
Implemented in #8100
