### ISSUE TITLE
Generate coverage xml for vscode gutters

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8122]
Generate coverage.xml in order to view test coverage in vscode with the coverage gutters plugin

**User Story**

After a test run, a new coverage.xml file should be generated each time - this will allow us to see visually which places are covered by unit tests

**Acceptance Criteria**
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**
Done when running tests generates coverage xml

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @ 
*   Designed by: @

**Comment by chiatt** [comment]
Solved in #8123
