### ISSUE TITLE
If no quitUrl is provided to a Workflow, it attempts to redirect to init-workflow plugin

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#8125]
**Describe the bug**
See https://github.com/archesproject/arches/blob/master/arches/app/media/js/viewmodels/workflow.js#L31. This will cause an error in every case because `init-workflow` is not in core Arches. A default of `arches.urls.home` or "/search" would be better (seems like there is no `arches.urls` reference for "/search"?).

**Your Arches Information**

*   Version used: latest

**Ticket Background**
*   Found by: @mradamcox

**Comment by chiatt** [comment]
Resolved in #8131
