### ISSUE TITLE
Consolidate i18n language settings

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8130]
**Describe the bug**

There are currently multiple i18n language settings - d_languages, settings.py, and languages - we should consolidate these down to a maximum of two (ui vs business data) tables.  Potentially one if that makes sense.

1) Consider who would have permissions/access to this table.
2) Consider current processes that need access (read vs write) to this/these table(s).  
3) Consider migration paths for existing language settings.

**Comment by apeters** [comment]
fixed by #8153
