### ISSUE TITLE
Provide a way for functions to know if a resource copy operation is happening to help logic

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#8171]
**User Story**

Some function logic may need to behave differently when tile saves occur as part of a resource copy operation. There needs to be a way for functions to know if a resource copy operation is in progress.

A simple suggestion is to use a `is_copy_operation` kwarg that is part of the `resource.save` call (defaulting False). This can be passed through to the `tile.save` and followup save methods that call the functions. 

**Acceptance Criteria**
-   [ ] The function has method of checking for a copy operation
-   [ ] The default state is that it is not a copy operation so as to not affect existing functionality.
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**

**Ticket Background**
*   Sponsored by: 
*   Suggested by: @aj-he 
*   Designed by: @aj-he

**Comment by chiatt** [comment]
re #6862

**Comment by chiatt** [comment]
Resolved in #8339
