### ISSUE TITLE
[webpack]  form.js require inside init doesn't respect absolute paths

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8195]
### To Reproduce

1. set up webpack ( see: https://github.com/archesproject/arches/pull/8190 )
2. navigate to `js/views/form.js`
3. uncomment lines 26-29 -- the `require` block in `initialize`
4. save the file
5. notice that webpack fails to build and provides an error

### Contextual Knowledge

- changing the path from `/models/` to `../models/` fixes the build by changing the path from absolute to relative. This may be a viable workaround but we should investigate why absolute paths are not respected here.
- absolute paths are defined in `frontend/webpack/webpack.common.js`, via adding `javascriptRelativeFilepathToAbsoluteFilepathLookup` as a resolve alias
- The error message is interesting, because when webpack can't resolve the filepath it treats the import as a module, and looks for direction from `arches/package.json`: 
```
Module not found: Error: Can't resolve 'models' in '/Users/cbyrd/Projects/arches/arches/app/media/js/views'
resolve 'models' in '/Users/cbyrd/Projects/arches/arches/app/media/js/views'
  Parsed request is a module
  using description file: /Users/cbyrd/Projects/arches/package.json (relative path: ./arches/app/media/js/views)
```
  This should be an interesting thread to pull. If we can leverage `package.json` to direct import paths on build, we may be able to simplify the webpack build and potentially resolve other webpack issues

**Comment by aarongundel** [comment]
This appears to be caused by where the library is referenced from in pre-webpack from vs how the javascript is packed and referenced.  The issue appears to be moot though; since form.js (and the place where it is referenced, config-manager.js) are no longer needed.  I've removed them in the linked PR.

**Comment by chrabyrd** [comment]
resolved
