### ISSUE TITLE
GeoJSON export is empty if first resource has no geometry

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#8201]
**Describe the bug**

When exporting the GeoJSON for a resource model's resources, if the first resource has no geometry then geometry fields for the export are not identified and an empty Feature Collection is returned.

![image](https://user-images.githubusercontent.com/38533555/156338414-2ae43a26-1f67-457a-a42c-4edeeb155775.png)

**To Reproduce**
1. Go to the Search page
2. Filter results by a resource model (and any other filters e.g. map extent).  Make sure the selection has resources with and without geometries
3. Click the Export Search Results icon
4. Select 'geojson url' as the export option
5. Copy the URL to clipboard
6. Open another browser tab
7. Copy the URL into the tab.
8. See the Error

**Screenshots**
![image](https://user-images.githubusercontent.com/38533555/156337555-36905b06-3171-4b41-b701-9bd6ac34507f.png)

![image](https://user-images.githubusercontent.com/38533555/156337489-fe2155b5-6261-4b8c-a15c-723e1eacb68e.png)

**Expected behavior**

If any of the resources have geometry then a geometry field name is identified and results are returned in the GeoJSON URL export.

**Your Arches Information**

*   Version used: 6.1.x
*   Operating System and version (desktop or mobile): Desktop Windows 10 Enterprise 10.0.19042 Build 19042
*   Browser Name and version: Chrome 98.0.4758.102
*   Link to your Arches Install (optional): N/A

**Additional context**

We are fixing this in our dev branch forked from arches 6.1.x - we'll hand back a fix once we have tested this in Keystone

**Ticket Background**
*   Found by: @csmith-he

**Comment by chiatt** [comment]
This may be worth cherry picking into 6.0.x once the PR's merged into 6.1.

**Comment by chiatt** [comment]
Fixed in #8262
