### ISSUE TITLE
Map marker pop-ups not loading

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8211]
**Describe the bug**
The search page map marker record pop-ups are not loading when clicked on.

**To Reproduce**
1. Go to search page
2. Click on a map marker to open the pop-up preview for that record
4. The pop-up is not loading, error in console

**Screenshots**

![coreMapPopup](https://user-images.githubusercontent.com/78143228/156781158-a8ab3a6e-4ab9-4460-b031-83b7164f36fe.gif)

![image](https://user-images.githubusercontent.com/78143228/156780168-483030a2-470e-428a-8d25-ce039c37acdf.png)

**Expected behavior**
When a map marker is clicked on, a pop up opens displaying preview information of that record.

**Your Arches Information**

*   Version used: dev/6.1.x branch
*   Operating System and version (desktop or mobile): Windows 10 desktop
*   Browser Name and version: Chrome 99.0.4844.51
*   Link to your Arches Install (optional):

**Ticket Background**
*   Found by: @rlwilliamss

**Comment by aj-he** [comment]
@aarongundel it looks like this was introduced in [PR 8104](https://github.com/archesproject/arches/pull/8104) ln:436 `viewmodels/map.js` where `features` became `feature`

**Comment by aarongundel** [comment]
This should be fixed now, @aj-he
