### ISSUE TITLE
Graph Manager: The top node of a new Resource should be automatically given the name of the Resource itself

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#824]
This is a proposal, but it makes sense to me.  Currently the top node is automatically named Top Node.  This seems like a fine stand in, but if the Resource has been given a name, it seems like the user is generally going to want that name to be used for the top node.

**Comment by apeters** [comment]
I know what you mean @mradamcox but for now I think we're going to keep it this way because to implement that "simple" change isn't in fact that simple.
