### ISSUE TITLE
RTL - fix tree viewer rendering

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#8243]
![Screen Shot 2022-03-11 at 4.31.18 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/3d85a304-4a92-4ce4-b9d1-c82d8e97d0ef)

**Comment by dwuthrich** [comment]
consider removing vertical lines in tree and using just indents and shading of alternate rows for the tree as in following image

![image](https://user-images.githubusercontent.com/815185/158009816-7a7c6535-1fe1-4976-8219-8f9e6168f1e9.png)

**Comment by apeters** [comment]
fixed by #8343
