### ISSUE TITLE
Provide ability to override default primary descriptors function

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#8247]
**User Story**
Developers can implement custom functions for Primary Display descriptors to allow for application-specific logic to generate the primary descriptors. Function definition would follow the existing pattern in Arches, and functions providing that service would need to extend a base primary_descriptors class.

**Acceptance Criteria**
-   [x] Base class created
-   [x] Existing primary_descriptors class updated
-   [x] Sample implementation of an alternate function
-   [x] Unit Tests passed
-   [ ] Documentation

**Definition of Done**
- Default `primarydescriptors` configuration is compatible with existing implementation or data migration provided
- Custom `primarydescriptors` functions can be implemented and configured within the current Functions pattern
- Different `primarydescriptors` functions can be assigned to different graphs
- Remove `primarydescriptors` implementation-specific logic from function consumers

**Ticket Background**
*   Sponsored by: BC Government
*   Suggested by: @bferguso
*   Designed by: @bferguso
*   Initial discussion: https://community.archesproject.org/t/custom-primary-display-name-functions/1552

**Comment by aj-he** [comment]
@bferguso @chiatt Can an example of creating a custom primary descriptor function be added to arches-docs under the Types of Extension section?

https://arches.readthedocs.io/en/latest/creating-extensions/#types-of-extensions

**Comment by chiatt** [comment]
Resolved in #8256
