### ISSUE TITLE
Manage Menu: Sort dropdown items by Resource and Graph

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#827]
It would be easier to use this dropdown if its contents were sorted in the same manner as the Find dropdown on the Resource Designer front page.

**Comment by mradamcox** [comment]
For clarification, this is the menu

![image](https://cloud.githubusercontent.com/assets/10427268/20985673/128afbdc-bc8b-11e6-88cc-cf047cac3d5a.png)

that I'm proposing to be made to look like this menu

![image](https://cloud.githubusercontent.com/assets/10427268/20985755/67f1b3e0-bc8b-11e6-84e7-9042deac90d3.png)

**Comment by mradamcox** [comment]
The reasoning is that the name of a resource model or branch may not give any indication of what category the item falls into.

**Comment by jmunowitch** [comment]
In the new Graph Designer in 4.3, this is implemented:
Duplicate of #3553
