### ISSUE TITLE
Graph Manager: Set Focus on New Child Node

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#828]
#### Expected Behavior

After adding a child node to a graph, I would like the focus to be on the newly created child node so I can edit its attributes appropriately (particularly the property that connects it to the parent node). 
#### Current Behavior

 As it stands, the focus remains on the parent node from which the adding of a child node was initiated.

**Comment by apeters** [comment]
For a branch it does just what you'd expect, it's for a resource model that we keep the focus on the root node because you can only attach branches to the root.  Should that not be the case?

**Comment by apeters** [comment]
I think we can close this for the reasons above
