### ISSUE TITLE
Site Visit workflow - styling issues when working with photos

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/arches#8283]
Site Visit workflow - In the Site Visit workflow, when you edit images in the Site Photos Upload step, the photograph and delete button divs are fixed and cover the panel content when scrolling. The delete button div does not cover content but it is placed overlapping the horizontal scroll bar.
Steps to reproduce

1) Open a new Site Visit workflow and fill out data for the first step - Site Visit Details

2) The next 3 steps do not need data entered to be able to move on - use the Next Step but-ton 

3) On the Site Photos Upload step - upload a photo and then click on the edit button

4) Scroll up and down the page:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/59013689/152211008-84fb278e-0afa-4f33-bc95-98ca03289a16.png">

**Comment by chiatt** [comment]
Fixed in #8306
