### ISSUE TITLE
Timewheel inefficiently handles range processing causing timeouts

### ISSUE THREAD

**Issue by khodgkinson-he** [archesproject/arches#8287]
**Describe the bug**
As currently configured, the timewheel iterates through entire date ranges available in data, despite some being outside returned ranges selected in settings, which should be ignored. As not required for display, this is inefficient.

modified timewheel config with ranges, used against 2.5 million year data timespan

```py
TIMEWHEEL_DATE_TIERS = {
    "name": "Millennium",
    "interval": 1000,
    "range": {"min": -2000, "max": 3000},
    "root": True,
    "child": {
        "name": "Century",
        "interval": 100,
        "range": {"min": 1500, "max": 2000},
        "child": {"name": "Decade", "interval": 10, "range": {"min": 1750, "max": 2100}},
    },
}
```
with settings above, current code still iterates through ranges which takes too long.

**To Reproduce**
1. have data spanning 2.5 million years, set date range child to centary.
2. Open timewheel

**Screenshots**

**Expected behavior**
Timewheel to cover selected range

![image](https://user-images.githubusercontent.com/53860784/159255619-14b7960c-c687-4e5b-bb5e-1db69339823f.png)

**Your Arches Information**

*   Version used: DEV 6.1
*   Operating System and version (desktop or mobile): Windows 10
*   Browser Name and version: Chrome
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @khodgkinson-he

**Comment by chiatt** [comment]
Resolved in #8304
