### ISSUE TITLE
Primary descriptors should be persisted to the resource instances table

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#8301]
When working in PostgreSQL, there are many occasions when being able to access the primary descriptor values for a resource instance would be useful.  Currently, these values are only stored in elasticsearch and are therefore difficult to access from other parts of the application.  We should add columns to the resource instances table for these values and populate them when we generate and index them.

**Comment by aarongundel** [comment]
This implies a modification to the relational data model to expose this in the instances views.
