### ISSUE TITLE
Resource instance widget includes the model icon to help identify what is being selected

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#8303]
To help users identify what they are selecting in the resource instance widget, include the icon in front of the resource instance display name.  This is especially useful if resources have similar name but belong to different models.

![image](https://user-images.githubusercontent.com/25295526/160096008-6f00d585-1f9c-40ca-89ab-30a6cd8391c9.png)

![image](https://user-images.githubusercontent.com/25295526/160096124-c76e47d2-5991-493c-9e91-2853eabd6c5c.png)

![image](https://user-images.githubusercontent.com/25295526/160105060-1f1d3e69-0aee-4fcb-8d83-024eaf119efc.png)

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @aj-he
*   Designed by: @aj-he

**Comment by chiatt** [comment]
Resolved in #8305
