### ISSUE TITLE
Consultation workflow - no option to edit coordinates

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8345]
**Describe the issue** - In the Consultations workflow, there is no option to edit coordinates as there is no 'Edit Coordinates' button on the Geometry - Geospatial Coordinates window.

**Steps to reproduce**

1) Open a new Consultation workflow

2) In the first step of the workflow, use the map tools to add a geometry to any location in London

3) There should be an option to edit the coordinates, next to Edit GeoJSON:

Expected result - Should be able to edit the coodinates of a spatial feature

![image](https://user-images.githubusercontent.com/78143228/161799679-2e2da396-2b06-4445-b262-6a0944c3d471.png)

The Edit Coordinates option in Application Area workflow:

![image](https://user-images.githubusercontent.com/78143228/161799980-0b8a7b65-edff-4830-ac21-757c83892756.png)

**Comment by chiatt** [comment]
Fixed in #8346
