### ISSUE TITLE
Popup displayed when map in drawing mode (search or edit)

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#8364]
**Describe the bug**
Map popup is displayed when drawing features (either filter geometries or resource geometries) when a point lays on an existing geometry.

**To Reproduce**
1. On the map search page zoom in to a resource with a geometry displayed on the map
2. Click on the "Filter" tab on the right
3. Select "Draw a polygon" in the "Select a filter" pick list (any drawing mode will do)
5. Click inside the displayed geometry
6. Note that the popup displays even though in a drawing mode

**Screenshots**
<img width="1920" alt="popup_while_drawing" src="https://user-images.githubusercontent.com/6750642/164748249-3b8057aa-ad2c-42a3-856a-c563066f0994.png">

**Expected behavior**
Map popups not be displayed when in a drawing mode (either in search or when editing/creating a resource geometry)

**Your Arches Information**

*   Version used: master branch
*   Operating System and version (desktop or mobile): OSX
*   Browser Name and version: Firefox Developer 100.0b7
*   Link to your Arches Install (optional):

**Additional context**
I'll be submitting a PR with a proposed fix shortly

**Ticket Background**
*   Found by: @bferguso

**Comment by chiatt** [comment]
Resolved in #8365
