### ISSUE TITLE
Image Service Manager: single/dual pane controls do not stay in synch

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#8367]
There are UI inconsistencies when a user switches from single to dual pane, and from dual back to single pane mode.  See the attached video  to view the issues.  The issues are:

1.  When selecting the dual ane mode, there is no visual cue that anything has happened.  When the dual pane is selected, we should immediately show the slider so that the user can confirm that dual mode is now active.  The default image for the second pane should be the canvas in the first frame.

2. When moving back to single pane mode, the radio button does not update.  It still shows that the 2 pane mode is active

3. The dropdown showing the selected image shows the wrong canvas, and the gallery at the foot of the page does not highlight the correct canvas

https://images.zenhubusercontent.com/49451058/ba76972e-e70f-4d7a-a5a0-5280bbd64ddb/iiif_two_pane.mp4

**Comment by chiatt** [comment]
Resolved in #8394
