### ISSUE TITLE
Image Service Manager: selecting image in panel dropdown incorrectly updates both panels

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#8368]
As shown in the attached video, when a user updates a panel in the 2 panel layout, both panels are updated instead of just the selected panel.

https://images.zenhubusercontent.com/49451058/6b4493ee-85b1-4fe2-a0ef-bec401a172f1/improper_update.mp4

**Comment by chiatt** [comment]
Resolved in #8394
