### ISSUE TITLE
IIIF Card: Selecting number of panels should be disabled until an image service is selected

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#8369]
As shown in the attached video, users can select 1- and 2-panel layout before any service has been selected.  This is a poor UX, and selecting the 2-panel layout should not be possible until a service has been selected.

https://images.zenhubusercontent.com/49451058/c7be646e-b04f-4d97-a89a-2ede3ae7d5b5/two_panel_control.mp4

**Comment by chiatt** [comment]
Resolved in #8394
