### ISSUE TITLE
Graph Manager: Can't delete node

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#837]
#### Expected Behavior
I should be able to delete a node after I add it.

#### Current Behavior
starting with a brand new Branch graph, I add a single node to the top node and then try to delete it. The spinner goes forever, and console says

Uncaught TypeError: Cannot read property 'domainnode_id' of undefined

**Comment by robgaston** [comment]
@mradamcox Looks like this issue is resolved now:

![dinghzc29p](https://cloud.githubusercontent.com/assets/1187406/19246114/961a057c-8ed9-11e6-907c-672a1a34df66.gif)

Let me know if I'm missing something here. Thanks.

**Comment by mradamcox** [comment]
yeah, it works now.
