### ISSUE TITLE
IIIF Card: Selecting 2 panel layout does not bring up slider or image selection tools

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#8370]
As shown in the attached video, when a user selects 2-pane mode in the IIIF card, the UI does not update or show any indication that image comparisons are available.

What should happen: when selecting 2-pane mode, the slider should automatically appear with the image selection dropdowns in the upper corners of each panel.  The newly opened second panel should default to the same canvas as in the original single panel view.

https://images.zenhubusercontent.com/49451058/96d79238-39ed-4976-9d3a-2ea95a3a9cde/no_controls_display.mp4

**Comment by chiatt** [comment]
Resolved in #8394
