### ISSUE TITLE
IIIF Card: error when loading a new service when a card is in 2-pane mode

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#8371]
As shown in the attached video, when changing the iiif service when the IIIF card is in 2-pane mode the panes do not update properly.  The canvas from the initial (and no longer active) service persists.

https://images.zenhubusercontent.com/49451058/1c6b8e37-89d4-4132-a4e8-b4a73716ded2/service_update_error.mp4

**Comment by chiatt** [comment]
Resolved in #8394
