### ISSUE TITLE
Search bar - Concepts is hidden below Term Matches

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8375]
**Describe the bug**
On the Search Page in the Search bar - the Concepts option is now below the Term Matches option and is hidden by the list of resulting term matches.

**To Reproduce**
1) Open the Search page

2) Type something into the search bar e.g., 'Test'

3) In the result drop down, Concepts is below Term Matches - should be side by side as before

**Screenshots**
![image](https://user-images.githubusercontent.com/78143228/165504408-9b2c986e-5707-4331-bf25-9993072ded2b.png)

**Expected behavior**
should be side by side:

![image](https://user-images.githubusercontent.com/78143228/165504464-d9b0435d-d742-4798-a43d-52075614026d.png)

**Your Arches Information**
Version used: 6.1.x with the arches-her package
Operating System and version (desktop or mobile): Windows 10
Browser Name and version: Chrome 100.0.4896.88
Link to your Arches Install (optional):

**Ticket Background**
*   Found by: @rlwilliamss / Matt Jones HE

**Comment by chiatt** [comment]
@rlwilliamss I'm not able to reproduce this issue on my Windows 10 instance. Is it possible that you are getting an error in your Chrome dev tools console?

**Comment by rlwilliamss** [comment]
@chiatt Closing this as it happened as a result of accessibility changes and has now been fixed.
