### ISSUE TITLE
Bug: Cant initiate manage--->data widgets and cards from resource model

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#838]
### Bug Report
When accessing the card/widget designer from a resource model, (rather than a branch), the UI returns a picker for data entry cards, but there is no way to access the card editing UI once the card is selected.

#### Expected Behavior
After the card is selected, if should either jump to the card management UI for that card, or have a button enabled that allows me to indicate that I can go ahead and "Go" to that card's management UI.

**Comment by apeters** [comment]
fixed in the latest
