### ISSUE TITLE
Bug: Cant Initiate Delete Branch when lots of branches loaded

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#840]
### Bug Report
Cant scroll far enough down on the Branch library page to use "Manage ---> Delete" when I have enough branches in my list to fill the whole page.
![screen shot 2016-09-26 at 8 45 18 am](https://cloud.githubusercontent.com/assets/9683819/18841163/a7d630ac-83c5-11e6-9719-db9c8476b292.png)

**Comment by dwuthrich** [comment]
meets requirements
