### ISSUE TITLE
Allow POST data in search request

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#8412]
When filtering resources by external geometries the submitted GeoJSON string can cause the URL to exceed the maximum length (typically 2048 characters). POST data can be used to transfer larger amounts of data to the search URL. 

Currently the `views/search.py` only checks for parameters embedded in the URL, not for data in the POST part of the request.

**User Story**
We would like to be able to pass map search criteria that exceeds the maximum URL length to filter resources by arbitrary external geometries.

This issue only addresses the server side issue where the search.py only looks for parameters in the GET portion of the request, not in the POST data. When search criteria are passed as a POST data it breaks the ability to save the query as a bookmark so changes to the client-side javascript are left to the implementor for now.

**Acceptance Criteria**
-   [ ] Existing search functionality is unchanged
-   [ ] POST parameters passed to the search URL are included in the search criteria
-   [ ] Unit Tests passed
-   [ ] Documentation

**Definition of Done**
Both GET (URL encoded) and POST data are used to define the search criteria.

**Ticket Background**
*   Sponsored by: Self Funded
*   Suggested by: @bferguso
*   Designed by: @bferguso

**Comment by chiatt** [comment]
Resolved in #8413
