### ISSUE TITLE
Hidden resources displaying in term search and results

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8438]
**Describe the bug** - Resources that are hidden from certain user groups are displaying in the term search and search results.

**Expected result** - The term search and Resource Type drop down should only show results for a model only if there are are least 1 card with permissions... otherwise hide it from results and the Resource Type dropdown.

**To Reproduce**

1. As an admin user, go to the graph designer for the Consultation model and set permissions for anonymous users to 'No Access' across all Consultation model cards

1. Log out and go to the Search page as an anonymous user

2. Click on the Resource Type drop down and select Consultation (in this example Consultation and Application Area resources are hidden from anonymous users) - the Consultation results return. When clicked on a 403 page is returned so anonymous users cannot access the record, but they should not be able to see them in the Resource Type drop down or search results.

**Screenshots**

![anonuser](https://user-images.githubusercontent.com/78143228/168828513-81b0e683-1796-40a2-b98a-2b594477a8ab.gif)

**Your Arches Information**
*   Version used: 6.0.1
*   Operating System and version (desktop or mobile): Windows 10
*   Browser Name and version: Chrome 101.0.4951.67
*   Link to your Arches Install (optional):

**Ticket Background**
*   Found by: @StucakeGLHER

**Comment by chiatt** [comment]
re #2491

**Comment by apeters** [comment]
fixed by #8466
