### ISSUE TITLE
EDTF transform_value_for_tile change causes validation errors during csvfile load in dev/6.1.x

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#8447]
The addition of a `transform_value_for_tile` method for `EDTFDatatype` that returns a tuple in https://github.com/archesproject/arches/pull/8327 has broken data loading via CSV.

The issue is that the `value` assigned here https://github.com/archesproject/arches/blob/bf308e8229c6fa7168e40d6563b57b991e2d4ce0/arches/app/utils/data_management/resources/formats/csvfile.py#L812 receives a tuple from `EDTFDatatype.transform_value_for_tile` now which is not expected by the `validate` https://github.com/archesproject/arches/blob/bf308e8229c6fa7168e40d6563b57b991e2d4ce0/arches/app/utils/data_management/resources/formats/csvfile.py#L813

**Comment by aj-he** [comment]
@njkim I've assigned you as you worked on #8327

**Comment by chiatt** [comment]
Resolved in #8448
