### ISSUE TITLE
Rename ETL Manager 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#8473]
The ETL Manager is capable of managing data processing tasks other than ETL, e.g. transforming tile values or moving data from one node to another. For that reason the name should probably be changed to something that reflects that flexibility. 

Maybe something like?
- Data Processing Manager
- Task Manager
- Data Task Manager

Other suggestions?

**Comment by apeters** [comment]
I like `Task Manager`.  It's short and sweet and conveys what the plugin can do, which is the ability to perform tasks.
Adding "Data" seems redundant but also unnecessarily limiting.

**Comment by chiatt** [comment]
@apeters I agree. My only reservation about calling it 'Task' manager has been that the word 'task' is generally associated with Celery tasks. At this point though, it's becoming clear that Celery will be a requirement for the task manager, and it's hard to imagine any etl module not leveraging Celery to maintain its status in the load_events table (which should probably be changed to something like 'task_events' or 'task_status').

**Comment by dwuthrich** [comment]
@chiatt @apeters I don't think "Task Manager" is the appropriate new name for the ETL Manager.  There are many potential future tasks that do not necessarily imply manipulating data.  Also, a user looking for data import/export services would not immediately understand that "Task Manager" is the place to look.  Instead, something like "Import/Export Manager" or "Bulk Data Manager" is more descriptive and accurate.

**Comment by apeters** [comment]
@dwuthrich after further thinking, I think "Bulk Data Manager" would be most appropriate.  I think that this would also be where we employ scripts to update data in bulk, RE: what Getty Digital wants.  "Import/Export Manager" seems too narrow.
Maybe "Task Manager" was too broad and not descriptive enough.  Fundamentally Arches deals with "Data".  The word "Bulk" distinguishes it from a single data editor, which we already have.

**Comment by dwuthrich** [comment]
@apeters I agree that "Bulk Data Manager" is a reasonable fit, especially because it can reasonably include data update scripts

**Comment by chiatt** [comment]
Yeah - "Bulk Data Manager" seems the most suitable. However, I can imagine using this plugin to monitor beat tasks that wouldn't really be considered bulk operations. For example, a beat task could pull in a daily value  from a scientific instrument's api  (e.g. avg daily humidity in a museum) creating just a single resource or tile. I'm sure that's a less common use case though.

**Comment by apeters** [comment]
This is really an "Automated Data Manager" then.  A system that allows a user to run processes that can update 1 to many data in the system.

**Comment by chiatt** [comment]
Completed in #8857
