### ISSUE TITLE
As a data manager, I want to quickly find the names and UUIDs of Resource Models in my Arches instance

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#850]
A data manager should be able to quickly view the UUIDs and names of the Resource Models in their Arches instance. Optionally, a data manager should also be able to view the nodegroups and node names in each Resource Model including cardinality. This will assist the data manager in loading and modifying data in Arches.

Proposed Solution:
Create a service that takes in no inputs and returns the Resource Model name and UUID of all the Resource Models in an Arches instance.

Questions:
1. Would it be more helpful to return the entire Resource Graph of each Resource Model in an Arches instance? I believe this would contain the UUID for the Resource Model as well as all the Nodes and NodeIDs for the Resource Model, along with the structure of the Resource Model.

Answer
1. The service can have an optional 'details' flag that would return the entire each Resource Model for each Resource in an Arches instance.

simple service - returns the name and UUID of each Resource Model
detailed service - returns simple service return and the entire Resource Model for each resource in the Arches instance

**Comment by apeters** [comment]
This should be easy to do, but it would be nice to get more detail on the use case.
EG: spitting out a JSON listing of the resource models and their uuids plus the nodes contained within the model and their uuids would be relatively easy, but JSON can be potentially verbose.  Maybe a simple CSV would be better?

**Comment by dwuthrich** [comment]
The use case is to allow a data editor to bulk load data into Arches.  This implies knowing the resource models, the node groups (e.g.: grouping of nodes) and the cardinality of node groups. Either JSON or CSV (or both) would be fine.

**Comment by apeters** [comment]
fixed in the latest
