### ISSUE TITLE
ETL Manager: csv loader does not show statistics properly

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#8501]
When running an import job, the ETL loader shows the user the status of the job (e.g.: running, completed, failed).

however, as shown in the screen shot below, the actual job metadata is not updated upon completion of the job.  That is, even though the job status iin left hand panel is updated to "completed", the job metadata does not show the completion time or duration until the page is refreshed.

![Screen Shot 2022-06-02 at 11.21.27 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/b432feee-a19d-4639-9cc2-5bd32320004e
)

**Comment by chiatt** [comment]
Resolved in #8506
