### ISSUE TITLE
ETL manager: pressing the "undo import" link on a job results in UI spinner just hanging 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#8505]
It looks like the undo import feature is not working.

What should happen: pressing the undo import link should start another job (probably managed via celery) so that the user can continue their work and be notified when the job has been completed

**Comment by dwuthrich** [comment]
Actually, the undo task is working, similarly to how it works when deleting instances from Arches Designer.  However, this approach forces the user to keep a page that looks to be unresponsive open.  We will need to implement a better UX for users to be sure what the status of a "remove resource instances" job is

**Comment by chiatt** [comment]
I think this would be pretty straight forward if we update the status column in the load_event table that corresponds to that load. A celery task that handles this could also potentially be used for: #6242
