### ISSUE TITLE
Fix migration dependency order in 7.0.x

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#8557]
The order of shared dependencies of arches versions needs to match in order to facilitate migrations from one version to the next. This is not the case for dev/6.1.x and dev/7.0.x. The dev/7.0.x branch has two migrations that proceed some dev/6.1.x migrations:
```
7783_make_settings_active
7783_add_graph_publications
```
These migrations should follow the `8528_bulk_load_performance_functions` migration.

**Comment by chrabyrd** [comment]
resolved in #8585
