### ISSUE TITLE
Loading resource instances with 1000's of related resources is really slow

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#8578]
The attached json-ld file has 1000's of related resources and takes over 5 min to load.
[https://app.zenhub.com/files/49451058/8f0f5234-bea0-4490-a6ca-25b5a5bbb6d6/download](https://app.zenhub.com/files/49451058/8f0f5234-bea0-4490-a6ca-25b5a5bbb6d6/download
)

**Comment by chiatt** [comment]
Resolved in #8619
