### ISSUE TITLE
[RTL] User Profile page styling broken

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8608]
**Describe the bug**

The user profile styling is broken in RTL - it's also lacking some padding in LTR and could use some cleanup.  Some strings are not translated properly - ENABLED/DISABLED for two factor authentication.

**To Reproduce**
1. Go to the user's profile page
2. Note styling

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by aarongundel** [comment]
@chiatt seems like one that should be fixed prior to 7.x release

**Comment by apeters** [comment]
closed by #8876
