### ISSUE TITLE
Resource Manager: Resource doesn't respect the cardinality of the branch card on append

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#862]
### Bug Report

Steps to reproduce behavior:
1. Set the cardinality of a card associated with a branch to n.
2. Jump to a resource and append the branch.
3. Open the card from the resource, observe that cardinality of the card is no longer n.

**Comment by robgaston** [comment]
this was fixed in #1095

**Comment by robgaston** [comment]
This should be fixed in #1097
