### ISSUE TITLE
Resolve ESLint webpack errors

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8675]
1. check out #8190 
2. python manage.py setup_db
3. 

( in core ) pip uninstall arches ???? -- may not need
( in core ) pip install -e .

5. start the application server in arches ( not a project )
6. in a separate terminal window, run `yarn start`
7. after ~1 minute, the application should build and the process should end with the following message: 
`
✖ 407 problems (257 errors, 150 warnings)
  112 errors and 0 warnings potentially fixable with the --fix option.
`

8. solve the errors, and disregard the warnings for now. 
9. to leverage the `--fix` option, navigate to `webpack.config.dev.js` in `arches/webpack` directory
10. Update the ESLint plugin to read as:

```
        new ESLintPlugin({
            extensions: [`js`, `jsx`],
            fix: true,
        }),
```
11. restart your yarn dev server, some of the errors should be automatically fixed.
12. Be sure to revert the `fix:true` setting before pushing out the PR

**Comment by njkim** [comment]
Resolved in #8677
