### ISSUE TITLE
Resource instance widget improperly updated after new resource instance is created

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#8682]
When a new resource instance is created using the resource instance widget, an entry for the newly created instance should appear below the widget input. Instead, only the word 'null' appears in the input.

In 7.0.x  (incorrect):
![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/8735b0ca-e758-40a0-a24d-8c84149450bf)

In 6.2.x (correct): 
![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/9caa7c88-2a1f-423e-89bb-181fb0a3355f)

**Comment by chrabyrd** [comment]
solved in #8703
