### ISSUE TITLE
In v7 'null' Appears as subtitle in cards that do not have a subtitle

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#8688]
The string 'null' is automatically saved as the subtitle of a card. This displays under the card title in the resource editor.

![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/44627868-1403-4fcd-9c7e-52e0a38ffc5d)

**Comment by chrabyrd** [comment]
resolved in #8711
