### ISSUE TITLE
Improve error messaging around the excess tiles trigger

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8689]
The excess tiles trigger function throws when there's a cardinality violation, preventing an insert.  We should provide a more detailed error message to our users in order to allow them to debug the issue more easily.  Currently the exception just says "'Multiple Tiles for Cardinality-1 Nodegroup" - which doesn't give the user an idea about where to look for the issue.

**Comment by chiatt** [comment]
Resolved in #8690
