### ISSUE TITLE
As a data manager, I want to be able to reconcile the concept labels in my arches input files (csv, .arches, etc) with the concept labels that current exist in my arches instance

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#871]
As a data manger I want to be able to reconcile the concept labels in my arches input file (whatever format that may take) with the concept labels that exist in my arches instance.

Proposed Solution:
Create a service that takes in a conceptid as input and returns a list of child concept labels and conceptids and a contextual report about the concept that was passed into the service.

Questions:
1. If we have a context report as part of the return, what format should that? JSON dump? Link to RDM? ??

**Comment by apeters** [comment]
@ryan86  isn't this fixed in the latest?

**Comment by ryan86** [comment]
@apeters yes

**Comment by apeters** [comment]
fixed in the latest
