### ISSUE TITLE
Changing UI Language ARCHES

### ISSUE THREAD

**Issue by himuura** [archesproject/arches#8710]
Hi there! I've manage to install and configure ARCHES without much fuss on the topic, to help a friend of mine with his project. My main issue is, after changing the LANGUAGE to pt-PT, only the search menu appears in PT, all the rest is still in English.

LANGUAGE_CODE = "pt-PT"
LANGUAGES = [
   ('de', _('German')),
   ('en', _('English')),
   ('en-gb', _('British English')),
   ('es', _('Spanish')),
   ('pt-PT', _('Portuguese')),
]

I read the documentation but despite all the tremendous work you guys did, **to me** it's a little fuzzy on how to change the default UI language.
I also tried on the project root and get the some stuff onto the locales folder of the project:

django-admin makemessages -l pt-PT (got and error on a package/test/index.html regarding a char not being UTF-8)

UnicodeDecodeError: skipped file License.txt in ./media/packages/arches/arches/app/media/plugins/line-icons (reason: 'utf-8' codec can't decode byte 0x93 in position 802: invalid start byte)
UnicodeDecodeError: skipped file index.html in ./media/packages/jquery-migrate/test (reason: 'utf-8' codec can't decode byte 0xb4 in position 5501: invalid start byte)
processing locale pt

Can anyone share some light on the steps to change the default UI language? Thanks in advance!

**Comment by himuura** [comment]
EDIT:
Also tried these
django-admin makemessages --ignore=env/* --local=pt --local=pt_PT  --extension=htm,py

django-admin compilemessages

Only the "Search" context is in Portuguese, all the rest is in English.

**Comment by dwuthrich** [comment]
@himuura Which version of Arches are you using?

**Comment by himuura** [comment]
> @himuura Which version of Arches are you using?

Latest mate, 6.1.0.

**Comment by dwuthrich** [comment]
Arches v7, to be released end of August, has full support for internationalization.  You may want to look at it before working on getting 6.1 to work with Portuguese strings/data.

**Comment by himuura** [comment]
> Arches v7, to be released end of August, has full support for internationalization. You may want to look at it before working on getting 6.1 to work with Portuguese strings/data.

A great thank you mate! Is the beta available?

**Comment by dwuthrich** [comment]
Check out the 7.0.x branch of the Arches repo.  It's the main development branch for all v7 work

**Comment by chiatt** [comment]
Hi @himuura,

If you need help with anything it is better to submit your question on the Arches forum rather than here on github. The forum has a much larger audience able to help you. You can find it here: https://community.archesproject.org/
