### ISSUE TITLE
Adding new languages causes existing graph publications to break on add

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8742]
**Describe the bug**

After adding a new language in Arches, the editor no longer works  (in the language that is added) for graphs that have already been published.  The error is 

```
DoesNotExist at /add-resource/
PublishedGraph matching query does not exist.
```

**Comment by aarongundel** [comment]
More context for this ticket:  The issue happens whenever a new language is added and the graphs are already published.  We either need to make sure that all languages have a publication record or fall back on the default language publication record.  The short-term workaround is to republish the graph after the language is added.

**Comment by aarongundel** [comment]
Note:  Better exception handling (or even better - no exception) would be ideal here.  The user doesn't need to know there's an issue or should know immediately how to fix it.

**Comment by chiatt** [comment]
A command would also be helpful to sync up publications.
