### ISSUE TITLE
Unable to save any graph changes if resource instances exist in v7

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#8748]
Prior to v7 a user could make any change to a graph so long as that change did not impact the graphs relationship to business data. For example a user could switch report templates, card components, change a report template, etc. A user could not, delete a node, add a new node to a card, change a node's datatype, or any other change that would prevent a tile from being read properly by the system

In v7 a user cannot make any changes at all. The graph simply cannot be saved if there is any business data. This is a big limitation for anyone trying to maintain an existing system.

**Comment by chrabyrd** [comment]
resolved in #9246
