### ISSUE TITLE
Arches Designer `Card` tab does not render report template preview on change

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8749]
**Describe the bug**

The center pane should render a preview of the selected report template without the user needing to navigate to a different node && back

**To Reproduce**
1. navigate to arches designer
2. navigate to the card tab for any resource model
3. click to topmost node to change the report configuration
4. select a new report configuration from the dropdown
5. notice the center pane doesn't update until you navigate to a different node && back

**Screenshots**

<img width="1422" alt="Screen Shot 2022-08-03 at 10 21 24 AM" src="https://user-images.githubusercontent.com/9162695/182670389-46842acd-c542-4714-bb57-737015a2a1be.png">

**Comment by chiatt** [comment]
@johnatawnclementawn and I noticed that this appears resolved in the latest.
