### ISSUE TITLE
Form Manager: New form dropdown does not update on form save

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#875]
### Bug Report

The form dropdown that appears in next to "Data Entry Forms" should update the name of the current form when the user saves a new form for the first time.

If a user edits an existing form name, then the dropdown should update as well.

**Comment by dwuthrich** [comment]
Functions as expected when user adds a new form.  Does not update dropdown when user edits the form name for an existing form

**Comment by robgaston** [comment]
@dwuthrich I changed this slightly so that it should now work in all cases, but it only updates the name in the dropdown after the user saves the edits (as opposed to as the user types, which became difficult to manage when using the chosen component).  Hopefully that is sufficient.

**Comment by dwuthrich** [comment]
meets requirements
