### ISSUE TITLE
Password change flow gives insufficient information and feedback

### ISSUE THREAD

**Issue by jvasile** [archesproject/arches#8753]
When a user tries to change their password, they must meet some complexity requirements.  I can't find any feedback mechanism to tell the user if they've met the criteria.  And if they haven't, when they hit the button to change password, Arches just sits there. 

Arches also doesn't tell users what counts as a special character.  And the list for Arches is... oddly small?  Some users might be so audacious as include a question mark or an equals sign in their password.  But then it seems like Arches stopped responding because there's no feedback to tell the user which validation they failed or even that they failed it at all.

To reproduce, go to https://ARCHESINSTALL/user and click "change password".  Put in a password like "1HereIsAQuestion?" and hit the button.  Nothing will happen.  There will be nothing at all.  An endless void.  Some users will find it meditative.  Some will face this void and eventually try to fill it with their own screams.

**Expected behavior**
Some combination of these would probably clear this up:

1) Some sort of visual indication of whether an inputted or submitted password has failed validation (and which criterion it failed)
2) Include the list of special chars in the prompt for a password 
3) Expand the list of special chars accepted beyond  !@#)(*&^%$ 

**Your Arches Information**
*   Version used: 6.1.0
*   Operating System and version (desktop or mobile):   Debian OS
*   Browser Name and version: Firefox latest (also tried Chromium latest)

**Comment by chiatt** [comment]
Thanks @jvasile - an endless void is certainly not the user experience we're aiming for.

**Comment by aarongundel** [comment]
I also ran into this issue - it's happening because the ValidationError isn't imported in auth.py - but it is "caught".  Importing it solves the issue.

**Comment by aarongundel** [comment]
This fix will need to be cherry picked into 7.x also

**Comment by aarongundel** [comment]
This void of screams should be resolved now.

**Comment by aarongundel** [comment]
note: change was merged to 6.2.x dev and 7.2.x dev - this will be in the next release of arches.
