### ISSUE TITLE
switch-widget template for boolean datatype shows [object Object] in Designer

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8762]
**Describe the bug**

switch-widget template for boolean datatype shows [object Object] in Designer. Also, regardless of template, changing the default value does not update the preview in real time

**To Reproduce**
1. navigate to arches designer
2. create or find a resource model with a boolean datatype
3. navigate to the `card` tab and update the widget template to `switch-widget`
4. notice the UI breaks

**Screenshots**

<img width="1409" alt="Screen Shot 2022-08-04 at 1 04 19 PM" src="https://user-images.githubusercontent.com/9162695/182942507-acbe40d7-6c2b-4814-81ac-ff5c24fa1b0b.png">

**Comment by chiatt** [comment]
This issue is essentially resolved. There are still some refinements to make the patch release. https://github.com/archesproject/arches/issues/8794
