### ISSUE TITLE
Search results does not respect `settings.SEARCH_ITEMS_PER_PAGE`

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8776]
**Describe the bug**

The amount of search results returned as a `page` in the search view appears to not respect the `settings.SEARCH_ITEMS_PER_PAGE` setting.

Note: tested with `1` and `2` as values.

**To Reproduce**
1. go to `settings.py` and change the `SEARCH_ITEMS_PER_PAGE` value to be less than 5.
2. ( optional ) rebuild your webpack bundle and restart the django server as a sanity check
3. navigate to the search page
4. notice the number of search results returned is not what's defined in `SEARCH_ITEMS_PER_PAGE`

**Comment by chiatt** [comment]
This setting is actually overridden by what's in the system settings instance.

**Comment by chrabyrd** [comment]
> This setting is actually overridden by what's in the system settings instance.

ah -- right you are
