### ISSUE TITLE
Export search results notification item has illegible button

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8777]
**Describe the bug**

The notification item that appears when you export search results contains a button with css that renders it illegible.

**To Reproduce**
1. export a list of search results that is more than the value of `settings.SEARCH_EXPORT_IMMEDIATE_DOWNLOAD_THRESHOLD`
2. open the notification panel
3. see illegible button

**Screenshots**

<img width="1409" alt="Screen Shot 2022-08-08 at 2 03 57 PM" src="https://user-images.githubusercontent.com/9162695/183514337-0af52214-34d7-45da-8772-ecf92b69fe52.png">

**Comment by chiatt** [comment]
Resolved in #8846
