### ISSUE TITLE
The application enters an error state if a user with nodegroup restrictions navigates to the resource editor

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8779]
**Describe the bug**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'parentnodegroup_id')
    at card.js:231:1
```

**To Reproduce**
1. create a resource editor user
2. as an administrator, restrict this user's write access to a resource model's nodegroup ( or restrict all access )
3. as the user, attempt to create a new resource of said model

**Screenshots**

<img width="2007" alt="Screen Shot 2022-08-08 at 3 20 38 PM" src="https://user-images.githubusercontent.com/9162695/183524472-081d6ba5-d8b7-44fe-a695-feffa5823b5d.png">

**Comment by chiatt** [comment]
Fixed in #8790
