### ISSUE TITLE
Resource Editor: Adding a branch to a resource breaks connection to top concept for concept widgets

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#878]
### Bug Report

Configuring the concept collection for a concept node when creating a branch works as expected.  However, after appending the branch to a resource, concept nodes no longer able to show concepts values.

**Comment by apeters** [comment]
If you just append the card then the dropdown isn't populated although the top concept appears to be set.  If you go to the card itself and re-select the desired top concept then it works as expected.

**Comment by apeters** [comment]
this appears to be fixed in the latest
