### ISSUE TITLE
'_ is not defined' ReferenceError in node-form.htm

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#8798]
**Describe the bug**
A javascript dependency error occurs when navigating to a resource manager node that isn't a semantic node. The graph node edit section of the page fails to load properly.

This also seems to be an issue in graph-settings.htm

**To Reproduce**
1. Go to Arches Designer -> Resource Models -> Heritage Resource Model
2. Click on 'Modification Event -> Modification Type' in the left navigation tree (or any node that has a concept or concept-list datatype)
3. See error in the java console:
```
Uncaught ReferenceError: Unable to process binding "with: function(){return nodeForm }"
Message: Unable to process binding "if: function(){return node() }"
Message: Unable to process binding "if: function(){return node().datatypeConfigComponent }"
Message: Unable to process binding "component: function(){return {
                                    name:node().datatypeConfigComponent,params:_.extend(node(),{isEditable:!checkIfImmutable()})} }"
Message: _ is not defined
```

**Screenshots**
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/6750642/184179417-bfe88e6d-4ef5-4362-ad44-470b87684b72.png">

**Expected behavior**

**Your Arches Information**

*   Version used: dev/6.2.x
*   Operating System and version (desktop or mobile): OSX
*   Browser Name and version: Firefox Developer

**Additional context**
Originally found this in our implementation, then did a clean install w/ the default resource models.
Working from our fork of dev/6.2.x

**Ticket Background**
*   Found by: @bferguso

**Comment by chiatt** [comment]
Fixed in #8802
