### ISSUE TITLE
Invalid ajax type option in datatypes/concept.js

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#8803]
**Describe the bug**
The Ajax type option is currently set to "json" but should be "GET". This causes an issue when Arches behind a web/proxy server that limits the request types.

**To Reproduce**
NB - this can only be tested when application is hosted behind a web/proxy server that limits the request types.
1. Go to Arches Designer -> Resource Models -> Heritage Resource Model
2. Click on 'Modification Event -> Modification Type' in the left navigation tree (or any node that has a concept or concept-list datatype)
3. Proxy server will not allow the request to be completed. In our case it was responding with a 302 to the logon page.

**Screenshots**
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/6750642/184254868-a7ac7eac-da30-4fe5-835c-a981091d1781.png">

**Expected behavior**
List of Collection should be returned by the server

**Your Arches Information**

*   Version used: dev/6.2.x
*   Operating System and version (desktop or mobile): OSX
*   Browser Name and version: Firefox Developer Ed.
*   Link to your Arches Install (optional):

**Additional context**
Invalid request type only rejected if web/proxy server in front of Arches instance rejects/limits request types

**Ticket Background**
*   Found by: @bferguso

**Comment by chiatt** [comment]
Fixed in #8805
