### ISSUE TITLE
dev/7.0.x CSS Bug with Right-to-Left Languages in Arches Designer

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#8830]
I'm running dev/7.0.x Arches core with the Arches HER project. I'm testing some internationalization features. Although I haven't installed Hebrew or Arabic .po files, I could see a CSS (?) bug once I switched from English to "Arabic" (again no .po files). This likely has something to do with styling assumptions in Arches Designer with Right-to-Left languages.

I'm using a the Brave (based on Chrome) browser in Windows 11.  Screenshot is attached.

![arches-ui-bug-internationalization](https://user-images.githubusercontent.com/1286742/185253553-c4a42a8d-8134-4ac2-a848-868ff78a4a48.png)

The same layout / style bug is present in the Hebrew view.

![arches-ui-bug-internationalization-he](https://user-images.githubusercontent.com/1286742/185259777-7d225717-5423-4fe3-aedc-b7289eb898f7.png)

**Comment by chiatt** [comment]
Resolved in #8847
