### ISSUE TITLE
Possible Bug: dev/7.0.x Bug Display of the Correct Language for the "Publish Graph" button

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#8835]
I'm running dev/7.0.x Arches core with the Arches HER project in order to test some internationalization features. I haven't installed extra Hebrew or Arabic .po files.

In Arches Designer, I'm attempting to add names for branches in multiple languages. Hebrew so far has the most complete user interface translations. However the blue "Publish Graph" button is rendered in English, not the expected Hebrew while I'm in the Hebrew view of the UI.

I'm not sure this is a bug, it may just be that the .po files to configure the Hebrew UI is incomplete. Attached is a screenshot.

![arches-ui-bug-internationalization-button-lang](https://user-images.githubusercontent.com/1286742/185264084-05f246f6-6cb5-4b9e-a418-1d64b05aac91.png)

**Comment by jacobtylerwalls** [comment]
This string is marked for localization now.
