### ISSUE TITLE
Branches not working in 7.x

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8842]
**Describe the bug**

Branches don't seem to be working 7.x - they're all showing as inactive.  There's also a function to publish branches - I'm not sure that makes sense.  In any case, the publication of branches doesn't seem to affect the active/inactive status of the branch so that it can be used in a graph.

**To Reproduce**
1. Go to any new graph
2. Try to add a branch
3. Problems

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by aarongundel** [comment]
Per discussion with @robgaston and @chiatt remove the active flag from branches; treat all branches as active.  Remove the publish button from branches.

**Comment by aarongundel** [comment]
thanks @ekansa for finding this issue.

**Comment by ekansa** [comment]
@aarongundel  Thanks for following up and investigating so quickly!

**Comment by chrabyrd** [comment]
resolved in #8874
