### ISSUE TITLE
dev/7.0.x Bug Display of the Correct Language for the "Unpublish Graph" button

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#8848]
I'm running dev/7.0.x Arches core with the Arches HER project in order to test some internationalization features. I haven't installed extra Hebrew or Arabic .po files.

In Arches Designer, I'm attempting to add names for branches in multiple languages. Hebrew so far has the most complete user interface translations. However the orange "Unpublish Graph" button is rendered in English, not the expected Hebrew while I'm in the Hebrew view of the UI.

This seems very related to this bug I reported earlier (https://github.com/archesproject/arches/issues/8835). Attached is a screenshot.
![arches-unpublished-branch-label-bug](https://user-images.githubusercontent.com/1286742/185995707-b7ae1fdc-7906-481e-94da-ff6216e760da.png)

**Comment by robgaston** [comment]
the issue here is that these strings are not in the PO files (same as #8835).

in both cases, #8840 should make these strings available in the PO files, though they will still need to have translations provided

**Comment by jacobtylerwalls** [comment]
This string is marked for localization now.
