### ISSUE TITLE
dev/7.0.x Bug Display of language dropdown option list interfering with other text

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#8854]
I'm running dev/7.0.x Arches core with the Arches HER project in order to test some internationalization features. I haven't installed Hebrew or Arabic .po files, but I'm trying to do some tests that don't depend on those.

In the user interface for creating a new resource instance, the language drop down option list has messy interference from the label of another field, see the screenshot

![arches-instance-add-language-dropdown](https://user-images.githubusercontent.com/1286742/186261077-de950e12-042c-4a33-b286-64381eb4ee5d.png)

**Comment by apeters** [comment]
fixed by #8896
