### ISSUE TITLE
Resource Editor: Display vertical menu when designing resource/branch

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#887]
### Bug Report

Improve user experience and navigation by showing vertical menu when user is in the resource/branch designer workflow

**Comment by apeters** [comment]
do you mean the graph manager where users are creating the actual resource model? (adding nodes/edges, etc...)

**Comment by dwuthrich** [comment]
Yes.  Vertical (Side) menu should be visible at all times, even when user is using Arches Designer and its various tools (e.g.: graph manager, card manager, forms, reports, etc.)

**Comment by apeters** [comment]
Ok, that's clear.  Also, currently that side nav is associated with a header that shows login information among other things.  Should we be showing that as well?

**Comment by dwuthrich** [comment]
No.  See arches_resource_editor_v2.html for example of side menu/header

**Comment by apeters** [comment]
Got it!


Director of Web Development - Farallon Geographics, Inc. - 971.227.3173

**Comment by dwuthrich** [comment]
meets requirements
