### ISSUE TITLE
There are many areas were the padding of elements only works in LTR and is off in RTL.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#8871]
The following are a bunch of photos of areas where padding needed to be fixed.  Some of the photos are shown after the fix itself.

Fix several spacing issues on the graph designer page

<img width="615" alt="Screen Shot 2022-08-30 at 1 03 02 PM" src="https://user-images.githubusercontent.com/823773/187534252-baa33046-f8d5-496b-a0f9-e06d31aa0437.png">

----------------------
Arches help title

![Screen Shot 2022-08-24 at 6.08.29 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/37777241-87f6-400f-bdf1-4d862191797b)
-----------------------
Placement of opacity slider and basemap icons
<img width="317" alt="Screen Shot 2022-08-30 at 3 21 59 PM" src="https://user-images.githubusercontent.com/823773/187554045-01ef75f1-4a0a-4558-b995-3caa67487f32.png">
<img width="308" alt="Screen Shot 2022-08-30 at 3 22 24 PM" src="https://user-images.githubusercontent.com/823773/187554046-8d71d093-add0-4893-a95a-880fa0ae6d8b.png">

----------------------
Placement of header labels
<img width="934" alt="Screen Shot 2022-08-24 at 6 47 15 PM" src="https://user-images.githubusercontent.com/823773/187531436-564f5ad7-4d1c-468b-a728-b0353b8078d9.png">

-----------------------
Title placement on change password modal

<img width="397" alt="Screen Shot 2022-08-24 at 6 48 41 PM" src="https://user-images.githubusercontent.com/823773/187531636-36c252a3-4ec8-473e-aeff-8d87423a55c0.png">

-----------------------
Link alignment on card config 

<img width="251" alt="Screen Shot 2022-08-24 at 11 35 01 AM" src="https://user-images.githubusercontent.com/823773/187532077-315ca28e-a9c1-43b7-ada2-f7c1a0a28f38.png">

----------------------
Fix button alignment for "add new" card in the header

<img width="386" alt="Screen Shot 2022-08-25 at 9 35 59 AM" src="https://user-images.githubusercontent.com/823773/187534742-1b3e8200-6c56-4c65-a85d-89173e418b47.png">

---------------------
Time wheel and button placement issues
<img width="495" alt="Screen Shot 2022-08-30 at 12 51 19 PM" src="https://user-images.githubusercontent.com/823773/187530942-db7158be-736b-4d16-b5f3-4bd315374a1e.png">

---------------------
The related resource info panel
<img width="316" alt="Screen Shot 2022-08-29 at 3 10 07 PM" src="https://user-images.githubusercontent.com/823773/187311497-11c7bef9-d115-490e-9ddd-1c25769fb1c4.png">

----------------------
The search results footer
<img width="392" alt="Screen Shot 2022-08-29 at 3 50 57 PM" src="https://user-images.githubusercontent.com/823773/187314962-5ff5e774-7fbd-4f96-af0c-10691f3f46fa.png">

----------------------
The term search icon
<img width="421" alt="Screen Shot 2022-08-29 at 5 03 20 PM" src="https://user-images.githubusercontent.com/823773/187325224-a2a164a7-39f7-43ca-abc2-325e231d5483.png">

**Comment by chiatt** [comment]
Fixed in #8903
