### ISSUE TITLE
Edit log fails for resources with tiles nested 2 levels or deeper

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#8879]
Edit log javascript only handles for one degree of child tiles currently, resulting in errors.  Existing logic should be made recursive to handle for any depth.

**Comment by chiatt** [comment]
Fixed in #8880

**Comment by chiatt** [comment]
Reopening until fix is applied to 6.2.x

**Comment by aarongundel** [comment]
applied to 6.2, closing.
