### ISSUE TITLE
"Find a card" filter in resource editor is broken

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#8911]
<img width="415" alt="Screen Shot 2022-08-31 at 11 22 03 AM" src="https://user-images.githubusercontent.com/1187406/187751632-1c4e9257-d9ed-41fd-bced-ef8bd99d5a8f.png">

Typing into the "Find a card" filter in the resource editor does nothing.  It should either filter the card list, highlight card names that match or both.

**Comment by apeters** [comment]
closed by re #8915
