### ISSUE TITLE
Resource Editor: Add global save/discard buttons to header

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#892]
### Bug Report

For the Resource Editor, saving edits to cards should be done by clicking either a "Save" or "Discard" button in the Resource Editor header, as we do in the settings/card/form managers for resource/branch design.

The current "save" buttons are meant to manage cardinality of cards and card groups.  Perhaps we should update the labels on these buttons to indicate that to the user.  

Change the current "Save" buttons for card/card container cardinality to "Add"

**Comment by apeters** [comment]
I thought we agreed that for now we will just leave this the way it is.  That is, the "Save" button truly does mean save.
