### ISSUE TITLE
iiifannotations API not working

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8935]
**Describe the bug**

There's a problem with the iiifannotations API endpoint in 6.2.  

**To Reproduce**
Procedure 1 (with AFS)
1. Using the Arches for Science Project
2. Go through the upload dataset workflow (this does happen in other workflows - but this one is easy to see - also assuming you have run the appropriate prerequisite workflows) 
3. On the Data files and location step, you'll see breakage - see screenshot below.

Procedure 2 (without AFS)
1. Hit the iiifannotations API with the appropriate/necessary parameters.  
2. The same breakage should occur

**Screenshots**

![Screen Shot 2022-08-31 at 4 36 17 PM](https://user-images.githubusercontent.com/124614/187797019-8a70ec79-f31b-47ca-8206-bb68c7d3a6a8.png)

**Comment by aarongundel** [comment]
@chiatt I think there's a problem here.  This originally worked for me, then stopped working.  I think it's because this view gets overwritten by 7131 - so the change made in migration 6837 needs to be made in 7131 as well.

**Comment by chiatt** [comment]
Fixed in #8962
