### ISSUE TITLE
Arches 7.0.0 Error while setting DB

### ISSUE THREAD

**Issue by himuura** [archesproject/arches#8945]
Hey mates! Just installed arches today, v7.0.0 and when im running python manage.py setup_db i get this:

elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)))

Any clues on how to solve?

**Comment by bferguso** [comment]
Hi @himuura  - you may want to check out this: https://github.com/archesproject/arches/blob/stable/7.0.0/releases/7.0.0.md . 

Specifically item 7 in the "Upgrading Arches" section might help sort out the issue.

**Comment by himuura** [comment]
> Hi @himuura - you may want to check out this: https://github.com/archesproject/arches/blob/stable/7.0.0/releases/7.0.0.md .
> 
> Specifically item 7 in the "Upgrading Arches" section might help sort out the issue.

Just noticed the notes!! Thanks mate!
