### ISSUE TITLE
Resource Editor: Wire up "Copy Resource" tool in "Manage..." menu

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#895]
### Bug Report

Users will want to copy a resource so that they can quickly create a new resource that differs only slightly from the current resource.

Pressing the "Copy Resource" button should:
1. confirm that the user has saved all edits
2. Automatically create a new resource with an identifier that says "Copy of <Parent Resource Identifier>"
3. Close parent resource and open copy in Resource Editory

**Comment by apeters** [comment]
fixed in the latest
