### ISSUE TITLE
z-index conflict between sidebar search components and workbench tabs

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#8952]
There is a visual bug resulting from a z-index conflict between "workbench" component tabs and sidebar search components on the search page, see below:
<img width="492" alt="Screen Shot 2022-09-06 at 9 56 05 AM" src="https://user-images.githubusercontent.com/1187406/188695520-92cb8ac3-12ec-47b9-897b-ab986590907f.png">

**Comment by apeters** [comment]
closed by #8953
