### ISSUE TITLE
Manifest manager updates

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#8973]
Polish updates for the IIF Manifest Manager

- In Manifest Manager indicate that attribution logo should be a URL.
- When creating metadata in the manifest manager, date entered in the inputs for the metadata should save when a user clicks save without having to press the + button.
- Image names not appearing in name input when a user selects and image
- We should not make a request each time a user updates the attribution logo url in the image service manager.

**Comment by chiatt** [comment]
Fixed in #8946
