### ISSUE TITLE
Resource Editor: Editor does not save concepts

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#903]
### Bug Report

Node groups with a string node and concept node aren't saved properly.  String values are saved (if the card has cardinality of n), but concepts are not

**Comment by robgaston** [comment]
This is likely a bug w/ the concept widget itself.  We should now be fully testing widgets (including resource editor and reports, not just in the card manager) as part of our QA of the widget development effort.

**Comment by apeters** [comment]
this should be fixed in the latest

**Comment by dwuthrich** [comment]
meets requirements
