### ISSUE TITLE
Allow for editing and republishing of published models 

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#9053]
Currently, after a model is published it cannot be edited until it is unpublished.

To facilitate updating models after publish, a user should be able to continue editing a model after publication.  This would mean that in the graph designer a user could edit a published graph and then decide when they want to republish it or revert to the previous publication.

It would be nice, though not essential to review all previous publications for a model and revert to any of them.  This could probably be built on top of the "revert to the previous publication" logic described above.

(RDM Phase II, 7.2.x)

**Comment by chrabyrd** [comment]
resolved in #9613
