### ISSUE TITLE
Arches Designer: Ensure that default Node, Node/Node Type branches can't be deleted

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#907]
### Bug Report

Should it be possible to delete the default node and node/node type branches?  Should they be editable or just clonable?

Seems like allowing delete of these nodes could adversely impact use of Arches.

**Comment by apeters** [comment]
worst case, those branches could always be re-created.  Alternatively, we could deliver those graphs in flat file format that a user could re-import if necessary.  Thoughts?

**Comment by adamlodge** [comment]
meets requirement
