### ISSUE TITLE
RDM Improvements to support PeriodO vocabularies without hassle

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#9072]
**Problem**
One cannot use the RDM to import a [PeriodO](https://perio.do/en/) time period vocabulary. PeriodO vocabularies can be downloaded in the JSON(-LD), Turtle, or CSV structured data formats. One can get all of the PeriodO concepts, or concepts created be a certain authority, or individual period concepts in this way. However, the Arches RDM (as of version 7) does not support import of these period vocabularies.

PeriodO is an important standard, and Arches should support it without hassle.

**Proposed Solution**
I'd like the Arches RDM to support JSON-LD and Turtle imports (in addition to RDF-XML). PeriodO structured data files are perfectly valid, but they don't seem define a "Concept Scheme" in a manner expected by the RDM import functions. It would be good to have the RDM import be a bit more "forgiving" in this respect.

**Additional context**
A few different Arches users discussed this issue in this forum thread: [https://community.archesproject.org/t/use-of-periodo-in-arches/1716](https://community.archesproject.org/t/use-of-periodo-in-arches/1716). We also discussed some experiments in converting PeriodO into RDF/XML and the trouble we encountered when ingesting into the Arches RDM.

**Comment by ekansa** [comment]
From the user "jlayt", it looks like there may be an issue with the RDM not being comprehensive in its support of SKOS. I'm quoting him from [here](https://community.archesproject.org/t/use-of-periodo-in-arches/1716/6?u=ekansa):

> Concepts do have an inScheme so should work OK. There are no top level concepts, but those are optional in SKOS so 
> shouldn’t be an issue if RDM correctly implements the standard.

**Comment by ekansa** [comment]
Here's a Perio.do turtle file for the British Museum's period concepts. I can't seem to upload it directly here to Github, so here's a link back at the Arches forum: [https://community.archesproject.org/t/use-of-periodo-in-arches/1716/13?u=ekansa](https://community.archesproject.org/t/use-of-periodo-in-arches/1716/13?u=ekansa)

**Comment by apeters** [comment]
Here's a copy of the turtle file (zipped) that @ekansa mentioned using: [periodo-authority-8m57h.ttl.zip](https://github.com/archesproject/arches/files/9966713/periodo-authority-8m57h.ttl.zip)
