### ISSUE TITLE
Exception in rich-text widget when upgrading from v6 to v7

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#9101]
**Arches Version/Branch:** dev/7.2.x

**Describe the bug and how to reproduce it:**

After upgrading a v6 project to v7 the following error occurs when accessing a page w/ a Rich Text widget on it (in both the Resource Model Editor and when editing a Resource data):
`TypeError: Cannot set properties of null`

On line 47 of the `views/components/widgets/rich-text.js` file this is the offending statement:
`            currentValue[currentLanguage.code] = {value: '', direction: 'ltr'};`

The solution for my instance was to check for a null currentValue in the section of the `if` block and set it to an empty object if it is null.

It seems to be a transitory issue with the project upgrade as I was  unable to replicate the issue after applying the patch, updating the resource model, reloading the data, and then removing the patch.

**Comment by chiatt** [comment]
Resolved in #9102
