### ISSUE TITLE
Search errors out when searching for a string/lang pair where the language doesn't exist

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#9173]
**Arches Version/Branch:** dev/7.2.x

**Describe the bug and how to reproduce it:**
When using advanced search to search for a string with no value and a language that doesn't exist, then the UI throws up an error.

![Screen Shot 2023-01-13 at 11 31 57 AM](https://user-images.githubusercontent.com/823773/212403144-fe7d4e38-2449-4748-9146-081c8210386a.png)

**Comment by chiatt** [comment]
fixed in #9174
