### ISSUE TITLE
Update the Graph `copy` method to handle grouping cards

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#9267]
Currently grouping cards save a config with the following:

```
{
    "groupedCardIds": [],
    "sortedWidgetIds": []
}
```

When `graph.copy()` is called, it copies over this config to the new graph without updating `groupedCardIds` nor `sortedWidgetIds`. This method should be altered so that it also updates its config to use the copied  graph's `groupedCardIds` and `sortedWidgetIds`.

**Comment by chiatt** [comment]
Fixed in #9276
