### ISSUE TITLE
Required node error is unclear

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9280]
It appears the required node error needs to be updated to support i18n

![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/34b7e0f5-c153-48b0-861a-583cb2dcb2d4)

**Comment by jacobtylerwalls** [comment]
No longer seeing this. Might have been a side effect of the issue described in https://github.com/archesproject/arches/pull/10096#discussion_r1344674417.

**Comment by jacobtylerwalls** [comment]
Actually, I can reproduce this after having fixed #10486
