### ISSUE TITLE
Yarn 1.x reaching end of life

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9282]
In 2020 yarn 1.22, the version we currently use in Arches, [entered maintenance mode](https://classic.yarnpkg.com/en/docs/install#mac-stable). Moving to yarn 3.x will require some [effort](https://yarnpkg.com/getting-started/migration#why-should-you-migrate) and likely impact Arches project maintainers. It may be necessary in the coming months to either upgrade to the latest version of yarn or to replace yarn with npm (or possibly even [pnpm](https://www.atatus.com/blog/npm-vs-yarn-vs-pnpm/)). Although yarn does provide some performance benefits during installation, moving to npm would mean managing one less dependency.

**Comment by chiatt** [comment]
That's a good point @bferguso. We should aim to do that.

**Comment by whatisgalen** [comment]
following

**Comment by chrabyrd** [comment]
resolved in #10980
