### ISSUE TITLE
Switching between languages sometime don't save instences values on the new language.  

### ISSUE THREAD

**Issue by YuvalShafriri** [archesproject/arches#9288]
When creating a new resource instance in an existing graph, after writing the instance name, saving it, and switching to another language (in this case, English), the results list shows up as displayed in the screenshot below. 
"לא מוגדר" is the Hebrew translation of "undefined"
[image.png](https://files.slack.com/files-tmb/T0NH402F8-F04S2EZG45S-a3a3cee9d5/image_480.png)

**Comment by YuvalShafriri** [comment]
Hi @chiatt 
I just realized that on the string type value I have the option to create separate text values for each UI language,  
**So, this is not so much a bug but a feature...** 
 as a User i expected to see the single value I entered after switching to English, even if it written in Hebrew, so i just needed to alter the language dropdown above the textbox and see or enter new text... 
this means also that need to make two data import for each language
 better to clarify it somewhere...
 Anyway, great feature :)

**Comment by chiatt** [comment]
Thanks @YuvalShafriri - If you're importing with csv, you should be able to import data only once using a column for each language. If you have a string node for 'name', then I think the columns in your csv would need to be labeled `name (en), name (he)`.  I don't think this syntax is in the documentation, but you can get it a template header if you export a csv from the command line.  Be aware, you have to be a little careful if your intent is to append data as explained here: https://arches.readthedocs.io/en/stable/localizing-arches/?highlight=localization#csv-exports-and-imports
