### ISSUE TITLE
Search buffer distance showing as oval rather than circle

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches#9329]
There seems to be something going on with buffering around points. When setting a distance, the buffer comes out as an oval rather than a circle. Is this something to do with the mapping projection?  Works fine on other Arches instances I have looked at, Arcade or Heritage Jersey for example. 

Also, it might be helpful to Users to clarify what the ‘distance’ is, radius or diameter, for example although this is shown within the GeoJSON code:

![image](https://user-images.githubusercontent.com/47248246/96866945-f6363e80-1463-11eb-9496-56aef24672f8.png)

**Comment by dwuthrich** [comment]
@rebeccawilliamss I think this may be a configuration issue.  Your settings.py or local settings_local.py fill should have an entry that looks like this:

ANALYSIS_COORDINATE_SYSTEM_SRID = 3857  # Coord sys units must be meters

I believe this setting tells Arches which srid to use for things like buffers.  Perhaps @chiatt can confirm

**Comment by chiatt** [comment]
Yeah - I suspect the ANALYSIS_COORDINATE_SYSTEM_SRID needs to be updated. I'm going to close this issue because it is something that can be addressed in the project settings. @rebeccawilliamss, if using a different ANALYSIS_COORDINATE_SYSTEM_SRID doesn't solve the issue, please reopen this ticket.
