### ISSUE TITLE
Accessibility: Base templates to adhere to semantic HTML5 markup with landmarks

### ISSUE THREAD

**Issue by phudson-he** [archesproject/arches#9330]
This will form part of the accessibility contribution work for Arches v7.

Changes made will to adhere to [WCAG 2.1 Requirements](https://www.w3.org/TR/WCAG21/#requirements-for-wcag-2-1). Work will involve ensuring semantic HTML5 markup is used and include appropriate page landmarks where required.

Will look at the following files:

- arches\arches\app\templates\base.htm
- arches\arches\app\templates\base-manager.htm
- arches\app\media\css\arches.scss

An HE fork was created from archesproject/arches/accessibility and a pull request with an appropriate feature branch will be submitted when ready.

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @phudson-he
*   Designed by: @phudson-he

**Comment by phudson-he** [comment]
FYI: @apeters @johnatawnclementawn @aj-he

**Comment by phudson-he** [comment]
PR raised here: #9336

**Comment by apeters** [comment]
fixed by #9336
