### ISSUE TITLE
Add Image Datatype

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9333]
Currently images are managed in arches using the file-list datatype. However, there is commonly data associated with images such as caption, credit, and location that currently must be recorded in separate nodes in a card. With an image datatype this information could be saved alongside the url, perhaps accompanied by other image information such as dimensions and pixel depth. This would reduce the number of nodes needed to track metadata about images. It would also simplify design around components such as the 'PhotoGalleryCard' or that are not intended for use with other file types.

**Comment by azaroth42** [comment]
+1 to this issue.
Also, the URL to the image should be able to be outside of Arches, e.g. point to a IIIF instance, or to any image on the web.

**Comment by apeters** [comment]
closed by #9334
