### ISSUE TITLE
rename first Settings tab to Indentifiers

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#935]
Regarding the first tab in the Settings Menu for either Resource Models or Branches. Currently the tabs are called Resource Model Identifiers and Branch Identifiers, respectively, and I think in both cases it would be cleaner to just name the tab Identifiers.

**Comment by dwuthrich** [comment]
Tab should be labeled "Identifiers" not "Branch Identifiers"

**Comment by mradamcox** [comment]
Reopening this to apply it to the Form editor as well. I would also pull for changing "Form Settings" to "Settings" AND/OR removing "Form" from "Form Name", "Form Subtitle", and "Form Icon"

**Comment by apeters** [comment]
Closing and creating a new ticket #1121
