### ISSUE TITLE
Error when accessing graph model in django /admin

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#9365]
Issue found on v7.2.1 and dev/7.4.x 

When trying to open a graph model in the /admin/models/graphmodel/ page the following error occurs
![graphmodel_in_admin](https://user-images.githubusercontent.com/119508494/227279398-957a5dc2-3723-4c69-9e36-264913ce1b6c.png)

**Comment by chiatt** [comment]
Possibly related: https://github.com/archesproject/arches/issues/9398
