### ISSUE TITLE
Concept Widget: Does not appear to delete last of several saved records

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#940]
### Bug Report

When a concept widget has cardinality n, it appears that the last of several saved records is not deleted:

see: http://recordit.co/hkwbTSzFXI

However, when refreshing the screen the last record does appear to have been deleted

**Comment by ryan86** [comment]
Unable to reproduce this locally.

**Comment by apeters** [comment]
I can't reproduce this either.
