### ISSUE TITLE
Some card configs are not restored after graph import

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9407]
In designing a graph If a user modifies a card's widget sort order, or changes a node's widget to something other than the default, those changes are not reflected after that graph is imported into another system. The changes appear in the exported json, but are not restored after import, so it seems there is a problem with import rather than export.

This image shows configs saved in the designer (left) and how they appear after import (right)

![Screenshot 2023-04-04 at 4 39 36 PM](https://user-images.githubusercontent.com/1877663/229947425-039d02a6-6148-436e-9180-cebedbbb9d83.png)

**Comment by ryan86** [comment]
- Widget template assignment
- Sort order of widgets in card

**Comment by bferguso** [comment]
I'm also seeing that sub-cards are not presented in the correct order after re-import. Looking at the `cards` table, the sort order values appear to be correct, however they're not presented in the correct order in the card tree.

**Comment by bferguso** [comment]
It also appears that the 
1. `nodes.sortorder` column is not being updated by the graph designer and
2. card and widget reordering does not always trigger an update in the graph designer (the Save Card Edits button doesn't appear and publishing afterwards doesn't update the cards and widgets sort order in the graph). To force the save one can modify and revert another change in the card (name, etc) to enable the save button.
