### ISSUE TITLE
ES my_project_concepts index not updated when import thesauri

### ISSUE THREAD

**Issue by ViktorGetty** [archesproject/arches#9437]
Manually created simple thesaurus 
![image](https://user-images.githubusercontent.com/17183432/232852111-5d133ae1-3f57-4ac1-b50f-c44373a66f01.png)
On Elasticsearch side 5 entries added to 'my_project_concepts' index in addition to 2 existing:
![image](https://user-images.githubusercontent.com/17183432/232852606-e7c8fca2-0431-4130-956d-181d1a43423a.png)
one for AAT_Concepts, one for Language and 3 for different languages.
Then exported this thesaurus and imported into new (identical) instance of Arches. All values look fine in RDM, but only 1 addition entry created in ElasticSearch for 'AAT_Concept' (top level).
![image](https://user-images.githubusercontent.com/17183432/232853316-081134f8-c408-4567-8cd8-a13a132db813.png)
Then, when a resource created (with corresponding model that uses this thesaurus in RDM) is opened, the value of the language is missing, and in the Arches logs there is Elasticsearch 'id not found' error.

**Comment by apeters** [comment]
I agree that this appears to be fixed in `dev/7.5.x`.  I wasn't able to reproduce.
