### ISSUE TITLE
After deleting thesaurus through UI 'my_project_concepts' not cleaned in ES

### ISSUE THREAD

**Issue by ViktorGetty** [archesproject/arches#9444]
This issue is reciprocal to 9437. Steps to reproduce:
In the fresh instance of Arches manually create a thesaurus with one top concept and one entry like so:
![image](https://user-images.githubusercontent.com/17183432/233185390-79df4c75-ed57-42a6-bab8-dc75a7dd5fd4.png)
In Elasticsearch this results in 7 entries in 'my_project_concepts' index - 2 initial and 5 new. One for thesaurus, one for top level concept and 3 for each language:
![image](https://user-images.githubusercontent.com/17183432/233185969-4f02246e-daf5-4650-8eb5-3a2bb3e66be6.png)
Then delete 'AAT Concepts' thesaurus and check Elasticsearch/my_project_concepts' index:
![image](https://user-images.githubusercontent.com/17183432/233186307-e6037b38-1bfa-4fac-b381-fd742d3ebd46.png)
Only one out of 5 entries deleted (for 'AAT Concepts'). This leads to errors when later one creates a new thesaurus with English language. In UI it is only one value, but in Elasticsearch there are multiples. Here is an example of the error from DataDog when API was used to insert a resource:
![image](https://user-images.githubusercontent.com/17183432/233186893-18386624-43b8-48fb-92a8-b7dd385bf0a9.png)

**Comment by johnatawnclementawn** [comment]
Resolved in #10821
