### ISSUE TITLE
Update Branches with ability to be immutable when added to graph

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#9466]

**Comment by bferguso** [comment]
Is this issue intended to address the inability to use a branch to move a tree of a graph from one part of a graph to another? If the branch used to transfer the tree is transient, the original graph can no longer be loaded due to the required reference to the missing branch.

**Comment by chrabyrd** [comment]
resolved in #9613

**Comment by apeters** [comment]
This may be fixed in #9613, but it's still an issue in at least 7.6.x (maybe 7.5.x but I haven't tested).  Hence my ticket #10908
