### ISSUE TITLE
Resource Report / Tile proxy filter_by_perm bottleneck

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#9484]
When a tile proxy model instance calls the ``filter_by_perm`` method, only the nodegroupid from the tile is passed to the method. However this method is called repeatedly on the same nodegroups which we can assume have already been checked for permissions. For ex:
Tile 1 - Ng A (check 1)
  child Tile 1A - Ng B (check 2)
  child Tile 1B - Ng C (check 3)
Tile 2 - Ng A (check 4)
  child Tile 2A - Ng B (check 5)
  child Tile 2B - Ng C (check 6)
Tile 3 - Ng A (check 7)
  child Tile 3A - Ng B (check 8)
  child Tile 3B - Ng C (check 9)

The perm method gets called N nodegroups - 1 more times than it has to per node group, i.e. it could get called 3 times in the example but instead gets called 3^2 times.

Note that there are only 3 nodegroups and all we're trying to do in this method is check the permission for the nodegroups, not permissions on tiles. Therefore we should only check nodegroup-permission 1 time per nodegroup.

Relevant logic:
https://github.com/archesproject/arches/blob/stable/7.3.0/arches/app/models/tile.py#L692

This issue is especially burdensome for loading reports here:
https://github.com/archesproject/arches/blob/stable/7.3.0/arches/app/views/api.py#L1087

**Comment by whatisgalen** [comment]
I'm seeing some pretty encouraging results but actually modifying the logic in the ResourceReport api like so:

``readable_nodegroups = list(str(nodegroup.pk) for nodegroup in get_nodegroups_by_perm(request.user, ["models.read_nodegroup"], any_perm=True))``

``if "tiles" not in exclude:
            permitted_tiles = TileProxyModel.objects.filter(resourceinstance=resource, nodegroup_id__in=readable_nodegroups).select_related("nodegroup").order_by("sortorder")``
            
``if "cards" not in exclude:
            permitted_cards = CardProxyModel.objects.filter(graph_id=resource.graph_id, nodegroup_id__in=readable_nodegroups).select_related("nodegroup").order_by("sortorder")``

**Comment by chiatt** [comment]
Hey @whatisgalen, what version of arches is this targeting, 6.2 or 7.4?

**Comment by whatisgalen** [comment]
@chiatt Sorry I missed your comment! I don't know if this has been addressed as of 7.5 but the intent was to fix it in 7.x
