### ISSUE TITLE
Resource Designer: Change order of commands in "manage" dropdown button

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#949]
### Bug Report

Move "manage graph" to follow "manage reports"
For branches, move "manage graph" to follow "manage cards"

**Comment by mradamcox** [comment]
I was thinking about this yesterday, and wondering if it would make sense
to leave those entries in the same order, but change the order in the
top-left MANAGE... bar when editing a Resource Model or Branch.
Intuitively, I think it makes more sense for Graph/Semantics to show up
after Settings.  As in, if you are going to describe what the components of
a Resource Model or Branch are, you will probably want to talk about the
Graph before you talk about the Report.

**Comment by dwuthrich** [comment]
Most recent version of Arches addresses this issue
