### ISSUE TITLE
Resource Editor: Canceling the creation of a new resource instance still saves to the database

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#952]
### Bug Report

Arches creates a resource instance, even when a user discards an edit.  Note the following steps:
1. Create a new resource instance
2. begin editing a node
3. cancel your edit and navigate away from the editor
4. return to resource editor and select recently added
5. observe that a new resource instance was added despite press cancel

see: http://recordit.co/Id3P420WJY

**Comment by apeters** [comment]
Hitting "Create Resource" does just that.  At that point the resource is created in the system.  Adding nodes have nothing to do with creating a resource instance.

**Comment by dwuthrich** [comment]
Most recent version of Arches addresses this issue
