### ISSUE TITLE
Resource Editor: Can't cancel edit of a saved record for a card container

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#953]
### Bug Report

Arches allows users to edit saved card container records, but does not show cancel/save buttons during edit session.

see: http://recordit.co/VmAgHSY5I0

Arches should allow user to cancel edits, require user to press the save button on edit.

**Comment by apeters** [comment]
When we discussed this a while ago it seemed that we would keep this the way it is.  There is no place in the app where we allow the user to "undo" their edits after a save to the database.

**Comment by dwuthrich** [comment]
meets requirements
