### ISSUE TITLE
Changing node data type in Graph Designer causes exception

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#9559]
An exception occurs when changing the datatype of a node in the Graph Designer.

The following is shown in the server log:
`[25/May/2023 08:10:04] "POST /int/arches-fossils/node/018c4c31-dc89-4ed2-801d-7ea1673d86d9 HTTP/1.1" 500 275`

No stack trace is shown on the server. This causes the following javascript exception:
`Uncaught TypeError: can't access property "find", self.graph.nodegroups() is undefined`

This appears to be an issue with changing between any two data types. The only way around it is to either delete/recreate the node or to change it to semantic first and then back to the target datatype (this doesn't always work).

**Comment by chiatt** [comment]
Fixed in https://github.com/archesproject/arches/pull/9815
