### ISSUE TITLE
We should create a command line function to update serialized graphs when a language is enabled

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#9625]
We should add a command line function that will add serialized graphs for each language in the system without creating a new graph_x_published_graph value.

To reproduce:

1. Get a project running with only the default language enabled, ensure it has at least 1 Resource model
2. Enable support for multiple languages by uncommenting or adding a value in the `LANGUAGES` setting in `settings.py`
3. Manually rebuild webpack to update the language switcher
4. Select the non-default language from the switcher
5. Attempt to access the graph designer, resource editor, or resource report pages
6. Notice the application breaks because there's no serialized graph for that language

**Comment by chiatt** [comment]
We have a `graphs publish` command. Maybe we could add an argument to that command? `graphs publish --update`?

**Comment by apeters** [comment]
I have run into this problem as well.  It would be nice to get this fixed soon.

**Comment by chrabyrd** [comment]
resolved in #10116
