### ISSUE TITLE
Widget: Create concept multi-select using check boxes

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#965]

**Comment by robgaston** [comment]
We'll need to create an additional data type (`concept-array` or `concept-list` or something along those lines) to support this

**Comment by ryan86** [comment]
Would it be simpler to use the same datatype for concept and concept list with concept just being a list of length 1?

**Comment by apeters** [comment]
I know that @robgaston and I came to the conclusion that we needed a separate datatype for a list, which we would need if we actually want to store the data as an `array` type.

**Comment by robgaston** [comment]
@ryan86 I think that would work and might be simpler in the implementation, but my concern would be that widgets that assume an array of one could hide tile data either loaded via import or added using a different widget.  For that reason, I think it seems like a better idea to just be explicit about it handle them using separate datatypes.

**Comment by dwuthrich** [comment]
meets requirements
