### ISSUE TITLE
Create dedicated setting for webpack to identify app server

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9656]
Currently webpack uses the `ARCHES_NAMESPACE_FOR_DATA_EXPORT`, but this setting is actually intended for a different purpose and is not guaranteed to be the arches host address. 

We need a dedicated setting such as `ARCHES_HOST_URL = "http://localhost:8000/"`

This setting should be added to the project template so that project creators can easily access it when customizing their project.

**Comment by chrabyrd** [comment]
This has been addressed in: https://github.com/archesproject/arches/pull/9426
