### ISSUE TITLE
Language selector should be on the right side of rich text widget

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9678]
The language selector is on the left crowding the required value asterisk. It should align on the right as it does for the regular string widget. 

<img width="511" alt="image" src="https://github.com/archesproject/arches/assets/1877663/84553656-5637-4c08-b92b-7d7458ef404c">

<img width="655" alt="image" src="https://github.com/archesproject/arches/assets/1877663/22660ab9-4d8c-4ec3-983f-bd27a56c0bea">

**Comment by johnatawnclementawn** [comment]
For v7.4.x, addressed in #9686 
For v7.5.x, addressed in PR for #9518
