### ISSUE TITLE
Create Branch: Appellation.E41

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#968]
### User Story

As a developer of resource models, I want a CRM-compliant appellation.E41 branch available to me to append to a resource model that I may develop.

Applies to: Actor
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repository

**Comment by adamlodge** [comment]
Applies to Actor, not Activity

**Comment by ryan86** [comment]
Notes
- Epithet.E82 cannot be related to Appellation.E41 with a P131 property.
- Actor Appellation.E82 cannot be related to Appellation.E41 with a P131 property.

**Comment by ryan86** [comment]
Removed epithet from branch in favor of appellation type with concept collection name type. Removed collector Appellation E41 in favor of connecting directly to resource.
