### ISSUE TITLE
Identify the list of branches that should ship with Arches by default

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#970]

**Comment by adamlodge** [comment]
This is the raw list taken from a review of the old HIP resource graphs.  Currently making a ticket for every one of these.  

appelation.E41
arches activity phase.E4
arches event phase.E4
beginning of existence.E63
condition assessment.E14
description.E62
end of existence.E64
evaluation criteria assignment.E13
external resource.E1
file path.E62
identifier.E42
information carrier.E84
keyword.E55
language.E55
measurement type.E55
modification event.E11
name.E41
place.E53
production.E12
publication event.E12
Resource Creation Event.E65
resource type classification.E55
right.E30
right description.E30
temporal coverage.E4
thumbnail.E62
title.E41
