### ISSUE TITLE
Add support for using Elasticsearch API Key authentication

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#9700]
There is a requirement to be able to use API Keys instead of username/password basic auth to connect to and use and Elasticsearch instance. 

It is proposed that we be able to specify api_key details in the settings instead of username and password.

The Elasticsearch python client docs provide the following example
```py
# Set 'api_key' on the constructor
client = Elasticsearch(
    "http://localhost:9200",
    api_key=("id", "api_key")
)
client.search(...)
```

**Comment by aj-he** [comment]
We'll be picking this up shortly

**Comment by RobOatesHistoricEngland** [comment]
@apeters @chiatt Any feedback on this and #9850?

**Comment by apeters** [comment]
@RobOatesHistoricEngland I think it would be nice to allow for either scenario (basic auth or api key)

**Comment by aj-he** [comment]
completed in #9859
