### ISSUE TITLE
Create Branch Arches Event Phase E4

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#971]
### User Story

As a developer of resource models, I want a CRM-compliant Arches_Event_Phase.E4 branch available to me to append to a resource model that I may develop.

Applies to resource models: Actor, Historical Event
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repo

**Comment by adamlodge** [comment]
Two issues:
1. Cant connect Phase Type Assignment (E17) to  Cultural Period (E55) based on P41i per old graph.    However, I think we made a mistake in the old graph and the connecting property should have been P2.  As such, I am using P2 in place of P41i for this. @annabelleee : please indicate your thought on this decision.

2. The branch cannot connect to the Actor top node.

**Comment by annabelleee** [comment]
Split these into two different branches: Actor Phase Type and Event Phase Type. The Actor Phase type connects to the Actor resource model via P41i and the Event Phase Type connects to the Historical Event resource model via P10. Also Phase Type Assignment (E17) to Cultural Period (E55) connects via P42.
