### ISSUE TITLE
1.1.1 Non-Text Content - Logo has nonsensical alt text

### ISSUE THREAD

**Issue by imogenroberts** [archesproject/arches#9710]
As a user using a screen reader and the keyboard to navigate, alighting on the Arches logo in the left hand nav should prompt the screen reader to read out that the user has alighted on a link to the Arches home page. 

**Linked work item:**
#9391 

**Expected Result**:

Logo does not need alt text and can be marked as 'null' (use speech marks - "" - in the alt text in the code) as it provides no useful information to the user. This means the screen reader will simply ignore the picture and just read out the alt text for the button.

**Actual Result:**

Logo has nonsensical alt text - 'graphic nifty logo' - which doesn't add any meaning for the user.

**Evidence:**
(Use NVDA screen reader to reproduce)

**Comment by johnatawnclementawn** [comment]
Addressed in #9737
