### ISSUE TITLE
Create Branch: Beginning of Existence.E63

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#972]
### User Story

As a developer of resource models, I want a CRM-compliant Beginning_of_Existence.E63 branch available to me to append to a resource model that I may develop.

Applies to resource models: Activity, Actor, Heritage Resource, Heritage Resource Group, Historical Event
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance

**Comment by ryan86** [comment]
Notes
- Beginning of Existence.E63 cannot be related to Activity.E7 with a -P92 property.
- Beginning of Existence.E63 cannot be related to Historical Activity.E5 with a -P92 property.

**Comment by ryan86** [comment]
Now using P116i to connect to activity and historical event resources.
