### ISSUE TITLE
Create Branch: Condition Assessment E14

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#973]
### User Story

As a developer of resource models, I want a CRM-compliant Condition_Assessment.E14 branch available to me to append to a resource model that I may develop.

Applies to resource models: Heritage Resource, Heritage Resource Group
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repo

**Comment by ryan86** [comment]
Notes
- Condition Description cannot be of type E62
- Date Condition Assessed.E49 cannot be related to Condition State.E3 with a P4 property.
- Condition Image.E73 cannot be related to Condition State.E3 with a -P138 property.
- Condition Image File path cannot be of type E62
- Condition Image Thumbnail cannot be of type E62 (may not be applicable in Arches4)

**Comment by annabelleee** [comment]
Relates to Heritage Resource E18 with P34i
Relates to Heritage Resource Group E27 with P34i
Added File Path to Condition Image E36, but unclear if necessary.
