### ISSUE TITLE
Create Branch End of Existence (E64)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#975]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording End_of_Existence.E64 available to me to append to a resource model that I may develop.

Applies to resource models: Activity, Actor, Heritage Resource, Heritage Resource Group, Historical Event
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance

**Comment by ryan86** [comment]
Notes
- End of Existence.E64 cannot be related to Activity.E7 with a -P93 property.
- End of Existence.E64 cannot be related to Historical Activity.E5 with a -P93 property.

**Comment by ryan86** [comment]
Now using P115i to associate to activity and historical event resources.
