### ISSUE TITLE
Move call to save a resource instance out of resource.index method

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9758]
Ideally we would not make changes to data in postgres when we are indexing a resource in ElasticSearch

**Comment by chiatt** [comment]
The reason why we are calling save within index is because we need to calculate and set the descriptors on the database instance record. We can't put it in resource.save because we don't call resource.save when saving a tile. Instead, we just save the tile and then reindex the resource. Calling save on the resource with in save ensure that save is always called after all tiles are saved.

**Comment by chrabyrd** [comment]
resolved in #9967
