### ISSUE TITLE
Create Branch Evaluation Criteria Assignment (E13)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#976]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording Evaluation_Criteria_Assignment.E13 available to me to append to a resource model that I may develop.

Applies to resource models: Heritage Resource, Heritage Resource Group
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repo

**Comment by annabelleee** [comment]
Relates to Heritage Resource E18 and Heritage Resource Group E27 via P140i.
