### ISSUE TITLE
1.4.3 Contrast - Three contrast errors present on Resource Report

### ISSUE THREAD

**Issue by imogenroberts** [archesproject/arches#9760]
As a user who struggles to discern like colours, contrast between text and background colours should always meet the WCAG minimum standard ratio, 4.5:1.

**Linked Work Item:**
#9663 

**Expected Result:**
Contrast been all text and background colours should meet or exceed the minimum standard ratio of 4.5:1.

**Actual Result:**
Three instances of very low contrast, occurring on text 'Report Date, 'Month, Day, Day, Year' and 'Hide Null Values'. Each of these has a contrast ratio of 2.68:1, well below the WCAG-recommended 4.5:1 contrast ratio.

**Evidence:**

![Image](https://github.com/archesproject/arches/assets/77161085/dbdba952-5651-4e4a-b06f-797d0acc90d5)

**Comment by johnatawnclementawn** [comment]
Resolved in #9773
