### ISSUE TITLE
ActivityStream is swamped by tiles during resource creation

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#9768]
When creating a resource, every tile that gets created during the process spawns an entry in the activity stream at /history. With only 19 instances, my stream is already at 1200 entries, making it very expensive to consume.

Instead, there should be a Create entry that subsumes all of the subsequent tile edit Update entries.

**Comment by azaroth42** [comment]
Propose that resource.save() should send a flag to the tile.save() function to prevent the creation of the edit_log entry for each tile. Tile edits don't go through resource.save(), so the updates still end up in the history.

Any downsides to this?

**Comment by apeters** [comment]
Maybe the activity stream could filter out the tile create entries?

**Comment by azaroth42** [comment]
Got it, thanks Cyrus! For our current usage, I don't need bulk loading or backing out transactions so I don't think we're blocked in our current hacky workaround, but it would be good to discuss the right solution that allows both to co-exist. Per Alexei's response, having a filter that could distinguish internal tile creation within the resource creation would be great...

https://github.com/archesproject/arches/blob/03b0b1d6211004fd353952a07473ed52652f00ad/arches/app/views/resource.py#L669 

But I don't know how to do that :)

**Comment by apeters** [comment]
@azaroth42 Just to be clear it sounds like it's not simply tile create events that are the issue (because those could easily be filtered with `edittype != "tile create"`).  What it sounds like you want to exclude is tiles created as part of resource creation, correct?  Subsequent tile creation is essentially treated as an `update` to the resource and is a desired entry in the ActivityStream.  Is that right?

**Comment by azaroth42** [comment]
Right!

If this line passed /something/ that could then be filtered on when constructing the list:

https://github.com/archesproject/arches/blob/master/arches/app/models/resource.py#L228 

but rolled together for the transaction / bulk edit usage.

"import tile create" or somesuch?

**Comment by chiatt** [comment]
The 'note' column is unused. We could document the context of the tile creation there.
