### ISSUE TITLE
Create Branch External Resource (E1)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#977]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording External_Resource.E1 available to me to append to a resource model that I may develop.

Applies to resource models: Activity, Actor, Heritage Resource, Heritage Resource Group, Historical Event, Information Resource
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance

**Comment by ryan86** [comment]
Notes
- Cannot be related to an Activity Resource with a BM.PX.is_related_to property.
- Cannot be related to an Actor Resource with a BM.PX.is_related_to property.
- Cannot be related to an Historical Event Resource with a BM.PX.is_related_to property.
- Cannot be related to an Information Resource with a BM.PX.is_related_to property. Perhaps use P67_refers_to instead.

**Comment by ryan86** [comment]
Combined with identifier. Added source type and changed to external identifier type. Now connects to all resources with P1 property.
