### ISSUE TITLE
Concept search not returning concept when labels begin with uppercase letter

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9786]

**Comment by jkemper-pca** [comment]
Hi,
We have been having this issue with our instance ([forum post](https://community.archesproject.org/t/arches-7-4-0-and-rdm-search-not-finding-all-concepts/2079)) and I did a bit of looking into this.
It looks like the analyzer for concepts was changed a few months ago for this field ([commit](https://github.com/archesproject/arches/commit/3d49a1f11d14516d7c9d33bada141dba35bf6758#diff-c89f7409345719c29e4b688b792ab7a1800b9ba2bfde9509f4794c30cafb141cL80)) and this new analyzer **does not** do an analysis with the lowercase value ([ES doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html) comparing the old analyzer ("standard") and new one ("whitespace"))

Hope this helps!
-James, Parks Canada
