### ISSUE TITLE
Create Branch Information Carrier (E84)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#980]
### User Story
As a developer of resource models, I want a CRM-compliant branch for recording Information_Carrier.E84 available to me to append to a resource model that I may develop.

Applies to resource models: Information Resource

#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance

**Comment by ryan86** [comment]
Information Carrier.E84 does not have a businesstable in the v3 gephi graph I was referencing but from the demo site it appears to be of type domain (or in archesv4 'concept')

**Comment by annabelleee** [comment]
Information Carrier.E84 is a semantic node with type of Information Carrier Format Type.E55. I made this change.
