### ISSUE TITLE
Bulk Data Manager, Import Branch Excel, upload hands on validation step (AfS dev/1.0.x, Arches stable/7.4.0)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#9811]
I'm using AfS to better understand and document the Bulk Data Manager (see arches-docs: https://github.com/archesproject/arches-docs/blob/95a5b12367353a1030fc4ebf8fa7ca36b9509242/docs/administering/bulk-data-manager.txt#L42). 

In testing an upload of an Excel workbook with 1 record created for the AfS Dimension branch I ran into a problem. The validation step never completes. The frontend makes repeatly makes requests to the AfS backend as so:

`afs7             | [21/Jul/2023 00:05:53] "GET /etl-manager?action=loadEvent&page=1 HTTP/1.1" 200 4242`

Those requests repeat endlessly (even after 20 minutes or so, for a 2 line Excel import). It seems the backend never finishes the validation step. 

I'm attaching a copy of my Excel workbook with some data that I was hoping to import. 
[Dimension.xlsx](https://github.com/archesproject/arches-for-science-prj/files/12114868/Dimension.xlsx)

**Comment by chiatt** [comment]
This should now be addressed here: https://github.com/archesproject/arches/pull/9812
