### ISSUE TITLE
Create Branch Language (E55)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#982]
### User Story
As a developer of resource models, I want a CRM-compliant branch for recording Language.E55 available to me to append to a resource model that I may develop.

Applies to resource models: Information Resource

#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance

**Comment by ryan86** [comment]
Notes
- In HIP v3 this is E55 but maybe it should be E56?

**Comment by annabelleee** [comment]
I think it should be E56. Has anyone started this branch? I don't see it in the QA.

**Comment by ryan86** [comment]
http://54.183.131.28/graph/20b7896b-9561-11e6-b664-024f9e178154/settings

**Comment by annabelleee** [comment]
I created a LanguageAlt branch which uses this pattern: E33-P72-E56. It would connect to the Info Resource using P106. Thoughts? E56 cannot connect directly to E73.
