### ISSUE TITLE
Term Search Dropdown - 4.1.3 Status Message - Screen reader does not convey the presence of suggested results

### ISSUE THREAD

**Issue by imogenroberts** [archesproject/arches#9823]
As a user reliant on the screen reader to tell me about changes in the page triggered by user input, I expect the screen reader to convey the presence and number of suggested results when I begin to write a valid search term in the search bar.

**Linked work item:** 
#9499 

**Expected Result:**
When the user types two valid characters into the search bar (e.g. 'se'), the screen reader should alert the user of the presence and number of suggested results which have appeared. 

**Actual Result:**
When the user begins typing a valid search term into the search bar and suggested results appear below, the screen reader simply reads out the letters so far typed into the search bar and interprets this as a list of one item, which is misleading for the user.

**Evidence:**

(Use NVDA screen reader to replicate)

**Comment by johnatawnclementawn** [comment]
This issue is dependent on our select2/chosen replacement work

**Comment by apeters** [comment]
@imogenroberts I took a look at the example on this page:
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/
and NVDA didn't seem to list the number of results when typing into the combobox.  Can you confirm?

**Comment by imogenroberts** [comment]
@johnatawnclementawn yes - seems that the user being informed that the list with results on it is expanded is enough to satisfy the criteria. That's a skill issue on my part! Will mark this defect as closed.
