### ISSUE TITLE
Create Branch Measurement Type (E55)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#983]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording data from the old MEASUREMENT_TYPE.E55 branch so it is available to me to append to a resource model that I may develop.

Applies to resource models: Heritage Resource, Heritage Resource Group
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repo

**Comment by ryan86** [comment]
Notes

- Measurement Type.E55 cannot be related to Unit of Measurement.E55 with a P91 property.
- Value of Measurement cannot be of type E60. Property connecting Unit of Measurement.E55 to Value of Measurement.E60 may not be able to be P90.
-

**Comment by annabelleee** [comment]
New Measurement Branch relates to Heritage Resource E18 and Heritage Resource Group E27 via P39i. Top node is now Measurement E16.
