### ISSUE TITLE
Create Branch Modification Event (E11)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#984]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording Modification_Event.E11 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Heritage Resource
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repository

**Comment by ryan86** [comment]
Notes

- Modification Description cannot be of type E62
- Modification Description cannot be connected to Modification Event with a P3 property
- Cannot be related to Heritage Resource E18 with a -P31 property

**Comment by annabelleee** [comment]
Branch relates to Heritage Resource (E18 ) with P12i property. Add Modification Description branch to Modification Event: E11 --P140i--> E13 --P3--> E62
