### ISSUE TITLE
Nodegroups can appear in card tree but not in Graph making them impossible to delete 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9847]
If a user follows the steps described [here](https://community.archesproject.org/t/adding-new-node-published-resource-model-with-instances/2053/5) they will find that there are cards that appear in the card tree and reports, but do not appear in the graph tree. This is a problem because they appear as 'New Node' in reports, and they can't be removed because they are inaccessible from the graph tree. 

The problem is not merely a UI issue. Node and nodegroup tables, records for the New Node's are present. 

We need to find a way to prevent this issue as well as a process for remedying the problem in systems that have these unwanted nodes.

**Comment by jacobtylerwalls** [comment]
I found it easier to reproduce consistently using a different Graph Validation Error (adding a node without a linked ontology). Video below.


https://github.com/archesproject/arches/assets/38668450/b04249da-f6a1-4319-93b8-ded2027ced8a

**Comment by jacobtylerwalls** [comment]
Just reproduced the original issue on 7.3. It's not reproducible on 7.4.

(The video'd issue is a little different. Forgive me!)

Looking into the feasibility of a data migration to clean this up.

**Comment by jacobtylerwalls** [comment]
Fixed in #9853
