### ISSUE TITLE
Create Branch Name (E41)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#985]
### User Story
As a developer of resource models, I want a CRM-compliant branch for recording Name.E41 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Activity, Heritage Resource, Heritage Resource Group, Historical Event

#### Definition of Done
- [x] able to be attached to the parent resource node with correct property
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored on repo

**Comment by ryan86** [comment]
Notes
- Cannot be related to Actor with P1 property. (Name.E1 should probably be Name.E41)
- Cannot be related to Heritage Resource Group with P1 property. (Name.E1 should probably be Name.E41)
- Cannot be related to Historical Event with P1 property. (Name.E1 should probably be Name.E41)
- Cannot be related to Heritage Resource with P1 property. (Name.E1 should probably be Name.E41)

**Comment by annabelleee** [comment]
Changed E1 to E41.
