### ISSUE TITLE
Create Branch Place (E53)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#986]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording Place.E53 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Activity, Actor, Heritage Resource, Heritage Resource Group, Historical Event, Information Resource
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repository

**Comment by ryan86** [comment]
Notes
- Place Site Location E53 cannot be related to Place E53 with the P87 property
- Description of Location cannot be of class E62
- Administrative Subdivision E48 cannot be related to Place E53 with the P45 property
- Place Cadastral Reference E53 cannot be related to Place E52 with the P87 property
- Cannot be appended to Actor E39 with the P53 property

**Comment by annabelleee** [comment]
Relates to Activity E7 with P7
Relates to Heritage Resource E18 with P53
Relates to Heritage Resource Group E27 with P89
Relates to Actor E39 with P74 (this restricts the place to former and current residences, which can be as broad or narrow)
Relates to Historical Event E5 with P7
Relates to Information Resource E73 with P67
