### ISSUE TITLE
Adding two nodes to a published graph can raise a 500

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#9864]
Similar to #9858 but with a different backend error, attempting to edit a published graph by adding multiple nodes off the root can raise a 500.

### To reproduce ###
1. Create a new graph with an ontology type of "Linked Art".
2. Create a child node with a data-collecting type (and a valid ontology).
3. Publish the graph.
4. Create an instance.
5. Open the graph designer.
6. While the graph is in a published state, add a node off the root. Don't select the child node.
7. Repeat step 6.

### Result ###
```py
afs7             |   File "/web_root/arches/arches/app/views/graph.py", line 394, in post
afs7             |     graph.save()
afs7             |   File "/web_root/arches/arches/app/models/graph.py", line 475, in save
afs7             |     self.validate()
afs7             |   File "/web_root/arches/arches/app/models/graph.py", line 1625, in validate
afs7             |     self.check_if_resource_is_editable()
afs7             |   File "/web_root/arches/arches/app/models/graph.py", line 1527, in check_if_resource_is_editable
afs7             |     self.nodes[db_node.nodeid],
afs7             | KeyError: UUID('06f23c44-3183-11ee-bc84-0242ac120007')
afs7             | [02/Aug/2023 22:22:13] "POST /graph/300b5716-a288-4c38-b5c8-6d2f26d7194e/append_node HTTP/1.1" 500 132613
```

### Version ###
Arches 7.4
Arches for Science 1.0 dev

### Video ###

https://github.com/archesproject/arches/assets/38668450/998564ac-9ba2-46e2-b6d9-f173495faa0a

**Comment by chiatt** [comment]
It's nice that a user can make changes to a graph and then unpublish later before actually saving them. However, it would be much safer to simply disable the interface of a published graph.
