### ISSUE TITLE
Prevent all datatype changes in Graph Designer

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#9875]
Currently we allow some datatype changes (eg concept -> concept-list) but disallow others (eg string -> number). This logic is based entirely on an exception when attempting to update the ES index. 

Ideally with editable_future_graphs we should update the function to handle all datatype changes, but in the meantime we should ensure that this logic is enforced for every datatype change.

**Comment by chiatt** [comment]
I think this is a good change because I don't believe that we clean up configs when a user switches between datatypes. It also reduces confusion when a user discovers that they can switch datatypes in some cases, but not in others.
