### ISSUE TITLE
Create Branch Production (E12)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#988]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording Production.E12 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Heritage Resource, Heritage Resource Group

We may choose to break this branch into sub-branches for usability.
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repo

**Comment by ryan86** [comment]
This the Production branch from v3 has been split into two seperate branches in v4.  One for "Component" and another for "Phase Type".  Both can connect to heritage resource and heritage group respectively.  Component has been significantly simplified from the v3 setup.

**Comment by ryan86** [comment]
Phase type still needs some work to get the node names more descriptive and unique.

**Comment by annabelleee** [comment]
Phase type was split into Heritage Resource Phase Type and Heritage Resource Group Phase Type.
