### ISSUE TITLE
Create Branch Resource Creation Event (E12)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#990]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording Resource_Creation_Event.E12 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Information Resource
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance

**Comment by ryan86** [comment]
Notes
- 'Date of Update.E50' cannot be related to 'Resource Update Event.E65' via a -P71 property.

**Comment by ryan86** [comment]
Removed E39s (Creator and Contributor) these should be their own resources related to the information resource with types 'created by'/'contributed to'. Removed date of update because it is not part of the creation event.
