### ISSUE TITLE
Refactor inheritance pattern used by ETL modules

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9900]
The ETL module inheritance pattern needs to be refactored to allow developers to easily leverage existing code in the development of new etl modules. Here are some thoughts for possible changes, but a better pattern might emerge once the refactoring is underway: 

1. The `base_import_module` is used in the `branch_excel_importer` and `import_single_csv`. This makes sense because they are both importers, but it is also used in `base_data_editor`. 
If the base_import_module is generic enough, it may be sufficient to simply rename it as `base.py`.  Then perhaps a `base_importer`, `base_exporter`, and `base_editor` could inherit from it. 

3. `branch_excel_exporter` and `tile_excel_importer` both inherit from `branch_excel_importer`. I think this is because both excel formats are using excel related methods available in `branch_excel_importer`. These excel methods could be moved into a separate python module to be shared by importers and exporters. 

This work should be done against the `bulk_data_manager_improvements` branch

**Comment by jacobtylerwalls** [comment]
Fixed in #9911
