### ISSUE TITLE
Top Nav Buttons - 1.3.1 Info and Relationships - Labels for Notifications and Help buttons are repeated upon selection

### ISSUE THREAD

**Issue by imogenroberts** [archesproject/arches#9902]
As a user reliant on the screen reader, I expect an accurate interpretation via alt text of the buttons and actions displayed visually on the page.

**Linked Work Item:**
#8039 

**Expected Result:**
When the user expands the Notifications and Help buttons, the screen reader should read out the accessible (alt-text) name of the button only once.

**Actual Result:**
However, upon selecting either Notifications or Help, the screen reader reads out the name of the button twice. This could be confusing for visually impaired users, who might believe they have pressed the button twice, or that there are two buttons.

**Evidence:**

![Image](https://github.com/archesproject/arches/assets/77161085/e946ad33-fd43-4d53-850c-3683e0fee17e)

**Comment by johnatawnclementawn** [comment]
After a quick look at this, I hypothesize that either the focus shifting logic in the `handleEsc` method is being fired twice, or focus shifting logic is doubled up in `openHelp`, but the solution wasn't immediately clear, so this may take a little more digging

**Comment by imogenroberts** [comment]
RETEST: The Top Nav Help and Notifications buttons are read out a single time by the screen reader on focus, and on input the screen reader also asks if the user wants to close the toggle a single time only. The video attached uses the on-screen keyboard, which (for some reason) does not prompt the screen reader to read out that the toggles are expanded. However, this is not a problem as the real keyboard does prompt this behaviour.

**Evidence:**

https://github.com/archesproject/arches/assets/77161085/6fb4c7bd-88dd-4ec2-bdcc-37ce13a81b5f
