### ISSUE TITLE
Create Branch Thumbnail.E62

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#995]
### User Story
As a developer of resource models, I want a CRM-compliant branch for recording Thumbnail.E62 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Information Resource

#### Definition of Done
- [ ] able to be attached to the parent resource node
- [ ] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [ ] check that edges have appropriate properties
- [ ] proper node data types
- [ ] branch stored on QA instance

**Comment by dwuthrich** [comment]
This branch won't be required with the file upload widget
