### ISSUE TITLE
Language Filter - 3.3.2 Labels or Instructions - None of the list items have an accessible name

### ISSUE THREAD

**Issue by imogenroberts** [archesproject/arches#9957]
As a user reliant on the screen reader to interpret list items, I expect all list items to have accessible names which can be correctly interpreted by the screen reader to match the text in the list.

**Linked work item:** 
#9521 

**Expected Result:**
Every item in a list must have an accessible label so that screen readers can correctly interpret list items.

**Actual Result:**
Every item in the language dropdown is read out by the screen reader as 'blank', meaning that users with vision difficulties will have no way of knowing which language they are choosing.

**Evidence:**

Use NVDA to replicate:

![Image](https://github.com/archesproject/arches/assets/77161085/50863858-6d68-456e-acbf-c252a3255122)

**Comment by johnatawnclementawn** [comment]
This issue is dependent on our select2/chosen replacement work.

Each item is dynamically created in encapsulated chosen code, which prevents us from directly adding aria-labels to the items

**Comment by imogenroberts** [comment]
RETEST: All items in the Language dropdown combobox have an accessible name and are also oriented within the list (e.g. 'French (fr), 4 of 10').

**Evidence:**


https://github.com/archesproject/arches/assets/77161085/33a5711f-2b54-4f0f-b205-c97573b83e13
