### ISSUE TITLE
Develop primary identifier function for resources

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#997]
To support this we need to be able to sort business data (tiles).
- add sort order to tile instance table because:
  - creates an ability to build business id from n cardinality nodes based on first instance of a node
  - stabilizes the sorting in display of tiles in reports and forms
- add ability to define function for building a business id within resource model definition.  
  - biz id limited to nodes within a single group.
  - user configures concatenation of nodes within group per tile, 
  - user configures number of tiles to return (based on sort order), and concatenation of tile instances
  - return of the function (probably) not saved in within a node in the resource model, but is saved in ES

**Comment by dwuthrich** [comment]
Primary Name Function applies the same name to all resource instances, does not resolve UUID of concepts to labels.

see: http://recordit.co/6ChFuZeeKE

**Comment by apeters** [comment]
I'd like to close this ticket as completing the basics of the primary name function.
I've created 2 tickets related to the bugs notes
 - repeated primary names (#1307)
 - resolution of concept UUIDs (#1341)

**Comment by dwuthrich** [comment]
closed in favor of #1307 and #1341
