### ISSUE TITLE
Export Branch function exports the entire Resource Model if the Resource Model is published

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#9971]
If a Resource Model is in a Published state, when selecting a Node in the Graph Designer and clicking the Export Branch button, the entire Resource Model is exported as a Branch. The Branch name in the list of Branches is the name of the Node exported, but the content of that Branch is the entire Resource Model with a root node name that matches the source Resource Model root node.

The top level Card names in the Cards tab within the Branch are all have a title matching the exported Node name.

No observed exceptions are thrown in the browser nor from the server.

Branch: dev/7.4.x

**Comment by bferguso** [comment]
Closing in favour of #10348

**Comment by jacobtylerwalls** [comment]
Thanks, Brett, sorry I missed it!
